### ISSUE TITLE
Clients should support `jaeger-baggage` header for ad-hoc baggage

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1010]
Go client supports it.

* [x] Python https://github.com/jaegertracing/jaeger-client-python/pull/207
* [x] Java https://github.com/jaegertracing/jaeger-client-java/pull/525
* [ ] Node.js
* [ ] C#
* [ ] C++
* [ ] C

**Comment by verma-varsha** [comment]
Hi! I wanted to know if this task is done for the nodejs client or not

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients.
