### ISSUE TITLE
Unable to find some services.

### ISSUE THREAD

**Issue by readwritelearn** [jaegertracing/jaeger#1021]
Hi all : 
        I ' m a new to istio and jaeger.  I have installed the istio(1.0) on minikube and deployed both bookinfo and helloworld sample. However, I can only find the helloworld service on jaeger. Can someone tell me the reason or where should I check.

![image](https://user-images.githubusercontent.com/41249226/44617033-5f26c980-a88e-11e8-96e6-50f0dc4c115c.png)
![image](https://user-images.githubusercontent.com/41249226/44617035-6cdc4f00-a88e-11e8-9cd0-b248fc48ed0c.png)

If you guys need more information please let me know.
Cheers
RWL

**Comment by jpkrohling** [comment]
cc @objectiser

**Comment by objectiser** [comment]
@readwritelearn Could you list the pods? Did you use auto or manual injections for the bookinfo example?

**Comment by xcl001987** [comment]
I had the same problem， and i used auto injections for the bookinfo example.  
I deployed jaeger in the following steps： 
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/production-elasticsearch/configmap.yml
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/production-elasticsearch/elasticsearch.yml
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/jaeger-production-template.yml
![image](https://user-images.githubusercontent.com/3435209/49360496-4a22c780-f714-11e8-81fa-813bf481d70f.png)
![image](https://user-images.githubusercontent.com/3435209/49360509-573fb680-f714-11e8-97f1-15b6b04fec23.png)

**Comment by objectiser** [comment]
Closing pending more information.
