### ISSUE TITLE
agent: tchannel timeout should be configurable

### ISSUE THREAD

**Issue by gouthamve** [jaegertracing/jaeger#1026]
## Requirement - what kind of business use case are you trying to solve?

We run a central jaeger collector and all our different clusters send spans over stunnel to that central collector. Now this means sometimes there are latency blips and it takes more than a second. 

## Problem - what in Jaeger blocks you from solving the requirement?

Currently the timeout is hardcoded to `1s` here: https://github.com/jaegertracing/jaeger/blob/master/cmd/agent/app/reporter/tchannel/reporter.go#L123

## Proposal - what do you suggest to solve the problem or improve the existing situation?

It should ideally be configurable via a flag.

**Comment by gouthamve** [comment]
Umm, @black-adder I found this: https://github.com/jaegertracing/jaeger/issues/927 after opening the issue. I think this is a sub issue in that.

As mentioned there, I'm not sure this is trivial to tackle as it involves some refactoring and without clear instructions and context, new comers don't know what to refactor :) Having said that, if you're open to making just this timeout a flag, I'll take a stab this weekend if no-one else does by then.

**Comment by black-adder** [comment]
Good find; on paper looked so innocently simple.

**Comment by gouthamve** [comment]
Closed in #1034
