### ISSUE TITLE
Crossdock and Travis are buggy

### ISSUE THREAD

**Issue by isaachier** [jaegertracing/jaeger#1028]
## Requirement - what kind of business use case are you trying to solve?

~~Ever since #815, the crossdock tests have been broken.~~ This should have been caught immediately, but an error-handling issues in `.travis.yml` allowed the failed test to be ignored.

## Problem - what in Jaeger blocks you from solving the requirement?

The existing crossdock config and Travis CI setup have multiple issues:

- DNS config is not set up using `dns_search: .`, which sporadically causes errors when the a service never initializes, when in fact it has initialized, but the DNS config fails.
- ~~Command format (from #815) does not use the executable as the first argument, which is invalid.~~
- Using locally tagged images without specifying `:latest` causes build failures associated with outdated versions of the image.
- When using `if`/`then` in `.travis.yml`, use `test || exit 1` to guarantee test succeeds. Otherwise, the `then` command succeeds regardless of exit code from `test`.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Fix the above issues.

**Comment by isaachier** [comment]
OK I found that the changes in #815 are actually correct. I still see some spurious errors now and then about a missing executable. I believe this is more of a build issue than a Docker syntax issue. We may not be building the images and/or checking that the binary exists. Either way, keeping issue for other docker-compose/Travis issues I saw.

**Comment by isaachier** [comment]
Turns out MacBook is buggy, not tooling. My bad here.

**Comment by yurishkuro** [comment]
Please document your findings

**Comment by isaachier** [comment]
OK here it goes:

- DNS lookup is a real issue for me, but not widespread enough to warrant the fix I proposed.
- bash handles `if`/`then` as you would expect. Proof: `(if true; then cat $PWD; fi) || echo failure` => `failure`.
- Command syntax is correct to drop executable path. Entrypoint is used and arguments are appended to the entrypoint.
- `make build-crossdock` seems to work on Travis, just not locally. There is a real issue with timeouts that can easily be resolved, but I'd like to post a new issue for that. See documentation regarding that issue here: https://docs.docker.com/compose/startup-order.
