### ISSUE TITLE
Allow configuration of jaeger client in the query service

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger#1044]
## Requirement - what kind of business use case are you trying to solve?
The jaeger query service allows for tracing the query service itself. In the all-in-one container, the [default](https://github.com/jaegertracing/jaeger/blob/master/cmd/query/main.go#L83) initialization of the client works since the agent/collector reside on localhost. However, when the query service is deployed individually, the collector and agent are not guaranteed to be running locally or maybe running on non-default ports depending on the setup.

## Problem - what in Jaeger blocks you from solving the requirement?
The query service exposes no flags or environment variables to configure the tracer in the query service.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
The golang tracer allows configuration via [environment variables](https://github.com/jaegertracing/jaeger-client-go/blob/252d853b2a4f3cfc98bb89c3a8bb3d3aa50ed4d6/config/config_env.go#L53). I think all we'd have to do is to replace [New](https://github.com/jaegertracing/jaeger/blob/master/cmd/query/main.go#L89) with [FromEnv](https://github.com/jaegertracing/jaeger-client-go/blob/252d853b2a4f3cfc98bb89c3a8bb3d3aa50ed4d6/config/config_env.go#L53).

**Comment by trtg** [comment]
@black-adder  is it possible to disable tracing of jaeger-query? It results in a lot of additional traffic to the collectors and to our cassandra backend and looking at tons of "Collector::submitBatches" spans is not very informative.

**Comment by jpkrohling** [comment]
@trtg , once this issue here is fixed, you should be able to export `JAEGER_DISABLED` to the Query process and have tracing disabled.

**Comment by cosmologist10** [comment]
Hi! I want to work on this issue.

**Comment by subashiniganesh** [comment]
Hello @jpkrohling ,

I am Subashini, an aspiring Outreachy candidate. As I came to know about outreachy very recently, do you still have space for new applicants? May I still attempt solving issues?

@cosmologist10, If you're caught up doing something else, May I work on this issue?

Thanks.

**Comment by jpkrohling** [comment]
Sorry for the late response, @subashiniganesh, but I was out last week. You are certainly welcome to submit a patch by the program's deadline, which happens to be tomorrow. It's a tight deadline, but might be doable if you are experienced in Golang.

**Comment by subashiniganesh** [comment]
Ah!! Thanks for such a positive note. I submitted a PR. It was such an exciting experience. Shall I make a application and continue contributing?

**Comment by jpkrohling** [comment]
Sure, but hurry, it might be closing soon (if it's not closed already)!!!

**Comment by subashiniganesh** [comment]
Thanks @jpkrohling . I submitted the final application. And I am so glad to note that until Nov 16, we are allowed to make and record code contributions. Let me please search and find an issue and continue contributing. Please let me know if you have any suggestions.

**Comment by pavolloffay** [comment]
After this is done we should add configuration to docker compose file pointing tracer to jaeger agent.

**Comment by trtg** [comment]
@jpkrohling any progress on being  able to set JAEGER_DISABLED on the query process yet?

**Comment by Marusyk** [comment]
still no implemented???

**Comment by jpkrohling** [comment]
@Marusyk : looks like jaegertracing/jaeger-client-go#436 (which was a pre-requisite) has been merged. As you need this feature, do you want to give a shot at this one here?

**Comment by MichaelErmer** [comment]
would be cool to have an option to provide the agent host+port as cmd arg or env variable +1

**Comment by jpkrohling** [comment]
@MichaelErmer would you like to give it a try?

**Comment by yurishkuro** [comment]
we need to release a new Go client version, which is currently blocked by a couple of PRs

**Comment by jpkrohling** [comment]
The development of this feature on this side can happen in parallel, no?

**Comment by yurishkuro** [comment]
yes it can, by temporarily depending on the master branch of the client

**Comment by pavolloffay** [comment]
Done in https://github.com/jaegertracing/jaeger/pull/1919
