### ISSUE TITLE
Unnecessary restriction on tags + min-duration queries

### ISSUE THREAD

**Issue by liukai2012** [jaegertracing/jaeger#1047]
In query_parse.go:

if minDuration != 0 && len(tags) > 0 {
		// This is because querying for this almost certainly returns no results due to intersections
		return nil, errCannotQueryTagAndDuration
}

I do not understand why minDuration and tags do not appear when query tracing.

Anyone help me?

**Comment by yurishkuro** [comment]
please see #166

**Comment by cspurk** [comment]
@yurishkuro: #166 is about limitations of the _Cassandra_ storage backend. I wonder why this doesn’t work for _Elastisearch_ either. Is that expected?

**Comment by bobrik** [comment]
@yurishkuro can we move this into individual backends? I'd love to query for both duration and tags with elasticsearch.

**Comment by yurishkuro** [comment]
Yes, this type of validation should be scoped to Cassandra backend only. PRs welcome.

**Comment by bobrik** [comment]
@yurishkuro, there's already a check for this in Cassandra spanstore:

* https://github.com/jaegertracing/jaeger/blob/f9702c4b03/plugin/storage/cassandra/spanstore/reader.go#L227-L229

Is it safe to just remove the check in query parser then?

**Comment by yurishkuro** [comment]
yes, let's do it
