### ISSUE TITLE
jaeger-collector signal SIGSEGV

### ISSUE THREAD

**Issue by billowqiu** [jaegertracing/jaeger#1056]
## Requirement - what kind of business use case are you trying to solve?

jaeger-collector crash

## Problem - what in Jaeger blocks you from solving the requirement?

jaeger-collector crash，the panic message：
`
{"level":"error","ts":1535587411.3183763,"caller":"app/span_processor.go:102","msg":"Failed to save span","error":"Failed to create index: elastic: Error 503 (Service Unavailable): failed to process cluster event (create-index [jaeger-span-2018-08-30], cause [api]) within 30s [type=process_cluster_event_timeout_exception]","errorVerbose":"elastic: Error 503 (Service Unavailable): failed to process cluster event (create-index [jaeger-span-2018-08-30], cause [api]) within 30s [type=process_cluster_event_timeout_exception]\nFailed to create index\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).logError\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:201\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).createIndex\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:162\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:129\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:101\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:88\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:56\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65\nruntime.goexit\n\t/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2361","stacktrace":"github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:102\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:88\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:56\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb5fb97]

goroutine 98 [running]:
github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.(*BulkResponse).Failed(0x0, 0x105a780, 0xc42032a320, 0x453de22e5)
	/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/bulk.go:369 +0x37
github.com/jaegertracing/jaeger/pkg/es/config.(*Configuration).NewClient.func2(0x697ff, 0xc420d78180, 0x8, 0x8, 0x0, 0x105a780, 0xc42032a320)
	/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/pkg/es/config/config.go:82 +0x168
github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.(*bulkWorker).commit(0xc420418300, 0x10673c0, 0xc4200340c0, 0x0, 0xc4201d0000)
	/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:506 +0x41f
github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.(*bulkWorker).work(0xc420418300, 0x10673c0, 0xc4200340c0)
	/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:455 +0x298
created by github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.(*BulkProcessor).Start
	/Users/yurishkuro/golang/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:299 +0x198
`

**Comment by yurishkuro** [comment]
wtf why is my name in the stacktrace 😄 

the error says `"Failed to create index: elastic: Error 503 (Service Unavailable): failed to process cluster event (create-index [jaeger-span-2018-08-30], cause [api])"`. SEGSEGV looks like a red herring.

**Comment by yurishkuro** [comment]
it's probably because I had to do a manual release, which was brand new and Travis failed. No harm.

**Comment by billowqiu** [comment]
what cause the "panic: runtime error"， i think the "Failed to create index" do not cause this, because the message appear many times early.

**Comment by yurishkuro** [comment]
Good find. Do you want you post a fix?

**Comment by billowqiu** [comment]
ok，i will give a pr.

**Comment by yurishkuro** [comment]
Very old issue, no similar reports, so closing.
