### ISSUE TITLE
tag_index and duration_index's GC is not work fine

### ISSUE THREAD

**Issue by xmm1989218** [jaegertracing/jaeger#1057]
I use scylladb as storage (also test with cassandra simplely), tag_index and duration_index's sstable is not GCd fine. the expired sstables is not GCd. I add a dummy dimension to tag_index nad duration_index's schema. the problem go away. is there any better way to fix it?

http://user.cassandra.apache.narkive.com/MTHPUtGG/ttls-on-tables-with-only-primary-keys

**Comment by yurishkuro** [comment]
sounds like we should add a dummy field to these tables

**Comment by yurishkuro** [comment]
actually, I don't think we're seeing this issue on C 3.9

**Comment by yurishkuro** [comment]
Have you found the reason why you were seeing this?

**Comment by isaachier** [comment]
@xmm198218, could you explain what you saw when texting with Cassandra instead of ScyllaDB? Also, how does the link relate to this issue?

**Comment by xmm1989218** [comment]
@isaachier it is scylladb's bug, someone has been work on it
