### ISSUE TITLE
Deprecate custom retry logic

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#1085]
## Requirement - what kind of business use case are you trying to solve?
The ingester uses custom retry logic here to retry failing requests
https://github.com/jaegertracing/jaeger/blob/933efb3a52b0acd513a11e1d6711f3cf6578d8e0/cmd/ingester/app/processor/decorator/retry.go#L92-L94

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Deprecate this retry logic, and rely instead on the retries offered by the Cassandra and Kafka drivers. Retrying at the driver level is better because the driver has implementation specifics and can be smarter about retries. (For e.g. the Cassandra driver can retry on a different connection). These sort of storage specific decisions cannot be taken at the retry processor's abstraction level. 

## Any open questions to address
Are all queries easily retryable from a point of view of the Cassandra and Kafka drivers?
Can we get retry metrics from the driver and report them?

**Comment by pavolloffay** [comment]
@vprithvi do you use retry in c* storage?

If we want to use retry mechanism used in drivers we can close https://github.com/jaegertracing/jaeger/issues/302. I don't think that ES client provides any retry capability.

**Comment by vprithvi** [comment]
I don't think we configure the driver retries currently, but I think we should. I noticed that the ES client had a [https://godoc.org/github.com/olivere/elastic#Retry](Retry) function in it's docs, but I haven't looked deeper into it. 
`sarama` and `gocql` provide out of the box retries
