### ISSUE TITLE
Consider UPX to reduce binary size

### ISSUE THREAD

**Issue by ledor473** [jaegertracing/jaeger#1089]
## Requirement - what kind of business use case are you trying to solve?
Not really a requirement, but smaller binaries are always welcome

## Problem - what in Jaeger blocks you from solving the requirement?
None

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Internally, we use [UPX](https://upx.github.io/) to reduce the size of the Jaeger binaries.
Here's the output:
```
$ upx cmd/agent/agent-$GOOS
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  21583254 ->   6217556   28.81%  linux/ElfAMD   agent-linux

Packed 1 file.
```
```
$ upx cmd/collector/collector-$GOOS
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  32702099 ->   8746724   26.75%  linux/ElfAMD   collector-linux
```

**Comment by yurishkuro** [comment]
The license for upx looks suspicious.

https://github.com/upx/upx/blob/master/LICENSE

**Comment by yurishkuro** [comment]
Checked with Uber legal. We should be ok to use it, assuming:

* We must not modify UPX in any way, or use a version of UPX that has been modified in any way to compress the binaries.
* We must not modify the stubs embedded by UPX in each UPX-compressed program, and the stub can only be used for normal decompression purposes. 
* We also must not redistribute UPX, in it's unmodified or modified form.

It would be good to see if any other oss projects are using this tool.

**Comment by jpkrohling** [comment]
> Internally, we use UPX to reduce the size of the Jaeger binaries.

Just out of curiosity, how many agents/collectors do you have? I think it's impressive to have a binary going from 21MB to 6MB almost for free and I think it adds value for a scenario like agents as sidecars, where there would potentially be hundreds of agents, but I'm not sure I see that much value for the other components.

**Comment by ledor473** [comment]
@jpkrohling you are right that I mostly added it to reduce the size of the Agent. It was after reading some blog post probably and I wanted to try it out to see how it would react. Recently, I was updating our CI and added it to the Collector as well.

As for other projects, I couldn't find much usage. There was a pull request to Kubernetes at some point that highlighted some of the downsides of using UPX: 
https://github.com/kubernetes/kubernetes/pull/28265#issuecomment-230124309

**Comment by ledor473** [comment]
Closing as I doubt it's needed and because of the downsides listed in the Kubernetes issue
