### ISSUE TITLE
Ingester default healthcheck port

### ISSUE THREAD

**Issue by ledor473** [jaegertracing/jaeger#1093]
## Requirement - what kind of business use case are you trying to solve?
Run the jaeger-ingester with sane defaults easily

## Problem - what in Jaeger blocks you from solving the requirement?
```
$ go run cmd/ingester/main.go                                                                                                                                                                      ingester-binaries
{"level":"fatal","ts":1538145911.902807,"caller":"ingester/main.go:66","msg":"Could not start the health check server.","error":"port not specified","errorVerbose":"port not specified\ngithub.com/jaegertracing/jaeger/cmd/flags.(*SharedFlags).NewHealthCheck\n\t/Users/ledor473/go/src/github.com/jaegertracing/jaeger/cmd/flags/flags.go:110\nmain.main.func1\n\t/Users/ledor473/go/src/github.com/jaegertracing/jaeger/cmd/ingester/main.go:64\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/Users/ledor473/go/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:698\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/ledor473/go/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:783\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/Users/ledor473/go/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:736\nmain.main\n\t/Users/ledor473/go/src/github.com/jaegertracing/jaeger/cmd/ingester/main.go:124\nruntime.main\n\t/Users/ledor473/bin/go/src/runtime/proc.go:201\nruntime.goexit\n\t/Users/ledor473/bin/go/src/runtime/asm_amd64.s:1340","stacktrace":"main.main.func1\n\t/Users/ledor473/go/src/github.com/jaegertracing/jaeger/cmd/ingester/main.go:66\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/Users/ledor473/go/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:698\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/ledor473/go/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:783\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/Users/ledor473/go/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:736\nmain.main\n\t/Users/ledor473/go/src/github.com/jaegertracing/jaeger/cmd/ingester/main.go:124\nruntime.main\n\t/Users/ledor473/bin/go/src/runtime/proc.go:201"}
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Add a default healthcheck HTTP port just like Collector and Query

## Any open questions to address
- Which port should we use?

**Comment by jpkrohling** [comment]
> Which port should we use?

Is it, or will it be, included in the `all-in-one`? If so, it could be the health-check port that is used there +1 (14270 then)

**Comment by jpkrohling** [comment]
In time, I'm not implying that the all-in-one would have two health-check ports if the ingester gets added :)

**Comment by ledor473** [comment]
Here's the various default ports:
```
CollectorDefaultHealthCheckHTTPPort = 14269
QueryDefaultHealthCheckHTTPPort = 16687
```

**Comment by jpkrohling** [comment]
I think the `all-in-one` should include everything, turning on the required components on demand

**Comment by vprithvi** [comment]
I see - I agree with what you mentioned earlier then!

**Comment by yurishkuro** [comment]
> As a newcomer, I would expect the "all-in-one" to include "all" components, including the ingester.

eh, I am not convinced of that. The point of all-in-one is to be, well, all in one. Even though we support external storage, it does not break the notion that the rest of Jaeger components are "all in one". But with Kafka ingester it kind of breaks down, since you need _another_ component writing to Kafka. And while it could be the same process both writing and reading Kafka, we're getting into a weird territory.

Another objection is that currently the code is not so well structured as to make the all-in-one easy to maintain with more and more components. It's main is huge compared to others. Unless there's a very strong reason for including ingester there I would rather not do it.

Anyway, I think the question about the health port is answered?  14270?  (I don't really care)
