### ISSUE TITLE
What belongs in all-in-one and what doesn't

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#1095]
Currently, it's very clear what the all-in-one contains: everything that one needs to run a Jaeger backend is included in the all-on-one. With the addition of the `ingester` component, we have now a not-so-clear definition/boundary.

Starting a discussion from where we left it of: 

@jpkrohling said:
> As a newcomer, I would expect the "all-in-one" to include "all" components, including the ingester.

@yurishkuro said:
> eh, I am not convinced of that. The point of all-in-one is to be, well, all in one. Even though we support external storage, it does not break the notion that the rest of Jaeger components are "all in one". But with Kafka ingester it kind of breaks down, since you need another component writing to Kafka. And while it could be the same process both writing and reading Kafka, we're getting into a weird territory.
> 
> Another objection is that currently the code is not so well structured as to make the all-in-one easy to maintain with more and more components. It's main is huge compared to others. Unless there's a very strong reason for including ingester there I would rather not do it.

**Comment by jpkrohling** [comment]
> But with Kafka ingester it kind of breaks down, since you need another component writing to Kafka

Someone who needs the ingester has this other component already. In that situation, it would then be required to use two Jaeger components: the ingester and the `all-in-one`. I'm not sure the ingester belongs in the main binary that we are calling `all-in-one`, but from the outside, I would certainly expect all Jaeger components to be in a binary called `all-in-one`. If we had a different name, we would probably not be discussing this :)

> Another objection is that currently the code is not so well structured as to make the all-in-one easy to maintain with more and more components. 

My question is more about the definition than technical. I don't think this has a priority, unless people ask for it. But I think we do need a general rule, in case we add further components.

**Comment by yurishkuro** [comment]
> If we had a different name, we would probably not be discussing this :)

Naming is hard. Maybe we can rename it to "playground", to make the intention more obvious (maybe not the actual binary, but at least spell it out in the documentation / `main()`). It was never intended as a production-grade component, but as a quick way to spin up a single process for local testing / demos.

**Comment by pavolloffay** [comment]
I am closing this, the new all-in-one based on OTEL will be able to run all components.
