### ISSUE TITLE
gosec fails on crossdock

### ISSUE THREAD

**Issue by isaachier** [jaegertracing/jaeger#1097]
## Requirement - what kind of business use case are you trying to solve?

Cannot submit new pull requests to GitHub.

## Problem - what in Jaeger blocks you from solving the requirement?

gosec fails on crossdock source code. Causes Travis CI errors (https://travis-ci.org/jaegertracing/jaeger/jobs/434740163).

Example:

```
[/Users/isaachier/gocode/src/github.com/jaegertracing/jaeger/crossdock/main.go:92] - G107: Potential HTTP request made with variable url (Confidence: MEDIUM, Severity: MEDIUM)
  > http.Get(healthURL)
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Instead of excluding error G107, which should be fine in normal Jaeger source code, we should exclude the crossdock directory from unnecessary linting.

**Comment by bhavin192** [comment]
I think this can be closed as we have excluded `G104` and `G107` for gosec. It was added by #1048

https://github.com/jaegertracing/jaeger/blob/3c788199116f507dc8ebf628d38d96fc92225302/Makefile#L31
