### ISSUE TITLE
Consider HAR format

### ISSUE THREAD

**Issue by neopaf** [jaegertracing/jaeger#1102]
## Requirement - what kind of business use case are you trying to solve?

Traces 
* sent by email
* used in offline environments
* stored to long-term archive
* attached to tracker software (I know about links. but they are not very good long-term)
* analysed with some 3rd party software (would allow emerging of such)
* represented in a filtered way
* auto-converted to tests

## Problem - what in Jaeger blocks you from solving the requirement?

Currently traces go to DB and there is API, to extract them, but in proprietary format.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Suggest to consider adding a button in UI to export it in HAR format, which seems flexible enough
http://www.softwareishard.com/blog/har-12-spec/

And has lots of viewers.
Which could be base for analytic software.

**Comment by yurishkuro** [comment]
We have canonical thrift and protobuf format, will have canonical json in the future. What value does HAR provide over those?

**Comment by neopaf** [comment]
Yuri,
point is what we can do with what we export.
If there is a way to view a "canned trace" in any form, I think, people would be happier.
Found #214, sounds very good for me.
But that somewhat limits ways for people to view things.

HAR is also JSON, but there are several viewers for it, example:
https://chrome.google.com/webstore/detail/http-archive-viewer/ebbdbdmhegaoooipfnjikefdpeoaidml

#706... maybe we could use HAR as a base for our JSON general format?

Also my point is that if there is somewhat known JSON trace-related format, maybe consider that as a base?
https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/HAR/Overview.html has custom fields to store our stuff.

**Comment by neopaf** [comment]
In UI I've found only JSON. Missing something? Thrift and ProtoBuf, where are they?
(пользуясь случаем, спасибо за замечательный инструмент)

**Comment by yurishkuro** [comment]
I believe a combination of #706 and https://github.com/jaegertracing/jaeger-ui/issues/214 is sufficient to address all the scenarios you listed (except for the last two, I am not sure what those mean).

>  спасибо за замечательный инструмент

Спасибо за комплимент.

**Comment by neopaf** [comment]
got it. hoping for those then.
