### ISSUE TITLE
ES integration test is flakey

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#1108]
## Requirement - what kind of business use case are you trying to solve?
Have tests be indicative of real problems

## Problem - what in Jaeger blocks you from solving the requirement?
```
=== RUN   TestElasticsearchStorage/GetDependencies
--- FAIL: TestElasticsearchStorage (89.25s)
    --- FAIL: TestElasticsearchStorage/GetTrace (4.21s)
        integration_test.go:100: Waiting for storage backend to update documents, iteration 1 out of 30
. to update documents, iteration 30 out of 30
        integration_test.go:181: No trace with that ID found
        integration_test.go:181: No trace with that ID found
        <autogenerated>:1: 
            	Error Trace:	integration_test.go:185
            	            				integration_test.go:378
            	Error:      	Should be true
            	Test:       	TestElasticsearchStorage/GetTrace
        <autogenerated>:1: 
            	Error Trace:	domain_trace_compare_test.go:53
            	            				integration_test.go:186
            	            				integration_test.go:378
            	Error:      	Expected value not to be nil.
            	Test:       	TestElasticsearchStorage/GetTrace
    --- FAIL: TestElasticsearchStorage/GetLargeSpans (78.75s)
        integration_test.go:132: Testing Large Trace over 10K ...
        integration_test.go:100: Waiting for storage backend to update documents, iteration 1 out of 30
.
        integration_test.go:100: Waiting for storage backend to update documents, iteration 30 out of 30
        <autogenerated>:1: 
            	Error Trace:	integration_test.go:143
            	            				integration_test.go:379
            	Error:      	Should be true
            	Test:       	TestElasticsearchStorage/GetLargeSpans
        <autogenerated>:1: 
            	Error Trace:	domain_trace_compare_test.go:53
            	            				integration_test.go:144
            	            				integration_test.go:379
            	Error:      	Expected value not to be nil.
            	Test:       	TestElasticsearchStorage/GetLargeSpans
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

TBD

**Comment by yurishkuro** [comment]
this damned test keeps failing. Has something changed recently? Wasn't a problem until a few weeks ago,.

**Comment by vprithvi** [comment]
Haven't investigated deeply - but I'm curious whether this could be a timezone issue because I was able to get it to fail consistently one evening, and all my attempts succeeded the next day.

**Comment by yurishkuro** [comment]
interesting.

@pavolloffay @jpkrohling  could you try re-running the test here in your morning? https://travis-ci.org/jaegertracing/jaeger/builds/444722448?utm_source=github_status&utm_medium=notification

**Comment by objectiser** [comment]
Done, and was successful.

**Comment by annanay25** [comment]
@vprithvi +1.

Tried running it locally, but having some issues running the elasticsearch docker image. 

But since elasticsearch would index according to container-local time, and the search time we give in the query is host-local, there could be a discrepancy there.

**Comment by pavolloffay** [comment]
Strange I don't remember changing anything related to timestamps.

**Comment by pavolloffay** [comment]
@vprithvi did the tests fail locally or on travis?

**Comment by black-adder** [comment]
I tried running the ES tests throughout the day at a regular cadence and noticed they started to fail after 6PM UTC. Haven't ascertained when the tests start to pass.

**Comment by pavolloffay** [comment]
I will have a look at it. Here a failed travis job https://travis-ci.org/jaegertracing/jaeger/jobs/446428056

**Comment by pavolloffay** [comment]
It seems that #1156 and #1151 didn't solve this.

**Comment by yurishkuro** [comment]
I wasn't expecting it would.

**Comment by yurishkuro** [comment]
my PR didn't fix it either.
