### ISSUE TITLE
Promote @tiffon to full maintainer

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1113]
Joe (@tiffon) has been doing great work on Jaeger UI. I would like to propose to make him a full maintainer.  

@jaegertracing/jaeger-maintainers please vote

**Comment by vprithvi** [comment]
+1 Sounds good to me!

**Comment by black-adder** [comment]
+1

**Comment by jpkrohling** [comment]
Huge +1, really deserved!

**Comment by yurishkuro** [comment]
Done! Congratulations!

**Comment by tiffon** [comment]
Thanks folks! Great to hear!
