### ISSUE TITLE
Jaeger-agent need  in the implant in code? Or a agent similar to pinpoin? Just add parameters to the service you want to track, for example: -javaagent:/agent.jar?

### ISSUE THREAD

**Issue by cdoewew** [jaegertracing/jaeger#1118]
thank you

**Comment by jpkrohling** [comment]
The Jaeger Agent is a standalone process that runs as a daemon on the same host as your target application. Your application should be instrumented with the OpenTracing API, perhaps using the [java-agent](https://github.com/opentracing-contrib/java-agent) library and it should also embed the Jaeger Client. The client then captures the spans and sends to the Jaeger Agent.

This is all explained here: https://www.jaegertracing.io/docs/1.7/architecture/

For future questions, please add a proper title and body to the issue ;-) I'm closing this, but feel free to reopen in case you still have questions.
