### ISSUE TITLE
No such host for jaeger-collector when trying to run jaeger-agent.

### ISSUE THREAD

**Issue by gvkarthik93** [jaegertracing/jaeger#1120]
Hi, I am trying to deploy the individual components of Jaeger on my machine. I am using Cassandra as a storage.

What I am trying to do is to run cassandra and initialize the schema. After doing so, I am running the jaeger collector using the following command.

`docker run --rm --link cassandra:cassandra -e SPAN_STORAGE_TYPE=cassandra -p14267:14267 -p14268:14268 -p9411:9411 -e CASSANDRA_SERVERS=cassandra jaegertracing/jaeger-collector`

After doing so, I wanted to run Jaeger Agent so it can start collecting traces. However when I run jaeger-agent using the following command:

`docker run   --rm   -p5775:5775/udp   -p6831:6831/udp   -p6832:6832/udp   -p5778:5778/tcp   jaegertracing/jaeger-agent --collector.host-port=jaeger-collector:14268`

It gives me an error saying "no such host", but my jaeger collector is running on the port 14268.

Could someone please help me with this issue?

**Comment by gvkarthik93** [comment]
Hi, I am trying to deploy the individual components of Jaeger on my machine. I am using Cassandra as a storage.

What I am trying to do is to run cassandra and initialize the schema. After doing so, I am running the jaeger collector using the following command.

`docker run --rm --link cassandra:cassandra -e SPAN_STORAGE_TYPE=cassandra -p14267:14267 -p14268:14268 -p9411:9411 -e CASSANDRA_SERVERS=cassandra jaegertracing/jaeger-collector`

After doing so, I wanted to run Jaeger Agent so it can start collecting traces. However when I run jaeger-agent using the following command:

`docker run   --rm   -p5775:5775/udp   -p6831:6831/udp   -p6832:6832/udp   -p5778:5778/tcp   jaegertracing/jaeger-agent --collector.host-port=jaeger-collector:14268`

It gives me an error saying "no such host", but my jaeger collector is running on the port 14268.

Could someone please help me with this issue?

**Comment by yurishkuro** [comment]
You are not wiring Docker networking namespace correctly.

> -collector.host-port=jaeger-collector:14268

you need to use this name `jaeger-collector` when starting the collector Docker container and also pass  `--link` option to the agent to be able to recognize that name (similar to how you pass Cassandra name to the collector).

**Comment by gvkarthik93** [comment]
Could you tell me what changes I need to make in the above commands? Cause when you say use the name `jaeger-collector` where do I add it?

Is it something like this for jaeger-collector?
`docker run --rm --link cassandra:cassandra -e SPAN_STORAGE_TYPE=cassandra -p14267:14267 -p14268:14268 -p9411:9411 -e CASSANDRA_SERVERS=cassandra jaeger-collector`

and something like this for jaeger-agent?
`docker run --rm --link jaeger-collector:jaeger-collector -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp -p5778:5778/tcp jaegertracing/jaeger-agent --collector.host-port=jaeger-collector:14268`

I am able to run the all-in-one container but I want to setup the individual components.

**Comment by yurishkuro** [comment]
you need to pass the name to the collector container, `--name jaeger-collector`. You probably passed the name `cassandra` already when you started it, otherwise collector wouldn't find it.

**Comment by gvkarthik93** [comment]
I tried running these commands:

`docker run --rm --name jaeger-collector --link cassandra:cassandra -e SPAN_STORAGE_TYPE=cassandra -p14267:14267 -p14268:14268 -p9411:9411 -e CASSANDRA_SERVERS=cassandra jaegertracing/jaeger-collector`

`docker run   --rm --link jaeger-collector:jaeger-collector  -p5775:5775/udp   -p6831:6831/udp   -p6832:6832/udp   -p5778:5778/tcp   jaegertracing/jaeger-agent --collector.host-port=jaeger-collector:14268`

and I still got the error 

`{"level":"info","ts":1539641595.201806,"caller":"tchannel/builder.go:94","msg":"Enabling service discovery","service":"jaeger-collector"}
{"level":"info","ts":1539641595.201977,"caller":"peerlistmgr/peer_list_mgr.go:111","msg":"Registering active peer","peer":"jaeger-collector:14268"}
{"level":"info","ts":1539641595.2048247,"caller":"agent/main.go:62","msg":"Starting agent"}
{"level":"info","ts":1539641596.2030861,"caller":"peerlistmgr/peer_list_mgr.go:157","msg":"Not enough connected peers","connected":0,"required":1}
{"level":"info","ts":1539641596.2032733,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"jaeger-collector:14268"}
{"level":"error","ts":1539641596.454762,"caller":"peerlistmgr/peer_list_mgr.go:171","msg":"Unable to connect","host:port":"jaeger-collector:14268","connCheckTimeout":0.25,"error":"tchannel error ErrCodeTimeout: timeout","stacktrace":"github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).ensureConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:171\ngithub.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).maintainConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:101"}
`

**Comment by gvkarthik93** [comment]
And also when I tried to run jaeger-query, I am able to launch the UI on `localhost:16686` but it is showing an error in logs:

`
{"level":"error","ts":1539642372.6064699,"caller":"zap/logger.go:33","msg":"error when flushing the buffer: write udp 127.0.0.1:40290->127.0.0.1:6831: write: connection refused","stacktrace":"github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap.(*Logger).Error\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap/logger.go:33\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:257\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:267"}
`

This is the command I used to run jaeger-query:

`docker  run --rm --link cassandra:cassandra -e CASSANDRA_SERVERS=cassandra -p 16686:16686 jaegertracing/jaeger-query`

Could you help me with these issues?

**Comment by cdoewew** [comment]
> 而且当我尝试运行jaeger-query时，我可以启动UI，`localhost:16686`但它在日志中显示错误：
> 
> `{"level":"error","ts":1539642372.6064699,"caller":"zap/logger.go:33","msg":"error when flushing the buffer: write udp 127.0.0.1:40290->127.0.0.1:6831: write: connection refused","stacktrace":"github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap.(*Logger).Error\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap/logger.go:33\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:257\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:267"}`
> 
> 这是我用来运行jaeger-query的命令：
> 
> `docker run --rm --link cassandra:cassandra -e CASSANDRA_SERVERS=cassandra -p 16686:16686 jaegertracing/jaeger-query`
> 
> 你能帮我解决这些问题吗？
I also won't install, please teach you, ha ha

**Comment by gvkarthik93** [comment]
@cdoewew Do you have the same problem? I am sorry but I am unable to completely get what you are saying.

@yurishkuro Could you please help me with this problem?

**Comment by jpkrohling** [comment]
> I am able to launch the UI on localhost:16686 but it is showing an error in logs

That's because the tracer embedded into the UI is trying to send its own spans to an agent running on localhost, but there's none there (as localhost here is the container itself, not the host).

You might want to take a look at our Kubernetes templates for inspiration, but if you are just trying to get a simple instance to run, you might have better luck with the all-in-one. It can also be used with Cassandra.

**Comment by jpkrohling** [comment]
I just checked your commands running it locally here. It looks like you are using the port `14268` (plain http) on the agent -> collector communication, and it should be 14267 (tchannel). It's also usually a good idea to set the version explicitly, so, I added those to my command as well.

```bash
docker run \
  --rm \
  --name jaeger-collector \
  --link cassandra:cassandra \
  -e SPAN_STORAGE_TYPE=cassandra \
  -e CASSANDRA_SERVERS=cassandra \
  -p14267:14267 \
  -p14268:14268 \
  -p9411:9411 \
  jaegertracing/jaeger-collector:1.7

docker run \
  --rm \
  --name jaeger-agent \
  --link jaeger-collector \
  -p5775:5775/udp \
  -p6831:6831/udp \
  -p6832:6832/udp \
  -p5778:5778/tcp \
  jaegertracing/jaeger-agent:1.7 \
  --collector.host-port=jaeger-collector:14267

docker run \
  --rm \
  --name jaeger-query \
  --link cassandra:cassandra \
  -e SPAN_STORAGE_TYPE=cassandra \
  -e CASSANDRA_SERVERS=cassandra \
  -p16686:16686 \
  jaegertracing/jaeger-query:1.7
```

Note that you'll still see the UDP failures on the query until #1044 is fixed. On Kubernetes, this can be solved by deploying the agent as a sidecar container in the pod.

**Comment by gvkarthik93** [comment]
@jpkrohling These commands work. Now I am able to look at all the tracers and spans created in my applications. Technically speaking, these should be stored in the cassandra right. So when I try to go query from cassandra using cqlsh, I get empty tables. Do you know why or is there something I am doing wrong while running cassandra or creating the schema?

**Comment by gvkarthik93** [comment]
@jpkrohling  Also I have one other doubt. For now, I am deploying these containers one my local machine and the UI is able to track the tracers and display them when I run my application server on same local machine. How can I track requests if my application server is on a totally different machine?

**Comment by jpkrohling** [comment]
> I get empty tables

If your collector is pointing to Cassandra and your query can read data from it, then data is indeed there. Are you checking the correct keyspaces?

> How can I track requests if my application server is on a totally different machine?

If your test involves your application on a different Docker container, then they are seen as "different machines" already :-) Take a look at the documentation, especially this page: https://www.jaegertracing.io/docs/1.7/architecture/#components

Your application is the yellow box on the left. The typical solution is to let your application report the spans to a local Jaeger Agent, which then sends data to a remote Jaeger Collector.

I'm closing this, as I believe this is solved, but if you do have further questions, feel free to either just ask, or to reopen.

**Comment by gvkarthik93** [comment]
Hi @jpkrohling  Thanks for the insights. I understood the architecture and deployed it.

I have one doubt. Currently, my agent and application are running on VM1. Jaeger collector is on VM2. My collector is up and running. I wanted to link the agent and the collector.

So I ran this command:

`
docker run \
  --rm \
  --name jaeger-agent \
  -p5775:5775/udp \
  -p6831:6831/udp \
  -p6832:6832/udp \
  -p5778:5778/tcp \
  jaegertracing/jaeger-agent:1.7 \
  --collector.host-port=127.0.155.1:14267
`

Here 127.0.155.1 is my IP for VM2 where the collector is running. But when I did this, I got an error saying 

`
{"level":"info","ts":1539817101.6582057,"caller":"peerlistmgr/peer_list_mgr.go:157","msg":"Not enough connected peers","connected":0,"required":1}
{"level":"info","ts":1539817101.6582696,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"129.157.240.146:14267"}
{"level":"error","ts":1539817101.908742,"caller":"peerlistmgr/peer_list_mgr.go:171","msg":"Unable to connect","host:port":"129.157.240.146:14267","connCheckTimeout":0.25,"error":"tchannel error ErrCodeTimeout: timeout","stacktrace":"github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).ensureConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:171\ngithub.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).maintainConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:101"}
`

Could you please help me with this?

**Comment by jpkrohling** [comment]
Did you make a typo in your comment? You have `127.0.155.1` in the command but the output says `129.157.240.146`?

**Comment by gvkarthik93** [comment]
@jpkrohling oh yes. That was a typo. So I am trying to connect to 129.157.240.146 and I ran the command 

`docker run \ --rm \ --name jaeger-agent \ -p5775:5775/udp \ -p6831:6831/udp \ -p6832:6832/udp \ -p5778:5778/tcp \ jaegertracing/jaeger-agent:1.7 \ --collector.host-port=129.157.240.146:14267`

129.157.240.146 is the machine where my jaeger-collector docker is running. But it gave me that error. So is it the wrong command or is there any other way to connect to VM on different machine?

**Comment by gvkarthik93** [comment]
@jpkrohling I wanted to know if the command is correct for calling collector on different host or if there's anything wrong with the command.

**Comment by jpkrohling** [comment]
It does look correct to me.

**Comment by gvkarthik93** [comment]
Thanks @jpkrohling You were right. It's the proxy behind the network that stopped the connection. I fixed it and deployed Jaeger containers. It's now successfully collecting spans from all my applications. This discussion was really helpful.

**Comment by yurishkuro** [comment]
@gvkarthik93 if you found documentation to be lacking / insufficient and have concrete suggestions, please list them here, or (even better) create a PR in https://github.com/jaegertracing/documentation

**Comment by gvkarthik93** [comment]
@yurishkuro I agree. I will create a PR and contribute. I guess my learning experiences would definitely be helpful for someone.

**Comment by yurishkuro** [comment]
🎉

**Comment by nb2019** [comment]
我本机运行了docker 命令如下？
1：docker run -d --name jaeger-collector --net=host --restart=always -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://192.168.0.225:9200 -p 14267:14267 -p 14268:14268 -p 14269:14269 jaegertracing/jaeger-collector

2：docker run -d --name jaeger-query --net=host --restart=always -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://192.168.0.225:9200 -p 16686:16686/tcp jaegertracing/jaeger-query
现在log日志报错了


{"level":"error","ts":1544521522.0942338,"caller":"zap/logger.go:33","msg":"error when flushing the buffer: write udp 127.0.0.1:56157->127.0.0.1:6831: write: connection refused","stacktrace":"github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap.(*Logger).Error\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap/logger.go:33\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:257\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:267"}
{"level":"error","ts":1544521528.0942411,"caller":"zap/logger.go:33","msg":"error when flushing the buffer: write udp 127.0.0.1:56157->127.0.0.1:6831: write: connection refused","stacktrace":"github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap.(*Logger).Error\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap/logger.go:33\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:257\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:267"}
{"level":"error","ts":1544521531.0942106,"caller":"zap/logger.go:33","msg":"error when flushing the buffer: write udp 127.0.0.1:56157->127.0.0.1:6831: write: connection refused","stacktrace":"github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap.(*Logger).Error\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap/logger.go:33\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:257\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:267"}
怎么解决？
