### ISSUE TITLE
no jaegertracing/jaeger-ingester:1.7 tag

### ISSUE THREAD

**Issue by The-Alchemist** [jaegertracing/jaeger#1123]
## Requirement - what kind of business use case are you trying to solve?

The documentation at https://www.jaegertracing.io/download/ says:

```

jaeger-ingester | An alternative to collector; reads spans from Kafka topic and saves them to storage.$ docker pull jaegertracing/jaeger-ingester:1.7
```

## Problem - what in Jaeger blocks you from solving the requirement?

The `1.7` tag doesn't exist for the ingester; only `latest`.

**Comment by yurishkuro** [comment]
yes, a known issue, the container wasn't actually ready when we did a release. Only `latest` tag is available at the moment.

**Comment by The-Alchemist** [comment]
@yurishkuro : Not a problem, let me know if I can send a PR or something.

**Comment by pavolloffay** [comment]
ingester will be tagged during the next release no need for a PR.
