### ISSUE TITLE
Why client-golang traceID low is 63bit?

### ISSUE THREAD

**Issue by wolfelven** [jaegertracing/jaeger#1129]
Hi, everyone, I have a question, why traceid.low is 63bits in client-golang. I see traceid.low is 64bit in client-java .

**Comment by black-adder** [comment]
This issue belongs in the jaeger-client-go repo. Nonetheless, thanks for bringing this up. My guess is that when we first wrote the client, https://golang.org/pkg/math/rand/#Rand.Uint64 wasn't available (only added in golang 1.8). Would you be willing the make the change?

**Comment by yurishkuro** [comment]
I don't think presents an issue by itself, but feel free to open an issue in the go client repo.
