### ISSUE TITLE
How do we configure the collector's IP and port when running jaeger-agent binary file?

### ISSUE THREAD

**Issue by gvkarthik93** [jaegertracing/jaeger#1132]
I have jaeger-agent running through docker. When I run it through the following docker command,

`sudo docker run  --name jaeger-agent \-p5775:5775/udp  -p6831:6831/udp  -p6832:6832/udp  -p5778:5778/tcp  jaegertracing/jaeger-agent:1.7  --collector.host-port=129.157.240.146:14267
`

I am able to configure the IP of the collector and the port. How can I configure the IP and port of configure if I am running the binary executable file for agent on linux machine?

**Comment by yurishkuro** [comment]
in the same way, it's the same binary as in the docker container
