### ISSUE TITLE
TTL on traces

### ISSUE THREAD

**Issue by cphillips83** [jaegertracing/jaeger#1135]
## Requirement - what kind of business use case are you trying to solve?
Provide a way to control TTL for traces without needing to configure individual storage systems manually.

## Problem - what in Jaeger blocks you from solving the requirement?
I can not find any documentation on how to handle maintenance with Jaeger. Are we suppose to access whatever preferred database backend manually and clean up data over the course of months of usage? Wouldn't this require us to understand the data model jaeger is using to make sure things aren't left in a broken state?

## Any open questions to address
I believe cassandra offers TTL on data, ES generally has some sort of cron job running to fake TTL, the in memory dev setup has a way to specify the max amount of records and so on.

Is there a way to simply standardize this so that it can be configured at the Jaeger level and let the plugin determine how to implement it?

EDIT: Doing more research on this I see that ES does support TTL. I suppose the correct way is to just fully understand your backend storage and manually configure it during or after the schema creation?

**Comment by yurishkuro** [comment]
In Cassandra the TTL is defined per-table, and is configurable through the schema script/container we provide.

ES did not have TTL support previously, so there's an index cleaner container provided. Could you please link to the docs where you founds it does provide TTL?

If you would like to suggest a PR to change the docs, it would be great.

**Comment by cphillips83** [comment]
You are correct, after looking this up again it seems it was removed around 2017 due to how it was implemented. They suggest using `delete_query` instead via scheduled jobs.

I guess the issue here is two fold, from my experience cassandra and ES are not the type of database you can simple install and they work out of the box without extended maintenance and monitoring. This creates a bit of an issue when what you are looking for is a distributed trace system and it requires you to understand its dependencies.

Perhaps maybe there should be some documentation on how to maintain Jaeger for the long term? I know this would be storage specific but my simple question is how do I maintain this application over the course of a year or 5 without understanding the backing storage or your data model and their relationships with one another?

**Comment by yurishkuro** [comment]
> how do I maintain this application over the course of a year or 5 without understanding the backing storage or your data model and their relationships with one another?

The repo provides scripts for db schema and when we extend the schema we will provide data migration scripts. Otherwise I don't think it is a realistic expectation to be able to run Jaeger without any operational knowledge of the underlying database. Your other options are:
  * use a hosted database like Elasticsearch on AWS, which still requires some operational knowledge, at least about db schema, or
  * use a hosted version of Jaeger.
