### ISSUE TITLE
how to covert model.proto to java or python?

### ISSUE THREAD

**Issue by daxwang** [jaegertracing/jaeger#1138]
i want to consume jaeger trace data which stored in kafka and default data format is protobuf,  such as flink or a python script, so i covert model.proto(https://github.com/jaegertracing/jaeger/blob/master/model/proto/model.proto) to java or python, but i failed.
run  protoc --python_out=. model.proto, there are errors:
google/api/annotations.proto: File not found.
github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options/annotations.proto: File not found.
github.com/gogo/protobuf/gogoproto/gogo.proto: File not found.
model.proto: Import "google/api/annotations.proto" was not found or had errors.
model.proto: Import "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options/annotations.proto" was not found or had errors.
model.proto: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.

how to covert model.proto to java or python?  help me please.

**Comment by yurishkuro** [comment]
Yeah, we haven't moved towards supporting proto in other languages, so expect some friction. Some of these are standard annotations, gogo is specific to Go. I believe you need their source to be available on the protoc path.
