### ISSUE TITLE
how to decode trace_id from kafka protobuf data?

### ISSUE THREAD

**Issue by daxwang** [jaegertracing/jaeger#1145]
i run the jaeger demo and write data into kafka with protobuf, and then consume with python, but the trace_id decode always incorrectly，here my code, decode with utf-8:
               span = model_pb2.Span()
               span.ParseFromString(msg.value)
               print span.trace_id.decode('utf-8')

the result:
![image](https://user-images.githubusercontent.com/19586089/47554090-23b28500-d93b-11e8-9dc7-2d28cb262c8f.png)

so how to decode span.trace_id?  help please.

**Comment by yurishkuro** [comment]
> write data into kafka with protobuf

Using Jaeger's protobuf model?  I suggest reading it with the same protobuf model, not manually. It will decode all the IDs as needed.

**Comment by wuyupengwoaini** [comment]
@daxwang  https://github.com/PacktPublishing/Mastering-Distributed-Tracing/blob/master/Chapter12/src/main/java/model/ProtoUnmarshaler.java
The ProtoUnmarshaler  will be helpful for you  and the whole project is very helpful for you too.

**Comment by pavolloffay** [comment]
I am closing this as it is tagged as a question and there is no further activity.

**Comment by AudienceX** [comment]
so no how to decode the traceid like 'AAAAAAAAAADlP4sqB+IBqA==' created by kafka
