### ISSUE TITLE
Does Jaeger support MongoDB tracing

### ISSUE THREAD

**Issue by rekaparathalwar** [jaegertracing/jaeger#1149]
Does jaeger support MongoDB tracing by default. We are doing a spike to use Jaeger for our application. We are using spring boot with MongoDB as backend(using MongoDB atlas DBaaS) deployed in Azure Container Service (ACS).

**Comment by black-adder** [comment]
As long as MongoDB is OpenTracing compliant, jaeger will trace it. Looks like you could use this library: https://github.com/opentracing-contrib/java-mongo-driver to add tracing to the MongoDB driver. If you want MongoDB tracing at the database level, MongoDB itself would have to support that.

**Comment by jpkrohling** [comment]
I'm closing this, as I believe @black-adder's answer solves it, but feel free to reopen if you still have questions.

**Comment by ArunaKumarik16** [comment]
Is it possible to add baggage items to mongoDB operations (insert, aggregate..etc) in java. If it is yes? How?
