### ISSUE TITLE
can we always sample slow requests?

### ISSUE THREAD

**Issue by Dieterbe** [jaegertracing/jaeger#1152]
Hello, is there a way to set up sampling such that the slowest requests (longest root spans) are always instrumented?

We want to build a "slow query report" out of our jaeger traces so we can see all the queries that were slow. We could also build this into our application and track all queries that have long durations, but we're hoping to not have this feature creep into our application, and instead piggyback this functionality on top of our already existing jaeger infrastructure.
specifically we'ld like to just send the traces into kafka and our reporting tools would just read from kafka.
we want to sample to avoid overloading the backend but we need representive samples of all slow queries.
thank you :)

**Comment by yurishkuro** [comment]
It requires #425

**Comment by jpkrohling** [comment]
@Dieterbe would it be OK to close this, once you start following the issue that Yuri linked?

**Comment by Dieterbe** [comment]
yes. we can consider this a dupe. thanks folks.
