### ISSUE TITLE
Promote @objectiser to full maintainer

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1155]
Gary made a number of commits to the [backend](https://github.com/jaegertracing/jaeger/commits?author=objectiser) and even more to [Java client](https://github.com/jaegertracing/jaeger-client-java/commits?author=objectiser).

@jaegertracing/jaeger-maintainers

**Comment by black-adder** [comment]
+1

**Comment by tiffon** [comment]
+1

**Comment by jpkrohling** [comment]
+1

**Comment by pavolloffay** [comment]
+1

**Comment by yurishkuro** [comment]
🎉 

Congrats, @objectiser !

**Comment by black-adder** [comment]
yay, congrats!

**Comment by objectiser** [comment]
Thanks!

**Comment by theute** [comment]
Congrats @objectiser  !
