### ISSUE TITLE
Tracing backend and FAAS 

### ISSUE THREAD

**Issue by Puneeth-n** [jaegertracing/jaeger#1162]
Is there a way by which we can propagate Span contexts via something like `SNS` in AWS. I have orchestrated all our Nodejs backends with Jaeger. I was wondering on how to integrate our AWS lambdas so as to trace the request from our backend to lambdas and back to our backend.

**Comment by ledor473** [comment]
@Puneeth-n it's definitely possible to do that!
In fact, propagating context with SNS is very similar to how you do it with HTTP.

Amazon SNS supports [message attributes](https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html) that can be used with [Inject/Extract methods](https://opentracing.io/guides/java/inject-extract/) to pass the context around.

**Comment by Puneeth-n** [comment]
@ledor473 Thanks for the reply. The lambdas would then send the span details out of bound to the collector directly over HTTP right?

**Comment by jpkrohling** [comment]
It sounds like a great blog post! If you want to publish a how-to under our Medium publication, let me know!

**Comment by Puneeth-n** [comment]
Still getting the hang of it. Definitely my next project

**Comment by idohalevi** [comment]
@Puneeth-n can you please share your progress? I would love to read more about it

**Comment by Puneeth-n** [comment]
@idohalevi no didn't work on it anymore :/

**Comment by idohalevi** [comment]
@jpkrohling any insight on this? maybe best practices?

**Comment by jpkrohling** [comment]
@idohalevi you'd basically need to rely on the instrumentation library (OpenTelemetry, OpenTracing) to read and write the context. There's some documentation about context propagation in the OpenTracing repository (linked by @ledor473 in a previous message), and I'm sure there's something similar in the OpenTelemetry area.

**Comment by idohalevi** [comment]
@jacobmarble got it. Thank you for your help.

**Comment by yurishkuro** [comment]
I am going to close this since this is an issue for instrumentation, not for Jaeger.
