### ISSUE TITLE
Expose protocol factory and logger so ThriftProcessor can be used directly by 3rd party code

### ISSUE THREAD

**Issue by pjanotti** [jaegertracing/jaeger#1163]
## Requirement - what kind of business use case are you trying to solve?

Expose ways to get protocolFactory and logger to leverage ThriftProcessor by 3rd parties.

## Problem - what in Jaeger blocks you from solving the requirement?

While building a Jaeger receiver for OpenCensus Agent I can leverage much of the code already exposed by Jaeger (see below). However, since Jaeger uses Thrift and Zap logger from vendor it is not possible for a project to provide either the protocol factory or zap logger by direct importing either one.
```go
// Run starts the Jaeger interceptor, i.e.: mimicks the Jaeger agent, on the given port.
func Run(cfg *Config, sr spanreceiver.SpanReceiver) (func() error, error) {
	transport, err := thriftudp.NewTUDPServerTransport(cfg.Address)
	if err != nil {
		log.Fatalf("Failed to create UDP Thrift transport for Jaeger. Error: %v", err)
	}

	srv, err := servers.NewTBufferedServer(transport, cfg.MaxQueueSize, cfg.MaxPacketSize, nil)
	if err != nil {
		log.Fatalf("Failed to create Thrift buffered server for Jaeger. Error: %v", err)
	}

	protocolFactory, ok := app.GetProtocolFactory(cfg.Protocol) // <- This actually is what is missing. 
	if !ok {
		log.Fatalf("Invalid protocol %q for Jaeger.", cfg.Protocol)
	}

	logger, err := app.GetDefaultLogger() // <- This actually is what is missing. 
	if err != nil {
		log.Fatalf("Failed to create logger for Jaeger: %v", err)
	}

	handler := &jaegerHandler{spanSink: sr}
	processor := jaeger.NewAgentProcessor(handler)
	thriftProcessor, err := processors.NewThriftProcessor(srv, cfg.NumProcessors, nil, protocolFactory, processor, logger)
	if err != nil {
		log.Fatalf("Failed to create the Thrift Processort for Jaeger. Error: %v", err)
	}

	go thriftProcessor.Serve()

	closeFn := func() error {
		thriftProcessor.Stop()
		return nil
	}

	return closeFn, nil
}
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add and functions and/or default values that wraps the protocol factory and logger from vendor in Jaeger so the ThriftProcessor can be used by 3rd parties. For the protocol factory a simple small function wrapping the protocolFactoryMap does the job. Quick and without thinking too much adding the snippet below to github.com/jaegertracing/jaeger/cmd/agent/app/builder.go solves the problem for me:

```go
// GetProtocolFactory is a helper function that wraps the thrift.TProtocolFactory dependency that comes via vendoring.
// This way public exposed construction of an agent processor with custom reporter is possible.
func GetProtocolFactory(protocol Protocol) (thrift.TProtocolFactory, bool) {
	factory, ok := protocolFactoryMap[protocol]
	return factory, ok
}

// GetDefaultLogger is a helper function that wraps the zap.Logger dependency that comes via vendoring.
// This way public exposed construction of an agent processor with custom reporter is possible.
func GetDefaultLogger() (*zap.Logger, error) {
	// TODO: Allow configuration of logger.
	logger, err := zap.NewProduction()
	return logger, err
}
```

## Any open questions to address

For the logger it will be nice if it could work with some default logger or, like metrics factory, correctly handle the code when logger is nil.

**Comment by yurishkuro** [comment]
Could you please elaborate on what you're trying to do? What is OpenCensus receiver? Why does it need thrift format?

**Comment by pjanotti** [comment]
Ah first a clarification receiver is the tentative new name in OpenCensus for what is right now called an interceptor. What I am trying to do is add an interceptor/receiver for Jaeger to the OpenCensus agent per https://github.com/census-instrumentation/opencensus-service/issues/153. Note that the agent is not the collector, following the same terminology used in Jaeger.

**Comment by pjanotti** [comment]
This is reasonable. It was not clear to me if there was the intent of exposing that (and making it "embeddable") or not. Closing...

**Comment by odeke-em** [comment]
The Thrift issue was be solved by ensuring that the version of Thrift-Go being used is `v0.10.0` . Thus, with modules `go get github.com/apache/thrift/lib/go/thrift@0.10.0` as Thrift commit https://github.com/apache/thrift/commit/5785279e2e809f6c56dbbe0eb41d13fb17c88bdd added `context.Context` to `thrift.TProtocol.Flush` yet Uber uses a version from `v0.10.0`
