### ISSUE TITLE
Using a kerberos secured Kafka as buffer between Jaeger and Elasticsearch

### ISSUE THREAD

**Issue by awiradarma** [jaegertracing/jaeger#1188]
## Requirement - what kind of business use case are you trying to solve?
We want to store our jaeger spans in ElasticSearch, but we want to use Kafka as a buffer in between jaeger collector and our ES cluster. We would still want the Jaeger UI to query against our ES cluster. Our production Kafka clusters are Kerberos secured.

## Problem - what in Jaeger blocks you from solving the requirement?
Jaeger does not provide a mechanism to connect to a Kerberos secured Kafka cluster.

**Comment by yurishkuro** [comment]
Don't know about Kerberos specifically, but sarama driver does expose the TLS configuration

https://sourcegraph.com/github.com/Shopify/sarama/-/blob/config.go#L42
