### ISSUE TITLE
Implement storage cache for query service

### ISSUE THREAD

**Issue by isaachier** [jaegertracing/jaeger#1203]
## Requirement - what kind of business use case are you trying to solve?

Currently, the query service always hits Cassandra for data. We can easily cache some data in memory, assuming it is not volatile (e.g. service names that change infrequently).

## Problem - what in Jaeger blocks you from solving the requirement?

The current architecture has no caching.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Implement a basic in-memory cache for static data. @black-adder and @yurishkuro have already implemented this in the internal Uber Jaeger repository.

**Comment by yurishkuro** [comment]
closing per discussion in #1204
