### ISSUE TITLE
Use gRPC between collector and agent as default

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#1218]
We should decide when to use gRPC as default between agent and collector.

The first release with gRPC will be 1.9.0. If all goes well could we switch to the default in 1.10?

**Comment by yurishkuro** [comment]
sgtm

**Comment by pavolloffay** [comment]
1.9.0 has been released. I will change the default to gRPC as soon as possible to catch any bug in latest images before doing the final release.

**Comment by yurishkuro** [comment]
We need to solve the retry situation, otherwise all the cross dock tests are still running with tchannel

**Comment by pavolloffay** [comment]
+1 I (or anybody else) will have a look at it during the swap.
