### ISSUE TITLE
Is there a document to explain the specific meaning of various metrics?

### ISSUE THREAD

**Issue by wuyupengwoaini** [jaegertracing/jaeger#1224]
Supporting prometheus metrcis is a good thing for me ,but i find it is difficult to totally understand the real meaning of the metrics exposed by jaeger-agent,jaeger-collector and jaeger-query.

So, I really want to konw whether there is  a document to explain the specific meaning of various metrics?

**Comment by yurishkuro** [comment]
We don't have one at the moment. However, there is a PR that's getting merged soon that adds descriptions to out metrics API, so it would be a good time to add the documentation you are asking for as those descriptions (it will stay in the code and will be up to date). There was also work someone was doing to create standard dashboards.

**Comment by wuyupengwoaini** [comment]
Could you tell me the PR link?

**Comment by objectiser** [comment]
The description PR is https://github.com/jaegertracing/jaeger-lib/pull/61

**Comment by wuyupengwoaini** [comment]
Thank you ,waiting for the new PR and the standard dashboards.

**Comment by jpkrohling** [comment]
I know that @Gouthamve is working on a couple of things related to Grafana and we are planning on writing a blog post about how to monitor Jaeger.

Your point about documenting the meaning behind each metric is a great one, but I'm not sure what's the best way to approach this. Have you seen other projects doing this (cc @jstickler)?

**Comment by gouthamve** [comment]
Well while it's great to do this in the README, it's kinda hard to keep such a list up-to date. Ideally, good HELP text in Prometheus would fix this, and the above PR adds support for that. 

See: https://github.com/frodenas/stackdriver_exporter#metrics for inspiration.

**Comment by yurishkuro** [comment]
I suggest we start with the in-code documentation, which makes the metrics self-describing in Prometheus endpoint. Maintaining separate documentation is difficult.

**Comment by yurishkuro** [comment]
metrics are already self-describing
