### ISSUE TITLE
When reading numeric strings from an Elasticsearch store with --es.tags-as-fields.all, the string is parsed as a number

### ISSUE THREAD

**Issue by ScottKaye** [jaegertracing/jaeger#1236]
## Requirement - what kind of business use case are you trying to solve?

There seems to be a bug similar to https://github.com/jaegertracing/jaeger-ui/issues/146, which may now relate to https://github.com/jaegertracing/jaeger/pull/1018.  I am using Elasticsearch as my span store, with `ES_TAGS_AS_FIELDS_ALL=true`.  This stores spans like this:

```json
{
    "traceID": "bb62383fdf565f55",
    "spanID": "bb62383fdf565f55",
    "operationName": "operation",
    "references": [],
    "flags": 1,
    "startTime": 1543345090571024,
    "startTimeMillis": 1543345090571,
    "duration": 420980,
    "tag": {
        "sampler@type": "const",
        "sampler@param": "True",
        "identifier": "000045"
    },
    "logs": [],
    "process": {
        "serviceName": "ui",
        "tag": {
            "jaeger@version": "CSharp-0.2.2.0",
            "hostname": "local",
            "ip": "10.1.1.1"
        }
    }
}
```

Here's the relevant part of the index mapping, showing that `identifier` is mapped as a keyword (string), rather than a number.

```json
{
    "span": {
        "properties": {
            "tag": {
                "properties": {
                    "identifier": {
                        "type": "keyword",
                        "ignore_above": 256
                    },
                    "sampler@param": {
                        "type": "keyword",
                        "ignore_above": 256
                    },
                    "sampler@type": {
                        "type": "keyword",
                        "ignore_above": 256
                    }
                }
            }
        }
    }
}
```

## Problem - what in Jaeger blocks you from solving the requirement?

However when I open this span in Jaeger UI,

![](https://scottkaye.blob.core.windows.net/files/img/chrome_2018-11-27_14-59-44.png)

The string is parsed as a number, resulting in the zeroes (padding) being truncated.  Users copying and pasting the `identifier` value into another tool to search for aren't getting the correct results until they manually pad the number.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

If there is any way to read the Elasticsearch type mapped to the value at query time, a value of "keyword" would represent a string.  The mapping can be pulled with `GET localhost:9200/jaeger-span*/_mapping/span/field/tag.identifier`, which returns

```json
{
    "jaeger-span-2018-11-27": {
        "mappings": {
            "span": {
                "tag.identifier": {
                    "full_name": "tag.identifier",
                    "mapping": {
                        "identifier": {
                            "type": "keyword",
                            "ignore_above": 256
                        }
                    }
                }
            }
        }
    }
}
```

Prefixing the identifiers with anything non-numeric keeps the string format and works, though users have to now remove the extra character before searching.

**Comment by pavolloffay** [comment]
> Here's the relevant part of the index mapping, showing that identifier is mapped as a keyword (string), rather than a number.

This is correct at the moment we store everything as keyword. We need to map different types to the same in advance now known field.

@ScottKaye how do you report spans to jaeger?
* what client library are you using?
* do you have an example how do you create the span with `identifier` tag?

**Comment by ScottKaye** [comment]
I am using the [Jaeger C# library](https://www.nuget.org/packages/Jaeger/) with this simple test script:

```cs
var tracer = new Jaeger.Tracer.Builder("ui")
	.WithSampler(new Jaeger.Samplers.ConstSampler(true))
	.Build();

using (var scope = tracer.BuildSpan("operation").StartActive(true))
{
	scope.Span.SetTag("identifier", "000045");
	scope.Span.Log("test-event");
}
```

This is how I'm starting up Jaeger on Windows (heh):

```bat
@echo off
SET SPAN_STORAGE_TYPE=elasticsearch
SET ES_SERVER_URLS=http://localhost:9200
SET ES_TAGS_AS_FIELDS_ALL=true

.\jaeger-1.8.0-windows-amd64\jaeger-all-in-one.exe
pause
```

No special configuration is set on Elasticsearch.  I deleted everything in my local cluster, ran my test script, then opened Jaeger UI.  I get `45` parsed as a number.  Here's the full record as saved in Elasticsearch:

```json
{
    "traceID": "4d1b1124185fa8d0",
    "spanID": "4d1b1124185fa8d0",
    "flags": 1,
    "operationName": "operation",
    "references": [],
    "startTime": 1543957826297233,
    "startTimeMillis": 1543957826297,
    "duration": 5001,
    "tags": [],
    "tag": {
        "identifier": "000045",
        "sampler@param": true,
        "sampler@type": "const"
    },
    "logs": [
        {
            "timestamp": 1543957826301251,
            "fields": [
                {
                    "key": "event",
                    "type": "string",
                    "value": "test-event"
                }
            ]
        }
    ],
    "process": {
        "serviceName": "ui",
        "tags": [],
        "tag": {
            "hostname": "local",
            "ip": "10.1.1.1",
            "jaeger@version": "CSharp-0.2.2.0"
        }
    }
}
```

Running the same procedure without `SET ES_TAGS_AS_FIELDS_ALL=true` results in Jaeger UI displaying the value correctly.  I love what `ES_TAGS_AS_FIELDS_ALL` does structurally though, thank you for adding this feature!

**Comment by pavolloffay** [comment]
Elasticsearch does automatically type coercion https://www.elastic.co/guide/en/elasticsearch/reference/current/coerce.html. If you store string `5000` it will be converted to `int`.  Wondering what happens if you disable it on the index.

The discussion around types also happened here https://github.com/jaegertracing/jaeger/issues/906#issuecomment-414372345

**Comment by pavolloffay** [comment]
Type coercion happens for sure, but in your case the `identifier` is stored as a string. The conversion to int happens here https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/spanstore/dbmodel/to_domain.go#L165.

**Comment by StarpTech** [comment]
Hi, I'm facing with the same issue. The documents are stored correctly but all fields are from type `string` rather `number` etc. Here is an example of the opentracing `status_code` tag.

![image](https://user-images.githubusercontent.com/1764424/51383146-eb28de80-1b18-11e9-9dcc-2dea7cec3e27.png)
