### ISSUE TITLE
es.index-prefix should not include `:`

### ISSUE THREAD

**Issue by cushind** [jaegertracing/jaeger#1238]
## es.index-prefix should not include `:`

It would be better if the index-prefix did not include `:`, is there an explicit reason this is included? It actually prevents uniformity with our other elasticsearch indices. We have elasticsearch curator code that pattern matches, and the colon makes this more tedious. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Either exclude the `:` in the es.index-prefix or make it optional.

**Comment by pavolloffay** [comment]
It's traced in https://github.com/elastic/elasticsearch/issues/23892. It will be probably removed in version ES7.

I guess we can simply remove it and do direct concatenation with the name.

**Comment by pavolloffay** [comment]
Now the question is how to fix this in jaeger. The simplest is to change `:` to `-` but it will break people. 

The other option is to remove adding any separator to the prefix. It still breaks existing deployments using the prefix. They will have to change index prefix configuration and add `:` in there.

When do we want to do this? As soon as possible or let say wait for jaeger 2.0, but when will it happen?

**Comment by objectiser** [comment]
> The simplest is to change : to - but it will break people.

The benefit of just changing the separator is that it does not impact the user (in terms of prefix configuration) as long as reading from indexes with either char is supported for some period of time.

**Comment by cushind** [comment]
In our case its best to leave it out entirely, and we can still clearly delineate the prefix if we choose with any character.

**Comment by cushind** [comment]
I actually removed the `:` altogether and rebuilt the image. If that's the solution you want I can submit a PR.

**Comment by pavolloffay** [comment]
> as long as reading from indexes with either char is supported for some period of time.

I like the idea, but I don't like to complicate readers. Not sure if it would cripple query time as we would double number of indices (even half of them would not exists).

I would like to hear more from other people who are using ES storage cc @jaegertracing/elasticsearch

**Comment by masteinhauser** [comment]
I think Elasticsearch could handle specifying multiple indices to search, matching the two known patterns during a period where Jaeger has deprecated the old `:` colon-based separation. Especially if only a single index exists in either the new or old format, it _should_ be transparent to Jaeger's queries.

**Comment by pavolloffay** [comment]
I am looking into this. I will change the processing to include both separators `-` and `:` during the deprecation period.
