### ISSUE TITLE
Improve error reporting in the API

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1249]
The message says "and 1 failure" but does not specify what it was.

![image](https://user-images.githubusercontent.com/3523016/49959795-97edbb80-fedc-11e8-91f2-213895835eb1.png)

**Comment by vprithvi** [comment]
I looked into this - the query object only contains the string and not the failure. It seems that Cassandra logs might have the failure. 

I'll put out a diff to log the query

**Comment by yurishkuro** [comment]
string would be enough if it actually contained the error. We're currently swallowing the error message somewhere.

**Comment by vprithvi** [comment]
>We're currently swallowing the error message somewhere.

The error message is "Operation failed - received 0 responses and 1 failures"
