### ISSUE TITLE
Tracking issue for build failures due to dep fetch failure

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#1251]
## Requirement - what kind of business use case are you trying to solve?
Builds should be reliable
## Problem - what in Jaeger blocks you from solving the requirement?
Some builds fail with 
```
Will install into /home/travis/gopath/bin
Fetching https://github.com/golang/dep/releases/latest..
Release Tag = v0.5.0
Fetching https://github.com/golang/dep/releases/tag/v0.5.0..
Fetching https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64..
make: *** [install] Error 56
```

**Comment by yurishkuro** [comment]
please link the build.

we probably need to add a retry.

**Comment by pavolloffay** [comment]
We can close this we have migrated to go modules.
