### ISSUE TITLE
Is there anyway to trace the logs of agent?

### ISSUE THREAD

**Issue by gvkarthik93** [jaegertracing/jaeger#1261]
I have my agent, collector, query and cassandra containers running. I have 2 VMs. When I deployed the code with tracing integrated on first virtual machine, I could see the tracers and spans on jaeger UI. I could also track them in Cassandra DB. But when I replicated the same thing on virtual machine 2, my tracers and spans are not being collector.

In this scenario, I have only one collector. This one collector is getting spans from VM1 but not VM2. The application code is same. So is it the issue with the jaeger-agent? Cause I have 2 agents running on 2 VMs.

How can I debug it to find out if agent on VM2 is not sending any traces to collector? I can't see the tracer instantiated in the logs of my application on VM2. But I can see the same log in my application on VM1. Any insights are highly appreciated.

**Comment by yurishkuro** [comment]
You can start with looking at metrics from the agent (curl /metrics). It counts all the spans it receives and sends.

**Comment by gvkarthik93** [comment]
How can I check metrics from agent? Is there any specific way?

**Comment by gvkarthik93** [comment]
Never mind. I found we can find metrics for jaeger-agent through the port exposed and the URI /metrics. I have one question though. How can I interpret these metrics being displayed? How do I look for metrics related to specific span?

**Comment by gvkarthik93** [comment]
That really helps. Can we also check the number of tracers instantiated? If so, what's the attribute for it?

**Comment by gvkarthik93** [comment]
That really helps. Can we also check the number of tracers instantiated? If so, what's the attribute for it?

**Comment by yurishkuro** [comment]
Tracers are instantiated in your applications, the agent doesn't know anything about them until they send the data. The collector has a metric for the number of spans per service, but I don't think the agent has it.
