### ISSUE TITLE
Jagger docker-compose not work

### ISSUE THREAD

**Issue by tannh** [jaegertracing/jaeger#1265]
I have install docker stack flow https://github.com/jaegertracing/jaeger/blob/master/docker-compose/jaeger-docker-compose.yml. But i have get error with cassandra-schema. 
Detail error logs:
Cassandra is still not up at cassandra. Waiting 1 second.
Connection error: ('Unable to connect to any servers', {'172.24.0.2': error(111, "Tried connecting to [('172.24.0.2', 9042)]. Last error: Connection refused")})
Cassandra is still not up at cassandra. Waiting 1 second.
Connection error: ('Unable to connect to any servers', {'172.24.0.2': error(111, "Tried connecting to [('172.24.0.2', 9042)]. Last error: Connection refused")})
Cassandra is still not up at cassandra. Waiting 1 second.
Connection error: ('Unable to connect to any servers', {'172.24.0.2': error(111, "Tried connecting to [('172.24.0.2', 9042)]. Last error: Connection refused")})
Cassandra is still not up at cassandra. Waiting 1 second.
Connection error: ('Unable to connect to any servers', {'172.24.0.2': error(111, "Tried connecting to [('172.24.0.2', 9042)]. Last error: Connection refused")})
Cassandra is still not up at cassandra. Waiting 1 second.

system_traces  system_schema  system_auth  system  system_distributed

Generating the schema for the keyspace jaeger_v1_dc1 and datacenter dc1
Using template file /cassandra-schema/v001.cql.tmpl with parameters:
    mode = test
    datacenter = dc1
    keyspace = jaeger_v1_dc1
    replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}
    trace_ttl = 172800
    dependencies_ttl = 0

The container cassandra is up everthing.

Thanks

**Comment by IYABAO** [comment]
It does not work for me either.
jaeger/docker-compose/jaeger-docker-compose.yml

`Using template file /cassandra-schema/v003.cql.tmpl with parameters:

    mode = test

    datacenter = dc1

    keyspace = jaeger_v1_dc1

    replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}

    trace_ttl = 172800

    dependencies_ttl = 0

<stdin>:54:SyntaxException: Unknown property 'dclocal_read_repair_chance'

<stdin>:68:SyntaxException: Unknown property 'dclocal_read_repair_chance'

<stdin>:84:SyntaxException: Unknown property 'dclocal_read_repair_chance'

<stdin>:101:SyntaxException: Unknown property 'dclocal_read_repair_chance'

<stdin>:118:SyntaxException: Unknown property 'dclocal_read_repair_chance'

<stdin>:137:SyntaxException: Unknown property 'dclocal_read_repair_chance'

<stdin>:157:SyntaxException: Unknown property 'dclocal_read_repair_chance'`

**Comment by yurishkuro** [comment]
Which version of Cassandra?

**Comment by IYABAO** [comment]
> Which version of Cassandra?

4.0 And 3.9

**Comment by yurishkuro** [comment]
it works for me
```
$ docker compose -f docker-compose/jaeger-docker-compose.yml up
```
and the schema logs are successful:
```
$ docker compose -f docker-compose/jaeger-docker-compose.yml logs | grep cassandra-schema_1
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.22.0.2:9042': ConnectionRefusedError(111, "Tried connecting to [('172.22.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
....
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.22.0.2:9042': ConnectionRefusedError(111, "Tried connecting to [('172.22.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  |
cassandra-schema_1  | system       system_distributed  system_traces  system_virtual_schema
cassandra-schema_1  | system_auth  system_schema       system_views
cassandra-schema_1  |
cassandra-schema_1  | Generating the schema for the keyspace jaeger_v1_dc1 and datacenter dc1
cassandra-schema_1  | Using template file /cassandra-schema/v004.cql.tmpl with parameters:
cassandra-schema_1  |     mode = test
cassandra-schema_1  |     datacenter = dc1
cassandra-schema_1  |     keyspace = jaeger_v1_dc1
cassandra-schema_1  |     replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}
cassandra-schema_1  |     trace_ttl = 172800
cassandra-schema_1  |     dependencies_ttl = 0
cassandra-schema_1 exited with code 0
$
```

**Comment by yurishkuro** [comment]
I am closing this sine the original ticket is very old

**Comment by IYABAO** [comment]
the same command. 
`
$ docker compose -f docker-compose/jaeger-docker-compose.yml logs  | grep cassandra-schema
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  | Connection error: ('Unable to connect to any servers', {'172.21.0.2': error(111, "Tried connecting to [('172.21.0.2', 9042)]. Last error: Connection refused")})
cassandra-schema_1  | Cassandra is still not up at cassandra:9042. Waiting 1 second.
cassandra-schema_1  |
cassandra-schema_1  | system_traces  system_schema  system_auth  system  system_distributed
cassandra-schema_1  |
cassandra-schema_1  | Generating the schema for the keyspace jaeger_v1_dc1 and datacenter dc1
cassandra-schema_1  | Using template file /cassandra-schema/v003.cql.tmpl with parameters:
cassandra-schema_1  |     mode = test
cassandra-schema_1  |     datacenter = dc1
cassandra-schema_1  |     keyspace = jaeger_v1_dc1
cassandra-schema_1  |     replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}
cassandra-schema_1  |     trace_ttl = 172800
cassandra-schema_1  |     dependencies_ttl = 0
cassandra-schema_1  | <stdin>:54:SyntaxException: Unknown property 'dclocal_read_repair_chance'
cassandra-schema_1  | <stdin>:68:SyntaxException: Unknown property 'dclocal_read_repair_chance'
cassandra-schema_1  | <stdin>:84:SyntaxException: Unknown property 'dclocal_read_repair_chance'
cassandra-schema_1  | <stdin>:101:SyntaxException: Unknown property 'dclocal_read_repair_chance'
cassandra-schema_1  | <stdin>:118:SyntaxException: Unknown property 'dclocal_read_repair_chance'
cassandra-schema_1  | <stdin>:137:SyntaxException: Unknown property 'dclocal_read_repair_chance'
cassandra-schema_1  | <stdin>:157:SyntaxException: Unknown property 'dclocal_read_repair_chance'
`
Why template file is different? It depends the OS System? 
Using template file /cassandra-schema/v003.cql.tmpl

**Comment by yurishkuro** [comment]
Mine runs with Cassandra 4.0, which version are you running?  `dclocal_read_repair_chance` was definitely a valid setting at some point.
```
$ docker images | grep cassandra
cassandra                                           4.0         737365077efa   2 weeks ago     341MB
```

**Comment by IYABAO** [comment]
> Mine runs with Cassandra 4.0, which version are you running? `dclocal_read_repair_chance` was definitely a valid setting at some point.
> 
> ```
> $ docker images | grep cassandra
> cassandra                                           4.0         737365077efa   2 weeks ago     341MB
> ```

# Extract cassandra version
#
# $ cqlsh -e "show version"
# [cqlsh 5.0.1 | Cassandra 3.11.11 | CQL spec 3.4.4 | Native protocol v4]
#
cas_version=$(cqlsh -e "show version" \
    | awk -F "|" '{print $2}' \
    | awk -F " " '{print $2}' \
    | awk -F "." '{print $1}' \
)

template=$1
if [[ "$template" == "" ]]; then
    case "$cas_version" in
        3)
            template=$(dirname $0)/v003.cql.tmpl
            ;;
        4)
            template=$(dirname $0)/v004.cql.tmpl
            ;;
        *)
            template=$(ls $(dirname $0)/*cql.tmpl | sort | tail -1)
            ;;
    esac
fi

I run cassandra 4.0. 
My bad.  I checked the code. Realize that my jaegertracing/jaeger-cassandra-schema:latest is pulled a year ago.
Embarrassedly I pull the real "latest" docker image, it works fine now.
Thanks for your time.

**Comment by yurishkuro** [comment]
Such is the danger of :latest
