### ISSUE TITLE
ElasticSearch Backend Conversion issue with tags 

### ISSUE THREAD

**Issue by Etienne-Carriere** [jaegertracing/jaeger#1267]
I think there is a issue : 
* ES storage is used ( SPAN_STORAGE_TYPE=elasticsearch)
* Tags are store as field (--es.tags-as-fields.all)
* Storing objects of type numeric (int/float/...) 

Jaeger API : /api/traces/xxxx contains 
```
					
"tags": [
		[...]
                {
                  "key": "peer.ipv4",
                  "type": "string",
                   "value": "xxxxxxxxxxxxx"
                  },
                  {
                    "key": "peer@port",
                    "type": "int64",
                    "value": 443
                  },
```
						
while ES document is : 

```
 "tag": {
	  [...]
      "peer@ipv4": "xxxxxxxxxxxxx",
      "peer@port": 443,
    },
```

I think it is linked to https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/spanstore/dbmodel/to_domain.go#L166
where we take the initial key and not the key with substitution.

**Comment by yurishkuro** [comment]
what is the issue? tag with "int64" type is represented as a number in ES/JSON.

**Comment by Etienne-Carriere** [comment]
The issue is the '@' in the tag key which is not substituted to '.' for int* .
