### ISSUE TITLE
repeat traceId in diffrent trace

### ISSUE THREAD

**Issue by yzpangu** [jaegertracing/jaeger#1276]
we got repeat traceId in our project trace analysis

Traceid was generated in one request yesterday and the same traceid was generated in another request today

**Comment by black-adder** [comment]
Hi, thanks for reporting. This ticket might interest you: https://github.com/jaegertracing/jaeger/issues/858

**Comment by yurishkuro** [comment]
Trace IDs are random numbers, they are not guaranteed to never repeat.  If you want to reduce the probability of ID clashes you should configure Jaeger clients to use 128bit trace IDs.
