### ISSUE TITLE
New sampler tag to know if the Remote Sampler is used

### ISSUE THREAD

**Issue by ledor473** [jaegertracing/jaeger#1287]
## Requirement - what kind of business use case are you trying to solve?
It would great to be able to know whether or not a service is using the RemoteSampler.
Currently, if you use the RemoteSampler the tag `sampler.type` will be set to the actual implementation (`const`, `probabilistic`, etc.)

## Problem - what in Jaeger blocks you from solving the requirement?
The information is not in the datastore

## Proposal - what do you suggest to solve the problem or improve the existing situation?
I think we could add this functionnality to all client libraries.
Another option might be to do it in the Collector, something like a Sanitizer that compare the configured strategy to the received Span tags (`sampler.type` + `sampler.param`)

**Comment by yurishkuro** [comment]
Yes, I think it would be useful. We discussed it in the past but never did it. It could be the same tag, but with a hierarchical value, e.g. `remote/probabilistic`.

Currently adaptive sampling logic compares the recorded probability with what it was proposing, to decide if the sampler actually respected the settings. A bit fragile, but then it doesn't really depend on it being accurate.

**Comment by black-adder** [comment]
I regret not doing this when we started building adaptive sampling. Adaptive sampling might need to be updated slightly but this sounds good. We should settle on a delimiter for hierarchy and make sure we don't deviate from it, `/` sounds good.

**Comment by Falco20019** [comment]
@yurishkuro Is this already implemented somewhere?

**Comment by yurishkuro** [comment]
I don't think any client implemented it. To be backwards compatible, we can add an extra tag `sampler.remote=true`, rather than changing `sampler.type`. No backend functionality depends on this at the moment.

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients, please open this request in OpenTelemetry if still needed.
