### ISSUE TITLE
Wrong port exposed in ingester dockerfile

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#1288]
## Requirement - what kind of business use case are you trying to solve?
Correct port should be exposed.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently the ingester dockerfile [exposes port 14267](https://github.com/jaegertracing/jaeger/blob/master/cmd/ingester/Dockerfile#L8) which is a collector port.

However it should [expose port 14271 for metrics](https://github.com/jaegertracing/jaeger/blob/master/cmd/ingester/app/flags.go#L63) and [expose port 14270 for health check](https://github.com/jaegertracing/jaeger/blob/master/cmd/ingester/app/flags.go#L65)

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Expose 14271 and 14270 ports in dockerfile, and don't expose 14267.

**Comment by pavolloffay** [comment]
I think we also do not expose all ports in other dockerfiles. We should revisit all dockerfiles. Actually is the exposing a port in dockerfile mandatory? If no maybe we could not expose anything

**Comment by objectiser** [comment]
Agree - not clear whether required - but for now wanted to make sure this one was resolved before the 1.9 release.
