### ISSUE TITLE
querying data repeatedly makes duplicated span on jaeger-ui

### ISSUE THREAD

**Issue by crazycomputer** [jaegertracing/jaeger#1297]
## Requirement - what kind of business use case are you trying to solve?
When using the  search function of jaeger-query, if the data to be queried is very large, the method multiRead in "github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/reader.go" will query the storage more than once. There is a bug in this method that causes queried data may be repeated probably.
[https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/spanstore/reader.go](url)

## Problem - what in Jaeger blocks you from solving the requirement?
![default](https://user-images.githubusercontent.com/34932896/51676080-84239200-2010-11e9-85ff-bf650e473b9e.PNG)
The array of searchRequests is been maked  Outside the for loop，the length of it equals the slice of traceIds.  When  it query second time in the for loop，the length of traceIds will be changed，but the length of searchRequests  will not. This bug may cause repeated traceId be queried.like this:
![20190124-200601 espace](https://user-images.githubusercontent.com/34932896/51677337-458fd680-2014-11e9-9b9a-45822886a16a.png)
There is #duplicated span in this trace

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Maybe  we can initial searchRequests in for loop，the length of it will equals the slice of traceIds Always.

**Comment by black-adder** [comment]
good catch!

**Comment by pavolloffay** [comment]
done in #1677
