### ISSUE TITLE
Strip whitespace from value for servers in configmap

### ISSUE THREAD

**Issue by joshushua** [jaegertracing/jaeger#1300]
## Requirement 
Listing the IP addresses of each node of a Cassandra cluster.

## Problem - what in Jaeger blocks you from solving the requirement?
In the **configmap.yml** file, the key-value pair of _servers: XX.XX.XXX.XX_ for one IP entry works fine. But when providing more than one entry, like _servers: XX.XX.XXX.XX, XX.XXX.XX.XXX, XX.XXX.XXX.XX_, the Collector's *gocql* reveals an error for the second IP: _dns error: lookup XX.XXX.XX.XXX: no such host_ and reveals the same error for the third IP.

When I remove the whitespace between the comma and the next IP, the thing works fine and the Collector successfully connects to the Cassandra cluster.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Strip white spaces from the value, so that humans can still use whitespaces when writing and reading these values.

## Any open questions to address
Will you please include this type of Cassandra example in your documentation? Something beyond the all-in-one example which is too simple for production scenarios. I couldn't find anything about clusters and raw IP addresses for the cluster.

**Comment by jpkrohling** [comment]
For those looking to send their first contribution to the project, this is probably the right place to apply the fix:

https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/options.go

Make sure to add a new test to https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/options_test.go

**Comment by jpkrohling** [comment]
And don't forget to read the [CONTRIBUTING.md](https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING.md)!

**Comment by karlpokus** [comment]
I'll have a PR ready shortly.

**Comment by black-adder** [comment]
reopening to address the documentation ask

**Comment by Abhi-khandelwal** [comment]
Hi @black-adder, I'm new to this community, can I work on this issue ?

**Comment by yurishkuro** [comment]
@Abhi-khandelwal by all means, but not that at this point it's a documentation task, not coding.

**Comment by Abhi-khandelwal** [comment]
Ohk @yurishkuro , I'll try to fix some other beginner coding issues. :)

**Comment by aloeankh** [comment]
@jpkrohling I'm coming from Outreachy, am interested in data tracing research, and would enjoy solving this documentation issue. Would you recommend any other tasks I could complete in order to exemplify my skills?

**Comment by jpkrohling** [comment]
@aloeankh sorry, I just saw your message. The application phase for Outreachy is over (or almost), but if you'd still like to contribute, the right place for this would probably be in the Cassandra-specific documentation, here:

https://www.jaegertracing.io/docs/1.14/deployment/#cassandra
(source: https://github.com/jaegertracing/documentation/blob/master/content/docs/next-release/deployment.md#cassandra )

**Comment by Git-Jiro** [comment]
Hi @jpkrohling,
I would like to do that docs update.

One question though:
The link https://github.com/jaegertracing/documentation/blob/master/content/docs/next-release/deployment.md#cassandra points to the doc source. The examples start a docker container and provide some env vars to the container.
Is the assumption correct that the CASSANDRA_SERVERS env variable somehow ends up as the parameter --cas.servers for the jaeger binary?

If yes, then I kinda now what needs to be added to the docs.

**Comment by jpkrohling** [comment]
Every parameter can be specified both as CLI parameter and as env var (except the span storage type one). We list only env vars in the docs page, though.

**Comment by Git-Jiro** [comment]
@jpkrohling anything else that needs to be documented before this issue can be closed?
