### ISSUE TITLE
Strip whitespace from value for ES servers and kafka brokers

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger#1302]
## Requirement - what kind of business use case are you trying to solve?
See https://github.com/jaegertracing/jaeger/issues/1300 for ES servers and kafka brokers

## Problem - what in Jaeger blocks you from solving the requirement?
https://github.com/jaegertracing/jaeger/blob/bfa7b785e2dbb7d4fa55f2a51915b095a2fa928c/plugin/storage/es/options.go#L221 and https://github.com/jaegertracing/jaeger/blob/bfa7b785e2dbb7d4fa55f2a51915b095a2fa928c/plugin/storage/kafka/options.go#L77

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Same solution as in #1301 

## Any open questions to address
Perhaps come up with a general solution for this? Maybe `x/config/viper.go` that wraps viper but with an extra function `GetStrings` that handles the removal of whitespaces? Overkill?

**Comment by jpkrohling** [comment]
> Perhaps come up with a general solution for this?

You mean, to be applied automatically to all properties, or as a helper function? There might be cases where spaces should be part of the value, but we could apply this to properties where the input is well-defined, like IP addresses/hostnames.

**Comment by black-adder** [comment]
a helper function so as to not to copy `stripWhitespace` function everywhere.

**Comment by annanay25** [comment]
@black-adder was this issue fixed with #1305?

**Comment by pavolloffay** [comment]
Yeah I think it was, please reopen if it still has to be solved.
