### ISSUE TITLE
What's the cassandra query to fetch spans and the relationship between these spans?

### ISSUE THREAD

**Issue by gvkarthik93** [jaegertracing/jaeger#1303]
I am trying to figure out the cassandra query to fetch all spans and the relationship between these spans, including span times. If span A is parent of span B, then I'd like to fetch that information from the cassandra database and do some processing.

When I try running the query "select * from jaeger_v1_test.duration_index" I get all the spans, their dates and duration. But I am unable to get the correlation between the spans. Since I am fairly new to cassandra, any insights on this are highly appreciated.

**Comment by yurishkuro** [comment]
Cassandra stores raw span data. If you need to infer relationships between spans you can fetch the whole trace (all spans) and inspect their span references. And you may want to query jaeger-query API for that instead of going through Cassandra.

**Comment by gvkarthik93** [comment]
@yurishkuro I have tried querying "http://localhost:16686/api/traces/aa2d430a3fe5824c?prettyPrint=true" and I have received all the spans related to this specific trace ID "aa2d430a3fe5824c". What's the right way to query such that, I get spans and trace data for all the tracers?

**Comment by yurishkuro** [comment]
I think if you're trying to get data for _all traces_ you may be doing something wrong. Considering that traces are a continuous stream of data, new always coming in, old ones TTL-ing out, what does "all traces" even mean?

If your data set is small (and static?), you can potentially do a query for all service names and they query for all traces for a given service name, but you will quickly run into payload size limits. You will also get the same traces returned for many services, so you'd need to dedupe them.

If you describe what you're actually trying to solve, there may be better solutions.

**Comment by gvkarthik93** [comment]
I totally agree with the point. What I am trying to achieve is to get the trace data between a certain time period. That is, let's say I have a service running every 2 hours. I need to get the trace data for those 2 hours. When I mean trace data, what I am trying to extract is the spans for a particular service in that 2 hours period of time along with the relationship.

So when I query "http://localhost:16686/api/traces/aa2d430a3fe5824c?prettyPrint=true" like mentioned above, I am getting all the spans information related to that specific trace ID. I could also get the parent child relationship for that particular trace ID.

What I am trying to achieve is to fetch the same information for all the trace IDs in that specific 2 hour time period. Any insights are highly appreciated.

**Comment by yurishkuro** [comment]
my suggestion to query by service names would work, but will result in duplicates. I don't think there's any  other way, since Cassandra schema is not optimized for your query pattern.

If you know that all traces originate from a particular service, then you can query only that service and you won't get duplicates.

The query API allows time range. You can check Chrome Inspector to see which API calls the Jaeger UI makes.
