### ISSUE TITLE
Unable to get any traces

### ISSUE THREAD

**Issue by linuxsreeram** [jaegertracing/jaeger#1313]
Hi Team,

We have 3 node cassandra clustered environment in our infrastructure. We are having basic monitoring for that using nagios. Am trying to trace operations on cassandra using Jaegertracing. Below is my setup.

Installed 3 node Cassandra clustered environment on local machine. - Not container
Manually created schemas as per v001.cql.tmpl file.
Using below docker command ran jaeger-collector 

```
root@tcg-1:~# docker run -d --name jaeger-collector-new -e COLLECTOR_ZIPKIN_HTTP_PORT="9411" -p 14267:14267 -p 14268:14268 -p 9411:9411 jaegertracing/jaeger-collector  "--cassandra.servers=110.110.112.249" "--cassandra.keyspace=jaeger_v1_gld"
3d9a87f4fceba69ced12178fe9ac51e584befad268231886ca77d3ec08d19623
root@tcg-1:~#
root@tcg-1:~#
root@tcg-1:~#
root@tcg-1:~# docker logs -f 3d9a87f4fceba69ced12178fe9ac51e584befad268231886ca77d3ec08d19623
{"level":"info","ts":1549253137.2898624,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":14269,"status":"unavailable"}
{"level":"info","ts":1549253137.3631902,"caller":"cassandra/factory.go:92","msg":"Cassandra archive storage configuration is empty, skipping"}
{"level":"info","ts":1549253137.3682902,"caller":"static/strategy_store.go:79","msg":"No sampling strategies provided, using defaults"}
{"level":"info","ts":1549253137.3849761,"caller":"collector/main.go:139","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"info","ts":1549253137.3852139,"caller":"grpcserver/grpc_server.go:64","msg":"Starting jaeger-collector gRPC server","grpc-port":"14250"}
{"level":"info","ts":1549253137.3854196,"caller":"collector/main.go:153","msg":"Registering metrics handler with HTTP server","route":"/metrics"}
{"level":"info","ts":1549253137.3856714,"caller":"collector/main.go:162","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1549253137.3857908,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1549253137.4350293,"caller":"collector/main.go:237","msg":"Listening for Zipkin HTTP traffic","zipkin.http-port":9411}
```

**Jaeger-query:**
```
root@tcg-1:~# docker run -d --name jaeger-query-new -p 16686:16686 jaegertracing/jaeger-query  "--cassandra.servers=110.110.112.249" "--cassandra.keyspace=jaeger_v1_gld"
2834e0e647f755f96b4af995bb217eed61fedda47841fe56e3c4857fafe128bf
root@tcg-1:~# docker logs -f 2834e0e647f755f96b4af995bb217eed61fedda47841fe56e3c4857fafe128bf
{"level":"info","ts":1549253216.8550189,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":16687,"status":"unavailable"}
{"level":"info","ts":1549253216.9610865,"caller":"cassandra/factory.go:92","msg":"Cassandra archive storage configuration is empty, skipping"}
{"level":"info","ts":1549253216.9635487,"caller":"query/main.go:188","msg":"Archive storage not created","reason":"Archive storage not configured"}
{"level":"info","ts":1549253217.2871015,"caller":"query/main.go:136","msg":"Registering metrics handler with HTTP server","route":"/metrics"}
{"level":"info","ts":1549253217.287588,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1549253217.287819,"caller":"query/main.go:145","msg":"Starting HTTP server","port":16686}
```

**Jaeger-agent**
```
root@tcg-1:~# docker inspect 3d9a87f4fceb|grep IPA
            "SecondaryIPAddresses": null,
            "IPAddress": "172.17.0.2",
                    "IPAMConfig": null,
                    "IPAddress": "172.17.0.2",
root@tcg-1:~#
root@tcg-1:~#
root@tcg-1:~# docker run -d -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp -p5778:5778/tcp --name jaeger-agent-new jaegertracing/jaeger-agent --collector.host-port=172.17.0.2:14267
efdd32e667bde9b0031eb2616d531278da1f32df7e123258d163fde81c694d95
root@tcg-1:~# docker logs -f efdd32e667bde9b0031eb2616d531278da1f32df7e123258d163fde81c694d95
{"level":"warn","ts":1549253290.6280758,"caller":"tchannel/flags.go:72","msg":"Using deprecated configuration","option":"collector.host-port"}
{"level":"info","ts":1549253290.6346247,"caller":"tchannel/builder.go:97","msg":"Enabling service discovery","service":"jaeger-collector"}
{"level":"info","ts":1549253290.6349947,"caller":"peerlistmgr/peer_list_mgr.go:111","msg":"Registering active peer","peer":"172.17.0.2:14267"}
{"level":"info","ts":1549253290.6362836,"caller":"agent/main.go:89","msg":"Registering metrics handler with HTTP server","route":"/metrics"}
{"level":"info","ts":1549253290.6365654,"caller":"agent/main.go:93","msg":"Starting agent"}
{"level":"info","ts":1549253290.6369984,"caller":"app/agent.go:68","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1549253291.6368492,"caller":"peerlistmgr/peer_list_mgr.go:157","msg":"Not enough connected peers","connected":0,"required":1}
{"level":"info","ts":1549253291.6377785,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"172.17.0.2:14267"}
{"level":"info","ts":1549253291.6958845,"caller":"peerlistmgr/peer_list_mgr.go:176","msg":"Connected to peer","host:port":"[::]:14267"}
^C
root@tcg-1:~#
```

I could not see any traces on Jaeger-UI
Attached
![cassandra-jaegertrace](https://user-images.githubusercontent.com/39903910/52189788-cb0b5600-2860-11e9-8624-1659323a1d47.PNG)

--------------
Could you please guide me where am missing.

**Comment by linuxsreeram** [comment]
Logs from jaeger-query - error
{"level":"info","ts":1549253216.8550189,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":16687,"status":"unavailable"}
{"level":"info","ts":1549253216.9610865,"caller":"cassandra/factory.go:92","msg":"Cassandra archive storage configuration is empty, skipping"}
{"level":"info","ts":1549253216.9635487,"caller":"query/main.go:188","msg":"Archive storage not created","reason":"Archive storage not configured"}
{"level":"info","ts":1549253217.2871015,"caller":"query/main.go:136","msg":"Registering metrics handler with HTTP server","route":"/metrics"}
{"level":"info","ts":1549253217.287588,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1549253217.287819,"caller":"query/main.go:145","msg":"Starting HTTP server","port":16686}
{"level":"error","ts":1549258823.90714,"caller":"zap/logger.go:33","msg":"error when flushing the buffer: write udp 127.0.0.1:56895->127.0.0.1:6831: write: connection refused","stacktrace":"github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap.(*Logger).Error\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap/logger.go:33\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:257\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:267"}
^C

**Comment by yurishkuro** [comment]
have you tried https://www.jaegertracing.io/docs/1.9/troubleshooting/?

**Comment by pavolloffay** [comment]
I am closing this as it seems outdatted. If there are still issue please re-open or comment.

**Comment by aditya-wework** [comment]
level":"info","ts":1613572937.3705058,"caller":"peerlistmgr/peer_list_mgr.go:176","msg":"Connected to peer","host:port":"[::]:14267"} ... getting this error on running ./scripts/jaeger-all-in-one.sh command.
