### ISSUE TITLE
No way of profiling jaeger-collector

### ISSUE THREAD

**Issue by konradgaluszka** [jaegertracing/jaeger#1315]
Hi,
I was analyzing performance of jaeger-collector to see what objects are allocated and what are the method times after running jaeger under high load.

 I've noticed there is no pprof endpoints registered, so I've had to add it and build image myself.

Are there any methods (other than pprof) that you use for profiling?

I can create PR with my changes.

Something similar to this:
```
r := mux.NewRouter()
r.HandleFunc("/debug/pprof/", pprof.Index)
r.HandleFunc("/debug/pprof/cmdline", pprof.Cmdline)
r.HandleFunc("/debug/pprof/profile", pprof.Profile)
r.HandleFunc("/debug/pprof/symbol", pprof.Symbol)
r.HandleFunc("/debug/pprof/trace", pprof.Trace)
r.Handle("/debug/pprof/goroutine", pprof.Handler("goroutine"))
r.Handle("/debug/pprof/heap", pprof.Handler("heap"))
r.Handle("/debug/pprof/threadcreate", pprof.Handler("threadcreate"))
r.Handle("/debug/pprof/block", pprof.Handler("block"))

apiHandler := app.NewAPIHandler(jaegerBatchesHandler)
apiHandler.RegisterRoutes(r)
```

Regards, Konrad G

**Comment by black-adder** [comment]
please do!

**Comment by yurishkuro** [comment]
We internally build a different binary, where we had profiling endpoints. Feel free to create a PR to add them.

My only open question is whether we need a separate admin port for these things.

**Comment by jpkrohling** [comment]
> My only open question is whether we need a separate admin port for these things.

Yes. We don't want the wide world to access those profiling endpoints :-) They can be added to the same "healthcheck" port, as those are also meant to be admin-only.

**Comment by yurishkuro** [comment]
What about /metrics? Does it fall in the same category?

**Comment by jpkrohling** [comment]
I would say so, yes.
