### ISSUE TITLE
Wrong starttime value for some spans

### ISSUE THREAD

**Issue by bhavin192** [jaegertracing/jaeger#1316]
## Problem - what in Jaeger blocks you from solving the requirement?
For some of the spans the timestamp of `startTime` is wrong, which shows wrong sequence of spans for a particular trace in the UI. 

I'm using Jaeger 1.9 and jaeger-client-python from master branch

## Steps tried to debug the issue
To debug this I started with the jaeger-python-client and added some debug statements on top of tag 1.9
1. Added the `span.start_time` as tag while creating the span in the application 
2. In the agent added some debug statements where I can see the timestamp generated by the python client and the value agent receives are the same 
https://github.com/bhavin192/jaeger/commit/6d34b580a89c5c7c6c6d44efa8ece11e28bec7ae#diff-9d7f45efbcc36e509f799574dbb20fcfR138
3. Later I added some debug statements in the places where conversion of timestamp from microseconds to time.Time happens. These utility functions are seem to be working fine as they should
https://github.com/bhavin192/jaeger/commit/6d34b580a89c5c7c6c6d44efa8ece11e28bec7ae#diff-0b06a649eb774a7c9111ef25473304e6R27
https://github.com/bhavin192/jaeger/commit/6d34b580a89c5c7c6c6d44efa8ece11e28bec7ae#diff-0b06a649eb774a7c9111ef25473304e6R35
4. After this I added some debug statements in the memory.go where the actual Get and Write happens. 
https://github.com/bhavin192/jaeger/commit/6d34b580a89c5c7c6c6d44efa8ece11e28bec7ae#diff-e758f2d5fbad61b0317d57bc1a49eaa5R147
https://github.com/bhavin192/jaeger/commit/6d34b580a89c5c7c6c6d44efa8ece11e28bec7ae#diff-e758f2d5fbad61b0317d57bc1a49eaa5R160

According to 4 I can see the `startTime` while `WriteSpan` writes the span is correct. But the `startTime` when `GetSpan` happens for the same `spanID`, the value differs from the value it wrote some time ago.

Here are the lines from the log:
```
...
BUG: in WriteTrace: spanID: 46f12b0cee89522e, starttime: 2019-02-06 10:13:35.264481 +0000 UTC
...
BUG: in GetTrace: spanID: 46f12b0cee89522e, startTime: 2019-02-06 10:13:22.0823165 +0000 UTC
...
```
Line number: 67 and 118 from log [wrong-timestamp-1.log](https://github.com/jaegertracing/jaeger/files/2836183/wrong-timestamp-1.log)

This is what the JSON for the span from UI looks like

```json
{
  "traceID": "46982520522e40d2a8b7b005e3744452",
  "spanID": "46f12b0cee89522e",
  "flags": 3,
  "operationName": "decisionengine-span",
  "references": [
    {
      "refType": "CHILD_OF",
      "traceID": "46982520522e40d2a8b7b005e3744452",
      "spanID": "cf746e047965c490"
    }
  ],
  "startTime": 1549448002082316,
  "duration": 2006022,
  "tags": [
    {
      "key": "generated-by",
      "type": "string",
      "value": "lib.tracing"
    },
    {
      "key": "start-time-debug",
      "type": "float64",
      "value": 1549448015.2644815
    }
  ],
  "logs": [],
  "processID": "p4",
  "warnings": null
}
```

**Comment by yurishkuro** [comment]
Have you checked the "raw" json? It's returned without the clock skew adjustments.

**Comment by bhavin192** [comment]
```json
{
  "traceID": "46982520522e40d2a8b7b005e3744452",
  "spanID": "46f12b0cee89522e",
  "flags": 3,
  "operationName": "decisionengine-span",
  "references": [
    {
      "refType": "CHILD_OF",
      "traceID": "46982520522e40d2a8b7b005e3744452",
      "spanID": "cf746e047965c490"
    }
  ],
  "startTime": 1549448002082316,
  "duration": 2006022,
  "tags": [
    {
      "key": "generated-by",
      "type": "string",
      "value": "lib.tracing"
    },
    {
      "key": "start-time-debug",
      "type": "float64",
      "value": 1549448015.2644815
    }
  ],
  "logs": [],
  "processID": "p4",
  "warnings": null
}
```
This is the output of `?raw=true`

**Comment by yurishkuro** [comment]
Is this happening with memory-storage only? It's possible that the clock-skew adjustment is incorrectly done in-place

**Comment by bhavin192** [comment]
I need to verify that, I was using in memory store at that time. Just came across #787 yesterday, will update according to my findings.

**Comment by bhavin192** [comment]
Did not came across this issue after switching to a different storage backend. Closing as it is duplicate of #787
