### ISSUE TITLE
Release 1.10

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#1321]
Tracking issue for release 1.10

- [x] https://github.com/jaegertracing/jaeger/pull/1309
- [x] https://github.com/jaegertracing/jaeger/pull/1319
- [x] go-bindata and static unification https://github.com/jaegertracing/jaeger/pull/1348
- [x] removing SASI index on dependencies table in Cassandra #1328

**Comment by pavolloffay** [comment]
Please add what you want to include in the release

cc) @jaegertracing/jaeger-maintainers

**Comment by annanay25** [comment]
Can we have #1312 in this release?

**Comment by pavolloffay** [comment]
@annanay25 if it is merged sure. It seems more like a refactoring for #1307 which probably won't make to 1.10 or do you need it in 1.10?

**Comment by pavolloffay** [comment]
In this release we introduce archive storage for ES. At the moment ES storage factory fails if it cannot connect to ES - this effectively means that it will fail when upgrading to 0.10 from an older version.

We should introduce the following flag to enable archive storage. This is already done for C*

```
 --es-archive.enabled                                 Enable extra storage
```

**Comment by pavolloffay** [comment]
@yurishkuro could you please have a look at #1348 and also merge #1328. 

We would like to do the release this week. We need latest changes in the operator.

**Comment by pavolloffay** [comment]
We have all issues for the release resolved I will prepare for the release and cut it today or on Monday

**Comment by yurishkuro** [comment]
I'd like to understand what's with the UI, thwre may be features we want to release.

**Comment by pavolloffay** [comment]
There is only one commit since the last UI release and the new UI hasn't been released.

**Comment by pavolloffay** [comment]
The images had been pushed but binaries are not uploaded https://travis-ci.org/jaegertracing/jaeger/builds/493823895.

I will have a look at this on Monday morning.

**Comment by pavolloffay** [comment]
It seems that use wasn't build in ` make build-all-platforms && bash ./scripts/travis/package-deploy.sh`

but `build-all-platforms` does not depend on `build_ui`

**Comment by pavolloffay** [comment]
Actually the build was fine the assets are uploaded https://github.com/jaegertracing/jaeger/releases. The are failed jobs because 
```
before_deploy:
  - make build-all-platforms && bash ./scripts/travis/package-deploy.sh
```
runs for every job even whern DEPLOY=false. We should add check on deploy env var on that line.

**Comment by pavolloffay** [comment]
- [ ] Update docs

**Comment by pavolloffay** [comment]
Closing all has been done.
