### ISSUE TITLE
When searching for a traceId(using Elasticsearch as storage) does it search in the past? 

### ISSUE THREAD

**Issue by cristianb1989** [jaegertracing/jaeger#1322]

**Comment by cristianb1989** [comment]
I've found out(after digging through source code) how to customize the time interval to search for.
Just specify this argument when starting the jaeger-query **--es.max-span-age=720h0m0s** (this will expand the search interval to 30 days)

However would be good to have have this kind of information displayed/organized in the public documentation of Jaeger https://www.jaegertracing.io/docs/1.9/ , for instance having a _Configuration section_ declared within the site.

**Comment by cristianb1989** [comment]
I've reopened this just to have the Jaeger Documentation enhanced so that it comprises also the configuration section:
https://gist.github.com/jpkrohling/a7d24b1c1e3f76eb004915464785f531

**Comment by yurishkuro** [comment]
@cristianb1989 would you like to create a PR? Documentation is in https://github.com/jaegertracing/documentation
