### ISSUE TITLE
Failed to access Cassandra storage backend which is connected right after its reboot

### ISSUE THREAD

**Issue by iori-yja** [jaegertracing/jaeger#1331]
## Requirement - what kind of business use case are you trying to solve?
I put a cassandra server and jaeger-collector & -query all together in one server. After the server's reboot, the system is wanted to boot up gracefully and automatically.

### current behavior
After the reboot, cassandra boots up after initialization work besides jaeger-collector and -query boots up very quickly. By this time gap, jaeger containers boot & exit for a while until cassandra woke up. After storage server's boot, jaeger containers succeeds to connect the server.

## Problem - what in Jaeger blocks you from solving the requirement?

Even though -collector and -query eventually succeeded to connect to the storage, they fall into a _broken_ state.
_broken_ here means that the jaeger-collector and -query couldn't retrieve the data due to `gocql: no hosts available in the pool`, even though the `storageFactory` has succeeded to initialize. Restarting the containers can solve this behavior for now. (Reproducibility = always)

## Proposal - what do you suggest to solve the problem or improve the existing situation?

1. The most cheapest workaround is to exit the process on "no hosts available" error.
1. Graceful workaround is to fix the server status check correctly.
1. Another graceful check is to exit on `archiveOptions()` checks' failure.

## Log

Here is a part of the long log outputs which starts from the last failed attempt of storage client initialization in the restarting loop. 

```
{"level":"info","ts":1549948198.8485098,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":16687,"status":"unavailable"}
2019/02/12 05:09:58 gocql: unable to dial control conn 172.17.0.1: dial tcp 172.17.0.1:9042: connect: connection refused
{"level":"fatal","ts":1549948198.8652992,"caller":"query/main.go:107","msg":"Failed to init storage factory","error":"gocql: unable to create session: control: unable to connect to initial hosts: dial tcp 172.17.0.1:9042: connect: connection refused","stacktrace":"main.main.func1\n\t/home/travis/gopath/src/github.com/
jaegertracing/jaeger/cmd/query/main.go:107\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/hom
e/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/sr
c/github.com/jaegertracing/jaeger/cmd/query/main.go:174\nruntime.main\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/proc.go:201"}
{"level":"info","ts":1549948202.9565132,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":16687,"status":"unavailable"}
{"level":"info","ts":1549948203.4251032,"caller":"cassandra/factory.go:92","msg":"Cassandra archive storage configuration is empty, skipping"}
{"level":"info","ts":1549948203.4257433,"caller":"query/main.go:188","msg":"Archive storage not created","reason":"Archive storage not configured"}
{"level":"info","ts":1549948203.7419398,"caller":"query/main.go:136","msg":"Registering metrics handler with HTTP server","route":"/metrics"}
{"level":"info","ts":1549948203.7420306,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1549948203.7420483,"caller":"query/main.go:145","msg":"Starting HTTP server","port":16686}
{"level":"error","ts":1549948269.191453,"caller":"app/handler.go:462","msg":"HTTP handler, Internal Server Error","error":"Error reading operation_names from storage: gocql: no hosts available in the pool","errorVerbose":"gocql: no hosts available in the pool\nError reading operation_names from storage\ngithub.com/jae
gertracing/jaeger/plugin/storage/cassandra/spanstore.(*OperationNamesStorage).GetOperations\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore/operation_names.go:93\ngithub.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore.(*OperationNamesStorage).GetOperations-fm\n
\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore/reader.go:125\ngithub.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore.(*SpanReader).GetOperations\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore/reader.go:146\ngithub.
com/jaegertracing/jaeger/storage/spanstore/metrics.(*ReadMetricsDecorator).GetOperations\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/storage/spanstore/metrics/decorator.go:110\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).getOperationsLegacy\n\t/home/travis/gopath/src/github.com/jaegertra
cing/jaeger/cmd/query/app/handler.go:172\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).getOperationsLegacy-fm\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/app/handler.go:131\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.g
o:1964\nnet/http.Handler.ServeHTTP-fm\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/h2_bundle.go:5592\ngithub.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func4\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/opentracin
g-contrib/go-stdlib/nethttp/server.go:128\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964\nnet/http.Handler.ServeHTTP-fm\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/h2_bundle.go:5592\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.
gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux/mux.go:114\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.Comp
ressHandlerLevel.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/compress.go:146\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recov
eryHandler.ServeHTTP\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/recovery.go:78\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.(*recoveryHandler).ServeHTTP\n\t<autogenerated>:1\nnet/http.serverHandler.ServeHTTP\n\t/home/travis/.gimme/versions/go1.1
1.1.linux.amd64/src/net/http/server.go:2741\nnet/http.(*conn).serve\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1847\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/asm_amd64.s:1333","stacktrace":"github.com/jaegertracing/jaeger/cmd/query/app.(*APIHandle
r).handleError\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/app/handler.go:462\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).getOperationsLegacy\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/app/handler.go:173\ngithub.com/jaegertracing/jaeger/cmd/query/app.
(*APIHandler).getOperationsLegacy-fm\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/app/handler.go:131\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964\nnet/http.Handler.ServeHTTP-fm\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd
64/src/net/http/h2_bundle.go:5592\ngithub.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func4\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:128\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travi
s/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964\nnet/http.Handler.ServeHTTP-fm\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/h2_bundle.go:5592\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964\ngithub.com/jaegertracin
g/jaeger/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux/mux.go:114\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor
/github.com/gorilla/handlers/compress.go:146\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/g
ithub.com/gorilla/handlers/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:2741\nnet/http.(*conn).serve\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1847"}
```

### versions

jaeger-query: 1.9
cassandra: 3.11.3

**Comment by jpkrohling** [comment]
> Graceful workaround is to fix the server status check correctly.

This is the right solution. I think we even mentioned this case when the health check was implemented, but never followed up.

I'm not in favor of exiting the process, as it would be at most inconsistent with how it would act in case of a storage outage.

**Comment by iori-yja** [comment]
The right solution might be fixing latent initialization check routine bug not to fall into the case of successful storage initialization with empty connection pool at start up, but this is not radical because the pool can be gone whenever.

So I agree with improving health check to check server availability. But in my use case, health check is not enough because plain docker doesn't deal with unhealthy containers. It should try self-healing, eg, reconnecting the server or something.

**Comment by jpkrohling** [comment]
> It should try self-healing, eg, reconnecting the server or something.

Not sure I understand this part. Are you saying that Jaeger won't periodically attempt to reconnect to the storage?

**Comment by iori-yja** [comment]
Sorry, it's my fault. Actually it attempts (to be honest, I confirmed this recently). What I wanted to say is that it was not enough to mark as unhealthy in general, and the server should check & retry on first attempt, but I reconsider that those things might be unnecessary.

**Comment by jpkrohling** [comment]
> What I wanted to say is that it was not enough to mark as unhealthy in general

That's true and that should be fixed. Would you be open to submitting a contribution incorporating this fix?

**Comment by iori-yja** [comment]
> Would you be open to submitting a contribution incorporating this fix?
Sure. It might be an option like `--shut-down-on-unhealthy=(none, storage, _something to monitor_, all)` and reporting the storage health. Or is this too complicated?

**Comment by jpkrohling** [comment]
No, the fix is about improving the health check. I don't think we should ever exit the process if the storage is down, as we might be able to still ingest spans and store them in memory for a period of time while the storage recovers.

**Comment by iori-yja** [comment]
OK, I will make a PR about improving the health check.

By the way, what if expiring `--cassandra.max-retry-attempts`? After the expiration, the collected data in memory won't be saved on the storage, if I am understanding correctly.

**Comment by iori-yja** [comment]
Reconnection is only tried at most `MaxRetries` times: 
https://github.com/gocql/gocql/blob/master/connectionpool.go#L508

**Comment by iori-yja** [comment]
I noticed that whether the reconnection will succeed or not is depending on `--cassandra.reconnect-interval=` value. With any shorter or longer value than 10s, it fails as described in the first post of this thread.

|interval|result|
|---|---|
|1s|  :disappointed:  |
|5s| :disappointed: |
|7s| :disappointed: |
|10s| ✓ |
|20s| :disappointed: |
|60s| :disappointed: |
|1m| :disappointed: |

(note1: ✓ = automatically reconnected) 
(note2: no configuration couldn't serve without reconnection)
(note3: waited to see its success longer than 4 * interval)

**Comment by iori-yja** [comment]
@jpkrohling 
> we might be able to still ingest spans and store them in memory for a period of time while the storage recovers.

Your were correct. The server turns out able to reconnect after expiration and that's because the retry attempt is made on every failed query. I am still not sure why the very small difference of reconnect-interval can cause the long difference of successful reconnection, but it's OK for me.

So only the remaining problem is 
> That's true and that should be fixed. Would you be open to submitting a contribution incorporating this fix?

which is slightly different problem than this issue, so I will close here.
I made another PR #1338 about the remaining one.
