### ISSUE TITLE
Move `/metrics` from the query port to internal (health-check)

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#1332]
## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger currently exposes the metrics via the main query endpoint, which might be exposed to the public internet. Ideally, the `/metrics` endpoint would be directed to the internal, admin-only port that is used by the health-check handler.

```
$ docker run -p 16686:16686 --rm jaegertracing/all-in-one:1.9 
$ curl localhost:16686/metrics 
```

**Comment by objectiser** [comment]
+1, although support for the endpoint on the existing port would need to be deprecated so not to break existing deployments.

**Comment by yurishkuro** [comment]
> support for the endpoint on the existing port would need to be deprecated so not to break existing deployments

This is quite messy to do, I prefer we require a clean cut over to the new port (#1442).
