### ISSUE TITLE
Make dependencies_v2 the default for Cassandra

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1344]
After #1328 is released:

* [x] make dependencies_v2 the default for Cassandra
* [x] make v002 schema the default
* [x] fix documentation

**Comment by pavolloffay** [comment]
I have marked `* make v002 schema the default` as done - the create schema script uses the new schema by default. 

The `make dependencies_v2 the default for Cassandra` can be also considered done - Jaeger components uses v2 if `dependencies_v2` table is present.

So is there anything apart from docs what should be done? What docs should be updated? How to migrate to v2?

cc @black-adder

**Comment by pavolloffay** [comment]
I am closing this:

* V2 schema is used by default in create schema script and docker image
* migrations steps are in changelog
* jaeger binaries automatically regognizes if v2 schema is initialized

**Comment by pavolloffay** [comment]
Just a note cassandra create schema script  creates kyespace `jaeger_v1_${datacenter}` (note V1 in name) for V1 and V2.
