### ISSUE TITLE
DAG is missing / "no service dependencies found"

### ISSUE THREAD

**Issue by FrankEppinkMsgGillardon** [jaegertracing/jaeger#1349]
## Requirement - what kind of business use case are you trying to solve?
I am trying to display the DAG i.e. the service dependencies, but as of now they are missing in our Jaeger installation.

## Problem - what in Jaeger blocks you from solving the requirement?
In the "all-in-one" deployment the DAG was working, but now with a docker-compose file based on 
https://github.com/jaegertracing/jaeger/blob/master/docker-compose/jaeger-docker-compose.yml
and using a local cassandra it is no longer working.

## Any open questions to address
As I am new to Jaeger (and Cassandra) I am struggling a bit with the following questions which would probably help me to fix the problem:
1. What is the difference between the modules **jaeger-query** and **jaeger-ui**?
2. How and where do I do the configuration as described on 
https://www.jaegertracing.io/docs/1.9/frontend-ui/
3. I tried to run https://github.com/jaegertracing/spark-dependencies but failed with 
" Failed to open native connection to Cassandra at {127.0.0.1}:9042"

Any help or information is welcome, thanks

**Comment by yurishkuro** [comment]
1. there's no such thing as `jaeger-ui` (aside from a code repository). `jaeger-query` is the microservice that hosts UI assets.

2. it is explained in the doc you linked:

> These options can be configured by a JSON configuration file. The `--query.ui-config` command line parameter of the query service must then be set to the path to the JSON file when the query service is started.

3. That's the reason you don't see the DAG, Spark job needs to generate the data first.

**Comment by FrankEppinkMsgGillardon** [comment]
Hi Yurishkuro

Thanks for your answers.

1. I thought so, but thanks for the confirmation

2. I read the doc but I don't know how to do this in a docker container. I tried to login into the running jaeger-query but failed because there seems to be no shell.
I probably could pass the config via modification of Docker file or docker-compose but I assume that this is not the cause of my problem anyway, therefore I did not spend too much effort here.

3. I tried to start the jaegertracing/spark-dependencies docker container but as written above, it fails to connect to Cassandra and currently I don't have a clue what the problem is... I tried the different envs, e.g. the following command, but it failed:
`docker run --env STORAGE=cassandra --env CASSANDRA_CONTACT_POINTS=localhost:9042 jaegertracing/spark-dependencies`

**Comment by yurishkuro** [comment]
2 - fair enough, we can point to https://www.jaegertracing.io/docs/1.9/deployment/#configuration-options from that UI config page (would you like to create a PP?)

3 - please open a ticket in jaegertracing/spark-dependencies repo or ask on Gitter chat

**Comment by FrankEppinkMsgGillardon** [comment]
Thanks for the information, I created a ticket in jaegertracing/spark-dependencies repo
https://github.com/jaegertracing/spark-dependencies/issues/57
closing this issue
