### ISSUE TITLE
Jaeger UI display spans incorrect order

### ISSUE THREAD

**Issue by OsmanAktemur** [jaegertracing/jaeger#1354]
Hi,

I deployed jaeger components to kubernetes cluster as following instructions (Production setup section).
https://github.com/jaegertracing/jaeger-kubernetes

But when i display traces, tracing timeline seems incorrect order. ServiceClient calls for ServiceA, if i go to trace details i can see correct order for spans.

![image](https://user-images.githubusercontent.com/7611781/52910241-d8cfcb00-32a5-11e9-8ac3-5dadb98890c3.png)

![image](https://user-images.githubusercontent.com/7611781/52910258-087ed300-32a6-11e9-98d4-f77b5ef75007.png)

Deployed agent as DaemonSet
JaegerClient  : https://github.com/jaegertracing/jaeger-client-csharp
Sampler : Const

Am i missing some configuration for this issue? I tried jaeger all in one docker image and it was working properly.

**Comment by black-adder** [comment]
> tracing timeline seems incorrect order

That view was not designed to show chronological ordering of spans; it's simply there to show you a birds eye view of how many spans there are for each service in the trace (it's ordered alphabetically). If you would like that view to show a chronological ordering of spans, please open a ticket in the jaeger-ui repo as a feature request.

**Comment by sanasz91mdev** [comment]
can we open a ticket for this ? @black-adder
