### ISSUE TITLE
Is it possible to make jaeger use custom HTTP header name?

### ISSUE THREAD

**Issue by veterr** [jaegertracing/jaeger#1357]
Hi. I work in a company where we already have http header (say "company-trace-id") that contains trace id. Is it possible to make Jaeger use this header name instead of uber-trace-id?

**Comment by pavolloffay** [comment]
It should be possible if it's the same length and type. 

To make it work with jaeger clients you will have to provide a custom codec implementation which parses the headers 

* https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/spi/Codec.java#L17
* https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/propagation/TextMapCodec.java

I will close this as it is not an issue. Please ask questions in https://gitter.im/jaegertracing/Lobby. You can continue the discussion here if you have more comments on this topic.

**Comment by veterr** [comment]
Thank you. I was able to do it like this

public static JaegerTracer init(String service) {
    SamplerConfiguration samplerConfig = SamplerConfiguration.fromEnv()
            .withType(ConstSampler.TYPE)
            .withParam(1);

    ReporterConfiguration reporterConfig = ReporterConfiguration.fromEnv()
            .withLogSpans(true);

    Configuration config = new Configuration(service) {
        @Override
        protected JaegerTracer.Builder createTracerBuilder(String serviceName) {
            JaegerTracer.Builder builder = new JaegerTracerBuilder(serviceName, new JaegerObjectFactory());
            return builder;
        }
    }.withSampler(samplerConfig)
    .withReporter(reporterConfig);

    return config.getTracer();
}

static class JaegerTracerBuilder extends JaegerTracer.Builder {

    public JaegerTracerBuilder(String serviceName) {
        super(serviceName);
    }

    public JaegerTracerBuilder(String serviceName, JaegerObjectFactory objectFactory) {
        super(serviceName, objectFactory);

        TextMapCodec textMapCodec =
                TextMapCodec.builder()
                        .withUrlEncoding(false)
                        .withSpanContextKey("company-rest-id")
                        .withObjectFactory(objectFactory)
                        .build();
        this.registerInjector(Format.Builtin.TEXT_MAP, textMapCodec);
        this.registerExtractor(Format.Builtin.TEXT_MAP, textMapCodec);
        TextMapCodec httpCodec =
                TextMapCodec.builder()
                        .withUrlEncoding(true)
                        .withSpanContextKey("company-rest-id")
                        .withObjectFactory(objectFactory)
                        .build();
        this.registerInjector(Format.Builtin.HTTP_HEADERS, httpCodec);
        this.registerExtractor(Format.Builtin.HTTP_HEADERS, httpCodec);
    }
}

**Comment by yurishkuro** [comment]
I don't think you need to extend anything. Get a Builder from Configuration, and call registerInjector() on the builder before constructing the tracer.

**Comment by veterr** [comment]
Thank you! Yes, you were right, I was able to do it - 

Configuration config = new Configuration(service)
        .withSampler(samplerConfig)
        .withReporter(reporterConfig);

JaegerTracer.Builder builder = config.getTracerBuilder();

JaegerObjectFactory objectFactory = new JaegerObjectFactory();
TextMapCodec textMapCodec =
        TextMapCodec.builder()
                .withUrlEncoding(false)
                .withSpanContextKey("ufs-rest-id")
                .withObjectFactory(objectFactory)
                .build();
builder.registerInjector(Format.Builtin.TEXT_MAP, textMapCodec);
builder.registerExtractor(Format.Builtin.TEXT_MAP, textMapCodec);

**Comment by yurishkuro** [comment]
Ok glad it works. Feels like it should be simpler, at least we may want to expose the object factory from the Config.

One thing I don't understand: are you saying that you already use the trace context in the exact same format as Jaeger but named differently?

Note that if you want to future proof your deployment, you may want to look in using w3c trace context format (but Jaeger clients don't support it yet). Changing header format after large roll out of tracing is very difficult.

**Comment by veterr** [comment]
We already have header, but it is in another format then Jaeger. And we want to use header generated by Jaeger instead, but with the name of that original header. So I had to customize header name only

**Comment by yurishkuro** [comment]
can you elaborate on the reasons why you want that? If the existing header in different format is already being used, then repurposing it into a different (Jaeger) format seems like a compatibility headache.

**Comment by veterr** [comment]
That header is not used, it has only started to exist and not used by anybody. We want to fill it with Jaeger content, and the old content will not be persysted any more. 
By the way, I have an issue after doing like I had written 2 days ago, i.e. registerInjector() on the builder before constructing the tracer. My spans begin to double, the second "extra" span has the same span id as the first with "_1" appended. I uploaded a screenshot - 
https://photos.google.com/share/AF1QipM6CZI3n6uTBy63vcv1jDe9dZl3ZIeBs6x8QTd_bhOJJ7eE2OtkGptr4qZSedurBg/photo/AF1QipPyc3TM_1ihmGYp_0FlI7Z_Js3MrB5EPgThfED0?key=TGRUdXd3X1czMjF2M2NmYmc5OGJSUmFZbWxUMGx3

Do you know, what can be the reason, should I submit an issue?

**Comment by veterr** [comment]
Submitted an issue https://github.com/jaegertracing/jaeger/issues/1378
