### ISSUE TITLE
Compatibility with Elasticsearch APM UI

### ISSUE THREAD

**Issue by jozef-slezak** [jaegertracing/jaeger#1365]
## Requirement - what kind of business use case are you trying to solve?

Storing to Elastic Search backend in the way that Kibana APM UI can display spans.
https://www.elastic.co/guide/en/apm/get-started/current/distributed-tracing.html

## Problem - what in Jaeger blocks you from solving the requirement?

It is more like an improvement rather than a blocking issue... (that might lead to a synergy between Jaeger and ELK).

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Use the same/similar data model as https://github.com/elastic/apm-server when storing data to ELK.

**Comment by yurishkuro** [comment]
Better links: 
  * https://www.elastic.co/guide/en/apm/get-started/current/overview.html
  * https://www.elastic.co/guide/en/apm/get-started/current/apm-data-model.html

Jaeger does not have anything that maps to E-APM's ["transactions"](https://www.elastic.co/guide/en/apm/get-started/current/transactions.html) (similar to "segments" in other APM solutions)

**Comment by pavolloffay** [comment]
We don't have plans to support this at the moment. This could be done externally with a storage plugin https://github.com/jaegertracing/jaeger/issues/638

**Comment by yurishkuro** [comment]
doesn't look like this is getting traction, closing
