### ISSUE TITLE
Make Adjusters in Query Service configurable

### ISSUE THREAD

**Issue by MichaHoffmann** [jaegertracing/jaeger#1367]
## Requirement - what kind of business use case are you trying to solve?
Asynchronous requests will sometimes lead to wrong rendering of traces because of clock-skew adjustments in the query service. If the root trace is (0ms, 10ms) and an traced action that was started asynchronously is (20ms, 25ms), it will be shifted to be contained in the interval (0ms, 10ms) approximately.

## Problem - what in Jaeger blocks you from solving the requirement?
There seems to be no way to configure the Query Service to turn off selected Adjusters. Just commenting the clock-skew adjuster made the traces look much better.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Make the used Adjusters configurable, maybe via cli-flags. 

## Any open questions to address
Is there a way to configure the adjusters that i have missed?

**Comment by black-adder** [comment]
There is a way to disable adjustment in the UI:
![image](https://user-images.githubusercontent.com/791791/53181854-5b1dff00-35c6-11e9-8d32-56c5ac1692fe.png)
However this just gives you the json blob and doesn't actually display the trace. Do you mind creating a ticket in the UI repo?

**Comment by yurishkuro** [comment]
This is a different issue. I am going to respond shortly.

**Comment by yurishkuro** [comment]
@MichaHoffmann please see this issue: #961. Configurable adjusters is one possible solution, but I don't think it's the best one.

**Comment by MichaHoffmann** [comment]
Thank you for your response! #961 and https://github.com/jaegertracing/jaeger-ui/issues/197 look like a valid solution to my problem!
