### ISSUE TITLE
Redundant flag --reporter.type=grpc when used along with --reporter.grpc.host-port?

### ISSUE THREAD

**Issue by annanay25** [jaegertracing/jaeger#1376]
## Requirement - what kind of business use case are you trying to solve?

Make agent config flags more intuitive.

## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger agent deployment as of now requires the use of `--reporter.type=grpc --reporter.grpc.host-port=host:port` to report to collector using grpc.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Remove the redundant flag as passing `--reporter.grpc.host-port=host:port` is sufficient to specify GRPC usage; similar to how `--reporter.tchannel.host-port=host:port` is sufficient to specify `tchannel` use.

## Any open questions to address
_

**Comment by pavolloffay** [comment]
> similar to how `--reporter.tchannel.host-port=host:port` is sufficient to specify `tchannel` use.

this is because of backward compatibility. Before we had only one reporter - tchannel. We will be changing default reporter to grpc in the next release https://github.com/jaegertracing/jaeger/issues/1218.

**Comment by annanay25** [comment]
Ah, that makes sense @pavolloffay 

We could in the next release, check for the presence of either `--reporter.tchannel.host-port` or `--reporter.grpc.host-port` and decide on the `reporter.type` without having the user explicitly pass the flag.

We could mark this a "good first issue".

**Comment by yurishkuro** [comment]
I prefer to keep the selector flag until we remove tchannel completely, because if we only rely on the presence of the `host-port` flag, we have an ambiguity when it's provided for both transports, and we'd need to default to one (or crash, which is perhaps better).

**Comment by pavolloffay** [comment]
@annanay25 I will close this for now. We also don't want to remove flags as it causes a breaking change so this could happen soonest with the next major version.

**Comment by annanay25** [comment]
Sure, thanks! :)
