### ISSUE TITLE
Unable to find traces that where active more then 2 days ago, because they don't pop up in UI

### ISSUE THREAD

**Issue by veterr** [jaegertracing/jaeger#1377]
Hi, I am using this solution - github.com/jaegertracing/jaeger-openshift
I can't find traces for services that where active for more then 2 days ago, because they don't pop up in UI. 
When I open Jaeger UI I only see services that had active spans for the last 2 or 3 days, in the "Service" pop up. This makes impossible to find spans, if service was inactive longer than that period. Because if I don't select service name, the "Find traces" button is not active. Is there a workaround for that problem? It is extremely important for me to find elder traces. Btw, if I send a new span for service that was long inactive, it will pop up again, and I will be able to search for all spans of this service, including very very old.

**Comment by jpkrohling** [comment]
What's your backing storage? Elasticsearch?

**Comment by veterr** [comment]
Yes, elasticsearch

**Comment by pavolloffay** [comment]
jaeger by default queries data no older than 72h. This can be changed by the following flag:

```
--es.max-span-age duration                                  The maximum lookback for spans in ElasticSearch (default 72h0m0s)
```

**Comment by veterr** [comment]
Thank you, it works

**Comment by nehagupta84** [comment]
> jaeger by default queries data no older than 72h. This can be changed by the following flag:
> 
> ```
> --es.max-span-age duration                                  The maximum lookback for spans in ElasticSearch (default 72h0m0s)
> ```

where is this configuration exactly?

**Comment by yurishkuro** [comment]
@nehagupta84 this is not the first question you asked about configuration options. They are all explained in the docs (https://www.jaegertracing.io/docs/1.17/cli/), have you looked at those? If you find that the docs are not sufficiently self-explanatory, please open tickets with suggestions how to improve them.

**Comment by nehagupta84** [comment]
if am using jaeger helm deployment then also i can apply these cli options?

**Comment by yurishkuro** [comment]
You should ask that question in the related helm repository, because it's not a Jaeger-specific question.
