### ISSUE TITLE
Allow jaeger to store logs as fields in elasticsearch

### ISSUE THREAD

**Issue by raphaelfeng** [jaegertracing/jaeger#1392]
## Requirement - what kind of business use case are you trying to solve?

Be able to search the jaeger logs in the elasticsearch kibana

## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger store the logs as nested objects which cannot be search in kibana search bar

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Have a option --es.logs-as-fields.all similar to --es.tags-as-fields.all.
--es.logs-as-fields.all=true would store all the log as fields.

## Any open questions to address
None

**Comment by yurishkuro** [comment]
I don't see how this would work given that logs are not named like the tags, and each log itself is a list of tags.

**Comment by pavolloffay** [comment]
I will close this as won't fix. If somebody has a viable solution we can re-consider this issue.
