### ISSUE TITLE
jaeger only detect itself in Find Traces

### ISSUE THREAD

**Issue by zhangzheyu2simple** [jaegertracing/jaeger#1397]
I am trying istio from catalog app on rancher2.
after deploying bookinfo app, kiali console found the interaction of bookinfo.
![image](https://user-images.githubusercontent.com/40783573/53716539-3eb87700-3e90-11e9-9759-f79ba0366f82.png)

But currently istio-tracing(jaeger) only shows monitoring of itself.
![image](https://user-images.githubusercontent.com/40783573/53716501-247e9900-3e90-11e9-8781-70a1e76d867f.png)

What should I do next?

Here are steps I take.
deploy istio from catalog.
![image](https://user-images.githubusercontent.com/40783573/53716636-84753f80-3e90-11e9-8662-6e772d8d0e48.png)
istio yaml file
```
defaultImage: true
global.hub: docker.io/istio
global.tag: 1.0.5
global.imagePullSecrets: ""
grafana.image.repository: grafana/grafana
grafana.image.tag: 5.2.3
mixer.prometheusStatsdExporter.hub: docker.io/prom
mixer.prometheusStatsdExporter.tag: v0.6.0
tracing.jaeger.hub: docker.io/jaegertracing
tracing.jaeger.tag: '1.5'
prometheus.hub: docker.io/prom
prometheus.tag: v2.3.1
global.hyperkube.hub: quay.io/coreos
global.hyperkube.tag: v1.7.6_coreos.0
kiali.hub: docker.io/kiali
kiali.tag: v0.10
certmanager.hub: quay.io/jetstack
certmanager.tag: v0.3.1
gateways.istio-ingressgateway.type: NodePort
gateways.istio-egressgateway.type: ClusterIP
tracing.enabled: true
tracing.service.type: NodePort
tracing.ingress.enabled: 'false'
'tracing.ingress.hosts[0]': xip.io
kiali.enabled: true
kiali.ingress.enabled: 'false'
'kiali.ingress.hosts[0]': xip.io
kiali.service.type: NodePort
certmanager.enabled: true
prometheus.enabled: true
prometheus.service.nodePort.enabled: true
prometheus.service.nodePort.port: ""
grafana.enabled: 'false'
grafana.service.type: NodePort
grafana.security.adminUser: admin
grafana.security.adminPassword: changeme
grafana.persistence.enabled: 'false'
grafana.persistence.size: 5Gi
grafana.persistence.storageClass: ""
global.proxy.includeIPRanges: 10.43.0.1/16
```

**Comment by zhangzheyu2simple** [comment]
1,enable 'default' namspace 
2,deploy bookinfo in 'default' namespace
3,set ingress for kiali and jaeger

**Comment by objectiser** [comment]
Here are some suggestions you can try: https://preliminary.istio.io/help/faq/distributed-tracing/#no-tracing
