### ISSUE TITLE
Why is the "span startTime" that I queried from es and JaegerUI query different?

### ISSUE THREAD

**Issue by code98** [jaegertracing/jaeger#1399]
Why is the "span startTime" that I queried from es and JaegerUI query different?

Same traceId
Same SpanId
Same Elasticsearch

Data in the ES
![image](https://user-images.githubusercontent.com/10418235/53737211-db960700-3ec6-11e9-9048-d7be1f0d891d.png)

JaegerUi, use this interface "/api/traces"

![image](https://user-images.githubusercontent.com/10418235/53737244-f9fc0280-3ec6-11e9-8e30-53133a952ad1.png)

**Comment by yurishkuro** [comment]
Possibly due to clock skew adjustment. Try with ?raw=true parameter

**Comment by code98** [comment]
> 可能是由于时钟偏差调整。尝试使用？raw = true参数

Not a time zone issue, because it is a few milliseconds

**Comment by yurishkuro** [comment]
Clock skew adjustment is not related to time zone, it's the small differences in system clocks on different servers due to clock drift. Jaeger query service, by default, attempts to correct for these differences. By adding `?raw=true` parameter to the query you instruct it not to apply this adjustment.

**Comment by code98** [comment]
> Clock skew adjustment is not related to time zone, it's the small differences in system clocks on different servers due to clock drift. Jaeger query service, by default, attempts to correct for these differences. By adding `?raw=true` parameter to the query you instruct it not to apply this adjustment.

Hi, where is the use of raw=true? There are examples.  thanks....

**Comment by code98** [comment]
> Clock skew adjustment is not related to time zone, it's the small differences in system clocks on different servers due to clock drift. Jaeger query service, by default, attempts to correct for these differences. By adding `?raw=true` parameter to the query you instruct it not to apply this adjustment.

Hello, I still don't understand what it means here. I want to query the span data in Elasticsearch. If I don't make clock adjustments, is startTime accurate? thank you!

**Comment by yurishkuro** [comment]
for example: /api/traces/665010a93ef2ee1f?raw=true&prettyPrint=true

**Comment by code98** [comment]
> Clock skew adjustment is not related to time zone, it's the small differences in system clocks on different servers due to clock drift. Jaeger query service, by default, attempts to correct for these differences. By adding `?raw=true` parameter to the query you instruct it not to apply this adjustment.

The span data I queried from Elasticsearch can be used directly on my business system without making adjustments.

**Comment by yurishkuro** [comment]
do you still have a question?
