### ISSUE TITLE
TLS with Kafka Storage Backend

### ISSUE THREAD

**Issue by MichaHoffmann** [jaegertracing/jaeger#1401]
## Requirement - what kind of business use case are you trying to solve?
I would like to use the Kafka Sorage Backend with a TLS connection.

## Problem - what in Jaeger blocks you from solving the requirement?
I looked at the source and there seem to be no flags to configure ca, cert and key.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Add options for TLS connections to the Kafka Brokers. The sarama driver does support it. 

## Any open questions to address
Did i overlook something and the possibility to use TLS with Kafka existed all along?

**Comment by yurishkuro** [comment]
Sounds like a useful enhancement. Are you interested in creating a PR? It would be similar to how we do this for ES and Cassandra.

**Comment by MichaHoffmann** [comment]
I'll try on the weekend! Thanks for your response
