### ISSUE TITLE
Only one gen_assets.go being ignored

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#1405]
There is a `.gitignore` file in `cmd/query/app/ui/actual` that ignores the `gen_assets.go` file, but there are three other files that are not ignored:
```
./cmd/query/app/ui/placeholder/gen_assets.go
./plugin/storage/es/mappings/gen_assets.go
./examples/hotrod/services/frontend/gen_assets.go
```
Should we just add a general entry in the top level `.gitignore`?

**Comment by objectiser** [comment]
cc @pavolloffay  @jpkrohling

**Comment by objectiser** [comment]
Closing after IRC discussion with @pavolloffay - this particular generated file is being ignored as iit is larger than the others.

**Comment by pavolloffay** [comment]
We were checking all these static files before migration to `esc` (exception to UI bc that is large).

The build should regenerate them as part of specific build goals.  Another thing is that for example hotrod instructions from running from source allows direct `go run ./main.go all` - so no generation step needed.

Not checking them to codebase has one advantage - it assures that `go run ..` will always use the latest verison - but it requires to run generate step before. We will have to also regenerate as part of test goal
