### ISSUE TITLE
jaeger-collector dropping spans & traces

### ISSUE THREAD

**Issue by azuretek** [jaegertracing/jaeger#1411]
## Requirement - what kind of business use case are you trying to solve?

Using `jaeger-collector` to store spans & traces in `kafka`, and then `jaeger-ingester` to store in `cassandra`.

## Problem - what in Jaeger blocks you from solving the requirement?

I'm running at least 6 `jaeger-collector` instances and after a seemingly random amount of time (in this case 7~ hours) they start dropping what seems like the majority of spans and traces.

I'm not seeing anything in the logs that indicate an issue producing/communicating to `kafka`, in fact it looks like all logging stops on all my pods.

I've configured the collectors with these settings

```
collector:
    Image:       jaegertracing/jaeger-collector:1.9.0
    Ports:       14267/TCP, 14268/TCP, 9411/TCP
    Args:
      --collector.port=14267
      --collector.http-port=14268
      --collector.zipkin.http-port=9411
      --kafka.brokers=kafka-0.broker:9092,kafka-1.broker:9092,kafka-2.broker:9092
      --kafka.encoding=protobuf
      --kafka.topic=traces
```

This is what our prometheus metrics look like when the problem is happening. The spans were dropping until I restarted all the `jaeger-collector` pods, then ~7 hours later we see the problem again and it resolves again when I restart the pods.

<img width="1327" alt="screen shot 2019-03-08 at 12 30 10 am" src="https://user-images.githubusercontent.com/17463699/54017430-d9d47980-413a-11e9-8f3a-7c7e76757f9d.png">

**Comment by yurishkuro** [comment]
There should be metrics from Kafka writer, I would check if you started getting write errors or latency.

**Comment by azuretek** [comment]
This is what the two graphs look like next to eachother.

<img width="1599" alt="screen shot 2019-03-08 at 9 47 32 am" src="https://user-images.githubusercontent.com/17463699/54046028-0b276680-4188-11e9-8dd4-eabfa161882b.png">

**Comment by yurishkuro** [comment]
old issue, haven't come up in 5yrs, closing
