### ISSUE TITLE
Collector should expose client config http server (similar to agent)

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1420]
## Requirement - what kind of business use case are you trying to solve?

Sometimes people want to use HTTP sender to submit spans from clients directly to the collector. While many Jaeger clients support that, the sampling strategies and other client configuration can only be retrieved via HTTP from the agent.

## Problem - what in Jaeger blocks you from solving the requirement?

The collector only implements TChannel version of the client config server. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

We should mount the handlers from the agent onto the collector's HTTP port.

**Comment by vaibhavjayaraman** [comment]
can i give this a shot?

**Comment by objectiser** [comment]
@vaibhavjayaraman That would be great.

**Comment by vaibhavjayaraman** [comment]
ok. i will

**Comment by yurishkuro** [comment]
This was done in https://github.com/jaegertracing/jaeger/issues/1971
