### ISSUE TITLE
how can we connect the spans in  Multithreading ?

### ISSUE THREAD

**Issue by hp0632** [jaegertracing/jaeger#1425]
## Problem ：
I want to connect the spans in Multithreading, but when I build the child span with tracer, the span of client span-kind has two ,not a one . I can't figure it out what't going on. 

I user the dependency 👍 :
` <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-spring-jaeger-web-starter</artifactId>
            <version>0.1.4</version>
        </dependency>`

the step in method is :  
Result result = restTemplate.getForObject(url, Result.class);
I just do that .

**Comment by yurishkuro** [comment]
It is completely unclear to me what you're asking. Please revisit and restate your question.

**Comment by jpkrohling** [comment]
This is probably not related to Jaeger, nor Jaeger Java Client, but to the [OpenTracing Contrib's Spring Starter for Jaeger](https://github.com/opentracing-contrib/java-spring-jaeger). Please, open the issue there, but in general, the `ScopeManager` will not work for concurrent transactions in the same thread (like in reactive applications). For such cases, it's recommended to explicitly pass the context (Scope) as part of your application code.

**Comment by jpkrohling** [comment]
I'm closing as I don't think this question belongs to this project, but feel free to reopen if you think otherwise.

**Comment by hp0632** [comment]
> This is probably not related to Jaeger, nor Jaeger Java Client, but to the [OpenTracing Contrib's Spring Starter for Jaeger](https://github.com/opentracing-contrib/java-spring-jaeger). Please, open the issue there, but in general, the `ScopeManager` will not work for concurrent transactions in the same thread (like in reactive applications). For such cases, it's recommended to explicitly pass the context (Scope) as part of your application code.

OK， I think you were right .
