### ISSUE TITLE
Jaeger Agent does not buffer spans when the Collector is unavailable 

### ISSUE THREAD

**Issue by alioklm** [jaegertracing/jaeger#1430]
## Requirement - what kind of business use case are you trying to solve?

In our environment, the Collector comes up after the Jaeger-Agent, which we deploy as a sidecar in a Kubernetes pod. This means that between the time an app in a pod starts tracing and the time the Collector is up, the traces are lost. 

## Problem - what in Jaeger blocks you from solving the requirement?

It seems that the Jaeger-Agent simply drops spans if the Collector is not available. Some of these early spans are important to understand system behaviour. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

At a minimum, I imagine the Jaeger-Agent buffering the spans in-memory (with a configurable amount of memory); if the in-memory limit is reached, drop older traces or drop new ones (also configurable?).

As a slightly mode advanced version, Jeager-Agent could also offer to write the buffered spans to disk.

**Comment by jpkrohling** [comment]
I wanted to propose a similar feature, matching the "advanced version" mentioned above by @alioklm.

The use case is: when the Collector is down, the Agent should have a way to persist the spans to disk. This is to avoid losing such spans in case the Agent process itself dies unexpectedly. 

The proposal is: 

* upon the process boot, the Jaeger Agent would look up a known directory for spans and attempt to flush them to the collector
* when the collector is out, the agent would store one span per file, with the span ID as the file name and the span JSON representation as the contents of the file. For better distribution in disk, spans might be stored in a directory starting with the first two chars of the span ID, like: 
```
${TMPDIR}/spans/73/73abf3be4c32c2b8.json
```

* if the collector is out, the agent would periodically attempt to contact the collector again
* when spans are successfully flushed to the collector, they are removed from the file system

This would require three new command line parameters to the agent: 
* flag to enable this new feature -- defaults to "disabled" (at least for the first couple of versions)
* path to the location to store the spans -- defaults to TMPDIR (/tmp in most cases)
* interval to try to flush in case of a collector outage -- defaults to 1 minute

**Comment by objectiser** [comment]
Why single file per span? Why not store in a single file and roll over to new file when reaches certain limit - also means would be easier to purge based on time order, if the disk starts filling up, depending upon the drop strategy (e.g. oldest vs most recent).

**Comment by objectiser** [comment]
Or possibly file per trace id? This may then support a tail based sampling approach at some point in the future.

**Comment by jpkrohling** [comment]
The write would probably happen in a separate go routine. Having one span per file means that we don't need any synchronization for the concurrent writes. I wouldn't bother for now about performance or about disk size, as the file storage would only be used in exceptional cases. A proper file-based storage isn't the purpose of this feature.

About tail-based sampling: this might work, if all clients are talking to the same agent instance. Currently, we don't assume this to be the case.

**Comment by objectiser** [comment]
I don't think tail based sampling would rely on a single agent - I'm guessing it would broadcast out a set of trace ids that should be reported to all agents, and if they have a fragment of the trace they would report it to the collector.

**Comment by jpkrohling** [comment]
Sounds like an interesting approach. Perhaps the directory could be the trace ID, and each span is a file? Like:

```
${TMPDIR}/spans/<first 2 chars>/<trace id>/<span id>.json
${TMPDIR}/spans/73/73abf3be4c32c2b8/73abf3be4c32c2b8.json
```

**Comment by objectiser** [comment]
+1, and purging old data could be periodically done by checking the last modified date on the trace id directory.

**Comment by pavolloffay** [comment]
Spans arrive and are sent batches - it would be better to store the whole batch instead of a single span.

> This may then support a tail based sampling approach at some point in the future.

I don't think we will do it in Jaeger given that it is supported by OC. We could rather consider looking at their agent if it supports spans buffering.

**Comment by jpkrohling** [comment]
> Spans arrive and are sent batches

That's a good point.

> it would be better to store the whole batch instead of a single span

Why would it be better, though?

**Comment by pavolloffay** [comment]
* I think it would be easier to work with if we don't need to know trace/span ids.  
* performance should be also better, there might be also OS limits on the number of files etc.

**Comment by yurishkuro** [comment]
I would suggest fixing in-memory buffering first, as we're missing a basic resiliency feature. Right now if PostBatch RPC fails, the batch is dropped (maybe after a few retries). We need to have an abstraction in place to
  * continue retrying on different connections until the post succeeds
  * at the same time managing the queue in some way, e.g. maybe we don't want the oldest batches to remain while most recent dropped (I think today we're using "drop oldest" queue).

If we get this abstraction right, it should not be difficult to allow in-memory queue to overflow to disk.

**Comment by pavolloffay** [comment]
Closing this as it will be implemented in OTEL collector.
