### ISSUE TITLE
Jaeger all-in-one is not picking service container's traces

### ISSUE THREAD

**Issue by sawansharma005** [jaegertracing/jaeger#1435]
What I want - I am running two containers 
 - Jaeger all-in-one
 - application service

and I am trying to get the tracking logs from application container into the Jaeger all-in-one container.

===================================================================
**Below is my compose file:**

version: '2'

services:  
   jaeger: 
           image: jaegertracing/all-in-one:1.10
           ports:
                   - "5775:5775/udp"
                   - "6831:6831/udp"
                   - "6832:6832/udp"
                   - "5778:5778"
                   - "16686:16686"
                   - "14268:14268"
                   - "9411:9411"         
   demo:
           build: .
           ports: 
                   - "1501:80"
           environment: 
                   - JAEGER_SERVICE_NAME=hello_service
                   - JAEGER_AGENT_HOST=jaeger
                   - JAEGER_AGENT_PORT=6831     
                   - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778

===================================================================
**Below is my docker file of demo :** 

```
# Create a container with the compiled asp.net core app.
FROM microsoft/dotnet:2.2-aspnetcore-runtime

# Create app directory
WORKDIR /app

# Copy files from the artifact staging folder on agent
#COPY out/Facility.API .
#COPY src/Core/EventBusKafka/cacert.pem .
COPY out .

ENTRYPOINT ["dotnet", "Facility.API.dll"]
```
===================================================================

For C# client of OpenTracing I instantiated it in ConfigureServices method of Startup class using below code : 

```
 private void RegisterJaeger(IServiceCollection services)
       {
           // Adds the Jaeger Tracer.
           services.AddSingleton<ITracer>(serviceProvider =>
           {
               string serviceName = serviceProvider.GetRequiredService<IHostingEnvironment>()
               .ApplicationName;

               var samplerConfiguration = new Jaeger.Configuration.SamplerConfiguration(_loggerFactory)
                   .WithType(ConstSampler.Type)
                   .WithParam(1);

               var reporterConfiguration = new Jaeger.Configuration.ReporterConfiguration(_loggerFactory)
                   .WithLogSpans(true);

               var tracer = (Tracer)new Jaeger.Configuration(serviceName, _loggerFactory)
                   .WithSampler(samplerConfiguration)
                   .WithReporter(reporterConfiguration)
                   .GetTracer();

               // Allows code that can't use DI to also access the tracer.
               GlobalTracer.Register(tracer);

               return tracer;
           });

           services.AddOpenTracing();
       }  
```
===================================================================

**Code Instrumentation :** 

```
public async Task<IActionResult> GetFacility(int? facilityId)
       {

           try
           {
               using (var scope = _tracer.BuildSpan("GetFacility").StartActive(true))
               {
                   scope.Span.SetTag("FacilityController", "GetFacility Method");
                   scope.Span.Log(demoId.HasValue ? demoId.ToString() : "1");
                   return Ok(facilityId?? 1);
               }
           }           
           catch (KeyNotFoundException)
           {
               return NotFound();
           }
           catch (Exception ex)
           {
               _logger.LogError(ex, ex.Message);
               return BadRequest();
           }
       }
```

===================================================================

**Below span logs are being generated from my application :** 

![ConatinerLogs](https://user-images.githubusercontent.com/35069795/54664139-5e46d500-4b09-11e9-82b2-c43d6b2f7f81.png)

**Comment by objectiser** [comment]
It may be a sampling issue - by default only 1 in 1000 traces are reported. Can you try setting `JAEGER_SAMPLER_TYPE=const` and `JAEGER_SAMPLER_PARAM=1` ?

**Comment by sawansharma005** [comment]
> It may be a sampling issue - by default only 1 in 1000 traces are reported. Can you try setting `JAEGER_SAMPLER_TYPE=const` and `JAEGER_SAMPLER_PARAM=1` ?

`var samplerConfiguration = new Jaeger.Configuration.SamplerConfiguration(_loggerFactory)
                   .WithType(ConstSampler.Type)
                   .WithParam(1);`

Already did that while initializing the C# client in startup class, is there another configuration for JAEGER separately ?

**Comment by objectiser** [comment]
Ah yes, sorry missed that - was just looking at the docker-compose config. Don't have any experience of the c# client so may need others to suggest things, however from a quick look at the docs, it is possible to create the tracer using just [env vars](https://github.com/jaegertracing/jaeger-client-csharp#configuration-via-environment). So might be worth trying that, and create the sampling env vars in the docker-compose file to keep all config in one place.

**Comment by yurishkuro** [comment]
Please follow the troubleshooting steps in the docs first.

**Comment by sawansharma005** [comment]
I tired to enable log in debug mode, but logs are not generating when I am running my application in container, though when I am running my my application in local machine, it works fine i.e. logs are generating and span batch is being submitted into jaeger UI.

So as far as my understanding, jaeger agent is unable to pick the spans if I am running my application in docker container.

**Comment by jpkrohling** [comment]
> logs are not generating when I am running my application in container

If you can see spans being logged to the stdout when running your application locally but *not* when running in a container environment, then it explains why you don't see spans in the Jaeger UI. If you cannot see the spans in the logs, it most likely mean they are not being reported at all.

**Comment by sawansharma005** [comment]
> > logs are not generating when I am running my application in container
> 
> If you can see spans being logged to the stdout when running your application locally but _not_ when running in a container environment, then it explains why you don't see spans in the Jaeger UI. If you cannot see the spans in the logs, it most likely means that they are not being reported at all.

I see same kind of Console.Logs in my container and locally running application. But when my application run on local IIS express spans are displayed and when my application is run using docker image spans are not shown in Jaeger.

**Below is the container info log which shows information about Jaeger client initiation**

> {  
>    "levelName":"INFO",
>    "level":20,
>    "dateTime":"2019-03-20T08:38:29.7814343Z",
>    "epochTimestampNS":1553071109781000000,
>    "data":{  
>       "tracer":"Tracer(ServiceName=Facility.API, Version=CSharp-0.2.2.0, Reporter=CompositeReporter(Reporters=RemoteReporter(Sender=UdpSender(UdpTransport=ThriftUdpClientTransport(Client=127.0.0.1:6831))), LoggingReporter(Logger=Microsoft.Extensions.Logging.Logger`1[Jaeger.Reporters.LoggingReporter])), Sampler=ConstSampler(True), IPv4=-1408172029, Tags=[jaeger.version, CSharp-0.2.2.0], [hostname, c79a0e4011cd], [ip, 172.17.0.3], ZipkinSharedRpcSpan=False, ExpandExceptionLogs=FalseUseTraceId128Bit=False)",
>       "sourceContext":"Jaeger.Configuration",
>       "message":"Initialized {tracer}"
>    }
> }
> 

**I am using Jaeger all-in-one image 1.10** 

`docker run -d --name jaeger_local -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 9411:9411 jaegertracing/all-in-one:1.10  --log-level=debug`

I am not able to get why my application container Jaeger-client is not able to send spans to Jaeger-agent of all-in-one image container ?

**Comment by yurishkuro** [comment]
> ThriftUdpClientTransport(Client=127.0.0.1:6831)

This will try to send the spans to the networking namespace of the app container, but you need to send them outside of the container, to all-in-one container. You need to configure agent host (in your case `jaeger_local`), and you also need to pass `--link jaeger_local` to the app container so that it an resolve that host name.

**Comment by sawansharma005** [comment]
> > ThriftUdpClientTransport(Client=127.0.0.1:6831)
> 
> This will try to send the spans to the networking namespace of the app container, but you need to send them outside of the container, to all-in-one container. You need to configure agent host (in your case `jaeger_local`), and you also need to pass `--link jaeger_local` to the app container so that it can resolve that host name.

@yurishkuro we have already tried it but unable to receive span on agent.
below are our configuration for docker containers

-- Jaeger all-in-one

*
docker run -d --name jaeger \
  --network dockercompose_default \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -e JAEGER_AGENT_HOST=jaeger \
  -e HOSTNAME=jaeger \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.10
*

--Jaeger Client

*
docker run --rm -it \
  --network dockercompose_default \
  --link jaeger \
  --env ASPNETCORE_URLS=http://+:5000 \
  -p1561:5000 \
  -e JAEGER_AGENT_PORT=6831 \
  -e JAEGER_SAMPLER_TYPE=const \
  -e JAEGER_SAMPLER_PARAM=1 \
  facility 
*

**Comment by yurishkuro** [comment]
JAEGER_AGENT_HOST var is passed to the wrong container, it should be passed to the application, not the all-in-one

**Comment by sawansharma005** [comment]
> JAEGER_AGENT_HOST var is passed to the wrong container, it should be passed to the application, not the all-in-one

Apoligies, as I mistakenly updated the wrong configuration.

Correct configuration:

```
 ## Jaeger all-in-one ##
docker run -d --name jaeger \
  --network dockercompose_default \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -e HOSTNAME=jaeger \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.10
  
 ## Appication API container #### 
docker run --rm -it \
  --network dockercompose_default \
  --link jaeger \
  --env ASPNETCORE_URLS=http://+:5000 \
  -p1561:5000 \
  -e JAEGER_AGENT_HOST=jaeger \
  -e JAEGER_AGENT_PORT=6831 \
  -e JAEGER_SAMPLER_TYPE=const \
  -e JAEGER_SAMPLER_PARAM=1 \
  facility
```

**Comment by PruthviKumarBK** [comment]
@sawansharma005 @yurishkuro @jpkrohling  Did you manage to solve this? I've got very similar problem however, im connecting python container to jaeger all-in-one. Seems like my python container is successfully generating spans but I cannot see them in Jaeger-UI. (Very similar to your problem above). Appreciate if you can share your results.

**Comment by vijaybirru** [comment]
@PruthviKumarBK @yurishkuro @jpkrohling 
Even am facing same issue unable to get the traces in Jaeger UI , Application is running in container properly
can you please help me, i need to implement this Jaeger on total project (Microservices in docker)
vijaykumar.birru@gmail.com

**Comment by tommy20061222** [comment]
Any updates on this issue? I did add JAEGER_AGENT_HOST, and JAEGER_AGENT_PORT to my docker-compose file, and when the application start, i can see on my application container console Jaeger.Reporter has been printed out, but under Jaeger UI, under serivices, i can only see Jaeger-query, but unable to see the service i specified in the code. Please help!!!!

**Comment by yurishkuro** [comment]
Folks, 

make sure you can run the HotROD example in your setup first. It comes with its own compose file `./examples/hotrod/docker-compose.yml`. Then try swapping hotrod for your application. If it's in another language, check the client features matrix in the docs if client in your language supports the same env variables (if not, you can always configure it programmatically).

**Comment by vijaybirru** [comment]
@yurishkuro 
cat docker-compose.yml
version: '3.3'
services:
 jaeger:
   image: jaegertracing/all-in-one:latest
   ports:
     - "6831:6831/udp"
     - "80:16686"
   networks:
     - jaeger-example
 hotrod:
   image: jaegertracing/example-hotrod:latest
   ports: 
     - "8080:8080"
   command: ["all"]
   environment:
     - JAEGER_AGENT_HOST=jaeger
     - JAEGER_AGENT_PORT=6831
   networks:
     - jaeger-example
   depends_on:
     - jaeger

networks:
 jaeger-example:
--------
am able to see jaeger UI on port 80 and hotrod application in 8080.
then i removed hotrod container
now coming to my application, its java application microservice
i added dependecy in pom.xml and as well as code, and generated jar file ,using maven clean install
then java -jar .jar(locally with out container)
i can able to see output at port 8080 and i can see traces,
but when i am doing the same for container , traces are not coming in UI
docker file
FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
COPY ${JAR_FILE} app.jar
CMD ["yum install java -y"]
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

then i created image from the docker file
after that i created container like this
docker run --rm -d --link jaeger --env JAEGER_AGENT_HOST=jaeger --env JAEGER_AGENT_PORT=6831 -p 8080:8080 jaeger-app2
not able to see traces in Jaeger UI , but application is running on 8080 port
and i tried even by docker-compose.yml 
version: '3.3'
services:
 jaeger:
   image: jaegertracing/all-in-one:latest
   ports:
     - "6831:6831/udp"
     - "80:16686"
   networks:
     - jaeger-example
 bvk:
   image: jaeger-app
   ports: 
     - "8080:8080"
   command: ["all"]
   environment:
     - JAEGER_AGENT_HOST=jaeger
     - JAEGER_AGENT_PORT=6831
   networks:
     - jaeger-example
   depends_on:
     - jaeger

networks:
 jaeger-example:
------------
application is running but not able to see traces in jaeger UI

can u please help me,,,,,

**Comment by jpkrohling** [comment]
Please, follow the [troubleshooting guide](https://www.jaegertracing.io/docs/1.14/troubleshooting/) and try it out first without Docker Compose, to make sure it's not a problem in your Docker networking setup. If you still have problems, leave a comment with your findings from the troubleshooting guide (log messages, commands you executed, ...).

**Comment by tommy20061222** [comment]
Ok, i figure it out, at least in my case.  It turns out when i initialize the jaeger reporter, i need to specifiy the sender, in this case, is the docker container named "jaeger", so here is the code:

`  var reporterConfiguration = new Configuration.ReporterConfiguration(loggerFactory)
                .WithLogSpans(true)
                .WithSender(new Configuration.SenderConfiguration(loggerFactory).WithAgentHost("jaeger"));`

Hopefully, someone can benifit from above code.

**Comment by vijaybirru** [comment]
@jpkrohling 
i followed this **https://github.com/TheManawaha/opentracing_demo.git** github page and modified my code as per it,now am able to see docker application traces in Jaeger UI
this is the docker-compose.yml
version: '2'

services:           
        jaeger: 
                image: jaegertracing/all-in-one:latest
                ports:
                        - "5775:5775/udp"
                        - "6831:6831/udp"
                        - "6832:6832/udp"
                        - "5778:5778"
                        - "16686:16686"
                        - "14268:14268"
                        - "9411:9411"
        demo:
                build: opentracing_demo/.
                ports: 
                        - "8080:8080"
                environment: 
                        - JAEGER_SERVICE_NAME=hello_service
                        - JAEGER_AGENT_HOST=jaeger
                        - JAEGER_AGENT_PORT=6831 
                        - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778


and as i said i can see traces in Jaeger UI
Now my challenge is , how can i implement jaeger agent along with my application on docker swarm
i want to see traces in UI of different applications in different nodes of swarm.
waiting for your positive reply

**Comment by jpkrohling** [comment]
Sorry, I'm not familiar with Docker Swarm, but the idea is the same: if the agent is in the same network as the nodes, just adjust the `JAEGER_AGENT_HOST` (and related env vars) to point to the agent's address.
