### ISSUE TITLE
es client afterFn should check the case of resp == nil

### ISSUE THREAD

**Issue by YEXINGZHE54** [jaegertracing/jaeger#1440]
## Proposal - what do you suggest to solve the problem or improve the existing situation?
add nil pointer check before using es response pointer, such as : https://github.com/jaegertracing/jaeger/blob/21e9ab49048740c20cb0d01893b0134ff12ce80c/pkg/es/config/config.go#L117

**Comment by objectiser** [comment]
Hi @YEXINGZHE54 , how often does this problem occur?

Do you have the logs showing the panic - just curious if there is any other information that would indicate why a nil response would be returned?

**Comment by YEXINGZHE54** [comment]
hi, nil response would be returned in some rare case when es client interacting with ES server but got some unexpected failure. In detail: inside file gopkg.in/olivere/elastic.v5/bulk.go#191, the *BulkService.Do(ctx context.Context) (*BulkResponse, error) function will return a nil response if any error happened, and then inside file gopkg.in/olivere/elastic.v5/bulk_processor.go#531, *bulkWorker.commit(ctx context.Context) function call afterFn, without checking whether resp is nil;

**Comment by objectiser** [comment]
@YEXINGZHE54 Ok thanks - would you be interested in contributing a fix for this?

**Comment by YEXINGZHE54** [comment]
OK, I would like to do it.
