### ISSUE TITLE
Failed to create ElasticSearch index with special prefix if it's already used by other application

### ISSUE THREAD

**Issue by ranetkaSt** [jaegertracing/jaeger#1443]
Hi all.
We tried to write Jaeger spans to index with specific Elasticsearch prefix that is already in use by other our applications. But we got illegal_argument_exception.

Elasticsearch version 6.6.0.
Jaeger version 1.8. But the same issue is applied for the last existing version (1.11).
As I understand, it is related with ES [removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html).

Could you explain how we can avoid this problem if we want to use the one index prefix both for Jaeger and our business applications?

Stacktrace (CUSTOM means our custom application prefix):

`{"level":"error","ts":1553519398.4433336,
"caller":"app/span_processor.go:102","msg":"Failed to save span",
"error":"Failed to create index: elastic:
Error 400 (Bad Request): Rejecting mapping update to [CUSTOM-jaeger-service-2019-03-25] as the final mapping would have more than 1 type: [CUSTOM_mapping, service]
[type=illegal_argument_exception]",
"errorVerbose":"elastic: Error 400 (Bad Request):
Rejecting mapping update to [CUSTOM-jaeger-service-2019-03-25] as the final mapping would have more than 1 type: [CUSTOM_mapping, service]
[type=illegal_argument_exception]\n
Failed to create index\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).logError\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:199
\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).createIndex\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:168
\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:135
\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:101
\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan-fm\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:88
\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:34
\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:127
\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:56
\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65\nruntime.goexit
\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/asm_amd64.s:1333","stacktrace":"github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan
\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:102\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan-fm
\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:88\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1
\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:34\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue
\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:127\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1
\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:56\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1
\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65"}.`

Thank you in advance.

**Comment by pavolloffay** [comment]
hi @ranetkaSt we do not support this use case. Indices created by jaeger should be used only by jaeger.

This  doesn't even seem to be supported by ES https://discuss.elastic.co/t/multiple-type-in-one-index-in-es-6-1/116803
