### ISSUE TITLE
Jaeger ui suggestion

### ISSUE THREAD

**Issue by wuyupengwoaini** [jaegertracing/jaeger#1448]
I have used jaeger-ui for a while, and then I found some details that can be improved during use.

1.search ui's find trace button can add a dark color so that you can see it at a glance

2. It is best to add a search function to the "dependenices" page.

3. The service name in the "dependenices" page is best not to be placed outside the circle, it is best to put it inside the circle.

4. The number of self-calls in the "dependenices" page I think can be displayed without

**Comment by rneha725** [comment]
I want to work on the first issue.

**Comment by guanw** [comment]
@wuyupengwoaini UI suggestion might better go to https://github.com/jaegertracing/jaeger-ui/issues.

**Comment by wuyupengwoaini** [comment]
@guanw  ok,I'll close this issue,and open in jaeger-ui
