### ISSUE TITLE
Move metrics related to spanFormat out of span_processor.go

### ISSUE THREAD

**Issue by guanw** [jaegertracing/jaeger#1449]
## Requirement - what kind of business use case are you trying to solve?
the span processor should not need to have knowledge of spanFormat 

## Problem - what in Jaeger blocks you from solving the requirement?
None

## Proposal - what do you suggest to solve the problem or improve the existing situation?
We should move it out of `span_processor.go` metrics and maybe to handler level?

**Comment by yurishkuro** [comment]
I don't think we're doing this.
