### ISSUE TITLE
HotRod: pool: Stop all the workers by closing the stop channel

### ISSUE THREAD

**Issue by mfrw** [jaegertracing/jaeger#1453]
## Requirement - what kind of business use case are you trying to solve?
Instead of sending a signal on the stop chan, closing the stop chan is the correct way to stop all the workers; Reading from a closed chan is always successful.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Close the `stop` channel instead of sending values to it.

**Comment by yurishkuro** [comment]
not a bug as it's not causing any issues.

**Comment by mfrw** [comment]
@yurishkuro sorry for the late reply,
IMHO, this is a bug. Assuming you have more than 1 worker, calling stop only stops 1 of the workers and not all, while as closing the chan stops all the workers. Please let me know if you still want me to rename the PR.
