### ISSUE TITLE
Why is the data received from kafka like this?

### ISSUE THREAD

**Issue by code98** [jaegertracing/jaeger#1464]
jarger version is 1.9
kafka version is 0.10
spark version is 2.3

set SPAN_STORAGE_TYPE=kafka and --kafka.encoding json, then i consume kafka message

I think the key is a traceId, the traceId and key in value are different.

The problem I encountered is the same as this issue:

https://github.com/jaegertracing/jaeger/issues/1130

![image](https://user-images.githubusercontent.com/10418235/55668055-caaa2e00-5896-11e9-8615-0b82c5d7e6ce.png)

{"traceId":"AAAAAAAAAAADtYnuz5+J/Q==","spanId":"A7WJ7s+fif0=","operationName":"a","flags":1,"startTime":"2019-04-06T10:06:25.640Z","duration":"0.032187s","tags":[{"key":"http.status_code","vType":"INT64","vInt64":"200"},{"key":"component","vStr":"java-web-servlet"},{"key":"span.kind","vStr":"server"},{"key":"sampler.type","vStr":"probabilistic"},{"key":"sampler.param","vType":"FLOAT64","vFloat64":1},{"key":"http.url","vStr":"http://localhost:8080/db/"},{"key":"http.method","vStr":"GET"}],"logs":[{"timestamp":"2019-04-06T10:06:25.642Z","fields":[{"key":"handler.class_simple_name","vStr":"DbController"},{"key":"handler","vStr":"public java.lang.String com.trace.controller.DbController.a()"},{"key":"event","vStr":"preHandle"},{"key":"handler.method_name","vStr":"a"}]},{"timestamp":"2019-04-06T10:06:25.672Z","fields":[{"key":"event","vStr":"afterCompletion"},{"key":"handler","vStr":"public java.lang.String com.trace.controller.DbController.a()"}]}],"process":{"serviceName":"demo","tags":[{"key":"hostname","vStr":"B000000137570D"},{"key":"jaeger.version","vStr":"Java-0.27.0"},{"key":"ip","vStr":"127.0.0.1"}]}}

spark code:

![image](https://user-images.githubusercontent.com/10418235/55668171-71db9500-5898-11e9-831a-0ae58aee136a.png)

**Comment by yurishkuro** [comment]
- the record key is the trace-id encoded as hex digits.
- the trace-id in the json are encoded as base64

**Comment by code98** [comment]
> * the record key is the trace-id encoded as hex digits.
> * the trace-id in the json are encoded as base64

Base64 can't decode it.

**Comment by wuyupengwoaini** [comment]
I also encountered the same problem, and unable to decrypt trace_id using base64.

**Comment by yurishkuro** [comment]
I used the following class to successfully parse the protobuf messages from Kafka written there by Jaeger collector: https://github.com/PacktPublishing/Mastering-Distributed-Tracing/blob/master/Chapter12/src/main/java/io/jaegertracing/api_v2/Model.java

The class was generated from the main model.proto file by removing gogo annotations.

**Comment by wuyupengwoaini** [comment]
@code98  you can refer the code (the method  asHexString)
https://github.com/PacktPublishing/Mastering-Distributed-Tracing/blob/master/Chapter12/src/main/java/model/ProtoUnmarshaler.java

**Comment by AudienceX** [comment]
> @code98 you can refer the code (the method asHexString)
> https://github.com/PacktPublishing/Mastering-Distributed-Tracing/blob/master/Chapter12/src/main/java/model/ProtoUnmarshaler.java

are you sure the method 'asHexString' can decode traceid like 'AAAAAAAAAADlP4sqB+IBqA==' ?
my result is '41414141414141414141446C50347371422B494271413D3D' with this method
:(

**Comment by AudienceX** [comment]
so how you resolve this ....
now I'm using Python decode traceid from kafka and :<

**Comment by yurishkuro** [comment]
See #2591.

**Comment by nata7che** [comment]
Would love to get some help as I'm not sure how to best tackle this. Also trying to read exported spans from Kafka using (Kafka-streams) and traceId and spanIds look like the above. 

I do want to keep using the original format (i.e. hex digits). Which method should I use to decode it back?

Your help is much appreciated 🙏🏻

**Comment by yurishkuro** [comment]
@sumancoder https://www.jaegertracing.io/docs/latest/faq/#why-do-jaeger-trace-ids-look-differently-in-kafka-and-in-the-ui

**Comment by nata7che** [comment]
@sumancoder we use a function to manually convert the ID to hex-encoded strings:
```
export function base64ToHex(s: string): string {
    return Buffer.from(s, 'base64').toString('hex');
}
```
