### ISSUE TITLE
JSON over HTTP REST API for Jaeger collector

### ISSUE THREAD

**Issue by jindal93** [jaegertracing/jaeger#1466]
Jaeger collector does not have a REST API to collect Jaeger Thrift spans. There is no way to send spans from browsers to Jaeger collector.

A Zipkin REST endpoint exists at 9411 port. The Zipkin spans do not support everything, just like Jaeger span. For example: Zipkin does not have a way to reference spans
https://github.com/opentracing/specification/blob/master/specification.md#references-between-spans.
And, here is an open issue for that https://github.com/openzipkin/zipkin/issues/1244

Is there a way we can directly send Jaeger span to Jaeger collector in JSON format using REST API?

**Comment by black-adder** [comment]
https://github.com/jaegertracing/jaeger/blob/master/cmd/collector/app/builder/builder_flags.go#L47 jaeger collector does have a way to submit thrift spans over http.

You are correct that we do not have a JSON over HTTP endpoint in the collector.

**Comment by jindal93** [comment]
Thrift Spans have a dependency on Thrift library. That increases the size of the web page and lots of steps to convert thrifts to Javascript compatible format.

Is there any plan to accept Jaeger spans as JSON in near future?

**Comment by black-adder** [comment]
Yes we do have plans to support JSON in the collector to unblock that exact issue. https://github.com/jaegertracing/jaeger-client-javascript/issues/1
and https://github.com/jaegertracing/jaeger/issues/773

**Comment by jindal93** [comment]
Thanks @black-adder

**Comment by ibtesamlatif2997** [comment]
HI,

Is jaeger collector accepting JSON format over HTTP collector endpoint. because I am facing same issue in 2022 :-)

Thanks

**Comment by yurishkuro** [comment]
There is http endpoint for OTLP format, I don't recall if it accepts OTLP JSON or only proto. There are no plans for Jaeger-native json.
