### ISSUE TITLE
Support for Elastisearch 7.0

### ISSUE THREAD

**Issue by yichingwu** [jaegertracing/jaeger#1481]
Since 7.0 just came out of Elasticsearch, how long will it typically take for Jaeger UI to be updated to 7.0?

**Comment by yurishkuro** [comment]
@yichingwu have you tried Jaeger with ES-7? Do you know what specifically needs to change?

**Comment by yichingwu** [comment]
@yurishkuro , I just tried to ingest Jeager data from kafka to Elasticsearch, Once ingest the data ro elasticsearch there is no error message at Jaeger Ingest, but no index exists in Elasticsearch 7.0.
when I change to Elasticsearch 6.x, it work fine.

**Comment by pavolloffay** [comment]
This is a duplicate for #1474
