### ISSUE TITLE
[query] Refactor HTTP/gRPC server creation out of main()

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1482]
https://github.com/jaegertracing/jaeger/pull/1307/files#diff-dd83d41d7df5457b194e8e5ed287cdc3R150

A lot of boilerplate added to main, without tests. We should be able to move it to a sub-package and add proper tests (specifically validating serving http & grpc on the same port).

**Comment by stefanvassilev** [comment]
Hi @yurishkuro , can i take this? :)

**Comment by yurishkuro** [comment]
By all means 🤠

**Comment by yurishkuro** [comment]
Similar PR for all-in-one https://github.com/jaegertracing/jaeger/pull/1503
