### ISSUE TITLE
How to use collector and agent as library?

### ISSUE THREAD

**Issue by koolay** [jaegertracing/jaeger#1486]
I want to integrate the collector and agent in an exist golang service.  There is any example?

**Comment by yurishkuro** [comment]
Can you explain your use case in more details? Why do you want to do that?

**Comment by koolay** [comment]
It will be better there is less services in my production.  The service was deployed privately on every customer's host.

**Comment by yurishkuro** [comment]
Unless you're using Kafka, the collectors typically write to a database. Do you really want customer processes to be writing to a shared database?

**Comment by pavolloffay** [comment]
I am closing as it is tagged as a question and there hasn't been any activity since April 2019.
