### ISSUE TITLE
what is difference between jaeger collector and jaeger agent?

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1488]
Why do you directly send trace spans to jaeger collector from jaeger client? What does jaeger agent do?

**Comment by yurishkuro** [comment]
Agents are local to the host, so the client libraries do not need to have to do any service discovery to find them. Agents mostly just forward traffic to collectors, but they can also enrich spans with extra metadata (using agent tags).

For legacy reasons, agents implement HTTP endpoints that clients use to poll for sampling strategies and other configurations. The same HTTP endpoints are not mounted on the collectors.

**Comment by teivah** [comment]
@yurishkuro Just an additional question, please. So why do we need to specify the collector endpoint in each client? I mean if the traffic is client -> agent -> collector, why should a client be aware of the collector endpoint?
Thanks

**Comment by yurishkuro** [comment]
you don't need to specify collector endpoint. If you do, the client will talk directly to collector, bypassing the agent.

**Comment by a1300** [comment]
FYI this is also documented in the [FAQ](https://www.jaegertracing.io/docs/1.21/faq/) on the documentation website
