### ISSUE TITLE
[elasticsearch] add es client healthcheckEnabled to config

### ISSUE THREAD

**Issue by mwieczorek** [jaegertracing/jaeger#1496]
## Requirement - what kind of business use case are you trying to solve?

I have Elasticsearch instance which I'd like to use as the storage backend for Jaeger. The instance is exposing only selected 'paths' (f.e. `/_bulk` for pushing data) and returns 404 for `/` (where by default the health check is done: https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L355)

I tried to disable the healthcheck (changed https://github.com/jaegertracing/jaeger/blob/master/pkg/es/config/config.go#L251 to 
`options := []elastic.ClientOptionFunc{elastic.SetURL(c.Servers...), elastic.SetSniff(c.Sniffer), elastic.SetHealthcheck(false)}`, build the collector and run it) and I was able to push traces to ES

## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger configuration for elasticsearch does not provide a way to set if healthcheck should be done or not.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I'd like to add config option similar to `Sniffer` (https://github.com/jaegertracing/jaeger/blob/master/pkg/es/config/config.go#L44) with enabled healthcheck by default with option to disable it (if set to false).

Let me know if you'd consider such change.

**Comment by pavolloffay** [comment]
I am wondering whether this is a general use-case or just your case. The health check might be used even after the initial boot up. It might be worth investigating es go client.

**Comment by yurishkuro** [comment]
Do you this one https://github.com/elastic/go-elasticsearch?

**Comment by pavolloffay** [comment]
No, we are using this https://github.com/olivere/elastic at the moment

**Comment by yurishkuro** [comment]
It may be worth migrating to the native driver (maintained by Elastic)

**Comment by mwieczorek** [comment]
Hi, as this issue is not valid for me anymore - should we close it and open a new one for:
> It may be worth migrating to the native driver (maintained by Elastic)

?

**Comment by yurishkuro** [comment]
@mwarkentin can you elaborate what changed for you that this is no longer an issue?

**Comment by mwarkentin** [comment]
I think you meant @mwieczorek. 😊

**Comment by mwieczorek** [comment]
@yurishkuro I'm using ES provided inside my org be another team, and by default, they are exposing only `_bulk` path (it's filtered on LB level). But I got an exception and I got exposed everything I need.
I don't know if such requirement would valuable to others so that's why I asked if we should close this issue.

**Comment by yurishkuro** [comment]
agreed, seems like a very specific use case. Closing.
