### ISSUE TITLE
Provide a publisher mechanism to pass stored span data to a HTTP endpoint for post-processing

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#150]
Provide a mechanism for distributing reported span data from the Jaeger server. This can be used to trigger post processing of the tracing information.

As discussed here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jaeger-tracing/2ClHbZ3BwBg/tnGVfmQbBwAJ

**Comment by objectiser** [comment]
After further thought, as mentioned in the referenced discussion, having a kafka publisher would introduce dependencies in the server app. Having the http proxy may be a good way to go in the open source project, to decouple from the technology used for processing.

So as a first step, would it be possible to provide a mechanism to publish spans via HTTP if one or more endpoints are configured?

**Comment by yurishkuro** [comment]
publish in which format?

**Comment by objectiser** [comment]
Thrift would be good.

**Comment by badiib** [comment]
Just to clarify - we would like to have an http endpoint in the collectors to save spans?

**Comment by objectiser** [comment]
Providing a REST endpoint for reporting spans is also required, but covered by this issue: https://github.com/uber/jaeger/issues/123

This issue is to publish the span data to another http endpoint for post processing purposes.

**Comment by yurishkuro** [comment]
@objectiser would like to know more about the use case that requires this.

**Comment by objectiser** [comment]
This was based on an early discussion about how Jaeger could publish spans to a data pipeline via a REST API to avoid additional dependencies in the server - however I think more recent discussions about using something like Kafka to collect spans, and persist / post-process from there, have superceded such a requirement so will close.
