### ISSUE TITLE
jaeger ingester supports customized consumer client id

### ISSUE THREAD

**Issue by newly12** [jaegertracing/jaeger#1506]
## Requirement - what kind of business use case are you trying to solve?

I'm trying to use Jaeger Ingester to consume tracing messages from Kafka.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently Ingester doesn't support specify client id. Would have to add more customization for ingester.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

na

## Any open questions to address

na

**Comment by yurishkuro** [comment]
Please elaborate what you're trying to achieve by setting a custom client-id. What is the impact of not setting anything?

**Comment by newly12** [comment]
Thanks for reply. 

According to Kafka doc client is is used for tracking purpose
> An id string to pass to the server when making requests. The purpose of this is to be able to track the source of requests beyond just ip/port by allowing a logical application name to be included in server-side request logging.

as well as quota management. https://kafka.apache.org/documentation/#design_quotasgroups
> Quotas can be applied to (user, client-id), user or client-id groups. 

In my case client is is a mandatory value, that must be set to the value that we given in order to connect to our Kafka cluster to consume messages.
