### ISSUE TITLE
Archived traces 404ing with elasticsearch storage

### ISSUE THREAD

**Issue by zdicesare** [jaegertracing/jaeger#1511]
## Problem - what in Jaeger blocks you from solving the requirement?

With archive storage configured, I am getting 404s when trying to view an archived trace in the UI.

I am running Jaeger 1.11 with elasticsearch storage, version 6.2
The UI has a config w/ archiveEnabled set to true, `--es-archive.enabled=true`, and  `ES_SERVER_URLS` and `ES_ARCHIVE_SERVER_URLS` pointing to the same cluster.

I can successfully archive a trace in the UI and can see it stored in the jaeger-span-archive index.

However, accessing a trace via direct lookup at "trace/TRACE_ID" gives a 404.

**Comment by chandresh-pancholi** [comment]
I will look into it.

**Comment by zdicesare** [comment]
Also to be clear, the trace continues to load fine via direct lookup while it's still newer than 2 days, but after that point, it fails to load when I believe it should be loading it via archive storage

**Comment by zdicesare** [comment]
I confirmed this is because of the lookback logic in the `SpanReader`.

Specifically, it is not finding traces because it is still querying `jaeger-span-archive` with a `SearchAfter(time)` configured on the `elastic.SearchSource`.

Does it sound reasonable to have a function similar to `timeRangeIndexFn` and only set `SearchAfter()` on the `SearchSource` if the span is non-archive?

**Comment by pavolloffay** [comment]
I haven't looked at the code yet. Would you like to submit a PR for it?

**Comment by pavolloffay** [comment]
I am looking into this
