### ISSUE TITLE
Use integration tests to generate coverage

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1516]
The `plugin/storage/integration` tests are using `STORAGE` env var to decide which tests to run. It makes sense for tests that require external storage, but badger/grpc-plugin are currently not running at all.

I propose the following changes:
  * always run Badger tests
  * always run grpc-plugin tests, but look for env variable pointing to the plugin binary path (to address [this comment](address https://github.com/jaegertracing/jaeger/pull/1461/files#r280031679))
  * use `-coverpkg` directive to generate test coverage for the actual packages, and merge it with overall coverage (codecov.io allows submitting multiple reports from CI job)

**Comment by Esh08** [comment]
I see that this issue has been added as a good first issue, I'm new to contributing, how may I help? Please let me know, thanks!

**Comment by yurishkuro** [comment]
Help is appreciated. What kind of assistance are you looking for?

**Comment by yurishkuro** [comment]
Perhaps an even better way would be to change the tests from using `integration` build tag to have specific tag for each storage type, so that we don't even run irrelevant tests.
