### ISSUE TITLE
Follow up on maintaining connections for grpc

### ISSUE THREAD

**Issue by guanw** [jaegertracing/jaeger#1523]
Current grpc resolver used by agent to resolve collector address doesn't have the ability to maintain connections like what `peer_list_mgr.go` did using `maintainConnections`. Need to investigate if it's necessary to do so with grpc and if it indeed is how to do it.

_Originally posted by @yurishkuro in https://github.com/jaegertracing/jaeger/pull/1498_

**Comment by yurishkuro** [comment]
I am not sure if we need something explicit for that or not. A way to try this out (could be in the unit tests) is to do this:
  * use fixed discoverer w/ 5 servers and minPeers=3
  * start sending requests, verify all 3 servers are receiving them
  * shut down one of the servers, verify that all requests are going to the other two servers
  * bring up the 3rd server again (must be on the same port), verify all 3 servers are receiving requests

**Comment by guanw** [comment]
Tested it. Roundrobin will include servers in this case. Cheers.
