### ISSUE TITLE
jaeger ui difficult to get  recent 20 traces with all-in-one

### ISSUE THREAD

**Issue by JungleYe** [jaegertracing/jaeger#1527]
just now ，I want to get recent 20 traces from about 300 traces。 but every time I get differrnt 20 traces。  when I change the query condition "Limit Results" from 20 to 500. The result is ok.

I guess :  when I use "Limit Results = 20" to search traces, the system just randomly get 20 traces form the 300 traces。 and then, sort them by "Most Recent"

How can I get the most recent 20 traces ? 

Environment :  docker + jaegertracing/all-in-one:latest

**Comment by jacobmarble** [comment]
See #1393 and proposed fix in #1394
