### ISSUE TITLE
Tracking release 1.12.0

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#1528]
We have released 1.11.0 in March 7th. I think it's time to release 1.12.0.

@jaegertracing/jaeger-maintainers are there any issues you would like to get resolved to be included in 1.12.0?

**Comment by pavolloffay** [comment]
Let's set up the release date for May 14th (if there are no issues to be resolved).

**Comment by yurishkuro** [comment]
sgtm, I only wanted to look into what docs we need to update, there are already some open PRs.

**Comment by objectiser** [comment]
Wondering whether we should have an update of the UI including https://github.com/jaegertracing/jaeger-ui/pull/375 ? Seems like it is close to merge.

**Comment by yurishkuro** [comment]
UI has 3 pages of new commits since v1.1.0 which is user by the backend. I think we need to include it in the release. I am speaking to Joe & Everett to do a new UI release.

**Comment by everett980** [comment]
Just released [Jaeger UI v1.2.0](https://github.com/jaegertracing/jaeger-ui/releases/tag/v1.2.0). Unfortunately it doesn't include [UI PR #375](https://github.com/jaegertracing/jaeger-ui/pull/375), but does have a fair deal of other changes.

**Comment by tiffon** [comment]
I'm putting together a request for changes for jaegertracing/jaeger-ui#375.
I don't think it will make this release.

**Comment by Demonian** [comment]
II think it will be great if [Kafka TLS support PR](https://github.com/jaegertracing/jaeger/pull/1414) will be merged before the release.

**Comment by pavolloffay** [comment]
@Demonian #1414 needs to be rebased and it's still not finalized. We don't want to block release on this. We will include it in the next release.

**Comment by yurishkuro** [comment]
We should edit storage docs and mention the plugin framework as well as influxdb implementation https://github.com/influxdata/jaeger-influxdb/

**Comment by pavolloffay** [comment]
released, docs were done in https://github.com/jaegertracing/documentation/pull/251

**Comment by yurishkuro** [comment]
@pavolloffay many thanks for all the leg work to get the release out
