### ISSUE TITLE
all-in-one image misses ca-certs - can not connect to cloud-based elasticsearch backend

### ISSUE THREAD

**Issue by PBug90** [jaegertracing/jaeger#1545]
## Requirement - what kind of business use case are you trying to solve?
- use all-in-one container to connect to a cloud-based elasticsearch server, which is useful for basic testing or persisting traces in a dev environment

## Problem - what in Jaeger blocks you from solving the requirement?
Missing CA-certificates do not allow connections to HTTPS-Endpoints at all.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Other docker images explicitly copy SSL-Certs into image upon building.  https://github.com/jaegertracing/jaeger/blob/d51412d5f084cba5258e8ead83dd8e4a76dae1ae/cmd/collector/Dockerfile#L6

Copy ca-certificates in all-in-one Dockerfile aswell since it is currently missing:
https://github.com/jaegertracing/jaeger/blob/master/cmd/all-in-one/Dockerfile

**Comment by pavolloffay** [comment]
done in #1554
