### ISSUE TITLE
Elasticsearch index creation is not serialized

### ISSUE THREAD

**Issue by bobrik** [jaegertracing/jaeger#1550]
I was looking through tcpdump of an ingester with elasticsearch storage backend and found that index existence is checked a lot of times. Not only that, but index is also created a lot of times.

If I change the `SpanWriter` to log every attempt:

```go
exists, _ := s.client.IndexExists(indexName).Do(s.ctx) // don't need to check the error because the exists variable will be false anyway if there is an error
fmt.Printf("checked if index exists = %v (writer = %p)\n", exists, s)
```

I can see that it's triggered 1000+ times on ingester startup:

```
checked if index exists = true (writer = 0xc000340320)
checked if index exists = true (writer = 0xc000340320)
...
```

My suggestion here is to serialize `SpanWriter::createIndex` with a mutex as there isn't really a good reason to try to do this more than once.

Thoughts?

**Comment by yurishkuro** [comment]
good catch!

**Comment by chandresh-pancholi** [comment]
I can pick it up. Any suggestions where to start.

**Comment by yurishkuro** [comment]
there's already a PR in progress #1551
