### ISSUE TITLE
Linting not catching issues in travis?

### ISSUE THREAD

**Issue by burmanm** [jaegertracing/jaeger#1557]
## Problem - what in Jaeger blocks you from solving the requirement?

While trying to run ``make`` on my machine, the go-lint part of the make fails:

make go-lint
make[1]: Entering directory '/home/michael/go/src/github.com/jaegertracing/jaeger'
Running go lint...
Lint Failures
/home/michael/go/src/github.com/jaegertracing/jaeger/cmd/agent/app/builder.go:237:15: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)

That error is real in the master, however this isn't caught for some reason in the travis. I wonder what's the correct behavior?

**Comment by yurishkuro** [comment]
@burmanm are you using the same lint?

```shell
$ golint ./cmd/agent/app/

$ go get -u golang.org/x/lint/golint
$ golint ./cmd/agent/app/

```

**Comment by yurishkuro** [comment]
(I agree that the code looks suspicious/inefficient)

**Comment by burmanm** [comment]
Apparently updating the golint to master version helps. Although I'm not sure how I had the older version installed just some days ago (I wonder if VSCode installs a modified version of golint).

```
[michael@nina jaeger]$ golint ./cmd/agent/app/
cmd/agent/app/builder.go:237:15: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
[michael@nina jaeger]$ ls -l /home/michael/go/bin/golint
-rwxr-xr-x 1 michael michael 6295815  8. 5. 15:12 /home/michael/go/bin/golint
[michael@nina jaeger]$ go get -u golang.org/x/lint/golint
[michael@nina jaeger]$ golint ./cmd/agent/app/
[michael@nina jaeger]$
```
