### ISSUE TITLE
Set Agent Host on Query Deployment

### ISSUE THREAD

**Issue by weeco** [jaegertracing/jaeger#1562]
## Requirement - what kind of business use case are you trying to solve?

After deploying the Jaeger Agents as daemonset, the collector as deployment and the query as separate deployment, the query service prints such log lines:

```
{"level":"error","ts":1558691285.7870169,"caller":"zap/logger.go:33","msg":"error when flushing the buffer: write udp 127.0.0.1:57618->127.0.0.1:6831: write: connection refused","stacktrace":"github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap.(*Logger).Error\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap/logger.go:33\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:257\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:267"}
```

## Problem - what in Jaeger blocks you from solving the requirement?

I understand that it tries to send it's own tracing spans to localhost and since I don't have an agent running there it cannot send the spans. Obviously I could deploy an agent as sidecar container but I'd prefer sending them to the agents I run on that Kubernetes node - that's why I created the agents as daemonset in the first place right?

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I expected that there is an environment variable / argument where I could set the host for the jaeger agent.

**Comment by jpkrohling** [comment]
Duplicates #1044
