### ISSUE TITLE
Exporting the Jaeger trace results 

### ISSUE THREAD

**Issue by gauravagarwal2000** [jaegertracing/jaeger#1564]
Hi All,

Sorry, I couldn't find any similar query and hence filing this issue. 

Background: Our team in using Jaeger and would like to share the results to other teams. Currenlty they are sending this by screen shots.

Is there a way i can export the Jaeger trace results in some form (http,CSV,txt) from the GUI  ?

thanks

**Comment by jpkrohling** [comment]
You can export the JSON from one system and import in another

Export:
![image](https://user-images.githubusercontent.com/13387/58331357-41948980-7e39-11e9-81f7-21160b0724e7.png)

Import:
![image](https://user-images.githubusercontent.com/13387/58331461-83bdcb00-7e39-11e9-9dad-725a65e88e3c.png)

**Comment by gauravagarwal2000** [comment]
You need Jaeger to import the exported Json file.
I am trying to find solution where that dependency is not there . 

Operations teams uses this tool to look at the traces and report any latency issues to various other teams who may or may not have the environment as they are primarily interested in latency numbers or any failures . 
Hence the request is to have results being easily exported in some easily readable format like CSV or text.

**Comment by jpkrohling** [comment]
No, we currently export only the JSON representation of the trace. This can then be loaded into any other Jaeger instance, such as one started via `docker run jaegertracing/all-in-one`.

**Comment by gauravagarwal2000** [comment]
Thanks.
Can this be extracted via API ?

**Comment by cbrgm** [comment]
I'd be interested in this option too. Anyone knows wether it's possible to extract traces stored by Jaeger via the api?

**Comment by yurishkuro** [comment]
The trace screen has a button to view/download trace JSON. The search screen has a panel to upload this JSON to the UI.

**Comment by ubaierbhat** [comment]
Is there a way to download/export graph under "Trace graph" as svg or pdf?

**Comment by yurishkuro** [comment]
@ubaierbhat I don't think so. Feel free to open a ticket in https://github.com/jaegertracing/jaeger-ui with description of the use case / requirements. I think exporting the graph in dot format might be a better option than svg/pdf, since dot file can be trivially converted to those.

**Comment by larytet** [comment]
Is there a way to export all traces from the search results?

**Comment by pavolloffay** [comment]
No only a single trace in trace detail view. Although you can get the traces from the query API. However you will not be able to easily import them.

**Comment by larytet** [comment]
@pavolloffay I am trying queries like the one below, but I am not getting hits. How do I match a duration range?
```
curl -X GET "localhost:9200/jaeger-service-2020-07-30/_search?pretty" -H 'Content-Type: application/json' -d'
{
      "query": { 
          "bool": {
              "must": [ 
                  {"match": { "serviceName": "transaction-manager" }} 
               ],
               "filter": {
                    "range": {
                          "duration": {
                                "gte": 200,
                                "lte": 40000000
                          }
                    }
              }
          }
      }
}
'
```
