### ISSUE TITLE
Command-line flags don't work with all-in-one Docker image 1.12

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1565]
I thought that we changed the ENTRY_POINT so that additional CLI flags can be provided, but it looks like none are recognized

```shell
$ docker run \
  -e SPAN_STORAGE_TYPE=badger \
  -e BADGER_EPHEMERAL=false \
  jaegertracing/all-in-one:1.12
  help

zsh: command not found: help
```

**Comment by pavolloffay** [comment]
it works for me, you probably forgot `\` at the end of image line

**Comment by yurishkuro** [comment]
![image](https://user-images.githubusercontent.com/3523016/58340060-f66a7e80-7e18-11e9-8f50-c0bf5f9e0a2b.png)
