### ISSUE TITLE
Use pflag instead of flag

### ISSUE THREAD

**Issue by JonasVerhofste** [jaegertracing/jaeger#1566]
As far as I can tell, we currently use the standard Go flag package. This has as a result that all options which actually have to be a StringArray or StringSlice, are currently just 'comma separated lists', which are just very long Strings.

This brings problems when trying to create an easy readable configuration, because the lists can't be listed as arrays. In for example the ES-plugin, this works:
```yaml
es:
  server-urls: "server1:9200, server2:9200"
```
But this doesn't:
```yaml
es:
  server-urls: 
    - "server1:9200"
    - "server2:9200"
```
[pflag](https://github.com/spf13/pflag) is a drop-in replacement for the standard flag package (and it's already used by Cobra and Viper) and would provide us to do both, leaving compatibility with the current way (i.e. the single String) intact whilst also providing the second option of declaring lists/arrays.

I see the Golang flags are eventually already parsed to pflags in `pkg/config/config.go` on [line 38](https://github.com/jaegertracing/jaeger/blob/master/pkg/config/config.go#L38), but can't we find a way to also be able to pass `*pflag.FlagSet` instead of only `*flag.FlagSet`?

That's probably going to require a lot of refactoring and I'm not even sure if it's possible (and viable) at the moment. Any comments, remarks and/or idea's?

**Comment by pavolloffay** [comment]
If the change is backward compatible +1 from my side. 

Would you be interested in submitting a PR?

**Comment by yurishkuro** [comment]
The reason we chose to use stdlib flag pkg was to avoid external dependencies in much of the code base, since only main() functions are currently aware of pflag. However, now we have many places in the code that accept Viper directly, so depending on pflag wouldn't be such a stretch either.

Having said that, it's a pretty large change, I would assume, I am quite skeptical it's worth all  the churn for a single type of property.

**Comment by JonasVerhofste** [comment]
>Having said that, it's a pretty large change, I would assume, I am quite skeptical it's worth all the churn for a single type of property.

That's exactly what I was thinking too, and it's the reason I opened this issue; discussion on the matter. I do think it's worth the effort. Pflag has some types flag doesn't have, e.g. IP's, so we could use those instead of parsing them ourselves.

>Would you be interested in submitting a PR?

I am, but I currently don't have the time. I'll take another look at it in two weeks, should have more time by then. Any suggestions on where to start?

Probably also best to make a list of components that need to be changed, so we can keep track of them.

**Comment by p0larstern** [comment]
Hey, I would like to help if no one has planned to take this up, but I am new to this community and might need guidance at some points.

**Comment by yurishkuro** [comment]
I am going to close this, there are too many changes for very little benefit.

```
./cmd/tracegen/main.go:18:	"flag"
./cmd/flags/service.go:18:	"flag"
./cmd/flags/flags.go:18:	"flag"
./cmd/flags/admin.go:19:	"flag"
./cmd/ingester/app/flags.go:18:	"flag"
./cmd/collector/app/builder/builder_flags.go:18:	"flag"
./cmd/agent/app/flags_test.go:18:	"flag"
./cmd/agent/app/reporter/flags_test.go:18:	"flag"
./cmd/agent/app/reporter/grpc/flags_test.go:18:	"flag"
./cmd/agent/app/reporter/grpc/flags.go:18:	"flag"
./cmd/agent/app/reporter/flags.go:18:	"flag"
./cmd/agent/app/reporter/tchannel/flags_test.go:18:	"flag"
./cmd/agent/app/reporter/tchannel/flags.go:18:	"flag"
./cmd/agent/app/flags.go:18:	"flag"
./cmd/agent/app/builder_test.go:19:	"flag"
./cmd/docs/command.go:18:	"flag"
./cmd/query/app/flags.go:18:	"flag"
./plugin/sampling/strategystore/factory.go:18:	"flag"
./plugin/sampling/strategystore/static/options.go:18:	"flag"
./plugin/sampling/strategystore/static/factory.go:18:	"flag"
./plugin/sampling/strategystore/adaptive/options.go:18:	"flag"
./plugin/sampling/strategystore/adaptive/factory.go:18:	"flag"
./plugin/sampling/strategystore/factory_test.go:19:	"flag"
./plugin/configurable.go:18:	"flag"
./plugin/storage/memory/options.go:18:	"flag"
./plugin/storage/memory/factory.go:18:	"flag"
./plugin/storage/grpc/options.go:18:	"flag"
./plugin/storage/grpc/factory.go:18:	"flag"
./plugin/storage/grpc/README.md:40:        "flag"
./plugin/storage/factory.go:18:	"flag"
./plugin/storage/kafka/options.go:18:	"flag"
./plugin/storage/kafka/factory.go:19:	"flag"
./plugin/storage/cassandra/options.go:18:	"flag"
./plugin/storage/cassandra/factory.go:18:	"flag"
./plugin/storage/es/options.go:18:	"flag"
./plugin/storage/es/factory.go:19:	"flag"
./plugin/storage/badger/options.go:18:	"flag"
./plugin/storage/badger/factory.go:19:	"flag"
./plugin/storage/factory_test.go:19:	"flag"
./internal/tracegen/config.go:18:	"flag"
./examples/memstore-plugin/main.go:18:	"flag"
./pkg/metrics/builder.go:20:	"flag"
./pkg/metrics/builder_test.go:19:	"flag"
./pkg/config/config.go:18:	"flag"
./pkg/config/config_test.go:18:	"flag"
./pkg/kafka/auth/options.go:18:	"flag"
```
