### ISSUE TITLE
Couchbase as storage backend

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1575]
Early prototype by @chvck 

https://github.com/jaegertracing/jaeger/issues/638#issuecomment-497776791

> I just thought that I'd drop something here to say that there is also support for using Couchbase as a storage backend (via the grpc plugin), currently at https://github.com/chvck/couchbase-jaeger-storage-plugin. Will likely move to the couchbase-labs organisation in time.

**Comment by pavolloffay** [comment]
What is the action time on this? Add to docs?

**Comment by yurishkuro** [comment]
Yes, once it's out of the prototype phase. It's also referenced from the main storage backends ticket #638, so discoverable even now.

**Comment by yurishkuro** [comment]
@chvck any updates on the status of this work?

**Comment by chvck** [comment]
Hi @yurishkuro we're currently working on trying to improve visibility of the plugin so that we can progress it further. I'm hoping to get chance to publish a combined docker image of Jaeger all-in-one and the plugin this week to make it more accessible (the Dockerfile exists already).

**Comment by yurishkuro** [comment]
@chvck any news on this?

**Comment by chvck** [comment]
@yurishkuro unfortunately very similar status to before. We have released a docker image of the Jaeger all in one plus the plugin although it's currently under my personal account. We also have a docker composer file that runs Couchbase, Jaeger and the plugin together to try make evaluation as easy as possible.

Do you have any ideas on how we can improve visibility and uptake to help drive the development forward? I should have some time in January to try make things happen.

**Comment by yurishkuro** [comment]
I think you need to have a business case for why this backend is needed. Certainly some people are more familiar with some databases than others, but that is not a strong reason to maintain a dozen implementations, same efforts would be better spent on making fewer implementations better. However, some DBs may present features that provide a unique edge in either functionality or performance. If those benefits are clearly spelled out and quantified, that may raise more interest. Otherwise for someone who stumbles upon Jaeger there is little incentive to invest time in getting an external plugin working vs. using the officially supported backends.
