### ISSUE TITLE
Rename plugin/storage/grpc to hcgrpc

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1577]
In order to support single-node in-memory storage with distributed Jaeger components  (i.e. separate collector and query-service), we need a way to access it s fully remote, which is not how hashicorp-plugin implemented in plugin/storage/grpc package works. However,  we can use the  gRPC proto schema defined for hashicorp-plugin if we wrote another built-in plugin that will translate storage API calls to gRPC requests.

That new plugin would be better called "grpc", which conflicts with the current package name.

Option 1: rename current grpc package to hcgrpc or hcplugin

Option 2: extend current /grpc storage factory to accept  `hostPort` argument which would cause  it to use normal gRPC over TCP connection to remove storage rather than running a child-process over unix socket

Option 1 gives cleaner separation, but is not backwards compatible for existing plugin implementations.

@pavolloffay @chvck @jacobmarble @jaegertracing/jaeger-maintainers

**Comment by chvck** [comment]
I can't speak for anyone else but as it's not contained in a release yet I'd say to go with option 1.

**Comment by yurishkuro** [comment]
@chvck it did go out in https://github.com/jaegertracing/jaeger/releases/tag/v1.12.0

**Comment by chvck** [comment]
Oh, I'm not sure how I missed that. Awesome! I think that makes things a bit harder but if breaking changes are OK then I do think that option 1 is still the way to go though.

**Comment by yurishkuro** [comment]
No longer needed since the `grpc-plugin` now supports both HC plugins and remote gRPC servers, based on CLI flags.
