### ISSUE TITLE
all-in-one integration test is unstable

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1583]
Build failing https://travis-ci.org/jaegertracing/jaeger/jobs/540902708#L990

```
=== RUN   TestAllInOne
--- FAIL: TestAllInOne (1.01s)
    require.go:794: 
        	Error Trace:	all_in_one_test.go:86
        	            				all_in_one_test.go:60
        	Error:      	Received unexpected error:
        	            	Get http://0.0.0.0:16686/api/traces?service=jaeger-query&tag=jaeger-debug-id:debug: dial tcp 0.0.0.0:16686: connect: connection refused
        	Test:       	TestAllInOne
FAIL
FAIL	github.com/jaegertracing/jaeger/cmd/all-in-one	1.222s
make: *** [integration-test] Error 1
```

Looking at https://github.com/jaegertracing/jaeger/blob/5b36e3bc3ccb3dccfdf42eaa0d8f0bead19dff57/cmd/all-in-one/all_in_one_test.go#L121-L129

it seems that it may not wait long enough for health check to become green. I would extend the loop to 10k iteration (10seconds).

**Comment by guanw** [comment]
Not sure about this.. Since the error was thrown on L86 where it was tryhing to `getAPITrace` instead of `healthCheck`. But I will try that in a bit.

**Comment by guanw** [comment]
Increase the loop count & sleep time don't work. I'm going to try that script on a linux vm environment see if I could reprod there.

**Comment by guanw** [comment]
Turns out this to be an issue with prometheus panic as it requires all categories sharing same structure (in this case, the tag set should also be the same) I made the fix in the original story.

**Comment by yurishkuro** [comment]
are you sure?  I thought I saw the same failure on  master.

**Comment by guanw** [comment]
i think so. The test is passing now on #1576

**Comment by yurishkuro** [comment]
OK, in that case this ticket is still relevant, in the sense that the integration test doesn't check something. For example, if your issue in #1576 was causing all-in-one to crash upon receiving a request, we should've seen it in the test somehow, e.g. by dumping logs from Docker.

**Comment by yurishkuro** [comment]
have not seen this issue for a long time, closing
