### ISSUE TITLE
when jaeger storage is elasticsearch, es don't store the dependencies

### ISSUE THREAD

**Issue by zmberg** [jaegertracing/jaeger#1584]
jaeger version: v1.12.0; elasticsearch version: 6.8.0

I setup jaeger with storage type elasticsearch on k8s to tracing istio service.
```
- name: COLLECTOR_ZIPKIN_HTTP_PORT
  value: "9411"
- name: SPAN_STORAGE_TYPE
  value: "elasticsearch"
- name: ES_SERVER_URLS
  value: "http://10.0.102.5:9200"
```
I find Jaeger UI can't search dependencies, "No service dependencies found."
So I search elasticsearch with es api, I find that there are't dependencies indices.
```
[root]# curl http://xx.xxx.xx.xx:9200/_cat/indices?v
health status index                     uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   jaeger-service-2019-06-05 ZnhYT6OeT4uaAra10F5w9w   5   1         31            0     73.3kb         73.3kb
yellow open   jaeger-span-2019-06-05    qBnt555jSGqjBd6ESip54w   5   1       2996            0    353.6kb        353.6kb
```

I want to know whether dependencies indices should exist?

**Comment by zmberg** [comment]
I look jaeger plugin memory code, i find that the memory don't store DependencyLink object, and func GetDependencies() according to the span to return []model.DependencyLink.

But the plugin es func  GetDependencies() to search es dependencies indices to return []model.DependencyLink. And there don't exist dependencies indices.

I think Jaeger collector don't call the dependencystore.Writer, because the plugin factory don't have func CreateDependencyWriter()(dependencystore.Writer, error)

So the plugin es func GetDependencies() whether is not working?

**Comment by jpkrohling** [comment]
The dependencies are calculated by an external job when using Cassandra or Elasticsearch. 
See https://www.jaegertracing.io/docs/1.12/deployment/#aggregation-jobs-for-service-dependencies
