### ISSUE TITLE
Add support for Zipkin Protobuf spans over HTTP

### ISSUE THREAD

**Issue by t03apt** [jaegertracing/jaeger#1586]
I'd like to try Jaeger for some existing applications.
They are already reporting traces to Zipkin using `Content-Type: application/x-protobuf`.
Jaeger is rejecting those calls: `400 Bad Request Unsupported Content-Type`

Please consider to create a user story for this in the feature backlog.

**Comment by yurishkuro** [comment]
@pavolloffay @jpkrohling  not sure if it's good-first-issue or not. It's not very difficult.

**Comment by jpkrohling** [comment]
For someone who is familiar with Zipkin and/or Protobuf, shouldn't be that hard.

**Comment by jan25** [comment]
@yurishkuro would you know if anyone is working on this? I could take a look otherwise

**Comment by yurishkuro** [comment]
@jan25 I am not aware of anyone working on it.
