### ISSUE TITLE
Unable to connect to  elasticsearch with tls.skip-host-verify

### ISSUE THREAD

**Issue by zsq1314** [jaegertracing/jaeger#1590]
#Requirement - what kind of business use case are you trying to solve?
Connecting to a remote Elasticsearch instance that uses self signed certs using es.tls.skip-host-verify: true 

#Problem - what in Jaeger blocks you from solving the requirement?
On 1.12 with `--es.tls.skip-host-verify`, Jaeger collector is unable to connect to an Elasticsearch host that has self signed certs even though it appears this option would allow it.
`--es.tls.skip-host-verify` does not seem to be in effect, is there a problem with my configuration?
my run command(what is wrong with my command?)：
`./jaeger-collector --es.server-urls https://xxxx:9200 --es.tls.skip-host-verify --es.tls.ca=/xxxx/cert/root-ca.pem --es.username=admin --es.password=admin`

#Any open questions to address
Stacktrace
```
{"level":"info","ts":1559807452.3122857,"caller":"flags/service.go:113","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1559807452.3125966,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1559807452.3126779,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1559807452.312698,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"fatal","ts":1559807457.376742,"caller":"collector/main.go:87","msg":"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: Head https://10.64.125.96:9200: x509: certificate is valid for 127.0.0.1, not 10.64.125.96: no Elasticsearch node available","errorVerbose":"no Elasticsearch node available\ngithub.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.init.ializers\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/client.go:88\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:188\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337\nhealth check timeout: Head https://10.64.125.96:9200: x509: certificate is valid for 127.0.0.1, not 10.64.125.96\ngithub.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.(*Client).
```

Reported also in https://github.com/jaegertracing/jaeger/issues/1582#issuecomment-499389891

**Comment by pavolloffay** [comment]
` --es.tls                                                    Enable TLS with client certificates.`

It works only with client certificates and not username/password. To make it work with name/pass requires adding it here https://github.com/jaegertracing/jaeger/blob/cb226ff60b13f1841d806278615183a4abc5e043/pkg/es/config/config.go#L272.

Note that ` --es.tls.skip-host-verify` is meant to be used only in test environments.

**Comment by secat** [comment]
@pavolloffay if we want to use TLS client certificates AND username/password, is it possible to do this?

**Comment by pavolloffay** [comment]
IIRC you can use CA cert and user/pass.
