### ISSUE TITLE
Default logging shouldn't be sampled

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#160]
Logs are sampled, and any more than ~100 logs lines per second would be dropped. 
Change this so that all logs are output.

**Comment by jpkrohling** [comment]
Is this still the case?

**Comment by yurishkuro** [comment]
that's the default in zap, so probably still an issue

**Comment by jpkrohling** [comment]
Looks like we just need to find the places we call `zap.NewProductionConfig()` and set its `Sampling` property to `nil`: 

https://github.com/uber-go/zap/blob/badef736563f8135e0add3232b06f58656da03c8/config.go#L68-L69

Looks like a good first issue to me :-)

**Comment by psinghal20** [comment]
Hi! If this issue is still up for grabs, I would love to work on this.

**Comment by jpkrohling** [comment]
@psinghal20 it's yours!
