### ISSUE TITLE
Encode gRPC logs with zap and emit to stdout

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#1602]
## Requirement - what kind of business use case are you trying to solve?

It appears that gRPC logs are not json formatted, which implies that they are not using zap

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Use zap and emit grpc logs to stdout

**Comment by yurishkuro** [comment]
grpc uses its own logging API, that needs to be wrapped to work with zap.

we can probably use this: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/logging/zap/doc.go

**Comment by yurishkuro** [comment]
There's a PR #1330 trying to address this, but it needs rebasing.
