### ISSUE TITLE
Jaeger UI display duplicated traces when using badger as storage

### ISSUE THREAD

**Issue by quaff** [jaegertracing/jaeger#1604]
![1560499208227](https://user-images.githubusercontent.com/143040/59493514-974ed580-8ebd-11e9-9782-e4530ab009d1.jpg)
There is 8 duplicated traces "1785bb6"

jaeger-1.12.0-darwin-amd64 
SPAN_STORAGE_TYPE=badger  ./jaeger-all-in-one

**Comment by yurishkuro** [comment]
Thanks for reporting.

**Comment by yurishkuro** [comment]
cc  @burmanm

**Comment by burmanm** [comment]
Yeah, I'm fixing this. I found the reason, not sure when this feature got
broken as the duplicate checking is missing a test I remember having
created..
