### ISSUE TITLE
jaeger-collector to logstash (instead of es)

### ISSUE THREAD

**Issue by dealboy** [jaegertracing/jaeger#1605]
## Requirement - what kind of business use case are you trying to solve?

Connect jaeger-collector (v1.12) to Logstash  (our infra does not allow direct access to ES instances).
I configure http input with codec es_bulk in Logstash (6.5.x) , 
spans arrive to ES (6.5.x), but jaeger-collector throws an error.
(of course tests with sending directly to ES work fine)

## Problem - what in Jaeger blocks you from solving the requirement?
jaeger-collector  throws the following error

`jaeger_jaeger-all.0.w0a8tvzhmo0m@linuxkit-00155d00050d    | {"level":"error","ts":1560514541.9948287,"caller":"config/config.go:138","msg":"Elasticsearch could not process bulk request","request_count":8,"failed_count":0,"error":"invalid character 'o' looking for beginning of value","response":null,"stacktrace":"github.com/jaegertracing/jaeger/pkg/es/config.(*Configuration).NewClient.func2\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/es/config/config.go:138\ngithub.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.(*bulkWorker).commit\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:531\ngithub.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.(*bulkWorker).work\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:468"}
`
I cannot sport related errors in ES or Logstash logs.
Only related entries are 
``elk_elasticsearch.1.re5qr12aagvh@linuxkit-00155d00050d    | [2019-06-14T11:53:33,769][INFO ][o.e.c.m.MetaDataCreateIndexService] [Cm178Q_] [logstash-ydesdev-jaeger-service-2019-06-14] creating index, cause [auto(bulk api)], templates [logstash], shards [5]/[1], mappings [_default_]
elk_elasticsearch.1.re5qr12aagvh@linuxkit-00155d00050d    | [2019-06-14T11:53:35,199][INFO ][o.e.c.m.MetaDataMappingService] [Cm178Q_] [logstash-ydesdev-jaeger-service-2019-06-14/usJC-ifYSImxIZxULqjw-w] create_mapping [doc]
elk_elasticsearch.1.re5qr12aagvh@linuxkit-00155d00050d    | [2019-06-14T11:53:35,402][INFO ][o.e.c.m.MetaDataMappingService] [Cm178Q_] [logstash-ydesdev-jaeger-span-2019-06-14/aW3BZYKATEeE0rYznKS75w] create_mapping [doc]

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I cannot figure if it is a logstash issue or collector issue. Any help please?

**Comment by yurishkuro** [comment]
Writing to logstash is not officially supported in Jaeger. I am going to close this, as I don't think realistically maintainers have time to investigate these peripheral issues. 

If you find a solution, please post it here in case other people want to do the same.
