### ISSUE TITLE
sampling problem

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1612]
can I ask when we sampling by "never",  what does it mean?  trace still have been created but they don't be collect by collector? or in this case, trace have never been created

**Comment by yurishkuro** [comment]
If a trace is not sampled, the following  holds:
  * trace and span ID are still generated at every trace point
  * trace context and baggage is still propagated over the wire
  * once spans are finished, they are discarded (not reported to collectors)
  * some client libraries make write operations on the span (set tag, add log) into no-op
