### ISSUE TITLE
what is the problem mean?

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1614]
when I send data through kafka to elasticsearch and when I click jaeger Ui it show this

jaeger_1            | {"level":"error","ts":1560996832.9520793,"caller":"zap/logger.go:33","msg":"error when flushing the buffer: write udp 127.0.0.1:54147->127.0.0.1:6831: write: connection refused","stacktrace":"github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap.(*Logger).Error\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/log/zap/logger.go:33\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:257\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:267"}

**Comment by yurishkuro** [comment]
jaeger-query itself is trying to send spans to local agent
