### ISSUE TITLE
if I send trace directly to kafka， what serialize we use can match ingester?

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1615]
If I directly send span to kafka by java, what is method to serialize?
 
                properties.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
                properties.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());

for(SpanData spanData : spanDatas){
                    ProducerRecord<String, String> record = new ProducerRecord<>(topic, spanData.toString());
                    try {
                        producer.send(record, new Callback() {
                            @Override
                            public void onCompletion(RecordMetadata recordMetadata, Exception e) {
                                if (e == null){
                                    logger.info("Received new metadata. \n" +
                                            "Topic:" + recordMetadata.topic() + "\n" +
                                            "Parition: " + recordMetadata.partition() + "\n" +
                                            "Offset: "+ recordMetadata.offset() + "\n" +
                                            "Timestamp: " + recordMetadata.timestamp());
                                }
                                else{

                                    logger.error("Error while Producing", e);
                                }
                            }
                        }).get();
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    } catch (ExecutionException e) {
                        e.printStackTrace();
                    }

**Comment by yurishkuro** [comment]
The expected format is protobuf, per `model/proto/model.proto`. There is an example of parsing the data that you can try to reverse engineer for writing: https://github.com/PacktPublishing/Mastering-Distributed-Tracing/tree/master/Chapter12/src/main/java/model
