### ISSUE TITLE
Automatically trace deleted from jaeger in memory in every 25s

### ISSUE THREAD

**Issue by Asisranjan** [jaegertracing/jaeger#1616]
## Requirement - what kind of business use case are you trying to solve?
Trying with limiting number of traces in in-memory. I am using jaegertracing/all-in-one image. Limiting maximum number of traces using MEMORY_MAX_TRACES environment variable. In my test I am testing max trace is 20

## Problem - what in Jaeger blocks you from solving the requirement?
I have generated 10 traces. all the traces are displayed in jaeger ui. Observing, in every 25seconds, one of trace is getting deleted and disappeared from Jaeger ui. 

## Any open questions to address
Why traces deleted every 25 sec. Is there any thing I am missing.

{"level":"debug","ts":1560992074.8679144,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent","bytes-received":480}
{"level":"debug","ts":1560992074.8688984,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"42bd3bf2a58089dc","span-id":"42bd3bf2a58089dc"}
{"level":"debug","ts":1560992082.867254,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent","bytes-received":801}
{"level":"debug","ts":1560992082.8686414,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"4de3bc16bc13ecb1","span-id":"4de3bc16bc13ecb1"}
{"level":"debug","ts":1560992082.8687825,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"7c6838b653f8b85a","span-id":"7c6838b653f8b85a"}
{"level":"debug","ts":1560992083.869301,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent","bytes-received":478}
{"level":"debug","ts":1560992083.8720343,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"286fec6f264c4aad","span-id":"286fec6f264c4aad"}
{"level":"debug","ts":1560992084.8662515,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent","bytes-received":478}
{"level":"debug","ts":1560992084.8676286,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"2807324975f96f27","span-id":"2807324975f96f27"}
{"level":"debug","ts":1560992085.86622,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent","bytes-received":478}
{"level":"debug","ts":1560992085.8670275,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"501118478869f4e","span-id":"501118478869f4e"}

{"level":"debug","ts":1560992112.866112,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent","bytes-received":478}
{"level":"debug","ts":1560992112.866933,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"238f39fd42961f5f","span-id":"238f39fd42961f5f"}
{"level":"debug","ts":1560992114.866202,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent","bytes-received":801}
{"level":"debug","ts":1560992114.8668005,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"63d8ed1d4d615134","span-id":"63d8ed1d4d615134"}
{"level":"debug","ts":1560992114.8669047,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"68ee1927c4768759","span-id":"68ee1927c4768759"}
{"level":"debug","ts":1560992115.866195,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent","bytes-received":478}
{"level":"debug","ts":1560992115.8671951,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"29b43c9d3b30fa4","span-id":"29b43c9d3b30fa4"}
{"level":"debug","ts":1560992160.8661075,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent","bytes-received":478}
{"level":"debug","ts":1560992160.8672228,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"36317ae7569e6806","span-id":"36317ae7569e6806"}
{"level":"debug","ts":1560992161.8670542,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent","bytes-received":480}
{"level":"debug","ts":1560992161.8681276,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"6d3242d7bb17cc70","span-id":"6d3242d7bb17cc70"}
{"level":"debug","ts":1560992178.8660352,"caller":"processors/thrift_processor.go:113","msg":"Span(s) received by the agent","bytes-received":478}
{"level":"debug","ts":1560992178.86679,"caller":"app/span_processor.go:117","msg":"Span written to the storage by the collector","trace-id":"a694265d9543df","span-id":"a694265d9543df"}

**Comment by pavolloffay** [comment]
Note that jaeger-query also generates traces which probably affects your limit.

**Comment by Asisranjan** [comment]
Thanks! That is the issue. 
Is there any configuration which will limit max traces per service?

**Comment by yurishkuro** [comment]
There is not.

**Comment by pavolloffay** [comment]
This does not appear to be an issue with Jaeger. I am closing this. 

Feel free to reopen/comment if there are other issues.
