### ISSUE TITLE
why jeager collector write to kafka fail

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1619]
I build kafka and jeager collector and jaeger agent, but when trace write by collector, it fails

docker run --rm -it -p 9092:9092 -p 2181:2181 -p 3030:3030 --network kafkanetwork1 -e KAFKA_CREATE_TOPICS=jaeger-span -e ADV_HOST=127.0.0.1 --name kafka landoop/fast-data-dev:cp3.3.0

docker run   --rm   -p5775:5775/udp   -p6831:6831/udp   -p6832:6832/udp   -p5778:5778/tcp  --network kafkanetwork1 jaegertracing/jaeger-agent  --collector.host-port=172.26.0.3:14267

docker run --rm -it --network kafkanetwork1 --name=jaeger1 -e SPAN_STORAGE_TYPE=kafka  -p 14267:14267/tcp -p 14268:14268/tcp -p 9411:9411/tcp  jaegertracing/jaeger-collector  --kafka.producer.topic=jaeger-spans  --kafka.producer.brokers=172.26.0.2:9092  

{"level":"info","ts":1561079783.4344854,"caller":"flags/service.go:104","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1561079783.4346657,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1561079783.4347298,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1561079783.4347682,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"info","ts":1561079783.435001,"caller":"kafka/factory.go:62","msg":"Kafka factory","producer builder":{"Brokers":["172.26.0.2:9092"]},"topic":"jaeger-spans"}
{"level":"info","ts":1561079783.4395738,"caller":"static/strategy_store.go:79","msg":"No sampling strategies provided, using defaults"}
{"level":"info","ts":1561079783.440585,"caller":"collector/main.go:124","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"info","ts":1561079783.4406755,"caller":"grpcserver/grpc_server.go:64","msg":"Starting jaeger-collector gRPC server","grpc-port":"14250"}
{"level":"info","ts":1561079783.4407353,"caller":"collector/main.go:143","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1561079783.4408002,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"error","ts":1561079959.5541956,"caller":"kafka/writer.go:59","msg":"dial tcp 127.0.0.1:9092: connect: connection refused","stacktrace":"github.com/jaegertracing/jaeger/plugin/storage/kafka.NewSpanWriter.func2\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/kafka/writer.go:59"}

**Comment by yurishkuro** [comment]
I am guessing it's a similar set up issue as in #1623
