### ISSUE TITLE
fails to create consumer for jaeger ingester

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1623]
jaeger-ingester_1  | 2019/06/21 15:44:25 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
jaeger-ingester_1  | {"level":"info","ts":1561131865.96192,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
jaeger-ingester_1  | {"level":"info","ts":1561131865.962353,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
jaeger-ingester_1  | {"level":"info","ts":1561131865.9625242,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14270}
jaeger-ingester_1  | {"level":"info","ts":1561131865.9625585,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14270,"health-status":"unavailable"}
jaeger-ingester_1  | {"level":"fatal","ts":1561131878.661897,"caller":"ingester/main.go:74","msg":"Unable to create consumer","error":"kafka server: Offset's topic has not yet been created.","stacktrace":"main.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/main.go:74\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/main.go:105\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200"}
jaeger-ingester_1  | 2019/06/21 15:44:39 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
jaeger-ingester_1  | {"level":"info","ts":1561131879.2189744,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
jaeger-ingester_1  | {"level":"info","ts":1561131879.2192898,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
jaeger-ingester_1  | {"level":"info","ts":1561131879.2194474,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14270}
jaeger-ingester_1  | {"level":"info","ts":1561131879.2194915,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14270,"health-status":"unavailable"}

**Comment by zheyiyi** [comment]
my docker compose file is:

version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure
    networks:
      - kafkanetwork
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
    networks:
      - kafkanetwork

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "29094:29094"
    networks:
      - kafkanetwork
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_BOB://kafka:29092,LISTENER_FRED://kafka:9092,LISTENER_ALICE://kafka:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka:29092,LISTENER_FRED://localhost:9092,LISTENER_ALICE://never-gonna-give-you-up:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT,LISTENER_ALICE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_CREATE_TOPICS: jaeger-spans
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 20
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
      KAFKA_CONTROLLER_SHUTDOWN_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - kafkanetwork
  jaeger-ingester:
    image: jaegertracing/jaeger-ingester
    ports:
      # HTTP health check port: $ curl -v http://localhost:14270/
      - "14270:14270"
      # Metrics port: $ curl http://localhost:14271/metrics
      - "14271:14271"
    restart: on-failure
    environment:
      - LOG_LEVEL=info
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - KAFKA_CONSUMER_BROKERS=kafka:29092
      # KAFKA_BROKERS=kafka:29092
      - KAFKA_CONSUMER_TOPIC=jaeger-spans
      #- METRICS_BACKEND=expvar
    networks:
      - kafkanetwork
  jaeger:
    image: jaegertracing/jaeger-query:1.8.2
    ports:
      - "16686:16686"
    restart: on-failure
    environment:
      - LOG_LEVEL=info
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    networks:
        - kafkanetwork

networks:
  kafkanetwork:
    driver: bridge

volumes:
  esdata:
    driver: local

**Comment by yurishkuro** [comment]
It looks like Kafka may not have come up before Jaeger was started, but only a guess. Pease do your own debugging before opening issues, we cannot troubleshoot everyone's unique setup.
