### ISSUE TITLE
Trace API not handling fully qualified service name

### ISSUE THREAD

**Issue by robertb724** [jaegertracing/jaeger#1626]
## Requirement - what kind of business use case are you trying to solve?

Query traces from Kiali UI

## Problem - what in Jaeger blocks you from solving the requirement?

The trace API does not handle the fully qualified name of the service

This returns an empty JSON
```
http://exposedIP/jaeger/api/traces?end=1561392158515000&limit=20&lookback=3600&maxDuration=&minDuration=&service=example-service.default&start=1561388558515000&uiEmbed=v0
```

This returns the expected JSON with traces
```
http://exposedIP/jaeger/api/traces?end=1561392158515000&limit=20&lookback=3600&maxDuration=&minDuration=&service=example-service&start=1561388558515000&uiEmbed=v0
```

The only difference is I removed the reference to the namespace, `.default`

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Allow the trace API to accept the fully qualified name of the service

I also opened an issue in Kiali
https://github.com/kiali/kiali/issues/1180

**Comment by yurishkuro** [comment]
Have you tried url-encoding the services name? I don't think dot remains a dot in that case.

Also, it's possible that ES doesn't like the dot, as it uses dots as hierarchy separator.

**Comment by pavolloffay** [comment]
It seems more like the service `example-service.default` is reported to jaeger as `example-service` (without default).

@robertb724 can you please confirm this? Open Jaeger UI and the service should be listed in the drop-down. Do not forget to use a wide time range to make sure there are data from that service.

**Comment by pavolloffay** [comment]
Actually you confirmed that in your original post. The fix  should be done in kiali (remove `.default`) or in istio  (to include `.default`)
