### ISSUE TITLE
Support autocomplete by indexing tags and values for a given service and operation name

### ISSUE THREAD

**Issue by openmohan** [jaegertracing/jaeger#1629]
## Requirement - what kind of business use case are you trying to solve?
Support autocomplete by indexing tags and values for a given service and operation name

## Problem - what in Jaeger blocks you from solving the requirement?
There are no API implemented in backend yet to add tags and retrieve tags based on service and operation name

## Impact of the problem
No impact. It is an improvement for UX.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Create  API in the query module for adding and fetching tags for particular service and operation name

## Any open questions to address
1. It was mentioned in [364](https://github.com/jaegertracing/jaeger-ui/issues/364) to use the service name while filtering tags. It makes sense to add the operation name. As the tags will be based on the service and operation name as well.
2. Should the API's be done on the query module or any other?

**Comment by yurishkuro** [comment]
This is a dup of #364, please add your comments there. Are you interested in working on this?

**Comment by openmohan** [comment]
I am working on this, just that the issue exists in [UI repo.](https://github.com/jaegertracing/jaeger-ui/issues/364) But the work has to be done on jaeger server as well. So created this issue. 

I have started to explore the code. Will soon send out a WIP PR.
