### ISSUE TITLE
Upgrade from 1.12.0 to 1.13.0 causes Error 403 (Forbidden)

### ISSUE THREAD

**Issue by wsoula** [jaegertracing/jaeger#1641]
## Requirement - what kind of business use case are you trying to solve?

Track traces

## Problem - what in Jaeger blocks you from solving the requirement?

![image](https://user-images.githubusercontent.com/1820481/60278000-e16f8800-98bb-11e9-8ab8-23dd0f2e71a1.png)
If I rollback to 1.12.0 then it works again

**Comment by wsoula** [comment]
Appears env var `QUERY_BEARER_TOKEN_PROPAGATION=false` allows it to work.

**Comment by yurishkuro** [comment]
This is a bug, false value should be the default

**Comment by pavolloffay** [comment]
thanks for reporting @wsoula.

I will push 1.13.1 with your fix
