### ISSUE TITLE
error when flushing the buffer

### ISSUE THREAD

**Issue by mholleville** [jaegertracing/jaeger#1645]
Hello ! I'm trying to install jaeger since yesterday.

I have an ES 6.8.0 cluster. First strange thing, I have all Jaeger stack to install but I only have one index finger. Is that normal?

<img width="637" alt="Capture d’écran 2019-06-28 à 09 03 36" src="https://user-images.githubusercontent.com/49511757/60330480-cc195d00-9992-11e9-8e82-476d680594b8.png">

My agent configuration 

<img width="832" alt="Capture d’écran 2019-06-28 à 10 20 53" src="https://user-images.githubusercontent.com/49511757/60330487-d2a7d480-9992-11e9-92e5-be8c427a4567.png">

My query configuration

<img width="832" alt="Capture d’écran 2019-06-28 à 10 52 55" src="https://user-images.githubusercontent.com/49511757/60330520-ebb08580-9992-11e9-96ff-7eddf586b156.png">

My configmap

<img width="832" alt="Capture d’écran 2019-06-28 à 10 53 04" src="https://user-images.githubusercontent.com/49511757/60330531-f1a66680-9992-11e9-85bf-b668486c5027.png">

When I going on the UI I have this error 

`{"level":"error","ts":1561711877.6078942,"caller":"zap/logger.go:33","msg":"error when flushing the buffer: write udp 127.0.0.1:54209->127.0.0.1:6831: write: connection refused"`

Can you explain me ?

**Comment by jpkrohling** [comment]
This is the same problem as reported in #1644, right?

**Comment by pavolloffay** [comment]
The query is instrumented with Jaeger client which sends data over UDP to localhost - it expects that jaeger-agent runs there. 

The solution is to deploy jaeger-agent on the same host. Our k8s operator automatically does it.

**Comment by pavolloffay** [comment]
> I have an ES 6.8.0 cluster. First strange thing, I have all Jaeger stack to install but I only have one index finger. Is that normal?

Jaeger does not create indices automatically. Indices are created once you report data.
