### ISSUE TITLE
control jaeger trace dynamically

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1648]
how to start agent or stop agent in the running time.

**Comment by guanw** [comment]
Why do you want to start and stop agent? What are you looking to achieve here?

**Comment by zheyiyi** [comment]
> Why do you want to start and stop agent? What are you looking to achieve here?

I want to stop agent to trace and do not need to stop my application.
And then some time, when I want to start agent to trace, I do not need to restart my application

**Comment by guanw** [comment]
@zheyiyi Sorry for the late response. AFAIK there's no way of temporarily stopping tracing in client. I can also see the problem with this demand: what if you are running multiple micro services where they have a clear dependency of each other, and you turn off the tracing in the middle of some requests, what happens to this trace in the end? Is an incomplete trace ok for your use-case?

But if say your use case is simple, You could easily set up a bool variable to turn on/off creating spans as you needed. Something (in golang) like:

```
tracer := opentracing.GlobalTracer()
...
if !turnOffTracer {
    span := tracer.StartSpan("say-hello")
    defer span.Finish()
}

```

**Comment by wuyupengwoaini** [comment]
@zheyiyi   In fact, you do not need to dynamically control the start and stop of the agent to achieve dynamic control of span data reporting. You only need to customize the Reporter interface to achieve your goal.

**Comment by pavolloffay** [comment]
You could also use remote sampler and appropriatelly configure sampling for your service https://www.jaegertracing.io/docs/1.13/sampling/#collector-sampling-configuration.

Or implement a different Reporter which would stop sampling based on some conditions.
