### ISSUE TITLE
Support jaeger-debug-id header even when there is an established trace context

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#165]
Some command line tools like [yab](https://github.com/yarpc/yab) are capable of starting a trace before sending the request. They also allow setting additional headers like `jaeger-debug-id`, but the Jaeger client libs ignore (at least Java client does) it since there is already a trace context.

 * [ ] make sure all clients respect the header regardless of the presence of the trace
 * [ ] add a test for this behavior to end-to-end test

**Comment by vprithvi** [comment]
This is true of the node client as well.

**Comment by rbtcollins** [comment]
I suspect this is true of the c++ client too since our nginx stack seems to be ignoring the header.

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients.
