### ISSUE TITLE
Recommended collector topolgy in jaeger

### ISSUE THREAD

**Issue by prana24** [jaegertracing/jaeger#1650]
## Any open questions to address

Experts, Do we have any recommended  topology  of  collectors ?  
We want to go with  multiple collector being deployed in different kubernetes clusters  rather than multiple jaeger collector in one  Cluster.  
By doing this we want to avoid single point of failure .  Is there any issue in this topology ?  Would like to hear  views.

**Comment by jpkrohling** [comment]
As far as the collector is concerned, it doesn't matter whether all instances are part of the same pod or are deployed in different clusters. If anything, I'd place one pod with a couple replicas close to where your agents are. If you have your application deployed in several clusters, I'd then have one Jaeger instance per cluster, sharing the same backing storage but I wouldn't create additional clusters just to host a highly-available collector setup.
