### ISSUE TITLE
Use SPAN_STORAGE_TYPE custom plugin on Kubernetes

### ISSUE THREAD

**Issue by mholleville** [jaegertracing/jaeger#1651]
Hi I want use custom plugin for storage and use [influxDB](https://github.com/influxdata/jaeger-influxdb) . But I would like to know if you knew an example of implementation to use a custom plugin with Kubernetes?

I'm trying this but without success : 

```
env:
    - name: SPAN_STORAGE_TYPE
    - value: grpc-plugin jager-all-in-one-linux --grpc-storage-plugin.binary .jaeger-influxdb --grpc-storage-plugin.configuration-file ./config-example-v1.yaml
```

**Comment by yurishkuro** [comment]
the value of `SPAN_STORAGE_TYPE` var is simply `grpc-plugin`. You're trying to jam a whole command in there. Use different variables for that. 

Cf. https://www.jaegertracing.io/docs/1.13/deployment/#storage-plugin

**Comment by pavolloffay** [comment]
I am closing this as it is just a question
