### ISSUE TITLE
about jaeger-ingester usage

### ISSUE THREAD

**Issue by hotdust** [jaegertracing/jaeger#1654]
Becasuse it looks like not much doc about jaeger-ingester, I have questions about it as following:

## 1, how to deploy mutiple instance for HA ?
I started two instances. First one failed as soon as second one started. error messages as following:
```
panic: counter cannot decrease in value

goroutine 63 [running]:
github.com/jaegertracing/jaeger/vendor/github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc0001cb380, 0xbff0000000000000)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/prometheus/client_golang/prometheus/counter.go:71 +0xa3
github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-lib/metrics/prometheus.(*counter).Inc(0xc0002b6810, 0xffffffffffffffff)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-lib/metrics/prometheus/factory.go:223 +0x46
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).handleMessages(0xc000149a00, 0xf221a0, 0xc0001585a0)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:132 +0x872
created by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:91 +0x172
```

## 2, how to config mutilple jaeger-ingester to consume topic?
if jaeger-ingester lags, it's better to start multiple instance to consume topic.

**Comment by yurishkuro** [comment]
1 - make sure you're running the latest version, the panic on the counter has been fixed in the recent release

2 -  not sure what the question is. You just run multiple ingesters in the same consumer group (i.e. with identical parameters), and they will distributed topic partitions amongst them. That is a standard behavior of the Kafka driver, Jaeger doesn't implement anything special.

**Comment by hotdust** [comment]
thank you for quick reply. 
1.12 worked.
