### ISSUE TITLE
Badger storage type and data retention

### ISSUE THREAD

**Issue by tomaszturkowski** [jaegertracing/jaeger#1659]
Hello,
I'm using Jaeger with Badger storage enabled. Is there any known option to cleanup storage like it is implemented for ES storage (https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/esCleaner.py)? Or is there any option to set data retention span which will execute automatic cleanup of records older than 1 month for example?

**Comment by jpkrohling** [comment]
cc @burmanm

**Comment by burmanm** [comment]
``--badger.span-store-ttl=168h`` is the default. You can use that same parameter to define a new value how long to keep the spans. They're cleaned automatically after expiring.

**Comment by tomaszturkowski** [comment]
Thank you very much. Now everything is clear, I couldn't find that information in documentation or I missed it somehow.

**Comment by vedant1811** [comment]
Now the default is:

### 3 days

ref:

```
defaultTTL                   time.Duration = time.Hour * 72
```

in `plugin/storage/badger/options.go`
