### ISSUE TITLE
Open telemetry

### ISSUE THREAD

**Issue by RalphSu** [jaegertracing/jaeger#1660]
Open tracing and open census is merging to https://github.com/open-telemetry/community. Is that a plan to join it?

**Comment by yurishkuro** [comment]
https://medium.com/jaegertracing/jaeger-and-opentelemetry-1846f701d9f2

**Comment by RalphSu** [comment]
good to know, thanks @yurishkuro

**Comment by RalphSu** [comment]
closing this question since we already working on it.
