### ISSUE TITLE
how to create port of jaeger-ingester

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1663]
I need to change 14270 and 14271 port in jaeger-ingester. I change environment parameter like this in the docker compose file.
 ADMIN-HTTP-PORT: 34270
 METRICS_PORT: 34271
but it doesn't work. How i should be change?

jaeger-ingester:
    image: jaegertracing/jaeger-ingester:1.8.2
    ports:
      # HTTP health check port: $ curl -v http://localhost:14270/
      - "34270:34270"
      # Metrics port: $ curl http://localhost:14271/metrics
      - "34271:34271"
    restart: on-failure
    environment:
      # LOG_LEVEL: "debug"
      INGESTER_PARALLELISM: "1"
      INGESTER_DEADLOCKINTERVAL: "0ms"
      SPAN_STORAGE_TYPE: "elasticsearch"
      ES_SERVER_URLS: "http://elasticsearch:9200"
      KAFKA_BROKERS: "kafka:39092"
      METRICS_BACKEND: "expvar"
      ADMIN-HTTP-PORT: 34270
      METRICS_PORT: 34271

**Comment by yurishkuro** [comment]
`ADMIN-HTTP-PORT` is not a legal env var, `ADMIN_HTTP_PORT` is.

**Comment by pavolloffay** [comment]
@zheyiyi comment back if there are still issues. I think @yurishkuro provided the answer for you.
