### ISSUE TITLE
Comsos DB as storage backend

### ISSUE THREAD

**Issue by marius-stanescu** [jaegertracing/jaeger#1667]
Could you also add Cosmos DB as a storage backend?
Related to #638 and #1105.

**Comment by jpkrohling** [comment]
We have already Elasticsearch, Cassandra, Badger and in-memory in the main repository. To support other storage backends, we have support for storage plugins (#1461). We might be missing the documentation of how to develop one such plugin, but the PR introducing that feature also added an example:

https://github.com/jaegertracing/jaeger/blob/d3ee676bcb9666832a582ccf8b2c8e126b9532a1/examples/memstore-plugin/main.go#L30-L65

Right now, we are not hosting plugins in the main repository, but given enough traction, we can certainly host it at this organization. 

As such, I'm closing this issue, but do let us know in case you develop a plugin for Cosmos DB!

**Comment by omerlh** [comment]
Hey, @marius-stanescu I started to play a bit with the GRPC plugin API in dotnet, should be pretty simple to write a plugin. Is that something you're interested at?

**Comment by yurishkuro** [comment]
I am going to re-open this and link from #638. We can close once we have a clear answer.

I was under impression that CosmosDB has a wire protocol compatible with Cassandra, is it not the case?

**Comment by yurishkuro** [comment]
There are some discussions about CosmosDB here: #1105

**Comment by yurishkuro** [comment]
And here:  #1205

**Comment by yurishkuro** [comment]
Pining @sagaranand015 @nutharsh @486 @lukasmrtvy who previously commented on issues related to CosmosDB - did anyone got it to work?

**Comment by sagaranand015** [comment]
@yurishkuro : Checked the cosmosDb connection with cassandra API and as mentioned in https://github.com/jaegertracing/jaeger/issues/1105, it works by removing the SnappyCompressor in Cassandra connection. Also, the keyspace creation using templates do not work because of the commas(which Cosmos db does not support)

How do you think we should proceed here? A Plugin approach to Cosmos db or a storage backend altogether?

Also, should the compressor be forced or should it be driven by config? (This seems like a change we can make before going to plugin/storage backend development).

**Comment by yurishkuro** [comment]
@sagaranand015 these changes sound very minor. I don't think it makes sense to treat it as a new storage backend, just parameterize the existing code to allow to control for these variations.

**Comment by sagaranand015** [comment]
@yurishkuro :
So, this boils down to 2 action items:
1. Make the Cassandra Compressor drive from config. How about adding --cassandra.compression=(True/False) config from flags? Default being SnappyCompressor if --cassandra.compression is true(true by default) (Issue: https://github.com/jaegertracing/jaeger/issues/1105)
2. Change the Storage backend documentation to point out:
    a. --cassandra.compression flag to be false
    b. change the generated keyspace templates to remove unsupported commas.

If the above sounds good, will raise a PR for the same. Please let me know. Thanks

**Comment by yurishkuro** [comment]
@sagaranand015 yes, sounds good
