### ISSUE TITLE
Automatic instrumentation support for java like Pinpoint and SkyWalking

### ISSUE THREAD

**Issue by qudongfang** [jaegertracing/jaeger#1670]
## Requirement - what kind of business use case are you trying to solve?

Automatic instrumentation support for java like [Pinpoint](https://naver.github.io/pinpoint/) and [SkyWalking](https://skywalking.apache.org/).

## Problem - what in Jaeger blocks you from solving the requirement?

Client lib for java etc.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Using some tech like javaagents like Pinpoint and Skywalking.

**Comment by yurishkuro** [comment]
It's not in the scope of Jaeger project. We believe instrumentation should be vendor-neutral, not tied to a specific tracing backend.

See https://github.com/opentracing-contrib/java-specialagent

**Comment by qudongfang** [comment]
> It's not in the scope of Jaeger project. We believe instrumentation should be vendor-neutral, not tied to a specific tracing backend.
> 
> See https://github.com/opentracing-contrib/java-specialagent

Thanks a lot for your clarification and suggestion.
