### ISSUE TITLE
optimum ratio between collector queue size and worker instance

### ISSUE THREAD

**Issue by prana24** [jaegertracing/jaeger#1679]
## Requirement - what kind of business use case are you trying to solve?
In order to avoid span drops we  keep adding queue size  and worker instance at collector. Do we have any  collector queue  vs  number of worker instance ratio  which  needs to be maintained ? Also  what is the max. queue size we can go for  in collector ?  We are using  elastic search as backend

**Comment by yurishkuro** [comment]
I think these  questions are answered in https://www.jaegertracing.io/docs/1.13/performance-tuning/

Please review it and comment back if you still  have questions, so that we can update the documentation.

**Comment by prana24** [comment]
Thank you , i will go through it  come back if needed.

**Comment by jpkrohling** [comment]
I'm closing this, but feel free to reopen if you still have questions about this.
