### ISSUE TITLE
how can  jaeger get current span?

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1684]
If I have a controller method which called validateEquipment, inside it, I call dojob function and in dojob function, it call payment function. So validateEquipment span will be parent of dojob span and dojob span will be parent of payment span.  I just want to ask How jaeger solve the problem. Everytime it can get current parent of span and create child span?

    @RestController
    @ClassTrace
    public class Controller {

    @PostMapping("/validate")
    @ResponseBody
    @HttpMethodTrace
    public ResponseEntity<String> validateEquipment(RequestEntity<String> incoming) 
           new Job().dojob();
    }}

    public class Job{
      public void dojob(){
           payment()
     }

    public void payment(){

     System.out.println("pay 200")
    }}

**Comment by yurishkuro** [comment]
this isn't specific to Jaeger, it's part of OpenTracing context propagation framework

https://github.com/jaegertracing/jaeger-client-java/blob/0b2d27c8105da8f98121063ea68e09dd2272a49f/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java#L191
