### ISSUE TITLE
AWS Managed Elasticsearch as Storage Backend

### ISSUE THREAD

**Issue by tomaszturkowski** [jaegertracing/jaeger#1698]
In documentation I can see that is possible to use elasticsearch as storage backend for jaeger. Unfortunately managed AWS Elasticsearch cluster native transport protocol is not supported ([ref](https://forums.aws.amazon.com/thread.jspa?messageID=681938)).

Is there any way that I can manage to use aws elasticsearch together with jaeger?

**Comment by pavolloffay** [comment]
Jaeger does not use 9300 port. It uses only HTTP (9200) to communicate with elasticsearch and that port should be open in AWS. The ES host and port is fully configurable in Jaeger. Refer to the flags/options in the documentation.

I am closing this as it should not be an issue. If you have more questions please comment.
