### ISSUE TITLE
jaeger stand alone  linux installation 

### ISSUE THREAD

**Issue by prana24** [jaegertracing/jaeger#1699]
## Requirement - what kind of business use case are you trying to solve?
We have been facing resource limitation issue with our jaeger installation in our kubernetes cluster. In order to overcome we are thinking to move it to   linux deployment on bm/vm , Somehow i dont find any documents or link  which i can refer for the same.  
Can you please share if there is one ?

**Comment by jpkrohling** [comment]
What are you looking for exactly? The binaries are listed here: https://www.jaegertracing.io/download/ . You can just execute the binaries as you wish. If you are interested in systemd unit files to manage the processes, you can use the ones I described in the following blog post as base:

https://medium.com/jaegertracing/running-jaeger-agent-on-bare-metal-d1fc47d31fab

I'm really interested in hearing more about your resource limitation issue, though. Perhaps there's something we can improve there?

**Comment by jpkrohling** [comment]
I'm closing this, but feel free to reopen if you still have problems and have more information to share.
