### ISSUE TITLE
Thrift error "Expected version 01 but got 02" 

### ISSUE THREAD

**Issue by pradeepdogga** [jaegertracing/jaeger#1711]
Hi,
Using the lesson 01 solution in https://github.com/yurishkuro/opentracing-tutorial/tree/master/python/lesson01 I am running into an issue when I am running the same program on ubuntu 14.04 while I have no issue when I run the program on ubuntu 16.04.

The following is the error that I observe in jaeger backend logs:
{"level":"error","ts":1563932465.957273,"caller":"processors/thrift_processor.go:118","msg":"Processor failed","error":"Expected version 01 but got 02","stacktrace":"github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:118\ngithub.com/jaegertracing/jaeger/cmd/agent/app/processors.NewThriftProcessor.func2\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:82"}

To reproduce:
----------------
Run jaeger on ubuntu 16.04
Run lesson 01 from tutorial on same machine, it works and I can see traces on UI
Run lesson 01 from tutorial on ubuntu 14.04, it gives the above error in jaeger and I cannot see traces on UI.

Any help is appreciated.

Thanks,
Pradeep.

**Comment by yurishkuro** [comment]
just a guess, but maybe you are somehow forcing a different version of thrift lib

**Comment by pradeepdogga** [comment]
Thanks for the reply! 
I have thrift 0.9.2 on both the machines.
