### ISSUE TITLE
Receiving error - Updating sampler failed

### ISSUE THREAD

**Issue by amanikmss** [jaegertracing/jaeger#1726]
## Requirement - what kind of business use case are you trying to solve?
I have the Jaeger deployed as a container in ECS and I am trying to send traces to it (using C# Jaeger client) over HTTP from a Lambda web app (.NET Core). I have setup the environment variables (shown below) and am getting the Tracer using these environment variables.

`                Environment.SetEnvironmentVariable(Jaeger.Configuration.JaegerServiceName, serviceName);
                Environment.SetEnvironmentVariable(Jaeger.Configuration.JaegerEndpoint, Configuration.GetValue<string>("appSettings:JaegerEndPoint"));
`

## Problem - what in Jaeger blocks you from solving the requirement?
The issue is that I cannot send the traces over to Jaeger. The error that I see in CloudWatch is 'Updating sampler failed'. I see HTTP connection exceptions originating in RemoteControlledSampler.UpdateSampler. It looks like it is not able to connect to a Sampler Manager endpoint. I have tried to set it to (http://[JAEGER_COLLECTOR_IPADDRESS]:5778/Sampling) as well using the Environment variable Jaeger.Configuration.JaegerSamplerManagerHostPort but that doesn't help either. 

And funny thing is that I can talk to the container in ECS when I run the code from my local machine. When run in Lambda, it doesn't work.

Any help would be very much appreciated.

**Comment by yurishkuro** [comment]
connecting sampler to remote collector is currently not supported, samplers can only talk to an http endpoint implemented by jaeger-agent.
