### ISSUE TITLE
Adaptive sampling strategies not updated in certain situations

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger#1728]
Under certain conditions, the collector might not return adaptive sampling strategies for certain operations which in turn means the operation will continue to use the existing sampling strategy and not be updated.

https://github.com/uber/jaeger-client-go/blob/master/sampler.go#L361 doesn't update existing strategies that are not apart of the passed in strategies.

Issue exists in all clients

- [x] Go https://github.com/jaegertracing/jaeger-client-go/pull/413
- [x] Java
- [ ] Node
- [ ] Python
- [ ] C#
- [ ] C++

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients.
