### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [jaegertracing/jaeger#1737]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by jpkrohling** [comment]
I think we could give it a try, but I'm trying to figure out one thing first: do contributors have to sign up for fuzzit in order to view the reports? I'd rather not force that upon our contributors.

**Comment by yevgenypats** [comment]
@jpkrohling So good question, it depends on what is your security policy.

The regression tests are run locally in the CI (Travis) and if there are any crashes the contributors will see it in the CI log and there is no need to sign-up for fuzzit.

The fuzzing which is essentially an infinite job that runs on fuzzit and alerts only when crashes are found. The most common use-case is to alert the security team or specific people as you usually don't won't to publish crashes before they are fixed. We also have a feature that we will roll-out soon to file issue automatically on Github but then it will be publicly. 

Currently public regression + private crash reporting works for most projects. let me know if this also works for your use-case/project?

**Comment by jpkrohling** [comment]
Thanks for your clarification. 

> We also have a feature that we will roll-out soon to file issue automatically on Github but then it will be publicly.

Are you aware of GitHub Security Advisories? Perhaps they expose an API, allowing your tool to create one such advisory:

https://github.com/jaegertracing/jaeger/security/advisories 

This will be visible only to project maintainers.

> Currently public regression + private crash reporting works for most projects. let me know if this also works for your use-case/project?

I think it makes sense, you have my +1.

**Comment by yevgenypats** [comment]
Yes, I'm aware of the github security advisories. currently they don't provide an API afaik but once they do we will for sure integrate. 

Sounds good, we will look into the PR soon. will keep you posted once we have a draft PR.

**Comment by bookmoons** [comment]
https://github.com/jaegertracing/jaeger/compare/fb5505005a21f007792dedbcd2ad49484d1d587e...bookmoons:4260d517b9cfb1eb381c9669c692936664245fce has something toward this. It targets:
* Thrift deserialization.
* JSON deserialization.
* Requests to an agent.

If there are other bits that deserve fuzzing I can look into it. Will be prepping a PR for this soon.

**Comment by bookmoons** [comment]
https://github.com/jaegertracing/jaeger/compare/c30f242328b588f48f2b103b2735c9657c63f4e6...bookmoons:11b1e8ec4bfca40bcae357631c1919322c9d6e3f has this PR prepped. There's a successful test build. I see fuzzing happening in the Fuzzit queue.
https://travis-ci.org/bookmoons/jaeger/builds/582532787

@dominikh Built this integration on your fuzzer work. jaeger has a commit signing requirement. Would you mind setting it up for your commit? If you do it on your branch I think can rebase onto it.
https://github.com/bookmoons/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md#certificate-of-origin---sign-your-work

**Comment by dominikh** [comment]
@bookmoons done.

**Comment by bookmoons** [comment]
Thanks a lot @dominikh.

**Comment by yurishkuro** [comment]
I would like to revisit this. How much value are we going to get from fuzzing?  It is quite expensive to run and adds almost 17min to CI becoming green (example: https://travis-ci.org/jaegertracing/jaeger/builds/608901821)

**Comment by jpkrohling** [comment]
You sure it's being caused by the fuzzing job? I see the ES tests taking about 18 minutes, with the two fuzz jobs taking 11m and 4m each. I have to admit though that I haven't even looked at the results of a single job yet, so, it's not really adding much value *to me*.

![image](https://user-images.githubusercontent.com/13387/68765908-2d7a5980-061e-11ea-8db5-b2ea0dc33d94.png)

**Comment by yurishkuro** [comment]
Sure, ES step is long, but it runs in parallel with the others, while fuzzing is almost doubling the total wait time (and uses available compute, blocking other jobs). It feels like a solution in search of a problem.

**Comment by yevgenypats** [comment]
Hey team, saw that you are having issues with the fuzzing jobs latency.

Looks like the fuzzing regression is slow due to slow input for one of the fuzz targets. I can suggest a couple of solutions:

1) See why the fuzz target is slow and fix if possible
2) Remove the fuzz regression step completely. Fuzzit will still run regression in the cloud it just won't run them on pull-request so there might be a short latency if a bug is introduced in a pull-request you will be notified shortly after merge.

**Comment by pavolloffay** [comment]
The fuzz regression takes about 50 minutes and it's run only after all test jobs passed.

![Screenshot of Build #6241 - jaegertracing_jaeger - Travis CI](https://user-images.githubusercontent.com/5618424/68853684-da1a1100-06da-11ea-9110-5c13ee564074.png)

 On top of that the fuzz regression seems to be flaky on travis due to:
> The job exceeded the maximum time limit for jobs, and has been terminated.

https://travis-ci.org/jaegertracing/jaeger/builds/611282090?utm_source=github_status&utm_medium=notification


We should consider disabling it. 50 minutes on top of tests is very long and it sometimes even fails.

**Comment by pavolloffay** [comment]
The fuzzit badge in our readme requires to log in https://app.fuzzit.dev/orgs/jaeger/dashboard. Even after the login I wasn't able to find the results.

**Comment by yevgenypats** [comment]
@pavolloffay I've add you to jaeger organisation and you have access now to https://app.fuzzit.dev/orgs/jaeger/dashboard . You and @jpkrohling are now both admin of this organisation.

**Comment by pavolloffay** [comment]
The link https://app.fuzzit.dev/orgs/jaeger/dashboard should be public if we want to have it in the readme.

**Comment by yevgenypats** [comment]
Public dashboard is on our roadmap as most users usually want this private not to expose crashes before they are fixed. But this is a valid feature request and we are working on it.

**Comment by yurishkuro** [comment]
I am going to close this, since an external service is not the direction we want to go considering that Go 1.18 comes with fuzzing built-in, not to mention that we haven't really found a strong use case yet to use fuzzing in the first place.
