### ISSUE TITLE
Strange behavior for output logs

### ISSUE THREAD

**Issue by nlamirault** [jaegertracing/jaeger#174]
I try to add JSON content to logs like that : 

```go
span.LogFields(log.String("get_platform", string(resp)))

[...]

data := string(resp)
glog.V(0).Infof("Data: %s", data)
span.LogFields(log.String("response", data))
```

Output logs are : 
```
Data: [{"biosUUID": "422523e2-4bf4-917f-a3ba-e65574cc18ef", "description": "4ef78da2-3552-11e7-99f4-0800270a9ecb", "disks": [{"capacity": 10, 
[...]
```
On UI, first log (*get_platform*) seems to be correctly printed, with key = "get_platform", and a value in JSON.
But second and third logs, "response" and "virtual_machines", key are "event" and it's not JSON content but string as values.
I don't really understand the different behavior with the same code. Only responses are differents.

Any idea how can't i fix that ? 
Thanks
![2017-05-23-154644_1263x548_scrot](https://cloud.githubusercontent.com/assets/29233/26357761/a0b31e94-3fd0-11e7-9704-70fb4b2f0e96.png)

**Comment by black-adder** [comment]
Hi, your code looks fine, I think it's a bug on our end. But just to be sure, in the go-client, we limit the size of log value to 256 characters, so if the log is larger than that, we will truncate and by the time it gets to the UI, we will not be able to unmarshall it correctly to display it.

However in this case, I think the issue is in our code (https://github.com/uber/jaeger/blob/master/model/converter/thrift/zipkin/to_domain.go#L294) we seem to be only accept map[string]string json payloads however you are logging json payloads with nested objects and arrays. Looks like some fixes are going to be needed to get this working.

**Comment by black-adder** [comment]
Hmmm, nvm, I misunderstood the code, I think it should be able to handle nested json payloads correctly. I'll add a test to make sure.

**Comment by yurishkuro** [comment]
the fact that this goes through zipkin transformation may also have something to do with it. We need to merge the `jaeger.thrift` upgrade.

**Comment by thedoctorde** [comment]
@black-adder Hi, is it possible to lift restrictions of log value? I want to log whole response and its length more than 256 symbols.

**Comment by yurishkuro** [comment]
Yeah, I'd be in favor of removing the limits. If anything, there limit should be an optional thing, like a pluggable sanitizer.

**Comment by jpkrohling** [comment]
@nlamirault sorry this is taking so long -- are you able to quick check if this is still happening?

**Comment by nlamirault** [comment]
@jpkrohling sorry I can not verify that. I have no access to my old project.

**Comment by jpkrohling** [comment]
@nlamirault that's OK, I think it should be trivial to create a reproducer.

@kevinearls: would you be interested in testing this?

**Comment by kevinearls** [comment]
@jpkrohling Yes, I can test it.

**Comment by jpkrohling** [comment]
@kevinearls do you think you'll have time to test this?

**Comment by kevinearls** [comment]
@jpkrohling Probably not in the short term, but maybe after a few weeks.

**Comment by jkowall** [comment]
Seems like this one is stale and was never confirmed as an issue.
