### ISSUE TITLE
run     go get -v github.com/jaegertracing/jaeger/examples/hotrod/cmd  have some errors

### ISSUE THREAD

**Issue by gongbo2018** [jaegertracing/jaeger#1744]
**go env**

> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/Users/wangguocheng/Library/Caches/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH="/Users/wangguocheng/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6w/y98wch9x1wz2pxtxdfft4v8m0000gn/T/go-build614647098=/tmp/go-build -gno-record-gcc-switches -fno-common"
> 

run `go get -v github.com/jaegertracing/jaeger/examples/hotrod/cmd`   have some errors

**error message:**
> github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:79:20: not enough arguments in call to oprot.Flush
> 	have ()
> 	want (context.Context)
> github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:103:15: assignment mismatch: 2 variables but error2.Read returns 1 values
> github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:152:20: not enough arguments in call to oprot.Flush
> 	have ()
> 	want (context.Context)
> github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:176:15: assignment mismatch: 2 variables but error4.Read returns 1 values
> github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:225:20: not enough arguments in call to oprot.Flush
> 	have ()
> 	want (context.Context)
> github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:249:15: assignment mismatch: 2 variables but error6.Read returns 1 values
> github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:295:31: cannot use &metaProcessorHealth literal (type *metaProcessorHealth) as type thrift.TProcessorFunction in assignment:
> 	*metaProcessorHealth does not implement thrift.TProcessorFunction (wrong type for Process method)
> 		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
> 		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
> github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:296:34: cannot use &metaProcessorThriftIDL literal (type *metaProcessorThriftIDL) as type thrift.TProcessorFunction in assignment:
> 	*metaProcessorThriftIDL does not implement thrift.TProcessorFunction (wrong type for Process method)
> 		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
> 		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
> github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:297:36: cannot use &metaProcessorVersionInfo literal (type *metaProcessorVersionInfo) as type thrift.TProcessorFunction in assignment:
> 	*metaProcessorVersionInfo does not implement thrift.TProcessorFunction (wrong type for Process method)
> 		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
> 		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
> github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:307:27: not enough arguments in call to processor.Process
> 	have (int32, thrift.TProtocol, thrift.TProtocol)
> 	want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
> github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:307:27: too many errors

**Comment by yurishkuro** [comment]
The readme explains how to run HotRod from source.

https://github.com/jaegertracing/jaeger/blob/master/examples/hotrod/README.md

**Comment by pavolloffay** [comment]
I am closing this, we do not support `go get` as an installation way for hot rod.

**Comment by gongbo2018** [comment]
OK, I know.   Thank you!!!
