### ISSUE TITLE
Unexpected rounding of string span tags containing big integers

### ISSUE THREAD

**Issue by sergiimk** [jaegertracing/jaeger#1750]
## Requirement - what kind of business use case are you trying to solve?

We are implementing a custom gRPC-based storage plugin as per [this doc](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/grpc/README.md).

## Problem - what in Jaeger blocks you from solving the requirement?

The data that our plugin puts into Span tags can include big integer IDs (uint64). Since many languages don't deal with large integers in JSON nicely all such IDs are stringified. However even in string form Jaeger tries to interpret these tags as integers which results in rounding issues.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

A simplest way to reproduce this issue is to modify in-memory gRPC plugin to return following fake span:

```go
func (r *Reader) GetTrace(ctx context.Context, traceID model.TraceID) (trace *model.Trace, err error) {
	sp, _ := model.SpanIDFromString("123123123")
	return &model.Trace{
		Spans:      []*model.Span{
			&model.Span{
				TraceID: traceID,
				SpanID: sp,
				OperationName: "operation",
				References: []model.SpanRef{},
				Flags: model.Flags(0),
				StartTime: time.Now(),
				Duration: 1 * time.Minute,
				Tags: []model.KeyValue{
					model.KeyValue{Key: "x", VStr: "3205345037701495167", VType: model.ValueType_STRING},
				},
				Logs: []model.Log{},
				ProcessID: "123",
				Process: &model.Process{
					ServiceName: "xxx",
				},
				Warnings: []string{},
			},
		},
		Warnings:   nil,
	}, nil
```

The key line is:
```
model.KeyValue{
  Key: "x",
  VStr: "3205345037701495167", 
  VType: model.ValueType_STRING
}
```
Searching for a span in Jaeger UI shows that this tag has been converted to integer with loss of precision:
![wrong](https://user-images.githubusercontent.com/204914/63391211-89f31300-c366-11e9-8204-edf3a88415a2.png)

Modifying the value to contain non-numeric characters results in correct string type:
![right](https://user-images.githubusercontent.com/204914/63391249-ad1dc280-c366-11e9-8859-1a1b048e73a7.png)

**Comment by yurishkuro** [comment]
I think it has been fixed in https://github.com/jaegertracing/jaeger-ui/pull/436.

Will be available in the next release.

**Comment by sergiimk** [comment]
Oh, I didn't think about submodules when testing against master. Can confirm the issue is fixed in latest `jaeger-ui`.

Thanks a lot for a quick response!
