### ISSUE TITLE
Way to identify tenant info  in each span 

### ISSUE THREAD

**Issue by prana24** [jaegertracing/jaeger#1755]
## Requirement - what kind of business use case are you trying to solve?
Our jaeger tracing set up are used by multiple client  from different  kubernetes cluster , Is there a way we can identify spans   on the basis of cluster  and client ?  Something  in setting  or  at the agent level ?

**Comment by jpkrohling** [comment]
You can make use of the `--jaeger.tags` CLI option for the agent:

From the Agent's `--help` switch:
```
--jaeger.tags string     One or more tags to be added to the Process tags of all spans passing through this agent. Ex: key1=value1,key2=${envVar:defaultValue}
```

Most clients also have something similar that can be specified via the env var `JAEGER_TAGS`:
https://www.jaegertracing.io/docs/1.13/client-features/

Note, however, that you shouldn't trust this if your clients can't be trusted, as they can also set a value for a tag with the same name, confusing to whoever looks at the resulting span (to say the least).

For multi-tenancy with clients that you can't trust, the best is to have a dedicated Jaeger instance per tenant. You can then inject agents as sidecars, each pointing to the correct tenant's collector.

**Comment by prana24** [comment]
cool ,  i assume   `jaeger.tags `   should work with kubernetes deployment of  jaeger agent as well right  ?

**Comment by jpkrohling** [comment]
Yes, just set that via `options`. We do plan to automatically inject the `namespace` and `name` via the jaeger-operator.

**Comment by pavolloffay** [comment]
It seems like the question has been answered, I am closing this in favor of https://github.com/jaegertracing/jaeger-operator/issues/632
