### ISSUE TITLE
Why is Elasticsearch's ignore_above mapping explicitly set to 256?

### ISSUE THREAD

**Issue by ScottKaye** [jaegertracing/jaeger#1761]
## Requirement - what kind of business use case are you trying to solve?

I'm attempting to store stacktraces in my traces.  I log the full exception, which is very often over 256 bytes.  Since this value is greater than 256 bytes, I can't run aggregations (or even query for it at all) since it is ignored by Elasticsearch.

Here's an example of one of my logs:

```json
{
  "_index": "jaeger-span-2019-08-26",
  "_type": "span",
  "_id": "DbwazmwB2_V2oXygtnB3",
  "_score": 1,
  "_source": {
    "traceID": "2222222222222222",
    "spanID": "1111111111111111",
    "flags": 1,
    "operationName": "External Connection",
    "startTime": 1566825948340637,
    "startTimeMillis": 1566825948340,
    "duration": 4000000,
    "tags": [],
    "tag": {
      "error": true
    },
    "logs": [
      {
        "timestamp": 1566825952055972,
        "fields": [
          {
            "key": "event",
            "type": "string",
            "value": "error"
          },
          {
            "key": "error.object",
            "type": "string",
            "value": "System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\r\n   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)\r\n   at Connector.SendMessage(object obj) in Connector.cs:line 100"
          }
        ]
      }
    ],
    "process": {
      "serviceName": "Connection Service",
      "tags": [],
      "tag": {
        "hostname": "localhost",
        "ip": "1.1.1.1",
        "jaeger@version": "CSharp-0.3.3.0"
      }
    }
  },
  "fields": {
    "startTimeMillis": [
      "2019-08-26T13:25:48.340Z"
    ]
  }
}
```

## Problem - what in Jaeger blocks you from solving the requirement?

The [span mapping](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/mappings/jaeger-span-7.json) explicitly marks all keywords to `ignore_above: 256`.  This is likely the result of copying the output of the old dynamic mapper, which I believe is removed in ES7.  The default value for this field is actually `int.MaxValue` (2147483647), though it's [more useful to set it to `32766`](https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html).

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The simple solution is to remove all `ignore_above` settings in the span templates.  They were likely created by the dynamic mapper earlier and stuck.  A solution I would personally prefer would be to use Elasticsearch's default handling for strings - [create a fully-analyzed `text` field and a `keyword` subfield.](https://www.elastic.co/blog/strings-are-dead-long-live-strings)  This way, aggregations can be run on log values (keyword), but also searches for general values (text).  This would use more disk space though, and most users may not benefit from this at all.

## Any open questions to address

#1627 may solve this already, by allowing users to override the index templates with their own settings.  I'm not sure if this is in version 1.13 though, as it's not mentioned on the releases page.

**Comment by pavolloffay** [comment]
`ignore_above` does not seem to be removed/deprecated in 7.x https://www.elastic.co/guide/en/elasticsearch/reference/7.2/ignore-above.html. Could you provide pointer to docs whether it is used or not? 

>  A solution I would personally prefer would be to use Elasticsearch's default handling for strings - create a fully-analyzed text field and a keyword subfield. This way, aggregations can be run on log values (keyword), but also searches for general values (text). This would use more disk space though, and most users may not benefit from this at all.

I think this would not be used by jaeger query. If that affects performance it might not be well suited for all users. As you mentioned there is a possibility to change the mapping for users who need to query logs in kibana etc.


I think we should increase or remove `ignore_above` from IDs, operation names and consider increasing it to 32766 if that would not have perf affects. @yurishkuro is Jaeger collector doing truncation on any field? Is Cassandra truncating any fields?

> I'm not sure if this is in version 1.13 though, as it's not mentioned on the releases page.

If it's not in the changelog than it hasn't been merged. You can also compare in github UI https://github.com/jaegertracing/jaeger/compare/v1.13.1...master

**Comment by ScottKaye** [comment]
I have solved my requirement with the new index template option in #1627.  This is likely the best solution for anybody else facing this.  Thank you!
