### ISSUE TITLE
how to add value into process of Jaeger UI

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1770]
I use opencensus to create spans.

span.putAttribute(key,value)-----> jaeger UI's  tags
span.annotation---->jaeger UI's logs

My question is that on Jaeger Ui, How to add things into process?

![image](https://user-images.githubusercontent.com/12801407/64191761-2f1de900-ce47-11e9-8dd1-42b78429e7bb.png)

**Comment by yurishkuro** [comment]
I am not sure how you can add them with OpenCensus. Jaeger libraries support the notion of "tracer tags" that are added to Process. Similarly, Jaeger agent supports "agent tags" that are also added to the Process. If you are only using OpenCensus library & agent before sending data to Jaeger, then you  should open a ticket with them asking about it.

**Comment by jpkrohling** [comment]
Just to complement @yurishkuro's answer, the "agent tags" can be set by passing a comma-separated list of key=value pairs via the flag `--jaeger-tags`. Tracer tags can be passed using the same notation via the `JAEGER_TAGS` env var.

**Comment by annanay25** [comment]
@zheyiyi - We used [this sheet](https://docs.google.com/spreadsheets/d/1I-rP_H9UtgqwRM863hVMTHH6AEsJbPCPXWPRy8lVzzw/edit?usp=sharing) as reference while writing the OC proto -> Jaeger proto translation.

There was no direct mapping from OC proto for the `Process` field, but it should be populated when `StackTrace` is populated in the OC span.

Hope this helps.

**Comment by pavolloffay** [comment]
I am closing this as it is a question.

The tracer library/agent/collector you are using should support adding process level tags. In OpenTelemetry Java Jaeger exporter adds tags https://github.com/open-telemetry/opentelemetry-java/blob/ba1819996f07554df2cd3795f27f62edc84cb340/exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java#L86. For example resource object will be converted to process https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/src/main/java/io/opentelemetry/sdk/resources/Resource.java.
