### ISSUE TITLE
jaeger collector drop spans while queue is not full

### ISSUE THREAD

**Issue by luoyu2015** [jaegertracing/jaeger#1772]
## Requirement - what kind of business use case are you trying to solve?
We use jaeger 1.13(collector version) for distributed tracing in our production envrionment

## Problem - what in Jaeger blocks you from solving the requirement?
I noticed that jaeger collector dropped spans even when the queue is not full, but from what I saw in source code, spans are only dropped when the queue is full or stopped, so how can this happen?
the capacity of the queue is 2k(default).
the query of dropped spans is `rate(jaeger_collector_spans_dropped_total[1m])`
the query of queue length is `jaeger_collector_queue_length`
![image](https://user-images.githubusercontent.com/16425114/64232292-47176a80-cf24-11e9-87c1-dfacb5f32b4e.png)

**Comment by jpkrohling** [comment]
Prometheus scrapes the metrics endpoint from time to time. It is possible that the queue got full for a short period of time causing spans to drop but when the metrics got scraped, the queue has been drained up a bit already.

Do you have enough resources for your collector, to increase the queue size to, say, 4000?

**Comment by luoyu2015** [comment]
> Prometheus scrapes the metrics endpoint from time to time. It is possible that the queue got full for a short period of time causing spans to drop but when the metrics got scraped, the queue has been drained up a bit already.
> 
> Do you have enough resources for your collector, to increase the queue size to, say, 4000? If you stop getting spans dropped, or if it becomes less frequent, it kinda confirms that it's being dropped because the queue is full.

It seems that the number of dropped spans decreased rapidly after I increase the queue size to 4000, thank you very much
![image](https://user-images.githubusercontent.com/16425114/64237118-4b488580-cf2e-11e9-8be3-eff5d566dca6.png)

Btw, the annotation in https://github.com/jaegertracing/jaeger/blob/master/pkg/queue/bounded_queue.go
says `if it fills up due to slow consumers, the new items written by the producer force the earliest items to be dropped`
but from what I saw in BoundedQueue.Produce, the "new" span will be dropped when the queue is full, so which one is correct?
![image](https://user-images.githubusercontent.com/16425114/64237493-083ae200-cf2f-11e9-9105-3ca1055fa68e.png)

**Comment by jpkrohling** [comment]
I actually tested this when writing the blog post on [performance tuning](https://medium.com/jaegertracing/tuning-jaegers-performance-7a60864cf3b1), and it is indeed the oldest item that is getting dropped :-)

**Comment by luoyu2015** [comment]
Ok, I get it, thank you so much.
