### ISSUE TITLE
Jeger log output to file

### ISSUE THREAD

**Issue by chopper-poet** [jaegertracing/jaeger#1775]
if there a way to output log to a logfile and carve up by date,like this '2019-09-06.log'

**Comment by guanw** [comment]
@panjunDev Does [this](https://github.com/jaegertracing/jaeger/pull/1587/files) help?

**Comment by panjunDev** [comment]
> @panjunDev Does [this](https://github.com/jaegertracing/jaeger/pull/1587/files) help?

yes.

**Comment by pavolloffay** [comment]
I was about to close this, however zap supports logging to a file https://github.com/uber-go/zap/issues/294. We could have a switch with paths to log files.

**Comment by yurishkuro** [comment]
I would not recommend it. There are some scenarios where zap is not yet initialized and we write to stdout/err. And in general, knowing what to do with logs is the business of the orchestration system, not the application. If we start writing to files, we need to rotate them, that's additional configuration, etc.

**Comment by pavolloffay** [comment]
Let's close this then. We don't want to pull in more logic for log management.

Users can redirect stdout/stderr to a file and rotate it by an external utility like `logrotate`  - https://linux.die.net/man/8/logrotate
