### ISSUE TITLE
Allow de-duplicating Span.Process, agent, and collector tags

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#1778]
## Problem - what in Jaeger blocks you from solving the requirement?

When using `--jaeger-tags` in the Agent, and the same tags as `JAEGER_TAGS` on a client such as the Java client, the tags are being duplicated:

![image](https://user-images.githubusercontent.com/13387/64429976-8a561280-d0b7-11e9-8cf0-121968880d4c.png)

This is probably the relevant code:
https://github.com/jaegertracing/jaeger/blob/fb5505005a21f007792dedbcd2ad49484d1d587e/cmd/agent/app/reporter/grpc/reporter.go#L87-L91

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Either:
* Allow agents to override the client's process tag, or
* Prevent the agent from adding a process tag to a span's process tag if a tag with the same name exists 

## Any open questions to address

- Decide which of the proposals to implement

**Comment by annanay25** [comment]
Aha, good catch! 

I'd vote for the second option (prevent agent from adding tag if it already exists), because I can't think of a scenario where agent would have a more accurate value for a tag than a client.

P.S: This can also be marked "good first issue"!

**Comment by objectiser** [comment]
The counter argument is that you want the agent to enforce an official/authoritative value and prevent the client from being able to override it.

Possibly we need a mechanism to enable the agent to know which action to take when a duplicate is found.

**Comment by jpkrohling** [comment]
So:

1. provide a flag `--duplicate-tags`, with the possible values `client` (keep client's value), `agent` (keep agent's value), and `duplicate` (the current behavior).
1. by default, `client` is used (or `duplicate`, if we want to be extra careful in case someone depends on the current behavior)

**Comment by objectiser** [comment]
Sounds good as long as we believe all tags are to be treated the same.

**Comment by jpkrohling** [comment]
Marking this as "good first issue". I'll implement this in a couple of weeks if we don't get volunteers :)

**Comment by Pothulapati** [comment]
I can take this issue :D

**Comment by dm03514** [comment]
If something comes up @Pothulapati , I’d be happy to take it too :)

**Comment by jpkrohling** [comment]
@dm03514 we have plenty of good first issues. How about this one? https://github.com/jaegertracing/jaeger-operator/issues/654

**Comment by jpkrohling** [comment]
I could swear we had this fixed already :-) Any volunteers for this one?

**Comment by fbartnitzek** [comment]
I tried the `--collector.tags` configuration, but the tag-duplicates are multiplying fast even if you only test it with the jaeger-query. 
Without a way to prevent duplicates, by enforcing that client / agent / collector key wins, those tags produce too much noise to use them.

**Comment by jpkrohling** [comment]
> but the tag-duplicates are multiplying fast

Do you have an example of that?

**Comment by fbartnitzek** [comment]
sure: 
My test was on kubernetes, just with jaeger-collector and jaeger-query (v1.18.1, without operator).
Only the jaeger-query-agent-sidecar produces traces and the collector writes them to a separate elasticsearch index with this collector-tags
```
spec:
  containers:
  - args:
    - --collector.tags=testtag=testvalue
```

The jaeger-query traces showed 
- 2 testtag-labels for the first trace on path `/api/services`
- after a page refresh it showed 4 testtag-labels on path `/api/services`

after some clicking in the ui, I also found
- for path `/api/services/{service}/operations` traces with 2 and traces with 4 testtag-labels
- for path `/api/traces` traces with 5 and traces with 9 testtag-labels

And all spans of a trace have the same number of testtag-labels.

![image](https://user-images.githubusercontent.com/12848727/99063826-689ec800-25a5-11eb-8e54-75dd7d7a5dd7.png)

**Comment by jpkrohling** [comment]
This is really, really odd. We should indeed work on de-duplicating the tags, but there has to be something else going on...

**Comment by Betula-L** [comment]
@jpkrohling I can take this issue.
