### ISSUE TITLE
Client and Jaeger backend compatibility

### ISSUE THREAD

**Issue by fmhwong** [jaegertracing/jaeger#1785]
Do we have a table mapping which versions of jaeger-client are compatible to which versions of Jaeger backend in dockerhub?

**Comment by pavolloffay** [comment]
I don't think we have a compatibility table but I would assume a client is compatible with Jaeger backend if the Jaeger backed exposes port which is supported by the client.

In other words we don't break wire formats between client collector.

**Comment by fmhwong** [comment]
Thank you
