### ISSUE TITLE
Ingester performance impact vs direct collector/elasticsearch

### ISSUE THREAD

**Issue by eroji** [jaegertracing/jaeger#1790]
I am trying to deploy a Jaeger CR using the operator in Kubernetes, which is using Kafka based streaming strategy and the storage backend is Elasticsearch. The problem I am experiencing is that, when dealing with large amount of incoming traces, by using streaming strategy, the ingester seems to handle them in batches. This causes the amount of messages being temporarily stored in Kafka to pile up and delay of traces stored into Elasticsearch will grow to a point where it is more than an hour behind and eat up all the persistent volume provisioned to Kafka. In looking further, there does not appear to be any way to tune the ingester for more performance. I've tried creating more replicas of ingesters but that yielded negligible gains. If I switch the CR to store directly to Elasticsearch, I will see content for each trace however, the spans will be incomplete for some. I surmise that my Kubernetes backend storage may not be fast enough to deal with the volume of incoming messages, however, I believe it is fast enough if Kafka is there to be a buffer mechanism. However, because the ingester's processing method, it is creating an unintended, and growing delay that makes the implementation not really usable in it's current form.

**Comment by yurishkuro** [comment]
Are you monitoring ingester metrics for storage errors &retries? 

Have you tried increasing the number of partitions on the Kafka topic?

**Comment by eroji** [comment]
> Are you monitoring ingester metrics for storage errors &retries?
Any documentation on how to do this?

> Have you tried increasing the number of partitions on the Kafka topic?
No but I can certainly try

**Comment by eroji** [comment]
I increased the partition to 5 (from 1) matching the number of injester pods. I see that each of the injesters starts up with a respective Kafka topic partition assigned. Currently there is a low amount of traces flowing through so Jaeger is able to keep up. However, the batch behavior still seems to be present. There is about a 5-7 min delay until another batch of traces are processed and made available in Jaeger UI.

**Comment by pavolloffay** [comment]
The write to Elasticsearch is done in batches. It can be controlled by the following flags:
```
      --es.bulk.actions int                                       The number of requests that can be enqueued before the bulk processor decides to commit (default 1000)
      --es.bulk.flush-interval duration                           A time.Duration after which bulk requests are committed, regardless of other thresholds. Set to zero to disable. By default, this is disabled. (default 200ms)
      --es.bulk.size int                                          The number of bytes that the bulk requests can take up before the bulk processor decides to commit (default 5000000)
      --es.bulk.workers int                                       The number of workers that are able to receive bulk requests and eventually commit them to Elasticsearch (default 1)
      --es.create-index-templates                                 Create index templates at application startup. Set to false when templates are installed manually. (default true)
``

It's worth trying to experiment with these properties to see if the ingestion rate changes.

**Comment by romil-punetha** [comment]
Does the collector comprise of 2 types of workers, ie, one that reads from queue and the other that writes to es? 
```
options:
      collector:
        num-workers: "20"
        bulk:
          worker: "1"
```

**Comment by pavolloffay** [comment]
Collector workers and ES workers serve different purposes. ES storage layer uses ES bulk API that groups ES requests to a batch.

**Comment by pavolloffay** [comment]
@eroji were you able to solve this issue?

**Comment by eroji** [comment]
The main issue was ElasticSearch deployment, which was using Rook/Ceph. It was not able to keep up with the amount of traces Jaeger was receiving. By moving to an external ElasticSearch with more performant storage backend it is now working as expected.
