### ISSUE TITLE
kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

### ISSUE THREAD

**Issue by ali-1024** [jaegertracing/jaeger#1801]
This error has been made, kafka is deployed at a single point, local can link to kafka

![image](https://user-images.githubusercontent.com/39354350/65021923-3de1c100-d95a-11e9-982e-fcd6232bd16d.png)

After Google, the kafka configuration is wrong, but the modification is useless.

![image](https://user-images.githubusercontent.com/39354350/65022388-18a18280-d95b-11e9-83a0-6ab83b5a3ba8.png)

I can't locate the reason now.

jaeger-ingester:  1.14
kafka version ：2.11-2.3.0

**Comment by ali-1024** [comment]
This issue has been resolved because KAFKA_BROKERS is outdated
But there are other problems
If there's no news in kafka for a long time
It will stop on its own
[图片]

**Comment by ali-1024** [comment]
This issue has been resolved because KAFKA_BROKERS is outdated
But there are other problems
If there's no news in kafka for a long time
It will stop on its own

![R~P)O _ELIHR1H T~RC9Q6](https://user-images.githubusercontent.com/39354350/65034527-6b863480-d971-11e9-9c1f-41a0e38b2936.png)

**Comment by objectiser** [comment]
Have you looked at the `ingester.deadlockInterval` option:

> Interval to check for deadlocks. If no messages gets processed in given time, ingester app will exit. Value of 0 disables deadlock check. 

from https://www.jaegertracing.io/docs/1.14/cli/#jaeger-ingester

**Comment by ali-1024** [comment]
> 你看过这个`ingester.deadlockInterval`选项了吗：
> 
> > 检查死锁的时间间隔。如果在给定时间内没有处理任何消息，则ingester app将退出。值0禁用死锁检查。
> 
> 来自https://www.jaegertracing.io/docs/1.14/cli/#jaeger-ingester

Wow, that's true. I'm sorry I checked the help but didn't see it. Thank you for the problem

**Comment by ali-1024** [comment]
> 你看过这个`ingester.deadlockInterval`选项了吗：
> 
> > 检查死锁的时间间隔。如果在给定时间内没有处理任何消息，则ingester app将退出。值0禁用死锁检查。
> 
> 来自https://www.jaegertracing.io/docs/1.14/cli/#jaeger-ingester

Wow, that's true. I'm sorry I checked the help but didn't see it. Thank you for the problem

**Comment by ali-1024** [comment]
> Have you looked at the `ingester.deadlockInterval` option:
> 
> > Interval to check for deadlocks. If no messages gets processed in given time, ingester app will exit. Value of 0 disables deadlock check.
> 
> from https://www.jaegertracing.io/docs/1.14/cli/#jaeger-ingester

Wow, that's true. I'm sorry I checked the help but didn't see it. Thank you for the problem
