### ISSUE TITLE
fail to initiate jeager with es 7

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1805]
I follow the link to initiate all jaeger compose.
https://github.com/PacktPublishing/Mastering-Distributed-Tracing/blob/master/Chapter12/docker-compose.yml

 I just use es 7 image and new jaeger 1.14 and it doesn't work. Does jaeger 1.14 image is incompatible with kafka?

jaeger docker 1.8.2 works but jaeger docker image 1.14 doesn't work. Can anyone fix the bug?

version: '3.5'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

    restart: on-failure
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: on-failure
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      restart: on-failure

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.14
    ports:
      - "14268:14268"
      - "14269:14269"
    restart: on-failure
    environment:
      LOG_LEVEL: "debug"
      SPAN_STORAGE_TYPE: "kafka"
      KAFKA_BROKERS: "kafka:29092"

  jaeger-ingester:
    image: jaegertracing/jaeger-ingester:1.14
    ports:
      - "14270:14270"
      - "14271:14271"
    restart: on-failure
    environment:
      INGESTER_PARALLELISM: "1"
      INGESTER_DEADLOCKINTERVAL: "0ms"
      SPAN_STORAGE_TYPE: "elasticsearch"
      ES_SERVER_URLS: "http://elasticsearch:9200"
      KAFKA_BROKERS: "kafka:29092"
      METRICS_BACKEND: "expvar"
  jaeger:
    image: jaegertracing/jaeger-query:1.14
    ports:
       - "16686:16686"
       - "16687:16687"
    restart: on-failure
    environment:
      SPAN_STORAGE_TYPE: "elasticsearch"
      ES_SERVER_URLS: "http://elasticsearch:9200"

**Comment by pavolloffay** [comment]
nit learn how to format code in github issues:

```yaml
ports: 
```

Jaeger 1.14 is compatible with ES 7.x. `docker.elastic.co/elasticsearch/elasticsearch:7.3.2` enables security xpack which is probably causing failures in your case . I would recommend using oss flavor or disabling xpack.
