### ISSUE TITLE
I got the message in kafka.

### ISSUE THREAD

**Issue by ali-1024** [jaegertracing/jaeger#1806]
I want to get some information to do statistics and so on, but I just can't get the right information, what should I do

![~}@~RC243CE54BW3FCBYPKL](https://user-images.githubusercontent.com/39354350/65303415-31eb3e80-dba8-11e9-9a5d-803538fce3dc.png)

flink version 1.9.0
jaeger-collector: 1.7
kafka version ：2.11-2.3.0

**Comment by yurishkuro** [comment]
If you want people to help you, please take time to explain the problem in details. Your question has absolutely nothing to go on. What is "right information"? What are you even trying to do?

**Comment by ali-1024** [comment]
Sorry, I want to get jaeger-collector information from kafka, just like Ingester gets Kafka information and stores it in cassandra, but the information I get is a mess.

**Comment by yurishkuro** [comment]
You need to deserialize it from Protobuf. There's a Java example in my book: https://github.com/PacktPublishing/Mastering-Distributed-Tracing/blob/master/Chapter12/src/main/java/model/ProtoUnmarshaler.java

**Comment by ali-1024** [comment]
Thank you very much. I'll go back and study it.
