### ISSUE TITLE
Support --es.num-shards-span-index and --es.num-shards-service-index. As spans need more shards and service needs less shards.

### ISSUE THREAD

**Issue by vikrambe** [jaegertracing/jaeger#1807]

**Comment by pavolloffay** [comment]
As of Jaeger 1.14.0 you can create index templates manually and set shards and replicas you require.

**Comment by flodetan** [comment]
hi @pavolloffay 
I encoutered the same question: how can i split  `.num-shards` settings  for span & service ?
