### ISSUE TITLE
build on arm computer error !

### ISSUE THREAD

**Issue by zziawan** [jaegertracing/jaeger#1823]
## Requirement - what kind of business use case are you trying to solve?

use V1.8.1  build offline on arm computer ,when i got all the dependencies . make  can not success. some error raised, no error message.  can some help ？
=== RUN   TestParseStrategy
=== RUN   TestParseStrategy/#00
=== RUN   TestParseStrategy/#01
--- PASS: TestParseStrategy (0.00s)
    --- PASS: TestParseStrategy/#00 (0.00s)
    --- PASS: TestParseStrategy/#01 (0.00s)
PASS
ok      github.com/jaegertracing/jaeger/plugin/sampling/strategystore/static    (cached)
FAIL    github.com/jaegertracing/jaeger/plugin/storage [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/cassandra [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/cassandra/dependencystore [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/cassandra/samplingstore [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore/dbmodel [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/es [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/es/dependencystore [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/es/dependencystore/dbmodel [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/es/spanstore [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/integration [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/kafka [build failed]
FAIL    github.com/jaegertracing/jaeger/plugin/storage/memory [build failed]
FAIL    github.com/jaegertracing/jaeger/storage [build failed]
FAIL    github.com/jaegertracing/jaeger/storage/dependencystore [build failed]
testing: warning: no tests to run
PASS
ok      github.com/jaegertracing/jaeger/storage/samplingstore   (cached) [no tests to run]
FAIL    github.com/jaegertracing/jaeger/storage/spanstore [build failed]
FAIL    github.com/jaegertracing/jaeger/storage/spanstore/metrics [build failed]
Reaping losing child 0xdb75140 PID 102763
make: *** [test] Error 2

**Comment by zziawan** [comment]
after glide install  still no dependencies was found  when to make,why?

**Comment by jpkrohling** [comment]
It does sound like a real compilation problem, but just to confirm: are you able to build Jaeger on a non-ARM machine? If you get similar problems, you might be missing some of the steps listed in the [CONTRIBUTING.md](https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING.md).

In any case, I would also like to try it out myself: are you aware of any online resources where I could get an ARM machine to play with?

**Comment by zziawan** [comment]
> machine to pla

sorry, no online ARM machine.  i do follow CONTRIBUTING.md to  compile  version 1.8 source code  on non-ARM machine   after  command glide install successful , make still can not found dependencies . i copy all the cache dependencies to the go-path , compile successful, but no  go binary files  and images  found .  can i only run go build in all-in-one directory to build a go binary file?  thinks!

**Comment by jpkrohling** [comment]
It's still not clear to me whether you are having a setup issue, or something more complex. I can't test on ARM myself, so, I would like to ask you to:

1. compile the latest version from master (Jaeger 1.8 is old at this point)
1. compile using the same go version that we use in the CI (1.12.1)

If you still have problems, then try it on a regular x86_64. If you are having a setup issue, it's likely you'd have it on x86_64 as well, and then we can help you.

In time, trying to cross compile targeting ARMv5 failed with:

```
$ GOARCH=arm GOARM=5 go build -o cmd/all-in-one/all-in-one-armv5 ./cmd/all-in-one/main.go 
# github.com/jaegertracing/jaeger/plugin/storage/badger
plugin/storage/badger/stats_linux.go:33:69: invalid operation: int64(valDirStatfs.Bavail) * valDirStatfs.Bsize (mismatched types int64 and int32)
plugin/storage/badger/stats_linux.go:34:67: invalid operation: int64(keyDirStatfs.Bavail) * keyDirStatfs.Bsize (mismatched types int64 and int32)
```

cc @burmanm

**Comment by burmanm** [comment]
Does it really matter if something doesn't compile on 32-bit ARMv5? Processors with that architecture are not going to run Jaeger.

**Comment by jpkrohling** [comment]
> Does it really matter if something doesn't compile on 32-bit ARMv5?

Not sure. If there's something easy we can do to at least compile, we should do. But it might indeed not matter in the end.

For the record, the same happens for v7:

```
$ GOARCH=arm GOARM=7 go build -o cmd/all-in-one/all-in-one-armv7 ./cmd/all-in-one/main.go 
# github.com/jaegertracing/jaeger/plugin/storage/badger
plugin/storage/badger/stats_linux.go:33:69: invalid operation: int64(valDirStatfs.Bavail) * valDirStatfs.Bsize (mismatched types int64 and int32)
plugin/storage/badger/stats_linux.go:34:67: invalid operation: int64(keyDirStatfs.Bavail) * keyDirStatfs.Bsize (mismatched types int64 and int32)
```

`GOARCH=arm64` succeeds though.

**Comment by jpkrohling** [comment]
By the way, just saw this: https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

**Comment by zziawan** [comment]
> By the way, just saw this: https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

think you for you supporting, finally i  build without ui successfully(change the makefile, using " make build-binaries-linux"), and run it successfully. thanks!

**Comment by obscurerichard** [comment]
For what it's worth, I was able to build Jaeger for `armv7` just now using an amd64 Ubuntu 20.04 userland, go 1.6, and the latest d9453e08a9683cca90e198db62768fe78dd1f9af revision of `master`. 

```
$ go version
go version go1.16 linux/amd64
$ GOARCH=arm GOARM=7 go build -o cmd/all-in-one/all-in-one-armv7 ./cmd/all-in-one/main.go
```
I then ran it on a 32-bit armv7 Raspberry Pi 2 system running Raspberry Pi OS (Debian Buster):
```
pi@pi2:~$ ./all-in-one-armv7 --help
2021/02/22 23:28:36 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
Jaeger all-in-one distribution with agent, collector and query. Use with caution this version
by default uses only in-memory database.

Usage:
  jaeger-all-in-one [flags]
  jaeger-all-in-one [command]
...
pi@pi2:~$ ./all-in-one-armv7 2>&1 | head -10
2021/02/22 23:39:24 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
{"level":"info","ts":1614055164.873464,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1614055164.8738792,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1614055164.8754716,"caller":"flags/admin.go:105","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1614055164.8760333,"caller":"flags/admin.go:111","msg":"Starting admin HTTP server","http-addr":":14269"}
{"level":"info","ts":1614055164.8762186,"caller":"flags/admin.go:97","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
{"level":"info","ts":1614055164.8916352,"caller":"memory/factory.go:61","msg":"Memory storage initialized","configuration":{"MaxTraces":0}}
{"level":"info","ts":1614055164.89554,"caller":"static/strategy_store.go:201","msg":"No sampling strategies provided or URL is unavailable, using defaults"}
{"level":"info","ts":1614055165.0275226,"caller":"server/grpc.go:76","msg":"Starting jaeger-collector gRPC server","grpc.host-port":":14250"}
{"level":"info","ts":1614055165.027812,"caller":"server/http.go:47","msg":"Starting jaeger-collector HTTP server","http host-port":":14268"}
```
It started up fine on that system, but I haven't tested it further yet.
