### ISSUE TITLE
esCleaner occasionally fails with KeyError

### ISSUE THREAD

**Issue by svenwltr** [jaegertracing/jaeger#1824]
## Requirement - what kind of business use case are you trying to solve?

We want to remove old indices from ElasticSearch.

## Problem - what in Jaeger blocks you from solving the requirement?

Cleaning itself works, but occasionally it fails and needs a restart. This produces noise in our alerting system. We can silence the alert for this, but then we would not notice actual failures.

The process exits with this Traceback:

```
Traceback (most recent call last):
  File "/es-index-cleaner/esCleaner.py", line 106, in <module>
    main()
  File "/es-index-cleaner/esCleaner.py", line 40, in main
    ilo = curator.IndexList(client)
  File "/usr/local/lib/python3.7/site-packages/curator/indexlist.py", line 31, in __init__
    self.__get_indices()
  File "/usr/local/lib/python3.7/site-packages/curator/indexlist.py", line 72, in __get_indices
    self._get_index_stats()
  File "/usr/local/lib/python3.7/site-packages/curator/indexlist.py", line 149, in _get_index_stats
    iterate_over_stats(stats_result)
  File "/usr/local/lib/python3.7/site-packages/curator/indexlist.py", line 121, in iterate_over_stats
    for index in stats['indices']:
KeyError: 'indices'
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

—

## Any open questions to address

—

## Versions

* ElasticSearch: `6.8.2`
* Jaeger: `1.14.0`

**Comment by pavolloffay** [comment]
@svenwltr any idea what the error means? Is there any way to reproduce it on a demo setup?

**Comment by svenwltr** [comment]
@pavolloffay I just took a quick look into the code of the `curator` lib. To me it looks like it happens when one of the requests to Elasticsearch fails, as it [catches an specific kind of exceptions](https://github.com/elastic/curator/blob/master/curator/indexlist.py#L141-L149), but continues anyway.

Probably our ES cluster is just responding too slow. I did not manage to reproduce it yet.

**Comment by BEvgeniyS** [comment]
Experiencing the same with Amazon's ES and Jaeger operator 1.14

**Comment by pavolloffay** [comment]
Would anybody of you be able to catch the error type?

**Comment by Nick-Anderssohn** [comment]
This is effecting me too.

**Comment by lighteness** [comment]
This is effecting me too.

**Comment by MischaWeerwag** [comment]
> This is effecting me too.

**Comment by blame19** [comment]
Any update on the issue?

**Comment by ediezh** [comment]
It is happening to me too. Not just te esCleaner, it happens with the es rollover too.

**Comment by jpkrohling** [comment]
Apparently, it's a permission issue as pointed out by @roberth1988 here: https://github.com/jaegertracing/jaeger/issues/1691#issuecomment-861341232

**Comment by ediezh** [comment]
I don't think it's all due to the permission issue. We are running a es cluster without permission control even.
