### ISSUE TITLE
Jaeger agent wont connect to collector

### ISSUE THREAD

**Issue by namaiiee2222** [jaegertracing/jaeger#1826]
I'm build jaeger query and collector with docker and trying to connect agent from another server to collector.

The agent connect to collector with ip and port but it can not connect with domain name and port.

./jaeger-agent  --reporter.grpc.host-port=xx.xx.yy.zz:14250 -> this work 

 ./jaeger-agent  --reporter.grpc.host-port=dns:///example.com:80 -> wont work 

any solution?

**Comment by pavolloffay** [comment]
Perhaps your DNS is not working properly.

It does not seem like a problem in jaeger, therefore I am closing this. Feel free to reopen or comment if there is anything more we can do.

**Comment by jpkrohling** [comment]
Note that the port in the second example has to be 14250 as well.
