### ISSUE TITLE
  jaegertracing/spark-dependencies only using tag: latest

### ISSUE THREAD

**Issue by liorco3000** [jaegertracing/jaeger#1828]
jaegertracing/spark-dependencies only using tag: latest

Hi can jaegertracing/spark-dependencies be tagged with some kind of tag besides latest ?

Please tag your builds 

Also why do we need to use this in production,
What does this spark job actually do ?

**Comment by pavolloffay** [comment]
Duplicate of https://github.com/jaegertracing/spark-dependencies/issues/64

**Comment by pavolloffay** [comment]
It calculates dependencies between services. It's needed if you use real storage - kafka, Elasticsearch.
