### ISSUE TITLE
Suport for collector level tags

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#1844]
Similar to agent tags https://github.com/jaegertracing/jaeger/issues/833
Related to removing duplicated tags in collector https://github.com/jaegertracing/jaeger/issues/1778

Add the ability to the collector to add a set of tags to incoming spans. 

The agent supports `JAEGER_TAGS` for adding tags, however if we support the same env var in collector the same set of tags could be added twice - although it depends if we remove duplicate tags in #1778.

Use cases:
* add tenant information cc) @radekg

**Comment by yurishkuro** [comment]
if we do this, let's make sure we reuse the code from the agent

**Comment by radekg** [comment]
@yurishkuro, would the referenced commit be close to what you'd imagine such a feature to look like? It would obviously require tests. For clarity, this is not a PR yet.

**Comment by yurishkuro** [comment]
@radekg not quite, because it adds the tags unconditionally, and there's a requirement to fix that (e.g. #1788)

**Comment by radekg** [comment]
@yurishkuro I've opened the PR so the work can be tracked. I'll add tests in the next couple of days. Regarding #1788, I wonder what's the best way to proceed. Probably wait for that to be merged first and then adapt my PR?

**Comment by yurishkuro** [comment]
Yes, you're probably right, we can merge #1854 first, and then add the deduping policy as a separate ticket.
