### ISSUE TITLE
Problems upgrading to ES7 (AWS)

### ISSUE THREAD

**Issue by dcelasun** [jaegertracing/jaeger#1858]
## Requirement - what kind of business use case are you trying to solve?

I'm trying to follow [the documentation](https://www.jaegertracing.io/docs/1.14/deployment/#upgrade-to-elasticsearch-7-x) on upgrading to ES7.

## Problem - what in Jaeger blocks you from solving the requirement?

According to the docs, I should be able the start the collector in ES7 mode while connecting to ES 6.8.

> Elasticsearch 6.8 supports 7.x, 6.x, 5.x compatible mappings. The upgrade has to be done first to ES 6.8, then apply data migration or wait until old daily indices are removed (this requires to start Jaeger with `--es.version=7` to force using ES 7.x mappings for newly created indices).

However, trying to connect to ES 6.8 (AWS managed ES, if that matters) with `--es.version=7` fails with:

```sh
$ ./collector-linux version
{"gitCommit":"fb5505005a21f007792dedbcd2ad49484d1d587e","GitVersion":"v1.14.0","BuildDate":"2019-10-11T16:39:14Z"}

$ ES_SERVER_URLS=https://example.com SPAN_STORAGE_TYPE=elasticsearch ./collector-linux --es.version=7
2019/10/14 10:11:12 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
{"level":"info","ts":1571044272.9358723,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1571044272.9359663,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1571044272.9360156,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1571044272.9360237,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"fatal","ts":1571044273.0986753,"caller":"collector/main.go:95","msg":"Failed to create span writer","error":"elastic: Error 400 (Bad Request): Malformed [mappings] section for type [dynamic_templates], should include an inner object describing the mapping [type=illegal_argument_exception]","stacktrace":"<redacted>"}
```

**Comment by pavolloffay** [comment]
Could you please paste the response of ES ping endpoint? `http://es:9200/`

**Comment by pavolloffay** [comment]
It seems like a bug I was able to reproduce via docker and OSS ES 6.8.0.

**Comment by pavolloffay** [comment]
I think we have to include `_doc` type into our ES7 indices in order to support smooth migration. At some point it was present in https://github.com/jaegertracing/jaeger/pull/1690 when I tested it, but it was removed in later commits.

Adding liks for docs:
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html
https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-8.0.html
https://discuss.elastic.co/t/malformed-mappings-section-for-type-dynamic-templates/188428

**Comment by chandresh-pancholi** [comment]
@pavolloffay shall I pick it up.

**Comment by pavolloffay** [comment]
@chandresh-pancholi feel free to do so. I have submitted a PR #1866 however the way forward is still not clear to me. See the comments in the PR.

**Comment by pavolloffay** [comment]
@dcelasun our docs were misleading. You should be able to start Jaeger with ES6 by using data created by ES5. Then wait until ES5 indices are removed or reindex data manually.

The new docs will be added here https://github.com/jaegertracing/documentation/pull/319

**Comment by dcelasun** [comment]
Did you mean ES6 instead of ES5? I've never mentioned ES5.

Looking at that PR and assuming you've meant ES6, I can upgrade to ES7 (with ES6 created data) and everything should just work. Does that sound correct?

**Comment by pavolloffay** [comment]
> Did you mean ES6 instead of ES5? I've never mentioned ES5.

No I meant ES 5.

>  I can upgrade to ES7 (with ES6 created data) and everything should just work. Does that sound correct?

Correct. Could you please review  https://github.com/jaegertracing/documentation/pull/319 and comment if it is not clear enough?

**Comment by pavolloffay** [comment]
Done in https://github.com/jaegertracing/documentation/pull/319
