### ISSUE TITLE
[tracking] Delayed sampling

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1861]
## Requirement - what kind of business use case are you trying to solve?

Have the ability to delay sampling decision when more data is available about the trace. For example, the root service may retrieve additional information about the request, for example whether the current user is admin or not, and set it as a tag on the span sometime after the span has been already started (or on a child span instead of the root span). We may want to sample all requests from admin users based on this late arriving information.

## Problem - what in Jaeger blocks you from solving the requirement?

Most Jaeger clients only apply sampling at the start of the root span. Node.js client does support re-sampling when the operation name changes.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Generalize the Node.js client capability further:
  * allow sampling decisions to be made at different times: span creation, change of span operation, adding a span tag, finishing a span
  * allow spans for the same trace in a given service to share sampling state, so that sampling decision could be made on a tag set on a child span and still force sampling of the parent spans

This approach does not allow sampling caller service spans based on a sampling decision made in the downstream service, because that information is not propagated backwards (although if the errors are propagated and set as tags in the caller service then it may still affect sampling).

NB: This is already implemented in the Node.js client.

* [x] Node.js https://github.com/jaegertracing/jaeger-client-node/issues/379
* [x] Go https://github.com/jaegertracing/jaeger-client-go/issues/449
* [ ] Java
* [ ] Python
* [ ] C#
* [ ] C++

## Any open questions to address

* What to do with metrics #1862

**Comment by objectiser** [comment]
Equally I guess if the sampling decision is changed, after the context has been injected into an outbound request, that will not be propagated - thus leading to fragmented traces.

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients.
