### ISSUE TITLE
Documentation for using AWS Elasticsearch

### ISSUE THREAD

**Issue by samudurand** [jaegertracing/jaeger#1863]
## Requirement - what kind of business use case are you trying to solve?

Using Jaeger tracing with AWS Elasticsearch

## Problem - what in Jaeger blocks you from solving the requirement?

The issue https://github.com/jaegertracing/jaeger/issues/678 mentions the need for a way to provide AWS ES certificates, and there is even a PR https://github.com/jaegertracing/jaeger/pull/1139 for it that seem to have been merged into release 1.8
However I cannot find any documentation on the subject of how to use that feature, and the issue that has been created to address it has not been fixed https://github.com/jaegertracing/documentation/issues/161

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Could we get some documentation on how to use the feature ? Or at least an explanation of how to do so here.
If I get enough information I am happy to contribute to the repo to add some formal guidelines on how to use it once I manage it myself.

**Comment by pavolloffay** [comment]
For client certificates you have to use flags `--es.tls.*` https://www.jaegertracing.io/docs/1.14/cli/.

Could you please share your AWS Elasticserch configuration, based on that we can improve the docs for https://github.com/jaegertracing/documentation/issues/161

**Comment by samudurand** [comment]
Ah I completely missed that, thanks ! Closing the issue since that should be enough

**Comment by pavolloffay** [comment]
Could you please go back to this issue or https://github.com/jaegertracing/documentation/issues/161 and describe what did you have to configure?

**Comment by samudurand** [comment]
I will do so once I have successfully configured my app, at the moment I haven't tried those options yet
