### ISSUE TITLE
Change ingester deadlock interval to inf (0)

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#1867]
https://github.com/jaegertracing/jaeger/pull/1134 introduced 

> --ingester.deadlockInterval duration              Interval to check for deadlocks. If no messages gets processed in given time, ingester app will exit. Value of 0 disables deadlock check. (default 1m0s)

 @yurishkuro why the default is 1 minute? Could it be changed to `0`? The problem is that people usually deploy Jaeger and do not immediately start sending data. With the current default value the ingester dies and it is restarted with exponential backoff (in k8s) which is not ideal.

**Comment by yurishkuro** [comment]
Yes, seems reasonable not to make this the default behavior.

**Comment by vprithvi** [comment]
I think this is a reasonable change - there is no good reason to have the default be 1 minute
