### ISSUE TITLE
all-in-one with badger crashes often and never recovers

### ISSUE THREAD

**Issue by surendarchandra** [jaegertracing/jaeger#1869]
## Requirement - what kind of business use case are you trying to solve?

A temporary storage backend while we investigate other options.

## Problem - what in Jaeger blocks you from solving the requirement?
With the badger in non-ephemeral mode, it runs for a bit and right about 90M mark, it crashes and then never recovers. CPU load is maxed out and it seems to be doing something while
the system is down.

Constantly destroy old badger and start a new one

## Proposal - what do you suggest to solve the problem or improve the existing situation?

A more stable storage backend.

**Comment by jpkrohling** [comment]
What is the error message that you get once it crashes? Where are you running it (bare metal, Kubernetes, ...), and how's the resource allocation for the process?

@jkandasa, how hard would it be to change the performance tests to use badger instead of ES?

**Comment by surendarchandra** [comment]
Bare metal, I had given the VM 4 CPUs. Unfortunately didn't capture the error messages during crash.

Switched to Cassandra and that seems much better.

**Comment by jpkrohling** [comment]
If you could try it out and send us an error message, we'd have a starting point to investigate this. Otherwise, we'll depend on our own tests, which might not yield the same problem.

**Comment by chandresh-pancholi** [comment]
@surendarchandra Could you help me out here on how can I reproduce this issue?

**Comment by pavolloffay** [comment]
@burmanm did we solve this with truncate flag?

**Comment by burmanm** [comment]
I think this might be related to mmap issues in the container. That is, the container doesn't allow allocating enough blocks to the memory and that then potentially corrupts the disk space. This is kinda machine / installation specific issue unfortunately. But certainly something that could be investigated (by limiting the amount of virtual memory & blocks and see if this reoccurs) and then a set of "FAQ" could be written.

**Comment by jpkrohling** [comment]
I'm closing this, hoping that this had been fixed by #3096.

**Comment by zziawan** [comment]
@jpkrohling  we also has the problem. jaeger restaring  neeed very long time (40m) to reading data.  version 1.24.0

[https://discuss.dgraph.io/t/jaeger-can-not-start-badger-deleting-file-very-slow-jaeger-can-not-init-storage/16150](url)
