### ISSUE TITLE
trace-without-root-span What's the reason????

### ISSUE THREAD

**Issue by zhouxiaodiu** [jaegertracing/jaeger#1870]

**Comment by zhouxiaodiu** [comment]
![1571643592(1)](https://user-images.githubusercontent.com/38526309/67185742-14183000-f419-11e9-9855-f8e42f8f109b.png)

**Comment by zhouxiaodiu** [comment]
![1571643592(1)](https://user-images.githubusercontent.com/38526309/67185764-22664c00-f419-11e9-9118-cc7745fb7c52.png)

**Comment by liguangcheng** [comment]
@zhouxiaodiu hi bro, have you resolved the without root span issue?
