### ISSUE TITLE
Collectors silently stopped at midnight

### ISSUE THREAD

**Issue by zdicesare** [jaegertracing/jaeger#1874]
## Requirement - what kind of business use case are you trying to solve?

Collector uptime and normal operation

## Problem - what in Jaeger blocks you from solving the requirement?

We have the Jaeger infrastructure (still on Jaeger 1.11) deployed in AWS, using AWS hosted ES and Jaeger collectors + agents running in ECS. We noticed that we had no recent trace data and that new requests were not generating traces.

Looking at ES we noticed that request volume dropped dramatically at midnight EDT on the 19th.

![image (7)](https://user-images.githubusercontent.com/1680362/67228068-8c292a80-f406-11e9-822d-42ecc2f6782b.png)

We run two collectors, which had been running since 09-26. The collectors are using the default logging configuration, and they had no errors/logs written since they were started on the 26th.

I noted in ES that there was no daily span index created for the 20th. There was an index for the 19th, but it had less than 25% data as we would have expected for the day.

The collectors were not constrained by CPU / memory before or at midnight on the 19th.

We forced a new deployment of the collector service and the index was created for the 21st and trace data began flowing again.

## Any open questions to address

In hindsight I should have also checked if the collector containers were responsive on the host. This is a very unusual issue and it is the only time this has happened to us, but I wanted to leave an issue just to document it. If it reoccurs we will try to grab some more diagnostics. Let me know if there are other metrics I can provide now or tips for debugging if it reoccurs.

**Comment by jpkrohling** [comment]
Did it happen at exactly midnight? How is your collector configured, especially related to the ES flags? Were you grabbing metrics from the collector, like:

`jaeger_collector_spans_dropped_total`, which would indicate that spans accumulated in the internal queue and were eventually dropped, in favor of newer spans
`jaeger_collector_spans_received_total, which would indicate whether spans were still being received during the failure

Could you confirm how you are deploying Jaeger? At first, I thought you'd be running the binaries directly on EC2 machines, but then you mentioned "containers" and I'm not sure if you just have Docker/Swarm, or if you have Kubernetes (and the Operator?).

**Comment by zdicesare** [comment]
Incoming requests to ES did reach 0 at exactly midnight.

The collector is instantiated with:

```
"--sampling.strategies-file=sampling_strategies.json",
"--es.num-shards=1",
"--collector.queue-size=4000",
```

As well as environment variables for elasticsearch span storage type, and a single ES server specified in `ES_SERVER_URLS` and `ES_ARCHIVE_SERVER_URLS`.

We have the collector deployed as a docker container running in ECS as a service, there are 2 collectors running at any given time. No Kubernetes or Swarm though.

Unfortunately I do not have the collector metrics from this time period. If this happens again I will record those. For what it's the worth our agents also did not emit any errors during this period either.

**Comment by pavolloffay** [comment]
@zdicesare any updated on the metrics? Were you able to resolve this?

**Comment by zdicesare** [comment]
This has only happened the one time, so we are still waiting for it to recur. If we want to close this, I can reopen with additional metrics if it reoccurs
