### ISSUE TITLE
Readme files for Docker Hub

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#188]
Readme files on Docker Hub https://hub.docker.com/r/jaegertracing should contain more information e.g. URL to the repository, which tags should be used etc.

**Comment by yurishkuro** [comment]
@pavolloffay when you say "readme files", is there some mechanism to provide that from this repo, or it's just a matter of going and editing the descriptions on Docker Hub?

Do you have a proposal of how the description should look like?

**Comment by pavolloffay** [comment]
Are we using automated builds? If so the readme from the docker file directory should be automatically used (If I remember correctly).

About the description, just a basic information, tags semantics, link to the git repository, nothing fancy.

**Comment by yurishkuro** [comment]
Sorry, what do you mean by automated builds? The docker images are built and published by Travis job.

**Comment by pavolloffay** [comment]
This https://docs.docker.com/docker-hub/builds/ you basically specify repo and dockerfile location, then the build is automatically triggered by github.

**Comment by yurishkuro** [comment]
No, we are not using automated builds. They seem to only work if the whole build is done via Docker file, but we're building the executables outside of the container and Dockerfile just copies them into the images.

**Comment by mabn** [comment]
If there were binaries released somewhere (e.g. to github) then it should be possible to create automated build which would just "ADD" the binary.

**Comment by pavolloffay** [comment]
This would work only for tagged versions. We push also `latest` per commit in master.

**Comment by yurishkuro** [comment]
@pavolloffay I still don't know how we can do this change.

**Comment by pavolloffay** [comment]
I think we have to add description manually via docker hub. I am fine with keeping it empty and documenting only on jaegertracing.io.

On docker hub we could add a logo. I cannot do it as I am not owner of the account.

**Comment by pavolloffay** [comment]
I am closing this as I don't think it's necessary to duplicate what we have in https://www.jaegertracing.io/download/. Feel free to reopen.
