### ISSUE TITLE
Elasticsearch Cross Cluster Query

### ISSUE THREAD

**Issue by allen13** [jaegertracing/jaeger#1883]
Would like to add the ability to use the elasticsearch cross cluster query api to query spans across multiple AZs.

I already have some general idea on how to do it but wanted to check here before spending the time working on an MR.

Initial design:

`--es.remote-read-clusters=local,cluster_one,cluster_two`

This will result in the search query GET /jaeger-span-2019-10-28,cluster_one:jaeger-span-2019-10-28,cluster_two:jaeger-span-2019-10-28/_search

es/options.go

```go
flagSet.String(
		nsConfig.namespace+suffixRemoteReadClusters,
		nsConfig.remoteReadClusters,
		"(experimental) The comma-separated list of Elasticsearch remote clusters to read from. Add local to the list to also target the main cluster. i.e. local,cluster1,cluster2")
```

es/spanstore/reader.go

Used a wrapper function to inject the remote clusters. This is the best way I could come up with that has the minimal affect on current code.

```go
func getTimeRangeIndexFn(archive, useReadWriteAliases bool, remoteReadClusters string[]) timeRangeIndexFn {
	if archive {
		var archivePrefix string
		if useReadWriteAliases {
			archivePrefix = archiveReadIndexSuffix
		} else {
			archivePrefix = archiveIndexSuffix
		}
		return addRemoteReadClusters(func(indexName string, startTime time.Time, endTime time.Time) []string {
			return []string{archiveIndex(indexName, archivePrefix)}
		}, remoteReadClusters)
	}

	if useReadWriteAliases {
		return addRemoteReadClusters(func(indices string, startTime time.Time, endTime time.Time) []string {
			return []string{indices + "read"}
		}, remoteReadClusters)
	}

	return addRemoteReadClusters(timeRangeIndices, remoteReadClusters)
}

// Elasticsearch cross cluster query api example: GET /twitter,cluster_one:twitter,cluster_two:twitter/_search
// Add remote cluster prefix to each index
func addRemoteReadClusters(fn timeRangeIndexFn, remoteReadClusters string[]) timeRangeIndexFn {
	return func(indices string, startTime time.Time, endTime time.Time) []string {
		jaegerIndices := fn(indices, startTime, endTime)
		if len(remoteReadClusters) > 0 {
			remoteJaegerIndices := string[]{}
			for remoteCluster := range remoteReadClusters {
				for jaegerIndex := range jaegerIndices {

					if remoteCluster != "local"{
						jaegerIndex = remoteCluster + ":" + jaegerIndex
					}

					remoteJaegerIndices = append(remoteJaegerIndices, jaegerIndex)
				}
			}
		} else {
			return jaegerIndices
		}
	}
}
```

**Comment by pavolloffay** [comment]
I do not have much experience with cross cluster queries. Can anybody from @jaegertracing/elasticsearch have a look? 

@allen13 the feature could be easily added if it is not breaking and it is properly handled for all supported ES versions - 5.x, 6.x and 7.x. It shouldn't also break the rollover aliases support  https://medium.com/jaegertracing/using-elasticsearch-rollover-to-manage-indices-8b3d0c77915d? 

Isn't there a possibility to use a proxy to add requested zones?

**Comment by allen13** [comment]
Submitted PR here https://github.com/jaegertracing/jaeger/pull/1892

**Comment by allen13** [comment]
Cross-cluster query support was added in Elasticserch 5.4. https://www.elastic.co/guide/en/elasticsearch/reference/5.5/modules-cross-cluster-search.html

As long as the flag isn't used it shouldn't break prior versions.

**Comment by pavolloffay** [comment]
Anybody from @jaegertracing/elasticsearch interested in Elasticsearch Cross Cluster Query?
