### ISSUE TITLE
Jaeger Tag value No longer than a certain length， maxTagValueLength is 1G, but this tag no display

### ISSUE THREAD

**Issue by hyhanyan** [jaegertracing/jaeger#1889]
![image](https://user-images.githubusercontent.com/11550403/67860742-8aeab280-fb16-11e9-8e4a-09430ea52eae.png)
![image](https://user-images.githubusercontent.com/11550403/67860769-a3f36380-fb16-11e9-84c3-dc87b7aa2601.png)
when tagSize is 57883， max span tag no display

![image](https://user-images.githubusercontent.com/11550403/67860824-d0a77b00-fb16-11e9-877c-81049332f2df.png)
when tagSize is 22057, max span tag is display

**Comment by hyhanyan** [comment]
![image](https://user-images.githubusercontent.com/11550403/67860938-1401e980-fb17-11e9-97d5-248e6fc232a8.png)

**Comment by hyhanyan** [comment]
Thanks Krohling. 
Yes. When we set a tag which has big value, the whole span can't be displayed on UI.
Actually, our span may have some tags. Some times, even each tag had less than 20000, we still can't see the span.

**Comment by hyhanyan** [comment]
Today we looked at the database that jaeger connected to，It was found that the "max value" was not written to the es data

**Comment by hyhanyan** [comment]
@jpkrohling  how is this going?

**Comment by jpkrohling** [comment]
@hyhanyan if you can send a PR with a test case + bug fix, it would certainly expedite. So far, I imagine that neither @rubenvp8510 nor @jkandasa had time to try it out.

**Comment by pavolloffay** [comment]
@hyhanyan what storage are you using? Is it Elasticserach?

**Comment by pavolloffay** [comment]
If the tag/span is not in the storage and there are not logs in Jaeger server. The data most likely wasn't sent from the tracer. This might be go client issue and not server.

**Comment by hyhanyan** [comment]
@pavolloffay Yes ，is  Elasticserach , 5,6,8.

**Comment by hyhanyan** [comment]
I was looking for this problem yesterday, and I found that it was because the maxSpanBytes value was too small, is (65000-30) 
![image](https://user-images.githubusercontent.com/11550403/68173173-0a8edc00-ff72-11e9-9887-8f65fbf494c5.png)
![image](https://user-images.githubusercontent.com/11550403/68173187-137fad80-ff72-11e9-8c3c-56cb5f5c3168.png)
![image](https://user-images.githubusercontent.com/11550403/68173193-1f6b6f80-ff72-11e9-9d09-a826b3979a4b.png)

So let me make this a little bit bigger， UDPPacketMaxLength = 16500 
But there's another problem,  

![image](https://user-images.githubusercontent.com/11550403/68173359-9c96e480-ff72-11e9-91b0-0d7c582900e4.png)

because the maximum buff that udp sends is 65535

**Comment by hyhanyan** [comment]
We haven't found a good way to solve it at present

**Comment by yurishkuro** [comment]
You cannot report spans larger than 65k bytes over UDP. But you can use a different reporter/sender, e.g. Thrift over HTTP, which does not have these limitations.

Note that if you're using ingester with Kafka, there's also Kafka message size limit.

**Comment by hyhanyan** [comment]
@yurishkuro Thanks ，I can use HTTP，The data is displayed in the UI

**Comment by hyhanyan** [comment]
Will the way to use udp be improved, like HTTP

**Comment by pavolloffay** [comment]
I think that is limitation of UDP packet size. 

This is already documented https://www.jaegertracing.io/docs/1.14/client-libraries/#emsgsize-and-udp-buffer-limits

**Comment by hyhanyan** [comment]
Ok， thanks
