### ISSUE TITLE
Jaeger-cassandra-schema compatibility with cassandra 

### ISSUE THREAD

**Issue by princeop** [jaegertracing/jaeger#189]
Using jaeger-cassandra-schema docker with cassandra 3.0.12 causes this exception 

`<stdin>:156:ConfigurationException: Unable to find custom indexer class 'org.apache.cassandra.index.sasi.SASIIndex'` on this line:

`CREATE CUSTOM INDEX ON ${keyspace}.dependencies (ts_index) USING 'org.apache.cassandra.index.sasi.SASIIndex' WITH OPTIONS = {'mode': 'SPARSE'};`

This in turn causes to dependency functionality not working on jaeger-query docker:

`"Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING"`

SASIIndex in available in cassandra since version 3.4+

**Comment by black-adder** [comment]
Thanks for catching this, we removed SASI indexes but forgot to do it for the dependencies table, we'll get rid of it.

**Comment by omeid** [comment]
Any update on this?

**Comment by black-adder** [comment]
It's a breaking change as of this moment so we're gonna cut a release and then fix it for the upcoming release

**Comment by jpkrohling** [comment]
This should have been fixed by #278 .

**Comment by yurishkuro** [comment]
@jpkrohling it won't be - the request in this issue is to support _older_ versions of Cassandra, specifically pre-3.4 when SASI indices were not available. The Dependencies table is the only one still using a SASI index.

**Comment by rajatparida86** [comment]
Any updates on this fix?

**Comment by yurishkuro** [comment]
I expect it to happen within a month.

**Comment by jpkrohling** [comment]
Took a bit more than a month, but I think this is now fixed :-)
