### ISSUE TITLE
Jaeger agent as windows service 

### ISSUE THREAD

**Issue by ArturBhasker** [jaegertracing/jaeger#1890]
## Requirement - what kind of business use case are you trying to solve?

Run jaeger-agent on machine as windows service.
## Problem - what in Jaeger blocks you from solving the requirement?
There are no any possible way to run jaeger-agent as windows service. Jaeger agent could run as console application or docker. I can use 3rd party utils to run as service, but it hasn't track jaeger-agent application work. It cause many problems e. g. jaeger-agent can be stopped, but service will continue work with failed agent without any warning.
I didn't find any solution of this problem in project. Do you have task to create service?

**Comment by jpkrohling** [comment]
I have no idea what it would involve to have a proper Windows service. What kind of changes are required? If it's not too invasive, we could certainly consider incorporating support for it.

**Comment by ArturBhasker** [comment]
I want to launch jaeger-agent in windows sc. Something like

   sc create jaegerService binpath= "C:\jaeger-agent.exe --reporter.grpc.host-port=somehost:14267"

Is there any way to do it?

**Comment by jpkrohling** [comment]
I'm not aware of any maintainer who develops on Windows, but speaking only for myself, the answer is: I don't know. If it's not working as a regular service, then we'd need more information and a volunteer to fix whatever is broken.

**Comment by pavolloffay** [comment]
Is the problem with passing the flags? If so did you try this https://stackoverflow.com/a/10472078/4158442?

**Comment by bocharovf** [comment]
Seems like to be a "windows service" application should respond to special commands from Windows. If we use sc util with jaeger agent it could not be started at all.
 
There is "svc" package in Go to build windows services:
https://godoc.org/golang.org/x/sys/windows/svc
https://github.com/golang/sys/tree/master/windows/svc/example

Maybe we could use "svc" package and introduce addtitional "windows only" flag to install and start agent as a service "--windows.service install/remove/start/stop".

**Comment by yurishkuro** [comment]
Sounds reasonable. I would put it behind a build tag so that this doesn't even come up for non-Windows builds.

**Comment by ScottKaye** [comment]
I'm using [NSSM](https://nssm.cc/) to run Jaeger instances, which works quite well already.  It just wraps the agent (or any executable) and handles the windows service stuff for you.

```
nssm stop JaegerAgent
nssm remove JaegerAgent confirm

nssm install JaegerAgent C:\Jaeger\jaeger-1.14.0-windows-amd64\jaeger-agent.exe --reporter.grpc.host-port=localhost:14250

nssm set JaegerAgent AppStdout C:\Jaeger\logs\jaeger-agent.out.log
nssm set JaegerAgent AppStderr C:\Jaeger\logs\jaeger-agent.err.log
nssm set JaegerAgent Description Jaeger Agent service

nssm start JaegerAgent
```

**Comment by jpkrohling** [comment]
@ScottKaye would you be open to contribute that to our docs? It could either belong to the main ["Deployment"](https://github.com/jaegertracing/documentation/blob/master/content/docs/next-release/deployment.md) page, or to a new page sibling to ["Kubernetes"](https://github.com/jaegertracing/documentation/blob/master/content/docs/next-release/operator.md)

**Comment by ArturBhasker** [comment]
Yeah! We can use nssm, but as I say below, it woldn't save log in windows event journal and service wouldn't monitor the work of jaeger-agent console

**Comment by ScottKaye** [comment]
@jpkrohling Created jaegertracing/documentation#320.  This is my first pull request in a very long time!

@ArturBhasker It looks like NSSM does write to the event log on process failure, at least for me.  In my example I'm also redirecting stdout and stderr to a file, which can be read/streamed for monitoring if required.
