### ISSUE TITLE
Does Jager support connecting Jaeger-collector to the Elastic Search hosted as a PaaS service?

### ISSUE THREAD

**Issue by vkadiwala** [jaegertracing/jaeger#1891]
## Requirement - what kind of business use case are you trying to solve?
Connecting to Jaeger-collector and jaeger-query service to Elastic search hosted as a PaaS service.

## Problem - what in Jaeger blocks you from solving the requirement?

![image](https://user-images.githubusercontent.com/46812966/68024318-c4b2e900-fccf-11e9-9d28-da3e8d50d005.png)

**Comment by jpkrohling** [comment]
Could you please share the jaeger-collector and jaeger-query logs?

**Comment by vkadiwala** [comment]
Thanks for your help, we identified that using Elastic search version 7.x has introduced this issue. Once we downgraded Elastic search to 6.8.x, Jaeger is working without any issue and able collect and display Traces.

**Comment by yurishkuro** [comment]
@pavolloffay I thought we support ES 7.x

**Comment by pavolloffay** [comment]
We do support ES7 since Jaeger 1.14. What version of Jaeger are you using?

Jaeger binaries should show log `"Elasticsearch detected"` with correct ES version at startup. You can force the version by `--es.version=`.

**Comment by pavolloffay** [comment]
@vkadiwala I am closing this as there is not enough information about the problem - jaeger version, logs...

Please reopen the issue if the problem still happens and provide more information
