### ISSUE TITLE
Add SSL verification mode parameter for rollover script

### ISSUE THREAD

**Issue by weeco** [jaegertracing/jaeger#1898]
## Problem - what in Jaeger blocks you from solving the requirement?

Currently it is possible to specify TLS certificates, but it isn't possible to specify the verification mode for Elasticsearch here: https://github.com/jaegertracing/jaeger/blob/d85776db9cce72ae714da89dbd09e5dcea9eddb4/plugin/storage/es/esRollover.py

Since I only want to run this once, I'd usually go ahead and port forward one of the elasticsearch nodes and execute the script against localhost using the docker run command. Unfortunately I'd need to mount the CA certificate into the container now, which makes it more cumbersome to execute.

Instead I'd like to set the SSL verification mode to none for the setup request. It should be fairly simple to add a parameter to the script and use that for the connection.

**Comment by pavolloffay** [comment]
done in #1918
