### ISSUE TITLE
Add flag allow disable gzip encoding on jaeger-query

### ISSUE THREAD

**Issue by Sasasu** [jaegertracing/jaeger#1899]
### Problem
Some HTTP client cannot process gzip encoding automatically

I can't change the HTTP client behavior

### Proposal 

Add a flag, allow disable gzip encoding

```
--query.gzip    enable gzip compress (default true)
```

**Comment by yurishkuro** [comment]
Compression is only applied if the client indicates that it wants it in the `Accept-Encoding` header.

**Comment by jpkrohling** [comment]
@Sasasu are you facing a specific problem with that? Are you able to provide a reproducer? As @yurishkuro mentioned, the regular content negotiation should be skipping the gzip compression if the client doesn't support it, but we might have a bug somewhere.

**Comment by jpkrohling** [comment]
From https://github.com/jaegertracing/jaeger/pull/1900#issuecomment-550940480:

> the client is `ribbon` with `eureka` with `RestTemplate(org.springframework.web.client.RestTemplate)` reported by another Java developer.

**Comment by Sasasu** [comment]
I think this is RestTemplate's bug.

The HTTP client supports gzip encoding, but `RestTemplate` uses some `readRawBody` method then tries to deserialize the HTTP body to Java class.

The code is 
```java
ResponseEntity<DescribeTopologyResponse> responseEntity = this.restTemplate.exchange(url, HttpMethod.GET, entity, DescribeTopologyResponse.class, request);
```
`this.restTemplate` was initialized by spring.

The HTTP client does send `Accept-Encoding: gzip`.
The HTTP client support decodes gzip by using some `readBody` method.
But RestTemplate does not use the method which supports gzip encoding...

I think this is the Java ecosystem's problem, not jaeger or gorilla/mux's problem.

**Comment by yurishkuro** [comment]
Please open a ticket with Spring to fix it. Closing this ticket.
