### ISSUE TITLE
Allow configuration of Cassandra tag indexing

### ISSUE THREAD

**Issue by joe-elliott** [jaegertracing/jaeger#1901]
## Requirement - what kind of business use case are you trying to solve?

Our Jaeger installation is currently constrained by the number of tag indexes written into Cassandra/Scylla.  We are ingesting ~7.5k spans/second and ~75k tag indexes/second.

We would like a central place to control/reduce the number of tags we index.  This would allow us to increase our sampling rate and capture more spans/second.

## Problem - what in Jaeger blocks you from solving the requirement?

The Jaeger Cassandra StorageFactory internally has support for tag filters, but they are not configurable: 
https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/spanstore/writer.go#L124

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Expose two simple filters that allow for tag indexing control:

`cassandra.tag-index-blacklist`
`cassandra.tag-index-whitelist`

These two filters would be a comma delimited list of tags to white or blacklist by exact match.  They would be mutually exclusive.  

## Any open questions to address
None.

**Comment by joe-elliott** [comment]
Given how simple this is I'm working on a PR now for it as it's written.  I'd be glad to make adjustments as necessary or drop it if it's not desired.

**Comment by yurishkuro** [comment]
+1. At Uber we also disabled log indexing altogether, so we're only indexing select tags.

**Comment by joe-elliott** [comment]
@yurishkuro Feel free to assign to me.  I should have a PR together soon.
