### ISSUE TITLE
Allow disabling of log indexing

### ISSUE THREAD

**Issue by joe-elliott** [jaegertracing/jaeger#1905]
## Requirement - what kind of business use case are you trying to solve?

In order to increase spans throughput to Cassandra we need more control over what is indexed.  Currently all logs are being indexed.  Once https://github.com/jaegertracing/jaeger/issues/1904 is merged we will have more control, but it would be nice to just disable log indexing all together.

## Problem - what in Jaeger blocks you from solving the requirement?

There is a partial implementation already: https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/spanstore/dbmodel/log_fields_filter.go

It just needs to be exposed as a configuration option.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add a boolean configuration option to the Cassandra backend `index-logs` that defaults to true.

## Any open questions to address

None

**Comment by joe-elliott** [comment]
I would be glad to begin working on this as soon as https://github.com/jaegertracing/jaeger/issues/1901 is merged.  The changes touch some of the same areas.

**Comment by yurishkuro** [comment]
NB: while the CLI flag could be "positive" ("enable"), the struct field should be negative (DisableLogIndexing) so that the default behavior of the storage doesn't change.
