### ISSUE TITLE
Optimize all-in-one and Docker CI steps

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1908]
One of the longest parts of all-in-one and Docker steps is building the UI, which is now repeated (after #1909).

We can either combine these two steps, or fix the scripts to skip building the UI when on a PR build.

**Comment by Eileen-Yu** [comment]
Wondering about the status of this issue?
See there is a discussion over a previous closed PR when CI is performed over travis, do we have progress for this OR we may like some step forward to improve the build of all-in-one?

**Comment by yurishkuro** [comment]
This has been fixed by #4251, closing.
