### ISSUE TITLE
how to clean jaeger history data in istio

### ISSUE THREAD

**Issue by linkingli** [jaegertracing/jaeger#1914]
hello,how to clean jaeger history data? i deploy a application in istio,but when i update service,there still some old version history,so i have to delete jaeger pod,:(.
like following, there are same old versions about the same service,but i only want the "eshop" service
![image](https://user-images.githubusercontent.com/28832157/68531558-857b3c80-034e-11ea-9c6f-5579738aa6e1.png)

so i have to delete pod for jaeger:(
```
istio-system   istio-tracing-669fd4b9f8-xcbl2            1/1     Running   0          51m
```

**Comment by linkingli** [comment]
forget the following information
```
Image:          docker.io/jaegertracing/all-in-one:1.12
istio version:      1.3.3
kubenetes version:     1.14.7
```

**Comment by yurishkuro** [comment]
Deleting data is not supported by any Jaeger storage implementations, but many of them do support TTL.
