### ISSUE TITLE
Cassandra & memory storage update: query service to support spanKind when retrieve operations for a given service.

### ISSUE THREAD

**Issue by guo0693** [jaegertracing/jaeger#1921]
## Requirement - what kind of business use case are you trying to solve?
Related to #1920 

- Cassandra & memory storage update: query service to support spanKind when retrieve operations for a given service.

- Update query service so that the restful & grpc endpoints satisfy requirement in #1920.

**Comment by yurishkuro** [comment]
this ticket is redundant, it's sufficient to have #1920

**Comment by guo0693** [comment]
Done
