### ISSUE TITLE
Converting JSONSpan to domain Span failed: encoding/hex: invalid byte: U+002E '.'

### ISSUE THREAD

**Issue by hyhanyan** [jaegertracing/jaeger#1926]

**Comment by hyhanyan** [comment]
use jaeger-ui , 
![image](https://user-images.githubusercontent.com/11550403/68939703-22980400-0799-11ea-9d76-a2578723625c.png)

**Comment by yurishkuro** [comment]
I am assuming you're using Elasticsearch?  Since it's the only storage that uses JSON as representation.

There may be data corruption in the storage, or a bug in the write path. I'd recommend looking in the storage for what kind of data is stored. Hex encoding would be used for trace/span IDs.

**Comment by yurishkuro** [comment]
cc @pavolloffay

**Comment by hyhanyan** [comment]
@yurishkuro Thanks, I will try it

**Comment by hyhanyan** [comment]
@yurishkuro Thanks, I will try it

**Comment by pavolloffay** [comment]
@hyhanyan could you please provide a reproducer? 

The best would be to read the data from ES index directly e.g. `curl http://localhost:9200/jaeger-span*/_search?`

and try to post here segment which is causing the issue.

**Comment by pavolloffay** [comment]
Closing in favor of #1960
