### ISSUE TITLE
Can you told me where is the code about kafka client in jaeger collector

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1936]
I check collector but I haven't found any code about kafka producer send spans to kafka in collector
https://github.com/jaegertracing/jaeger/tree/master/cmd/collector.
 Can you tell me where it is?

[
![image](https://user-images.githubusercontent.com/12801407/69179441-8abc5200-0ad9-11ea-87d2-9045657f692c.png)
](url)

**Comment by jpkrohling** [comment]
Kafka is set as a storage backend, and the code is mainly here:
https://github.com/jaegertracing/jaeger/tree/master/plugin/storage/kafka

The consumer side is the "ingester" component: https://github.com/jaegertracing/jaeger/tree/master/cmd/ingester

The official documentation is here:
https://www.jaegertracing.io/docs/1.15/deployment/#kafka

And here:
https://www.jaegertracing.io/docs/1.15/deployment/#ingester
