### ISSUE TITLE
Release with fix in issue #747

### ISSUE THREAD

**Issue by kvaidas** [jaegertracing/jaeger#1938]
## Requirement - what kind of business use case are you trying to solve?

Configuring jaeger-query to report its spans over http to a collector instance.

## Problem - what in Jaeger blocks you from solving the requirement?

The configuration does not work since the envvars are not respected for jaeger-query.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

This has already been fixed in issue #747 but hasn't been released.

## Any open questions to address

Can a new release be made that would include this fix?

**Comment by yurishkuro** [comment]
It will be included in the next release, sometime in December.
