### ISSUE TITLE
A small bug when the time on my server is not accurate

### ISSUE THREAD

**Issue by LeBW** [jaegertracing/jaeger#1948]
## Requirement - what kind of business use case are you trying to solve?
I am a college student, and I'm learning the basics of Jaeger now.

## Problem - what in Jaeger blocks you from solving the requirement?
It's about a small bug. 

I can't get any traces by default even if I configure everything right as in `Get Started`.  It upset me for a long time and  I finally found out that it's because the time on my server is not accurate( it's 20min later than normal), so Jaeger thinks that my traces are generated in the future. And Jaeger shows traces last hour by default, so it doesn't show anything in this case. I can't get any traces until I use 'custom time range' finally. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?
I think that maybe this is because Jaeger doesn't use local time but the 'hotrod' uses local time. What should I do if it's not convenient for me to accurate my server time?

**Comment by yurishkuro** [comment]
why do you call it "a bug"?  It sounds like Jaeger is behaving as expected. I am not sure it's worth it for Jaeger to try to deal with massive clock skews between the browser and the servers that generate the spans.

**Comment by LeBW** [comment]
> why do you call it "a bug"? It sounds like Jaeger is behaving as expected. I am not sure it's worth it for Jaeger to try to deal with massive clock skews between the browser and the servers that generate the spans.

Sorry but I finally got that the time we use to search depends on our browsers. Thanks.
