### ISSUE TITLE
[cassandra-schema] Make schema job run migration if TTL value changed

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/jaeger#1958]
## Requirement - what kind of business use case are you trying to solve?

I would like to like to adjust trace data TTL on the fly. While initially setting it with the schema job to say `60`, I would like to run the schema job again and have it changed to `2400` for example.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Have the schema job perform a migration if a value has changed.

**Comment by yurishkuro** [comment]
You can simply run `ALTER TABLE` against the relevant tables in your database and change the TTLs . 

I don't feel that it's worth the trouble of maintaining yet another script.

**Comment by naseemkullah** [comment]
Fair enough! Thanks.
