### ISSUE TITLE
Does Jaeger collector creates jaeger-service* index in elastic everyday? 

### ISSUE THREAD

**Issue by raz08** [jaegertracing/jaeger#1959]
## Requirement - what kind of business use case are you trying to solve?
Need to clean older indexes and spans from elastic.

## Any open questions to address
If yes, then why it is configured for 1 day?

**Comment by pavolloffay** [comment]
By default jaeger stores data in daily indices. This can be changed by using rollover https://www.jaegertracing.io/docs/1.17/deployment/#elasticsearch-rollover
