### ISSUE TITLE
Configure Jager Collector to work with Kafka With Basic Authentication 

### ISSUE THREAD

**Issue by vipinvkmenon** [jaegertracing/jaeger#1966]
## Requirement - 
Looking to integrate with Kafka which is provided by a platform Service. However, the kafka service provided by the platform only supports basic authentication

## Problem - 
The jager documentation or options did not indicate support for Kafka basic authentication

As a result, we would not be able to integrate our Jaeger solution with existing Kafka Services provided with our platform
## Proposal -
Jaeger to support authentication mechanisms provided by Kafka
## Any open questions to address

Is it available? Is it documentation that I possibly missed? Or is there a reason why it was not implemented?
(Maybe some best practise that I am unaware of)

**Comment by yurishkuro** [comment]
Wouldn't basic auth be sent in clear text? I can see how it can be useful with HTTPS, but without TLS is sounds like an anti-pattern.

But, if the sarama driver supports it, it is fairly easy to add.

**Comment by vipinvkmenon** [comment]
@yurishkuro 
Thank you for your quick reply. Also Loved your book :)
In this case, the Kafka service provides IPs that can only be accessed within the boun application
IE The IP cannot be externally accessed and only the service/app (Jaeger Collector/Jaeger Ingestor) bound to the Kafka service would have access to the network which has Kafka in it.

**Comment by chandresh-pancholi** [comment]
I am picking it up if anyone haven't started.
