### ISSUE TITLE
Enable multiplexing of "/api/traces" endpoint

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#1967]
## Requirement - what kind of business use case are you trying to solve?

`cmd/collector/app/http_handler.go` defines the `/api/traces` HTTP endpoint allowing callers to save spans.

The current use of this endpoint is for external AWS authenticated callers. However, there is a requirement now for services within the organization's internal network to make direct calls to the collector to save spans; with a new HTTP endpoint `/api/internal/traces`. 

In effect, this multiplexes the external and internal endpoints to the same "saveSpan" handler:
```
         /api/traces --
                        \
                          -------->  Save Span Handler
                        /
/api/internal/traces --
```

Why HTTP? 
Our internal collectors support HTTP, TChannel and gRPC endpoints for submitting spans, so a natural question is, why choose to expose this additional endpoint in HTTP instead of TChannel or gRPC?

Jaeger clients were designed to talk to agents running on hosts listening over thrift over UDP endpoints for submitting spans, as well as exposing other HTTP endpoints such as for querying sampling rates.
Hence our Jaeger clients currently only support calling HTTP endpoints and not TChannel or gRPC. It is worth noting there have been expressions of interest for Jaeger clients to support calling gRPC endpoints, however, it was a non-trivial change due to taking on additional dependencies.

## Problem - what in Jaeger blocks you from solving the requirement?

The `APIHandler` struct within `cmd/collector/app/http_handler.go` implements the `RegisterRoutes` interface function which registers the `/api/traces` endpoint to the `*APIHandler.saveSpan` handler function.

The `RegisterRoutes` function takes in a single `router *mux.Router` parameter, and the function is responsible for knowing exactly what endpoints to expose and handler functions to map to those endpoints.
There, however, does not appear to be a way to support the above requirement of configuring more that one endpoint to the same handler.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The proposal is to export the `saveSpan` function to:
```
func (aH *APIHandler) SaveSpan(w http.ResponseWriter, r *http.Request)
```

... enabling embedding of the `APIHandler` in our internal repository, essentially "subclassing" this struct like so:

```
type InternalAPIHandler struct {
	app.APIHandler
}

func NewInternalAPIHandler(apih *app.APIHandler) *InternalAPIHandler {
	return &InternalAPIHandler{APIHandler: *apih}
}

func (iapih *InternalAPIHandler) RegisterRoutes(router *mux.Router) {
	iapih.APIHandler.RegisterRoutes(router)
	router.HandleFunc("/api/internal/traces", iapih.SaveSpan).Methods(http.MethodPost)
}
```

## Alternatives considered

1. `RegisterRoutes` can register multiple endpoints and does not assume registering of just a single handler, hence changing the interface to pass multiple endpoint paths is not a valid option, let alone breaking the interface for other implementers and callers.

2. Another possibility is to hardcode the additional endpoint within `RegisterRoutes` like so:
```
router.HandleFunc("/api/traces", aH.saveSpan).Methods(http.MethodPost)
router.HandleFunc("/api/internal/traces", aH.saveSpan).Methods(http.MethodPost)
```
However, this use case of both an authenticated and unauthenticated endpoint for saving spans is specific to our organization and it's unlikely other users would have the same use case.

## Any open questions to address

Is it safe to have multiple endpoints calling the same `APIHandler.SaveSpan` function? Are there any concurrency-related concerns such as race conditions or data corruption?

**Comment by yurishkuro** [comment]
sgtm
