### ISSUE TITLE
Replicate /sampling endpoint from agent in the collector

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1971]
## Requirement - what kind of business use case are you trying to solve?

When using HTTP reporters in the clients to export tracing data directly to the collectors, users still want to be able to use remote sampler that loads centrally managed sampling strategies.

## Problem - what in Jaeger blocks you from solving the requirement?

The `/sampling` endpoint is only implemented in the agent today.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Expose the same endpoint from the collectors, e.g. `/api/sampling`.

**Comment by yurishkuro** [comment]
When this is done, update FAQ docs, cf. https://github.com/jaegertracing/documentation/pull/335

**Comment by namratachaudhary** [comment]
Hi
If this is still open, I can take it up.

**Comment by jpkrohling** [comment]
It's yours.

**Comment by RickyRajinder** [comment]
Hi @namratachaudhary I have already submitted a PR for this issue.

**Comment by yurishkuro** [comment]
Open question: can clients be configured with a different sampling URL?

**Comment by yurishkuro** [comment]
Clients support the following config options:
  * JAEGER_ENDPOINT, e.g. `http(s)://collector:port/api/traces`
  * JAEGER_SAMPLER_MANAGER_HOST_PORT - name implies no part is allowed

Possible solutions:
  * We could introduce JAEGER_SAMPLING_ENDPOINT, but that still leaves out other configurations like baggage restrictions. 
  * We could introduce JAEGER_CONFIG_ENDPOINT, but that wouldn't be a real endpoint, but a base address, with `/sampling` or `/baggage` path added by the client as needed.
  * We could introduce JAEGER_API (or something along these lines) that will be the base address used by both span reporter (by adding `/traces`) and sampler (by adding `/sampling`).

Q: is it better to hardcode the final segments of the URL in the clients or make them configurable? Strictly speaking the URL path is part of the contract, e.g. if we introduce a different format of the sampling output it should become `/api/v2/sampling` or something like that.

cc @jpkrohling @pavolloffay @objectiser

**Comment by pavolloffay** [comment]
> Q: is it better to hardcode the final segments of the URL in the clients or make them configurable?

I would lean towards the consistency and require configuring the full URL. It's more flexible and one could deploy it on different path.

**Comment by yurishkuro** [comment]
@pavolloffay so you'd vote for JAEGER_SAMPLING_ENDPOINT?

**Comment by yurishkuro** [comment]
This is done.
