### ISSUE TITLE
Travis CI arm64 support

### ISSUE THREAD

**Issue by jishminor** [jaegertracing/jaeger#1973]
## Requirement - what kind of business use case are you trying to solve?

Run and test all Jaeger components on arm64.

## Problem - what in Jaeger blocks you from solving the requirement?

No existing infrastructure to build and test Jaeger components on arm64.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Travis CI can now run multiarch builds out of the box: https://docs.travis-ci.com/user/multi-cpu-architectures/.

## Any open questions to address

Would there be any interest in modifying the CI configuration to support arm64 builds?

**Comment by yurishkuro** [comment]
I'd be concerned with how much extra load it would add to our CI jobs, which already take quite a while to run for each PR.

**Comment by jpkrohling** [comment]
I think we could consider adding it at least for the unit tests. I think it would cover most of the arch-related issues that we might face.

**Comment by jishminor** [comment]
Pushing the arm64 docker images to dockerhub would also be a great addition.

**Comment by jpkrohling** [comment]
@jishminor are you able to commit to support this when it needs maintenance? If so, send a PR with your proposal and let's see how the CI gets affected.

**Comment by jishminor** [comment]
I have only so far been using an arm64 jaeger agent, which speaks to a x86 jaeger collector. I still need to fully familiarize myself with your build and test infrastructure before I can give my commitment for maintenance support for arm64. Let me do some experimenting and get back to you. I don't for-see many things breaking when swapping out the x86 go runtime for the arm64, besides any OS level package use (syscall interfaces etc).

**Comment by jpkrohling** [comment]
Let us know if you hit any roadblocks!

**Comment by vielmetti** [comment]
@jishminor have you had any success here? If you need arm64 infrastructure to test or develop, reach out to the @worksonarm project via opening an issue at https://github.com/worksonarm/cluster/issues .

**Comment by jishminor** [comment]
@vielmetti I have not yet. I have my own repository for the Jaeger Agent on arm64 and arm, but have not gotten around to playing with the build infrastructure in this repo.

**Comment by MrXinWang** [comment]
Hi @jishminor! I am wondering will you propose a PR to add support for arm64? If not, I have a PR to support it :) Can I propose it? or I wait for yours?

**Comment by yurishkuro** [comment]
ARM64 binaries are already supported (#1656) as part of the release (but not the Docker images).

We don't have the CI resources to do integration testing on all supported platforms. I am closing this.
