### ISSUE TITLE
logs problem in the jaeger UI

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1974]
What I found that the maximum of logs in each span is 32 which showing in jaeger UI. Is it possible to adjust it?

![image](https://user-images.githubusercontent.com/12801407/70632517-f8e9c580-1bfc-11ea-849a-eb6d414447e6.png)

**Comment by yurishkuro** [comment]
Are you using opencensus client, by chance? IIRC it has this limit.

**Comment by zheyiyi** [comment]
Yes, I use opencensus.  I will look whether it can be config or not. Thanks.

Yuri Shkuro <notifications@github.com> 于2019年12月11日周三 上午10:02写道：
