### ISSUE TITLE
1.16.0 Cassandra add +x to V002toV003.sh

### ISSUE THREAD

**Issue by Sasasu** [jaegertracing/jaeger#1981]
### Problem - what in Jaeger blocks you from solving the requirement?
V002toV003.sh should be executable like others

![image](https://user-images.githubusercontent.com/12945182/71055721-a3c82980-2191-11ea-840a-59da428d8090.png)

### Proposal - what do you suggest to solve the problem?
`chmod +x V002toV003.sh`

**Comment by jpkrohling** [comment]
@Sasasu have you used this script to migrate your data? How was the procedure? We just released the Jaeger Operator v1.16.0 and decided to not apply the migration automatically, as we thought that it would be better for a human operator to be involved, as it probably requires a downtime on the collector.

Your experience might either validate our decision or help us change our minds :-)
