### ISSUE TITLE
A lot of trace without root warning both elasticsearch and cassandra storage backend 

### ISSUE THREAD

**Issue by liuzijuan123** [jaegertracing/jaeger#1984]
when the amount of span is low there are no spans lost, but when the amount of span is about 250k per minute, about 80% span data lost, I also set the ndex.translog.durability to async , it doesn't work,What other methods I can try.
Thank you very much

**Comment by jpkrohling** [comment]
Please, check the performance tuning guide: https://www.jaegertracing.io/docs/1.16/performance-tuning/
