### ISSUE TITLE
examples/hotrod can't compile

### ISSUE THREAD

**Issue by cuiyuan** [jaegertracing/jaeger#1998]
~/Projects/gocode/jaeger/examples/hotrod on git:master x [9:46:48]
$ go build

go: github.com/gocql/gocql@v0.0.0-20180506184654-181004e14a3f: parsing go.mod: go.mod:6: invalid module: gopkg.in/inf.v0 should be .v0, not v1 (v1.9.1-gopkgin-v0.9.1)
go: error loading module requirements

**Comment by yurishkuro** [comment]
Jaeger does not use go modules yet. See instructions in https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING.md#getting-started
