### ISSUE TITLE
How to use jaeger's UI to read data from the elasticsearch written by zipkin.

### ISSUE THREAD

**Issue by uckyk** [jaegertracing/jaeger#2001]
We currently use zipkin to collect data (jaeger does not support Dubbo). ES stores zipkin data. I know that zipkin and jaeger have different data formats. Maybe I need to set up a query service and then go to ES to query. (I don't know how to build it)
I would like to know if jaeger provides such tools for data conversion between zipkin and jaeger.

I am a beginner, thank you very much！！！

**Comment by objectiser** [comment]
You can use zipkin tracer in the client, but report the data to the Jaeger collector which provides a zipkin compatible http port (9411). This way, Jaeger will convert the zipkin format data into its own format and then store in Elasticsearch - and allow the traces to be queried using the Jaeger UI.

I'll close - if you have any further questions feel free to reopen.

**Comment by uckyk** [comment]
> You can use zipkin tracer in the client, but report the data to the Jaeger collector which provides a zipkin compatible http port (9411). This way, Jaeger will convert the zipkin format data into its own format and then store in Elasticsearch - and allow the traces to be queried using the Jaeger UI.
> 
> I'll close - if you have any further questions feel free to reopen.

HTTP is not allowed in our company

According to what you said, I use Zipkin client to send the data to Kafka (), consume Kafka data through Jaeger server, and then store it in ES. Finally, use the Jaeger UI to show it. Is this solution OK?

Is there another better solution? Thank you very much.

**Comment by objectiser** [comment]
@uckyk Unfortunately the ingester only accepts jaeger format trace data from kafka. Zipkin format is only supported via http currently. If you are interested in this approach, then I would suggesting creating a feature request (issue) where the idea can be evaluated.

**Comment by uckyk** [comment]
> @uckyk Unfortunately the ingester only accepts jaeger format trace data from kafka. Zipkin format is only supported via http currently. If you are interested in this approach, then I would suggesting creating a feature request (issue) where the idea can be evaluated.

Is the format of the data reported to Kafka different from that reported by HTTP? Isn't the last data format stored the same? The problem is a little idiotic. Sorry...

Is the final stored data area is Clinet or  collecotor. I messed up......

**Comment by objectiser** [comment]
Jaeger in general only deals with its own format, whether received via http, grpc or kafka. In addition, the jaeger-collector accepts zipkin format via http (on a different port from jaeger's http port) - but currently not via any other protocols.

**Comment by pavolloffay** [comment]
Jaeger ingester is able to consume data in `zipkin-thrift` encoding. (the ingester is a component which reads data from kafka and writes them to storage {cassandra, es...}).

```
--kafka.consumer.encoding string                  The encoding of spans ("json", "protobuf", "zipkin-thrift") consumed from kafka (default "protobuf")
```

**Comment by uckyk** [comment]
> Jaeger in general only deals with its own format, whether received via http, grpc or kafka. In addition, the jaeger-collector accepts zipkin format via http (on a different port from jaeger's http port) - but currently not via any other protocols.



> Jaeger in general only deals with its own format, whether received via http, grpc or kafka. In addition, the jaeger-collector accepts zipkin format via http (on a different port from jaeger's http port) - but currently not via any other protocols.

I understand that Jaeger only accepts his own data. Jaeger can use HTTP to be compatible with Zipkin data. The reason is Jaeger's transformation of Zipkin HTTP data transmission. Am I right?

**Comment by uckyk** [comment]
> Jaeger ingester is able to consume data in `zipkin-thrift` encoding. (the ingester is a component which reads data from kafka and writes them to storage {cassandra, es...}).
> 
> ```
> --kafka.consumer.encoding string                  The encoding of spans ("json", "protobuf", "zipkin-thrift") consumed from kafka (default "protobuf")
> ```

yes, thats mean, i can use  jaeger ingester to consume data from kafka then  storege to es, and use jaegerUI to view it.
