### ISSUE TITLE
Add context to spanstore.Writer interface

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#2006]
## Problem - what in Jaeger blocks you from solving the requirement?
https://github.com/jaegertracing/jaeger/blob/009b7f57fe54b54696a05fdd28cb445c597ca146/storage/spanstore/interface.go#L27-L29

The `spanstore.Writer` interface does not propagate context.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add a new `WriteSpanWithContext(ctx context.Context, span *model.Span) error` to propagate context. 

Alternatively, we may update to `WriteSpan(ctx context.Context, *model.Span) error`. 

Unfortunately, both of these are breaking changes. Alternatively, we may create a `WriterV2` interface, and supply a converter from `Writer` to `WriterV2`. Such a converter would simply use `ctx.Background()` for the context parameter.

**Comment by yurishkuro** [comment]
I would vote for simply changing the signature to `WriteSpan(ctx context.Context, *model.Span) error`. We did the same for the Reader interface in #1038.

**Comment by jpkrohling** [comment]
Implemented via https://github.com/jaegertracing/jaeger/pull/2436
