### ISSUE TITLE
Every 10 minutes agent grpc disconnected from collector

### ISSUE THREAD

**Issue by floatliang** [jaegertracing/jaeger#2011]
## Requirement - what kind of business use case are you trying to solve?

Tracing http calls of my microservice

## Problem - what in Jaeger blocks you from solving the requirement?

I launched agent and collector 1.14 in docker.
Recently i checked agent logs with docker container logs agent and find that:

`{"level":"info","ts":1578533821.070084,"caller":"base/balancer.go:140","msg":"base.baseBalancer: handle SubConn state change: 0xc0002a45b0, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1578533821.07017,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1578533821.0700924,"caller":"transport/log.go:30","msg":"transport: loopyWriter.run returning. connection error: desc = \"transport is closing\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1578533821.0705376,"caller":"base/balancer.go:140","msg":"base.baseBalancer: handle SubConn state change: 0xc0002a45b0, READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1578533821.0706186,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[{127.0.0.1:14250 0  <nil>}:0xc0002a45b0]","system":"grpc","grpc_log":true}
{"level":"info","ts":1578534001.1125383,"caller":"base/balancer.go:140","msg":"base.baseBalancer: handle SubConn state change: 0xc0002a45b0, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1578534001.1126258,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[]","system":"grpc","grpc_log":true}
{"level":"info","ts":1578534001.112556,"caller":"transport/log.go:30","msg":"transport: loopyWriter.run returning. connection error: desc = \"transport is closing\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1578534001.1129324,"caller":"base/balancer.go:140","msg":"base.baseBalancer: handle SubConn state change: 0xc0002a45b0, READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1578534001.1130183,"caller":"roundrobin/roundrobin.go:50","msg":"roundrobinPicker: newPicker called with readySCs: map[{127.0.0.1:14250 0  <nil>}:0xc0002a45b0]","system":"grpc","grpc_log":true}
`

It seems agent disconnected from collector every 10 minutes, is it a bug or just a normal case?

**Comment by jpkrohling** [comment]
This should *not* be happening. Are you running those images locally, or are you deploying them in some infra provider, like AWS? I remember reports about something similar happening on an AWS setup.

**Comment by floatliang** [comment]
@jpkrohling  I deployed one agent image and two collector images locally， all in one physical machine.
Actually i have also deployed nginx between agent and collector, could it cause this problem?
Here is my nginx config:
```text
upstream  collector_server {
    server xxx.xxx.xxx.xxx:14260 weight=1 fail_timeout=10 max_fails=1;
    server xxx.xxx.xxx.xxx:14261 weight=1 fail_timeout=10 max_fails=1;
}

server {
    listen   14250 http2;
    server_name xxx.xxx.xxx.xxx;
    access_log /nginx_log/collector_14250.access.log main;

    location / {
        grpc_pass grpc://collector_server;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}

```
Does this problem has any effect of the tracing service? actually it seems works fine under my monitor:
![image](https://user-images.githubusercontent.com/33773361/72120827-307e9580-3394-11ea-8a00-7bd575dc4269.png)
![image](https://user-images.githubusercontent.com/33773361/72120846-412f0b80-3394-11ea-861e-a0a398dc051d.png)

**Comment by jpkrohling** [comment]
TIL that NGINX has native options for gRPC, that sounds really cool :-) In any case, I would try to keep NGINX out of the setup for a while, to check whether that's the component closing the connections.

**Comment by floatliang** [comment]
@jpkrohling  Ahh, i also learned it from my colleagues. I'll try deploy agent and collector without nginx later, if there are any results i'll let you know : )

**Comment by floatliang** [comment]
@jpkrohling sorry for latter reply. recently i tried launching agent and collector images without nginx, and find that it works well, and no more complain about losting connection.
I googled for a while, guess it may caused by nginx periodically  closing connections to grpc server according to the directive [keepalive_timeout], by default it's 65s.
I set this directive to 300s to see what will happen.

**Comment by jpkrohling** [comment]
May I ask you something then? Your findings might save someone else's time. Would you be open to send a PR to the "troubleshooting guide" adding this? https://github.com/jaegertracing/documentation/blob/master/content/docs/next-release/troubleshooting.md
