### ISSUE TITLE
cpu limit for jaeger-agent

### ISSUE THREAD

**Issue by MrCSJ** [jaegertracing/jaeger#2014]
Is jaeger agent support to limit cpu?
I deploy agent on host，how to decrease the risk of jaeger-agent steal cpu or memory？

**Comment by yurishkuro** [comment]
Agent does not have any internal throttling. To protect the host you can limit how much resources are given to a container, and if the agent is running hotter/hungrier than those limits it will be dropping data (e.g. it won't be able to process all UDP packets).
