### ISSUE TITLE
Support url for sampling.strategies file

### ISSUE THREAD

**Issue by trondhindenes** [jaegertracing/jaeger#2015]
## Requirement - what kind of business use case are you trying to solve?
We'd like to allow dev teams to control sampling strategies. This currently is quite involved since jaeger relies on a filesystem-file. In kubernetes this typically means a configMap volume, which requires us to restart all jaeger collector pods when the file is updated. Quite cumbersome.

I'd like Jaeger to support a `sampling.strategies.url` option, where the sampling strategies file was downloaded from a url. The cache timeout could be a separate parameter, or it could use the cache headers from the dowload to determine how often to retrieve updates. 

Imho this would allow much easier changing of the sampling strategies, as we would be able to build a super-simple rest api to provide the json payload.

## Problem - what in Jaeger blocks you from solving the requirement?
strategies.json is implemented as a filesystem-file only

## Proposal - what do you suggest to solve the problem or improve the existing situation?
See requirement secion

**Comment by jpkrohling** [comment]
Looks interesting, do you want to give it a try?

**Comment by trondhindenes** [comment]
i'm not a go dev unfortunately, so implementing this is a bit out of reach for me atm.

**Comment by goku321** [comment]
Would like to try my hands on this.

**Comment by jpkrohling** [comment]
Go for it!
