### ISSUE TITLE
Jaeger all-in-one windows executable - Unable to send spans to Agent

### ISSUE THREAD

**Issue by sandeepopenstack** [jaegertracing/jaeger#2016]
## Requirement - what kind of business use case are you trying to solve?

Run Jaeger all-in-one executable on Windows VM, and be able to receive, store, and visualize spans/traces

## Problem - what in Jaeger blocks you from solving the requirement?

I have run the all-in-one windows executable, and after sending spans to Jaeger, Jaeger UI not able to show traces/spans. Not sure about how to use flags to configure all-in-one deployment on windows, as Agent port 6831 is not in LISTENING mode. Have attached additional logs below

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Need guidance on how to configure parameters for all-in-one executable. Please see logs below after starting jaeger-all-in-one.exe (latest version). You will see that 6831 port is NOT in listening mode, and I want to send spans agent. 

C:\LoggingProject0ATT\jaeger-1.16.0-windows-amd64>jaeger-all-in-one.exe
2020/01/14 17:19:22 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
{"level":"info","ts":1579043962.1301465,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1579043962.1321075,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1579043962.1321075,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1579043962.1330373,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"info","ts":1579043962.1711636,"caller":"memory/factory.go:56","msg":"Memory storage initialized","configuration":{"MaxTraces":0}}
{"level":"info","ts":1579043962.1711636,"caller":"static/strategy_store.go:79","msg":"No sampling strategies provided, using defaults"}
{"level":"info","ts":1579043962.178923,"caller":"all-in-one/main.go:246","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"warn","ts":1579043962.178923,"caller":"all-in-one/main.go:247","msg":"TChannel has been deprecated and will be removed in a future release"}
{"level":"info","ts":1579043962.1799552,"caller":"grpcserver/grpc_server.go:64","msg":"Starting jaeger-collector gRPC server","grpc-port":"14250"}
{"level":"info","ts":1579043962.1799552,"caller":"all-in-one/main.go:265","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1579043962.1799552,"caller":"grpc/builder.go:65","msg":"Agent requested insecure grpc connection to collector(s)"}
{"level":"info","ts":1579043962.1819007,"caller":"all-in-one/main.go:203","msg":"Starting agent"}
{"level":"info","ts":1579043962.1828785,"caller":"querysvc/query_service.go:133","msg":"Archive storage not created","reason":"archive storage not supported"}
{"level":"info","ts":1579043962.1828785,"caller":"all-in-one/main.go:347","msg":"Archive storage not initialized"}
{"level":"info","ts":1579043962.1828785,"caller":"app/agent.go:69","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1579043962.1838763,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1579043962.1838763,"caller":"app/server.go:112","msg":"Starting HTTP server","port":16686}
{"level":"info","ts":1579043962.1838763,"caller":"app/server.go:125","msg":"Starting GRPC server","port":16686}
{"level":"info","ts":1579043962.1838763,"caller":"app/server.go:135","msg":"Starting CMUX server","port":16686}

When i ran, netstat -a, I got the below, indicating that port 6831 is not in LISTENING mode.

[Log1.txt](https://github.com/jaegertracing/jaeger/files/4063039/Log1.txt)

 TCP    0.0.0.0:5778           DESKTOP-KCSFGDA:0      LISTENING
 [jaeger-all-in-one.exe]
  TCP    0.0.0.0:7680           DESKTOP-KCSFGDA:0      LISTENING
 Can not obtain ownership information
  TCP    0.0.0.0:14250          DESKTOP-KCSFGDA:0      LISTENING
 [jaeger-all-in-one.exe]
  TCP    0.0.0.0:14267          DESKTOP-KCSFGDA:0      LISTENING
 [jaeger-all-in-one.exe]
  TCP    0.0.0.0:14268          DESKTOP-KCSFGDA:0      LISTENING
 [jaeger-all-in-one.exe]
  TCP    0.0.0.0:14269          DESKTOP-KCSFGDA:0      LISTENING
 [jaeger-all-in-one.exe]
  TCP    0.0.0.0:16686          DESKTOP-KCSFGDA:0      LISTENING
 [jaeger-all-in-one.exe]
...
 **[jaeger-all-in-one.exe]
  UDP    0.0.0.0:6831           *:***
 [jaeger-all-in-one.exe]
  UDP    0.0.0.0:6832           *:*
 [jaeger-all-in-one.exe]
  UDP    0.0.0.0:50186          *:*

**When I ran using flags to specify the Agent port, I got the error below indicating **"Unable to initialize Jaeger Agent","error":"address 6831: missing port in address",**

**C:\LoggingProject0ATT\jaeger-1.16.0-windows-amd64>jaeger-all-in-one.exe --processor.jaeger-compact.server-host-port 6831**
2020/01/14 22:15:27 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
{"level":"info","ts":1579061727.1782403,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1579061727.1801615,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1579061727.1801615,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1579061727.181181,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"info","ts":1579061727.1899707,"caller":"memory/factory.go:56","msg":"Memory storage initialized","configuration":{"MaxTraces":0}}
{"level":"info","ts":1579061727.1899707,"caller":"static/strategy_store.go:79","msg":"No sampling strategies provided, using defaults"}
{"level":"info","ts":1579061727.197838,"caller":"all-in-one/main.go:246","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"warn","ts":1579061727.1988351,"caller":"all-in-one/main.go:247","msg":"TChannel has been deprecated and will be removed in a future release"}
{"level":"info","ts":1579061727.1988351,"caller":"grpcserver/grpc_server.go:64","msg":"Starting jaeger-collector gRPC server","grpc-port":"14250"}
{"level":"info","ts":1579061727.1997287,"caller":"all-in-one/main.go:265","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1579061727.1997287,"caller":"grpc/builder.go:65","msg":"Agent requested insecure grpc connection to collector(s)"}
**{"level":"fatal","ts":1579061727.2007077,"caller":"all-in-one/main.go:200","msg":"Unable to initialize Jaeger Agent","error":"address 6831: missing port in address","stacktrace":"main.startAgent\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:200\nmain.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:135\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:698\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:783\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:736\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:175\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/proc.go:203"}**

**Comment by yurishkuro** [comment]
try with a colon:

`--processor.jaeger-compact.server-host-port :6831`

**Comment by sandeepopenstack** [comment]
Thank you Sir for your quick response. It did work; however, when I run netstat -a -b command, I still do not see port 6831 in LISTENING mode? Is this expected behavior?

Is it correct to assume that all-in-one windows executable already has configured 6831 by default? 

Where can I see all parameters that are configured by default in the all-in-one executable? Any configuration file in the all-in-one code?

Thank you again and very much appreciate your wonderful work!

**Comment by yurishkuro** [comment]
When you run a binary with `help` command it prints all config options with the defaults.

It is  possible that your netstat does not show UDP ports as "listened to".

Note tat all-in-one has self-tracing enabled, if you refresh the search  screen a few times the query-service  should be detected.

**Comment by sandeepopenstack** [comment]
Hi - You can close this, as I got it working...Thank you!

**Comment by DikshithAC** [comment]
Jaeger - windows configuration doesn't work - all in one solution

**Comment by igplanet** [comment]
> Hi - You can close this, as I got it working...Thank you!

How did you get it working please? @sandeepopenstack
