### ISSUE TITLE
Agent use slb for collectors setting

### ISSUE THREAD

**Issue by MrCSJ** [jaegertracing/jaeger#2017]
-- set paramter for reporter.tchannel.host-port
Does agent support set the collector list with SLB(ServerLoadBalancer), I use a slb instead two collectors address, actually collector-1 and collector-2 has a different flow to receive spans?
the version i use is 14.0

**Comment by MrCSJ** [comment]
i didn't use service discovery，i want to user a address instead of list of address to set for agent，is there any advise?

**Comment by jpkrohling** [comment]
Not quite sure what you mean, but you should certainly be able to place a load balancer between your agent and your collectors, as long as your load balancer won't kill the long-lived tchannel connections. Same for gRPC.
