### ISSUE TITLE
Switch to go mod

### ISSUE THREAD

**Issue by kylesliu** [jaegertracing/jaeger#2019]
## Requirement - what kind of business use case are you trying to solve?

Hello everyone, I'm a gopher from China. When using jaeger, I found that there is no go mod . go mod can provide great help to developers in China.

**Comment by ChadiEM** [comment]
@kylesliu is probably talking about [Go Modules](https://github.com/golang/go/wiki/Modules).

**Comment by pavolloffay** [comment]
@yurishkuro are we able to use go mod. I found this PR from the last year https://github.com/jaegertracing/jaeger/pull/1546

**Comment by yurishkuro** [comment]
We can switch this repo to `go mod`, but we will lose the sync of transitive dependencies from jaeger-client-go and jaeger-lib, which are not using `go mod`. Those two are harder to switch because they are not on v1, so would require breaking changes.

**Comment by pavolloffay** [comment]
Do we know which transitive deps of `jaeger-lib` and `jaeger-client-go` are not using go modules?

**Comment by yurishkuro** [comment]
I don't think anyone did such analysis. But it's not what I meant, I meant dependencies like `jaeger -> jaeger-lib -> X`. If `jaeger` is on `go mod`, but `jaeger-lib` is not, then `X` will only be synced at the time of migrating to `go mod`, and after that we won't see updates to X even if `jaeger-lib` bumps it.

**Comment by pavolloffay** [comment]
> We can switch this repo to go mod, but we will lose the sync of transitive dependencies from jaeger-client-go and jaeger-lib, which are not using go mod. Those two are harder to switch because they are not on v1, so would require breaking changes.

Why would it be a breaking change? Does switching of dependency management mean breaking change?

**Comment by yurishkuro** [comment]
Go mod requires /vN directory for libs that are v2+. Making such change to source code makes the libs incompatible with existing consumers that import from root and use other dep mgrs. 

I was originally thinking we could combine switch to go mod in the libs with a move from uber/ to jaegertracing/ path and going back to v1, but that won’t work either because we already have v1 tags in those repos.
