### ISSUE TITLE
Grace stop agent

### ISSUE THREAD

**Issue by MrCSJ** [jaegertracing/jaeger#2021]
I execute jaeger-agent on CentOS (use command like this : nohup ./jaeger-agent --reporter.tchannel.host-port=ip:14267 --log-level=debug >jaeger-agent.log 2>&1 &
 )，what should i do to stop jaeger-agent graceful，current i user kill -9 pid。But i doubt this can discard some spans。By the way，the same question for collector、query and ingester

**Comment by jpkrohling** [comment]
You might want to take a look at this for a better way to start/manage the processes:

https://medium.com/jaegertracing/running-jaeger-agent-on-bare-metal-d1fc47d31fab

Right now, I don't think the agent can be stopped gracefully, but sending a SIGTERM is the appropriate way to stop the process. We do plan to handle graceful shutdown in the future. See #295 for more info on that.
