### ISSUE TITLE
How to control the balance above lists of collectors for agent

### ISSUE THREAD

**Issue by MrCSJ** [jaegertracing/jaeger#2026]
I have three collectors to receive spans from agent。I use agent with command like this “nohup ./jaeger-agent --reporter.tchannel.host-port=ip1:14267,ip2:14267,ip3:14267 --log-level=debug >jaeger-agent.log 2>&1 &”。But i found the flow of collectors is not average。So how to loadbalance for this situation。

**Comment by jpkrohling** [comment]
Use the gRPC reporter instead, which provides a client-side load balancing.

https://www.jaegertracing.io/docs/1.13/deployment/#discovery-system-integration
