### ISSUE TITLE
Expose Samara Kafka producer/consumer configurations to command line.

### ISSUE THREAD

**Issue by apm-opentt** [jaegertracing/jaeger#2037]
## Requirement - what kind of business use case are you trying to solve?

We are using Jaeger with Ingester.  On Collector, we are setting SPAN_STORAGE_TYPE=kafka.  We would like to tune Kafka configurations for performance.  The default Kafka Samara config is resulting in over 150% CPU usage on Kafka broker for just 40k spans per minute.

## Problem - what in Jaeger blocks you from solving the requirement?
Jaeger provided these producer settings
```
      --kafka.producer.authentication string          Authentication type used to authenticate with kafka cluster. e.g. none, kerberos, tls (default "none")
      --kafka.producer.brokers string                 The comma-separated list of kafka brokers. i.e. '127.0.0.1:9092,0.0.0:1234' (default "127.0.0.1:9092")
      --kafka.producer.compression string             (experimental) Type of compression (none, gzip, snappy, lz4, zstd) to use on messages (default "none")
      --kafka.producer.compression-level int          (experimental) compression level to use on messages. gzip = 1-9 (default = 6), snappy = none, lz4 = 1-17 (default = 9), zstd = -131072 - 22 (default = 3)
      --kafka.producer.encoding string                Encoding of spans ("json" or "protobuf") sent to kafka. (default "protobuf")
      --kafka.producer.kerberos.config-file string    Path to Kerberos configuration. i.e /etc/krb5.conf (default "/etc/krb5.conf")
      --kafka.producer.kerberos.keytab-file string    Path to keytab file. i.e /etc/security/kafka.keytab (default "/etc/security/kafka.keytab")
      --kafka.producer.kerberos.password string       The Kerberos password used for authenticate with KDC
      --kafka.producer.kerberos.realm string          Kerberos realm
      --kafka.producer.kerberos.service-name string   Kerberos service name (default "kafka")
      --kafka.producer.kerberos.use-keytab            Use of keytab instead of password, if this is true, keytab file will be used instead of password
      --kafka.producer.kerberos.username string       The Kerberos username used for authenticate with KDC
      --kafka.producer.protocol-version string        Kafka protocol version - must be supported by kafka server
      --kafka.producer.required-acks string           (experimental) Required kafka broker acknowledgement. i.e. noack, local, all (default "local")
      --kafka.producer.tls.ca string                  Path to the TLS CA for the Kafka connection
      --kafka.producer.tls.cert string                Path to the TLS Certificate for the Kafka connection
      --kafka.producer.tls.key string                 Path to the TLS Key for the Kafka connection
      --kafka.producer.topic string    
```
Setting `--kafka.producer.required-acks` to `noack` helps a little, reducing CPU usage on Kafka broker by 8%.  We experimented setting github.com/jaegertracing/jaeger/pkg/kafka/producer/config.go with the following parameters.  It resulted in 10 times improvement in Kafka broker CPU usage.
```
        saramaConfig.Producer.Flush.Bytes = 128000
        saramaConfig.Producer.Flush.Frequency = time.Duration(1 * time.Second)
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?
At a minimum, Jaeger should expose the above 2 settings to the command line.  Ideally Jaeger should expose all producer/consumer configurations.
Given that each Kafka client has it's own naming for configurations.  I would suggest Jaeger use Kafka's official parameter names for it's client.  For example, `saramaConfig.Producer.Flush.Bytes` should be exposed as `batch.size` and `saramaConfig.Producer.Flush.Frequency` should be exposed as `linger.ms`

**Comment by yurishkuro** [comment]
Sounds reasonable. Would you like to create a pull request?

I would also be interested to hear what performance improvements you will realize by using these new settings. Perhaps they should go into documentation / guidelines for the collector.

**Comment by apm-opentt** [comment]
I can create a pull request but I need to get approval from my management first.
