### ISSUE TITLE
Clarification in docs

### ISSUE THREAD

**Issue by nadilas** [jaegertracing/jaeger#2038]
Hi everyone,

This line cost me 1 day 😄  ... 

https://github.com/jaegertracing/jaeger/blob/4b58b94ed93c994f65882e256251943cc08b99a2/pkg/es/config/config.go#L294

Maybe you could update to docs to be more specific in saying `--es.tls` ignores `--es.tls.ca`? Or is it just me who got this wrong? 😊

**Comment by yurishkuro** [comment]
It should not ignore CA, what makes you think it does?

Meanwhile, this code will change with #1838

**Comment by nadilas** [comment]
@yurishkuro well, when setting —es.tls I don’t see this line in that if path of the code:
https://github.com/jaegertracing/jaeger/blob/4b58b94ed93c994f65882e256251943cc08b99a2/pkg/es/config/config.go#L308

But that’s only after I always had a “no such file or directory” - yes without a file oath - error on startup. Removing the —es.tls flag, leaving behind the —es.tls.ca flag fixed the issue. So I checked the code and then came to the conclusion above. Although I didn’t check c.TLS.create itself.

**Comment by jpkrohling** [comment]
The code does look strange and I think it could have a few comments, but when the CA path is set, both code branches will attempt to read the file.

https://github.com/jaegertracing/jaeger/blob/4b58b94ed93c994f65882e256251943cc08b99a2/pkg/es/config/config.go#L308-L315

and

https://github.com/jaegertracing/jaeger/blob/4b58b94ed93c994f65882e256251943cc08b99a2/pkg/es/config/config.go#L344-L360

**Comment by nadilas** [comment]
@jpkrohling got it. It does make sense, although the `createTLSConfig` is actually a `createTLSConfigWithClientCertificate` implementation.

https://github.com/jaegertracing/jaeger/blob/4b58b94ed93c994f65882e256251943cc08b99a2/pkg/es/config/config.go#L308-L315

Then my issue was definitely not having `CertPath` and `KeyPath` set as I was using password authentication. Sorry for the misinterpretation.
