### ISSUE TITLE
hotrod docker image and configurable jaeger agent host and port

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger#204]
* Currently, there is no docker image to run [HotROD](https://github.com/uber/jaeger/tree/master/examples/hotrod) example. It will be nice to have separate Docker image for HotROD
* HotROD works with the agent running on `127.0.0.1`, Will be nice to have configurable agent port and IP.

**Comment by pavelnikolov** [comment]
This would be really nice. In the mean time, you can use this image https://hub.docker.com/r/mikelorant/jaeger-hotrod/ it accepts `AGENT_HOST` and `AGENT_PORT` environment variables.

**Comment by yurishkuro** [comment]
@pavelnikolov would you like to submit a PR to add a hotrod image to the travis step that builds the other images?

**Comment by pavelnikolov** [comment]
I was about to submit a PR for that, but then I noticed the hotrod code needed some changes as @jkandasa has pointed out above. I didn't have time to do it and @mikelorant created the image I liked above ([repo here](https://github.com/mikelorant/jaeger-hotrod)). Although it works, it's a little hacky workaround and needs to be done properly.
I'll try to submit a PR soon and fix the hotrod code. Then creating a proper image would be a trivial task.

**Comment by yurishkuro** [comment]
I assume you mean this issue in the client: https://github.com/jaegertracing/jaeger-client-go/issues/197

**Comment by pavelnikolov** [comment]
I think the hotrod (from memory) is hardcoded to send tracing only to localhost. This is the reason Mike has forwarded traffic from port `6831/udp` to external host and port in his Docker image, suing `socat`:

```
socat UDP4-RECVFROM:6831,fork UDP4-SENDTO:${AGENT_HOST}:${AGENT_PORT} &
```
The fix is to allow hotrod to be configurable and to send data to custom host and port.

**Comment by pavolloffay** [comment]
@pavelnikolov #603 added a flag to configure agent address

**Comment by pavelnikolov** [comment]
This will save me some time. I'll try to create Docker file using it and will send a PR.

**Comment by pavolloffay** [comment]
Partially implemented in https://github.com/jaegertracing/jaeger/pull/694
