### ISSUE TITLE
Generated gRPC server for storage plugin is fail/ unable to build 

### ISSUE THREAD

**Issue by Sentorio** [jaegertracing/jaeger#2045]
## Requirement -
I've generate a gRPC server in go lang using storage.proto file located in `plugin/storage/grpc/proto/`. Now I'am unable to build the binary for that server. I receive the following log when I try to build the binary with `go build -o ~/out_binary proto-gen/storage_v1/storage.pb.go` command.

```
# command-line-arguments
proto-gen/storage_v1/storage.pb.go:1403:39: m.Dependencies[iNdEx].MarshalToSizedBuffer undefined (type model.DependencyLink has no field or method MarshalToSizedBuffer)
proto-gen/storage_v1/storage.pb.go:1443:23: m.Span.MarshalToSizedBuffer undefined (type *model.Span has no field or method MarshalToSizedBuffer)
proto-gen/storage_v1/storage.pb.go:1878:32: m.Spans[iNdEx].MarshalToSizedBuffer undefined (type model.Span has no field or method MarshalToSizedBuffer)
```

I'am using go 1.13.5.
Can you please have a look on this?

**Comment by yurishkuro** [comment]
Sound a bit like a mismatch between runtime and generator versions.

I suggest you take a look at influxdb plugin repository, how they build it.
