### ISSUE TITLE
Single Jaeger UI for multiple jaeger environment

### ISSUE THREAD

**Issue by prana24** [jaegertracing/jaeger#2051]
## Requirement - what kind of business use case are you trying to solve?
We are having multiple  jaegr  environment as of now and it is going to increase  with cloud coming into as new environment , we will have even more environment.  So we want to provide same URL to everyone so that  user can get single  UI for all the environment. Can we achieve this ?

**Comment by jpkrohling** [comment]
At the moment, each instance of the Jaeger Query can only talk to a single Jaeger Collector.
