### ISSUE TITLE
Restrict clock skew adjustment to a certain max delta

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2053]
Similar to #961, perhaps we should impose a limit on the skew adjustment, e.g. no more than 1s. If the calculated delta exceeds that limit, add a span warning saying that adjustment was not done, and include the proposed delta in the message.

**Comment by joe-elliott** [comment]
@yurishkuro I'd be glad to look at this:

Add a param to `jaeger-query` that takes a duration: `--query.max-clock-skew-adjust'
Default to unset which would maintain current behavior?

**Comment by yurishkuro** [comment]
I would default to something like 1sec, and use zero as "turn it off" equivalent.

**Comment by joe-elliott** [comment]
Sounds good.  I'll submit a PR in the next couple days.
