### ISSUE TITLE
Jaeger Span is not marked as an error when exception is handled by ControllerAdvice

### ISSUE THREAD

**Issue by dawidskiba** [jaegertracing/jaeger#2058]
## Requirement - what kind of business use case are you trying to solve?

I'm using io.opentracing.contrib:opentracing-spring-jaeger-web-starter:2.0.3 in my project.
I've spotted that exceptions that are caught by ExceptionHandlers in ControllerAdvice make Jaeger spans look like there was no error at all.

## Problem - what in Jaeger blocks you from solving the requirement?

Despite that exception is caught and transformed into ResponseEntity with custom error object in ControllerAdvice, Jaeger span should be processed (marked) as an error.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The workaround that I applied is that I injected WebFluxSpanDecorator.StandardTags into my ControllerAdvice and decorate spans manually.

## Any open questions to address

Is this behavior made by design?
If yes, is there a better way to handle this situation than described in my workaround proposal?

**Comment by pavolloffay** [comment]
Please open a ticket in the instrumentation repository. This is not Jaeger issue.
