### ISSUE TITLE
Replace the use of pkg/errors with native error wrapping

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2061]
currently we're using `errors.Wrap`. Since Go 1.13 we can instead use the stdlib 
```go
if err != nil {
    return fmt.Errorf("bad thing happend: %w", err)
}
```

**Comment by u5surf** [comment]
@yurishkuro 
I'll give you a resolve this issue, I experienced the making a resolution of same  error-wrapping issue (https://github.com/tektoncd/pipeline/pull/808) using `xerrors`. 
Of course, I know we can wrap with current `fmt` libraries as you referred.
