### ISSUE TITLE
Replace the use of FNV hash with maphash

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2062]
According to https://speakerdeck.com/campoy/the-state-of-go-2020?slide=31, the new hash is much faster.

**Comment by sandyleo26** [comment]
happy to tackle this as an entry to jaeger. Could i have some pointers to get me started? thank you.

**Comment by yurishkuro** [comment]
These are the examples of FNV hash usage
```
./plugin/storage/es/spanstore/service_operation.go:22:	"hash/fnv"
./plugin/storage/es/spanstore/service_operation.go:141:	h := fnv.New64a()
./storage/spanstore/downsampling_writer.go:19:	"hash/fnv"
./storage/spanstore/downsampling_writer.go:86:	// Currently fnv.Write() implementation doesn't throw any error so metric is not necessary here.
./storage/spanstore/downsampling_writer.go:109:				hash:   fnv.New64a(),
./model/process_test.go:20:	"hash/fnv"
./model/process_test.go:64:	h := fnv.New64a()
./model/hash.go:19:	"hash/fnv"
./model/hash.go:30:// HashCode calculates a FNV-1a hash code for a Hashable object.
./model/hash.go:32:	h := fnv.New64a()
./pkg/discovery/grpcresolver/grpc_resolver.go:19:	"hash/fnv"
./pkg/discovery/grpcresolver/grpc_resolver.go:127:	hasher := fnv.New32()
```

**Comment by sandyleo26** [comment]
hi @yurishkuro , i could be wrong but after a look at the implementation and documentation of `maphash` it seems the `maphash` is not deterministic. 

Take `model/hash.go` for example, i need to do something like
```golang
func HashCode(o Hashable) (uint64, error) {
        h := &maphash.Hash{}
	if err := o.Hash(h); err != nil {
		return 0, err
	}
	return h.Sum64(), nil
}

```

no field of `Hash` is exposed. the only way to set the seed is something like `SetSeed(maphash.MakeSeed())` which is random. This will cause some unit test to fail which expect same input having same [hash](https://github.com/sandyleo26/jaeger/blob/95331addaa0cccb628b363542c5064958e9a2ccc/model/span_test.go#L269 ) 

The documentation of `maphash` also hint hash will be [different](https://github.com/golang/go/blob/master/src/hash/maphash/maphash.go#L13-L14
) in different process. 

`fnv.New64a` on the other hand returns hasher with the same internal `offset64`

So my question is does maphash meet the requirements here?

**Comment by yurishkuro** [comment]
The godoc says

> The hash value of a given byte sequence is consistent within a single process, but will be different in different processes.

In some use cases it's ok, but we're using trace ID hash for downsampling, which needs to be stable across different instances of the service. I am puzzled why stdlib cannot expose a method of defining an explicit seed for maphash. In the current form it is not usable as a replacement.

**Comment by annanay25** [comment]
There is a method to explicitly define a seed - `hasher.SetSeed(s)` 

I've written a simple example here - https://gist.github.com/annanay25/fa5af5a2a985d9cd913fc25ed5bad6b7

But then the seed would have to be stored as part of some struct for uniform behaviour which is a little strange

**Comment by yurishkuro** [comment]
You can set the seed, but you cannot _create_ consistent seed across processes, because MakeSeed function is random.

**Comment by sandyleo26** [comment]
maybe we should close this issue for now?
