### ISSUE TITLE
sudden memory increase  in jaeger collector

### ISSUE THREAD

**Issue by prana24** [jaegertracing/jaeger#2065]
## Requirement - what kind of business use case are you trying to solve?

We have a jaeger 1.14  set up working since last 3-4 months without any issue which has two collector pod  , with provision of 4GB  memory in  Kubernetes cluster.  Average memory usage  by jaeger collector was around 1GB . Somedays back there was sudden spike in memory and increased till 4GB  for one collector and  another collector was around  1-2 GB.  There is no increase in corresponding traffic . Only  change i see is  there was a schedule maintenance  in kubernetes cluster  during that time  drain and delete some worker node from kubernetes cluster .    Is there anyway i can further check what is causing the memory hike ?

<img width="939" alt="Capture" src="https://user-images.githubusercontent.com/48326505/74152313-0bbc4e80-4bdc-11ea-9db8-a67e74f305d3.PNG">

**Comment by prana24** [comment]
Any pointer will be appreciated

**Comment by jpkrohling** [comment]
Are you also storing metrics from the `/metrics` endpoint? If so, check for the metrics around the queue sizes, as that's the only thing that should impact the memory consumption. It should get stable over time if you have enough throughput in the storage part, though.

**Comment by prana24** [comment]
<img width="953" alt="Capture" src="https://user-images.githubusercontent.com/48326505/74241121-5eb00780-4ca9-11ea-9578-e28260c20efc.PNG">
Attached is the  last 6 hours  collector queue size  and  and  colellector memory graphs  
<img width="955" alt="Capture" src="https://user-images.githubusercontent.com/48326505/74242067-3d501b00-4cab-11ea-8eb6-7d011201b497.PNG">  . Do not see that much queue size   or span drops

**Comment by jpkrohling** [comment]
With the given information, I can't figure out what might be happening. How are you getting the memory stats? Do they match with the metrics reported by the collector, like `go_memstats_alloc_bytes`, `go_memstats_alloc_bytes_total`, `go_memstats_heap_objects`, `process_resident_memory_bytes`, `process_virtual_memory_bytes`? 

Do you also see that for new instances? What happens if you scale the collector up to 4 pods?

**Comment by pavolloffay** [comment]
@prana24 what storage backed are you using?

**Comment by prana24** [comment]
@jpkrohling  ,   we get memory usage by using  cadvisor   `avg(container_memory_usage_bytes{container_label_io_kubernetes_container_name="jaeger-collector"}) by (pod)`    is the query  being used for the same. 
I have not used metrics mentioned by you , will add it ,   I think these are client ( agent ) specific metrics right ?  Does it also co-relate to collector  memory usage ?

**Comment by prana24** [comment]
@pavolloffay   we are using Elastic Search  for backend storage

**Comment by jpkrohling** [comment]
>  I think these are client ( agent ) specific metrics right ? Does it also co-relate to collector memory usage ?

They are all common to all components, so, they exist as well for the collector. Not sure there's a 100% correlation between them and what you see from cadvisor, but I would expect to also see a spike there.

**Comment by prana24** [comment]
@jpkrohling  I see your point , will share the findings with you as soon as i see something
