### ISSUE TITLE
Advantages of Jaeger over APMs (Dynatrace)

### ISSUE THREAD

**Issue by arpitjindal97** [jaegertracing/jaeger#2079]
I wanted to know what advantages user will get over Dynatrace using Jaeger.

[Here](https://stackoverflow.com/questions/59597548/advantage-of-opentracing-jaeger-over-apm-tracing-capabilities) is the relavant question asked in StackOverflow

**Comment by yurishkuro** [comment]
We're not in the business of doing comparative analysis with commercial products.
