### ISSUE TITLE
search.maxLimit not works in UI Release 1.17.0

### ISSUE THREAD

**Issue by satmurat** [jaegertracing/jaeger#2087]
I configure search.maxLimit to 2000 and ran jaegertracing/jaeger-query:1.17.0. But in search form input "Limit results" max value is 1500 yet. The UI feature search.maxLimit is included in 1.17.0?

```
{
  "dependencies": {
    "dagMaxNumServices": 200,
    "menuEnabled": true
  },
  "archiveEnabled": true,
  "tracking": {
    "gaID": "UA-000000-2",
    "trackErrors": true
  },
  "menu": [
    {
      "label": "About Jaeger1",
      "items": [
        {
          "label": "GitHub",
          "url": "https://github.com/jaegertracing/jaeger"
        },
        {
          "label": "Docs",
          "url": "http://jaeger.readthedocs.io/en/latest/"
        }
      ]
    }
  ],
  "search": {
    "maxLookback": {
      "label": "5 Days",
      "value": "5d"
    },
    "maxLimit": 2000
  },
  "linkPatterns": [{
    "type": "process",
    "key": "jaeger.version",
    "url": "https://github.com/jaegertracing/jaeger-client-java/releases/tag/#{jaeger.version}",
    "text": "Information about Jaeger release #{jaeger.version}"
  }]
}

**Comment by pavolloffay** [comment]
@rubenvp8510 is the new UI anyhow limiting the number of results? 

I think we haven't changed anything on the backed side.

**Comment by satmurat** [comment]
> I think we haven't changed anything on the backed side.

On UI this limit must be configurable (https://github.com/jaegertracing/jaeger-ui/commit/c6cb7adc059519b8a7737ec604db8a7ba16d31ad). But it doesn't work.

**Comment by rubenvp8510** [comment]
Hi

Yes, this was a feature introduced in 1.17, in the commit pointed by @satmurat, 

I tested this on master and it doesn't work for me, for me It simply does not impose any limit. I found the problem and will send a PR.

**Comment by yurishkuro** [comment]
move to UI ticket https://github.com/jaegertracing/jaeger-ui/issues/532
