### ISSUE TITLE
[tracking] Patch release 1.17.1

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2093]
* Kafka TLS (#2092)
* UI may not have been released correctly (https://github.com/jaegertracing/jaeger-ui/issues/532)

**Comment by jpkrohling** [comment]
Possibly #2094 too?

**Comment by pavolloffay** [comment]
Do we want to release from release branch or master? Since the release we have migrated go modules.

**Comment by yurishkuro** [comment]
I prefer to release from master. Go modules is not a breaking change.

**Comment by pavolloffay** [comment]
In master there are couple of breaking changes. We will have to relase from release branch. I have created `release-1.17` after migration to go modules and proto generation refactoring by @annanay25. I have also backported the TLS fix. 

https://github.com/jaegertracing/jaeger/commits/release-1.17

Now the UI fix has to be merged and UI released and updated here.

**Comment by objectiser** [comment]
@yurishkuro Could we also get https://github.com/jaegertracing/jaeger-ui/pull/542 included in the UI release?

**Comment by pavolloffay** [comment]
All blocking PRs have been merged. We can proceed with the release. We need a patch release of the UI (1.7.1) and bump it here.

**Comment by pavolloffay** [comment]
Release UI https://github.com/jaegertracing/jaeger-ui/pull/543

**Comment by pavolloffay** [comment]
We should agree and document when the changelog should be updated. I don't find it very useful to update it for patch releases. It adds unnecessary overhead.

**Comment by objectiser** [comment]
I think the fixed bugs need to be documented atleast on the GH release page.

**Comment by yurishkuro** [comment]
I don't think we should diverge GH releases and the changelog. What's the downside of adding a patch release to the changelog?

**Comment by pavolloffay** [comment]
Release job https://travis-ci.org/github/jaegertracing/jaeger/builds/661867156?utm_medium=notification&utm_source=github_status
