### ISSUE TITLE
Why is it called jaeger?

### ISSUE THREAD

**Issue by Lovnx** [jaegertracing/jaeger#2103]

**Comment by pavolloffay** [comment]
Some background for the name can be found here https://eng.uber.com/distributed-tracing/. @yurishkuro can provide you more details.

I am closing this as it is a question. Please use our gitter channel for questions.

**Comment by saikrishnasaski** [comment]
I think @yurishkuro is fan of AOT.

**Comment by yurishkuro** [comment]
I am not.
