### ISSUE TITLE
Remove tchannel reporter from agent

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#2105]
Remove tchannel reporter from agent. 

* agent by default uses `grpc` reporter 
* `tchannel` reporter was deprecated in 1.16 https://github.com/jaegertracing/jaeger/pull/1975.

TODO: 
- [ ] changelog
- [ ] docs
- [ ] remove generated classes

**Comment by pavolloffay** [comment]
This might also close https://github.com/jaegertracing/jaeger/issues/1193 and #983

**Comment by eundoosong** [comment]
If it's ok, I'd like to give it a shot

**Comment by pavolloffay** [comment]
I have already started working on this one.

**Comment by pavolloffay** [comment]
@yurishkuro any concerns from your side?

**Comment by yurishkuro** [comment]
Yes, we’re still using it.

**Comment by pavolloffay** [comment]
Are there any plans to migrate to gRPC inside Uber?

**Comment by pavolloffay** [comment]
Tchannel (14267) is used also to for:
* send span data from agent to collector
* send sampling configuration from collector to agent
* send baggage restriction from collector to agent - however this hasn't been fully open-sourced https://github.com/jaegertracing/jaeger/issues/373

For sampling strategies we have implemented gRPC pipe, but not for baggage restrictions. 

Also, the tchannel receiver (14267) is also implemented in the OpenTelemetry collector.

**Comment by objectiser** [comment]
> Also, the tchannel receiver (14267) is also implemented in the OpenTelemetry collector.

This should be removed soon: https://github.com/open-telemetry/opentelemetry-collector/issues/267

**Comment by yurishkuro** [comment]
I don't know how "doable" this is, but if we could refactor all tchannel code into a complete separate location, then we could copy all of it into our internal repo, and then delete from master. My main concern is that it might be complicated to rip it out from Agent's builder.

NB: yes, we do plan to migrate to gRPC internally, but the work hasn't been prioritize yet, there are some dependencies on the load balancing behavior. We can probably commit to have it done in Q2 (cc @vprithvi )

**Comment by pavolloffay** [comment]
I was able to move all tchannel to a single top level package and then use it in the current build https://github.com/jaegertracing/jaeger/pull/2112.

We could merge that and then in a second PR remove the tchannel from our components.
