### ISSUE TITLE
Remove deprecated kafka tls.enabled flags

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#2111]
Kafka TLS is configured by 
```
--kafka.consumer.authentication string          Authentication type used to authenticate with kafka cluster. e.g. none, kerberos, tls (default "none")
```

Release 1.17.0 (PR https://github.com/jaegertracing/jaeger/pull/1838) refactored Kafka TLS configuration and by mistake added flags `tls.enabled=bool`. Patch release 1.17.1 deprecated these flags. 

As there is duplicity between `--kafka.consumer.authentication` and `--kafka.consumer.tls.enabled` the second flag should be removed.

**Comment by jpkrohling** [comment]
Note that it's not both ways:

- `authentication=none` + `tls.enabled=true` is a valid scenario (ie, server provides cert, client does not)
- `authentication=tls` + `tls.enabled=false` is not (ie, both sides have to provide a cert)

**Comment by pavolloffay** [comment]
The whole motivation is to remove the duplicity between these two flags. TLS will be used only if `authentication=tls` is specified.

**Comment by jpkrohling** [comment]
Will people still be able to use auth=none with TLS between client and server?

**Comment by pavolloffay** [comment]
I don't think so, flag `.authentication=` is the only way to find out whether TLS should be enabled or not.

**Comment by jpkrohling** [comment]
> whether TLS should be enabled or not.

I think this is the root of the confusion: TLS can exist without TLS Authentication. Independent of how the current PRs move, we should aim to eventually support TLS between client and server independent of the authentication mechanism.

**Comment by yurishkuro** [comment]
then perhaps the flag should remain, but not be required if auth=tls is also already selected?

**Comment by jpkrohling** [comment]
> then perhaps the flag should remain, but not be required if auth=tls is also already selected?

The question then is what to do when `enabled=false` and `auth=tls` is used. Should `enabled` be made `true` despite the explicit `false`? Should the process break with an error?

**Comment by yurishkuro** [comment]
I think `enabled` should be silently set to `true` in that case. Fortunately, `false` is the default value which is not possible to set via command line (`--kafka.consumer.tls.enabled` is a no-arg switch), so `enabled=false` and `auth=tls` is never an explicit user's choice, just the default.

**Comment by pavolloffay** [comment]
Good point @jpkrohling, I haven't thought about this. It's a valid use case, however nobody it so far requested. It's better to keep the tls enabled flag just in case it will be implemented later.

The PR https://github.com/jaegertracing/jaeger/pull/2107 is updated and it reflects the discussion in this thread.

**Comment by pavolloffay** [comment]
I am closing this. The kafka `tls.enabled` will not be removed.
