### ISSUE TITLE
Tracking and removing deprecated CLI flags

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2113]
We've accumulated quite a few deprecated flags over time. We should start removing them. However, we need to define a backwards compatibility policy. I propose the following:
  * if a flag is deprecated in release N, it can be removed in release N+2
  * when adding a `(deprecated)` prefix to the flags, we should also add an indication of when it will b removed. Given the above rule, we could set a 3 months time interval. So the deprecation message should specify the date, e.g. `(deprecated, will be removed after 2020-03-15 or in release v1.19.0, whichever is later)`.
  * at the top of the file where the flag name is defined, add a constant and a comment, e.g.
```go
// TODO deprecated flag to be removed
healthCheckHTTPPortWarning = "(deprecated, will be removed after 2020-03-15 or in release v1.19.0, whichever is later)"
```
  * use that constant as the prefix to the help text, e.g.
```go
flagSet.Int(healthCheckHTTPPort, 0, healthCheckHTTPPortWarning+" see --"+adminHTTPHostPort)
```
  * when reading the flag into config, log a warning with the same warning
  * take care of deprecated flags in `initFromViper` functions, do not pass them to business functions

**Comment by yurishkuro** [comment]
We can also book tickets for the respective milestone for each deprecated flag, so that we don't forget to remove them in a timely manner.

**Comment by pavolloffay** [comment]
It sounds reasonable. Maybe instead of providing users with a date, it would be better to put there release version.

**Comment by jpkrohling** [comment]
> if a flag is deprecated in release N, it can be removed in release N+2

+1

> when adding a (deprecated) prefix to the flags, we should also add an indication of when it will b removed. Given the above rule, we could set a 3 months time interval. So the deprecation message should specify the date, e.g. (deprecated, will be removed after 2020-03-15 or in release v1.19.0, whichever is later).

I'm afraid this will make the help command too verbose, which impacts the readability for the non-deprecated flags as well. Apart from that, I have nothing against it.

One further action we could be taking is to log a message whenever a deprecated flag is being used, increasing the severity for every release:

1.17.0 - `--some-flag` becomes deprecated, log at `INFO` level
1.18.0 - `--some-flag` is still being used, log at `WARN` level
1.19.0 - `--some-flag` removed from code, log at `ERROR` level
1.20.0 - no more traces of `--some-flag` in the code

**Comment by yurishkuro** [comment]
> Maybe instead of providing users with a date, it would be better to put there release version.

I am suggesting both. It might happen that we do two releases in short succession. As an operator I would prefer a fixed length grace period

> I'm afraid this will make the help command too verbose, which impacts the readability for the non-deprecated flags as well.

I a not sure it's that bad, the help is formatted to easily see where next flag description begins, so if a text is longer for some, the eyes just skip to the next one. Plus, it's more incentive for us to remove them in a timely manner.

> 1.20.0 - no more traces of --some-flag in the code

That feels too much maintenance to me. I think a WARN level in 1.17 (first deprecated) and 1.18 is enough.

**Comment by yurishkuro** [comment]
I updated the ticket per discussion. If no objections, I want to add it to the contributing guidelines.

**Comment by annanay25** [comment]
The trick is to now track these flag deprecations on our end (if we pick time as a factor). 😃

**Comment by yurishkuro** [comment]
We have a script that dumps all combinations of flags from all binaries into a single file, which we can grep for `deprecated` and filter by dates. So before a release we can go through that and clean-up flags which have passed their TTL.
