### ISSUE TITLE
Bind to IP

### ISSUE THREAD

**Issue by galileo-pkm** [jaegertracing/jaeger#2120]
## Requirement - what kind of business use case are you trying to solve?
Good security practice

## Problem - what in Jaeger blocks you from solving the requirement?
Feature not available 

AFAIK there is no way to bind various jaeger services to a single address. 
There are command line switches that bind certain services to host:port combination but not available for all (UI, collector ...)

## Proposal - what do you suggest to solve the problem or improve the existing situation?
--bind-to-ip [coma list of IP addresses ] would be useful, especially for jaeger-all-in-one.

**Comment by yurishkuro** [comment]
We have an open ticket #1447 to support host:port CLI flags instead of just ports. What would `--bind-to-ip` provide in addition to that ticket?

**Comment by galileo-pkm** [comment]
I failed to find that issue, I should have posted this as a comment on that one. 
--bind-to-ip would set the listening address for all services without specifying the port (keep the default).

**Comment by yurishkuro** [comment]
But I think individual `host-port` flags are more flexible, e.g. you can set collector's inbound port on a public IP, while its admin port on internal IP only.

Feel free to comment on #1447.
