### ISSUE TITLE
jaeger collector not working with kerberos based kafka

### ISSUE THREAD

**Issue by gafoorraja** [jaegertracing/jaeger#2122]
## Requirement - what kind of business use case are you trying to solve?

 We are trying to use kafka streaming with jaeger for our heavy work loads specially tracing 

## Problem - what in Jaeger blocks you from solving the requirement?

Kerberos based authentication is not working as expected, gone thoroughly to all the packages involved while making this connection. We are able to found the root cause message but not able solve it.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
1\ It will be helpful if there is one test case with collector & ingester with kafka using kerberos keytab authentication. looked at the sarama config but at times confusing.

2\ Authentication is working with ssl based kafka, issue with only sasl_ssl - one working example config with all kerberos properties will clear some doubts.

3\ Are there any pre-requisites that need to be considered before using SASL_SSL auth like version compatibility etc.. if so any doc with details will be helpful
## Any open questions to address

Config that we are using

collector:
zipkin:
  http-port: 9411
log-level: debug
kafka:
  producer:
    authentication: kerberos
    topic: "JAEGER_TEST_TOPIC"
    brokers: '$KAFKA_BROKER:$PORT'
    kerberos:
      service-name: kafka
      config-file: "/etc/krb5.conf"
      keytab-file: "/etc/security/dev.keytab"
      realm: "dev-org.net"
      username: 'test@dev-org.net'  ##principal name
      use-keytab: "true"

Error at this stage: 
{"level":"fatal","ts":1583319166.0871506,"caller":"command-line-arguments/main.go:70","**msg":"Failed to init storage factory","error":"kafka: client has run out of available broker**n.main.func1\n\tcommand-line-arguments/main.go:70\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\tgithub.com/jaegertracing/jaeger/vendor/githuaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:783\ngithub.com/jaegertracing/jaeger/vendor/gitracing/jaeger/vendor/github.com/spf13/cobra/command.go:736\nmain.main\n\tcommand-line-arguments/main.go:117\nruntime.main\n\truntime/proc.go:203"}

To find more followed trace and finally at the end found error message at SendToKDC & SendTCP at  **vendor/gopkg.in/jcmturner/gokrb5.v7/client/network.go**
**Error: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database**

Validations:
1- Same principal & keytab is working with other programs under same network.
2- From that pod able to communicate to kafka brokers
3- able to create kerberos cache in the same pod

are there any kind of more checks & tests can be done to solve this issue ? please let me know.

**Comment by malkov82** [comment]
Is there any updates? I'm having the same issue..

**Comment by rubenvp8510** [comment]
Hi

This could be due an issue with the underlying library, sarama which uses a pure golang kerberos implementation 

Unfortunately not all encryption types used by Kerberos are supported, you can find more info about this issue here: https://github.com/Shopify/sarama/issues/1429

Could you share your kerberos configurations (krb5.conf) ? Just to confirm that this is not another issue.

**Comment by gafoorraja** [comment]
Hi,

Spent lot of time on this and finally found this, Looks like sarama doesn't support SASL/SSL.
https://godoc.org/github.com/Shopify/sarama#GSSAPIKerberosAuth.Authorize
// SASL based authentication with broker. While there are multiple SASL authentication methods
// the current implementation is limited to plaintext (SASL/PLAIN) authentication
 
Confluent go has SASL/SSL support and its working in stand-alone programs, tried integrating that to jaeger but time taking so for now I deployed own kafka cluser with no-auth since only sasl-ssl is supported for us.

Not sure if Sarama package will have this feature enabled anytime soon, please share if any roadmap or update to get this feature.

Thanks...

**Comment by malkov82** [comment]
Hi,

Thank you for interest. We have another no-auth kafka cluster too, but want to use kerberos based one if it's possible.

Sharing our krb5.conf libdefaults content below. I'm not a kerberos expert, just got it from my colleague, don't know if we can change it. Hope it helps.

[libdefaults]
 allow_weak_crypto = true
 default_realm = XX.XXXXXX.XXX.XX
 default_tgs_enctypes = aes256-cts aes128-cts arcfour-hmac-md5 des-cbc-md5 des-cbc-crc
 default_tkt_enctypes = aes256-cts aes128-cts arcfour-hmac-md5 des-cbc-md5 des-cbc-crc
 permitted_enctypes = aes256-cts aes128-cts arcfour-hmac-md5 des-cbc-md5 des-cbc-crc
 dns_lookup_realm = true
 dns_lookup_kdc = true
 passwd_check_s_address = false
 noaddresses = true
 udp_preference_limit = 1
 ccache_type = 3
 kdc_timesync = 0

**Comment by gauravgill95** [comment]
Hey I am also getting the same error . Is the issue resolved ?

**Comment by gauravgill95** [comment]
> Is there any updates? I'm having the same issue..

Did you found any fix ?
