### ISSUE TITLE
configuration consistency across components (es-index-cleaner)

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/jaeger#2124]
https://github.com/jaegertracing/jaeger/blob/32d667ee851c09a32966b4aaca635c741e38e4c3/plugin/storage/es/esCleaner.py#L15

Hello @pavolloffay @yurishkuro @jpkrohling 

## Requirement - what kind of business use case are you trying to solve?

Trying to reuse config across various jaeger components. Works quite well except for es-index-cleaner and spark components. This issue addresses es-index-cleaner

## Problem - what in Jaeger blocks you from solving the requirement?
example:
 es-index-cleaner -> HOSTNAME, INDEX_PREFIX
 other components -> ES_SERVER_URLS, ES_INDEX_PREFIX

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Keep environment variable names consistent with main components (collector, query, ingester)

**Comment by pavolloffay** [comment]
`HOSTNAME` is index cleaner and rollover is not env variable. The connection string to ES is added as a parameter e.g. `cleaner 0 http://localhost:9200`.

**Comment by pavolloffay** [comment]
I will close this as wont-fix. There is not much-added value and implementing this in a backward-compatible way will add unnecessary complications in several components.

**Comment by naseemkullah** [comment]
OK good point for HOSTNAME and work vs value, also I understand if prefixing with `ES_` might feel redundant but please keep this in mind when adding new configurable options at least.

The helm chart greatly benefits from such consistency:

ES related configurable variables defined once: https://github.com/jaegertracing/helm-charts/blob/fc87249b7f3b8a0a6e5fd891d7a7a52ef6e17cd4/charts/jaeger/templates/_helpers.tpl#L293-L316

Passed to the es-index-cleaner and all components that talk to ES as so: https://github.com/jaegertracing/helm-charts/blob/fc87249b7f3b8a0a6e5fd891d7a7a52ef6e17cd4/charts/jaeger/templates/es-index-cleaner-cronjob.yaml#L47

However `ES_INDEX_PREFIX` cannot be reused for example, we'd need to add extra config to set `INDEX_PREFIX`. Fortunately, ES_USERNAME and ES_PASSWORD can be reused from the main es variables config that is shared.
