### ISSUE TITLE
`jaeger_collector_spans_bytes` is always 0

### ISSUE THREAD

**Issue by joe-elliott** [jaegertracing/jaeger#2126]
## Requirement - what kind of business use case are you trying to solve?
Gain information about per span sizes through Jaeger

## Problem - what in Jaeger blocks you from solving the requirement?

Currently `jaeger_collector_spans_bytes` always reports 0.

After upgrading to 1.17 I added `jaeger_collector_spans_bytes` up on a graph to get more information about per span sizing.  Unfortunately the gauge appears to be pinned at 0.

![image](https://user-images.githubusercontent.com/2272392/76641319-cb782500-6527-11ea-89ee-b0e042134011.png)

I'm unable to at the moment, but when I get some time I will dig deeper on this.

**Comment by yurishkuro** [comment]
yes, at some point this got broken, we need to restore it

**Comment by jpkrohling** [comment]
Do you have a number of spans processed?

https://github.com/jaegertracing/jaeger/blob/91c7e69a8aad60910cb299e295601c0ede1c1a4b/cmd/collector/app/span_processor.go#L165-L168

**Comment by jpkrohling** [comment]
We might want to run `sp.countSpan` also when the feature isn't enabled

**Comment by joe-elliott** [comment]
I see now.  No we do not have the dynamic queue size enabled and this is why it is reporting 0.

Close this issue?  Or perhaps we need to populate this metric even when the dynamic queue size is not enabled?

I would be glad to submit a fix if we would like that.

**Comment by jpkrohling** [comment]
>  Or perhaps we need to populate this metric even when the dynamic queue size is not enabled?

This is part of the critical path, which is why I didn't enable it by default. As you have a production environment with a respectable load, do you think you'd be able to move the `countSpan` to the default `processSpanFuncs` and see how it behaves?

**Comment by joe-elliott** [comment]
I rebuilt the jaeger collector from the `v1.17.0` tag.  The only change was adding `countSpan` to the `processSpanFuncs`.  Additionally I scaled down to 1 collector to force all spans through the same one.

I can confirm I am now getting the span bytes metric:

![image](https://user-images.githubusercontent.com/2272392/76764923-079bc780-676c-11ea-9001-cd279cc5cc7c.png)

I am seeing a performance change in CPU used (`container_cpu_usage_seconds_total`):

![image](https://user-images.githubusercontent.com/2272392/76765007-24d09600-676c-11ea-8860-fd83a940b7f2.png)

and in queue latency:

![image](https://user-images.githubusercontent.com/2272392/76765119-4893dc00-676c-11ea-9c96-037a31382304.png)

spans processed was between 9 and 10k/second throughout the change.

![image](https://user-images.githubusercontent.com/2272392/76765197-65c8aa80-676c-11ea-8342-57bd53b164c2.png)

I am also seeing a few dropped spans.  This appears to be due to the queue filling up which is currently configured at 10k spans.

![image](https://user-images.githubusercontent.com/2272392/76765304-90b2fe80-676c-11ea-9ff1-627ff7957d2b.png)

**Comment by jpkrohling** [comment]
That's great info, @joe-elliott! Given this information, do you still think this should be on by default? On one hand, this is a type of information that is valuable to have. On the other hand, the price to pay seems high: increased CPU usage, data loss (spans dropped), ...

**Comment by yurishkuro** [comment]
> I rebuilt the jaeger collector from the v1.17.0 tag. The only change was adding countSpan to the processSpanFuncs.

Do you mean the addition was on top of 1.17?

`span.Size()` function computes size recursively through all the fields, so would certainly take up some CPU. But I am surprised by the impact on latency, etc.

**Comment by joe-elliott** [comment]
> Do you mean the addition was on top of 1.17?

Yup.  I checked out `v1.17.0`,  commented out the if statement surrounding the addition of the `countSpan` processor so it was added unconditionally, ran `make docker-images-only` and used the result jaeger-collector image.

**Comment by joe-elliott** [comment]
@jpkrohling 

>  Given this information, do you still think this should be on by default? 

It is valuable information, but it looks to be roughly a ~20% increase in cpu costs.  To me it feels like this should remain configurable behind an option.  Perhaps additional documentation would help clarify that it's only on when dynamic queue sizing is enabled or maybe making these spans stats independently configurable from the dynamic queue size option.

**Comment by jpkrohling** [comment]
>  Another option would be to make these spans stats independently configurable from the dynamic queue size option.

This is the right solution, IMO.

**Comment by joe-elliott** [comment]
Yeah, I was looking into `span.Size()` to see if there was an opportunity to optimize it, but unfortunately it's generated proto code.  It basically descends the object tree and calls `.Size()` on everything (logs, tags, ...)

`sp.spansProcessed.Inc()` could be independent but might be confusing.  It might be easier to just say have an `--collector.enable-processed-span-metrics` flag that covers both of them.  Then if you have `--collector.queue-size-memory` enabled it will of course enable the metrics as well.

**Comment by wiardvanrij** [comment]
This would be useful to us. Are there any plans to enable this as flag?

**Comment by jpkrohling** [comment]
@wiardvanrij, would you be willing to give it a try? It should be relatively easy, especially following the discussion from this thread, but let me know if you need more concrete directions.

**Comment by jpkrohling** [comment]
Sounds good. Ping us if you need help.

**Comment by ymtdzzz** [comment]
Hi, does anyone works on it? If not, I'd like to try it!

**Comment by yurishkuro** [comment]
go for it
