### ISSUE TITLE
jaeger-collector "caller":"kafka/writer.go:58","msg":"circuit breaker is open"

### ISSUE THREAD

**Issue by rotemironsrc** [jaegertracing/jaeger#2127]
hey, 

i am getting lots of 

{"level":"error","ts":1584263247.6373,"caller":"kafka/writer.go:58","msg":"circuit breaker is open","stacktrace":"github.com/jaegertracing/jaeger/plugin/storage/kafka.NewSpanWriter.func2\n\tgithub.com/jaegertracing/jaeger/plugin/storage/kafka/writer.go:58"}

my jager-collector uses kafka as a storage
and i have jager-ingester listen to kafka and saves to elastic search

what does it mean circuit breaker is open and how can i solve this problem ?

**Comment by yurishkuro** [comment]
this is something coming from the sarama kafka driver.

https://github.com/jaegertracing/jaeger/blob/af674a5433ff6bd9cf624dacaa28ec6ebea82c48/plugin/storage/kafka/writer.go#L57-L61

**Comment by rotemironsrc** [comment]
I know, but what does it mean and how can i solve that ?
i tried googling the answer, not a lot of results!

**Comment by lvyishan** [comment]
> I know, but what does it mean and how can i solve that ?
> i tried googling the answer, not a lot of results!

I also encountered the same error, did you solve it? how did it solve it
Look forward to your reply

**Comment by jpkrohling** [comment]
Is it happening only after a period of time? Or right away, upon bootstrap? What are the versions of the components involved (Kafka, Jaeger)? Are you able to consistently reproduce it easily? If so, please share the steps so that we can try it out ourselves.

**Comment by jpkrohling** [comment]
We need information in order to reproduce and eventually fix this. I'm closing this, but feel free to reopen if you can provide the information or a fix.
