### ISSUE TITLE
Remove TChannel from agent->collector path

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2129]
@pavolloffay I created a new internal build that uses a local copy of the `/tchannel` packages you created (#2105), and deployed it today. All metrics look good. I think we can start removing the code.

**Comment by pavolloffay** [comment]
Do you want to submit a PR? If no I can do that.

**Comment by yurishkuro** [comment]
Go for it, I won't be able to get to it soon.

One thing I wanted to watch out was making sure we don't leave other dead code around. For example, pkg/discovery may be only used from tchannel.

**Comment by pavolloffay** [comment]
I am wondering whether full removal would break OTEL collector they are exposing tchannel exporter.

Afther quick inspection it looks that they are not using tchannel from agent or the new `tchannel` package cc) @objectiser 
https://github.com/open-telemetry/opentelemetry-collector/pull/636/files#diff-0e6ca11168918e81d990fd9005b9671cL45
