### ISSUE TITLE
Crash loop on jaeger tracing pod in Kubernetes

### ISSUE THREAD

**Issue by rbizzell40** [jaegertracing/jaeger#2134]
<!--
MacOs 14.6 Mojave
Minikube version 1.8.2 and 1.8.1
Kubernetes 1.17
Istio 1.5
Go 1.12.9
I am deploying Istio by curling to the latest version and then. executing kubectl apply -f
All pods come up except tracing pod and I receive this error
kubectl logs -f istio-tracing-7f8b785b8c-q7lkt
{"level":"info","ts":1584726980.0993352,"caller":"flags/service.go:113","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1584726980.1002212,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1584726980.1004531,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1584726980.10061,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"fatal","ts":1584726980.1194055,"caller":"all-in-one/main.go:356","msg":"Failed to initialize tracer","error":"dial udp [::1]:6831: connect: cannot assign requested address","stacktrace":"main.initTracer\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:356\nmain.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:98\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:167\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200"}

**Comment by yurishkuro** [comment]
please provide details (versions, configuration, etc.)

**Comment by rbizzell40** [comment]
MacOs 14.6 Mojave
Minikube version 1.8.2 and 1.8.1
Kubernetes 1.17
Istio 1.5.0
Go 1.12.9
I am deploying Istio by curling to the latest version and then. executing kubectl apply -f
All pods come up except tracing pod and I receive this error
kubectl logs -f istio-tracing-7f8b785b8c-q7lkt
{"level":"info","ts":1584726980.0993352,"caller":"flags/service.go:113","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1584726980.1002212,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1584726980.1004531,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1584726980.10061,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"fatal","ts":1584726980.1194055,"caller":"all-in-one/main.go:356","msg":"Failed to initialize tracer","error":"dial udp [::1]:6831: connect: cannot assign requested address","stacktrace":"main.initTracer\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:356\nmain.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:98\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:167\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200"}

**Comment by rbizzell40** [comment]
Is this what you are looking for

**Comment by yurishkuro** [comment]
it looks like you have something already listening to `udp [::1]:6831` port

**Comment by rbizzell40** [comment]
That resolved the issue I had another service using that port. Thanks

**Comment by dangerouspython** [comment]
@rbizzell40 I am facing the exact issue. However running `lsof -i :900` doesn't yield anything. How were you able to solve the issue?
