### ISSUE TITLE
Unable to creates the schema required by the Jaeger components while connect with remote secure cassandra endpoint. 

### ISSUE THREAD

**Issue by narendra0356** [jaegertracing/jaeger#2146]
## Requirement - what kind of business use case are you trying to solve?

I would like to create the schema using jaeger-cassandra-schema-job on remote cassandra cluster.
The kubernetes Job that creates the schema required by the Jaeger components.

apiVersion: batch/v1
  kind: Job
  metadata:
    name: jaeger-cassandra-schema-job
    labels:
      app: cassandra-schema
      app.kubernetes.io/name: cassandra-schema
      app.kubernetes.io/component: storage-backend
      app.kubernetes.io/part-of: jaeger
  spec:
    activeDeadlineSeconds: 86400
    template:
      metadata:
        name: cassandra-schema
      spec:
        activeDeadlineSeconds: 320
        containers:
        - name: jaeger-cassandra-schema
          image: jaegertracing/jaeger-cassandra-schema:1.6.0
          env:
            - name: MODE
              value: "prod"
            - name: DATACENTER
              value: "dc1"
        restartPolicy: OnFailure
https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/production/cassandra.yml

Based on datacenter value(I have deployed cassandra and the jaeger-cassandra-hema- job, then schema job able to find the datacenter value=dc1) the schema job has created the keyspace and tables Using template file /cassandra-schema/v001.cql.tmpl with parameters. The Cassandra-schema-job, How to find the remote cassandra cluster datacenter value. Where i need to configure remote cassandra details.

**Comment by pavolloffay** [comment]
The container invokes this script https://github.com/jaegertracing/jaeger/blob/74856efebf703bd98742b96db48724dca4e9e7fb/plugin/storage/cassandra/schema/docker.sh#L7, so you will have to define `CQLSH_HOST` and maybe other env variables in the schema job to properly configure it for your environment.

**Comment by annanay25** [comment]
I think we should reopen this issue and move it to the documentation repo, because docs definitely need enhancement. We should have instructions on how to configure the missing env vars like `CQLSH_HOST`
