### ISSUE TITLE
Jaeger : Reading spans from Jaeger Agent or Jaeger Collector

### ISSUE THREAD

**Issue by narsii4u** [jaegertracing/jaeger#2147]
## Requirement - what kind of business use case are you trying to solve?
We need to send spans to streaming service which has configuration like
sasl.mechanism=PLAIN
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required

We tried lot of things and we at the end we found an ER https://github.com/jaegertracing/jaeger/issues/1989 , but since its still an open ER, I am looking for a work around for time being.
Or any other tracing mechanism which supports above properties? Kindly suggest.
@jaegertracing/jaeger-maintainers

## Problem - what in Jaeger blocks you from solving the requirement?
Jaeger has ER https://github.com/jaegertracing/jaeger/issues/1989 open which is required for our problem is our understanding.

Any work around will help like:

## Any open questions to address
Can we read spans from agent/collector using custom code? Or any other idea will be of great help.

**Comment by jpkrohling** [comment]
I'm not quite sure what's missing to get the collector/ingester to work in your scenario. What exactly is missing? Note that `SASL_PLAIN` (username/password) should work fine. You just need to set the following flags:

```
      --kafka.producer.plaintext.password string       The plaintext Password for SASL/PLAIN authentication
      --kafka.producer.plaintext.username string       The plaintext Username for SASL/PLAIN authentication
```

As for a workaround, there are a couple of solutions:

1. build a storage plugin, as described in https://github.com/jaegertracing/jaeger/tree/master/plugin/storage/grpc 
1. use OpenTelemetry Collector with a Jaeger receiver and a custom exporter. @pavolloffay is building a custom OpenTelemetry Collector for Jaeger which you can use as reference
1. Use @pavolloffay's Jaeger OpenTelemetry Collector with a custom exporter

**Comment by pavolloffay** [comment]
Jaeger OTEL receiver/exporter is using the same code as the current Jaeger Kafka implementation. They expose the same configuration and behave the same. Hence I am not sure if that would help.

**Comment by jpkrohling** [comment]
@pavolloffay they'd write their own exporter, not using our Kafka exporter.

**Comment by yurishkuro** [comment]
There is not enough information about the use case here. in Jaeger-v2 we plan to use official OTEL Collector components for Kafka. If this feature is not supported there, feel free to open an issue in otel-collector-contrib. I am closing this as wontfix.
