### ISSUE TITLE
Dependency link processor in production deployment

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#215]
Currently the calculation of dependency link (graph) data is only available in the in-memory configuration of the server (e.g. all-in-one docker image).

The approach that will be used in the production deployment of Jaeger has been outlined in the discussion here: https://groups.google.com/d/msg/jaeger-tracing/2ClHbZ3BwBg/F80_y7lCAgAJ

Thought it would be good to have an issue that can be used to track this feature, and possibly lead to discussions around the proposed approach.

**Comment by objectiser** [comment]
This issue has a dependency on https://github.com/uber/jaeger/issues/150.

**Comment by yurishkuro** [comment]
NB: we have an on-going internal work on the data pipeline that includes a dependencies processor.

**Comment by objectiser** [comment]
Sorry, forgot to mention that.

Do you have a time estimate for when this may be available?

**Comment by pavolloffay** [comment]
@yurishkuro are there any news when this will be open-sourced?

On the [ML](ML https://groups.google.com/d/msg/jaeger-tracing/2ClHbZ3BwBg/F80_y7lCAgAJ) you mentioned old data processing pipeline using Spark which loads the whole C* and does the processing. Does this processing produce dependency links and is it configurable via `dependency-storage.data-frequency`? If so is there a way to open-source it?

**Comment by black-adder** [comment]
The data pipeline *should* be OSS in H2. The problem with the spark job is that it uses zipkin data (before we had the jaeger domain model, we stored all our spans as zipkin in c*). If we wanted to OSS the existing Spark job we would have to either:

1. write a jaeger to zipkin converter in java/scala
2. open up an endpoint on the collector that returns zipkin spans
3. rewrite the Spark job to use jaeger model directly

3 is the best solution but I don't think we have any cycles internally to do so.

**Comment by yurishkuro** [comment]
we can "throw over the all" the spark job if someone wants to pick it up, but I really don't like it since it must scan the whole database, and as a result it often fails in the middle even after retries. The new gen dependency job based on the data pipeline will be streaming (from Kafka).

**Comment by pavolloffay** [comment]
I am starting to looking at this. Based on the previous discussion I have two approaches in my mind:

## Baggage based approach
Tracer would add jaeger specific baggage representing the service name in injecting the context. This baggage would be removed when extracting the context and it will be added to the first span. So when the span arrives in collector we know span's service name and parent service name.

pros: 
* it does not rely on the instrumentation setting appropriate tags (url or possibly others)
cons:
* requires change across all clients.
* it would not work with zipkin native clients

## Data investigation based approach
Dependency link would be created based on data attached to the span. For example, if there is `http.url` in client span it means that there is a chance that hostname represents service name of the called service(it holds in k8s deployment).

pros:
* only server side change
cons:
* depends on the data attached to span which can be wrong or there might be no-data at all.


We could implement just one or both. For example if there is no tag representing the parent service name it would try to derive dependency link based on the data in the span. All this would be configurable via flag in collector... Any feedback is welcome.

**Comment by black-adder** [comment]
The path we've taken looks like this: https://github.com/uber/jaeger/blob/553ec7a3f4afe4b71923ff7e81a62d4f8d3ec570/storage/spanstore/memory/memory.go#L56 we wait until the trace is complete then we can walk over the call graph and use service name and operation name to determine the dependency links. This requires no client side changes but requires knowledge that a trace is "complete".

Maybe I'm misunderstanding something and you want to generate the dependencies live as the spans arrive? Then yes you would require the changes you suggested but I don't see why we'd need live dependency links given the topology of a request will seldom change.

**Comment by objectiser** [comment]
As we understand it, the current "production" approach for creating the dependency links will require the post processing backend. The ideas Pavol has outlined are intended as a possible lightweight alternative approach for users who may not want to include the post processing pipeline infrastructure - possibly as their throughput is not that high.

**Comment by yurishkuro** [comment]
My problem with the first approach is that it does not provide very useful data, just service to service links (maybe endpoints dimension can be squeezed in). That kind of data can be obtained by other tools, e.g. by spying on the network connections (as Netsil does), or from service meshes.

I personally prefer the data mining approach, which we are using already internally with awesome results. I will try to showcase it at OS Summit in LA. The main difference there is that it really uses the fact that we are _tracing_ the transactions, so the dependency graphs are built with path awareness, rather than mere point to point links.

**Comment by objectiser** [comment]
Would it be better to make the dependency view in the UI optional then, so only displayed if the server has the information - so in the current environment it would be shown for all-in-one, but not for the "production" setup unless the post processing pipeline is in place?

And then later when the more advanced mechanism is available, it can take the place of the current dependency view?

**Comment by yurishkuro** [comment]
makes sense to me. 

@tiffon can we have a built-time env var to control that tab for now?

**Comment by pavolloffay** [comment]
My goal is to implement a light weight alternative for deriving dependency links. The exact same functionality what we have in `all-in-one` but for production deployment. It's useful information which can be derived very easy from the data what is there. 

> The main difference there is that it really uses the fact that we are tracing the transactions, so the dependency graphs are built with path awareness, rather than mere point to point links.

But I guess this would be a different screen not the current `/dependencies` tab.

**Comment by yurishkuro** [comment]
> My goal is to implement a light weight alternative for deriving dependency links. 

"light weight" is relative - it requires changes in libs across all languages and forces extra monitoring data in-band.

> But I guess this would be a different screen not the current /dependencies tab.

I think the new graphs will replace that tab. The p2p graph can be derived from the richer data easily, yet the actual display is not that useful in most situations.

**Comment by pavolloffay** [comment]
I remember that current dependencies screen was not useful for very large deployments, however for smaller ones it has its value. At least we see it that way. 

By lightweight, I mean that it does not require to deploy any other external services like kafka etc (it can make jaeger deployment for monitoring smaller deployments on k8s/openshift make much more expensive).

One baggage value is not that bad, note that that baggage is not accumulating. It's removed when it reaches the first service. 

I would store something like:
`timestamp, trace_id, parent_service, child_service`. Then the query would get all within the requested time window and calculate the counts (trace_id is redundant) later it could be used for more advanced processing.

**Comment by mabn** [comment]
> "light weight" is relative - it requires changes in libs across all languages and forces extra monitoring data in-band.

Isn't there already `x-uber-source`? I'm not sure how ubiquitous this is at Uber, but we have similar header (only for http calls). So @pavolloffay's "baggage based approach" would be similar to using `x-uber-source` to set `peer.service` tag.

+1 for the pipeline by the way! It enables lots of interesting possibilities.

**Comment by adriancole** [comment]
In trace-context group I have heard talk of a potential rider header for
service graph. However it will be hard to count links accurately. Also the
service names in many cases are less reliable from client. Finally need to
consider brokers which can wash this away. Keep this stuff in mind as after
the fact even if 1 minute after the fact, it is easier to resolve these
problems.

On 31 Aug 2017 3:54 am, "Marcin Biegan" <notifications@github.com> wrote:

"light weight" is relative - it requires changes in libs across all
languages and forces extra monitoring data in-band.

Isn't there already x-uber-source? I'm not sure how ubiquitous this is at
Uber, but we have similar header (only for http calls). So @pavolloffay
<https://github.com/pavolloffay>'s "baggage based approach" would be
similar to using x-uber-source to set peer.service tag.

+1 for the pipeline by the way! It enables lots of interesting
possibilities.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/uber/jaeger/issues/215#issuecomment-326100618>, or mute
the thread

**Comment by pavolloffay** [comment]
Closing now we have a spark job which processes spans and creates dependency links: https://github.com/jaegertracing/spark-dependencies

**Comment by yurishkuro** [comment]
@pavolloffay could you please mention it in the documentation somewhere?
