### ISSUE TITLE
Which processors should be used by default?

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#2152]
Created from https://github.com/jaegertracing/jaeger/pull/2148#discussion_r402939295

List of OTEL processors https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor

**Comment by pavolloffay** [comment]
Based on https://github.com/jaegertracing/jaeger/pull/2148#discussion_r403898358. OTEL collector might run without any processor.

**Comment by objectiser** [comment]
Use of the `queued_retry` processor may be required if we want a certain set of metrics - I will re-review the metrics again this week following some changes upstream, so we can list which metrics would be dependent upon which particular processors.

**Comment by pavolloffay** [comment]
Once our storage exporters will accept batches we could enable batch and queued retry processors. 

For now, I wanted to enable memory limiter, however, it accepts absolute settings. I have submitted a proposal to accept percentage configuration https://github.com/open-telemetry/opentelemetry-collector/issues/1078 that would enable us to enable it by default for any deployment.

**Comment by pavolloffay** [comment]
Closing as it is a "low level" issue related to V2 which might take a different approach.
