### ISSUE TITLE
Add span sanitiser to mask sensitive fields

### ISSUE THREAD

**Issue by annanay25** [jaegertracing/jaeger#2166]
From - https://gitter.im/jaegertracing/Lobby?at=5e865f678f149739d32f336d

There is a requirement to mask sensitive fields from span logs, something that can be implemented as a span sanitiser processor as part of the jaeger-otel-collector.

**Comment by pavolloffay** [comment]
Can it be done via OTEL's attribute processor https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#attributes-processor?

**Comment by pavolloffay** [comment]
I am closing this. It can be done be enabling OTEL attribute processor in our OTEL based agent or collector. 

There is no plan to add this into legacy agent/collector.
