### ISSUE TITLE
storage/host requirements for Jaeger

### ISSUE THREAD

**Issue by itisdeep** [jaegertracing/jaeger#2178]
Hi Team,

I have used Jaeger production templates for Openshift (not all-in-one)  to deploy in our environments and I am not using Jaeger operator. Since our elasticsearch cluster is running externally (not on Openshift), I have tweaked the yamls to point to our elasticsearch cluster. I would like to know, is there scenario that might come up while running Jaeger in production that may need us to get some persistent storage in Openshift OR any extra host required for Jaeger. Where does Jaeger store the data that it shows on Jaeger-query URL? Is it the elasticsearch backend in my case?

Regards,
Deependra

**Comment by objectiser** [comment]
@itisdeep All the data is stored in the external Elasticsearch in the scenario you described.

Is there a particular reason you didn't use the Jaeger operator?

**Comment by itisdeep** [comment]
@objectiser thanks for the response. There is no particular reason. I found it easy without operators. Is there something I am missing by not using Operators?

**Comment by objectiser** [comment]
The operator aims to simplify configuration of different scenarios, and will help with upgrade situations.
