### ISSUE TITLE
ES bulk and config of ES_SERVER_URLS

### ISSUE THREAD

**Issue by biskit** [jaegertracing/jaeger#2179]
Hi,
Newbie to this product so please go easy on me...

1. Trying to see if Jaeger could do a bulk post to ES like FileBeat/MetricBeat and honor the setup.template.enabled= flag or similar.

Details:
- I would like to see a bulk post to an end point - say http://localhost:9200/jaeger/_bulk 
   today ES_SERVER_URLS ignores the URI

- Not worry about loading templates to index if the setup.template.enabled=false is set. similarly dont' worry about rotating index etc

- Being a bulk operation, not worry about indexing or any of that and just dump the collector trace spans as json

- Get back a FileBeat/MetricBeat style response of errors that says what particular trace ID failed to post and why

This makes receiving on the backend (be it ES or similar) without needing new plugins.

2. Or if this is lot of work, one can write to a log file (don't see a local file plugin) and can use FileBeat to process this file up to ES.

I did see #2142 but not sure how to configure that to be used in 1.17.1

Thanks,

**Comment by pavolloffay** [comment]
Our Elasticsearch storage writer already uses bulk API to index data to ES. Are you asking for this or something different? Could you please point us to Elasticsearch docs or blog post where we can learn more what you are asking for?

**Comment by biskit** [comment]
hi thanks for reply. 

I have my ES behind a lb and it has to either forwarded or rewritten and forwarded. I tried to set ES_SERVER_URLS to something like http://localhost:8080/jaeger that can be then forwarded, but all I could see was it tyring a HEAD on "/".

I could not see anything further because it gave up after trying. 

This was my command line: 
`SPAN_STORAGE_TYPE=elasticsearch ES_SERVER_URLS=http://localhost:8080/jaeger ./jaeger-all-in-one`

If I can get past this I can see the POST calls to `_bulk`.

Thanks

**Comment by biskit** [comment]
It does make calls to HEAD at given URL. 

I was looking for something like a tee writer that can dump all spans to a given URL and not worrying about anything more than a 503 retry later.

Is there a tee writer somewhere either as storage option or some other form of plugin?

**Comment by pavolloffay** [comment]
The `server-urls` flag is passed directly to the ES client https://github.com/jaegertracing/jaeger/blob/b1868a623bb0fa61bd369875578988534982a5e4/pkg/es/config/config.go#L286. We are using this client https://github.com/olivere/elastic you might check out there if your feature is supported there.

> It does make calls to HEAD at given URL.

So did it work? Did it ping the `=http://localhost:8080/jaeger` ?

> Is there a tee writer somewhere either as storage option or some other form of plugin?

I don't know of anything like this.
