### ISSUE TITLE
generate an alert when a service exceeds 10 seconds

### ISSUE THREAD

**Issue by ortiga88** [jaegertracing/jaeger#2180]
I have a monitored service that takes 2 seconds each request. I want an email alert to arrive if it takes more than 10 seconds, is there a plugin or could this be done from the jaeger itself ???

**Comment by pavolloffay** [comment]
There is no such functionality in Jaeger at the moment. This could be done be exporting prometheus metrics from your runtime and then leveraging Prometheus alert manager to set the condition.

Please ask questions on https://gitter.im/jaegertracing/Lobby
