### ISSUE TITLE
Is it possible to send traces to elasticsearch through logstash

### ISSUE THREAD

**Issue by itisdeep** [jaegertracing/jaeger#2187]
Hi Team,
 Is it possible to send traces/logs from Jaeger to logstash first instead of directly sending to elasticsearch. Correct me if I am wrong but I think its not possible as of now as I could not find anything related to it. But if we use intermediate buffers like Kafka then its possible to send it through logstash? Please advise. Below are the versions that we are using-
Elasticsearch: 7.4
Jaeger: version 1.14 images running on openshift cluster

**Comment by yurishkuro** [comment]
Jaeger itself only writes to Kafka or supported storage backends. You can implement various external adapters or storage plugins.
