### ISSUE TITLE
ElasticSearch index gets too large when tracing a large cluster. 

### ISSUE THREAD

**Issue by sunxiaoguang** [jaegertracing/jaeger#2189]
## Requirement - what kind of business use case are you trying to solve?
ElasticSearch index gets too large when tracing a large cluster. It's more than 1TB at this time and we expect it to grow even more later on. 

## Problem - what in Jaeger blocks you from solving the requirement?
A single huge index makes searching pretty slow even when I only need to search the latest spans within an hour. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Support rollover indices by finer granularity like every hour or even every quarter hour.

**Comment by yurishkuro** [comment]
Jaeger works with Elastic Rollover, which allows you to set different index rollover policies other than one index per day. https://www.jaegertracing.io/docs/1.17/deployment/#elasticsearch-rollover
