### ISSUE TITLE
Security on collecting traces

### ISSUE THREAD

**Issue by LarsMilland** [jaegertracing/jaeger#219]
Hi

Is it possible to add security layers to the different collectors, UDP / HTTP based ones to restrict which clients can submit tracing data to the collectors. I am thinking on Oauth based tokens, client certificates, LDAP username/password, shared secrets or similar. Also would it be possible to restrict which clients can submit traces on which services.

Having looked in the codebase I am not able to find such features.

Best regards
Lars Milland

**Comment by yurishkuro** [comment]
Could you describe the use case and the network layout of clients/apps & Jaeger deployment that you're thinking about?

Of the options you listed, the basic auth makes the most sense to me, which is equivalent to an "API token" used in many commercial offerings (i.e. a shared secret). We already support that in the Go client, but there's no enforcement on the server.

**Comment by jpkrohling** [comment]
I have the same comment as the issue for the UI: 
https://github.com/uber/jaeger/issues/218#issuecomment-309649858

In short: this is probably better handled by a side car.

**Comment by objectiser** [comment]
@jpkrohling This would be a good topic for a blog :) Show how keycloak could be used to secure the UI and server.

**Comment by LarsMilland** [comment]
After looking at the comments/discussions here on my question on supporting some kind of secured access to Jaeger Collectors endpoints, I have chosen to use the concept of a side-car with an Apache httpd server acting as reverse proxy to the Jaeger Collector endpoint. As I anyway am going to deploy Jaeger on OpenShift and have by that deployment architecture an easy way of augmenting the Jaeger component running as Docker container on OpenShift with additional Docker containers wrapping the non-secure ports. Also I in my setup prefer to use the HTTP based Collectors Apache httpd acting as reverse proxy fits perfectly. I will then just add certificates for HTTPS encryption on the endpoint and Basic Authentication forwarding to our internal LDAP directory with both authentication and authorization on LDAP group memberships. That way I can reuse all security components and processes of my organisation, and let Jaeger be Jaeger - securing it by wrapping it through Apache httpd as reverse proxy. Clients submitting traces will be handed credentials for LDAP Service Account kind users (this could of course just as well be client certificate based authentication instead of LDAP). 

The exact same solution will be applied to the UI endpoint of Jaeger (see also issue #218).

**Comment by yurishkuro** [comment]
That's awesome, @LarsMilland. Would you consider writing a blog post about this setup?

**Comment by jpkrohling** [comment]
If there's a blog post on this already, I'd gladly add a link to it on a blog post I'm writing about using a sidecar to protect the UI.

**Comment by LarsMilland** [comment]
@yurishkuro, @jpkrohling - I have published a blog post on the architecture we have implemented with a sidecar option on both the Collector and UI endpoints on Jaeger here:

https://medium.com/@larsmilland01/secure-architecture-for-jaeger-with-apache-httpd-reverse-proxy-on-openshift-f31983fad400

**Comment by jpkrohling** [comment]
Thanks for sharing, @LarsMilland ! If you could, join our gitter channel: I'd like to suggest a couple of things to improve in private.

**Comment by yurishkuro** [comment]
can this issue be closed?

**Comment by jpkrohling** [comment]
Not yet: I think our official answer would involve using Istio (for container-based deployments), so, let's wait until that works for us to close this one here.

**Comment by rabbitstack** [comment]
+1 for a native authentication support in Jaeger. Let's imagine a typical SaaS scenario where agents collect  trace data on remote nodes and send the spans to the publicly exposed (might be behind the reverse proxy) collector endpoint. Obviously, we wouldn't like everybody inject trace data, therefore, the agent should send a sort of auth token (JWT or plain API token) alongside trace metadata. The collector should be able to validate the token (querying the DB, verifying JWT signature, etc.), and reject the span request if authentication is not successful.

**Comment by jpkrohling** [comment]
> Obviously, we wouldn't like everybody inject trace data, therefore, the agent should send a sort of auth token

This is better handled by a service mesh framework, like Istio. Otherwise, we'll bring infra-level knowledge to components that are very slim and specialized.

We have a demo already on how to protect the UI with Keycloak, and the collector could be protected in a very similar way. So, I really think this does not belong to the microservices (collector, agent, ...)

**Comment by rabbitstack** [comment]
> This is better handled by a service mesh framework, like Istio.
This could add (unneeded) complexity and might not be suitable for every scenario. 

Also, think this could derive to making Jaeger a multi tenant platform if one could also store the token and use it later to filter out the traces that pertains to a specific user.

I was aware of the @LarsMilland blog post, but note, he has had to modify the tracer client to add username/password headers, and IMHO this wouldn't be reasonable to do on each (go, ruby, node.js)  client impl.

Thanks

**Comment by jpkrohling** [comment]
I think this could be discussed on the mailing list, specially about the multi tenancy aspect (there's a thread there about it already). I particularly think there are ways to achieve all of that today with existing tools, without bloating Jaeger components, but if the general consensus is that this *needs* to be included in Jaeger itself, I'm OK with that :)

**Comment by jpkrohling** [comment]
I'm closing this, as the recommended approach hasn't changed and we don't have plans to add auth/z directly into the backend components such as the collector.
