### ISSUE TITLE
A new bit introduced in the context flag to mark the status of the sampling decision

### ISSUE THREAD

**Issue by lujiajing1126** [jaegertracing/jaeger#2201]
## Requirement - what kind of business use case are you trying to solve?

According to the [B3-propagation protocol](https://github.com/openzipkin/b3-propagation), the client is allowed to send simply `X-B3-Sampled: 0` without specifying the fields of the trace context such as `X-B3-TraceId`, `X-B3-ParentSpanId` etc.

## Problem - what in Jaeger blocks you from solving the requirement?

In the current [B3Codec](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/propagation/B3TextMapCodec.java#L128-L142) of the jaeger-java-client, if `X-B3-TraceId` is not found in the headers, a NULL context will be returned. Thus the sampling decision sent with `X-B3-Sampled` header will be totally neglected.

However, the aforementioned behavior cannot be implemented in the current jaeger client in the sense of lacking the memory of sampling decision which can be probably stored in the context flags.

With the [current jaeger context flags](https://www.jaegertracing.io/docs/1.17/client-libraries/#value), there are only two deterministic statuses, i.e. `Sample` and `Not Sample` which are documented on the website. With the glossary used in B3-propagation protocol, they are equivalent to `Accept` and `Deny`. So actually we cannot tell the difference between `Deny` and `Defer` in the following scenario.

- With only `jaeger-baggage` header, the sampling decision is now supposed to be made later by the Sampler. The context flag is set to `0` which means `Defer` sampling.
- If `X-B3-Sampled: 0` is used, the context flags can be only set to `0` now (which is a limitation), with which the client requires the tracer not to sample the trace. In this context, `0` means `Deny`.

However, this is controversial since there are two different behaviors corresponding to the single `0` context flag.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

With the above discussion, I propose to use `0x04` to mark whether the sampling decision has been made. According to the document and current implementations, Bit 3 (`0x04`) has not been used.

The detailed semantics can be defined as following,

- If sampling decision is sent in the propagation, for example `X-B3-Sampled`, Bit 3 MUST be set to 1 with Bit 1 set to 1 as Sampled and 0 as Not Sampled. New spans created subsequently SHOULD be compatible with this sampling decision iff there is no existing context.
- If sampling decision is not found, for example only `jaeger-baggage` is sent, Bit 3 MUST be set to 0 with Bit 1 set to 0. The sampling decision is thus delegated to the sampler. This behavior is exactly the same as the current one.

The semantic proposed here is supposed to be backward compatible with the old versions since the old versions do nothing with the Bit 3.

### Open questions

Probably some edge cases have to be considered?

### Related issues and PRs

1. https://github.com/jaegertracing/jaeger-client-java/issues/708
2. https://github.com/jaegertracing/jaeger-client-java/issues/624
3. https://github.com/jaegertracing/jaeger-client-java/pull/707

**Comment by yurishkuro** [comment]
* We need a proper name for the new bit. The name from the PR `flagSampledSet` does not make sense to me. I think `flagSamplingDeferred` is probably the most appropriate.
* The bit needs to be backwards compatible. All existing clients will be setting the new bit to 0, so that 0 value must have the same semantics as today.
* There needs to be a validity matrix. Zipkin is avoiding inconsistent states by using a single denormalized enum field (which mixes additional concerns like "debug", for which we have a separate bit). For example, if we go with "deferred" flag, then:
   * `sampled=0, deferred=1` means an upsamping may occur downstream in upgraded clients, while existing clients that don't recognize `deferred` will not sample the spans
   * `sampled=1, deferred=1` seems to be logically inconsistent altogether
* The matrix needs to prescribe the behavior for invalid states, e.g. `1/1` from the previous bullet point should be treated as `1/0`.

Once we have clearly defined semantics for Jaeger native clients, we can map Zipkin states to the matrix.

**Comment by lujiajing1126** [comment]
> * We need a proper name for the new bit. The name from the PR `flagSampledSet` does not make sense to me. I think `flagSamplingDeferred` is probably the most appropriate.

I agree with this. Though I used `flagSampledSet` in PR and this name has been used by `openzipkin/brave` project, `flagSamplingDeferred` seem to be more meaningful.

> * The bit needs to be backwards compatible. All existing clients will be setting the new bit to 0, so that 0 value must have the same semantics as today.

Yes. The `BIT 3 = 0` implies that the sampling decision has been made according to the current semantics. So in the future, set BIT 3 to 1 means undetermined sampling decision, I suppose.

> * There needs to be a validity matrix.

A preliminary version could be

| flag matrix | sampled = 0 | sampled = 1 |
| - | - | - |
| deferred = 0 | Not Sampled | Sampled |
| deferred = 1 | Deferred | Invalid (equals to Deferred? or Sampled?) |

The interpretation of the invalid state actually means the priority of the flags.
Similarly, additional DEBUG flag should be considered.

**Comment by lujiajing1126** [comment]
Any further discussion or detailed plan?

**Comment by yurishkuro** [comment]
@jaegertracing/jaeger-maintainers please review

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients, please open this request in OpenTelemetry if still needed
