### ISSUE TITLE
Any invalid or redundant config in jaeger-query?

### ISSUE THREAD

**Issue by salmon7** [jaegertracing/jaeger#2202]
## Requirement - what kind of business use case are you trying to solve?

Is there any redundant config which takes no effect in jaeger-query? Like the config  `--es.create-index-templates` takes no effect to the application after I look into the code. It really confused me and lead me to wrong side. (The index template should be created by collector).

Docs is here [link](https://www.jaegertracing.io/docs/1.17/cli/#jaeger-query-elasticsearch)

## Problem - what in Jaeger blocks you from solving the requirement?

It may confuse someone who is the beginner of jaeger.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

None

Show valid config in the component  docs or in `-h` command line

## Any open questions to address

None

**Comment by yurishkuro** [comment]
Can you point to the code? Generally, the way Storage plugins are implemented, it's irrelevant where they are instantiated, so I would assume you _could_ create templates from the query service just as well.

**Comment by pavolloffay** [comment]
@salmon7, are you asking only about Elasticsearch configuration? 

Jaeger query can persist data via archive storage. The reader and writer share storage configuration that exposes flags - we do this for all storages except Kafka (split by producer and consumer).

**Comment by salmon7** [comment]
> Can you point to the code? Generally, the way Storage plugins are implemented, it's irrelevant where they are instantiated, so I would assume you _could_ create templates from the query service just as well.

In jeager query, I can not find any place will init spanWriter which is the only way to init the template of es. It just inits the spanReader [here](https://github.com/jaegertracing/jaeger/blob/66993a2a86bb92a68f865aa8f2a6ce29618425b1/cmd/query/main.go#L94) but no anything about writer. On the contrary, in collector it inits spanWriter [here](https://github.com/jaegertracing/jaeger/blob/66993a2a86bb92a68f865aa8f2a6ce29618425b1/cmd/collector/main.go#L72).  

I will show the call inverted stack to create index template in es for collector:
1.  [CreateTemplates](https://github.com/jaegertracing/jaeger/blob/66993a2a86bb92a68f865aa8f2a6ce29618425b1/plugin/storage/es/spanstore/writer.go#L94)  
2.  [writer.CreateTemplates](https://github.com/jaegertracing/jaeger/blob/66993a2a86bb92a68f865aa8f2a6ce29618425b1/plugin/storage/es/factory.go#L201)  
3. [Factory.CreateSpanWriter](https://github.com/jaegertracing/jaeger/blob/66993a2a86bb92a68f865aa8f2a6ce29618425b1/plugin/storage/es/factory.go#L109)
4. [main.storageFactory.CreateSpanWriter](https://github.com/jaegertracing/jaeger/blob/66993a2a86bb92a68f865aa8f2a6ce29618425b1/cmd/collector/main.go#L72)  

So, if the query can write the storage, maybe it should init the writer first?

**Comment by salmon7** [comment]
> @salmon7, are you asking only about Elasticsearch configuration?
> 
> Jaeger query can persist data via archive storage. The reader and writer share storage configuration that exposes flags - we do this for all storages except Kafka (split by producer and consumer).

Em.... But I can't see any code to init the writer in jaeger query, maybe it not direct instantiated because the abstract factory?

**Comment by pavolloffay** [comment]
> Em.... But I can't see any code to init the writer in jaeger query, maybe it not direct instantiated because the abstract factory?

It's archive storage, for example here: 

https://github.com/jaegertracing/jaeger/blob/32d667ee851c09a32966b4aaca635c741e38e4c3/cmd/qu
ery/app/querysvc/query_service.go#L129

**Comment by pavolloffay** [comment]
I am closing this, we will do a cleanup of flags in Jaeger 2.0.
