### ISSUE TITLE
Create Jaeger ingester OpenTelemetry distribution

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#2205]
Similar to #2204 but for ingester.

**Comment by yurishkuro** [comment]
What about ingester would benefit from otel-collector framework?

**Comment by pavolloffay** [comment]
There might be several advantages:

* unified configuration for all jaeger components
* unified observability for all jaeger components - health check, metrics 
* use of OTEL processors   e.g. attribute processor

**Comment by objectiser** [comment]
The other benefit would be transitioning to the standard OTel Collector kafka exporter and receiver (using OTel model).
