### ISSUE TITLE
Not able to run the code 

### ISSUE THREAD

**Issue by vvvprabhakar** [jaegertracing/jaeger#2210]
ok  	github.com/jaegertracing/jaeger/storage/spanstore/metrics	3.258s
?   	github.com/jaegertracing/jaeger/storage/spanstore/mocks	[no test files]
?   	github.com/jaegertracing/jaeger/swagger-gen/models	[no test files]
?   	github.com/jaegertracing/jaeger/swagger-gen/restapi	[no test files]
?   	github.com/jaegertracing/jaeger/swagger-gen/restapi/operations	[no test files]
?   	github.com/jaegertracing/jaeger/thrift-gen/agent	[no test files]
?   	github.com/jaegertracing/jaeger/thrift-gen/baggage	[no test files]
?   	github.com/jaegertracing/jaeger/thrift-gen/jaeger	[no test files]
?   	github.com/jaegertracing/jaeger/thrift-gen/sampling	[no test files]
?   	github.com/jaegertracing/jaeger/thrift-gen/zipkincore	[no test files]
FAIL
**make: *** [test] Error 1**

**Comment by vvvprabhakar** [comment]
I want to know how we can generate a binary for a jaeger-query with UI
I want some minor modification in UI, after that modification so I want to build the binary

**Comment by yurishkuro** [comment]
the Makefile has targets to generate all binaries, for different platforms.

**Comment by vvvprabhakar** [comment]
I am getting an error wat to do ?? 
How to solve thw above error ?? 
When i give make in terminal it exits with [test] error

**Comment by yurishkuro** [comment]
The building instructions are described in CONTRIBUTING.md
