### ISSUE TITLE
Not able to trace a service from Jaeger UI using spring-boot application.

### ISSUE THREAD

**Issue by Haiba8** [jaegertracing/jaeger#2217]
Unable to trace a services for springboot application on Jaeger UI(localhost:16686/search). Here I am able to run an application successfully, but unable to get a services in jaeger ui(Except defalut one jaeger-query).
I used docker cmd to start the jaeger service,
`docker run --rm -it --network=host jaegertracing/all-in-one`
Open the Jaeger UI on [http://localhost:16686/search](url)

And even I  linked the container that has  demo-opentracing.jar file with the other running container jaegertracing/all-in-one with a cmd,
`docker run --network=opentracing-java-examples-master_default --link opentracing-java-examples-master_demo_1:opentracing-java-examples-master_demo -t -i --name jaegerDock -p 16686:16686 -p 6831:6831/udp jaegertracing/all-in-one:1.9`
Then also i didn't get any services at Jaeger UI.

and the code is as follows,
DemoApplication class,

`@SpringBootApplication
  public class DemoOpentracingApplication {

	@Bean
	public RestTemplate restTemplate(RestTemplateBuilder restTemplateBuilder) {
		return restTemplateBuilder.build();
	}

	@Bean
	public io.opentracing.Tracer jaegerTracer() {
		return new Configuration("spring-boot", new Configuration.SamplerConfiguration(ProbabilisticSampler.TYPE, 1),
				new Configuration.ReporterConfiguration())
				.getTracer();
	}

	public static void main(String[] args) {
		SpringApplication.run(DemoOpentracingApplication.class, args);
	}
}`

And the HelloController class,

`@RestController
public class HelloController {

    @Autowired
    private RestTemplate restTemplate;

    @RequestMapping("/hello")
    public String hello() {
        return "Hello from Spring Boot Container!";
    }

    @RequestMapping("/chaining")
    public String chaining() {
        ResponseEntity<String> response = restTemplate.getForEntity("http://localhost:8082/hello", String.class);
        return "Chaining Container+ " + response.getBody();
    }
}`

pom.xml file,

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>demo-opentracing</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>demo-opentracing</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.3.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>io.opentracing.contrib</groupId>
			<artifactId>opentracing-spring-web-autoconfigure</artifactId>
			<version>0.0.4</version>
		</dependency>

		<dependency>
			<groupId>com.uber.jaeger</groupId>
			<artifactId>jaeger-core</artifactId>
			<version>0.18.0</version>
		</dependency>

		<dependency>
			<groupId>io.opentracing.brave</groupId>
			<artifactId>brave-opentracing</artifactId>
			<version>0.20.0</version>
		</dependency>
		<dependency>
			<groupId>io.zipkin.reporter</groupId>
			<artifactId>zipkin-sender-okhttp3</artifactId>
			<version>0.10.0</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
`

![Screenshot (661)](https://user-images.githubusercontent.com/60427220/80994752-c023e480-8e5a-11ea-8100-8f7773dab523.png)
![Screenshot (598)](https://user-images.githubusercontent.com/60427220/80994791-daf65900-8e5a-11ea-81b0-3cb26afc8937.png)

 follwed this link :[https://github.com/pavolloffay/opentracing-java-examples](url)

**Comment by yurishkuro** [comment]
you're linking containers in the wrong direction. Jaeger does not need to find your application, your application does need to know how to reach Jaeger.

**Comment by Haiba8** [comment]
Thanks for the reply Sir. That was second try to get the services,as I was unable get. I am beginner to Jaeger, I am not getting where I am going wrong.I followed the link to study the Jaeger tracing , https://github.com/jaegertracing/jaeger/issues/url
Can you please help to get the traces.

**Comment by yurishkuro** [comment]
I recommend starting with the demo https://github.com/jaegertracing/jaeger/tree/master/examples/hotrod#run-everything-via-docker-compose. You can modify the docker-compose file to run your application instead of HotROD.

**Comment by Haiba8** [comment]
I ran it through docker-compose file, still no services found.

![Screenshot (662)](https://user-images.githubusercontent.com/60427220/81007030-1f3f2480-8e6e-11ea-938c-41f4a2dd4076.png)
![Screenshot (663)](https://user-images.githubusercontent.com/60427220/81007049-282ff600-8e6e-11ea-8c50-a72041cbecbe.png)

**Comment by yurishkuro** [comment]
This should've worked, assuming that your application is actually emitting traces. Have you followed https://www.jaegertracing.io/docs/1.17/troubleshooting/ ?

**Comment by Haiba8** [comment]
Yaa I followed.

**Comment by yurishkuro** [comment]
what did you try and what were the results?

**Comment by Haiba8** [comment]
I just added JAEGER_REPORTER_LOG_SPANS= true, to the docker-compose.yml
file along with other environments like
JAEGER_SERVICE_NAME=spring-boot
JAEGER_AGENT_HOST=jaeger
JAEGER_AGENT_PORT=6831
JAEGER_SAMPLER_MANAGER_HOST_PORT=Jaeger:5778

**Comment by objectiser** [comment]
On Mon, May 4, 2020 at 9:20 PM Haiba8 <notifications@github.com> wrote:

> I just added JAEGER_REPORTER_LOG_SPANS= true, to the docker-compose.yml
> file along with other environments like
> JAEGER_SERVICE_NAME=spring-boot
> JAEGER_AGENT_HOST=jaeger
> JAEGER_AGENT_PORT=6831
> JAEGER_SAMPLER_MANAGER_HOST_PORT=Jaeger:5778
>

Did you see any logging message (within your app) showing that your spans
were being reported? (related to JAEGER_REPORTER_LOG_SPANS)

You might want to try sampling all spans, using JAEGER_SAMPLER_TYPE=const
and JAEGER_SAMPLER_PARAM=1

**Comment by Haiba8** [comment]
I just see the ports 8080,9411,16686 & 14267 are in listening state. I tried by using JAEGER_SAMPLER_TYPE=const
and JAEGER_SAMPLER_PARAM=1 . Still I can't see any progress.
