### ISSUE TITLE
Should there be a default storage type in new OTelCollector based components?

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#2228]
As these components are being released in 2.x, we have the opportunity to revisit whether we should have a default storage type, and if so, whether it should be cassandra.

**Comment by yurishkuro** [comment]
+1 for no default.

**Comment by jpkrohling** [comment]
This is not applicable for the all-in-one deployment, I assume.

**Comment by pavolloffay** [comment]
Closing as it is a "low level" issue related to V2 which might take a different approach.
