### ISSUE TITLE
Query endpoint api/services returns 503

### ISSUE THREAD

**Issue by Ffavicon** [jaegertracing/jaeger#2245]
Query endpoint api/services returns 503 if i try to find spans.
Primary storage: Elasticsearch
![image](https://user-images.githubusercontent.com/45531613/81956289-cc0a6600-9613-11ea-91ef-95310e62c790.png)

How to solve it?

**Comment by yurishkuro** [comment]
It's coming from your Elastic backend: "all shards failed". Check if it's available and accessible from where jaeger-query runs.
