### ISSUE TITLE
Support ppc64le architecture build

### ISSUE THREAD

**Issue by Siddhesh-Ghadi** [jaegertracing/jaeger#2272]
Adding a travis-ci job which runs on ppc64le arch. Any thoughts on this?

**Comment by pavolloffay** [comment]
There have been already some attempts to do this https://github.com/jaegertracing/jaeger/search?q=ppc64le&type=Issues.

Now the makefile is refactored which should make it easy to add new architecture builds. Would you like to submit a PR?

**Comment by Siddhesh-Ghadi** [comment]
Sure. I will start working on it.

**Comment by Siddhesh-Ghadi** [comment]
Hi @pavolloffay,

Could community release a **multi-arch** `jaegertracing/protobuf:0.1.0` image which is required for `PROTO_GEN_TEST`? Currently the image is only available for amd64 and is resulting in `exec format error` on ppc64le architecture. [Log](https://travis-ci.org/github/aishwaryabk/jaeger/jobs/696431752#L7152)

Or should we only run unit test on ppc64le like mentioned in https://github.com/jaegertracing/jaeger/pull/1982#issuecomment-566980678
> 1. the extra time required to perform a build. Instead of running the whole build in a new arch, only the fast unit-tests should be executed

**Comment by pavolloffay** [comment]
Could you please open an issue or a PR to that repository with changes required to the dockerfile and build infra(if any)?
