### ISSUE TITLE
Jaeger client in C/C++

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#228]
Just booking a placeholder, as there is currently no active work on that.

Why it's important - many low level infra components are implemented in C/C++, we're missing the ability to integrate with them today. For example, there is [nginx instrumentation](https://github.com/rnburn/nginx-opentracing/tree/opentracing-api).

Refs:
  * [zipkin-cpp](https://github.com/flier/zipkin-cpp/blob/master/include/zipkin.h)
  * [lightstep-tracer-cpp](https://github.com/lightstep/lightstep-tracer-cpp)

**Comment by isaach1000** [comment]
I'd be interested in helping out with this, but what exactly is involved? I have taken a look at the other clients, but having a hard time discerning the key components. For example, it seems not all the IDL files are used in all of the clients. How does zipkin relate to the jaeger client, and is it necessary to implement zipkin support in order to move ahead with the jaeger implementation?

**Comment by isaach1000** [comment]
OK thanks. Will give it a shot.

**Comment by yurishkuro** [comment]
Do you want me to create a repository under jaegertracing?

NB: I added one more step above:
  * project structure, readme, license (APL2), travis build, code coverage

**Comment by isaach1000** [comment]
Please. I'll fork it once you do.

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/cpp-client

**Comment by rnburn** [comment]
Hey @isaachier just wanted to check in on this as some people were asking about using Jaeger for [nginx](https://github.com/rnburn/nginx-opentracing/issues/7).

Are you planning on binding to the [OpenTracing API](https://github.com/opentracing/opentracing-cpp)? I don't see any code for it in https://github.com/isaachier/cpp-client.

Also, just a suggestion: you may want to consider limiting your dependencies for the Jaeger client a little more. Requiring a large library like boost, for example, is likely to be an obstacle for projects like [envoy] to use it.

**Comment by isaachier** [comment]
As of now, this has been sort of a side project. I did see the OpenTracing API, but not sure if it is worth the headache of merging. If there is a good reason to, I will. Right now seems the C++ API is not widely used and not yet stable (see end of their README).

I have thought about the dependencies. In short, Boost is one of the few libraries I feel is indispensable. One strong reason for this leads from another large dependency that cannot be avoided: Apache Thrift. All of the Jaeger clients use Apache Thrift to communicate, and the generated Thrift code depends on Boost.

About dependencies in general, it will depend how you use the library. I intend on exposing a simple C header for C clients or anyone else who does not want the included headers from Boost etc. That way, it is only required to link to the few Boost libraries (i.e. thread, asio, etc.) that are not header-only.

**Comment by rnburn** [comment]
@isaachier We just released version 1.0 of the C++ OpenTracing API. While it might evolve somewhat, the expectation is to keep it as stable as possible. I wrote that README; the section you're talking about was copied over from the [OpenTracing Go API](https://github.com/opentracing/opentracing-go#api-compatibility).

I'm expected to release nginx OpenTracing bindings soon into opentracing-contrib, and we plan to make bindings available for envoy [as well](https://github.com/envoyproxy/envoy/issues/1196), so if you bind to them you'll be able to make the client work with those projects. It would also be more aligned with what the other Jaeger client libraries do.

**Comment by isaachier** [comment]
OK great. I am not opposed in any way to merging using the OpenTracing C++ API, especially if it means we can leverage future instrumentations of C/C++ based projects. I'll take a look at the dependencies again and see what I need vs what is truly important. The hardest part here is networking using sockets on different platforms without a convenient wrapper like Boost ASIO.

**Comment by isaachier** [comment]
I pushed a commit with some initial work. As of now, doesn't look too difficult to implement OpenTracing interfaces using existing code.

**Comment by yurishkuro** [comment]
The official client is available from https://github.com/jaegertracing/cpp-client

**Comment by maniaabdi** [comment]
Hi, is there any sample/tutorual on instrumenting a c++ code with Jaeger-cpp-client?

**Comment by yurishkuro** [comment]
@maniaabdi check https://github.com/opentracing/opentracing-cpp/tree/master/example

Jaeger-specific part would be only initialization.
