### ISSUE TITLE
Issues with ES 7.4.2

### ISSUE THREAD

**Issue by pathikritmodak** [jaegertracing/jaeger#2284]
**Describe the bug**

Jaeger query is failing to get the spans in the UI because of the following error. 

`Jun  8 12:51:50 ip-172-31-57-156 jaeger-query[7223]: {"level":"error","ts":1591620710.104769,"caller":"app/http_handler.go:430","msg":"HTTP handler, Internal Server Error","error":"Search service failed: json: cannot unmarshal object into Go struct field SearchHits.hits.total of type int64","errorVerbose":"json: cannot unmarshal object into Go struct field SearchHits.hits.total of type int64\nSearch service failed\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*ServiceOperationStorage).getOperations\n\t/go/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/service_operation.go:121\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanReader).GetOperations\n\t/go/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/reader.go:256\ngithub.com/jaegertracing/jaeger/storage/spanstore/metrics.(*ReadMetricsDecorator).GetOperations\n\t/go/src/github.com/jaegertracing/jaeger/storage/spanstore/metrics/decorator.go:114\ngithub.com/jaegertracing/jaeger/cmd/query/app/querysvc.QueryService.GetOperations\n\t/go/src/github.com/jaegertracing/jaeger/cmd/query/app/querysvc/query_service.go:86\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).getOperationsLegacy\n\t/go/src/github.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:161\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/lib/go-1.13/src/net/http/server.go:2007\ngithub.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5\n\t/go/src/github.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:140\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/lib/go-1.13/src/net/http/server.go:2007\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/lib/go-1.13/src/net/http/server.go:2007\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux/mux.go:212\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1\n\t/go/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/compress.go:148\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/lib/go-1.13/src/net/http/server.go:2007\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\t/go/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/go-1.13/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/lib/go-1.13/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357","stacktrace":"github.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).handleError\n\t/go/src/github.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:430\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).getOperationsLegacy\n\t/go/src/github.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:168\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/lib/go-1.13/src/net/http/server.go:2007\ngithub.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5\n\t/go/src/github.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:140\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/lib/go-1.13/src/net/http/server.go:2007\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/lib/go-1.13/src/net/http/server.go:2007\ngithub.com/jaegetracing/jaeger/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux/mux.go:212\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1\n\t/go/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/compress.go:148\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/lib/go-1.13/src/net/http/server.go:2007\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\t/go/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/go-1.13/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/lib/go-1.13/src/net/http/server.go:1890"}`

Also I see that curator is broken because v5.4.1 isn't compatible with 7.4.2.

` INFO      Preparing Action ID: 1, "delete_indices"
 ERROR     Elasticsearch version 7.4.2 incompatible with this version of Curator (5.4.1)`

**Expected behavior**
Jaeger UI should show the spans and also curator is able to delete older indexes.

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: v1.17.1
 - Deployment: EC2

**Comment by pathikritmodak** [comment]
Just to give more information that it was running fine with ES 6.8. This has started happening post 7.4.2 upgrade.

**Comment by pavolloffay** [comment]
Could you please paste the logs of Jaeger binaries when they started? Jaeger should detect ES version automatically and log it. There is also a flag to specify the version explicitly `--es.version=7`. Could you please try that?

**Comment by pathikritmodak** [comment]
Thanks, specifying the version explicitly solves the problem. 
But still the curator issue remains, I believe it's probably needed to pull the latest curator version to solve that problem.
