### ISSUE TITLE
Rollover API support listed as experimental, is it safe for production?

### ISSUE THREAD

**Issue by JayG-EBSCO** [jaegertracing/jaeger#2287]
We have recently have upgraded our Jaeger deployment to 1.18. As part of the deployment we are looking into using the Elasticsearch rollover feature. We have however noticed that in parts of the documentation, this is marked as experimental. This has brought up concern about using it in a production deployment. Our plan is currently to utilize it based on the max_size option to keep our indices below a specified size. We have a test cron job that runs every 15 min against the AWS manged ES cluster.

Is this feature one that is safe for production deployment? Are there any concerns we should keep in mind because of the experimental label?

**Comment by pavolloffay** [comment]
Rollover is a stable feature. It's safe to be used in a production environment. I will remove the experimental labels from flags.

Where in the docs did you see experimental?

**Comment by JayG-EBSCO** [comment]
> Rollover is a stable feature. It's safe to be used in a production environment. I will remove the experimental labels from flags.
> 
> Where in the docs did you see experimental?

Great to hear that it is stable.

It is listed as experimental in several places on the CLI flags page within the documentation: https://www.jaegertracing.io/docs/1.18/cli/#jaeger-collector as an example.

**Comment by pavolloffay** [comment]
It has been removed from the CLI flags. Where else did you see it?

**Comment by JayG-EBSCO** [comment]
> It has been removed from the CLI flags. Where else did you see it?

Noted here within this text as an example.
https://www.jaegertracing.io/docs/1.18/cli/#jaeger-collector-elasticsearch


--es.use-aliases | false
-- | --
(experimental) Use read and write aliases for indices. Use this option with Elasticsearch rollover API. It requires an external component to create aliases before startup and then performing its management. Note that es.max-span-age is not taken into the account and has to be substituted by external component managing read alias.

**Comment by pavolloffay** [comment]
That is derived from flags, It should be fixed now by #2290.


thanks for reporting
