### ISSUE TITLE
Multiarch docker images

### ISSUE THREAD

**Issue by rur0** [jaegertracing/jaeger#2292]
## Requirement - what kind of business use case are you trying to solve?
Ability to utilize multiarch images

## Problem - what in Jaeger blocks you from solving the requirement?
I have a rpi k3s (arm64) cluster that I use to run a web app written in golang, and I would like to use jaeger for tracing on it. I have compiled jaeger-operator and got it running on the cluster, however when it pulls the main jaeger docker image- it errors out with 'exec format'.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Build and upload multiarch images to official docker repo

**Comment by yurishkuro** [comment]
Are you referring to a single image somehow being multi-arch, or to multiple images? There would be a lot of manual work on creating individual docker hub repo for each one permutation.

**Comment by pavolloffay** [comment]
@rur0 thanks for creating the issue. 

This has been created from https://github.com/jaegertracing/jaeger-operator/issues/1086.

I think he is referring to https://docs.docker.com/buildx/working-with-buildx/. It seems that a single image can have multiple architectures. When the client requests the image from the registry it gets multiple manifests. Then the client chooses the right image.

Other resources: https://www.youtube.com/watch?v=SYJgkkjqd7s

@rur0 would you like to contribute this?

**Comment by rur0** [comment]
@pavolloffay Yes

**Comment by Jingzhao123** [comment]
@MrXinWang
