### ISSUE TITLE
Elasticsearch URL not being accepted properly

### ISSUE THREAD

**Issue by madeinindiadot** [jaegertracing/jaeger#2298]
**Describe the bug**

My Elasticsearch url with trailing "/" is not being accepted by Jaeger

```
docker run --rm  -it \
  --name jaeger-collector  \
  -e SPAN_STORAGE_TYPE=elasticsearch  \
  -e ES_SERVER_URLS="https://elastic.search.test.com:443/es/"  \
  -e ES_USERNAME=elastic  -e ES_PASSWORD=elastic   \
  -p 14267:14267   -p 14268:14268   -p 14250:14250 \
  -e JAEGER_DISABLED=true -e LOG_LEVEL=debug \
  jaegertracing/jaeger-collector:1.18 --es.tls.skip-host-verify=true
```

"msg":"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: no Elasticsearch node available"

**To Reproduce**
1. Have a elasticsearch URL as "https://elastic.search.test.com/es/" 
2. Ensure that "/" is present at the end in URL "https://elastic.search.test.com/es/" 
3. "https://elastic.search.test.com/es" (URL without slash) should return 404
4. "https://elastic.search.test.com/es/" (URL with slash) should return 200 OK

**Expected behavior**

Jaeger is removing the trailing slash even though the ES_SERVER_URLS is given with "https://elastic.search.test.com/es/" The HEAD request is going to "https://elastic.search.test.com/es" (without slash) instead of "https://elastic.search.test.com/es/" (with trailing slash)

**Screenshots**

**Version (please complete the following information):**
 - OS: linux
 - Jaeger version: 1.18
 - Deployment: Docker

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.
Jaeger documentation mentions to provide complete ES url. Provided the same but the trailing slash is being removed as part of initial health check and its failing to establish connection with ES

Ensure that "https://elastic.search.test.com/es"(without trialing slash) doesn't forward request to "https://elastic.search.test.com/es/"(with trailing slash)

**Additional context**

**Comment by pavolloffay** [comment]
As far as I know Jaeger does not remove any parts of the ES URL. Maybe the ES client https://github.com/olivere/elastic does.

Once you set `https://elastic.search.test.com/es"` (without `/`) did it work?

**Comment by madeinindiadot** [comment]
Can you explain the error msg "failed to create primary Elasticsearch client: health check timeout: no Elasticsearch node available" -> what exactly does health check timeout mean? is it an error from elastic or jaeger. coz in the jaeger collector debug logs i am able to see that (trailing /) is missed

**Comment by madeinindiadot** [comment]
@pavolloffay Once you set https://elastic.search.test.com/es" (without /) did it work?

The ES (without /) returns a 404 not found. So the health check is failing and it doesnt work. In jaeger logs, I see the following

,"msg":"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: Head \"https://elastic.search.test.com/es\": x509: certificate signed by unknown authority: no Elasticsearch node available"

**My Config:**
storage:
    type: elasticsearch
    options:
      es:
       server-urls: https://elastic.search.test.com/es/

you can see the URL in config has trailing slash whereas the logs show a HEAD request without slash

**Comment by jpkrohling** [comment]
Is this about TLS? If you use an Elasticsearch instance without TLS configured, are you able to access it? I just tried it here, and it seems to work for me:

```console
$ curl http://192.168.2.114:9200
{
  "name" : "guarana",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "PlZra6E2SGKxbgHBljxd_w",
  "version" : {
    "number" : "7.9.1",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "083627f112ba94dffc1232e8b42b73492789ef91",
    "build_date" : "2020-09-01T21:22:21.964974Z",
    "build_snapshot" : false,
    "lucene_version" : "8.6.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

$ docker run --rm -it \
--name jaeger-collector \
-e SPAN_STORAGE_TYPE=elasticsearch \
-e ES_SERVER_URLS="http://192.168.2.114:9200" \
-p 14267:14267 -p 14268:14268 -p 14250:14250 \
-e JAEGER_DISABLED=true -e LOG_LEVEL=debug \
jaegertracing/jaeger-collector:1.18
```

**Comment by madeinindiadot** [comment]
> Is this about TLS? If you use an Elasticsearch instance without TLS configured, are you able to access it? I just tried it here, and it seems to work for me:
> 
> ```
> $ curl http://192.168.2.114:9200
> {
>   "name" : "guarana",
>   "cluster_name" : "elasticsearch",
>   "cluster_uuid" : "PlZra6E2SGKxbgHBljxd_w",
>   "version" : {
>     "number" : "7.9.1",
>     "build_flavor" : "default",
>     "build_type" : "tar",
>     "build_hash" : "083627f112ba94dffc1232e8b42b73492789ef91",
>     "build_date" : "2020-09-01T21:22:21.964974Z",
>     "build_snapshot" : false,
>     "lucene_version" : "8.6.2",
>     "minimum_wire_compatibility_version" : "6.8.0",
>     "minimum_index_compatibility_version" : "6.0.0-beta1"
>   },
>   "tagline" : "You Know, for Search"
> }
> 
> $ docker run --rm -it \
> --name jaeger-collector \
> -e SPAN_STORAGE_TYPE=elasticsearch \
> -e ES_SERVER_URLS="http://192.168.2.114:9200" \
> -p 14267:14267 -p 14268:14268 -p 14250:14250 \
> -e JAEGER_DISABLED=true -e LOG_LEVEL=debug \
> jaegertracing/jaeger-collector:1.18
> ```

This is not TLS, the TLS verify has been skipped. Its about the trailing slash at the end of the elastic URL being removed when establishing connectivity

**Comment by madeinindiadot** [comment]
@pavolloffay Once you set https://elastic.search.test.com/es" (without /) did it work?

The ES (without /) returns a 404 not found. So the health check is failing and it doesnt work. In jaeger logs, I see the following

,"msg":"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: Head "[https://elastic.search.test.com/es\](https://elastic.search.test.com/es%5C)": x509: certificate signed by unknown authority: no Elasticsearch node available"

My Config:

storage:
    type: elasticsearch
    options:
      es:
       server-urls: https://elastic.search.test.com/es/
you can see the URL in config has trailing slash whereas the logs show a HEAD request without slash

**Comment by madeinindiadot** [comment]
Basically I want Jaeger to accept "https://elastic.search.test.com/es**/**"

**Comment by yurishkuro** [comment]
As Pavol said, Jaeger does not do anything with the URL, we pass it to ES driver and if that's doing something to the URL we can't fix that. Having said that, the fact that your setup _requires_ a training slash sounds like a reverse proxy issue rather than ES. The following requests with or without trailing slash work just fine against ES:
```
curl http://192.168.2.114:9200
curl http://192.168.2.114:9200/
```

**Comment by madeinindiadot** [comment]
ok looks like the elastic driver library is doing it.
