### ISSUE TITLE
gRPC plugin archive storage support

### ISSUE THREAD

**Issue by m8rge** [jaegertracing/jaeger#2299]
## Requirement - what kind of business use case are you trying to solve?

Existing Elasticsearch and Cassandra as archive storage do not suit me. I want to use grpc plugin as archive storage.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently, grpc plugin can't be use as archive storage. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I propose archive storage support in grpc plugin.

## Any open questions to address

I have following options:

1. Create another namespace `grpc-archive-storage-plugin` in addition to existing `grpc-storage-plugin` and duplicate all options (`binary`, `configuration-file`, `log-level`). This will issue another process in addition to existing `grpc-storage-plugin.binary`. This is most flexible than next option.
2. Implement ArchiveFactory interface in shared.grpcClient with modifying storage.proto in some way...

Which option I should follow?

**Comment by yurishkuro** [comment]
I like option 1, but not sure how compatible it is with the existing setup, because the type of storage can only be selected once in Jaeger today, via SPAN_STORAGE_TYPE. In other words, you cannot mix different implementations of primary and archive storage.
