### ISSUE TITLE
"process is empty for the span" errors

### ISSUE THREAD

**Issue by nicks** [jaegertracing/jaeger#2300]
**Describe the bug**

I'm trying to set up Jaeger for the first time and getting log errors that look like this

> {"level":"error","ts":1592618224.399752,"caller":"app/span_processor.go:138","msg":"process is empty for the span","stacktrace":"github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:138\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:35\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:175\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:75\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\tgithub.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:77"}

Can you help me understand what this error means or what I can do to diagnose it further? 

It's not clear to me if this is a problem with how my app is using the trace API, or a problem with opentelemetry, or a problem with Jaeger

**To Reproduce**
1. Run Jaeger
2. Run an opentelemetry collector that exports to jaeger
3. Send a span to the opentelemetry collector

**Expected behavior**
No errors

**Screenshots**
Here's a complete log dump of both the jaeger server and the opentelemetry collector, which included the command-lines I'm using to run them
https://cloud.tilt.dev/snapshot/AaS26-4LxyiPB-GVtMw=

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.18
 - Deployment: Docker (jaegertracing/all-in-one:1.18)

**Comment by yurishkuro** [comment]
Don't know what the root cause is, but the span is missing critical data, the Process section that contains the service name. Somewhere in the pipeline the conversion from opentelemetry format is done incorrectly. Which client library are you using?

**Comment by nicks** [comment]
We're using opentelemetry-go

Ya, my reading of the spec here is that opentelemetry allows spans to omit the service group of attributes:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/README.md#service

The collector maps that Jaeger's process service name. But the process service name is required on the Jaeger side. 

I think the next step is for me to file a bug against opentelemetry-collector to either fill in a dummy service name before sending to Jaeger, or error out if it gets a spec like this. Does that sound right?

**Comment by yurishkuro** [comment]
In the Jaeger native SDKs the Process information is included only once per batch to minimize the overhead on the user application, but once the batch gets into the collector pipeline it's re-inflated into all spans. The same principle applies to OpenTelemetry data, so something is not doing it correctly.

**Comment by nicks** [comment]
thanks! That's helpful. I filed this bug against opentelemetry: https://github.com/open-telemetry/opentelemetry-collector/issues/1160

I have a pretty good isolated repro case that just uses off-the-shelf opentelemetry and jaeger sample code, but it will take me some time to pull out all the code/config files.

I'm currently leaning towards this being a bug in the opentelemetry-collector, but it might also be some misunderstanding in the protocol between the two. feel free to close if you agree.

**Comment by nicks** [comment]
This has been fixed upstream, thanks for your help!
