### ISSUE TITLE
how to run jaeger  binary executable without docker

### ISSUE THREAD

**Issue by sanjaychakravorty** [jaegertracing/jaeger#2304]
i have downloaded all Jaeger binaries in folder "folder_jaeger" and trying to execute like this
D:\\folder_jaeger\jaeger-all-in-one.exe using powershell
but i am getting below error message.kindly help and provide workable solution.

> jaeger-all-in-one.exe : The term 'jaeger-all-in-one.exe' is not recognized as the name of a cmdlet, function, script
> file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
> and try again.
> At line:1 char:1
> + jaeger-all-in-one.exe
> + ~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (jaeger-all-in-one.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

**Comment by jan25** [comment]
@sanjaychakravorty Can you try `jaeger-all-in-one --collector.zipkin.http-port=9411`? (based on https://www.jaegertracing.io/docs/1.18/getting-started/#all-in-one)

**Comment by jpkrohling** [comment]
I don't think any of the maintainers have a Windows machine readily available, so, we rely on help from the wider community to reproduce and fix this.

**Comment by alanisaac** [comment]
This looks like a [common PowerShell error](https://stackoverflow.com/questions/24156451/powershell-the-term-is-not-recognized-as-cmdlet-function-script-file-or-operable) to me.  If you're running `jaeger-all-in-one.exe` and seeing this error, try prefixing it with `./`:

```powershell
./jaeger-all-in-one.exe
```

Just to make sure, I pulled down the [1.18.1 release](https://github.com/jaegertracing/jaeger/releases/tag/v1.18.1) for Windows and was able to run `./jaeger-all-in-one.exe` fine on my Win10 machine.

**Comment by SanketNeema** [comment]
the following command I am using to start Jaeger without docker.
1. .\jaeger-all-in-one --collector.zipkin.host-port=:9411
2. test I am using Postman http://localhost:14250 hit.
