### ISSUE TITLE
add prometheus metrics to the hotrod example app

### ISSUE THREAD

**Issue by ghostsquad** [jaegertracing/jaeger#2305]
This is a request to add `/metrics` endpoint exposing prometheus metrics, to make this a complete demo of logs, tracing and metrics.

**Comment by yurishkuro** [comment]
Metrics are already available: https://github.com/jaegertracing/jaeger/blob/master/examples/hotrod/README.md#metrics

**Comment by ghostsquad** [comment]
Oh thanks! I was expecting them to be on the 8080 port
