### ISSUE TITLE
Add TraceID to Logs in HotRod Example Application

### ISSUE THREAD

**Issue by ghostsquad** [jaegertracing/jaeger#2310]
This is a request to add the TraceID to logs for the HotRod application. This would allow for some cool demos, especially with Grafana 7.0 and it's support for unification of metrics, logs and jaeger tracing.

**Comment by pavolloffay** [comment]
Would you like to submit a patch for it?

**Comment by ghostsquad** [comment]
Ya. This would be a good exercise for me.
