### ISSUE TITLE
Buffer size for udp is too small

### ISSUE THREAD

**Issue by kbarukhov** [jaegertracing/jaeger#2331]
**Describe the bug**
Default buffer size for udp is too small. Because of that some udp-packets are dropped

**What troubleshooting steps did you try?**
We have quick fix for this issue. May be we should merge it?
https://github.com/ozonru/jaeger/blob/1.18-udp-buffer-size/cmd/agent/app/servers/thriftudp/transport.go#L90

**Comment by yurishkuro** [comment]
+1, please do a PR. Could you also provide more context - your setup, under what conditions you notice data loss, how did you arrive to the current buffer size? What is the default buffer size? Is it OS-dependent?

It may make sense to expose this parameter as configurable.

**Comment by kbarukhov** [comment]
With something like 1.2 million spans in second and about 5 Gbits total traffic we saw package dropping. Default buffer size is around 4 kB. Current size was found experimently) I'll test if these syscalls work on windows and do a PR

**Comment by yurishkuro** [comment]
"1.2 million spans/sec" for one agent? Sweet.

**Comment by mkabischev** [comment]
Noo, 1.2kk spans is total throughput for our setup. We have some instances with "heavy" services that send a lot of telemetry and that caused this problem.
