### ISSUE TITLE
error=true tag search no result

### ISSUE THREAD

**Issue by zziawan** [jaegertracing/jaeger#2332]
when some trace has error=true tag, they can be found by operation name, but when add error=true tag no result retrun. using error=true and operation=all also no result found 。jeager version 1.14 ,traces saved in momery。

**Comment by joe-elliott** [comment]
I am unable to reproduce.  I have tested in 1.14 and 1.18 using the jaeger-all-in-one.  Can you give more details?  

![image](https://user-images.githubusercontent.com/2272392/89844752-8265e480-db4a-11ea-8d3a-cee06636abfe.png)

Tests were done using the Grafana tns demo: https://github.com/grafana/tns/
