### ISSUE TITLE
Function in file with build tag shows as undefined

### ISSUE THREAD

**Issue by kbarukhov** [jaegertracing/jaeger#2340]
**Describe the bug**
Undefined function in file with build tag in continuous-integration/travis-ci/pr check

**To Reproduce**
I've made a PR with new function that depends on OS, so I have written build tags for linux and darwin and other systems
https://github.com/jaegertracing/jaeger/pull/2336/files#diff-e09bc7e5e0a1c73c957ea2e4243d019f
but some checks say that the function is undefined even though checks are on linux os
https://travis-ci.org/github/jaegertracing/jaeger/builds/706823926

**Expected behavior**
Defined function

**What troubleshooting steps did you try?**
Tried to run it on darwin and windows, everything works fine

**Additional context**
Do I have to fix something, change the code? I will appreciate if you could help me

**Comment by yurishkuro** [comment]
I don't have much experience with these, but perhaps it's being confused by multiple entires in the build tag (even though it seems valid syntax). Did you try dropping the suffix from linux/mac file and giving it `!windows` build tag? This is how we did it for one place in badger storage, see:
  * ./plugin/storage/badger/stats_linux.go
  * ./plugin/storage/badger/stats.go

**Comment by kbarukhov** [comment]
Thank you, it helped. I still don't understand the reason of the problem though
