### ISSUE TITLE
spans in kafka consume two times

### ISSUE THREAD

**Issue by spyvip** [jaegertracing/jaeger#2341]
**Describe the bug**
if we deploy two ingesters in k8s，spans in kafka will consume two times

**To Reproduce**
1. deploy two ingesters,two collectors in k8s
2.
3.

**Expected behavior**

spans in kafka should consume once

**Screenshots**
![image](https://user-images.githubusercontent.com/1212932/87258230-81eb1700-c4d4-11ea-9cd6-3f9743ac9bc3.png)

**Version (please complete the following information):**
 - OS: [Linux]
 - Jaeger version: [ 1.18]
 - Deployment: [ Kubernetes]

**What troubleshooting steps did you try?**

**Additional context**

**Comment by objectiser** [comment]
@spyvip How were the ingesters deployed? Did you use the jaeger operator, helm charts, something else?

Can you look at the flags supplied to the ingester in those pods and confirm whether the `--kafka.consumer.group-id` flag is passed with the same value for both pods?

**Comment by spyvip** [comment]
> jaeger operator,

@objectiser 

- use jaeger operator
-  we use default args, and no other setting。 

` --kafka.consumer.group-id` is `jaeger-ingester` by default in official website document

**Comment by pavolloffay** [comment]
Interesting the bottom span has suffix `_1` in the span ID.

**Comment by yurishkuro** [comment]
> Interesting the bottom span has suffix _1 in the span ID.

that's done at query time by the span id deduper

**Comment by spyvip** [comment]
sorry, now it is normal, may be out k8s problem
![trace-jaeger](https://user-images.githubusercontent.com/1212932/87614929-02637f00-c744-11ea-89e2-0c7003ab6bf1.png)
