### ISSUE TITLE
RUM (Real User Monitoring) ?

### ISSUE THREAD

**Issue by elgalu** [jaegertracing/jaeger#2344]
Does the Jaeger tracing ecosystem provide something like [Elastic APM RUM](https://www.elastic.co/guide/en/apm/agent/rum-js/master/intro.html) ?

**Comment by yurishkuro** [comment]
The page you link has practically zero information about what exactly E-APM supports w.r.t. RUM. It sounds more like metrics.

**Comment by elgalu** [comment]
Sorry, these provide better info:
https://www.elastic.co/guide/en/apm/agent/rum-js/master/intro.html
https://www.elastic.co/blog/performing-real-user-monitoring-rum-with-elastic-apm
https://github.com/elastic/apm-agent-rum-js

**Comment by yurishkuro** [comment]
Thanks for the links. The blog still sounds pretty confusing as to what exactly they are trying to do. You can certainly get traces into Jaeger like the ones they showed, if you instrument your frontend application. Jaeger itself does not provide instrumentation (it's not in the scope of the project), but you can use OpenTelemetry which has good support for JS and is natively integrated with Jaeger. As far as user activity metrics, and dimensions like geo locations - that's not what Jaeger is built for, I would point you to Grafana and Prometheus.
