### ISSUE TITLE
Inquiry About the Microservice Architecture Employed by `jaeger`

### ISSUE THREAD

**Issue by research-sudo** [jaegertracing/jaeger#2345]
I am a researcher investigating the open source projects that are designed by the microservice architectural style ([https://martinfowler.com/microservices/](url)). My preliminary investigation shows that the  **_jaeger_** project ([https://github.com/jaegertracing/jaeger](url)) is designed by the microservice architectural style. 

1. Can you please **_confirm_** if my interpretation that this project is designed by following the microservice architectural style is correct? Note that if the projects (e.g., frameworks or tools) support the development of microservices-based systems but themselves are not designed by following the microservice architectural style, please also clarify it?
2. If my interpretation is correct, what **_features_** or **_characteristics_** of the architecture of this open source project show that the microservice architectural style has been used?
3. **Optional Question**: Do you know any other open-source projects that are designed by following the microservice architectural style?

I would be greatly appreciative if you can kindly answer the three questions above.

**Comment by yurishkuro** [comment]
1. Yes
2. Jaeger backend is split into multiple components that generally perform a single function, like the agent, collector, ingester, indexer, and query-service. Each component is deployed and scaled independently of the others.
3. Thanos, Cortex.

**Comment by research-sudo** [comment]
Thank you so much Yuri

**Comment by research-sudo** [comment]
Could you please give me Thanos and Cortex link?

**Comment by yurishkuro** [comment]
https://github.com/thanos-io/thanos
https://github.com/cortexproject/cortex

**Comment by jpkrohling** [comment]
Glad to see you did open an issue with your questions, @research-sudo. For question 3, you might want to read on the evolution of istio, which started with a highly distributed architecture and has since switched to a less distributed one (named `istiod`), in name of performance.

**Comment by research-sudo** [comment]
@jpkrohling Thank you so much for your report.
