### ISSUE TITLE
ingester bulk write to elasticsearch

### ISSUE THREAD

**Issue by spyvip** [jaegertracing/jaeger#2346]
## Requirement - what kind of business use case are you trying to solve?

write spans to elasticsearch by bulk

## Proposal - what do you suggest to solve the problem or improve the existing situation?

![image](https://user-images.githubusercontent.com/1212932/87614839-c0d2d400-c743-11ea-90b3-c1e9b407a666.png)

**Comment by pavolloffay** [comment]
The spans to ES are written in bulks. The bulk processor is initialized when the ES client is created.
