### ISSUE TITLE
JaegerUI does not find any spans when using ElasticSearch backend

### ISSUE THREAD

**Issue by cappelaere** [jaegertracing/jaeger#2350]
**Describe the bug**
JaegerUI does not find any spans when using ElasticSearch backend.

**To Reproduce**
1. cd jaeger/crossdock; docker-compose -f jaeger-docker-compose.yml up
2. inject some spans from a jaeger-client
3. Try to search the traces/spans from JaegerGUI.  No services can be found.

**Expected behavior**
Services/Traces/Spans should be found in the GUI.
**Version (please complete the following information):**
 - OS: [OSX]
 - Jaeger version: [e.g. 1.8]
 - Deployment: [Docker]

**What troubleshooting steps did you try?**
Ran Jaeger all-in-one in docker.  Use client to send traces/spans.  JaergerGui works fine
Ran crossdock/jaeger-docker-compose.yml, JaegerGUI does not work anymore

**Comment by yurishkuro** [comment]
` jaeger/crossdock` is integration testing facility, it's not expected to server the UI.

**Comment by cappelaere** [comment]
I just wanted to demonstrate the way to reproduce the problem when using ES.  I cannot get the UI to retrieve any traces/spans.  If this is not a bug, how would you make it work?
Thanks.

**Comment by yurishkuro** [comment]
This sounds more like a typical networking issue, especially if you're trying to report spans from outside of docker-compose namespace. Try following https://www.jaegertracing.io/docs/1.18/troubleshooting/.

**Comment by cappelaere** [comment]
The spans get ingested properly. I see them in the log.  I can query them from Kibana.  I just can't query them from the JaegerGUI.  I am using a similar docker-compose.  Is the ES query very restricted that it would not match my spans?  How could I troubleshoot this a little more.
Many thanks,
Pat.

**Comment by pavolloffay** [comment]
If the reported spans have old timestamps then query will not find them. This can be configured by `--es.max-span-age`

**Comment by cappelaere** [comment]
This was it.  I am deeply grateful.  Thank you.
Pat.

**Comment by pavolloffay** [comment]
I am closing this as resolved. Please reopen if there are more issues.
