### ISSUE TITLE
Logs for Go application sidecar jaeger-agent

### ISSUE THREAD

**Issue by Althea01** [jaegertracing/jaeger#2351]
I have a jaeger-agent sidecar injected to my Go application and I just want to know if there's a way to tell if the sidecar is actually up and running.

**Comment by yurishkuro** [comment]
Agent writes logs to stdout. This repo does not dictate how you deploy the agent, and thus cannot help in locating the logs.

Is this about the agent deployed via Jaeger operator?

**Comment by jpkrohling** [comment]
There's a health check log entry stating whether the agent was able to startup or not. The agent is fully functional when it's able to talk to a collector, which might happen after it started up. Both conditions can be seen in the logs, and here's an example using the `business-application-injected-sidecar.yaml` from the Jaeger Operator:

```console
$ kubectl logs deployments/myapp -c jaeger-agent
2020/07/21 06:33:19 maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined
{"level":"info","ts":1595313199.1786742,"caller":"flags/service.go:116","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1595313199.1787896,"caller":"flags/admin.go:120","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1595313199.1788266,"caller":"flags/admin.go:126","msg":"Starting admin HTTP server","http-addr":":14271"}
{"level":"info","ts":1595313199.178838,"caller":"flags/admin.go:112","msg":"Admin server started","http.host-port":"[::]:14271","health-status":"unavailable"}
{"level":"warn","ts":1595313199.1788468,"caller":"reporter/flags.go:61","msg":"Using deprecated configuration","option":"jaeger.tags"}
{"level":"info","ts":1595313199.1792989,"caller":"grpc/builder.go:66","msg":"Agent requested insecure grpc connection to collector(s)"}
{"level":"info","ts":1595313199.179325,"caller":"grpc@v1.27.1/clientconn.go:106","msg":"parsed scheme: \"dns\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1595313199.180657,"caller":"command-line-arguments/main.go:78","msg":"Starting agent"}
{"level":"info","ts":1595313199.1807065,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1595313199.1807292,"caller":"app/agent.go:69","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1595313199.1815403,"caller":"dns/dns_resolver.go:212","msg":"ccResolverWrapper: sending update to cc: {[{10.244.0.8:14250  <nil> 0 <nil>}] <nil> <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1595313199.1815553,"caller":"grpc@v1.27.1/clientconn.go:948","msg":"ClientConn switching balancer to \"round_robin\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1595313199.1818345,"caller":"base/balancer.go:196","msg":"roundrobinPicker: newPicker called with info: {map[0xc0004981e0:{{10.244.0.8:14250  <nil> 0 <nil>}}]}","system":"grpc","grpc_log":true}
```

That said, we could be more explicit about the connection state... The last log entry is a bit cryptic to people who are not used to gRPC.

**Comment by Althea01** [comment]
I injected the sidecar using 
`"sidecar.jaegertracing.io/inject": "true"`
and the application is running fine, but I'm not able to access the jaeger-agent container.

**Comment by pavolloffay** [comment]
Is your application instrumented with OpenTracing and is it using Jaeger go client https://github.com/jaegertracing/jaeger-client-go?

**Comment by jpkrohling** [comment]
> but I'm not able to access the jaeger-agent container.

Not sure what you mean here. Are you unable to get the logs for the `jaeger-agent` container? Or is your application having trouble sending spans to the agent?

**Comment by Althea01** [comment]
It says that there's no container named "jaeger-agent" which confuses me. My application is using openCensus.

**Comment by jpkrohling** [comment]
> In that case, show us the output of `kubectl get pod <your-pod> -o yaml`.

**Comment by Althea01** [comment]
Oh, thank you, I noticed that the sidecar is not injected with that annotation.
