### ISSUE TITLE
Sanitize http handler jaeger spans in collector.

### ISSUE THREAD

**Issue by Amiedeep** [jaegertracing/jaeger#2352]
**Describe the bug**
When we set error tag on a span to string ("True", for example) or error message, Jaeger collector doesn't sanitize the tags to mark the span erroneous. This issue is present in opentracing-tutorials python exercise; More information could be found [here](https://github.com/yurishkuro/opentracing-tutorial/pull/66#discussion_r453933772).

Zipkin spans, for instance, already have their tags sanitized by Jaeger collector. 

**To Reproduce**
1. Create a span in a golang app.
2. Mark span erroneous using either `span.SetTag("error", "True")` or `span.SetTag("error", "error message")`
3. Jaeger UI doesn't highlight span as erroneous.

**Expected behavior**
Jaeger collector should mark span as erroneous. If there is a message in a error tag, it should be added to `error.message` field; like in zipkin handler.

**Screenshots**
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8849040/88042952-60d89500-cb6a-11ea-9b99-d48d50316fd9.png">

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/8849040/88042986-6f26b100-cb6a-11ea-95c2-3ed9369fdf0b.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8849040/88043020-7ea5fa00-cb6a-11ea-8f26-323d48c6666a.png">

**Version (please complete the following information):**
 - OS: MacOS Mojave 10.14.6 
 - Jaeger version: docker all-in-one 1.7
 - Deployment: docker all-in-one

**What troubleshooting steps did you try?**
Read the code. All handlers other than Zipkin doesn't have sanitizers.

**Additional context**
If adding sanitizers sounds reasonable to you; I will go ahead and create a pull request.

**Comment by yurishkuro** [comment]
My preference is to fix it in the Python client. Turns out it already has the logic for separating tag values by types, but for some reason it doesn't seem to work here: https://github.com/jaegertracing/jaeger-client-python/blob/d56ae3440424b9e10b2d6a400b821814751d8236/jaeger_client/thrift.py#L72

**Comment by yurishkuro** [comment]
Also, if someone is doing `span.SetTag("error", "True")` (with a string value), then that's just incorrect instrumentation and I don't think we need to fix that. Where did you find that example?

**Comment by Amiedeep** [comment]
It is because of jaeger version in requirements.txt, python client is not marking spans as erroneous. I will create a pull request for that in tutorials.

On second comment, zipkin sanitizer is marking spans erroneous when error is set to `"True"` and also adding another annotation when a message is send in error tag;  [Here](https://github.com/jaegertracing/jaeger/blob/master/cmd/collector/app/sanitizer/zipkin/span_sanitizer.go#L169) is the code.  

Also, shouldn't sanitizer be at collector level rather than in language client implementations?

**Comment by yurishkuro** [comment]
I am not strongly opposed to sanitizer, but in this case the issue is only with Python client that has full ability to set the tag as a proper Boolean already, so I would rather fix it at the source than put an extra overhead of collectors.

**Comment by Amiedeep** [comment]
This ticket can be closed now. I have raised a pull request in opentracing-tutorials to fix this issue.
