### ISSUE TITLE
Can we deploy jaeger components (collector/query/UI) as a binary in Linux VM instance

### ISSUE THREAD

**Issue by dinesh4747** [jaegertracing/jaeger#2353]
Can someone please guide on deploying jaeger (collector/query/UI) components on a bare metal VM with specific configuration files

**Comment by jpkrohling** [comment]
From my message to the mailing list:

There isn't much to say, other than that you just run the binaries directly, passing `--config-file` with the location of your configuration file.

I wrote a blog post some time ago specific to the deployment of Jaeger Agent on bare metal, and the same idea can be applied to all other components:

https://medium.com/jaegertracing/running-jaeger-agent-on-bare-metal-d1fc47d31fab
