### ISSUE TITLE
Jaeger UI (jaeger-query) bug - HTTP Error 431 when searching for long operation names

### ISSUE THREAD

**Issue by Saad-Hussain1** [jaegertracing/jaeger#2360]
**Describe the bug**
This is a bug with the UI (jaeger-query). When trying to search for traces after selecting operations with very long names from the left pane on the UI, some users are getting HTTP Error 431. (see screenshots below)

From https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431:
```
Servers will often produce this status if:
  - The Referer URL is too long
  - There are too many Cookies sent in the request
```

**To Reproduce**
Note: This only happens for some users. Not sure why.
1. Go to the Jaeger UI
2. From the left search pane, select a service + operation with very long names. In our case, the service name is 35 characters and the operation name is 191 characters.
3. Click "Find Traces". Some users will get a HTTP Error 431 at this point.

**Expected behavior**
Expected list of traces with the selected Service + Operation to display, as usually would after pressing "Find Traces".

**Screenshots**
![image](https://user-images.githubusercontent.com/44215800/88581152-be615b80-d01a-11ea-9ad3-10638c68b146.png)

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.13
 - Deployment: Kubernetes

**What troubleshooting steps did you try?**
Troubleshooting docs do not mention this issue. Tried searching online for general solutions to 431 error but found nothing that helped in this case.

As mentioned, from https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431:
```
Servers will often produce this status if:
  - The Referer URL is too long
  - There are too many Cookies sent in the request
```

If it were a problem with either of these, we would expect it to not work for any users. However it does work for some and not for others. Browsers are up to date. Tried with Firefox & Chrome, works for some users in both browsers and for other users neither browser works.

**Additional context**
Access to the UI is protected behind a simple reverse proxy server which authenticates a user with our organization's SSO and then proxies to jaeger-query in Kubernetes.

**Comment by yurishkuro** [comment]
Not commenting specifically on the 431 error, but you are using broken instrumentation if your operation names are so long and apparently include numeric IDs. Does your service really have 10,000 unique endpoints? Please refer to OpenTracing specification for guidelines on good operation names (key requirements: low cardinality).

**Comment by yurishkuro** [comment]
Also, Jaeger 1.13 is more than 1yr old, try the latest version.
