### ISSUE TITLE
Jaeger containers healthcheck support

### ISSUE THREAD

**Issue by dekimsey** [jaegertracing/jaeger#2361]
## Requirement - what kind of business use case are you trying to solve?

I would like to make my container depend on the successful start up of jager containers (agent for instance, but applies to all jaeger containers). In AWS ECS deployment is unable to perform a container-level healthcheck on the jaeger containers. So declaring my app to depend on the "HEALTHY" startup of a jaeger container is not possible at this time. Nor is ECS able to determine if the deployment completed successfully since it cannot healthcheck the app at startup.

## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger containers are stripped down and do not have a way to execute wget or curl to check the admin port. ECS needs a [command it can execute](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_healthcheck) in the container that will exit 0.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Rather than including curl or wget which would bloat the containers needlessly. Add a built-in command to jager binaries to check their respective health (taking a minimal/identical set of environment/arguments to be compatible). The idea being we can very easily just have jaeger check it's own health and exit 0 if successful.

```
jaeger-agent health [--admin.http.host-port] [--config-file]
Checks the local agent admin endpoint to verify health.
```

**Comment by dekimsey** [comment]
To be clear, while this is clearly possible via the admin endpoint with other tools (such as Consul), ECS itself doesn't support http requests as healthchecks and appears to require we shell-in to run a command in the container.

**Comment by yurishkuro** [comment]
Sounds like a reasonable solution. Are you interested in creating a pull request?

**Comment by dekimsey** [comment]
Yes, I think that's possible. Let me give it a go and we'll see what happens.

**Comment by jpkrohling** [comment]
> ECS itself doesn't support http requests as healthchecks and appears to require we shell-in to run a command in the container.

😯 Do they have a good reason for that? 

> Sounds like a reasonable solution. Are you interested in creating a pull request?

Sounds good to me as well.

**Comment by Dheerajcode2016** [comment]
What happened to this , can we do healthcheck now ?

**Comment by cmnemoi** [comment]
For anyone who got here from the Internet, accordingly to the documentation, with Jaeger v2 you can use the `/status` endpoint exposed on the port 13113 : https://www.jaegertracing.io/docs/2.11/deployment/#management-ports

**Comment by yurishkuro** [comment]
This issue is from 2020, I am curious if ECS still has this limitation that it needs a command to run instead of using an http health check. While this issue was resolved for Jaeger v1, there is no similar `status` command in Jaeger v2 (which is really OTEL Collector underneath).
