### ISSUE TITLE
How to specify port for cassandra schema job?

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/jaeger#2366]
https://github.com/jaegertracing/jaeger/blob/9529beec11a44bcb020d06fe3153de01d7115e55/plugin/storage/cassandra/schema/docker.sh#L7

related: https://github.com/jaegertracing/helm-charts/issues/137

How to specify non standard cassandra port?

Would it make sense and be possible to use `--cassandra.server`/`CASSANDRA_SERVER` and `--cassandra.port`/`CASSANDRA_PORT` for consistency with other components?

**Comment by pavolloffay** [comment]
The port can be specified in `CQLSH_HOST` e.g. `CQLSH_HOST=cassandra:123456`. 

> Would it make sense and be possible to use --cassandra.server/CASSANDRA_SERVER and --cassandra.port/CASSANDRA_PORT for consistency with other components?

It's not worth making this change since all dependent components would have to adapt to it.


Please reopen if the non standard C* port cannot be used via `CQLSH_HOST`
