### ISSUE TITLE
Fetch traces in batch for a duration

### ISSUE THREAD

**Issue by open-richard** [jaegertracing/jaeger#2368]
Hi guys,

I am trying to fetch all the traces from a service within a duration, e.g., 30 minutes.
So far, I can not find any API to do that. 
The way I did is just fetching traces in the way similar to what jaeger UI does by small duration with "start" and "end", sequentially. (because if I fetch within a long time, it will omit many traces)
But this can be sooooo slow.
Is there an API that enables me to do a long duration of trace fetch?

Any input would be appreciated!

Thanks,
Richard

**Comment by pavolloffay** [comment]
The query API supports search by duration, however it is span duration and not trace duration.

**Comment by open-richard** [comment]
> The query API supports search by duration, however it is span duration and not trace duration.

Thanks for your reply, @pavolloffay! 
Somehow I did not get a notification for your reply, sorry for the extra late response!

**Comment by jpkrohling** [comment]
I'm closing this, as your question has apparently been answered. Feel free to reopen if that's not the case.
