### ISSUE TITLE
Jaeger query doesn't propagate auth token on dependency endpoint

### ISSUE THREAD

**Issue by yoave23** [jaegertracing/jaeger#2369]
**Describe the bug**
Jaeger query doesn't propagate auth token on the `/dependencies` endpoint. Works fine others.
**To Reproduce**
1. Start jaeger-query with `QUERY_BEARER_TOKEN_PROPAGATION=true`
2. make a GET request to `/dependencies?endTs=?????????&lookback=???????` with an authorization token
3. inspect jaeger-query request headers 

**Expected behavior**
The dependency endpoint should propagate the auth token the same way it does on other endpoints (/operations, /traces, etc.)

**Version (please complete the following information):**
 - OS: [macOS]
 - Jaeger version: [1.8]
 - Deployment: [Docker]

**Additional context**
We're using ES as storage although it seems that it affects all storage types
looks like the issue (for ES storage) is located here: `plugin/storage/es/dependencystore/storage.go:84` where it uses the `DependencyStore`'s context (`Background` context) instead of the original one

**Comment by objectiser** [comment]
@yoave23 Thanks for reporting this - would you be interested in submitting a PR?

**Comment by yoave23** [comment]
@objectiser sure, on it

**Comment by yoave23** [comment]
@objectiser it seems like we need to change the `GetDependencies` in `storage/dependencystore/interface.go:32` in order to be able to use the real context. Does this sound like a valid approach? if not, would you mind recommending a different approach?

**Comment by objectiser** [comment]
@yoave23 Yes that is the right approach.

**Comment by objectiser** [comment]
@yoave23 Sorry should have realised earlier, but might be worth waiting for #2364 to merge (hopefully this week) - and then add your change on top?
