### ISSUE TITLE
Jaeger Cassandra deployment question

### ISSUE THREAD

**Issue by dinesh4747** [jaegertracing/jaeger#2372]
Hi Team 

I wanted to use Cassandra as a storage option for Jaeger and have built Cassandra in the Gcp instance group and looking for directions on right template and configmap/deployment yaml to connect jaeger collector pods to Cassandra instances

Any help or reference pointer would help in a big way 

@jpkrohling

**Comment by dinesh4747** [comment]
I was primarily looking for to deploy jager using the operator model within the GKE cluster and would wanted to transport data to Cassandra running on GCE/instance groups.

I have been stuck badly on getting right set of deployment artifacts/yamls to proceed further

Kindly let me know incase of any further questions

**Comment by dinesh4747** [comment]
My cassandra instance doesn't give a permission to create keyspace and schema by application and it needs to created along with the cassandra bootstrapping - I am just looking for directions on how do i proceed in this use-case @jpkrohling

**Comment by yurishkuro** [comment]
Creating the schema is described in the documentation: https://www.jaegertracing.io/docs/1.18/deployment/#cassandra

**Comment by jpkrohling** [comment]
In addition to what @yurishkuro mentioned, here are the sources for the create-schema job that the operator executes while bootstrapping the Cassandra cluster: https://github.com/jaegertracing/jaeger/tree/master/plugin/storage/cassandra/schema .
