### ISSUE TITLE
example [hotrod] can't work properly on my centos

### ISSUE THREAD

**Issue by chaseSpace** [jaegertracing/jaeger#2375]
```
[root@localhost hotrod]# docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                                                                  NAMES
2ee68ac63394        jaegertracing/all-in-one:latest   "/go/bin/all-in-on..."   52 minutes ago      Up 52 minutes       5775/udp, 5778/tcp, 14250/tcp, 6832/udp, 14268/tcp, 0.0.0.0:6831->6831/udp, 0.0.0.0:16686->16686/tcp   jaeger

[root@localhost hotrod]# pwd
/root/jaeger_test/jaeger-master/examples/hotrod
[root@localhost hotrod]# go run ./main.go all
2020-08-06T15:40:46.550+0800    INFO    cobra@v0.0.3/command.go:792     Using expvar as metrics backend
2020-08-06T15:40:46.551+0800    INFO    cobra@v0.0.3/command.go:762     Starting all services
2020-08-06T15:40:46.652+0800    INFO    frontend/server.go:67   Starting        {"service": "frontend", "address": "http://0.0.0.0:8080"}
2020-08-06T15:40:46.652+0800    INFO    route/server.go:57      Starting        {"service": "route", "address": "http://0.0.0.0:8083"}
2020-08-06T15:40:46.755+0800    INFO    customer/server.go:55   Starting        {"service": "customer", "address": "http://0.0.0.0:8081"}
```
I haven't changed anything. But hotrod‘s web-ui access is very slow, this is a local env. Addr is http://127.0.0.1:8080.
And the four button have no any reaction after click, I didn't see any requests from the browser network By F12.
I have tried running hotrod with docker image, same all.
So, where is the problem?

**Comment by chaseSpace** [comment]
Jaeger's webui access is ok, I saw a [frontend] service on jaeger webui.

**Comment by chaseSpace** [comment]
I have been solved the problem.
Try to access http://127.0.0.1:8080 is not load local resource completely, it will load `https://code.jquery.com/jquery-3.1.1.min.js`, 

Yes, If someone can not  access `https://code.jquery.com`, this example is failed!
Why not put the js file into local directory?

**Comment by yurishkuro** [comment]
It should be fine to serve jquery locally. Are you interested in creating a pull request?

**Comment by chaseSpace** [comment]
I have checked out the repo,  and find `index.html` was compressed into the code by the `esc`command, but I didn't find the code location of the `esc` command. Could you tell me?

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/jaeger/blob/4275e0c28e2a5f341f42deb9c20c872d8bdaf3ca/Makefile#L203

**Comment by chaseSpace** [comment]
Yes, I found this; but my question is where is the code location of `esc`, Do you mean `esc` is a Linux command?
After when I execute `make build-examples`, no output, and there is nothing changed.

**Comment by yurishkuro** [comment]
oh, no, it's a utility written in Go

https://github.com/jaegertracing/jaeger/blob/4275e0c28e2a5f341f42deb9c20c872d8bdaf3ca/Makefile#L374
