### ISSUE TITLE
jaeger-ingester high availability

### ISSUE THREAD

**Issue by spyvip** [jaegertracing/jaeger#2383]
I deploy 2 ingester instances, but we just found only one can work, we want to 2 ingester can both work。

**Comment by yurishkuro** [comment]
they can, but your Kafka topic must have at least as many partitions as there are ingesters.

**Comment by spyvip** [comment]
> ingesters

@yurishkuro  kafka topic have 12 partitions.   2 ingester instances , they cannot both work for average
