### ISSUE TITLE
Collector Sampling Configuration - Filter by tag

### ISSUE THREAD

**Issue by WorldIsM** [jaegertracing/jaeger#2386]
Hi, I would like to configure my collector not to store spans when it comes with a specific tag or tag value is like '%something%'. Is it possible to do so?

**Comment by pavolloffay** [comment]
No, this is not possible at the moment. This use case seems like a tail base sampling. The future version of Jaeger will be based on OpenTelemetry collector that support tail based sampling https://www.jaegertracing.io/docs/1.18/opentelemetry/
