### ISSUE TITLE
Duplicate traceID in different traces

### ISSUE THREAD

**Issue by defool** [jaegertracing/jaeger#2394]
## Requirement - what kind of business use case are you trying to solve?
Ensure unique traceID.

## Problem - what in Jaeger blocks you from solving the requirement?
Duplicate traceID in different traces.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Use new algorithm to generate unique traceID.

**Comment by yurishkuro** [comment]
Span IDs are scoped to a trace, they are not meant to be globally unique. Please explain what problems this is causing.

**Comment by defool** [comment]
I found the option `Gen128Bit` generates 128-bit traceID, which may solve my problem.

**Comment by yurishkuro** [comment]
Some Jaeger SDKs allow pluggable trace ID generators, so that you can implement your own, e.g. using some form of UUID to ensure uniqueness. Otherwise, by default the IDs are random and not guaranteed to be unique.
