### ISSUE TITLE
Plan for 1.19 release

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2398]
Are there any features / PRs we want to close before publishing 1.19? There is an annoying bug (https://github.com/jaegertracing/jaeger-ui/issues/589) in the UI that was fixed, but people keep running into it.

We could also do 1.18.2 with the recent UI, but there is a nice new feature for trace statistics in the UI (https://github.com/jaegertracing/jaeger-ui/pull/506).

@jaegertracing/jaeger-maintainers

**Comment by objectiser** [comment]
We were going to raise the topic on the next bi-weekly call. We thought it would be good to get #2387 and #2389 included in a `1.19` release.
