### ISSUE TITLE
Is there another way to monitor jaeger without prometheus 

### ISSUE THREAD

**Issue by yeqown** [jaegertracing/jaeger#2405]
there's some resistance for me to using `Prometheus`, my question as the title describes. Could I have another way to monitor jaeger?

thanks to your help ~

**Comment by jpkrohling** [comment]
What do you want to use instead? The `/metrics` endpoint is compatible with OpenMetrics, and can be read by most modern monitoring solutions. We also have a health check port that you can use for simple ping-like monitoring, like what Nagios would use.

**Comment by yeqown** [comment]
Actually, I'm finding a way to use `/metrics` endpoint by `Grafana` directly ~, is this possible? I don't need all indicators in `/metrics`

**Comment by jpkrohling** [comment]
@joe-elliott should correct me if I'm wrong, but isn't Grafana "just" a way to plot data (ie, dashboard)? You'd still need a Prometheus as a data source for Grafana.

But let me confirm something: you are talking about monitoring *Jaeger*, not your instrumentation applications, right?

**Comment by joe-elliott** [comment]
Correct.  Grafana only plots data, it does not scrape metrics, store them or provide a query api.  Prometheus is a fantastic solution for this, but like @jpkrohling said there should be a lot of options to scrape and store an OpenMetrics endpoint.

Grafana supports most popular time series databases out of the box so regardless of what you choose @yeqown you should be able to visualize it with Grafana.

**Comment by yeqown** [comment]
@jpkrohling right, I'm talking about monitoring `Jaeger`. Thank you all to resolve my confusion @jpkrohling @joe-elliott and I  have learned some useful knowledge about OpenMetrics. The way to resolve my question is choosing an option to scrape `/metrics` endpoint... right?
