### ISSUE TITLE
Does Jaeger OpenTelemetry support Elasticsearch 7?

### ISSUE THREAD

**Issue by Hongbo-Miao** [jaegertracing/jaeger#2407]
In current Jaeger OpenTelemetry docker compose example
https://github.com/jaegertracing/jaeger/blob/master/crossdock/jaeger-opentelemetry-docker-compose.yml

it is using Elasticsearch 6:

```yml
image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.3
```

I saw it is using OpenTelemetry version images for Jaeger:

- jaegertracing/jaeger-opentelemetry-collector
- jaegertracing/jaeger-opentelemetry-agent

I succeed testing on elasticsearch-oss 6.8.3 and 6.8.12, but failed upgrading to 7.0.0 and 7.9.0, got error:

```json
{
  "data": null,
  "total": 0,
  "limit": 0,
  "offset": 0,
  "errors": [
    {
      "code": 500,
      "msg": "search services failed: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]"
    }
  ]
}
```

I tried to upgrading to Elasticsearch 7 for a while, but no luck.
So just wonder does Jaeger OpenTelemetry currently support Elasticsearch 7? cc author @pavolloffay 

If it does, it would be very helpful to upgrade the example docker-compose.yml to use Elasticsearch 7. Thanks!

**Comment by pavolloffay** [comment]
hi @Hongbo-Miao the Jaeger OTEL and main Jaeger version support ES 5.x, 6.x and 7.x. 

There was a bug, I have submitted a fix https://github.com/jaegertracing/jaeger/pull/2409. Tve version bump in compose and integration tests can be done in a separate PR.

**Comment by Hongbo-Miao** [comment]
Thank you sooo much for the help @pavolloffay !
Really appreciate your time and the contributions on Jaeger OTEL

**Comment by Hongbo-Miao** [comment]
Confirmed, test latest images, and works with elasticsearch-oss:7.9.0
Thanks a lot!
