### ISSUE TITLE
Positive confirmation that Agent made a connection to Collector

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2410]
We should investigate whether it's possible to log a less cryptic message when the agent connects to the collector. Right now, the only indication that it happened is this message:

```
{"level":"info","ts":1598254766.3977652,"caller":"base/balancer.go:196","msg":"roundrobinPicker: newPicker called with info: {map[0xc000330270:{{:14250  <nil> 0 <nil>}}]}","system":"grpc","grpc_log":true}
```

**Comment by BernardTolosajr** [comment]
Im not sure if we can use the [connectivity semantics for gRPC](https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md) for this.

**Comment by jpkrohling** [comment]
From your link, it makes me believe that we could use [`GetState()`](https://godoc.org/google.golang.org/grpc#ClientConn.GetState) or [`WaitForStateChange()`](https://godoc.org/google.golang.org/grpc#ClientConn.WaitForStateChange)?

**Comment by varunpurohit76** [comment]
Hi guys! can i pick this up?

**Comment by BernardTolosajr** [comment]
> From your link, it makes me believe that we could use [`GetState()`](https://godoc.org/google.golang.org/grpc#ClientConn.GetState) or [`WaitForStateChange()`](https://godoc.org/google.golang.org/grpc#ClientConn.WaitForStateChange)?

Yes, we can use the GetState to get the current status and WaitForStateChange for status changes.

**Comment by jpkrohling** [comment]
Would you be able to send a PR with your proposal? It's easier to test it like that ;-)

**Comment by BernardTolosajr** [comment]
> Would you be able to send a PR with your proposal? It's easier to test it like that ;-)

Sure, let me PR my proposal. thank you ;-)
