### ISSUE TITLE
Through jaeger-UI query, very slow

### ISSUE THREAD

**Issue by kakaNo1** [jaegertracing/jaeger#2412]
Deploy through Docker:

jaegertracing/jaeger-query:1.17
jaegertracing/jaeger-collector:1.17
jaegertracing/jaeger-agent:1.17
elasticsearch:7.6.2  *   3

I set up elasticSearch Cluster for 3 sets and set it up
"number_of_shards" : "1",
"number_of_replicas" : "2"

But with a Jaeger-UI query, it can be slow, sometimes waiting more than five minutes, and I'm confused

**Comment by jpkrohling** [comment]
What are the exact commands you are using to start the containers? Are you using docker-compose, or plain docker?

**Comment by jpkrohling** [comment]
@kakaNo1 was it a problem on your side? I would appreciate if you could provide more information, as others might face this as well in the future :-)

**Comment by kakaNo1** [comment]
> @ kakaNo1在您这边有问题吗？如果您能提供更多信息，我们将不胜感激，因为将来其他人也可能会遇到此问题:-)

collector
docker run -d --name jaeger-collector --rm  -e ES_USE_ALIASES=true -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://xxxxx:9200 -p 14267:14267 -p 14268:14268 -p 9411:9411 jaegertracing/jaeger-collector:1.17

query
docker run -d --name jaeger-query --rm  -e ES_USE_ALIASES=true -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://xxxxx:9200 -p 16686:16686/tcp jaegertracing/jaeger-query:1.17

agent
docker run   -d  --name jaeger-agent --restart=always -p 5775:5775/udp   -p 6831:6831/udp   -p 6832:6832/udp   -p 5778:5778/tcp   jaegertracing/jaeger-agent:1.17   --collector.host-port=xxxxx:14267

**Comment by herbguo** [comment]
Hello, I would like to know if this issue has been resolved. I am currently encountering the same issue as jaeger query, which has a slow query speed from ES and increased bulk_ Worker is not good either. Is it because the data volume in ES is too large or the parameters are not effective?
