### ISSUE TITLE
Use bot account to publish Docker images

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2422]
@jpkrohling I noticed that since 1.19 the images are published "by you" on Docker Hub, which is a dubious improvement over previous state where they from Won's account.

What do we need to do to use the `jaegertracingbot` account?

![image](https://user-images.githubusercontent.com/3523016/91366693-72990200-e7d2-11ea-9978-03eab1da89c3.png)

**Comment by yurishkuro** [comment]
Maybe it's these settings in Travis. If so, I can update them to the bot account.

![image](https://user-images.githubusercontent.com/3523016/91366930-1682ad80-e7d3-11ea-84f2-d131e39062e3.png)

Regarding the "all branches" setting - couldn't someone just open a PR with an echo statement and steal the pwd?

**Comment by jpkrohling** [comment]
Yes, sorry, the problem with #1952 was likely that the account it used had expired credentials or not sufficient rights. I removed the credentials from `.travis.yaml`, as it's far easier to just replace the env vars in the job setting than to commit a new version of the file. The next step is indeed to replace the credentials in the settings to use the bot's account. Do you have access to those credentials?

> Regarding the "all branches" setting - couldn't someone just open a PR with an echo statement and steal the pwd?

Travis jobs runs against people's forks, so, it would print what people have in their fork's settings. It's similar to what happens between `DOCKER_PASS` being declared in `.travis.yaml` and being used in the scripts: it's decrypted using a key stored as env var, which is set by repo. People echo'ing the private key in a PR would echo their own fork's private key.

I believe that Travis has a second layer of security, where they would just filter out the values for env vars declared in the job, like it has for env vars declared in `.travis.yaml`: 

![image](https://user-images.githubusercontent.com/13387/91413202-0dcdbe00-e84b-11ea-8d2d-a50d2e041030.png)

**Comment by yurishkuro** [comment]
> Travis jobs runs against people's forks, so, it would print what people have in their fork's settings.

But the password would be set in the central Travis job, nothing from the fork. Still feels like a security gap, even if travis obfuscates stdout - there are other ways to grab the value, e.g. by sending it to some website via POST request.

**Comment by yurishkuro** [comment]
I updated job settings to use jaeger bot credentials.

**Comment by yurishkuro** [comment]
Fixed

![image](https://user-images.githubusercontent.com/3523016/91470802-2cd84a00-e863-11ea-876b-876231489bec.png)

**Comment by jpkrohling** [comment]
> there are other ways to grab the value, e.g. by sending it to some website via POST request

Well, sure, if we merge such code. But the same would happen with the password set in `.travis.yaml`. We just need to be careful not to merge PRs that would leak the credentials ;-)

**Comment by yurishkuro** [comment]
I wasn't referring to merged PRs, but to new PRs that run CI. People are free to change anything in those PRs, including any steps in `.travis.yaml`.

**Comment by jpkrohling** [comment]
New PRs don't run in the context of the main repository. PRs run in the context of the PR owner's fork. Let me scratch a test PR to demonstrate :)

**Comment by jpkrohling** [comment]
https://travis-ci.org/github/jaegertracing/jaeger/builds/721942147

Doc about this: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

**Comment by yurishkuro** [comment]
+1
