### ISSUE TITLE
TLS config tests are flaky

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#2428]
**Describe the bug**
```
$ go clean -testcache
$ go test github.com/jaegertracing/jaeger/pkg/config/tlscfg
...
--- FAIL: TestReload_ca_certs (20.18s)
    cert_watcher_test.go:160:
        	Error Trace:	cert_watcher_test.go:160
        	Error:      	Should be true
        	Test:       	TestReload_ca_certs
--- FAIL: TestAddCertsToWatch_remove_ca (0.00s)
    cert_watcher_test.go:312:
        	Error Trace:	cert_watcher_test.go:312
        	Error:      	Should be true
        	Test:       	TestAddCertsToWatch_remove_ca
FAIL
FAIL	github.com/jaegertracing/jaeger/pkg/config/tlscfg	20.472s
FAIL
$ go test github.com/jaegertracing/jaeger/pkg/config/tlscfg
ok  	github.com/jaegertracing/jaeger/pkg/config/tlscfg	0.575s
```

**To Reproduce**
1. `go clean -testcache`
2. `go test github.com/jaegertracing/jaeger/pkg/config/tlscfg`
3. Able to reproduce the failed tests quite reliably, often on the first pass.

**Expected behavior**
Tests to pass.

**Screenshots**

**Version (please complete the following information):**
 - OS: MacOS
 - Jaeger version: master
 - Deployment: N/A

**What troubleshooting steps did you try?**
I suspect it's due to the `certWatcher` failing to detect file changes on the filesystem.

I tried modifying tests to ensure synchronous writes to the cert files and that seems to have alleviated the problem. That is, I no longer could see the failed tests when repeatedly (about 10 times) running:
```
$ go clean -testcache
$ go test github.com/jaegertracing/jaeger/pkg/config/tlscfg
```

**Additional context**

**Comment by pavolloffay** [comment]
@albertteoh would you like to submit a PR to fix it?
