### ISSUE TITLE
Collector memory jump due to resize and OOM since 1.19.2

### ISSUE THREAD

**Issue by Stono** [jaegertracing/jaeger#2433]
**Describe the bug**
Hey, 
We had been running Jaeger `1.18.0` in production since it was released (any many versions before that), and never had a pod restart.  Yesterday we upgraded to `1.19.2` and since then we've had three collector instances killed by kubernetes OOM killer.  Nothing has changed at all about our spans, or configuration, so feels like there's a regression here.

We run our collectors with a `request` of `80Mi` and a limit of `160Mi`.  Under normal operation they sit around `70Mi` so when this happens they're jumping to 2.5x their standard usage. 

As you can see here, the memory spike is very sudden:
<img width="1619" alt="Screenshot 2020-08-29 at 16 35 51" src="https://user-images.githubusercontent.com/1486729/91640470-b7f94180-ea15-11ea-883e-05218dc00ad8.png">

This is always preceeded by an event like this in the logs:
```
{"level":"info","ts":1598551280.4247098,"caller":"app/span_processor.go:260","msg":"Resizing the internal span queue","new-size":99273,"average-span-size-bytes":845}
```

You can see at the same time the queue length on the collector spikes significantly:
<img width="800" alt="Screenshot 2020-08-29 at 16 37 13" src="https://user-images.githubusercontent.com/1486729/91640499-f0008480-ea15-11ea-985e-3b027bc16d24.png">

There's no corresponding spike in processing latency, incoming requests etc, and all other instances of collectors remain healthy.

Our collector configuration is:

```
        - name: COLLECTOR_NUM_WORKERS
          value: "100"
        - name: COLLECTOR_QUEUE_SIZE_MEMORY
          value: "80"
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        - name: ES_BULK_WORKERS
          value: "2"
        - name: ES_MAX_SPAN_AGE
          value: 48h0m0s
        - name: ES_NUM_REPLICAS
          value: "1"
        - name: ES_NUM_SHARDS
          value: "15"
        - name: ES_SNIFFER
          value: "false"
        - name: ES_TAGS_AS_FIELDS_ALL
          value: "true"
        - name: SPAN_STORAGE_TYPE
          value: elasticsearch
```

**To Reproduce**
Unfortunately I don't have a deterministic way to reproduce it.

**Expected behavior**
A clear and concise description of what you expected to happen.  We're doing about 30k spans/second across 18 instances, so it's fairly high load.

**Version (please complete the following information):**
 - OS: [e.g. Linux]
 - Jaeger version: [e.g. 1.8] 1.19.2
 - Deployment: [e.g. bare metal, Docker, Kubernetes, ...] GKE

**Comment by joe-elliott** [comment]
I just upgraded to 1.19.2 and will report back if I see anything similar.  Out of curiosity were you seeing the `Resizing the internal span queue` message before the upgrade? or are the memory spikes and the log message both new behavior?

I did a quick scan of our logs and this message has not been logged for us in the past 30 days.

**Comment by Stono** [comment]
Frustratingly I wasn’t scraping the logs to ES so they’re long gone.

I do have metric data though and the spike shown above in queue length never happened before

**Comment by joe-elliott** [comment]
Oh, this message is only logged if you have the dynamic queue size option enabled (which we do not).  That explains why I've never seen it.  Turning it on now.

**Comment by Stono** [comment]
We're seeing this about 4 or 5 times a day, we're going to roll the collector back to `1.18.0` and see how we get on.

**Comment by jpkrohling** [comment]
> this message is only logged if you have the dynamic queue size option enabled

That's correct. IIRC, a temporary spike in memory is kinda expected, but it should normalize once the resize operation is done. I think I might explain what's going on here. 

You've said that you want a dynamic queue size, using 80MiB of memory (`COLLECTOR_QUEUE_SIZE_MEMORY`). You've also set the `requests` for the pod to be `80MiB`, and the `limit` to 160MiB. Ideally, you should have `requests` to be 2x the size of `COLLECTOR_QUEUE_SIZE_MEMORY` + some buffer, for the other parts of the collector. With a queue size of 80MiB, I would set the `requests` to around 200MiB, and the limit to 150% of that (or 200%, if you can't afford 150%). 

The reason to have a requests 2x the size of the max queue size is that the resize operation will create another underlying queue, with the new size.

Two things are interesting in your report, though:

1. the memory spike seems to be permanent, when I would expect it to come back to the same levels
1. what's the red line in your graph?
1. there's nothing we changed in the last version regarding the queue sizes, from what I remember. You should indeed experience the same behavior in previous versions of Jaeger.

I'll run some experiments here to confirm that memory is being released back after the resize operation, but please try to adjust your memory settings to give the collector some extra room when using the dyn queue size.

**Comment by Stono** [comment]
Hey,
What you have said makes sense, thanks for the reply.  I’m hesitant to make any adjustments just yet because we’ve been stable with this configuration for over a year.  

As for the memory being free’d - I dont think we will are a drop off, as I don’t believe once it’s been allocated it is released back to the OS, only to the process as free (but allocated) memory.

**Comment by jpkrohling** [comment]
> As for the memory being freed up - I dont think we will see a drop off, as I don’t believe once it’s been allocated it is released back to the OS, only to the process as free (but allocated) memory.

I had a [similar memory problem](https://issues.redhat.com/browse/TRACING-1071) somewhere else, and the OS indeed has problems in seeing the released memory back. If you can, try setting the following env var, to see if it helps: `GODEBUG=madvdontneed=1`

**Comment by joe-elliott** [comment]
So, except for the initial sizing we have not seen a resizing event in our collectors.  Seeing it a few times a day suggests that your average span size is changing quite a bit over the course of the day.  Do the resizing logs reflect that?

Disabling the dynamic queue size feature will also prevent this from occurring.  Unsure if that's an option for you.

**Comment by Stono** [comment]
@joe-elliott we only ever see one resize event on one out of 18 collectors and that one resize event causes it to crash.  We're doing 30k spans per second round-robined so they're all getting their fair distribution of span sizes.  The span sizes don't change throughout the day, they're all generated by istio and contain the same small amount of metadata.

Since downgrading to `1.18.0` i can confirm we are seeing resize events:

```
{"level":"info","ts":1598859603.5000615,"caller":"app/span_processor.go:261","msg":"Resizing the internal span queue","new-size":103054,"average-span-size-bytes":814}
```

However they did not result in the pod dying, despite in this instance the. queue size growing to bigger than the size in my OP.

<img width="1591" alt="Screenshot 2020-08-31 at 15 20 26" src="https://user-images.githubusercontent.com/1486729/91730173-857a5080-eb9d-11ea-9ddd-ea3dd46b79a1.png">

Certainly looks as if 1.18.0. is simply using less memory 🤷

**Comment by jpkrohling** [comment]
>  We're doing 30k spans per second round-robined so they're all getting their fair distribution of span sizes

Could you confirm that your collectors are indeed receiving the same share of spans from your clients/agents?  Could you check the metric `jaeger_spans_saved_by_svc_total` and plot it in a per-node basis?

> However they did not result in the pod dying, despite in this instance the queue size growing to bigger than the size in my OP.

The graph seems to indicate that the memory is still around 50Mi. The pod should only be killed once it reaches the limit, which is 160Mi from what I understood.

**Comment by Stono** [comment]
My point is that the resize event on 1.19 caused it to hit the limit, on 1.18 it did not

**Comment by jpkrohling** [comment]
> My point is that the resize event on 1.19 caused it to hit the limit, on 1.18 it did not

I understood that, but I believe this is by chance.

**Comment by Stono** [comment]
Maybe...
But it’s consistently causing OOMs on 1.19.2 and literally never on 1.18. 

Let’s see what happens over the next 24hrs

**Comment by jpkrohling** [comment]
@joe-elliott, @Stono do you have a way to measure the regular footprint between those two versions? Perhaps the overall footprint of 1.19.2 is bigger, which makes the limit to be reached?

**Comment by Stono** [comment]
> @joe-elliott, @Stono do you have a way to measure the regular footprint between those two versions? Perhaps the overall footprint of 1.19.2 is bigger, which makes the limit to be reached?

Yes that’s what I shared above showing 1.18 sitting about 20% lower (currently) but I’m keen to see if it rises again. 

A slightly higher memory footprint would exacerbate the issue during a reside so it makes sense.

**Comment by joe-elliott** [comment]
I'm seeing roughly the same `container_memory_working_set_bytes` between 1.18 and 1.19.  I am, however, using Cassandra (Scylla) backend.

**Comment by Stono** [comment]
> I'm seeing roughly the same `container_memory_working_set_bytes` between 1.18 and 1.19. I am, however, using Cassandra (Scylla) backend.

For context I’m using ElasticSearch backed

**Comment by Stono** [comment]
Hey, 
Sorry for the delays in getting back to you.   I've been going back and forth between 1.18 and 1.19 with different configuration and have gotten absolutely nowhere trying to debug this!  We're now, annoyingly, back on 1.19 and haven't had a crash in days...

I'm half inclined to say we should close the issue and if i get anywhere with pin pointing what's up I can reopen it?  But as it stands, i'm head scratching.

**Comment by jpkrohling** [comment]
Alright, I'm closing this for now then. If you do experience this again, try to get a memory profile from the collector and attach here. Something like this would work, assuming that your Jaeger is running at localhost (or that you have a `kubectl port-forward my-jaeger-pod 14269`):

```console
$ curl localhost:14269/debug/pprof/heap --output heap.gz
```

You can also browse it yourself with:

```console
$ go tool pprof -http localhost:8080 http://localhost:14269/debug/pprof/heap 
```

A web browser should be opened automatically, with `http://localhost:8080/ui/` loaded.
