### ISSUE TITLE
Bump gRPC dependency to v1.31.x

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2449]
Similar to #2443, we should migrate to newer versions of gRPC/protobuf/... as soon as feasible, otherwise the costs of moving to an even higher version once we *need* is going to be higher than desirable. 

This task is to track all that is required to get it working, including the update of the [builder image](https://github.com/jaegertracing/docker-protobuf/).

**Comment by pavolloffay** [comment]
Dup of #2771
