### ISSUE TITLE
Remove deprecated `--es.max-num-spans` flag in v1.21.0

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#2457]
## Requirement - what kind of business use case are you trying to solve?

As a follow-up task to #2437, which deprecated `--es.max-num-spans` in favour of `--es.max-doc-size`, this is a reminder Issue to remove the deprecated `--es.max-num-spans` flag in version 1.21.0, as noted in the [deprecation note on the flag](https://github.com/jaegertracing/jaeger/pull/2453/files/9ebf9d37a2662f12696c4664d043d5b6c61eaebe#diff-33c1785172c58663ab0bc033adbcef49R182).

**Comment by BernardTolosajr** [comment]
Hi guys, i'll pick this one. thanks
