### ISSUE TITLE
Can we set up username and password based authentication for Jaeger Dashboard?

### ISSUE THREAD

**Issue by mohanbabugaddam69** [jaegertracing/jaeger#2463]
Can we set up username and password based authentication for Jaeger Dashboard

**Comment by jpkrohling** [comment]
No, not via Jaeger proper. We currently recommend setting up an authentication proxy in front of the Query.

**Comment by mohanbabugaddam69** [comment]
Can you give any reference to do go with the authentication proxy? Sorry my bad, I am new to this . Just started exploring it

**Comment by chandu9333** [comment]
Can we use RBAC for Jaeger UI authentication?

**Comment by yurishkuro** [comment]
Cf: https://medium.com/jaegertracing/protecting-jaeger-ui-with-an-oauth-sidecar-proxy-34205cca4bb1
