### ISSUE TITLE
Observing span metrics/analytics for Jaeger UI using Jaeger and/or Prometheus

### ISSUE THREAD

**Issue by lavieth** [jaegertracing/jaeger#2473]
Hello! 
A question, is it necessary to use Prometheus to monitor Jaeger metrics (spans sent, trace data, etc.) or is there a way to just use Jaeger itself, (I'm sure there is, just not sure how)? The application for this is a research project I am working on that uses Jaeger UI to view node/server interactions for sensor nodes that collects physical data and reports it to a server for review/collection all linked via IOT. (especially for finding a link of possibly dropped spans due to packet loss, timeouts, physical interruptions)

Thank you!

**Comment by yurishkuro** [comment]
You can access the /metrics endpoint for the raw data, but if you want to collect a time series for plotting / analysis you will need to use a metrics system like Prometheus or similar that can scrape the data.
