### ISSUE TITLE
Debug images with delve and other base image

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2493]
## Requirement - what kind of business use case are you trying to solve?

We discussed having a different base image for Jaeger, for better troubleshooting, but never moved forward, mostly because the maintenance burden of having two very similar images wasn't worth it. But @bjung82 had a great question, on whether we have a debug image with delve enabled, for remote debugging. 

This sounds like a great idea, and given the recent issues with the agent, sounds like something that would really help users.

## Problem - what in Jaeger blocks you from solving the requirement?

Sometimes, observability is not enough ;-)

## Proposal - what do you suggest to solve the problem or improve the existing situation?

This would require a new Dockerfile for all components, new targets in the Makefile. 

Context: #2465, and would probably also be helpful for #2452

**Comment by vkartik97** [comment]
can I take this up ?

**Comment by jpkrohling** [comment]
It's yours!

**Comment by jpkrohling** [comment]
@aebirim wants to work on this one as well.

**Comment by yurishkuro** [comment]
> whether we have a debug image with delve enabled, for remote debugging.

@jpkrohling is delve needed to be in the image for this?

**Comment by jpkrohling** [comment]
Delve needs to be there, and the Jaeger binaries in the image should not be optimized, so that Delve can extract name and line information.
