### ISSUE TITLE
can i extract ip address from http request and add it to tags?

### ISSUE THREAD

**Issue by axiangcoding** [jaegertracing/jaeger#2497]
when i use jaeger-collector to receive spans, by using Thrift over HTTP, 
can i extract ip address from request header and add it to tags?
like this:
```
{
  "traceId": "something",
  "spanId": "something",
  "operationName": "something",
  "flags": something,
  "startTime": "something",
  "tags": [
    { "key": "key1", "vStr": "value1" },
    { "key": "ipaddr", "vStr": "127.0.0.1" } //from request header
  ],
  "process": {
    "serviceName": "something",
    "tags": [
      { "key": "key2", "vStr": "value2" },
    ]
  }
}
```

**Comment by axiangcoding** [comment]
if jaeger-collecot can't did it, perhaps some soluations?
Looking forward to advice, Thanks in advance
And forgive my poor english  :)

**Comment by jpkrohling** [comment]
That's currently not possible: while you can add tags to the spans seen by a collector, the values are static. The agent can also add tags, but again, not with dynamic values.

What you could be doing is to make your application send trace information to an agent on the same host, and then make the agent add the IP to all spans it processes. We do something similar in the Jaeger Operator to add the Kubernetes pod's name/namespace to the spans.

**Comment by axiangcoding** [comment]
> That's currently not possible: while you can add tags to the spans seen by a collector, the values are static. The agent can also add tags, but again, not with dynamic values.
> 
> What you could be doing is to make your application send trace information to an agent on the same host, and then make the agent add the IP to all spans it processes. We do something similar in the Jaeger Operator to add the Kubernetes pod's name/namespace to the spans.

Thanks for your answer. I will try another way. 
Hava a nice day!
