### ISSUE TITLE
Where is the query-linux-$TARGETARCH?

### ISSUE THREAD

**Issue by douzizuibang** [jaegertracing/jaeger#2507]
I have downloaded the jaeger code which from master branch, and then executed the `go mod tidy`. And executed the command `go build` from `/cmd/query` folder. I have encounted the error 
```
Step 7/8 : COPY query-linux-$TARGETARCH /go/bin/query-linux
COPY failed: stat /var/lib/docker/tmp/docker-builder908757000/query-linux-amd64: no such file or directory
```
when executed `docker build ...` command. How/Where can I find or generate the linux-query-$TARGETARCH file?
THX

**Comment by joe-elliott** [comment]
Use the `make` commands to build binaries and docker images.

`make docker` will build all binaries, the ui and docker images.  You can review `./Makefile` to see other options.

**Comment by douzizuibang** [comment]
I have executed the `make` command and get the error. Please help to investigated it. Thx

<img width="619" alt="截屏2020-09-24 上午11 54 50" src="https://user-images.githubusercontent.com/16741710/94099216-ffc88880-fe5c-11ea-855a-f133bc279365.png">
