### ISSUE TITLE
How to entered the jaeger-query container?

### ISSUE THREAD

**Issue by douzizuibang** [jaegertracing/jaeger#2508]
I have deploy the jaeger-query pod via k8s yaml. However, I try to executing the command into pod failed.
```
kubectl exec -it <pod name> bash -n xxx
```
So, what is the comand into the pod?

**Comment by joe-elliott** [comment]
I don't believe there is a shell available in the jaeger containers.  They are built:

```
FROM scratch
```

Simple "getting started" questions may be more appropriate in the https://gitter.im/jaegertracing/Lobby

**Comment by yurishkuro** [comment]
See #2493.
