### ISSUE TITLE
Does adding request header remoteAddr to Process.Tag during request handler have side effects?

### ISSUE THREAD

**Issue by axiangcoding** [jaegertracing/jaeger#2510]
Last time i ask a question about how to extract ip address from request header to spans. see: #2497 
After comprehensive consideration and some attempts, I eventually decided to modify the source code to achieve this function.
After a day of learning in GO language (I am much more familiar with Java) and jeager-collector source code, i made a code change in `./cmd/collector/app/handler/http_handler.go` as follow:
```
func (aH *APIHandler) SaveSpan(w http.ResponseWriter, r *http.Request) {
	bodyBytes, err := ioutil.ReadAll(r.Body)
	r.Body.Close()
	if err != nil {
		http.Error(w, fmt.Sprintf(UnableToReadBodyErrFormat, err), http.StatusInternalServerError)
		return
	}

	contentType, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))

	if err != nil {
		http.Error(w, fmt.Sprintf("Cannot parse content type: %v", err), http.StatusBadRequest)
		return
	}

	if _, ok := acceptedThriftFormats[contentType]; !ok {
		http.Error(w, fmt.Sprintf("Unsupported content type: %v", contentType), http.StatusBadRequest)
		return
	}

	tdes := thrift.NewTDeserializer()
	// (NB): We decided to use this struct instead of straight batches to be as consistent with tchannel intake as possible.
	batch := &tJaeger.Batch{}
	if err = tdes.Read(batch, bodyBytes); err != nil {
		http.Error(w, fmt.Sprintf(UnableToReadBodyErrFormat, err), http.StatusBadRequest)
		return
	}

       // my modification is here
	batch.Process.Tags = append(batch.Process.GetTags(), &tJaeger.Tag{Key: "remoteAddr", VStr: &r.RemoteAddr})
       // 

	batches := []*tJaeger.Batch{batch}
	opts := SubmitBatchOptions{InboundTransport: processor.HTTPTransport}
	if _, err = aH.jaegerBatchesHandler.SubmitBatches(batches, opts); err != nil {
		http.Error(w, fmt.Sprintf("Cannot submit Jaeger batch: %v", err), http.StatusInternalServerError)
		return
	}

	w.WriteHeader(http.StatusAccepted)
}
```

Based on this, I packaged a docker image, and it works fine. But i'm new to Go language and Jaeger, could some bugs happened after i did this? 
If there are some unknown bugs here, how do i fix it? 
Or maybe a function like this can be officially added to the main repository in the furture?
Please give me some suggestions, thank you in advance

**Comment by objectiser** [comment]
@axiangcoding The problem with this solution is that it assumes the sender is the source of the span (i.e. no intermediate collectors). It would be better if this field was added at the source - either within the instrumented app or within a sidecar agent.

**Comment by jpkrohling** [comment]
I'm not quite sure I get this use case. Every span generated by Jaeger clients has its own "ip" process tag, representing the IP for the host that generated the span. The IP the collector will be getting is then either the Agent's, which will differ from the IP in the process tag, or will be the Jaeger Client's, which will match exactly the IP in the process tag.

**Comment by axiangcoding** [comment]
The reason I need to add ip address to spans here is because we have a lot of products (based on nodejs, java, csharp, etc.), and I hope to implement this feature with minor changes, so I have a question about #2497 .
Our products are directly transmitted to jaeger-collector by using Thrift over HTTP, without going through jaeger-agent, so it can be guaranteed that this IP is a real IP address.
My original purpose was to convert the IP address into geographic location information in jaeger-collector, but doing so will affect the speed (Try it before, now try to fix it on Spark, but its another story).
Considering that we can directly add an IP address in the jaeger client, this function seems very useless :(
Anyway, thanks very much for the suggest
