### ISSUE TITLE
[Jaeger UI] Versioning show on Jaeger UI

### ISSUE THREAD

**Issue by redondoxx** [jaegertracing/jaeger#2511]
## Requirement - what kind of business use case are you trying to solve?

Easily check version (ex: 1.19.2) on Jaeger UI.

## Problem - what in Jaeger blocks you from solving the requirement? 

Take some effort to check the image version in our backend and infra.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Visualize the versioning of Jaeger Query on Jaeger UI.

**Comment by objectiser** [comment]
Closing as duplicate of https://github.com/jaegertracing/jaeger-ui/issues/365
