### ISSUE TITLE
jaeger-collector to high version，but can`t  receive data

### ISSUE THREAD

**Issue by jiangxinlingdu** [jaegertracing/jaeger#2516]
jaeger-collector to high version，but can`t  receive data，by comparing  i find some problems
![image](https://user-images.githubusercontent.com/6373972/94510259-ebafcd00-0248-11eb-8fce-f70f72a0dcd2.png)
agent use 14267 send to collector, now i want to high version jaeger-collector,what should i do ? how to update agent cmd ???

**Comment by albertteoh** [comment]
Hi,

It sounds like you'd like to upgrade to v1.18.0+ and, if so, please refer
to v1.18.0's release notes
<https://github.com/jaegertracing/jaeger/blob/master/CHANGELOG.md#1180-2020-05-14>
which
detail the breaking changes:

Remove Tchannel port (14267) from collector and Tchannel reporter from
> agent.


If you're running the collector with the default configuration, you can
connect the agent to the collector with these parameters:
--reporter.grpc.host-port <host>:<port>

Albert

**Comment by jiangxinlingdu** [comment]
3q
