### ISSUE TITLE
Update Jaeger license to Apache 2 license

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#252]
We are planning to re-release Jaeger source code under [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). This affects the following repositories:
  * [x] https://github.com/uber/jaeger
  * [x] https://github.com/uber/jaeger-lib
  * [x] https://github.com/uber/jaeger-ui
  * [x] https://github.com/uber/jaeger-client-go
  * [x] https://github.com/uber/jaeger-client-java
  * [x] https://github.com/uber/jaeger-client-node
  * [x] https://github.com/uber/jaeger-client-python

This issue is meant to notify all contributors (who are not Uber employees) to raise their objections or concerns _before August 21, 2017_.

**Comment by yurishkuro** [comment]
For https://github.com/uber/jaeger-client-node:

@OmgImAlexis @frankgreco

**Comment by yurishkuro** [comment]
For https://github.com/uber/jaeger-client-python:
  * @MrSaints
  * @bharat-p
  * @philipgian

**Comment by yurishkuro** [comment]
For https://github.com/uber/jaeger-client-java: @nklmish @adriancole @atanasbalevski @rubbish @hzariv @aristidisp @felixbarny @objectiser @pavolloffay @kevinearls @mabn @jkandasa @jpkrohling

**Comment by yurishkuro** [comment]
For https://github.com/uber/jaeger-ui: @tiffon @pavolloffay

**Comment by yurishkuro** [comment]
For https://github.com/uber/jaeger: @seregayoga @yuekui2 @mwarkentin @pavolloffay @jpkrohling @wuman

**Comment by yurishkuro** [comment]
For https://github.com/uber/jaeger-lib: @madhuravi

**Comment by yurishkuro** [comment]
For https://github.com/uber/jaeger-client-go: @JELGT2011 @willhug @szdavid92 @Dogild @diegofernandes @hkshaw1990

**Comment by OmgImAlexis** [comment]
Does this affect the CLA we signed?

**Comment by adriancole** [comment]
Since pinged, I should mention I'm wholesale in favor of this if nothing
else a simplified license scheme (since afterwards all parts not just some
use ASL). Good luck!

**Comment by frankgreco** [comment]
I have no objections to this.

**Comment by jpkrohling** [comment]
I'm OK with this change.

**Comment by seregayoga** [comment]
Apache 2 licence is ok. Go ahead.

**Comment by hkshaw1990** [comment]
I'm ok with the Apache v2 license.

**Comment by yurishkuro** [comment]
ALL - to reduce the amount of emails this will generate to everyone who's `@mentioned`, you may simply +1 / thumbsup the main description as some people have done already. Not replying at all is fine too, we'll assume you have no objections.

**Comment by adriancole** [comment]
Quick question: while doing maintenance on license, are you also planning to make it "Copyright The Jaeger Contributors" or is that unaffected/a separate topic?

**Comment by yurishkuro** [comment]
copyright is separate, won't happen until we move to a top-level org.

**Comment by yurishkuro** [comment]
all done
