### ISSUE TITLE
Wrong deprecation message for 'es-archive' option

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2526]
**Describe the bug**
The deprecation message for the flag `--es-archive.max-num-spans` reads: 

> (deprecated, will be removed in release v1.21.0. Please use es.max-doc-count). The maximum number of spans to fetch at a time per query in Elasticsearch. The lesser of es.max-num-spans and es.max-doc-count will be used if both are set.

It should state that the flag to use is `es-archive.max-doc-count` instead of `es.max-doc-count`. Same with all other occurrences of the flag names in the message.

**To Reproduce**
1.  `$ podman run -e SPAN_STORAGE_TYPE=elasticsearch -p 16686 jaegertracing/all-in-one:1.20.0 --help | grep max-num-spans`

**Expected behavior**
The `es-archive` prefix should be used in the message.

**Version (please complete the following information):**
 - Jaeger version: 1.20

**Comment by jpkrohling** [comment]
@albertteoh would you like to take care of this one?

**Comment by albertteoh** [comment]
Yup, leave it with me, @jpkrohling! Thanks for picking that up.
