### ISSUE TITLE
Incorrect type casting for binary annotations

### ISSUE THREAD

**Issue by tobstarr** [jaegertracing/jaeger#2527]
**Describe the bug**
We are trying to feed traces via zipkin protocol into jaeger using the elixir package tapper (https://hexdocs.pm/tapper/readme.html).

When we add the annotation `http_status` jaeger does return status code 500 though and the jaeger container logs show `"interface conversion: interface {} is string, not float64"` with a stacktrace.

Tapper is using binary annotations to send the `http_status` to zipkin and uses the status code as a string and not as an integer/float64. According to the zipkin-api this seems to be according to the spec: https://github.com/openzipkin/zipkin-api/blob/master/zipkin-api.yaml#L316

**To Reproduce**
1. start jaeger in local docker container like this: `jaegertracing/all-in-one:1.19.2`
2. setup a new elixir project using e.g. `mix new tapper_zipkin`, configure tapper like described at https://hexdocs.pm/tapper/readme.html#zipkin-reporter and then run
```
id = Tapper.start(name: "status-test", sample: true)
Tapper.update_span(id, [Tapper.http_status_code(200)])
Tapper.finish(id)
```
This will print `...[warn]  Failed to send spans: status=500 %HTTPoison.Response{body:...` in the elixir logs.
3. alternatively you can also just run `curl -H "Content-Type: application/json" http://localhost:9411/api/v1/spans -d @payload.json` with payload.json being
```
[
  {
    "binaryAnnotations": [
      {
        "endpoint": {
          "ipv4": "10.66.33.10",
          "port": 0,
          "serviceName": "phrase-graphql"
        },
        "key": "http.status_code",
        "type": "I16",
        "value": "200"
      }
    ],
    "debug": false,
    "duration": 367554,
    "id": "b3c6a8321d953c81",
    "name": "POST /graphql",
    "timestamp": 1601458290564597,
    "traceId": "b3c6a8321d953c81bd03f016672ca19a"
  }
]
```

**Expected behavior**
I would have expected jaeger to accept the trace/span and not return an error.

**Screenshots**
-

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.19.2
 - Deployment: docker (jaegertracing/all-in-one:1.19.2)

**What troubleshooting steps did you try?**
I also looked into how the official zipkin libraries for go and ruby behave in such a scenario but it seems that both do not use binary annotations at all. But looking at the zipkin-api document it is very clear to me that the binary annotations endpoint should at least also accept values as strings for all numeric types.

**Additional context**
-

**Comment by yurishkuro** [comment]
if you're sending it as a string value, then the `type` field should be `string`, but you have `I16` (integer).

**Comment by tobstarr** [comment]
@yurishkuro thanks for clarifying. Do you know of link to the actual protocol specification of zipkin (I only found the OpenAPI spec) where this is more clear so that I can reference it when I file a bug with the library I am using?

**Comment by yurishkuro** [comment]
The same zipkin-api repository you linked has all the schemas. Specifically, you're sending the old v1 schema where tags were typed, whereas in the latest schemas like JSON or proto v3, the tags are string->string.

**Comment by jkowall** [comment]
This is old and folks should be using the new Elixr support in Otel now : https://opentelemetry.io/docs/languages/erlang/
