### ISSUE TITLE
Migrate to OpenTelemetry Collector based Agent, Collector, Ingester and All-In-One

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#2530]
Currently we are building two sets of agent, collector, ingester and all-in-one executables/images - one set for the existing 1.x stream and the other based on the OpenTelemetry Collector.

For Jaeger 2, the OpenTelemetry Collector based components should be the only ones being built, and they should be renamed to their 1.x equivalents (i.e. replacing them).

Although some options continue to be supported with the new components, any breaking changes (i.e. options no longer supported, change in healthcheck ports, etc) should be clearly documented in the release notes.

**Comment by pavolloffay** [comment]
Closing as it is a "low level" issue related to V2 which might take a different approach.
