### ISSUE TITLE
Add Chronowave storage backend as build-in options

### ISSUE THREAD

**Issue by rleiwang** [jaegertracing/jaeger#2534]
## Requirement - what kind of business use case are you trying to solve?
Facilitate root cause analysis by integrating trace and application log search/display into one application, Jaeger.

## Problem - what in Jaeger blocks you from solving the requirement?
Jaeger UI currently can't search on logs. The storage backends in all-in-ones mode don't support searching tags with just key words or wild card.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
I am proposing to add https://github.com/chronowave/chronowave as one of the storage backends. Chronowave is an open source data store built for append only machine generated data. Chronowave uses sequence based full text search engine to provide the same search functionalities as ElasticSearch has, but with much less system resource requirements. I have integrated Chronowave with Jaeger in https://github.com/chronowave/jaeger. It works in all-in-one mode. The following screen shot shows the result of wild card key word search on HotRod trace tags.

![image](https://user-images.githubusercontent.com/6434571/94977457-a8b25b80-04cd-11eb-837c-6217697bad42.png)

## Any open questions to address
Before I create pull request, are there any integration tests I need to integrate first?

**Comment by yurishkuro** [comment]
I've never heard of chronowave. The repo has a total of 2 commits made in the last 5hrs, and the whole org created 9 days ago. Can't tell if this is spam or not.

If you're interested in using Jaeger with this backend, you can implement a grpc plugin or use a fork. We only support integration with widely used data stores.
