### ISSUE TITLE
Jaeger not working with Webclient

### ISSUE THREAD

**Issue by winster** [jaegertracing/jaeger#2537]
Please take a look at https://github.com/winster/jaeger-trace-reactive/blob/master/src/main/java/com/example/demo/JaegerTraceReactiveApplication.java

This is a spring boot application with opentracing. As per the doc, jaeger supports webflux and webclient. But it has been noted that, the trace skips the reactive flow when there is a webclient call. 

Is there a way to fix this?

### Update
Please find the screenshots attached in README https://github.com/winster/jaeger-trace-reactive
Initial analysis shows that following method are invoked everytime webclient makes http request. 

- `TracingExchangeFilterFunction::filter` 
- `TracingClientResponseMono::subscribe`
- `TracingClientResponseSubscriber::onSubscribe`

Also noted that `SpanLogsAppender::append` is called for every log with the same spanId. 

It is observed that `JaegerSpan::finish` is called before missing logs are appended. But span is not null, when the missing logs are being appended.

I tried removing, `@Async` annotation in service method for which Jaeger shows only `POST` trace.

I'm stuck, no way to debug further. Looking forward to the support

**Comment by jpkrohling** [comment]
I don't think this is the right repository for this bug report, sounds like a problem with the instrumentation library you are using? 

```xml
		<dependency>
			<groupId>io.opentracing.contrib</groupId>
			<artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
			<version>3.2.0</version>
		</dependency>
```

I'm not 100% sure, but try opening an issue in the following repository: https://github.com/opentracing-contrib/java-spring-jaeger
