### ISSUE TITLE
Finish implementing trace anonymizer

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2556]
## Requirement - what kind of business use case are you trying to solve?

Allow people to safely export production traces into GitHub tickets (as a way of reproducing problems, especially with the UI) without exposing sensitive information.

## Problem - what in Jaeger blocks you from solving the requirement?

The anonymizer is partially implemented.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Finish the implementation as follows

* extend the Anonymizer type with these additional parameters
  * hashStandardTags - when true, the `allowsTags` are also hashed, when false they are preserved as is
  * hashCustomTags - when true, all other tags are hashed, when false they are dropped (current behavior)
  * hashLogs - when true, logs are hashed, when false they are dropped (current behavior)
  * hashProcess - when true, process tags are hashed, when false they are dropped (current behavior)
* implement main program
  * add option to specify query service gRPC address to load the trace
  * add option to specify trace ID to load from gRPC query service
  * add option to specify output directory to save the file
  * add options for Anonymizer configuration parameters
  * when saving anonymized trace to a file, it first must be converted to the UI model (see writer package)
    * validation: the trace should be loadable by Jaeger UI (Load JSON tab in the Search panel)

cc @jpkrohling

**Comment by Ashmita152** [comment]
Hi @yurishkuro @jpkrohling may I pick and try solving this issue as two PRs for the two parts.

**Comment by jpkrohling** [comment]
It's yours!

**Comment by Ashmita152** [comment]
Hi @yurishkuro 

This PR implements only the first part of the issue, second part (main program) is still remaining, which I am planning to pick next. Sorry for creating the confusion.

**Comment by yurishkuro** [comment]
Yes, I know - github auto-closed the issue because the PR had a magic clause "fixes ####".

**Comment by Ashmita152** [comment]
Sorry my bad, I shouldn't have added fixes ## thing in the PR.
