### ISSUE TITLE
Enhance mergify with maintainer's interests

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2561]
@jaegertracing/jaeger-maintainers , Mergify was enabled for this repository and I added a base configuration file:

https://github.com/jaegertracing/jaeger/blob/720dd9db01fadf0e58113f66eda504ad764a0566/.github/mergify.yml

Please, enhance it with your interests!

**Comment by yurishkuro** [comment]
seems no interest in this, closing
