### ISSUE TITLE
Enable OTLP port to be configurable via CLI flags

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#2563]
## Requirement - what kind of business use case are you trying to solve?

Allow users to change the port (currently 13133) used for the OTLP endpoint in the Jaeger OpenTelemetry Collector and Agent.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently other protocol endpoints can have their ports changed via CLI flags - but the OTLP port is fixed.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add a new CLI flag to support configuring a different port for OTLP.

**Comment by joe-elliott** [comment]
To give some history. 

- Generally we haven't added any additional flags for otel and all the cli flags are pulled from the existing Jaeger agent and collector. @pavolloffay may be able to add more here for the reasoning behind it.
- The otlp port should be currently overridable by using the otel config file param.
- For setting individual otel fields via the cli the plan was to use a [set param](https://github.com/open-telemetry/opentelemetry-collector/pull/1640).  Unfortunately this was [reverted](https://github.com/open-telemetry/opentelemetry-collector/issues/1907) and will be remerged once the linked issue is fixed.

**Comment by objectiser** [comment]
Ok thanks @joe-elliott.

@jpkrohling I guess we could just detect/extract the overridden port from the OTel Config in the operator's CR and use that to adjust the collector/agent deployments?

**Comment by jpkrohling** [comment]
> The otlp port should be currently overridable by using the otel config file param.

Would we then end up having both flags (Jaeger) and a configuration file (OpenTelemetry Collector)?

**Comment by joe-elliott** [comment]
Yes, it can be currently configured using a mix of Jaeger cli, Jaeger config file and an Otel Config file.  The application attempts to merge all 3 sources into one.

It can also be fully configured by only specifying an otel collector configuration file.  Perhaps we should document an end goal and begin working towards that?

**Comment by objectiser** [comment]
I'm closing this, as based on the current ideas we won't be supporting the previous concept of CLI flags.
