### ISSUE TITLE
Jaeger Collector Kafka Bug

### ISSUE THREAD

**Issue by rajugpt6-coder** [jaegertracing/jaeger#2564]
I have configured all the environment variables for jaeger-collector with kafka. But the jaeger collector is not pushing data to the kafka topic.

Tried command to read data from kafka topic: bin/kafka-console-consumer.sh --topic logs --from-beginning --bootstrap-server localhost:9092

Jaeger collector command: docker run \
  -e SPAN_STORAGE_TYPE=kafka \
  -e KAFKA_PRODUCER_BROKERS=localhost:9092 \
  -e KAFKA_TOPIC=logs \
  jaegertracing/jaeger-collector:1.20

Jaeger Agent Command: docker run \
  --rm \
  -p5775:5775/udp \
  -p6831:6831/udp \
  -p6832:6832/udp \
  -p5778:5778/tcp \
  jaegertracing/jaeger-agent:1.20 \
  --reporter.grpc.host-port=jaeger-collector.jaeger-infra.svc:14250

**Comment by albertteoh** [comment]
@rajugpt6-coder, can you please share the log output from jaeger-collector and jaeger-agent?

**Comment by albertteoh** [comment]
BTW, try replacing `KAFKA_TOPIC` with `KAFKA_PRODUCER_TOPIC` (https://www.jaegertracing.io/docs/1.20/deployment/#kafka).

**Comment by rajugpt6-coder** [comment]
Thanks it works!
