### ISSUE TITLE
Duplicate components are being built twice in OpenTelemetry distribution

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2567]
Currently, the Jaeger OpenTelemetry distribution uses the default components from the main OpenTelemetry Collector, making some factories to be called twice, such as the Jaeger Receiver, Exporter and Zipkin Receiver:

https://github.com/jaegertracing/jaeger/blob/bd59f13478cdd35b41e85f67a6f04b6cb4d92df8/cmd/opentelemetry/app/defaultcomponents/defaults.go#L76

https://github.com/jaegertracing/jaeger/blob/bd59f13478cdd35b41e85f67a6f04b6cb4d92df8/cmd/opentelemetry/app/defaultcomponents/defaults.go#L91-L102

https://github.com/open-telemetry/opentelemetry-collector/blob/f683a384c41120d52ea93783b7f5d40da2d06476/service/defaultcomponents/defaults.go#L72

https://github.com/open-telemetry/opentelemetry-collector/blob/f683a384c41120d52ea93783b7f5d40da2d06476/service/defaultcomponents/defaults.go#L90-L91

**Comment by lastchiliarch** [comment]
Seems out of  date, I have checked the master branch that  cmd/opentelemetry had been removed. Maybe we could close this issue. @jpkrohling
