### ISSUE TITLE
OTEL all-in-one `--help` hangs

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#2581]
**Describe the bug**
May be related to #2566.

Running `go run ./cmd/all-in-one --help` prints help documentation, but appears to hang afterwards.

**To Reproduce**
1. `cd cmd/opentelemetry`
2. `go run ./cmd/all-in-one --help`

Output:
```
Jaeger OpenTelemetry all-in-one

Usage:
  jaeger-opentelemetry-all-in-one [flags]
...
      --sampling.strategies-file string                    The path for the sampling strategies file in JSON format. See sampling documentation to see format of the file
^Csignal: interrupt
```

**Expected behavior**
Print help documentation and exit successfully.

**Screenshots**

**Version (please complete the following information):**
 - OS: macOS
 - Jaeger version: master
 - Deployment: Development

**What troubleshooting steps did you try?**

**Additional context**

**Comment by yurishkuro** [comment]
Is it just all-in-one or other otel binaries too?

**Comment by albertteoh** [comment]
> Is it just all-in-one or other otel binaries too?

@yurishkuro just otel all-in-one. All other binaries otel and non-otel exit successfully after printing help.
