### ISSUE TITLE
Missing supporting library github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options: Unable to install Jaeger Agent from Github repo 

### ISSUE THREAD

**Issue by blessengeorge** [jaegertracing/jaeger#2582]
**Describe the bug**
I have git cloned the repo and placed the code into $GOPATH/src folder. Ran 
`go get -v -d ./...` in order to install all the dependencies but facing the following error: 

`github.com/grpc-ecosystem/grpc-gateway (download)
package github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options: cannot find package "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options" in any of:
	/usr/lib/go-1.10/src/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options (from $GOROOT)
	/home/admin123/go/src/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options (from $GOPATH)
`

**To Reproduce**

**Expected behavior**
Was expecting a clean install. 

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: Latest
 - Deployment: Bare metal

**Comment by yurishkuro** [comment]
> `go get -v -d ./...`

This repo is using go modules, there is no need to put it under $GOPATH/src or to install dependencies (and the above wouldn't be the way anyway). Please refer to CONTRIBUTING.md for setup instructions.

**Comment by blessengeorge** [comment]
Thanks Yuri - I have gone over the document CONTRIBUTING.md 

I'm trying to create a Dockerfile using just the Jaeger Agent. Can you help me with the steps to go about it ?

**Comment by jpkrohling** [comment]
Are you trying to add the Jaeger Agent to your own image? You can either base your container image on the Jaeger Agent's ([`jaegertracing/jaeger-agent`](https://hub.docker.com/repository/docker/jaegertracing/jaeger-agent)), or download a binary from our releases page ([v1.20.0](https://github.com/jaegertracing/jaeger/releases/tag/v1.20.0)).

**Comment by blessengeorge** [comment]
Yes that is correct. Great will try out these suggestions thanks!
