### ISSUE TITLE
How to decode traceid read from kafka

### ISSUE THREAD

**Issue by AudienceX** [jaegertracing/jaeger#2591]
I'm using kafka in Jaeger System, and I got traceid like "AAAAAAAAAABx3MgiIQRHEg==",  span_id like "jkVS3tZkQKM="  from Kafka
There are some Issues say that the traceId can decode by base64,  but I can't 

So  how to decode traceId With Python or C++

**Comment by yurishkuro** [comment]
What are "some issues"? This is standard base64.

**Comment by AudienceX** [comment]
> What are "some issues"? This is standard base64.

emmmmm....
issues: [Why is the data received from kafka like this? question](https://github.com/jaegertracing/jaeger/issues/1464), and [how to decode trace_id from kafka protobuf data? question](https://github.com/jaegertracing/jaeger/issues/1145)

But I get maybe wrong result decoding with  Base64 using https://www.base64decode.org/

Input: AAAAAAAAAABx3MgiIQRHEg==
output: qÜÈ"!G

**Comment by yurishkuro** [comment]
Why do you think it's wrong? If you're trying to get to a hex ID, you need to decode to a byte array first and the convert bytes to hex. The online converter tries to interpret those bytes as string.

**Comment by AudienceX** [comment]
> Why do you think it's wrong? If you're trying to get to a hex ID, you need to decode to a byte array first and then convert bytes to hex. The online converter tries to interpret those bytes as string.

I still don't know how the traceId in kafka was produced.....

You said ," you need to decode to a byte array first and then convert bytes to hex"
Is it means that traceId gotton from Jaeger UI is hex ?

For example, a traceid , "abe33738f1825469",  will first decode with hex, then encode with base64,
so it can became " AAAAAAAAAABx3MgiIQRHEg=="  ?

**Comment by yurishkuro** [comment]
> abe33738f1825469

you first convert it into byte array, `[0xAB, 0xE3, 0x37, ...]`, and then encode this byte array with base64.

**Comment by yurishkuro** [comment]
Btw, are you using JSON encoding with Kafka?  We use binary protobuf, which is much more efficient.

**Comment by AudienceX** [comment]
> Btw, are you using JSON encoding with Kafka? We use binary protobuf, which is much more efficient.

“JSON encoding”, you mean the parameter  **--kafka.producer.encoding=json** of jaeger-collcoter ?
I do use JSON encoding

Maybe when I knew the protobuf and Jaeger I will try using **protobuf**

but now I'm noob....

Thank you very much 

Let me try the process that you said of decode...

**Comment by AudienceX** [comment]
> > abe33738f1825469
> 
> you first convert it into byte array, `[0xAB, 0xE3, 0x37, ...]`, and then encode this byte array with base64.

emmmmm....

I'm trying to use java to simulate the process you said . But maybe I do something wrong... So could you please help me find what's the problem?


```Java
import java.io.* ;
import java.util.Arrays;
import java.util.Base64;

public class HelloWorld {
    public static void main(String []args) {
        byte[] ascii = "83e968fc89ec0038".getBytes(); 
        String byteArray = Arrays.toString(ascii);
	System.out.println("contents of byte array in default encoding: " + byteArray); 
	String base64Str = Base64.getEncoder().encodeToString(ascii);
	System.out.println("base 64 code: " + base64Str); 
    }
}

```

```Java
>>>
contents of byte array in default encoding: [56, 51, 101, 57, 54, 56, 102, 99, 56, 57, 101, 99, 48, 48, 51, 56]
base 64: ODNlOTY4ZmM4OWVjMDAzOA==
```

the traceid I got from Jaeger UI  is "83e968fc89ec0038", and from the java code I got base64 code  "ODNlOTY4ZmM4OWVjMDAzOA==", which can't be found in Kafka msg

the traceId in kafka msg more like "AAAAAAA........."

**Comment by yurishkuro** [comment]
`byte[] ascii = "83e968fc89ec0038".getBytes(); `

This returns a byte for every character in the string. You need to _convert_ the string to bytes using hex encoding.

**Comment by AudienceX** [comment]
> `byte[] ascii = "83e968fc89ec0038".getBytes(); `
> 
> This returns a byte for every character in the string. You need to _convert_ the string to bytes using hex encoding.

There's gotta be someway to complaint someone like you who perverted my mind!

Look at this !  [ids.go](https://github.com/jaegertracing/jaeger/blob/95331addaa0cccb628b363542c5064958e9a2ccc/model/ids.go)


``` Go
// TraceIDFromString creates a TraceID from a hexadecimal string
func TraceIDFromString(s string) (TraceID, error) {
	var hi, lo uint64
	var err error
	switch {
	case len(s) > 32:
		return TraceID{}, fmt.Errorf("TraceID cannot be longer than 32 hex characters: %s", s)
	case len(s) > 16:
		hiLen := len(s) - 16
		if hi, err = strconv.ParseUint(s[0:hiLen], 16, 64); err != nil {
			return TraceID{}, err
		}
		if lo, err = strconv.ParseUint(s[hiLen:], 16, 64); err != nil {
			return TraceID{}, err
		}
	default:
		if lo, err = strconv.ParseUint(s, 16, 64); err != nil {
			return TraceID{}, err
		}
	}
	return TraceID{High: hi, Low: lo}, nil
}
```

That 's what you say **standard base64**

Fuck!

**Comment by yurishkuro** [comment]
Your original question was how to convert an ID from JSON:

> I'm using kafka in Jaeger System, and I got traceid like "AAAAAAAAAABx3MgiIQRHEg=="

This ^^ is base64 encoding.  TraceIDFromString() converts from hex encoding.

**Comment by AudienceX** [comment]
> Your original question was how to convert an ID from JSON:
> 
> > I'm using kafka in Jaeger System, and I got traceid like "AAAAAAAAAABx3MgiIQRHEg=="
> 
> This ^^ is base64 encoding. TraceIDFromString() converts from hex encoding.

So what is the difference ？
I want to covert an id  from Kafka JSON to  an hex ID which  in jaeger UI
And then I  ask how an id  convert from original ID to hex ID 
You said that "If you're trying to get to a hex ID, you need to decode to a byte array first and then convert bytes to hex. The online converter tries to interpret those bytes as string"

But from the code in **ids.go**, I  know that It's not stand hex convert. 

To trans Hex ID to base64 ID, or trans Base64 ID to Hex ID, I must transfer some fucntions in **ids.go** from Go to Python or Java or any language I need

That‘’s not ** standard** at all

**Comment by nata7che** [comment]
any news here? references to converters would be great..

**Comment by Rishi0405** [comment]
It May be too late, but hopefully this will help

maven dependency
```
<dependency>
    <groupId>commons-codec</groupId>
    <artifactId>commons-codec</artifactId>
    <version>1.15</version>
</dependency>
```
Imports
```
import org.apache.commons.codec.binary.Base64;
import static org.apache.commons.codec.binary.Hex.encodeHex;
```
code
```
final String encoded = "PK0fIykrpiGLttuOy9Y2FA==";
final String traceid = new String(encodeHex(Base64.decodeBase64(encoder)));
```

I guess the traceid/spanid is in string format, if it is bytestring then use `.toByteArray()`
