### ISSUE TITLE
Bump go-plugin to 1.3 accidentally reverted

### ISSUE THREAD

**Issue by chlunde** [jaegertracing/jaeger#2593]
This change was accidentally reverted (I checked with Pavol). I think the change is as simple as `go get github.com/hashicorp/go-plugin@v1.3.0; go mod tidy; git add go.sum go.mod; cd cmd/opentelemetry/; go mod tidy; git add go.sum`.

One thing I wonder is why the previous change modified `go.sum` in `cmd/opentelemetry/`. I see the replace directive there, but I wonder if *tidy* is the best approach to update `go.sum`, and if there is any point in doing it at all.

**To Reproduce**
1. Check version in go.mod

**Expected behavior**
Find 1.3 since #2261 is merged.

**Comment by yurishkuro** [comment]
Put a PR?
