### ISSUE TITLE
ingester  crash

### ISSUE THREAD

**Issue by yangvipguang** [jaegertracing/jaeger#2603]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11416887/97555246-d6c68500-1a12-11eb-9315-5a59c5ca28ec.png)
is it a bug?

**Version (please complete the following information):**
 - OS: [e.g. Linux]  Linux
 - Jaeger version: [e.g. 1.8]  1.20
- Deployment: [e.g. bare metal, Docker, Kubernetes, ...]  K8S 1.16

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

I have tried several times

**Additional context**

**Comment by objectiser** [comment]
@yangvipguang Have you specified the `ingester.deadlockInterval` property? The message appears to indicate you haven't.

See description of this flag in https://www.jaegertracing.io/docs/1.20/cli/#jaeger-ingester.

I'll close this issue for now - but if that doesn't fix your issue please reopen with details of how you are running the ingester.

**Comment by yangvipguang** [comment]
@objectiser  yes i just found that  i have fixed it .

**Comment by yurishkuro** [comment]
I think we can have a better error message.
