### ISSUE TITLE
UI find nothing

### ISSUE THREAD

**Issue by yangvipguang** [jaegertracing/jaeger#2604]
I have configured agent as daemonset But I can't  find my application in the ui.
![image](https://user-images.githubusercontent.com/11416887/97561209-c0bcc280-1a1a-11eb-8cf5-25252393f738.png)

But the daemon aget log looks like everything is ok.
![image](https://user-images.githubusercontent.com/11416887/97561180-b5699700-1a1a-11eb-8cf2-780a89012e65.png)

![image](https://user-images.githubusercontent.com/11416887/97561237-d16d3880-1a1a-11eb-8098-bf6c86d5b0b7.png)

**Comment by jpkrohling** [comment]
Have you followed the [troubleshooting guide](https://www.jaegertracing.io/docs/1.20/troubleshooting/)? Have you tried starting the daemonset with debug level logging? What do you see in the metrics endpoint?

**Comment by yangvipguang** [comment]
@jpkrohling  Yes i have read the guide 。daemonset has debug  level  log 。 Should I  change my appliction with opentracing or just any appliction。
