### ISSUE TITLE
Unable to start jaeger with Docker on windows 10

### ISSUE THREAD

**Issue by sreaswar** [jaegertracing/jaeger#2607]
**Describe the bug**
 Jaeger tracing fails to start (consistently reproducible) with docker-compose on Windows 10 Hyper-V 
Cannot start service jaeger: Ports are not available: unable to list exposed ports: Get "http://unix/forwards/list": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**To Reproduce**
1.   docker compose file 
jaeger:
    image: jaegertracing/all-in-one:1.13
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"

2.  docker-compose up -d

**Expected behavior**
the container image is loaded (this works)
The container is started - this step fails
Cannot start service jaeger: Ports are not available: unable to list exposed ports: Get "http://unix/forwards/list": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Screenshots**

**Version (please complete the following information):**
 - OS: Windows 10 Version 1909
 - Jaeger version: [e.g. 1.13)
 - Deployment: Docker on Hyper-V  
   Docker Desktop 2.4.0.0
   Engine 19.03.13 Compose 1.27.4
**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.
I did not find anything in the troubleshooting section relevant to my problem.
On Docker i did try a few things such as manual DNS configuration (the docker compose file has other images that start successfully)

**Additional context**

**Comment by yurishkuro** [comment]
I think you've already identified the issue: `Ports are not available`. It's not an issue with Jaeger, but with your environment.
