### ISSUE TITLE
Allow es configuration from yaml

### ISSUE THREAD

**Issue by Vemmy124** [jaegertracing/jaeger#2612]
I'd like to use elasticsearch exporter from opentelemetry-collector, but there is no way to set env variables, which could have effect

## Problem - what in Jaeger blocks you from solving the requirement?
Some of the options cannot be put via yaml file, which is the only way to set up config from collector, for example these ones https://github.com/jaegertracing/jaeger/blob/master/pkg/es/config/config.go#L57

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Let's expose them or discuss this problem with opentelemetry

**Comment by pavolloffay** [comment]
The excluded conf properties are excluded for a reason. E.g. the ES implementation in the OTEL build does not use bulk processor and instead the OTEL batch processor with queue-retry should be used.

**Comment by Vemmy124** [comment]
Thank you!
