### ISSUE TITLE
jaeger-collector unknown flag: --es.server-urls

### ISSUE THREAD

**Issue by tinyRatP** [jaegertracing/jaeger#2616]
**Describe the bug**

jaeger-collector cannot work with the option `--es.server-urls`.

**To Reproduce**
1. Download the jaeger version: 1.20.0
2. Unzip it.
3. ./jaeger-collector --es.server-urls="http://localhost:9200"

**Expected behavior**

just work.

**Screenshots**

```text
Use "jaeger-collector [command] --help" for more information about a command.

unknown flag: --es.server-urls
```

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.20.0
 - Deployment: binary

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

**Comment by objectiser** [comment]
@tinyRatP you need to set the `SPAN_STORAGE_TYPE` env var:
```
SPAN_STORAGE_TYPE=elasticsearch ./jaeger-collector --es.server-urls="http://localhost:9200"
```
