### ISSUE TITLE
opentelemetry sdk: unknown service opentelemetry.proto.collector.metrics.v1.MetricsService

### ISSUE THREAD

**Issue by meilihao** [jaegertracing/jaeger#2620]
**Describe the bug**
opentelemetry client demo report: `rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.metrics.v1.MetricsService`

**To Reproduce**
1. start jaeger

```bash
# vim config.yaml
exporters:
  jaeger_elasticsearch:
    es:
      server-urls: http://elasticsearch:9200
      num-replicas: 1
processors:
  attributes:
    actions:
      - key: user
        action: delete
service:
  pipelines:
    traces:
      processors: [attributes]
# docker run --rm -it --net host -v ${PWD}:/config \
    -e SPAN_STORAGE_TYPE=elasticsearch \
    jaegertracing/opentelemetry-all-in-one \
    --config-file=/config/config.yaml \
    --es.server-urls=http://localhost:9200 \
    --es.num-shards=1
```

2. run [opentelemetry client](https://github.com/meilihao/demo/tree/master/opentelemetry/exporter_otelcol)

**Expected behavior**
no error and jaeger ui display result.

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: opentelemetry-all-in-one:latest
 - Deployment: Docker

**Additional context**
`opentelemetry client + opentelemetry-collector + docker jaegertracing/all-in-one` is ok

**Comment by yurishkuro** [comment]
The config file does not define any pipeline for the metrics.

cc @jpkrohling @joe-elliott

**Comment by joe-elliott** [comment]
I'm unable to reproduce this issue either from master or using the all in one docker container.  

@meilihao are you saying that the error was coming from the all-in-one?  Or from your client code?

**Comment by meilihao** [comment]
@joe-elliott error message from client code.

@yurishkuro Where can I find examples of configuration files for opentelemetry-all-in-one?

**Comment by joe-elliott** [comment]
So my guess is that your client is pointing to Jaeger, but Jaeger does not support the metrics part of the OTel service and you are getting that error.

I don't believe it makes sense for Jaeger to support the OTel metrics service.  Is there a way you can disable it?  Or point it somewhere else?

**Comment by meilihao** [comment]
ok, i will use opentelemetry client + opentelemetry-collector + jaeger + prometheus.
