### ISSUE TITLE
1.21 release

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2627]
It feels like a good time to do a new release. Any critical PRs we want to wait for?

@jaegertracing/jaeger-maintainers

**Comment by jpkrohling** [comment]
+1 on releasing it

**Comment by objectiser** [comment]
https://github.com/jaegertracing/jaeger/pull/2482 needs to be merged.

Nothing critical for me.

**Comment by joe-elliott** [comment]
+1

**Comment by yurishkuro** [comment]
I can do it this w/e

**Comment by jpkrohling** [comment]
How about we let our newest maintainer do the next release? It's a good way to test whether the instructions are still accurate.

**Comment by joe-elliott** [comment]
Yup, I'll give this a shot today.  Will discuss in the bi-weekly.
