### ISSUE TITLE
Inclusion of non-instrumented services

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2628]
The other day we added the ability to render uninstrumented services that are referenced in the leaf spans via `peer.service` tag (https://github.com/jaegertracing/jaeger-ui/pull/659).

This opens up a larger can of worms - should these services show up:
  * as pills in the trace row in the Search result?
  * in the Services dropdown on the Search page? And if they do, should the search bring back the traces that indirectly refer to those services?
  * in the service dependency graphs? (I always wanted them to)

**Comment by objectiser** [comment]
> as pills in the trace row in the Search result?

Yes, although presented slightly differently to make it clear not a traced service

> in the Services dropdown on the Search page? And if they do, should the search bring back the traces that indirectly refer to those services?

Not sure about this one, as it would imply the other search criteria is applying to spans on that service, which is impossible as no spans exist

> in the service dependency graphs? (I always wanted them to)

Yes, that would be good (again visually distinguished) - and also DDG.
