### ISSUE TITLE
Example of a client posting to collector over HTTP

### ISSUE THREAD

**Issue by mnaga** [jaegertracing/jaeger#266]
From the documentation I see that the collector has a http port as well and the span data can be sent directly from clients. Is there any example or documentation around the http endpoint? 

To provide some context, we have a home grown instrumentation around our services and as a first step would like to post that data to jaeger and am trying to see whats the best option.

14268 | HTTP | can accept spans directly from clients in Jaeger or Zipkin Thrift

**Comment by yurishkuro** [comment]
jaeger-client-go  & java can be configured to use HTTP sender instead of UDP sender, you can probably use those as it and give them spans (might not work if spans have private data that you cannot provide directly, but at least you can see the code for the sender).

**Comment by yurishkuro** [comment]
Closing as the docs requirement is covered by #456
