### ISSUE TITLE
Ruby / Rails client

### ISSUE THREAD

**Issue by jalberto** [jaegertracing/jaeger#268]
Is it there any work to add a ruby client? 

If it is not, Is it possible to use zipkin-ruby with jaeger?

**Comment by yurishkuro** [comment]
There is currently no Jaeger client in Ruby. A contribution would be awesome (but I don't think Ruby opentracing API is finalized).

I don't know how `zipkin-ruby` sends the traces out of process, but if it's in zipkin thrift format over HTTP, then Jaeger backend can accept them.

**Comment by jalberto** [comment]
do you mean this one? https://github.com/opentracing/opentracing-ruby

**Comment by yurishkuro** [comment]
Yes. I didn't follow it too closely as I don't know Ruby that well, but it looks like it might be in the "released" state already. @tedsuo do you know what the state of Ruby API?

**Comment by jalberto** [comment]
I would be able to help in ruby side of things :)

**Comment by yurishkuro** [comment]
So as a guideline, the following is a rough outline for getting a new client out:

1. setup new project, travis build, code coverage, release publishing, etc.
2. implement basic tracer & span functionality with a simple 100% sampling & a configuration mechanism
3. implement remote reporter with abstract sender
4. implement UDP or HTTP sender or both
5. implement other samplers (probabilistic, rate limiting)
6. implement remote sampler that pulls sampling strategy from the agent
7. implement adaptive sampler
8. optionally other features like baggage whitelisting

Steps 5-8 could be added later, 1-4 are needed to get a minimal viable client.

**Comment by jalberto** [comment]
I will need to get familiar with opentrace first

**Comment by tedsuo** [comment]
@yurishkuro I've been concentrating on Java/Python/C++11, was going to look at ruby after python. The ruby API will need context management at some point just like the others, but otherwise I can say it is in production and working at LightStep.

**Comment by indrekj** [comment]
I published a very basic ruby client some time ago: https://github.com/salemove/jaeger-client-ruby

**Comment by jpkrohling** [comment]
@indrekj would you be interested in having the Ruby client as part of this organization?

**Comment by danielmbarlow** [comment]
For info I use [opencensus-ruby](https://github.com/census-instrumentation/opencensus-ruby/) in production to communicate with Jaeger via [opencensus-ruby-exporter-jaeger](https://github.com/Thinkei/opencensus-ruby-exporter-jaeger) and I'm pretty happy with it.

Notes:
* OpenTracing and OpenCensus [are merging into OpenTelemetry](https://medium.com/opentracing/a-roadmap-to-convergence-b074e5815289)
* If you want Sidekiq integration [this is what we're using](https://github.com/census-instrumentation/opencensus-ruby/pull/102)

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients.
