### ISSUE TITLE
Lookback value does not affect the x-axis properly

### ISSUE THREAD

**Issue by mmohamadi** [jaegertracing/jaeger#2694]
I set the lookback value to last 2 hours, but the x-axis didn't get affected properly and showed the tracing data of the last minute. 
I also, set a custom range but the same problem occurred.

**Expected behavior**
Expected to see the tracing information of the last 2 hours

**Screenshots**
![Screenshot_20201217_203307](https://user-images.githubusercontent.com/35332133/102519210-72858080-40a7-11eb-9168-fd147f203d18.png)

**Comment by yurishkuro** [comment]
I suspect the x-axis is bounded to the actual data points retrieved from the search. Just because you set 2hr look back does not mean that all points in the last 2hrs were retrieved (the number of traces is subject to the LIMIT parameter).
