### ISSUE TITLE
Jaeger misinterprets a span status code of 1 (UNSET) as error

### ISSUE THREAD

**Issue by dennisjac** [jaegertracing/jaeger#2700]
When a span does not have its status code explicitly set in open-telemetry is defaults to 1 which is `UNSET` but Jaeger then reports this as an error in the UI which is not correct. There exists an explicit status code of 2 that indicates an actual error so Jaeger should only report an error is the status code is 2.

**To Reproduce**
1. Create a span that has a status code of `UNSET`(or don't set a status code at all since this is the default)
2. Jaeger will incorrectly interpret this as an error

**Expected behavior**
Jaeger should not interpret an UNSET status code as an error.

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.21.0
 - Deployment: N/A

**Comment by yurishkuro** [comment]
Jaeger does not accept opentelemetry data model natively, the conversion happens somewhere upstream, either in OTEL SDK or in the OTEL collector. Please describe your setup in more details.

**Comment by dennisjac** [comment]
I'm new to tracing and not entirely sure yet how all of the pieces fit together. With you comment above I looked at the OTEL Jaeger exporter and found that it does the correct thing: 
https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-exporter-jaeger/src/transform.ts#L60

Then I found that this was fixed only six days ago here:
https://github.com/open-telemetry/opentelemetry-js/issues/1757

So it looks the issue is already fixed in the OTEL Jaeger exporter but just hasn't been released yet.
