### ISSUE TITLE
Badger still not  cleaning data in jaegertracing/all-in-one:1.21.0

### ISSUE THREAD

**Issue by dk-lockdown** [jaegertracing/jaeger#2703]
Closing as should be resolved by https://github.com/jaegertracing/jaeger/pull/2613.

If the problem still occurs please reopen.

_Originally posted by @objectiser in https://github.com/jaegertracing/jaeger/issues/1916#issuecomment-729003390_

**Comment by Anna-Katona** [comment]
+1 
The same issue. Despite TTL is 12 hours, there are still *.sst files for the last >3 days.

**Comment by jpkrohling** [comment]
Closing, hoping that this was fixed by the recent upgrade to badger v3. Feel free to reopen if this is still happening.

**Comment by zziawan** [comment]
@jpkrohling  jaeger-all-in-one(1.24.0+) still not clean the log data.  is it possible to set all the configurations of badger by CLI flages?
opts.LevelOneSize = 32 << 20
opts.TableLoadingMode = options.FileIO 
opts.ValueLogLoadingMode = options.FileIO
opts.MaxTableSize = 4 << 20 
opts.NumLevelZeroTables = 1
opts.NumLevelZeroTablesStall = 2
opts.NumMemtables = 1
opts.NumVersionsToKeep = 0
opts.ValueLogFileSize = 32 << 20
