### ISSUE TITLE
make expects a command "esc" that I do not have

### ISSUE THREAD

**Issue by nolash** [jaegertracing/jaeger#2710]
nor do I know what it's supposed to be. any hints?

```
esc -pkg assets -o cmd/query/app/ui/actual/gen_assets.go -prefix jaeger-ui/packages/jaeger-ui/build jaeger-ui/packages/jaeger-ui/build
make: esc: No such file or directory
make: *** [Makefile:233: cmd/query/app/ui/actual/gen_assets.go] Error 127
```

I'm on

* jaeger 1.21.0 (72b9a062e57afa466f30ebe0f547d34a9b57ea26)
* go version go1.15.6 linux/amd64
* archlinux 5.9.14-arch1-1

**Comment by albertteoh** [comment]
@nolash it looks like you'll need to run `make install-tools` as outlined in: https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING.md.

**Comment by nolash** [comment]
That was it. Thanks @albertteoh
