### ISSUE TITLE
Rethink stale bot integration

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2717]
I would like to apply stalebot to PRs automatically without the need for an extra label (currently we require `needs-info`), because most old PRs are pending due to authors not following up, not because maintainers did not review them.

Side Q: why is this issue #2465 not being closed by the bot? It's supposed to close after 7 days, the last update was 21 days ago.

cc @jpkrohling

**Comment by jpkrohling** [comment]
We can add another more appropriate label, like 'waiting-on-author'. My main issue with simply closing PRs automatically without a filter is that we might get a false-positive in there, and I think it's really rude with the author to close their issue/PR without a human getting in touch first. It's also really bad if we threaten to close a PR/issue if it's pending on something on our side.

I'm not sure what's going on with #2465, need to take a closer look.

**Comment by yurishkuro** [comment]
> It's also really bad if we threaten to close a PR/issue if it's pending on something on our side.

There are many ways to prevent a PR from closing after the bot warns that it became stale - we or the author can comment back to extend it, or we can even put a special "hold" tag on it. Whereas the current situation is that the majority of PRs are reviewed, but the authors do not follow up, and we have to explicitly go and tag them to make them eligible for stale bot - that's an unnecessary friction.

**Comment by jpkrohling** [comment]
We can try it, even though I'd prefer to have us review/discuss the open PRs periodically and ping the authors directly. I think we moved a bit in this direction in the past by assigning PRs to maintainers, but that didn't help much.

**Comment by yurishkuro** [comment]
> I'd prefer to have us review/discuss the open PRs periodically and ping the authors directly.

I don't think this manual approach scales. Most maintainers don't have time for that, and just pinging the author can be automated, humans don't add much to that process imo (I don't want to play the role of todoist). I think the bot already does a ping by asking "is anything blocking you..." etc.

**Comment by jpkrohling** [comment]
Alright, we can try it :-)

**Comment by jpkrohling** [comment]
It might be easier to migrate to the [actions/stale](https://github.com/actions/stale). I've seen reliability issues with the "legacy" stale bot before.

**Comment by jpkrohling** [comment]
Might I assign this to you, @Ashmita152?

**Comment by Ashmita152** [comment]
sure @jpkrohling
