### ISSUE TITLE
Golang-based persistence

### ISSUE THREAD

**Issue by reidlai** [jaegertracing/jaeger#2725]
## Requirement - what kind of business use case are you trying to solve?

Would like to explore golang-based persistence instead of using java-based elasticsearch, kafka, and cassandra

## Problem - what in Jaeger blocks you from solving the requirement?

Because java based deployment footprint consumed too much memory/cpu compared with golang and jaeger is golang based solution, would like to see any plugin to integrate like Grafana Loki, NATS, ArangoDB, etc

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Would like to see if jaeger has plugin roadmap so I can easily to create plugin using Loki, NATS, ArangoDB, etc

**Comment by yurishkuro** [comment]
we already have plugin architecture: https://github.com/jaegertracing/jaeger/tree/master/plugin/storage/grpc

**Comment by jpkrohling** [comment]
Closing, as I think this was addressed by @yurishkuro , but feel free to reopen if that's not the case.
