### ISSUE TITLE
Downsampling in query service?

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2727]
It seems we have the wrong scope of these flags, what meaning do they have for the query service?
```
$ SPAN_STORAGE_TYPE=memory go run ./cmd/query help
...
      --downsampling.hashsalt string               Salt used when hashing trace id for downsampling.
      --downsampling.ratio float                   Ratio of spans passed to storage after downsampling (between 0 and 1), e.g ratio = 0.3 means we are keeping 30% of spans and dropping 70% of spans; ratio = 1.0 disables downsampling. (default 1)
...
```

**Comment by jpkrohling** [comment]
I can schedule some time to track this down.

**Comment by joe-elliott** [comment]
The query service adds storageFactory flags here:

https://github.com/jaegertracing/jaeger/blob/e677384baeb9a39a8ec1bf7ec55ed1afc1d35323/cmd/query/main.go#L144

which adds the downsampling flags here:

https://github.com/jaegertracing/jaeger/blob/e677384baeb9a39a8ec1bf7ec55ed1afc1d35323/plugin/storage/factory.go#L170

A quick git blame suggests it has been this way for years.  We could split these methods into `AddReaderFlags` and `AddAllFlags`?  If that makes sense I'll submit a PR.

**Comment by yurishkuro** [comment]
> We could split these methods into AddReaderFlags and AddAllFlags

+1

However, when archive storage is configured query can also write
