### ISSUE TITLE
Kafka for trace storage

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#274]
I feel that Kafka could be a good storage backend because the primary way of discovering traces is over time windows that are short. 

### Basic idea
Have `jaeger-agent` or `jaeger-collector` emit spans into Kafka with the `traceID` as key. Instead of using Cassandra/Elasticsearch as an index, simply operate on the data itself. 

### What charecteristics of Kafka apply?
- Durable, high [read/write throughput](https://engineering.linkedin.com/kafka/benchmarking-apache-kafka-2-million-writes-second-three-cheap-machines) 
- Easy(?) to scale
 
### What charecteristics of traces/spans apply?
- Immutability 

### What is the data model? 
The data model could be a thrift serialized representation of the span.

### How do we combine spans into traces?
Kafka guarantees that all messages for a given key end up on a single partition. Combining spans into traces can be done on consumers by using Kafka's session windows based on traceID during query time. 

This assumes that all spans with a given window fit in memory, which depends on window size and data volume. We might be able to improve upon the session window implementation by making it aware of the service name and operation name, allowing us to quickly discard unwanted spans. 

I think that the viability of Kafka as a backend storage hinges on whether we are able to do this operation quickly for a particular service name. If we aren't, we would need to rely on a streaming solution like Flink, Samza, etc which greatly increase complexity for common use cases. 

### How would search work?
Once we've combined spans into traces, we could use [Lucene-Luwak](https://github.com/flaxsearch/luwak) for searches.

Because we are reading from Kafka, we can easily tell users how far we are into the search process, and how much data remains in the time window. 
We would also be able to keep expanding the time window until we hit a match. 
We would be able to support `tail -f` style searches for debugging, etc. 
Search performance would also be linear wrt the time windows selected, assuming a constant data volume. 

### How about aggregations?
We could use a similar approach to search, and maintain a running percentile, etc. 

### How does adaptive sampling work?
Adaptive sampling parameters can be computed by a kafka consumer, and propagated to kafka producers using kafka itself. We could use the same mechanism for baggage whitelisting and other configuration changes. 

See also: https://github.com/uber/jaeger/issues/212, which argues for not having kafka streaming directly out of Jaeger clients.

**Comment by jpkrohling** [comment]
Can this be closed, or are there still things to be done related to this issue?

**Comment by black-adder** [comment]
Just waiting for https://github.com/jaegertracing/jaeger/pull/880 so that the kafka writing can be enabled

**Comment by jpkrohling** [comment]
Could then #880 include a "Resolves" keyword followed by this issue's number, so that this one gets closed once that is merged?
