### ISSUE TITLE
Kerberos authentication for KDCs like Active Directory that do not support FAST negotiation

### ISSUE THREAD

**Issue by kaz-zahed** [jaegertracing/jaeger#2744]
## Requirement - what kind of business use case are you trying to solve?

Kerberos authentication for KDCs like Active Directory that do not support FAST negotiation.

## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger does not expose the configuration property that allows disabling FAST negotiation for Kerberos authentication.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Shopify/sarama Kafka library exposed this configuration property with release v1.27.0 with this [pull request](https://github.com/Shopify/sarama/pull/1466). Jaeger's Kafka Kerberos authentication configuration can be updated to allow configuring this property.

**Comment by pmuls99** [comment]
Hey @kaz-zahed, @yurishkuro seems like the PR raised for this issue is closed. Could I take this up and raise a PR?

**Comment by yurishkuro** [comment]
Feel free to try

**Comment by pmuls99** [comment]
Hey @yurishkuro , I just raised a PR (#4520)addressing the issue. Could you please take a look and give me pointers on improvement!
