### ISSUE TITLE
Remove temporary usage of a Thrift fork

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2781]
The PR #2780 introduced the usage of a personal fork for Apache Thrift Go libraries to address a memory problem with the agent. Once a new version of Thrift is released that includes the fix, we need to revert that and use the official library again.

**Comment by jpkrohling** [comment]
Looks like Thrift 0.14 is now released: https://github.com/apache/thrift/releases/tag/v0.14.0

Any takers?

**Comment by albertteoh** [comment]
I can take a look at this.

**Comment by albertteoh** [comment]
@jpkrohling is there a way to confirm that this new thrift tag fixes issues #2638 and #2452? I also tried the reproducer in https://github.com/jaegertracing/jaeger/issues/2638#issuecomment-742592854 but I see the following output:
```
$ go run main.go
error while processing: *jaeger.Batch error reading struct: *jaeger.Span error reading struct: EOF
memory usage before: 0 MiB
memory usage after: 0 MiB
finished
```
I was expecting some non-zero memory usage numbers and no error; but maybe I'm wrong?

@Mario-Hofstaetter, @zigmund: Were you able to confirm that changes in #2780 fixed the memory leak issue?

**Comment by zigmund** [comment]
@albertteoh is there docker image containing https://github.com/jaegertracing/jaeger/pull/2780?
Or I should use `jaegertracing/jaeger-agent:latest`? Docker hub says it was pushed last time 2 days ago.

**Comment by jpkrohling** [comment]
`jaegertracing/jaeger-agent:latest` should indeed contain the fix.

**Comment by jpkrohling** [comment]
> @jpkrohling is there a way to confirm that this new thrift tag fixes issues #2638 and #2452? I also tried the reproducer in [#2638 (comment)](https://github.com/jaegertracing/jaeger/issues/2638#issuecomment-742592854) but I see the following output:
> 
> ```
> $ go run main.go
> error while processing: *jaeger.Batch error reading struct: *jaeger.Span error reading struct: EOF
> memory usage before: 0 MiB
> memory usage after: 0 MiB
> finished
> ```
> 
> I was expecting some non-zero memory usage numbers and no error; but maybe I'm wrong?
> 

I would also expect something non-zero, but perhaps it's a rounding error? The message printed before that, about the failure to process the batch, is indicative that the problematic package was received and processing stopped. In unpatched versions, this would trigger the excessive memory consumption. In any case, you can also try the reproducer at https://github.com/Mario-Hofstaetter/jaegertracing-jaeger-issue-2638, by @Mario-Hofstaetter.

**Comment by zigmund** [comment]
@jpkrohling running over hour on `jaegertracing/jaeger-agent:latest` without memory issues.

**Comment by jpkrohling** [comment]
@albertteoh if you don't mind, I'll take this one as I have some free cycles and we could really have a new release soon :-)

**Comment by albertteoh** [comment]
Please go ahead @jpkrohling :)

**Comment by jpkrohling** [comment]
I'm blocked by https://issues.apache.org/jira/browse/THRIFT-5353. I think we should move forward with the release without this issue here.

**Comment by yurishkuro** [comment]
Thrift 0.14.1 was released, presumably fixing https://issues.apache.org/jira/browse/THRIFT-5353. We need to try to upgrade to it.
