### ISSUE TITLE
Release Process Broken in GHA

### ISSUE THREAD

**Issue by Ashmita152** [jaegertracing/jaeger#2810]
**Describe the bug**
Hi @jpkrohling  @yurishkuro 

I was testing releases process with my fork and I think I found two problems with docker images part of release process.

- The release version tagged docker images are built by the CI/CD runs for the PR "Preparing release <version>" In travis, dockerhub password was accessible even in the CI/CD triggered by that PR but in GitHub Actions, they aren't accessible for the PR. This will cause failure in docker push part.
- In Travis, docker push [image] (done here: https://github.com/jaegertracing/jaeger/blob/master/scripts/travis/upload-to-registry.sh#L88) used to push all tags for that image. But in GitHub Actions, it is only pushing the "latest" tag. I am trying to find the fix for this.

I will like you to mark this issue as blocker for https://github.com/jaegertracing/jaeger/issues/2734

**To Reproduce**
1. Create a release v1.22.0 in personal fork by following the steps in RELEASE.md

**Expected behavior**
docker images with tags as v1.22.0 should be pushed to personal dockerhub and quay.

**Comment by yurishkuro** [comment]
Hi @Ashmita152 

> In travis, dockerhub password was accessible even in the CI/CD triggered by that PR

I am not sure I follow this one. The secrets are never available in PRs, neither in Travis nor in GHA, because making them available to PRs means someone can always put a PR that simply prints them to logs. The only time secrets are available is when the PR is merged to the main branch, which is also the only time when we want to publish the images to the official repos.

**Comment by Ashmita152** [comment]
Hi Yuri,

I see. Then probably the way BRANCH value was populated in Travis maybe different than that of GHA.

Our script checks for BRANCH var to match regex for release branch which will only happen when CI is triggered from the PR. The CI run after PR merge will have BRANCH as "master". 

Eg. https://github.com/Ashmita152/jaeger/runs/1881177338 run triggered by the PR (BRANCH=v1.22.0) but https://github.com/Ashmita152/jaeger/runs/1881178291 (after merge of PR, has BRANCH=master).

**Comment by yurishkuro** [comment]
> Eg. https://github.com/Ashmita152/jaeger/runs/1881177338 (run triggered by the PR has BRANCH=v1.22.0) but https://github.com/Ashmita152/jaeger/runs/1881178291 (after merge of PR, has BRANCH=master).

Yeah, sounds a bit off, but again, the settings in a PR run are not important since we don't deploy from them. Are you trying to get to the value of 1.22.0? It should not be in the run for the PR merge, but rather for the following run where the tag is applied (by doing a release).

**Comment by Ashmita152** [comment]
> It should not be in the run for the PR merge, but rather for the following run where the tag is applied.

Thank you Yuri. Ah that's right. Sorry my mistake. I was looking at the wrong place. I also created that release with tag and here is the ci-release.yml run: https://github.com/Ashmita152/jaeger/runs/1880765044?check_suite_focus=true
This means there is only one problem: "docker push image" should just push all tags for images which isn't happening right now.
