### ISSUE TITLE
Error when `--es.use-ilm` is set without `--es.use-aliases`

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#2814]
## Requirement - what kind of business use case are you trying to solve?

`--es.use-ilm` must always be used in conjunction with `--es.use-aliases` to ensure ES writers and readers refer to the single index mapping. Otherwise, ILM will not work as it does not have a rollover alias to work on.

As such, we should provide a useful error to users who mistakenly set `--es.use-ilm` without enabling `--es.use-aliases`.

This is a follow-up task to [this PR review comment](https://github.com/jaegertracing/jaeger/pull/2796/files#r571716159).

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The proposal is to add validation at the top of each ES [reader](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/factory.go#L141) and [writer](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/factory.go#L162) constructor with the following logic:
```
if cfg.GetUseILM() && !cfg.GetUseReadWriteAliases() {
	return nil, fmt.Errorf("the error message")
}
```

**Comment by bhiravabhatla** [comment]
Will pick this up

**Comment by bhiravabhatla** [comment]
Error message could be (from description) - "--es.use-ilm must always be used in conjunction with --es.use-aliases to ensure ES writers and readers refer to the single index mapping"?

**Comment by yurishkuro** [comment]
+1
