### ISSUE TITLE
[vote] Promote @albertteoh to maintainer

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2815]
@jaegertracing/jaeger-maintainers, I would like to nominate @albertteoh as our newest maintainer. Here are some stats:

* 30+ PRs merged across all repositories: https://github.com/search?q=org%3Ajaegertracing+is%3Apr+author%3Aalbertteoh+is%3Amerged
* 28 Reviews in the main repository: https://github.com/jaegertracing/jaeger/pulls?q=is%3Apr+reviewed-by%3Aalbertteoh

**Comment by objectiser** [comment]
+1

**Comment by kevinearls** [comment]
+1

**Comment by pavolloffay** [comment]
+1

**Comment by joe-elliott** [comment]
+1

**Comment by yurishkuro** [comment]
+1

**Comment by jpkrohling** [comment]
We have a new maintainer! Welcome, @albertteoh!

**Comment by yurishkuro** [comment]
Need to add to README

**Comment by albertteoh** [comment]
Thanks everyone :)
