### ISSUE TITLE
Unique Docker image tags for opentelemetry components

### ISSUE THREAD

**Issue by sschne** [jaegertracing/jaeger#2817]
## Requirement - what kind of business use case are you trying to solve?

We want to use unique docker image tags to always ensure image versions are consistent. This helps to avoid breaking changes to be automatically deployed to our infrastructure.

## Problem - what in Jaeger blocks you from solving the requirement?

The opentelemetry components are currently only being released with the `latest` tag. 

https://github.com/jaegertracing/jaeger/blob/bf1cb8aecad50668f5cf8c51a4fc6f2e1ce62bec/scripts/upload-to-registry.sh#L83-L86

In our particular case, the opentelemetry-collector component introduced a breaking change by disabling the Zipkin server by default.

**Comment by jpkrohling** [comment]
I'd recommend not using those images for the time being. We changed the strategy for using OpenTelemetry as the base for the new Jaeger, and the final solution is likely to be incompatible with these images.

See https://github.com/jaegertracing/jaeger/discussions/2779

**Comment by sschne** [comment]
Hi, thanks for clarification. We decided to use the standard collector for the moment until Jaeger v2 is ready. Closing.

**Comment by yurishkuro** [comment]
@jpkrohling perhaps we need to change the messaging we have in the docs about the first cut of OTEL-based images.
