### ISSUE TITLE
Do we need to do something to address Docker limits?

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2819]
CNCF has a solution if we need it https://github.com/cncf/servicedesk#my-project-is-affected-by-the-docker-hub-rate-limits-policy-changes-what-can-i-do

What I am not clear on is how we can verify if Jaeger pulls are being rate limited. So far nobody complained, and our own CI jobs were not affected.

**Comment by jpkrohling** [comment]
Good question. Is this still the latest stand?

>    Free plan – anonymous users: 100 pulls per 6 hours 
>    Free plan – authenticated users: 200 pulls per 6 hours
>    Pro plan – unlimited
>    Team plan – unlimited

On Quay, we have more than 18k pulls per day for the es-index-cleaner image: https://quay.io/repository/jaegertracing/jaeger-es-index-cleaner . The second most pulled image seems to be the agent, with about 200 pulls per day, with one day having more than 400 pulls. Given that DockerHub is still the one we use by default everywhere (docs, examples, blog posts, ...), I think we have a higher usage there.

Haven't we requested the limit to be lifted already? I remember seeing that form, just not sure I myself sent the request...

**Comment by pavolloffay** [comment]
@yurishkuro can this be closed?
