### ISSUE TITLE
zstd compression support for Kafka storage

### ISSUE THREAD

**Issue by arnitolog** [jaegertracing/jaeger#2824]
**Describe the bug**
I started to see the error below as soon as I enabled zstd compression on the collector side.
We are on jaeger 1.19.2 and Kafka 2.5.0

{"level":"error","ts":1613990679.9162657,"caller":"kafka/writer.go:58","msg":"zstd compression requires building with cgo enabled","stacktrace":"github.com/jaegertracing/jaeger/plugin/storage/kafka.NewSpanWriter.func2\n\tgithub.com/jaegertracing/jaeger/plugin/storage/kafka/writer.go:58"}

**To Reproduce**
1. configure zstd compression for kafka 

Have I missed something? Will upgrade to the latest Jaeger will help here?

**Comment by jpkrohling** [comment]
If it requires cgo, we will probably remove support for this feature.

**Comment by arnitolog** [comment]
as far as I can see sarama has switched from cgo to pure Go implementation for zstd in 1.24.0: https://github.com/Shopify/sarama/blob/master/CHANGELOG.md#version-1240-2019-10-09
https://github.com/Shopify/sarama/pull/1477

**Comment by jpkrohling** [comment]
In which case, we might want to bump the dependency. Would you like to give it a try?

**Comment by arnitolog** [comment]
yeah, will try to build it locally and see how it works
