### ISSUE TITLE
jaeger-query reports http.url in incorrect format

### ISSUE THREAD

**Issue by W3D3** [jaegertracing/jaeger#2832]
**Describe the bug**
The jaeger-query itself reports traces. These traces do not adhere the [semantic specification for open tracing](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#standard-span-tags-and-log-fields):

The **http.url** should be specified in standard URI format (e.g. "https://domain.net/path/to?resource=here") but only contains the path in this case.

**To Reproduce**
1. Simply look at traces genereated by "jaeger-query" service

**Expected behavior**
I would expect the field http.url to be filled with the full URL, including protocol and host, e.g. "https://hostname/api/services"

**Screenshots**
![image](https://user-images.githubusercontent.com/1103924/109016409-71c82680-76b6-11eb-8db7-cb2186ae2e30.png)

**Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - Jaeger version: jaegertracing/all-in-one:1.20.0
 - Deployment: Kubernetes (Minikube)

**Comment by yurishkuro** [comment]
Full url makes sense in the client spans. Server spans may not have access to scheme/host/port.

**Comment by W3D3** [comment]
I get the issue, but his makes it kind of inconsistent to work with automation software relying on this field being filled with a valid URI, but this is now more or less an issue with the standard and not Jaeger.
I guess this will be no issue when the standard will be changed to OpenTelemetry, as it differentiates between _http.url_ and _http.target_?

**Comment by yurishkuro** [comment]
hopefully OpenTelemetry Go implementation will have instrumentation that follows the standard that we could use.
