### ISSUE TITLE
Wrap the Query and UI as an OpenTelemetry Collector extension

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2838]
For v2, the Query and the UI are going to be packaged in two ways:

- Wrapped as part of an otelcol extension, to be used with the all-in-one distribution
- On its own binary, like today

The business code is pretty much the same, as the extension would just use the same HTTP handlers.

**Comment by pavolloffay** [comment]
Closing as it is a "low level" issue related to V2 which might take a different approach.
