### ISSUE TITLE
Define the list of receivers, processors, and exporters for each binary

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2839]
We talked briefly in the past about the components we want for each binary, and this issue here is to track the state of our agreement. I'm writing from memory, and the final state will evolve based on your comments.

## Agent

Extensions:
- zpages
- Health Check
- pprof
- Remote sampling configuration (client)
- Remote sampling configuration (server)

Receivers:
- Jaeger Thrift via UDP
- Zipkin Thrift via UDP

Processors:
- Batch processor
- Memory limiter

Exporters:
- Jaeger Proto via gRPC
- OTLP via gRPC

## Collector

Extensions:
- zpages
- Health Check
- pprof
- Remote sampling configuration (server)

Receivers:
- Jaeger Thrift via TChannel
- Jaeger Proto via gRPC
- Zipkin Thrift via TChannel
- Zipkin Proto via gRPC
- OTLP via gRPC
- OTLP via HTTP

Processors:
- Batch
- Memory limiter

Exporters:
- Badger
- Elasticsearch
- Cassandra
- Kafka
- Jaeger Proto via gRPC
- OTLP via gRPC

## Ingester

Extensions:
- zpages
- Health Check
- pprof

Receivers:
- Kafka

Processors:
- Batch
- Memory limiter

Exporters:
- Badger
- Elasticsearch
- Cassandra

## All in one

Extensions:
- zpages
- Health Check
- pprof
- Jaeger Query and UI
- Remote sampling configuration (client)
- Remote sampling configuration (server)

Receivers:
- Jaeger Thrift via UDP
- Jaeger Thrift via TChannel
- Jaeger Proto via gRPC
- Zipkin Thrift via UDP
- Zipkin Thrift via TChannel
- Zipkin Proto via gRPC
- OTLP via gRPC
- OTLP via HTTP
- Kafka

Processors:
- Batch
- Memory limiter

Exporters:
- Badger
- Elasticsearch
- Cassandra
- Kafka
- Jaeger Proto via gRPC
- OTLP via gRPC

**Comment by yurishkuro** [comment]
missing sampling configuration servers

**Comment by jpkrohling** [comment]
> missing sampling configuration servers

Added "Remote sampling configuration (client)" and "Remote sampling configuration (server)" to the respective places.

**Comment by pavolloffay** [comment]
Closing as it is a "low level" issue related to V2 which might take a different approach.
