### ISSUE TITLE
Fix archive default values reported for ES and Cassandra

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#2853]
**Describe the bug**
Noticed when @mehta-ankit_gitlab raised the following question in Gitter:
> Question regarding Archive option for Jaeger using Elasticsearch backend.
--es-archive.max-doc-count is set to 0 and --es-archive.max-span-age is set to 0s as default.
Does someone know, if these defaults mean age of the span (inside the archive index) is ignored when querying it.

When checking the `--help` docs, the default values are missing or incorrect for the `*-archive*` flags.

I confirmed the defaults should be the same as the non-archive equivalents as these are the values used for archive flags internally if unset; i.e. this bug only impacts `--help` documentation.

This also impacts the jaeger documentation: https://www.jaegertracing.io/docs/latest/cli/

**To Reproduce**
1. `docker run -e SPAN_STORAGE_TYPE=elasticsearch jaegertracing/jaeger-query --help` .
2. Same problem when changing storage type to `cassandra`.
3. Same problem with `jaeger-collector` as well.

**Expected behavior**
Got: 
```
      --es-archive.max-doc-count int                       The maximum document count to return from an Elasticsearch query. This will also apply to aggregations.
      --es-archive.max-span-age duration                   The maximum lookback for spans in Elasticsearch (default 0s)
      --es-archive.num-replicas int                        The number of replicas per index in Elasticsearch
      --es-archive.num-shards int                          The number of shards per index in Elasticsearch
```

Want:
```
      --es-archive.max-doc-count int                       The maximum document count to return from an Elasticsearch query. This will also apply to aggregations. (default 10000)
      --es-archive.max-span-age duration                   The maximum lookback for spans in Elasticsearch (default 72h0m0s)
      --es-archive.num-replicas int                        The number of replicas per index in Elasticsearch (default 1)
      --es-archive.num-shards int                          The number of shards per index in Elasticsearch (default 5)
```

**Version (please complete the following information):**
 - OS: Linux & MacOS
 - Jaeger version: latest
 - Deployment: Dev

**Additional Context**
I propose the fix should be to share the primary (e.g. non-archive) default configs with all other additional namespaces like `archive`.

**Comment by mehta-ankit** [comment]
Thanks for creating this issue @albertteoh

**Comment by mehta-ankit** [comment]
Wanted to add a couple of other things to this issue:

- It does not sound right, but if someone wants archive option, how would they decide on the `--es-archive.max-span-age` value. Any value they set would mean that once past that value they cannot query the archived span. Doesn't it defeat the purpose of archiving a span ?? 🤔 
- Since I was confused about the default values, i did a test. I manually updated data in the Elasticsearch index (updated the startTime value for a document to be `20` days old) and then tried to view the archived span on the Jaeger Query (using the url i had saved). It did work  for me. If default value of max-span-age was 72h for archived spans, query should not have been able to retrieve that span.

**Comment by albertteoh** [comment]
Fair questions, @mehta-ankit. Short answer is, `--es-archive.max-span-age` is not used when fetching archived traces.

Here's what jaeger-query does when fetching a specific trace by ID:

1. Try to find it in the current index (e.g. `jaeger-span-2021-02-26`):
```
{
  "size": ${es.max-doc-count},
  "terminate_after": ${es.max-doc-count},
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "traceID": {
              "value": "${traceid-to-search}",
              "boost": 2
            }
          }
        },
      ...
  "search_after": [
    ${now - es.max-span-age}
  ]
}
```
2. If not found, [search in the `jaeger-span-archive` index](https://github.com/jaegertracing/jaeger/blob/5062366157fff65a052dc6ac6779e7621054248d/cmd/query/app/querysvc/query_service.go#L75). Note: [`search_after` is omitted from the query](https://github.com/jaegertracing/jaeger/blob/0d2fd6bb74ba71f9834c6d5087ad4fa1620e1c6e/plugin/storage/es/spanstore/reader.go#L170), so `--es-archive.max-span-age` is not used:
```
{
  "size": ${es-archive.max-doc-count},
  "terminate_after": ${es-archive.max-doc-count},
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "traceID": {
              "value": "${traceid-to-search}",
              "boost": 2
            }
          }
        },
        ...
}
```

**Comment by mehta-ankit** [comment]
Thanks for answering my question @albertteoh .
Based on your own answer, don't you think this (what you said in the issue description) is not the correct solution then ?
`I confirmed the defaults should be the same as the non-archive equivalents as these are the values used for archive flags internally if unset; i.e. this bug only impacts --help documentation.`

I feel if `--es-archive.max-span-age` is not used when querying archived spans, then documentation should just say that, and it should not share primary default configs.

What do you think ?

**Comment by albertteoh** [comment]
> I feel if --es-archive.max-span-age is not used when querying archived spans, then documentation should just say that

I agree, however, this only applies to `--es-archive.max-span-age` (as far as I know); `--es-archive.max-doc-count`'s default of `10000` is still used in the query and so showing `0` in documentation is misleading. As such, I still think the correct defaults should be shown in documentation.

I'll see if there's a way to selectively override the help documentation for `archive` namespaces. Currently, I only see the capability to override default values.

**Comment by yurishkuro** [comment]
I thought we had code that would apply primary defaults to archive defaults, but I may be just confusing it with how we reused config files at Uber.

**Comment by albertteoh** [comment]
> I thought we had code that would apply primary defaults to archive defaults, but I may be just confusing it with how we reused config files at Uber.

Yup, we have the means to apply primary defaults to archive defaults, but the primary default isn't passed into archive defaults, leading to the config's zero-values being adopted: https://github.com/jaegertracing/jaeger/blob/bf1cb8aecad50668f5cf8c51a4fc6f2e1ce62bec/plugin/storage/es/options.go#L114

We can see this reflected in the CLI help docs:

<img width="756" alt="Screen Shot 2021-03-02 at 11 39 45 am" src="https://user-images.githubusercontent.com/26584478/109578895-1e3d5900-7b4c-11eb-97f0-c22faad88d62.png">

@yurishkuro please let me know if I'm missing something, or perhaps it was intentionally omitted for a good reason.

**Comment by yurishkuro** [comment]
no good reason afaik. More like complicated code to allow both CLI-based and struct-based configuration (where structs are populated from configs)

**Comment by albertteoh** [comment]
Maybe that's why there's the `TODO` comment to use Cobra.

**Comment by albertteoh** [comment]
@mehta-ankit another option is to default `--es-archive.max-span-age` to the maximum allowable duration in Go (290 years) which is effectively the same as omitting the "lookback" time filter in the ES query. I think this is better than `0s` and the default `72h` which I think are both misleading, even in the presence of updating the documentation to indicate it is not used.

What do you think?

**Comment by mehta-ankit** [comment]
I feel ideal solution is to not show the flag that is not used in code (as overwriting it has no impact).

But if we cannot do it (if it's not trivial) I agree that a large enough values makes it clear what time limit would be used for search and hence what spans might be returned. (which is all 😄 ). So i agree this is better than showing `0s` or `72h`
