### ISSUE TITLE
Publish test report

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2859]
One feature I always missed from Jenkins was the ability to easily view the test report for a specific run, and apparently, there's a good candidate for this feature being proposed for the otelcol repository:

https://github.com/open-telemetry/opentelemetry-collector/pull/2531
https://github.com/EnricoMi/publish-unit-test-result-action

We should try it out in this repository as well.

**Comment by yurishkuro** [comment]
+1

**Comment by sheetalsingala** [comment]
Can I give this a try?

**Comment by yurishkuro** [comment]
go for it

**Comment by yurishkuro** [comment]
@samyakjain10 why do you think it's resolved? I don't believe it is.
