### ISSUE TITLE
COLLECTOR_ZIPKIN_HTTP_PORT does not work for jaegertracing/jaeger-collector 1.22.0

### ISSUE THREAD

**Issue by uqix** [jaegertracing/jaeger#2864]
**Describe the bug**

With env var `COLLECTOR_ZIPKIN_HTTP_PORT=9411`,  jaeger-collector 1.22.0 prints `Not listening for Zipkin HTTP traffic, port not configured`.

**To Reproduce**

1. Run jaeger-collector 1.22.0 with `COLLECTOR_ZIPKIN_HTTP_PORT=9411`
2. See logs

**Expected behavior**

`Listening for Zipkin HTTP traffic","zipkin host-port":":9411` as in v1.21.0

**Screenshots**
![image](https://user-images.githubusercontent.com/10142314/110119711-24a32d80-7df7-11eb-9efd-a55cf65fffa2.png)
![image](https://user-images.githubusercontent.com/10142314/110119737-2c62d200-7df7-11eb-89ee-91b0f16d7525.png)

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.22.0
 - Deployment: Kubernetes

**Comment by airen29** [comment]
I have the same issue and for now I did not find any solution.

**Comment by albertteoh** [comment]
@uqix Jaeger v1.22.0 has removed `COLLECTOR_ZIPKIN_HTTP_PORT` which was deprecated in an earlier release. Please use `COLLECTOR_ZIPKIN_HOST_PORT` instead:

```
 --collector.zipkin.host-port string                  The host:port (e.g. 127.0.0.1:9411 or :9411) of the collector's Zipkin server (disabled by default)
```

For more details on flags that have been removed due to an expired deprecation notice, please refer to: https://github.com/jaegertracing/jaeger/releases/tag/v1.22.0.

**Comment by airen29** [comment]
@albertteoh We are installing it via `helm chart` option (https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml) and there is still the same value. 

So I guess change in helm chart is also needed.

**Comment by yurishkuro** [comment]
I was going to transfer the issue, but I see a new one was opened in helm-charts, so closing this.

**Comment by nsphung** [comment]
Please update the documentation https://www.jaegertracing.io/docs/1.22/getting-started/#all-in-one to reflect this deprecation.

**Comment by yurishkuro** [comment]
@nsphung good call out, thanks. https://github.com/jaegertracing/documentation/pull/479
