### ISSUE TITLE
Make tracing headers configurable

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger#287]
By default Jaeger clients use uber-trace-id and uberctx- headers for propagating trace context. Some people asked to have those be configurable.

- [x] [go](https://github.com/uber/jaeger-client-go/pull/176)
- [ ] python
- [ ] java
- [ ] node 

To do: needs justification, since headers also imply value format, so it's strange to want to only change the header keys. If people simply want to use their own names instead of Uber's, then it's ill advised as it creates incompatible propagation format. We should rather support w3c standard.

**Comment by jpkrohling** [comment]
What is this about, @black-adder?

**Comment by yurishkuro** [comment]
I updated the description. I think we should close it.

**Comment by jpkrohling** [comment]
> We should rather support w3c standard

This is the key part, IMO.
