### ISSUE TITLE
Remove deprecated --span-storage.type flag

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#2875]
The deprecation notice was [first made on 8th Jan 2018](https://github.com/jaegertracing/jaeger/commit/8db7a11f21abc7433715741bdfdd5b873f866cd9#diff-caefdd9a976b1f008470978057e0b48f4d15e0dfdc8ae1fa7a0d7023ff68f888R61), which exceeds both the [3 month and N+2 release](https://github.com/jaegertracing/jaeger/issues/2113) deprecation expiry policy.

**Comment by yurishkuro** [comment]
This one is tricky, since the respective env var is not deprecated and is the only other way to set the storage type. I would suggest leaving this alone until v2.

**Comment by albertteoh** [comment]
Ah of course, I'll close this issue for now, thanks.
