### ISSUE TITLE
Add test facility to load traces from JSON files

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2884]
Context: https://github.com/jaegertracing/jaeger/pull/2882#discussion_r595217825

For v2, it would be good to have a facility that converts traces in JSON to OpenTelemetry Collector's `pdata.Traces`, to use as part of our tests.

**Comment by yurishkuro** [comment]
Standard protobuf has json serialization.

**Comment by jpkrohling** [comment]
pdata isn't protobuf, from what I remember. There should be some translation facility as part of OpenTelemetry Core though.

**Comment by dbgoytia** [comment]
Hi @jpkrohling, is someone actively participating on this issue? I'd like to contribute!

**Comment by jpkrohling** [comment]
I don't think anyone is working on it.
