### ISSUE TITLE
Jaeger Showing 2 Traces With Same MessageId

### ISSUE THREAD

**Issue by carlyn12** [jaegertracing/jaeger#2887]
**Describe the bug**
I have two simple spring boot apps that communicate over jms and implement 
opentelemetry auto tracing with jaeger. When sending the traces to my local jaeger instance, I see two different traces showing where one is correctly showing both spans end-to-end and the other appears to be a duplicate that has the same messageId as the consumer. 

**To Reproduce**
1. built both apps with maven
2. start jaeger-all-in-one docker container 
3. run the applications with the following command: 
```java -Dotel.traces.exporter=jaeger \
-Dotel.metrics.exporter=none \
-Dotel.exporter.jaeger.endpoint="http://localhost:14250" \
-Dotel.resource.attributes=service.name="OTLJmsAuto" \
-Dotel.traces.sampler="always_on" \
-Dotel.instrumentation.jms.enabled=true \
-Dapplication.home=./ \
-Dapplication.name=producer \
-javaagent:./opentelemetry-javaagent-all.jar \
-jar ./target/producer-0.0.1-SNAPSHOT.jar
```

4. navigate to http://localhost:16686/search and see two different traces showing(see screenshots)

**Expected behavior**
Only the top trace should show which includes two spans(producer and consumer).

**Screenshots**
![Producer](https://user-images.githubusercontent.com/80895904/111642837-d0278700-87d4-11eb-9b96-bd1b408adde6.png)
![Consumer](https://user-images.githubusercontent.com/80895904/111642838-d0c01d80-87d4-11eb-8e1d-cba881097e66.png)
![Process](https://user-images.githubusercontent.com/80895904/111642841-d0c01d80-87d4-11eb-93b4-3341b941faab.png)
![SearchPage](https://user-images.githubusercontent.com/80895904/111642842-d0c01d80-87d4-11eb-8fac-c247a7be9c07.png)
![Receive](https://user-images.githubusercontent.com/80895904/111642843-d0c01d80-87d4-11eb-9e25-ac966c34e6e3.png)

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.22
 - 
**What troubleshooting steps did you try?**
Tried upgrading dependency versions as well as using the latest version of opentelemetry-javaagent-all.jar. Tried with debug mode.

**Comment by jpkrohling** [comment]
I'm afraid this is the wrong repository for this issue. Please, report it against the OpenTelemetry Java instrumentation, which is where you get the instrumentation libraries. In your case, Jaeger is only responsible for the backend.
