### ISSUE TITLE
Error/warn if TLS flags are used when tls.enabled=false

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#2893]
## Requirement - what kind of business use case are you trying to solve?

Motivated by [this comment in Slack](https://cloud-native.slack.com/archives/CGG7NFUJ3/p1616518570051700):
> we tried the CLI flag --es.tls.skip-host-verify and the enviornment variable ES_TLS_SKIP_HOST_VERIFY
> Neither one seems to have an effect
> ...
> Found the issue, you also need to set --es.tls.enabled/ES_TLS_ENABLED 🤦 

## Problem - what in Jaeger blocks you from solving the requirement?

The user was, rightfully, confused when the `--es.tls.skip-host-verify` was set but wasn't working.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Log a warning or error if any `--*.tls.*` flag is set when `--*.tls.enabled == false`, maybe somewhere [here](https://github.com/jaegertracing/jaeger/blob/master/pkg/config/tlscfg/flags.go#L73) and [here](https://github.com/jaegertracing/jaeger/blob/master/pkg/config/tlscfg/flags.go#L89).

## Any open questions to address

Should we log a warning or error (and prevent startup of service)? I would lean towards the latter to be more explicit, though I think it would be considered "breaking" behaviour. The former warning could be easily missed.

**Comment by yurishkuro** [comment]
+1 to crash

**Comment by LostLaser** [comment]
I would like to pick this one up. Is there a consensus that this incorrect configuration should be fatal?

**Comment by albertteoh** [comment]
@LostLaser I think an incorrect configuration should be fatal rather than just being logged and my understanding is @yurishkuro is on the same page (but please correct me if I'm wrong).

**Comment by yurishkuro** [comment]
Agreed

**Comment by jpkrohling** [comment]
@LostLaser it's yours :-)

**Comment by clock21am** [comment]
is there activity on this issue? if not can I take this over?

**Comment by albertteoh** [comment]
@LostLaser are you okay with @clock21am taking over this task?

**Comment by LostLaser** [comment]
Yes, that’s fine! Sorry for the delay.

**Comment by clock21am** [comment]
it should fail for both clients and sever side if I am not right?

**Comment by albertteoh** [comment]
> it should fail for both clients and sever side if I am not right?

IIUC, the TLS flags should only apply to the server side, and so should fail for just the server side.
