### ISSUE TITLE
Bump github.com/go-openapi/strfmt

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2930]
The PR #2913 opened by dependabot brought a new version of github.com/go-openapi/strfmt, which seems to have a few API incompatibilities with the previous version. This ticket is about making the necessary changes so that we can upgrade to a newer version.

**Comment by KrishnaSindhur** [comment]
can I look into it

**Comment by jpkrohling** [comment]
It's yours, @KrishnaSindhur

**Comment by ampaire** [comment]
@jpkrohling,  looks like this issue was not resolved. @KrishnaSindhur can I help?

**Comment by jpkrohling** [comment]
@ampaire, it's yours now!

**Comment by clock21am** [comment]
@jpkrohling it no update has been made can I take this issue?

**Comment by jpkrohling** [comment]
Closed by #2800
