### ISSUE TITLE
ES index rotation mode can choice with day and hour

### ISSUE THREAD

**Issue by WalkerWang731** [jaegertracing/jaeger#2933]
## Requirement - what kind of business use case are you trying to solve?

As our Jaeger span count increasing, more and more large ES index size, the large size index will be caused more performance issues for the ES side. To avoid this issue, an hourly rotate index is the most convenient option when in systems with large amounts of data. 
I think can provide a parameter for the user choice, the default is "day" mode (like that current) user also can change to "hour" mode
let me create a PR to finish it

**Comment by pavolloffay** [comment]
Did you consider to use the rollover configuration?

**Comment by WalkerWang731** [comment]
> Did you consider to use the rollover configuration?

Yeah, I have considered that on [here](https://github.com/jaegertracing/jaeger/pull/2935#issuecomment-821046608)
