### ISSUE TITLE
Can't receive spans with otlp protocol

### ISSUE THREAD

**Issue by heruv1m** [jaegertracing/jaeger#2934]
There is no mention in jaeger's documentation about otlp support in the last version, but it was in [previous version](https://www.jaegertracing.io/docs/1.21/opentelemetry/)
Also I found an unofficial [example](https://rehansaeed.com/exporting-open-telemetry-data-to-jaeger/) but it doestn't work too.
Is otlp still supported by jaeger? 
How can I configure jaeger to receive spans(traces)?

**Comment by jpkrohling** [comment]
A preview component in a previous version was able to ingest OTLP spans. The main binaries were never able to ingest that. We decided to change our approach to OpenTelemetry, making it our new base for v2, and we are probably going to be able to ingest OTLP by then. I wasn't aware of this example, and it looks like it does use the experimental component (`jaegertracing/opentelemetry-all-in-one`).
