### ISSUE TITLE
ElasticSearch writer race condition 

### ISSUE THREAD

**Issue by mh-park** [jaegertracing/jaeger#294]
There is a race condition in https://github.com/uber/jaeger/blob/master/plugin/storage/es/spanstore/writer.go#L118 where if multiple collectors are writing to a new index at once, one will succeed in creating the index and writing the span, and the others will fail in creating the index and drop the span.

This is not an issue if there is only one collector.

A simple alleviation to this is to create the indices ahead of time.

**Comment by yurishkuro** [comment]
`_, err := s.client.CreateIndex(indexName).Body(spanMapping).Do(s.ctx)`

don't we get a specific error when index already exists? If so we don't have to exit the method with an error

**Comment by mh-park** [comment]
We would have to check if the error contains a certain message, and Won said that's bad practice?
@black-adder

**Comment by yurishkuro** [comment]
are you sure es client doesn't use some errors constants we can check against? If it doesn't, maybe open a ticket there (could even do a PR if simple enough).

**Comment by pavolloffay** [comment]
Fixed in https://github.com/jaegertracing/jaeger/pull/641.
