### ISSUE TITLE
Add requirements.txt for esRollover/Cleaner scripts

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#2940]
## Requirement - what kind of business use case are you trying to solve?

Run `esRollover.py` or `esCleaner.py` just to see help docs.

## Problem - what in Jaeger blocks you from solving the requirement?

Results in the following error if dependencies aren't installed which is not a great user experience:
```
 ./plugin/storage/es/esRollover.py 
Traceback (most recent call last):
  File "./plugin/storage/es/esRollover.py", line 4, in <module>
    import curator
ModuleNotFoundError: No module named 'curator'
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Provide a `requirements.txt` file in `plugins/storage/es` containing the curator dependency needed to run esRollover/Cleaner.py:
```
elasticsearch-curator==5.8.3
```

And instructions in README to run the following to validate dependencies are installed or if not, installs them for the current python environment:
```
pip install -r requirements.txt
```

**Comment by yurishkuro** [comment]
Don't we already have requirements.txt **somewhere**?

If it's somehow derived from ES distribution then perhaps we shouldn't tempt users to run the .py directly, but use a container image that we publish.

**Comment by albertteoh** [comment]
> Don't we already have requirements.txt somewhere?

Nope. Not that I can see in this repo at least.

> If it's somehow derived from ES distribution then perhaps we shouldn't tempt users to run the .py directly, but use a container image that we publish.

Ah yes, I should have looked around a bit more before creating this issue; I'd forgotten we have a docker image for ES rollover/cleanup.

Turns out the dependencies are installed when building the docker image:
https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/Dockerfile.rollover#L6

Thanks, Yuri. Closing this issue.
