### ISSUE TITLE
How to corelate 2 traces ?

### ISSUE THREAD

**Issue by shubhmah57** [jaegertracing/jaeger#2949]
We have a problem, in which backend microservices (preferably written in spring boot)are called from a java based application, and we are using Jaeger to trace. 

When Jaeger is used to tracing, the trace which is generated from the application which is used to call the Backend services isn't getting correlated with the traces generated for backend services.

Can there be any possible solution to the problem without making any change in the code for BE microservices?

**Comment by jpkrohling** [comment]
Could you please rephrase your question? I'm not sure I understood it. If possible, add screenshots to demonstrate the problem you are facing.

**Comment by jkowall** [comment]
@shubhmah57 also please explain the instrumentation library or agent you are using to report the trace data to Jaeger. This sounds like a propagation issue, which is likely due to the trace context not being passed across other non-instrumented components.

**Comment by pavolloffay** [comment]
This seems like instrumentation problem - broken traces due to incorrectly propagated context.
