### ISSUE TITLE
Graceful shutdown by properly handling SIGTERM

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#295]
From https://github.com/uber/jaeger/pull/280 :

> What I think should happen is you tell the health endpoint to start returning Unavailable and then sleep for a couple seconds, and the exit. The main tchannel / http servers will remain in operation during the sleep and allowed to finish service the in-flight requests, while the routing mesh might hopefully detect health check down and stop sending traffic.

**Comment by yurishkuro** [comment]
#2076 still pending.
