### ISSUE TITLE
same arg,2.12-2.2.0 kafka is ok,but 2.11-0.11.0.0 fail

### ISSUE THREAD

**Issue by wenhx8** [jaegertracing/jaeger#2950]
**Describe the bug**

**To Reproduce**
1. 
2.
3.

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - OS: [e.g. Linux]
 - Jaeger version: [e.g. 1.8]
 - Deployment: [e.g. bare metal, Docker, Kubernetes, ...]

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

{"level":"info","ts":1619111640.6141622,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1619111640.6142764,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1619111640.6146374,"caller":"flags/admin.go:105","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1619111640.6147656,"caller":"flags/admin.go:111","msg":"Starting admin HTTP server","http-addr":":14269"}
{"level":"info","ts":1619111640.6148138,"caller":"flags/admin.go:97","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
{"level":"info","ts":1619111640.622844,"caller":"kafka/factory.go:69","msg":"Kafka factory","producer builder":{"Brokers":["10.172.52.74:32047"],"RequiredAcks":1,"Compression":0,"CompressionLevel":0,"ProtocolVersion":"","BatchLinger":0,"BatchSize":0,"BatchMinMessages":0,"BatchMaxMessages":0,"Authentication":"plaintext","Kerberos":{"ServiceName":"kafka","Realm":"","UseKeyTab":false,"Username":"","ConfigPath":"/etc/krb5.conf","KeyTabPath":"/etc/security/kafka.keytab"},"TLS":{"Enabled":false,"CAPath":"","CertPath":"","KeyPath":"","ServerName":"","ClientCAPath":"","SkipHostVerify":false},"PlainText":{"Username":"kafka-tianyan-dyl","Mechanism":"SCRAM-SHA-256"}},"topic":"jaeger-spans"}
{"level":"fatal","ts":1619111641.639278,"caller":"command-line-arguments/main.go:75","msg":"Failed to init storage factory","error":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","stacktrace":"main.main.func1\n\tcommand-line-arguments/main.go:75\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v0.0.7/command.go:838\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v0.0.7/command.go:943\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v0.0.7/command.go:883\nmain.main\n\tcommand-line-arguments/main.go:137\nruntime.main\n\truntime/proc.go:204"}

        env:
        - name: SPAN_STORAGE_TYPE
          value: kafka
        - name: KAFKA_PRODUCER_BROKERS
          value: 'xxx'
        - name: KAFKA_TOPIC
          value: jaeger-spans

        - /go/bin/collector-linux
        - --collector.zipkin.host-port
        - "9411"
        - --kafka.producer.plaintext.username
        - xxxx
        - --kafka.producer.plaintext.password
        - xxxx
        - --kafka.producer.authentication
        - plaintext
        - --kafka.producer.encoding
        - json
        - --kafka.producer.plaintext.mechanism
        - 'SCRAM-SHA-256'
        - --log-level
        - debug

**Comment by pavolloffay** [comment]
@wenhx8 did you resolve this issue?

**Comment by dgoscn** [comment]
Hi @wenhx8. 

Did you resolved the issue?

**Comment by wenhx8** [comment]
not resolve issue
