### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [jaegertracing/jaeger#2955]
It has been noticed that while using fossa-contrib/fossa-action@v1 your fossa-api-key 304657e2357ba57b416b94e6b119131b is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by yurishkuro** [comment]
It was my understanding that api key is not a secret, just a project identifier.

**Comment by jpkrohling** [comment]
That's also my understanding. It should really be named something like `public-key` :-)

**Comment by raima-zachariah** [comment]
Thank you for taking out the time to respond. I was performing a vulnerability analysis and this was part of my result finding.
