### ISSUE TITLE
Have Docker images built with bash preinstalled

### ISSUE THREAD

**Issue by neoaisac** [jaegertracing/jaeger#2957]
## Requirement - what kind of business use case are you trying to solve?

Support bash by default in the docker images.

## Problem - what in Jaeger blocks you from solving the requirement?

The docker images publisher in the Docker hub do not have bash, which means that when they're used in a Dockerfile with the `RUN` command (for example to add a `wait-for` script in a docker compose script) these fail.

```
#5 0.497 container_linux.go:367: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Expose builds of these images that contain `bash`, or use another base distribution of linux.
Else, document how to add Dockerfile `RUN` commands for the existing images, when there is no `bash` preinstalled.

**Comment by jpkrohling** [comment]
>for example to add a wait-for script in a docker compose script

Could you expand on the use case? Are you using that to make Jaeger wait for a dependency to start before running the entrypoint?

**Comment by pavolloffay** [comment]
I am closing this as we didn't get the exact use case.

Btw. Jaeger images do have shell
```
docker run --rm -it --entrypoint /bin/sh jaegertracing/jaeger-collector:latest
```
