### ISSUE TITLE
Build Error esc: Command not found  

### ISSUE THREAD

**Issue by sachinkakatkar** [jaegertracing/jaeger#2963]
**Describe the bug**
When i run the command "make build-ui" or "make build-binaries-ppc64le"
then build fail with error esc: command not found.

**To Reproduce**
1. git submodule update --init --recursive
2.make install-tools
3.make test
4.make build-ui 
5.make build-binaries-ppc64le

**Expected behavior**
Build shall success without error

**Screenshots**
![Error esc command](https://user-images.githubusercontent.com/25656314/116234274-019f5500-a77a-11eb-9190-5220d94cfbe6.png)

**Version (please complete the following information):**
 - OS: ubuntu 20.04
 - Jaeger version: v1.22.0
 - Deployment: bare metal

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**
Platform architecture is ppc64le

**Comment by albertteoh** [comment]
@sachinkakatkar is your `$GOPATH` in `$PATH`?

```
export PATH=$PATH:$(go env GOPATH)/bin
```

**Comment by sachinkakatkar** [comment]
> @sachinkakatkar is your `$GOPATH` in `$PATH`?
> 
> ```
> export PATH=$PATH:$(go env GOPATH)/bin
> ```

@albertteoh Thanks.  Above solution working perfectly.

**Comment by yurishkuro** [comment]
fwiw I still have the PR open to switch to go:embed and discontinue using esc, but we need to find a way to serve assets from an archive, and I didn't have time to finish that.

**Comment by yurishkuro** [comment]
fixed in #2964, it will print more detailed error message
