### ISSUE TITLE
ILM policy is not configurable

### ISSUE THREAD

**Issue by jrRibeiro** [jaegertracing/jaeger#2967]
## Requirement - what kind of business use case are you trying to solve?

Following https://github.com/jaegertracing/jaeger/pull/2796 (great work, btw), we now have the ability to use ILM to manage indices. In _multi-tenancy_ scenarios, when running several Jaeger instances using the same Elastic storage, we can use different indices for each instance by defining its own prefix. However, different indices might need different ILM policies (some indices need different rollover and retention configurations than others).

## Problem - what in Jaeger blocks you from solving the requirement?

Right now, an ILM policy is hard-coded (named `jaeger-ilm-policy`) and it is not possible to change.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Make the policy's name configurable using an env var (to use with USE_ILM). This way, we can set the ILM policy to use and change the mappings of the index to use different policies per index.

I can open a new PR if you agree with my proposal. :slightly_smiling_face:

**Comment by yurishkuro** [comment]
+1
