### ISSUE TITLE
Remove v2 directory

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2969]
We decided yesterday during the community sync call that we want to remove the v2 directory entirely until the OpenTelemetry Collector reaches GA. The ground is too unstable at the moment to rely on it as the base for the Jaeger v2.

**Comment by jkowall** [comment]
Hopefully we keep this work somewhere since we will have to redo it at some point.

**Comment by jpkrohling** [comment]
>Hopefully we keep this work somewhere since we will have to redo it at some point.

Git history ;-)
