### ISSUE TITLE
Org-wide issue/PR templates

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#2974]
## Requirement - what kind of business use case are you trying to solve?

This is a follow-up to https://github.com/jaegertracing/jaeger-idl/pull/74#issuecomment-815410966.

## Problem - what in Jaeger blocks you from solving the requirement?

Each project under the jaeger org is either missing or has a similar issue template which means:
- More maintenance effort required in cases like the gitter to slack move (see #2871).
- Inconsistent experience for contributors when creating new issues (or PRs).

## Proposal - what do you suggest to solve the problem or improve the existing situation?

A [single default issue/PR template](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) similar to OpenTelemetry's (https://github.com/open-telemetry/.github) applied across the Jaeger org, by copying the contents from jaegertracing/jaeger's `.github/ISSUE_TEMPLATE` to jaegertracing's .github project: https://github.com/jaegertracing/.github.

Tested in my own "org" to confirm expected behaviour; default issue_templates can be overridden in the project repo's `.github/ISSUE_TEMPLATE`, otherwise, the default issue_templates will be applied when creating new issues.

## Any open questions to address

- Should existing issue_templates be deleted from all jaeger projects or should we be more selective.
- Should we apply this to PULL_REQUEST_TEMPLATE.md as well?

**Comment by jpkrohling** [comment]
There are other files that we can place there, like the security.md and the generic contributing.md. Perhaps the DCO and code of conduct as well?

**Comment by yurishkuro** [comment]
I would prefer to only move those files which are understood by GitHub. I would keep DCO in the repos because it is part of the development process, and so are contributing docs. And our code of conduct is just a link to CNCF, so it's also better to keep in the repos (but OK to copy to .github as well for repos where we didn't define it).

**Comment by yurishkuro** [comment]
Note that main repo has `.github/ISSUE_TEMPLATE/config.yml`, which is specific to the repo because it contains an exact link to Discussions. Do we want discussions for all repos to happen in one place or in individual repos? I'd probably go with one place.

**Comment by jpkrohling** [comment]
>I would prefer to only move those files which are understood by GitHub

I thought every file in there would show up in all repos from the organization. If that's not the case, I agree with you.

**Comment by yurishkuro** [comment]
no, they don't "show up" in the repos, but are used by GitHub in various sections of the website.

**Comment by albertteoh** [comment]
Yup, good call @yurishkuro .

I propose to copy the following files from `jaegertracing/jaeger` into `jaegertracing/.github` repo. Please check these are correct:
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/config.yml (so we have one place for discussions)
- .github/PULL_REQUEST_TEMPLATE.md

Also, I propose (as a follow-up PR to the above task) we remove the following repos' ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE files which appear to be (more or less) identical to what we plan to add into `jaegertracing/.github`'s, making them redundant:
- https://github.com/jaegertracing/jaeger/.github
- https://github.com/jaegertracing/documentation/tree/master/.github
- https://github.com/jaegertracing/jaeger-ui/tree/master/.github
- https://github.com/jaegertracing/jaeger-idl/tree/master/.github
- https://github.com/jaegertracing/jaeger-client-java/tree/master/.github
- https://github.com/jaegertracing/jaeger-client-go/tree/master/.github
- https://github.com/jaegertracing/jaeger-client-python/tree/master/.github
- https://github.com/jaegertracing/jaeger-client-cpp/tree/master/.github
- https://github.com/jaegertracing/jaeger-client-node/tree/master/.github
- https://github.com/jaegertracing/jaeger-performance/tree/master/.github
- https://github.com/jaegertracing/jaeger-client-csharp/tree/master/.github
- https://github.com/jaegertracing/jaeger-lib/tree/master/.github
- https://github.com/jaegertracing/spark-dependencies/tree/master/.github
- https://github.com/jaegertracing/jaeger-client-javascript/tree/master/.github
- https://github.com/jaegertracing/xdock-zipkin-brave/tree/master/.github
- https://github.com/jaegertracing/legacy-client-java/tree/master/.github

The following differ to from the standard ISSUE_TEMPLATE and/or PULL_REQUEST_TEMPLATE files so I'll leave them for now:
- https://github.com/jaegertracing/helm-charts/tree/main/.github
- https://github.com/jaegertracing/docker-protobuf/tree/master/.github

Please let me know what you think.

**Comment by yurishkuro** [comment]
sgtm

**Comment by albertteoh** [comment]
https://github.com/jaegertracing/.github/pull/1: PTAL.
