### ISSUE TITLE
i installed jaeger but alpha cant conected to jaeger-collector

### ISSUE THREAD

**Issue by cangchen8180** [jaegertracing/jaeger#2981]
**Describe the bug**
i installed jaeger but alpha cant conected to jaeger-collector.
![image](https://user-images.githubusercontent.com/13382285/117537306-920b4e80-b032-11eb-807e-bb32c9fd3a42.png)

but jaeger ui is successful.
![image](https://user-images.githubusercontent.com/13382285/117537295-8750b980-b032-11eb-8b88-0730d970520f.png)

command:

> docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 14250:14250 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.22

**To Reproduce**
jaeger logs 

`2021/05/08 11:14:20 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
{"level":"info","ts":1620472460.8559754,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1620472460.8592544,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1620472460.862263,"caller":"flags/admin.go:105","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1620472460.8630283,"caller":"flags/admin.go:111","msg":"Starting admin HTTP server","http-addr":":14269"}
{"level":"info","ts":1620472460.8638659,"caller":"flags/admin.go:97","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
{"level":"info","ts":1620472460.9159117,"caller":"memory/factory.go:61","msg":"Memory storage initialized","configuration":{"MaxTraces":0}}
{"level":"info","ts":1620472460.9770288,"caller":"server/grpc.go:76","msg":"Starting jaeger-collector gRPC server","grpc.host-port":":14250"}
{"level":"info","ts":1620472460.977779,"caller":"server/http.go:47","msg":"Starting jaeger-collector HTTP server","http host-port":":14268"}
{"level":"info","ts":1620472460.9815383,"caller":"server/zipkin.go:52","msg":"Listening for Zipkin HTTP traffic","zipkin host-port":":9411"}
{"level":"info","ts":1620472461.0245485,"caller":"grpc/builder.go:70","msg":"Agent requested insecure grpc connection to collector(s)"}
{"level":"info","ts":1620472461.0246274,"caller":"grpc@v1.29.1/clientconn.go:243","msg":"parsed scheme: \"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1620472461.0269074,"caller":"grpc@v1.29.1/clientconn.go:249","msg":"scheme \"\" not registered, fallback to default scheme","system":"grpc","grpc_log":true}
{"level":"info","ts":1620472461.026982,"caller":"grpc@v1.29.1/resolver_conn_wrapper.go:143","msg":"ccResolverWrapper: sending update to cc: {[{:14250 <nil> 0 <nil>}] <nil> <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1620472461.0278158,"caller":"grpc@v1.29.1/clientconn.go:667","msg":"ClientConn switching balancer to \"round_robin\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1620472461.0278826,"caller":"grpc@v1.29.1/clientconn.go:682","msg":"Channel switches to new LB policy \"round_robin\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1620472461.029382,"caller":"grpc@v1.29.1/clientconn.go:1056","msg":"Subchannel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1620472461.029567,"caller":"grpc@v1.29.1/clientconn.go:417","msg":"Channel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1620472461.0300686,"caller":"grpc/builder.go:108","msg":"Checking connection to collector"}
{"level":"info","ts":1620472461.030285,"caller":"grpc/builder.go:119","msg":"Agent collector connection state change","dialTarget":":14250","status":"CONNECTING"}
{"level":"info","ts":1620472461.0298057,"caller":"grpc@v1.29.1/clientconn.go:1193","msg":"Subchannel picks a new address \":14250\" to connect","system":"grpc","grpc_log":true}
{"level":"info","ts":1620472461.0325398,"caller":"command-line-arguments/main.go:218","msg":"Starting agent"}
{"level":"info","ts":1620472461.0331204,"caller":"querysvc/query_service.go:137","msg":"Archive storage not created","reason":"archive storage not supported"}
{"level":"info","ts":1620472461.0332408,"caller":"app/agent.go:69","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1620472461.0331457,"caller":"app/flags.go:128","msg":"Archive storage not initialized"}
{"level":"info","ts":1620472461.039068,"caller":"grpc@v1.29.1/clientconn.go:1056","msg":"Subchannel Connectivity change to READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1620472461.0392349,"caller":"base/balancer.go:200","msg":"roundrobinPicker: newPicker called with info: {map[0xc0005533f0:{{:14250 <nil> 0 <nil>}}]}","system":"grpc","grpc_log":true}
{"level":"info","ts":1620472461.0392876,"caller":"grpc@v1.29.1/clientconn.go:417","msg":"Channel Connectivity change to READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1620472461.0393176,"caller":"grpc/builder.go:119","msg":"Agent collector connection state change","dialTarget":":14250","status":"READY"}
{"level":"info","ts":1620472461.040886,"caller":"app/static_handler.go:181","msg":"UI config path not provided, config file will not be watched"}
{"level":"info","ts":1620472461.041129,"caller":"app/server.go:170","msg":"Query server started"}
{"level":"info","ts":1620472461.0419047,"caller":"app/server.go:230","msg":"Starting HTTP server","port":16686,"addr":":16686"}
{"level":"info","ts":1620472461.0423024,"caller":"app/server.go:249","msg":"Starting GRPC server","port":16685,"addr":":16685"}
{"level":"info","ts":1620472461.0417478,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"}
`

**Comment by albertteoh** [comment]
@cangchen8180 it looks like alpha is running in a docker container as part of a docker-compose, but trying to talk to jaeger-collector on localhost (127.0.0.1) but it is running in another container. 

Try adding the `jaegertracing/all-in-one:1.22` image as another container into your docker-compose and change alpha's tracing config to point to the container name of jaeger-collector.
