### ISSUE TITLE
Humio as storage backend

### ISSUE THREAD

**Issue by em135** [jaegertracing/jaeger#3005]
Humio is great at storing and querying large amount of data, but lacks visualization for the data. We therefore want to add visualization capabilities to Humio using Jaeger. @Xitric and I are working on a storage backend for Humio using the grpc plugin. Our project can be seen at https://github.com/em135/humio-jaeger-plugin.

We have implemented the spanstore.Reader and dependencystore.Reader interfaces. We are currently able to visualize traces by querying Humio. However, the visualization of dependency graphs are insufficient in a large-scale production system.

**Comment by em135** [comment]
> What's the action item behind this ticket? Would you like to see your storage incorporated in the core? Or is it open so that interested folks can exchange experiences?

The storage should not be incorporated in the core. We have made a MVP Humio storage plugin to visualize our data. This issue and our work should serve as a discussion board for a Humio storage plugin (similar to the other open storage plugin issues).

**Comment by yurishkuro** [comment]
Closing as done: https://github.com/em135/humio-jaeger-plugin
