### ISSUE TITLE
Collector sampling with opentelemetry

### ISSUE THREAD

**Issue by heruv1m** [jaegertracing/jaeger#3040]
Hello
I have made a scheme below. Is it possible to use   [jaeger collector sampling](https://www.jaegertracing.io/docs/1.22/sampling/#collector-sampling-configuration)  with opentelemetry java instrumentation?
![image](https://user-images.githubusercontent.com/8426800/119978696-a0f67880-bfc2-11eb-9231-265463961304.png)

**Comment by yurishkuro** [comment]
This is a question for OTEL Java SDK. My guess is that the answer is no, I do not recall seeing OTEL SDKs supporting Jaeger sampling strategies format (even though the OTEL collector *can* proxy sampling requests to jaeger).
