### ISSUE TITLE
AWS Lambda suppot through extensions

### ISSUE THREAD

**Issue by alialamine** [jaegertracing/jaeger#3048]
## Requirement - what kind of business use case are you trying to solve?

Integration with AWS Lambda

## Problem - what in Jaeger blocks you from solving the requirement?

A good way to provide the integration is to have an extension ready for use by the community

## Proposal - what do you suggest to solve the problem or improve the existing situation?

AWS Lambda announced the general availability of [extensions](https://aws.amazon.com/blogs/compute/introducing-aws-lambda-extensions-in-preview/) meant to solve integration issues of platforms like jaeger

## Any open questions to address

the following needs experimenting with the aws api for lambda extensions before answering it
- Is there any way to provide the extension for use by everyone without needing to add layers to every account (a shared layer kind of thing). Based on the general availability article there seems to be such an api.

Note: I have plans to tackle this but no eta at the moment

**Comment by yurishkuro** [comment]
This sounds mostly like an instrumentation issue, which is not in scope of the Jaeger project (see OpenTelemetry). What specific changes are you expecting in Jaeger for this?

**Comment by jkowall** [comment]
Agree with @yurishkuro but I want to point out that you can use a central collector on an EC2 instance and not deploy a collector for each account. This would provide a shared collector you could use across all your functions. These questions are best asked on the https://github.com/aws-observability/aws-otel-lambda or the https://github.com/aws-observability/aws-otel-collector repo.

**Comment by alialamine** [comment]
Very fair, didn't look into the jaeger itself, thought it needed to be here.
