### ISSUE TITLE
Release action is broken

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#3058]
When releasing 1.23.0, the "Upload binaries" step failed with:

![image](https://user-images.githubusercontent.com/13387/120858260-d5e66a80-c582-11eb-9957-c0e10e35ca9d.png)

I believe this is due to recent changes to the repository token scope that GitHub made. The action we are using for this seems outdated, so, we might want to consider changing to another action.

**Comment by jpkrohling** [comment]
@Ashmita152, do you know anything about this action?

@albertteoh, I remember you had some issues during the last release, but not sure this was it. Do you recall what happened?

**Comment by albertteoh** [comment]
@jpkrohling the issue I faced was with the Documentation release related to push privileges for jaegertracingbot, and the problem seems to be specific to GH Actions. From an old email thread:

> remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 3 of 3 required status checks are expected. At least 1 approving review is required by reviewers with write access.        
To https://github.com/jaegertracing/documentation
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/jaegertracing/documentation'

> It seems like it's a known issue with Github actions not having the privileges to push to a protected branch (master) without approval from a reviewer. 
https://github.community/t/allowing-github-actions-bot-to-push-to-protected-branch/16536

**Comment by Ashmita152** [comment]
Hi Juraci,

I just tried creating a release in my jaeger fork and "Upload binaries" step went well: https://github.com/Ashmita152/jaeger/runs/2751315900?check_suite_focus=true

As you said, it's most likely related with GitHub token scope. May I ask you to check the permissions granted to GH Actions here: https://github.com/jaegertracing/jaeger/settings/actions or it might be somewhere in GitHub organisation level. My forks's settings looks like this:

![gh action](https://user-images.githubusercontent.com/16268376/120880142-ffdb7380-c5fa-11eb-949a-a7af064f6d17.png)

Sorry that you had to do release manually and push images manually. I found all-in-one image missing 

```
❯ docker pull jaegertracing/all-in-one:1.23
Error response from daemon: manifest for jaegertracing/all-in-one:1.23 not found: manifest unknown: manifest unknown
```

Regards.

**Comment by jpkrohling** [comment]
>May I ask you to check the permissions granted to GH Actions here

Indeed, it was only "Read repository contents permission" instead of "Read and write permissions". I just swapped it and started the job again. Let's see how it goes :-)

>I found all-in-one image missing

That one is a separate step, which failed here locally, as I don't sem to have node 10:

```
$ BRANCH=v1.23.0 scripts/build-all-in-one-image.sh
+ BRANCH=v1.23.0
++ go env GOARCH
+ GOARCH=amd64
+ expected_version=v10
++ node --version
+ version=v14.17.0
+ major_version=v14
+ '[' v14 = v10 ']'
+ echo 'ERROR: installed Node version v14.17.0 doesn'\''t match expected version v10'
ERROR: installed Node version v14.17.0 doesn't match expected version v10
+ exit 1
```

**Comment by Ashmita152** [comment]
Thank you Juraci. It looks like the release workflow passed [this time](https://github.com/jaegertracing/jaeger/runs/2754237798?check_suite_focus=true) 🎉

**Comment by jpkrohling** [comment]
Thanks for your help, @Ashmita152!
