### ISSUE TITLE
Schema support for cassandra 4

### ISSUE THREAD

**Issue by nothinux** [jaegertracing/jaeger#3080]
Hi, i'm trying to initilize schema in cassandra 4, but i got `'Unknown property 'dclocal_read_repair_chance'`.
after i check changelog for cassandra 4, `dclocal_read_repair_chance` has removed [link](https://github.com/apache/cassandra/blob/6c30261bc8d696f599a1e9ebea8a5bffbd0ac9ed/NEWS.txt#L255).

So temporarily I removed `AND dclocal_read_repair_chance=0.0` in plugin/storage/cassandra/schema/v003.cql.tmpl, and it works well.

i know cassandra 4 still RC, i'm interested to contribute, would sending a pull request v004.cql.tmpl similar to v003.cql.tmpl but without the `AND dclocal_read_repair_chance=0.0` solve the problem? or is there something else to do?

Thank you

**Comment by albertteoh** [comment]
You may need to provide a migration script from v003 -> v004 as well like https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/schema/migration/V002toV003.sh.
