### ISSUE TITLE
Metrics Query Development Environment

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#3107]
## Requirement - what kind of business use case are you trying to solve?

As part of #2954, I'd like to ensure there is a decent development environment that users and contributors alike can easily spin up/down, something like jaeger all-in-one.

## Problem - what in Jaeger blocks you from solving the requirement?

The metrics querying capabilities of jaeger-query are made possible through the availability of OTEL-generated span metrics data, so a number of components need to be spun up in order to have "instant" graphs seen in the new Monitor tab, namely:

- Something to generate traces, ideally for multiple services and operations at varying rates and properties to make the graphs more interesting to look at.
- OTEL collector to receive these spans then compute and expose these metrics.
- A Prometheus server to scrape these metrics and expose endpoints for querying the metrics data.
- Jaeger all-in-one providing the ability to query and view the metrics and drill-down into the related traces.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

It wouldn't be feasible (AFAIK) to have these components combined into a single container like jaeger all-in-one.
I propose to introduce a docker-compose file defining the aforementioned components, much like the existing [jaeger-docker-compose.yml](https://github.com/jaegertracing/jaeger/blob/master/docker-compose/jaeger-docker-compose.yml), and perhaps in the same directory with a Makefile target to easily bring up the dev environment.

The docker-compose file would look something like this, with some modifications like using official rather than personal images: https://github.com/albertteoh/atm-dev/blob/main/docker-compose.yml

## Any open questions to address

Note that for generating traces, I provide two options in the above sample [docker-compose.yml file](https://github.com/albertteoh/atm-dev/blob/main/docker-compose.yml):
- [synthetic-load-generator](https://github.com/Omnition/synthetic-load-generator) by Splunk, which is now an archived repo. The reason why I have a personal image is due to a config-related bug in the upstream repo which I fixed in my local fork.
- HotROD

The benefit of synthetic-load-generator is that it generates fairly complex and configurable traces at varying rates of calls, errors and durations, without human intervention; unlike HotROD. This is desirable, particularly when viewing metrics as there is a continuous stream of metrics updates over time.

The problem is the repo is archived (and so no longer maintained) and contains a bug (which I've fixed locally) and so would involve pushing an alternative image managed by us.

HotROD, on the other hand, is familiar to users, is maintained by the community, and publishes official tagged images, but requires user intervention to generate traces and metrics.

**Comment by yurishkuro** [comment]
Are you sure splunk's load generator didn't just move to OTEL?

I have a personal repo microsim that can generate consistent load with some randomized behavior for a configured graph of microservices (there is one config that simulates hotrod pattern).

**Comment by jpkrohling** [comment]
@tigrannajaryan, was it moved? I also had the impression that the load generator was archived without replacement.

**Comment by albertteoh** [comment]
Thanks for your inputs @yurishkuro @jpkrohling

> Are you sure splunk's load generator didn't just move to OTEL?

I couldn't find evidence of it being moved. Even OTEL refers to the archived synthetic load generator: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/performance.md#testing.

Hopefully, Tigran is able to shed more light on its status.

> I have a personal repo microsim that can generate consistent load with some randomized behavior for a configured graph of microservices (there is one config that simulates hotrod pattern).

Thanks for suggesting https://github.com/yurishkuro/microsim. I'll take a look at it.

**Comment by tigrannajaryan** [comment]
Splunk archived https://github.com/Omnition/synthetic-load-generator since we no longer use it ourselves and do not plan to evolve it. It is Apache licensed so anyone is free to fork and maintain a fork.

**Comment by yurishkuro** [comment]
@tigrannajaryan is there something else you use?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan is there something else you use?

I am not aware of any alternates.
