### ISSUE TITLE
Support optional Close() method in grpc plugin writer

### ISSUE THREAD

**Issue by slon** [jaegertracing/jaeger#3120]
## Requirement - what kind of business use case are you trying to solve?

I would like to support graceful shutdown for grpc plugin.

## Problem - what in Jaeger blocks you from solving the requirement?

Writer in storage plugin might buffer spans in internal queue. AFAIK, kafka writer [works that way](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/kafka/writer.go#L85). Even more, because Writer interface does not support batching, internal buffering is the only viable option for achieving high write throughput.

During graceful restart, collector should flush that internal queue before shutting down. Bundled storage plugins can implement optional Close() method, that is invoked [during collector shutdown](https://github.com/jaegertracing/jaeger/blob/c5642b708be9e2577cc1c494889ae97946ccc78a/cmd/collector/main.go#L108-L113).

But grpc_plugin storage does not support that method.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Extend plugin protocol with Close method. Plugin would advertise Close support in plugin capabilities.
That way, new collector should stay compatible with old plugins. And new plugins should stay compatible with old collector.

**Comment by yurishkuro** [comment]
+1
