### ISSUE TITLE
Jaeger - windows configuration doesn't work - all in one solution. 

### ISSUE THREAD

**Issue by DikshithAC** [jaegertracing/jaeger#3123]
Jaeger - windows configuration doesn't work - all in one solution.

**Comment by Ashmita152** [comment]
Hi @DikshithAC 

Sorry for the trouble you faced in running Jaeger's all-in-one in windows. We need to improve the documentation for windows environment. Thank you for reporting it. 

We have users who run Jaeger on windows successfully. It will be helpful if you can describe the steps(commands) you used along with the error messages. We can help you that way better, without that information we can't help much.

I guess you are looking for python related tutorial. I would like to recommend you to this tutorial: https://github.com/yurishkuro/opentracing-tutorial/tree/master/python

It's a kind request from my side to be careful about the words you use while opening any issue in any open-source project. I learnt everything about tracing from that book and is among my favourite books. 

Thank you!

**Comment by jpkrohling** [comment]
+1 to everything @Ashmita152 said, especially this part:

> It's a kind request from my side to be careful about the words we use while opening any issue in any open-source project.

**Comment by DikshithAC** [comment]
Hi @Ashmita152,
Please be informed, no offence as such with the "words" above which points about "carefulness". I have paid "my hardened money for the book and in a position of non return status from vendor".  The same have conveyed here. 

Appreciate your advice when asked. Till then ........ .Hope you got my message clear.

**Comment by jpkrohling** [comment]
In a final attempt to turn this into something positive, I'll refer once again to something @Ashmita152 said before:

> It will be helpful if you can describe the steps(commands) you used along with the error messages. We can help you that way better, without that information we can't help much.

**Comment by DikshithAC** [comment]
@jpkrohling , please remove label "invalid". Will provide details
