### ISSUE TITLE
add stop command to jaeger-agent

### ISSUE THREAD

**Issue by esrrhs** [jaegertracing/jaeger#3128]
jaeger-agent support these command
Available Commands:
  docs        Generates documentation
  help        Help about any command
  status      Print the status.
  version     Print the version.

is there a STOP command to let the jaeger-agent quit other than kill it

thanks

**Comment by jpkrohling** [comment]
There isn't, and sending SIGINT (ctrl+c) should cause the process to cleanly exit.
