### ISSUE TITLE
Sampling configuration strategies doesn't seem to work

### ISSUE THREAD

**Issue by davidbartos** [jaegertracing/jaeger#3165]
**Describe the bug**
Just like in the https://github.com/jaegertracing/jaeger/issues/2197 issue, configuring the sampling strategy based on this https://www.jaegertracing.io/docs/1.24/sampling/ doesn't seem to work. I did everything as it was mentioned, it seems that the collector even reads the sampling.json file, but it is neglected. I tried to filter out a whole service by choosing probabilistic sampling with a param: 0.0, but I kept getting the traces.

**Expected behavior**
I expected to be able to configure the sampling strategies, filtering different services/operations.

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: v1.21
 - Deployment: Kubernetes

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.
There isn't any specific troubleshooting step for this

**Additional context**
The used sampling strategy:
```
{
         "service_strategies": [
           {
            "service": "anyservice",
            "type": "probabilistic",
            "param": 0.0
           }
         ],
         "default_strategy": {
           "type": "probabilistic",
           "param": 1,
           "operation_strategies": [
             {
              "operation": "/livez",
              "type": "probabilistic",
              "param": 0.0
             },
             {
              "operation": "/readyz",
              "type": "probabilistic",
              "param": 0.0
             }
           ]
         }
}


```

**Comment by jdileonardo** [comment]
Are your clients configured to respect remote sampling?

**Comment by jkowall** [comment]
Jaeger clients are deprecated and currently there is support for remote sampling in Otel which can be used if necessary; otherwise you should be using sampling in the Otel collector.
