### ISSUE TITLE
Support Alibaba Cloud Log Service as storage backend 

### ISSUE THREAD

**Issue by qiansheng91** [jaegertracing/jaeger#3172]
I'm interested in supporting [Alibaba Cloud Log Service](https://www.alibabacloud.com/help/doc-detail/48869.htm) (SLS) as a storage backend. 

And As I know, Trace is the specific collection of logs with calling relationships by using trace ID and span ID, and The SLS is a log storage service. It provides high-performance write and queries, and SLS as a storage backend of jaeger will be great. 

Could someone give some point about Let X as a storage backend? Thanks!

**Comment by qiansheng91** [comment]
I created the repo to implement [this plugin](https://github.com/qiansheng91/jaeger-sls)

**Comment by qiansheng91** [comment]
Hi All

The Plugin has been released.  Here is [the gif of the demo](https://github.com/qiansheng91/jaeger-sls#quick-start).

**Comment by qiansheng91** [comment]
Ref: #638

**Comment by pavolloffay** [comment]
I consider this as done- please add docs in https://github.com/jaegertracing/documentation https://github.com/jaegertracing/documentation/blob/master/content/docs/next-release/deployment.md#storage-plugin
