### ISSUE TITLE
Migrate away from curator

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#3179]
Library `elasticsearch-python` that is used by curator added a check to verify that ES is elastic.co product https://github.com/elastic/elasticsearch-py/releases/tag/v7.14.0.

So now our index cleaner and rollover scritps fail to run with old ES (5.x and even old -oss versions). Here is failed build https://github.com/jaegertracing/jaeger/pull/3178/checks?check_run_id=3240658056#step:6:835

I propose to migrate the python scripts to golang and as a quick fix we can pin the `elasticserch-python` to an older version without the check.

**Comment by jpkrohling** [comment]
Yes, please!

**Comment by pavolloffay** [comment]
done
