### ISSUE TITLE
Duplicate tag keys due to agent level tags 

### ISSUE THREAD

**Issue by pbdger** [jaegertracing/jaeger#3202]
**Describe the bug**
By using the --agent.tags parameter, duplicate key entries can be created by the agent.

**To Reproduce**
1.  Set agent parameter --agent.tags=agent=setViaAgentCli
2.  Start the Agent
3.  Create a tracer in Your code with tag agent=setInTracerCreation

**Expected behavior**
tags are defined as key:value pairs (https://opentracing.io/docs/overview/tags-logs-baggage/#tags).
Therefore, the expectation is that when the trace is displayed at the process, there is only one tag key agent.

**Screenshots**
![image](https://user-images.githubusercontent.com/81152194/129172187-978830f4-30b4-45e8-bd6e-e0178d4f99f0.png)

**Version (please complete the following information):**
 - OS: MacOs
 - Jaeger version: 1.25
 - Deployment: Docker

**Additional context**
The fix would also need to define if the tag from the --agent.tags parameter always overwrites a tag from the tracer or if the tags from the tracer is lead.

**Comment by pavolloffay** [comment]
same as https://github.com/jaegertracing/jaeger/issues/3203
