### ISSUE TITLE
gRPC Collector Does Not Support Configurable Max Message Size

### ISSUE THREAD

**Issue by js8080** [jaegertracing/jaeger#3210]
**Describe the bug**
The Jaeger gRPC Collector Service has a default max receive message size of 4mb and does not support overriding this max size even though gRPC allows for it.

Source from `cmd/collector/app/server/server.go`:
```go
var defaultServerOptions = serverOptions{
	maxReceiveMessageSize: defaultServerMaxReceiveMessageSize,
	maxSendMessageSize:    defaultServerMaxSendMessageSize,
	connectionTimeout:     120 * time.Second,
	writeBufferSize:       defaultWriteBufSize,
	readBufferSize:        defaultReadBufSize,
}
```

Where `defaultServerMaxReceiveMessageSize` is defined as:
```go
const (
	defaultServerMaxReceiveMessageSize = 1024 * 1024 * 4
```

There is a method available to set the max receive message size also but it is not called and has no configuration options associated with it:
```go
// MaxRecvMsgSize returns a ServerOption to set the max message size in bytes the server can receive.
// If this is not set, gRPC uses the default 4MB.
func MaxRecvMsgSize(m int) ServerOption {
	return newFuncServerOption(func(o *serverOptions) {
		o.maxReceiveMessageSize = m
	})
}
```

**To Reproduce**
See my initial question on this in the Discussion section: [gRPC Collector Configurable Max Message Size #3200](https://github.com/jaegertracing/jaeger/discussions/3200)

**Expected behavior**
Some users of Jaeger (such as myself) may want the ability to log larger Spans and since gRPC is flexible and allows a larger message size limit, we should expose a setting to allow overriding the default max message size.

For example, a new CLI option for the Collector:
```
collector.grpc-max-receive-message-length
```

To change this behavior, we basically just need to add a new Collector CLI option as mentioned and then add the following code to `cmd/collector/app/server/grpc.go -> StartGRPCServer`:
```go
// StartGRPCServer based on the given parameters
func StartGRPCServer(params *GRPCServerParams) (*grpc.Server, error) {
	var server *grpc.Server
	var grpcOpts []grpc.ServerOption

        // New - set max receive message size via new params property populated via CLI option
	grpcOpts = append(grpcOpts, grpc.MaxRecvMsgSize(params.MaxReceiveMessageLength))

	if params.TLSConfig.Enabled {
		// user requested a server with TLS, setup creds
		tlsCfg, err := params.TLSConfig.Config(params.Logger)
		if err != nil {
			return nil, err
		}
```

We'd also have to update the `GRPCServerParams` type and some other code as well but that's the most important part of it.

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: Jaeger v1.21.0
 - Deployment: Jaeger deployed via Kubernetes but traced application is running on bare metal (Linux via WSL)

**What troubleshooting steps did you try?**
See my initial question on this in the Discussion section: [gRPC Collector Configurable Max Message Size #3200](https://github.com/jaegertracing/jaeger/discussions/3200)

**Comment by js8080** [comment]
@yurishkuro I tested a change to this with a local Jaeger build. Would you be interested in me contributing this change?

**Comment by yurishkuro** [comment]
please do
