### ISSUE TITLE
Add configuration file option to grpc plugin configuration tests.

### ISSUE THREAD

**Issue by EinKrebs** [jaegertracing/jaeger#3221]
## Requirement - what kind of business use case are you trying to solve?

I want to run integration tests on grpc plugin.

## Problem - what in Jaeger blocks you from solving the requirement?

The plugin needs config file to be passed.

**Comment by pavolloffay** [comment]
@EinKrebs would you like to submit a PR and show how this can be used with the clickhouse plugin?

**Comment by pavolloffay** [comment]
There is already an exmaple of how to use the storage integration test with gprc-plugin https://github.com/jaegertracing/jaeger/blob/f23484b9f2431b73cc0e12c8da911560ab9ec11d/plugin/storage/integration/grpc_test.go#L33
