### ISSUE TITLE
jaeger 1.14  search return  duplicate trace

### ISSUE THREAD

**Issue by zziawan** [jaegertracing/jaeger#3243]
**Describe the bug**
trace search return duplicate  traces. use the default istio tracing pod and agent.

![image](https://user-images.githubusercontent.com/5172896/131807003-041d7775-52ae-4cf0-9ddf-b0c86fd85d69.png)

**Comment by albertteoh** [comment]
Curious, if you expand each of the duplicate traces, are the spans duplicated as well?

**Comment by pavolloffay** [comment]
What is the storage backend used? Do you see this behaviour with newer Jaeger versions?

**Comment by zziawan** [comment]
we use newer jeager instead！thanks！ @pavolloffay @albertteoh
