### ISSUE TITLE
search with max mix duration only return a very few traces

### ISSUE THREAD

**Issue by zziawan** [jaegertracing/jaeger#3244]
jeager 1.14 all-in-one. when search traces without max min duration, a lot of traces found, but with min max duration(eg 1m-1000ms), only find very few（about 6） traces, although a lot of traces  duration in this duration but still be  filtered. do someone konwn why? thanks！

**Comment by albertteoh** [comment]
@zziawan the max/min duration filter is applied on a **span** level, not a trace level. This issue came up in the past as well with us, and I think we could improve the usability, perhaps improving the label text.

**Comment by zziawan** [comment]
@albertteoh  thanks for you reply！ but i found many  filtered traces only has one span  and the duration also in the search min max duration.  and the search result is the same every time! the search limit also no effiect no matter how bigger it is,  fixed num traces returned everytime.  thanks！

**Comment by albertteoh** [comment]
hmmm... did you try increasing the lookback time period? Perhaps those traces are quite old and I think the default lookback is an hour.

**Comment by zziawan** [comment]
@albertteoh  mybe it's a bug of v1.14. the same db and query, v1.17 no such problem. but i can not run v1.14 on my machine, so i can not found why。

**Comment by pavolloffay** [comment]
@zziawan what storage backed are you using? ES/Cassandra or badger? 

We are not planning to backport fixes to 1.14.0. Please close this issue if you cannot reproduce with newer version.

**Comment by zziawan** [comment]
@pavolloffay  we use badger。ok we try other verion.
