### ISSUE TITLE
jaeger 1.25 Unexpected end of JSON input

### ISSUE THREAD

**Issue by wangpu666** [jaegertracing/jaeger#3245]
**Describe the bug**
jaeger 1.25 Unexpected end of JSON input

**To Reproduce**
 go run main.go --query.static-files=/Users/xxx/GolandProjects/jaeger/jaeger-ui/packages/jaeger-ui/build/
1. http://127.0.0.1:16686/trace/af899a3500540bb781a68b98b36ec2e2

**Screenshots**
![image](https://user-images.githubusercontent.com/50776767/131879536-709c1859-c74c-4713-b9fd-3b38ff93f665.png)
![image](https://user-images.githubusercontent.com/50776767/131879626-66e3acc1-0b32-4b2d-934a-39d1548dcd38.png)

**Version (please complete the following information):**
 - OS: mac
 - Jaeger version: 1.25
 - clickhouse version : 21.8.3.44

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

**Comment by wangpu666** [comment]
https://github.com/bobrik/jaeger/tree/ivan/clickhouse/plugin/storage/clickhouse

**Comment by pavolloffay** [comment]
Could you please the trace data that are submitted to Jaeger?

**Comment by wangpu666** [comment]
> 请问提交给Jaeger的trace数据好吗？

I found the problem because the head of the returned span list accidentally carried nil, like this [nil,span,span,spam]
