### ISSUE TITLE
Should `opensearch` be a recognized backend type?

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#3247]
In #3198 we added ability to auto-detect OpenSearch storage. Would it make sense to add `opensearch` as a valid backend choice for `SPAN_STORAGE_TYPE`?

cc @pavolloffay @jkowall @albertteoh @Ashmita152

**Comment by pavolloffay** [comment]
I don't see much value by adding `opensearch` as a valid storage option right now. It will make more sense once opensearch implementation diverges. 

That said I don't have a strong opinion to add it right now and use the same implementation for both elasticsearch and opensearch.

**Comment by yurishkuro** [comment]
Yes, I meant using the same implementation for now. Having explicit `opensearch` option would server to goals:
  * be a forward-compatible configuration option, since I fairly certain we'll need to do it at some point in the future
  * a bit of a positional statement saying that we prefer to support liberally-licensed storage, not the new ES license

**Comment by yurishkuro** [comment]
@pavolloffay  #3255
