### ISSUE TITLE
What is the impact on business performance under the full sampling scenario? Has anyone tested this?

### ISSUE THREAD

**Issue by wangpu666** [jaegertracing/jaeger#3248]
What is the impact on business performance under the full sampling scenario? Has anyone tested this?

**Comment by jkowall** [comment]
I think you mean no sampling, versus full sampling (which would mean there is no data collected). Sampling doesn't change the overhead on the application unless you are using remote sampling, which isn't supported yet in OpenTelemetry. There are a lot of variables in terms of overhead for tracing but the biggest is going to be how your instrument and the architecture of the application. Most often the sampling happens at the collector and the reason for sampling is to reduce the cost to transfer and store the data.

Can you provide more details about the language, instrumentation, and goals you have?

**Comment by pavolloffay** [comment]
Closing it is a stale question.
