### ISSUE TITLE
Not able to retrieve traces via grpc on larger time windows when using badger storage and jaeger all-in-one

### ISSUE THREAD

**Issue by lennartmohr** [jaegertracing/jaeger#3263]
**Describe the bug**
We're using the latest jaeger all-in-one version with badger storage for tracing our services. Another app is retrieving the traces via grpc based on a time window e.g. the last hour to show the logs in an UI. This works totally fine if a traces consists of a smaller amount of spans for example 3. But when the amount of spans in a trace is increasing we're getting problems.  The larger traces only show up in our UI for around 15 to 20 min although they're stored in badger for 10 hours. We checked that. We determine the end of the fetch time window by using System.currentTimeMillis(). When we replace System.currentTimeMillis() with a time close to the trace start time we're still able to retrieve traces even if they are 5 hours old.
We have recently added badger as storage backend. Before we only used jaeger all-in-one where we were able to retrieve
all traces. So, maybe we missed something when setting badger storage up? 

**Expected behavior**
To be able to fetch all traces via grpc from badger storage stored for the configured time.

**Source**
Function for building trace query

private fun buildTraceQuery(tracingStartService: String?, startTime: Long): Query.TraceQueryParameters {
        val endTime = System.currentTimeMillis() / 1000
        return Query.TraceQueryParameters.newBuilder()
            .setStartTimeMin(Timestamp.getDefaultInstance().toBuilder().setSeconds(startTime))
            .setStartTimeMax(Timestamp.getDefaultInstance().toBuilder().setSeconds(endTime))
            .setServiceName(tracingStartService)
            .build()
    }

Function for building trace request

private fun buildFindTraceRequest(traceQuery: Query.TraceQueryParameters): Query.FindTracesRequest {
        return Query.FindTracesRequest.newBuilder().setQuery(traceQuery).build()
    }

**Version (please complete the following information):**
- Latest Jaeger all-in-one version
- 0.4.0 jaeger-proto dependency version

**Comment by MarWestermann** [comment]
We see the same behaviour when using elasticsearch backend. A specific trace is being fetched successfully via grpc for some time and then suddenly disappears from response even the startTimeMin stays the same and only the startTimeMax gets a new value (current time) for each request.

Later setting the startTimeMax back to a value which is nearer to the span time brings the span back in response

**Comment by jkowall** [comment]
Neither of these comments has provided enough information to replicate the problem, please provide a detailed explanation of the problem. Using Badger for production or reading from multiple machines is not recommended.
