### ISSUE TITLE
About jaeger-ingester zipkin to es accumulation

### ISSUE THREAD

**Issue by wangpu666** [jaegertracing/jaeger#3267]
**Describe the bug**
Regarding the accumulation of jaeger-ingester zipkin to es, our data in zipkin is directly transferred to kafka, and part of it is from jaeger-agent to jaeger-collector to jaeger-ingester; however, the accumulation of kafka in ziplin

**To Reproduce**
1. ziplin->kafka->jaeger-ingester accumulation
2. agent->collector->ingester no accumulation

**Expected behavior**
How can we not accumulate? In the process, it was discovered that the consumer group would not actively consume data even when Kafka accumulates.

**Screenshots**
![image](https://user-images.githubusercontent.com/50776767/133462766-9bd75134-1aa2-4f8c-8330-732db869c4bb.png)
![image](https://user-images.githubusercontent.com/50776767/133462843-136cf8b7-7eba-43b0-9cae-5a6ff085494d.png)
![image](https://user-images.githubusercontent.com/50776767/133463048-dd792d6f-4ff8-4a9d-9722-9e3e240b5267.png)

**Version (please complete the following information):**
 - OS: centos7
 - Jaeger version: 1.26
 - docker image: wangpukinds/jager-ingester:1.0

**Comment by jkowall** [comment]
This is no longer supported without using Otel somewhere in the mix, please re-open based on how you are instrumenting the code.
