### ISSUE TITLE
Wrong link on the deprecated repo jaeger-opentelemetry-collector

### ISSUE THREAD

**Issue by ecourreges-orange** [jaegertracing/jaeger#3275]
**Describe the bug**
@yurishkuro 
The repo https://github.com/jaegertracing/jaeger-opentelemetry-collector is in read-only si I can't file a bug over there.
It redirects us to https://github.com/jaegertracing/jaeger/tree/master/cmd/opentelemetry-collector which doesn't exist.
Please fix in README and description to point to https://github.com/jaegertracing/jaeger/tree/master/cmd/collector

Thanks, kind regards.
Emmanuel.

**Comment by yurishkuro** [comment]
Update. Thanks.
