### ISSUE TITLE
Support for Netflix Dynomite as storage backend

### ISSUE THREAD

**Issue by leowmjw** [jaegertracing/jaeger#331]
I am interested in using [Dynomite](https://github.com/Netflix/dynomite) instead of Cassandra as the backend.  Where to look in the code base to make the necessary changes and what interfaces need to be implemented?

Any pointers would be great; thanks!

**Comment by yurishkuro** [comment]
Storage implementations are defined here: https://github.com/uber/jaeger/tree/master/plugin/storage

Is there a Go driver for dynomite?

**Comment by black-adder** [comment]
According to this blog: https://medium.com/netflix-techblog/introducing-dynomite-making-non-distributed-databases-distributed-c7bce3d89404 Dynomite can be used with a golang redis client.

I'm not overly familiar with how redis indexes work so before we start this project, I'd like to see the redis schema that allows searching spans by tags, logs, duration, timestamp, service, and operation.

**Comment by leowmjw** [comment]
@yurishkuro Thanks for the pointer! Unfortunately looks like the only official driver is in Java 😿 --> https://github.com/Netflix/dyno ; looks like the first step is to port dyno to golang

**Comment by yurishkuro** [comment]
Don't see this moving forward.
