### ISSUE TITLE
Backpressure between collector and agent

### ISSUE THREAD

**Issue by slon** [jaegertracing/jaeger#3321]
## Requirement - what kind of business use case are you trying to solve?

We experience frequent span "drops" in our internal deployment. That drops are caused by automatic resharding inside our database. During resharding, some partitions become unavailable for write for a couple of minutes. While partitions are unavailable, collectors keep accepting spans from the clients and eventually drop them.

In our deployment, we got 10000 nodes and 100 collectors. Nodes got more than enough memory to buffer spans for a couple of hours. Collectors drop spans even after a slight hiccup.

Another use-case for backpressure is traffic bursts. We use jaeger to trace big distributed queries, spanning 1000-s оf nodes and 100000-s of RPC requests. Such queries generate very uneven bursts on the collector and cause span drops.

## Problem - what in Jaeger blocks you from solving the requirement?

Right now, collector always accepts incoming spans. Even if collector queue is full.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Would be nice to have some backpressure in collector protocol. I don't have a specific proposal right now.

One possibility is switching to GRPC streaming, but that seems like a huge change.

Another option is to add `queue_is_almost_full` flag to collector reply + custom backoff logic to the client. That would require less changes, but would be harder to configure.

What do you think?

**Comment by pavolloffay** [comment]
My understanding was that Jaeger will start dropping spans if the collector queue is full. I am not sure if we want to implement backpressure and let agent or clients know. There is no caching in the agent/SDK and they do not control the traffic either.

as @albertteoh mentioned the supported architecture to deal with traffic spikes is to put kafka in front of the storage.
