### ISSUE TITLE
trace data delay by about  10m 

### ISSUE THREAD

**Issue by zziawan** [jaegertracing/jaeger#3322]
jaeger-all-in-one 
 version 1.24
 storage  badger.
 after a service processed some  requests , the service and opertion can be see on the ui, but trace data can not show in the first 10 min .  the data did write to disk, and the file size changed.   why this happen, can some give me a clue ? dose it need some more time to process ? thanks!

**Comment by devendrapal-ag** [comment]
Hi Team,

I am also facing the issue with S3 storage. trace data delay around 10m. 
Any luck here ?

**Comment by zziawan** [comment]
this problem  cased by time, the span reporter time not the same as the query timestamp...   @devendrapal-ag  check to see if you reporter time  fall  behind .
