### ISSUE TITLE
Include testing of Linux/ARM64 Docker Images 

### ISSUE THREAD

**Issue by odidev** [jaegertracing/jaeger#3332]
Hi Team, 

I am working with Jaeger on the Linux/ARM64 platform. 

We know that Jaeger already supports Linux/ARM64 platform, and releasing the ARM64 binaries and docker images as well. 

But I can see that the images `all-in-one` and `hotrod` are also tested for Linux/AMD64, as can be seen below: 

- **all-in-one:** https://github.com/jaegertracing/jaeger/blob/master/scripts/build-all-in-one-image.sh#L47 and https://github.com/jaegertracing/jaeger/blob/master/Makefile#L89 

- **hotrod:** https://github.com/jaegertracing/jaeger/blob/master/scripts/hotrod-integration-test.sh#L16. 

May I know, do you have any plans to include the testing of Linux/ARM64 docker images, via GitHub Actions, in the future? 

Please share your opinion on the same. If required, I will be happy to contribute.

**Comment by odidev** [comment]
> We do not have sufficient CI infra quotas to keep running all tests on all possible architectures. We build binaries for many architectures already, but we only test on Linux/amd64. 

 

@yurishkuro , Thank you for this information. I understand the concern. 

Do you feel that testing on AMD64 is sufficient to cover other architectures like ARM64?

**Comment by frzifus** [comment]
> Do you feel that testing on AMD64 is sufficient to cover other architectures like ARM64?

I think that always depends very much on what you intend to do and what requirements have to be fulfilled. But in general, there is a high chance that it will work. To be a bit safer, you can also run the tests independently in your own ARM environment.

**Comment by odidev** [comment]
@frzifus, Thank you for the response. 

Considering there are limitations to the CI/CD quota, there is a project **“WorksOnArm”**, that provides access to the ARM64 HW. Please have a look : < https://github.com/WorksOnArm >.

**Comment by odidev** [comment]
Hi Team, did you get the chance to look into "[WorksOnArm](https://github.com/WorksOnArm)"? Kindly share your opinion.

**Comment by yurishkuro** [comment]
As stated, we have no plans to extend the testing. It provides very marginal benefits compared to both hw costs and maintenance burden.  If this testing is important to you, you're welcome to build an independent testing pipeline as a separate project that you will maintain.
