### ISSUE TITLE
Multiple storage backend not accepting jaeger.

### ISSUE THREAD

**Issue by crombus** [jaegertracing/jaeger#3334]
here is the log output:
`2021/10/21 04:42:00 maxprocs: Updating GOMAXPROCS=2: determined from CPU quota
WARNING: multiple span storage types have been specified. Only the first type (elasticsearch ) will be used for reading and archiving.

2021/10/21 04:42:00 Cannot initialize storage factory: unknown storage type elasticsearch . Valid types are [cassandra elasticsearch memory kafka badger grpc-plugin]`

I have entered values like this:
span-storage.type: elasticsearch, elasticsearch

**Comment by yurishkuro** [comment]
> span-storage.type: elasticsearch, elasticsearch

what do you expect to happen with this configuration? ES can be specified only once.

**Comment by crombus** [comment]
> > span-storage.type: elasticsearch, elasticsearch
> 
> what do you expect to happen with this configuration? ES can be specified only once.

That means in multiple backend storage only two storage can be specified (ES and cassandra). 
What if I two different cluster with ES installed. I want to write data on both.

Is such scenario possible?
