### ISSUE TITLE
Authenticator Name Option Cassandra

### ISSUE THREAD

**Issue by hdost** [jaegertracing/jaeger#3359]
## Requirement - what kind of business use case are you trying to solve?

Using scylladb and supporting alternative authentication methods. 

## Problem - what in Jaeger blocks you from solving the requirement?

In jaeger with certain authentication methods it doesn't work with Scylla DB. I know there's no official support yet but it can get most of the way there with a simple patch. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Currently there is a fork by a colleague of mine https://github.com/mycroft/jaeger which has implemented the small change. We have it working in a preproduction environment. 

## Any open questions to address

If the PR was put up would it get accepted with potentially some adjustments.

Related #197

**Comment by yurishkuro** [comment]
I think it would be fine, but is a bit difficult to judge as there isn't much detail you provided on the changes. Can you link to a pr or commit from that branch that illustrates the change?

**Comment by hdost** [comment]
> I think it would be fine, but is a bit difficult to judge as there isn't much detail you provided on the changes. Can you link to a pr or commit from that branch that illustrates the change?

@yurishkuro https://github.com/mycroft/jaeger/commit/10a69be93384aca25f23d9465d888e3111ef6539 is the relevant change. I can work on a PR.

**Comment by yurishkuro** [comment]
Sorry I don't understand that change. Please create a PR if still needed.
