### ISSUE TITLE
jaeger-es-rollover doesn't have --replicas and --shards flags for rollover command

### ISSUE THREAD

**Issue by armanzor** [jaegertracing/jaeger#3370]
**Describe the bug**
I can init rollover with needed number of replicas and shards, for example 1 replica and 1 shard, but when I do rollover, there's no flags --replicas and --shards and indices have been creating with 1 replica and 5 shards by default

**To Reproduce**
1. `docker run --rm jaegertracing/jaeger-es-rollover:latest init http://<opensearch_instance>:9200 --replicas 1 --shards 1`
2. `docker run --detach --name jaeger --env SPAN_STORAGE_TYPE=opensearch --env ES_SERVER_URLS=http://<opensearch_instance>:9200 -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778  -p 16686:16686  -p  14268:14268 -p 14250:14250 jaegertracing/all-in-one:1.27 --es.use-aliases=true`
3. `docker run --rm -e CONDITIONS='{"max_age": "1s"}' jaegertracing/jaeger-es-rollover:latest rollover http://<opensearch_instance>:9200`

You may repeat third step
If you try to use these flags with rollover, the you will get the error:
```
$ docker run --rm -e CONDITIONS='{"max_age": "1s"}' jaegertracing/jaeger-es-rollover:latest rollover http://<opensearch_instance>:9200 --replicas 1 --shards 1
Error: unknown flag: --replicas
<Usage help truncated>
```

**Expected behavior**
I'm able to use flags --replicas and --shards with rollover and get indices with specified number of replicas and shards

**Screenshots**
Aliaces:
```
alias                index                 filter routing.index routing.search is_write_index
jaeger-span-read     jaeger-span-000002    -      -             -              -
jaeger-span-read     jaeger-span-000003    -      -             -              -
jaeger-span-write    jaeger-span-000003    -      -             -              -
jaeger-service-read  jaeger-service-000001 -      -             -              -
jaeger-service-read  jaeger-service-000003 -      -             -              -
jaeger-service-write jaeger-service-000003 -      -             -              -
jaeger-span-read     jaeger-span-000001    -      -             -              -
jaeger-service-read  jaeger-service-000002 -      -             -              -
```

Indices:
```
health status index                 uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   jaeger-span-000001    JVwIGEzKS3WYvqLJ9wYEXQ   1   1        298            0       62kb           62kb
yellow open   jaeger-span-000003    NY3NaEltR2Gyh1jrXrI1-A   5   1          0            0        1kb            1kb
yellow open   jaeger-span-000002    K1JhEHu8Rsib8CWKaqhL_g   5   1       3722            0    303.9kb        303.9kb
yellow open   jaeger-service-000003 1sFgsLaMS2GDhbeGNQwM_w   5   1          0            0        1kb            1kb
yellow open   jaeger-service-000002 uL4b0MeySRCLDGoi-y-bqw   5   1         12            2     19.5kb         19.5kb
yellow open   jaeger-service-000001 tt4HTs1RT0SCJy0QpnhdBg   1   1         11            1     13.6kb         13.6kb
```

**Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - Jaeger version: 1.27
 - Deployment: Docker
 - Backend: Opensearch v1.1.0

**Comment by a7lan** [comment]
Any news? Bug open since 2021

**Comment by shanukun** [comment]
@a7lan @Armanzor 
`jaegertracing/all-in-one` updates the index templates to the default config of '5 shards' and '1 replicas'. Set the flag `--es.create-index-templates=false` to disable this.

There are no --replicas and --shards flag, but you can use `--es.num-replicas` and `--es.num-shards` flags with `jaegertracing/all-in-one`.

**Comment by yurishkuro** [comment]
`rollover` command does not redefine the index parameters, it only creates a new alias. So it does not need shards/replicas arguments. Instead, those arguments are needed for the `init` action.
