### ISSUE TITLE
Upgrade HotROD example to use OpenTelemetry SDK

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#3380]
Per #3362

* [x] replace Jaeger SDK with OTEL SDK using an OT Bridge 
* [x] replace OT instrumentation with OpenTelemetry
* [x] Remove references to OpenTracing API
  * [x] from HotROD code
  * [x] from HotROD tests `examples/hotrod/pkg/tracing/rpcmetrics/`
  * [x] from README #4790
* [x] Remove Jaeger exporter, leave only OTLP, and update README and docker-compose

**Comment by rbroggi** [comment]
Will try to work on that during the next weekend.

**Comment by rbroggi** [comment]
Before jumping right into the code I have been studying the opentelemetry golang API. Given that the notion  of logs is not complete in opentelemetry yet but is something used in Jaeger, I wanted to make sure we have a strategy to migrate what is currently 'logged' in HotROD to what in opentelemetry is called an 'Event'. Is this a good understanding? The only other option in open telemetry is to use Attributes (key-value) which are what in jaeger-client we call Tags. 

in the [article](https://medium.com/opentracing/take-opentracing-for-a-hotrod-ride-f6e3141f7941) there is also a section that describes the difference between tags vs Logs.

**Comment by yurishkuro** [comment]
Let me clarify - at this time our intention is not to upgrade everything to OTEL API, but keep OT instrumentation and use OT-to-OTEL bridge to replace Jaeger SDK with OTEL SDK. Therefore your question is not relevant because that decision will be made by the bridge.

**Comment by rbroggi** [comment]
> Let me clarify - at this time our intention is not to upgrade everything to OTEL API, but keep OT instrumentation and use OT-to-OTEL bridge to replace Jaeger SDK with OTEL SDK. Therefore your question is not relevant because that decision will be made by the bridge.

Copy that! I'm glad I asked the question! :smile:

**Comment by yurishkuro** [comment]
getting close to completing this

**Comment by yurishkuro** [comment]
The only remaining references to opentracing are in documentation files, still need to clean them up:
```
./README.md:71:### Native support for OpenTracing
./README.md:73:Jaeger backend, Web UI, and instrumentation libraries have been designed from the ground up to support the [OpenTracing standard](https://opentracing.io/specification/).
./README.md:74:  * Represent traces as directed acyclic graphs (not just trees) via [span references](https://github.com/opentracing/specification/blob/master/specification.md#references-between-spans)
./README.md:82:The OpenTracing and OpenCensus projects have merged into a new CNCF project...
./CONTRIBUTING.md:103:      hotrod/               - Demo application that uses OpenTracing API
./examples/hotrod/README.md:6:  * as a blog post [Take OpenTracing for a HotROD ride][hotrod-tutorial],
./examples/hotrod/README.md:90:[hotrod-tutorial]: https://medium.com/@YuriShkuro/take-opentracing-for-a-hotrod-ride-f6e3141f7941
./examples/opentracing-tutorial/README.md:1:# OpenTracing Instrumentation Tutorial
./examples/opentracing-tutorial/README.md:3:To learn how to instrument your own applications for distributed tracing with Jaeger and OpenTracing API,
./examples/opentracing-tutorial/README.md:4:please see https://github.com/yurishkuro/opentracing-tutorial/.
./docker-compose/monitor/grafana.ini:1025:# Opentracing is deprecated use opentelemetry instead
```
