### ISSUE TITLE
Upgrade internal use of tracing to OpenTelemetry

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#3381]
This is aimed as an intern project for the LFX Mentorship. Please refer to https://github.com/jaegertracing/jaeger/issues/4453. [Apply here](https://mentorship.lfx.linuxfoundation.org/project/b8009398-1252-4f63-82fe-363846ccc11d).

Historically, the Jaeger backend used the OpenTracing API, with Jaeger's own Go SDK `jaeger-client-go`, for instrumenting its own internals for distributed tracing. Since Jaeger's SDKs have been deprecated (#3362), we want to upgrade the Jaeger backend to use the OpenTelemetry tracing API and SDK directly.

## Expected Outcome:
  - Replace the use of OpenTracing API with OpenTelemetry
  - Remove `jaeger-client-go` and `jaeger-lib` as dependencies
  - Remove `opentracing-go` and `opentracing-contrib/*` as dependencies
  - Switch to standard OpenTelemetry instrumentation libraries where available (e.g. for HTTP, gRPC)
  - Rethink/rework `crossdock` integration tests to test end-to-end flow with OpenTelemetry data
  - Publish a blog post on medium.com/jaegertracing documenting the experience

## Proposed approach

I don't think using OTEL-OT Bridge makes sense for this project, since it will create an extra work for adding the bridge, but will not make the actual migration any easier. Instead, I would do this in stages:
  * Right now various components of the backend take `opentracing.Tracer` as argument. As a first step, we create a wrapper object that will contain that same tracer, and pass the wrapper object to components. This will be one-time large refactoring but without any functional changes.
  * Once the first step is done, we can add OTEL Tracer to the same wrapper object.
  * Then start changing components one by one by switching them to use OTEL instrumentation.
  * When all of them have been migrated, we can remove the OpenTracing part.

Some related issues:
* [ ] https://github.com/jaegertracing/jaeger/issues/4534

**Comment by yurishkuro** [comment]
Filed as a project for LFX Mentorship https://github.com/cncf/mentoring/pull/947

**Comment by swastik959** [comment]
@yurishkuro hi I am new to this org and want to work on this issue I have worked on some kubernetes sigs and has a knowledge of golang

**Comment by swastik959** [comment]
@yurishkuro  can you guide me through its process of getting selected

**Comment by yurishkuro** [comment]
I don't know all details yet, I assume the process will be documented here https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/02-Jun-Aug

**Comment by yurishkuro** [comment]
There are guidelines here https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/README.md#program-guidelines

**Comment by octonawish-akcodes** [comment]
I am interested in this issue under lfx mentorship

**Comment by rhzx3519** [comment]
@yurishkuro Hi, I'm very interested in this task, and I'm familiar with Golang and have contributed to some cloud-native projects.

**Comment by Shubham4359** [comment]
Hi @yurishkuro, i would love to work on this issue during the upcoming LFX mentorship.
I have previously worked in Golang and have also Contributed to other CNCF organisations Like Thanos. 
Can you please provide some starting material to work on this issue also any other things to keep in mind.
Thanks

**Comment by Swapnil-2502** [comment]
> Filed as a project for LFX Mentorship [cncf/mentoring#947](https://github.com/cncf/mentoring/pull/947)

Yeah I just saw it will be applying for the LFX Mentorship.

**Comment by shashankiitbhu** [comment]
Hi, I am very interested in this task and would like to work on this under LFX mentorship program.

**Comment by yurishkuro** [comment]
Applicants interested in this project: please see https://github.com/jaegertracing/jaeger/issues/4453

**Comment by haanhvu** [comment]
For anyone looking for guide/resources to study this project:
- Just google "migrate from OpenTracing to OpenTelemetry". This is actually a prominent issue generally.
- Some Jaeger-related resources:
https://www.timescale.com/blog/how-to-successfully-migrate-from-jaeger-to-opentelemetry-tracing/
https://medium.com/jaegertracing/experiment-migrating-opentracing-based-application-in-go-to-use-the-opentelemetry-sdk-29b09fe2fbc4

**Comment by yurishkuro** [comment]
@afzal442 will be working on this as part of LFX Mentorship program.

**Comment by yurishkuro** [comment]
This can be considered complete. We still import jaeger-client-go, but only in tests.
```
$ grx jaeger-client-go .
./crossdock/services/tracehandler_test.go:31:	"github.com/uber/jaeger-client-go"
./crossdock/services/tracehandler.go:29:	"github.com/uber/jaeger-client-go"
./cmd/collector/app/handler/http_thrift_handler_test.go:32:	jaegerClient "github.com/uber/jaeger-client-go"
./cmd/collector/app/handler/http_thrift_handler_test.go:33:	"github.com/uber/jaeger-client-go/transport"
./go.mod:50:	github.com/uber/jaeger-client-go v2.30.0+incompatible
```
