### ISSUE TITLE
Request with "parent+children" spans to the zipkin collector service fails with error: index out of range

### ISSUE THREAD

**Issue by alexsuraykin** [jaegertracing/jaeger#3404]
If we send parent and children spans in request, jaeger will be failed with error: "runtime error: index out of range"

**Steps to reproduce:**
1.  Run jaeger.
2.  Send POST request to the "<jaeger_address>: <zipkin_collector_port>/api/v1/spans" with next json in the body:
```json
[
    {
        "traceId": "4ed11df465275600",
        "id": "4ed11df465275600",
        "name": "get /",
        "timestamp": 1633073248674949,
        "duration": 14861,
        "localEndpoint": {
            "serviceName": "first_service",
            "ipv4": "10.0.2.15"
        },
        "annotations": [
            {
                "timestamp": 1633073248674949,
                "value": "sr"
            },
            {
                "timestamp": 163307324868981,
                "value": "ss"
            }
        ]
    },
    {
        "traceId": "4ed11df465275600",
        "parentId": "4ed11df465275600",
        "id": "c943743e25dc2cdf",
        "name": "get /api",
        "timestamp": 1633073248678309,
        "duration": 3360,
        "localEndpoint": {
            "serviceName": "first_service",
            "ipv4": "10.0.2.15"
        },
        "annotations": [
            {
                "timestamp": 1633073248678309,
                "value": "cs"
            },
            {
                "timestamp": 1633073248681669,
                "value": "sr"
            },
            {
                "timestamp": 1633073248685029,
                "value": "cr"
            },
            {
                "timestamp": 1633073248688388,
                "value": "ss"
            }
        ]
    }
]
```
**Expected result:** 202 Accepted
**Actual result:** 500 Internal Server Error

 - Jaeger version: 1.28.0, master
 - Deployment: Docker, Kubernetes

**Additional context**
During the debug, we found that the problem occurs in the [SubmitZipkinBatch](https://github.com/jaegertracing/jaeger/blob/master/cmd/collector/app/handler/thrift_span_handler.go#L109-L132) function.

After "Sanitize" there are "mSpans" array with 3 items and "bools" with labels of processed spans :

![image](https://user-images.githubusercontent.com/13114682/142899020-1c1a1ea3-3dfe-4208-97fd-4d382e24b2ce.png)

![image](https://user-images.githubusercontent.com/13114682/142900584-8df8b250-e224-4989-b471-e50a672a0047.png)

Where span with  "parentId" field was converted in two items.

And then function creates "responses" array with length=2(from original "spans"), but iterates through "bools" with length =3. Eventually there is rises error "index out of range [2] with length 2".

**Comment by pavolloffay** [comment]
@alexsuraykin thanks for reporting this. Would you like to work on a fix?

**Comment by frzifus** [comment]
hey, out of interest, I went down the street and noticed this comment:
> [if the span is client and server we split it into two separate spans](https://github.com/jaegertracing/jaeger/blob/main/model/converter/thrift/zipkin/to_domain.go#L158)

Looking at the 2nd span, it matches this condition.

**Comment by rgroothuijsen** [comment]
The problem appears to be that the `IsRPCClient()` method only checks if the span has a `kind` field set to `CLIENT`, but this field  was not introduced until v2. If I understand correctly, the v1 equivalent would be detecting the presence of a `cs` annotation.
