### ISSUE TITLE
Product/File version in Windows executables

### ISSUE THREAD

**Issue by pocki** [jaegertracing/jaeger#3414]
## Requirement - what kind of business use case are you trying to solve?
Actual the windows executables (jaeger-agent.exe, jaeger-collector.exe, ...) don't have a version set. It is hard to identify the current used version and check if the actual used version is outdated.

![image](https://user-images.githubusercontent.com/2448303/143830707-153c3f71-a84d-42db-a0db-5b95b2525351.png)

## Problem - what in Jaeger blocks you from solving the requirement?
Checking the actual used version and identity an outdated version.
We have some applications running native on Windows (Server) and therefore the agent is also running native on Windows.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Set the Product and/or File Version of the windows executables on compile or release.

**Comment by yurishkuro** [comment]
Jaeger binaries support "version" subcommand, is that not enough?

**Comment by pocki** [comment]
Thanks for the information. It's a little bit hidden.
Normally the services are always running and you just want to check the version. 
On Windows users are more likely to check it the properties page instead of extra typing in a command (also when the parameter for version nearly every app uses different)

**Comment by pocki** [comment]
Sorry, I am not familiar with Go and Go compiler.

**Comment by smolgeat** [comment]
Hi can I take this?

**Comment by yurishkuro** [comment]
@smolgeat sure

**Comment by xmarcoied** [comment]
Hi @yurishkuro. 
>  I don't know if Go compiler supports setting these properties on the Windows binary, but I don't have any objections to including them.

I don't think there's a way to straightforward doing this configurations with Go Compile. but I am thinking to use a 3rd party service/repo to embed such info through a `go:generate`. What do you think about this approach? I can draft a PR for one.

**Comment by yurishkuro** [comment]
That might be ok, I would recommend checking what other projects do (e.g. does Hugo have Windows binaries? Do they tag them like that?)

**Comment by keremgocen** [comment]
looking for a beginner-friendly issue if this is available

**Comment by yurishkuro** [comment]
it is

**Comment by ananyak19** [comment]
Hey can I work on this?

**Comment by yurishkuro** [comment]
Yes

**Comment by ananyak19** [comment]
Hi @pocki I am a first time contributor, can you please guide on how to get started here and where I need to make the changes in order to solve the issue?

**Comment by pocki** [comment]
As you can see above, I am also not familiar with Go and the Go Compiler. 
Please check the [contribution guidelines](https://github.com/jaegertracing/jaeger/blob/main/CONTRIBUTING.md) for this project.

**Comment by yurishkuro** [comment]
I see references to two utilities that seem to achieve this: https://stackoverflow.com/questions/35126344/how-to-set-the-file-version-field-in-pe-header-of-exe-files

**Comment by ananyak19** [comment]
Hi
I'm getting this error on running the command - git clone
***@***.***:jaegertracing/jaeger.git
jaeger
[image: image.png]

looks like i don't have access rights.

**Comment by ananyak19** [comment]
Hi, @pocki  @yurishkuro   i tried to clone the repository but don't have the required access rights. Can you help me with that?

**Comment by yurishkuro** [comment]
you need to clone into your personal namespace, e.g. ananyak19/jaeger
