### ISSUE TITLE
jaeger operator installation

### ISSUE THREAD

**Issue by xuanyingcool** [jaegertracing/jaeger#3424]
the link open 404
[](https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml)

The next few links are also 404

**Comment by xuanyingcool** [comment]
https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml

**Comment by albertteoh** [comment]
Relates to: https://github.com/jaegertracing/documentation/issues/325

**Comment by pavolloffay** [comment]
NO the https://github.com/jaegertracing/documentation/issues/325 is old. 

This issue is related to https://github.com/jaegertracing/jaeger-operator/issues/1630

@rubenvp8510 could you please fix the documentation to reflect changes to the operator?

**Comment by venkataphaniv** [comment]
Try this:

https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.28.0/deploy/operator.yaml

Replace 1.28 with 1.27, 1.26... and it worked for me.

**Comment by matheushent** [comment]
Quite frustating to have this open so long. It is still happening; what's does it take to fix a doc?
