### ISSUE TITLE
Soft multitenancy, tenant aware storage

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#3427]
## Requirement - what kind of business use case are you trying to solve?

I want to deploy a single Jaeger instance (collector, query) and be able to store and query data for multiple tenants. I want tenant data to be separated e.g. I don't want tenant `A` to access data from tenant `B`. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The tenant information can be propagated down to the storage layer and storage can decide how to store it. For instance, in ES the storage would add tenant name into index name. This feature requires changes in multiple areas - storage, API, metrics, internal components. The storage implementation could decide whether multi-tenancy is supported or not.

### Storage API change

There are probably 3 ways to implement this at the storage API
1. Add a parameter to identify a tenant
2. Propagate tenant in `context.Context`

There might be as well a third solution - propagate tenant in data, but I would exclude it because for instance `GetServices` (and other APIs) does not have any data parameter.

```go
type Writer interface {
	WriteSpan(ctx context.Context, span *model.Span) error
}

type Reader interface {
	GetTrace(ctx context.Context, traceID model.TraceID) (*model.Trace, error)
	GetServices(ctx context.Context) ([]string, error)
        ...
```

### API change

For similar reasons as in the storage API here, I would propose to propagate tenant in headers and then put it in the context.

```proto
message PostSpansRequest {
    Batch batch = 1 [
        (gogoproto.nullable) = false
    ];
}

message PostSpansResponse {
}

service CollectorService {
    rpc PostSpans(PostSpansRequest) returns (PostSpansResponse) {
        option (google.api.http) = {
            post: "/api/v2/spans"
            body: "*"
        };
    }
}

message GetServicesRequest {}

message GetServicesResponse {
  repeated string services = 1;
}
```

### Internal metrics

Some internal metrics should include tenantID label

## References 

Multi-tenancy blog post: https://medium.com/jaegertracing/jaeger-and-multitenancy-99dfa1d49dc0

**Comment by esnible** [comment]
+1

Does it make sense to propose an API for admin functions such as listing the tenants known to storage, or configuring a list of acceptable tenants for WriteSpan?  Or are those ideas outside of the APIs and part of script tools and internal config?

**Comment by jpkrohling** [comment]
Jaeger v2 will inherit the multi-tenancy capabilities of OpenTelemetry Collector, as defined here: 
https://github.com/open-telemetry/opentelemetry-collector/issues/1260

For Jaeger v2, it means that we would have a configuration like this:
```
processors:
  routing:
    from_attribute: X-Tenant
    default_exporters: elasticsearch
    table:
    - value: acme
      exporters: [elasticsearch/acme]
exporters:
  elasticsearch:
    endpoint: localhost:9122
  elasticsearch/acme:
    endpoint: localhost:9123
```

This is mostly handled by the routing processor: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor

Would that work for your scenario?

**Comment by yurishkuro** [comment]
My preference for storage APIs would be to capture tenancy explicitly as an argument, not pass it implicitly via Context.

**Comment by pavolloffay** [comment]
It makes sense. I was also thinking about RBAC here and it would be maybe great to support a list of tenants? The storage could support join view across multiple tenants.

**Comment by pavolloffay** [comment]
About the Jaeger V2, this is something we have been talking about a long time ago. Pity that Jaeger v2 codebase was removed in the past.

It could partially solve our use-case. In this case, the collector requires reconfiguration and restart if a new tenant is added/removed. A preferred solution is to do not require deployment changes when adding a new tenant.

**Comment by jpkrohling** [comment]
> Pity that Jaeger v2 codebase was removed in the past.

We decided to remove it, as it was causing tech debt that nobody was taking care of. More specifically, OpenTelemetry Collector was breaking the API compatibility at every new release, so bumping the versions at go.mod wasn't sufficient. From what I remember, the plan is still to have v2 based on OpenTelemetry Collector, we are just waiting for v1 to happen.

**Comment by bwplotka** [comment]
Thanks, @pavolloffay for starting this1 🤗  

I am digesting your @jpkrohling response https://github.com/jaegertracing/jaeger/issues/3427#issuecomment-985632588, but I don't get how this is multi-tenant. It only helps with routing to hard tenant elastic backends, right?

Ideally, we have hundreds / thousands of tenants using a single Jaeger + Storage cluster. In both Cortex, Thanos, Loki and Tempo this can be solved by attaching tag/label/externalLabel/attribute to the data or group of data from single tenant. So then you can limit access, RBAC, limit resources based on requests against certain data. Ideally, cross-tenant reads are supported too. Would there be a way to just add another tag to each trace? and then expand API to treat is a special parameter when calling (could be header as well, no need for the parameter for the first iteration).

**Comment by jpkrohling** [comment]
Pavol linked a blog post published some time ago on the topic of multitenancy and the different options. Typically, we've been hearing people wanting to have different storages for different tenants, which resulted in the routing processor.

Storing tenancy information as part of the span is certainly possible, but it leads to questions like:

- How do you ensure the tenant ID is only set at trusted components? 
- What to do with traces composed of spans coming from multiple tenants? Should those spans be simply from the trace, or should people still be able to view the timing information, just not its metadata?

The routing processor would be part of a Jaeger v2 instance, so, you'd still only have one Jaeger cluster. You can also still have one storage cluster, with each tenant being an index at the storage layer.

**Comment by bwplotka** [comment]
Good points Juraci, thanks 👍🏽  

> How do you ensure the tenant ID is only set at trusted components?

By overriding it always on trusted proxy/collector?


> What to do with traces composed of spans coming from multiple tenants? Should those spans be simply from the trace, or should people still be able to view the timing information, just not its metadata?

Good question. I think this should be simply not allowed in single iteration, i.e those never connect

> The routing processor would be part of a Jaeger v2 instance, so, you'd still only have one Jaeger cluster. You can also still have one storage cluster, with each tenant being an index at the storage layer.

great!

**Comment by jpkrohling** [comment]
> By overriding it always on trusted proxy/collector?

It's doable, especially if we use an attribute name that is unique enough to us, like `__jaeger_tenant`. But in general, just overriding data is a problem waiting to happen. After all, we'd be overriding a value that was explicitly set by someone at an earlier stage.

**Comment by pavolloffay** [comment]
The OTELcol proposal is missing one key use case and that is the read/query path. @jpkrohling could you please extend your proposal and include it? It might be very similar to multiple exporters but in this case using multiple extensions, here I am not sure if there can be multiple extensions of the same type.

**Comment by yurishkuro** [comment]
> The OTELcol proposal

What is this proposal exactly? Do you mean Jaeger v2 rebuilt on OTELcol? IMO it doesn't solve the multi-tenancy issue.

**Comment by pavolloffay** [comment]
yes I mean Jaeger V2. It looks more like a workaround and pushes the heavy lifting on the user to wire/configure everything together. 

From your perspective Yuri, what are the missing pieces?

**Comment by yurishkuro** [comment]
I think the storage and UI need to be tenant-aware, OTELcol does not help with that.

**Comment by dino-ma** [comment]
Can we also use the service name for storage isolation in injester and query UI for adaptation

**Comment by dino-ma** [comment]
Because as a multi tenant solution in the cloud era, we need to consider being as insensitive to tenants as possible, so we may provide a general collector. In this case, I suggest that different storage resources can be adapted according to the service name. Storage resources here refer to storage clusters with the same service and different storage drivers

**Comment by dino-ma** [comment]
Maybe the point we need to change is that injester and query UI can complete this relatively complex thing

**Comment by yurishkuro** [comment]
A trace usually spans many services, service name is not a tenant-like differentiator.

**Comment by dino-ma** [comment]
If this is the case, as the Infrastructure Department of a company, I provide a Jaeger cluster. If I do not distinguish according to services, it is bound to let my tenants know which cluster he uses, and I hope I can flexibly schedule the storage cluster at the back end. Because we may face hundreds of thousands of services

@yurishkuro

**Comment by dino-ma** [comment]
We may encounter the scenario of opening up and isolating certain services. It is not that the user or business needs to decide which tenant to use from input to end

@yurishkuro

**Comment by pavolloffay** [comment]
Closing, let's continue discussion in #3881
