### ISSUE TITLE
make install_examples not working on Windows

### ISSUE THREAD

**Issue by edukondalugorla** [jaegertracing/jaeger#344]
"make install_examples"  is not working in windows . Errors  are  in attached file. 
[error.txt](https://github.com/uber/jaeger/files/1231019/error.txt)

**Comment by vprithvi** [comment]
I'm surprised to see gradle output. Could you verify that you have glide installed from https://github.com/Masterminds/glide. 
Could you also paste the output of `glide --version`?

**Comment by edukondalugorla** [comment]
Yes I installed Gradle , Below is my gradle version result . 

E:\Workspace\GOSPACE\src\github.com\uber\jaeger>gradle -v

------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------

Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Windows 7 6.1 x86

E:\Workspace\GOSPACE\src\github.com\uber\jaeger>

**Comment by edukondalugorla** [comment]
glide version result below


E:\Workspace\GOSPACE\src\github.com\uber\jaeger>glide --version

          ___  _  _     _
         / __|| |(_) __| | ___
        | (_ || || |/ _` |/ -_)
         \___||_||_|\__,_|\___|


         version : 0.9.2
         build   : 7/10/16 11:29:30 PM

E:\Workspace\GOSPACE\src\github.com\uber\jaeger>

**Comment by vprithvi** [comment]
Was glide installed by following the instructions on https://github.com/Masterminds/glide ?
Could you update to the latest version?

**Comment by edukondalugorla** [comment]
I downloaded source code from https://github.com/Masterminds/glide into my GOPATH. In windows  make install is not working, Can you help how to install in windows.

**Comment by edukondalugorla** [comment]
I installed glide by downloding from https://github.com/Masterminds/glide/releases. and set the PATH variable.
now make install_examples  output  find in attached file.
[error.txt](https://github.com/uber/jaeger/files/1233362/error.txt)

**Comment by yurishkuro** [comment]
We do not support building on Windows, the Makefile has only been tested on Linux & MacOS.

If you must build on Windows, you're better off doing it in a Linux VM or in a Docker container that contains Go toolchain.

**Comment by yurishkuro** [comment]
`install_examples` target has been removed
