### ISSUE TITLE
Traceids with no calling relationship between different services may be duplicate

### ISSUE THREAD

**Issue by dino-ma** [jaegertracing/jaeger#3444]
**Describe the bug**
Traceids with no calling relationship between different services may be duplicate

**To Reproduce**
I have a very high QPS service, which has no upstream and downstream call relationship with other services, but it is shown in the topology diagram that almost all services are circularly dependent on it

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - OS: centos
 - Jaeger version:Go-2.29.1
 - Deployment: sidecar

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

**Comment by jkowall** [comment]
There is not enough detail here to try to replicate the problem. I am not sure why you want tracing on a service with no dependencies. Please reopen with more details on how we can replicate the problem you reported. Please follow the troubleshooting steps.
