### ISSUE TITLE
Build on a Mac

### ISSUE THREAD

**Issue by esnible** [jaegertracing/jaeger#3445]
**Describe the bug**

Jaeger container builds do not work on a Mac (using Docker desktop).  Or, if they do, the technique is not documented.

`make create-baseimg` yields

```
error: failed to solve: failed to do request: Head "http://localhost:5000/v2/baseimg_alpine/blobs/sha256:be307f383ecc62b27a29b599c3fc9d3129693a798e7fcce614f09174cfe2d354": dial tcp 127.0.0.1:5000: connect: connection refused
```

**To Reproduce**

See above.

**Version (please complete the following information):**
 - OS: Mac OSX
 - Jaeger version: Main/Master, 1.29.0 I think
 - Deployment: none
 - Docker Desktop: 4.2.0

**Additional context**

On the Mac, anything about the host should be `docker.for.mac.localhost` instead of `localhost`!  I couldn't figure out how to make that happen, though.

**Comment by yurishkuro** [comment]
I think the script tries to start a local registry, which may be failing for you. It failed for me, I didn't investigate what's using the port:
```
docker buildx inspect jaeger-build > /dev/null || docker buildx create --use --name=jaeger-build --buildkitd-flags="--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host" --driver-opt="network=host"
docker inspect registry > /dev/null || docker run --rm -d -p 5000:5000 --name registry registry:2

Error: No such object: registry
f5f2746e9b16163542f7c5022c835b9bb430dddb24cdb6724aa8a83943661e90
docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use.
```

**Comment by esnible** [comment]
I am using Docker Desktop 4.2.0.  I have no trouble running the registry:

```
docker ps       
CONTAINER ID   IMAGE                           COMMAND                  CREATED             STATUS             PORTS                    NAMES
1212eaae5e3e   moby/buildkit:buildx-stable-1   "buildkitd"              About an hour ago   Up About an hour                            buildx_buildkit_crazy_tharp0
56696386a448   registry:2                      "/entrypoint.sh /etc…"   About an hour ago   Up About an hour   0.0.0.0:5000->5000/tcp   registry
```

My problem is that the registry is not available on `localhost:5000`, but on `host.docker.internal:5000`.

docker run -it osexp2000/ubuntu-with-utils curl localhost:5000 
curl: (7) Failed to connect to localhost port 5000: Connection refused

docker run osexp2000/ubuntu-with-utils curl -v host.docker.internal:5000
...
< HTTP/1.1 200 OK
...
```

**Comment by yurishkuro** [comment]
I found that Apple AirPlay was using port 5000, so turning it off re-enabled the local registry. After that the build works fine for me, but I am on Docker Desktop 3.6.0.

We may need to introduce a way to parameterize the location of the registry to allow `host.docker.internal:5000` instead of localhost.

**Comment by yurishkuro** [comment]
```
$ grx localhost:5000 .
./docker/Makefile:6:BASE_IMAGE := localhost:5000/baseimg_alpine:latest
./docker/Makefile:7:DEBUG_IMAGE := localhost:5000/debugimg_alpine:latest
./scripts/build-all-in-one-image.sh:44:run_integration_test localhost:5000/$repo
./scripts/build-all-in-one-image.sh:53:run_integration_test localhost:5000/$repo
./scripts/hotrod-integration-test.sh:16:export CID=$(docker run -d -p 8080:8080 localhost:5000/$REPO:latest)
./scripts/build-upload-a-docker-image.sh:19:		base_debug_img_arg="--build-arg base_image=localhost:5000/baseimg_alpine:latest --build-arg debug_image=localhost:5000/debugimg_alpine:latest "
./scripts/build-upload-a-docker-image.sh:49:    IMAGE_TAGS="--tag localhost:5000/${name_space}/${component_name}:latest"
```
