### ISSUE TITLE
Set Cassandra compaction window size according to TTL

### ISSUE THREAD

**Issue by andrey-kondratov** [jaegertracing/jaeger#3466]
## Requirement - what kind of business use case are you trying to solve?

I am using Docker image [jaegertracing/jaeger-cassandra-schema](https://hub.docker.com/r/jaegertracing/jaeger-cassandra-schema) for creating a keyspace in Cassandra for Jaeger data. 

When filling a Cassandra cluster with a schema using non-default TTL as a parameter, it would be great to provide for better performance on large datasets by setting the appropriate `compaction_window_size` according to [the rule of thumb of max 50 buckets per table](https://thelastpickle.com/blog/2016/12/08/TWCS-part1.html).

## Problem - what in Jaeger blocks you from solving the requirement?

The current [implementation](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/cassandra/schema/v004.cql.tmpl#L19-L21) allows using [a custom TTL](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/cassandra/schema/v004.cql.tmpl#L74) but has a [hard-coded `compaction_window_size` of 1 hour](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/cassandra/schema/v004.cql.tmpl#L70-L71) for TTL of 2 days.

In case when TTL is set to a large value like 180 days, the recommended compaction window size is ~4 days (according to max 50 buckets per table: `180 / 50 = 3.6`). 

This can be worked around later with an `ALTER TABLE` command, however, this requires additional effort. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

a) support passing `compaction_window_size` to the docker image in a similar manner as `$trace_ttl`;
b) calculate `compaction_window_size` based on `$trace_ttl` value.

**Comment by varshith257** [comment]
@yurishkuro Is it up to work?

**Comment by yurishkuro** [comment]
yes

**Comment by varshith257** [comment]
@yurishkuro I have commented on issues which has been stale for long and ere they ready to work can comment there

**Comment by jeetb2022** [comment]
@yurishkuro Is the the issue still relevant if yes, i would love to give it a look.

**Comment by yurishkuro** [comment]
@akstron Yes, but I think one good follow-up is to add a comment to the Compaction Window config field with the advice from [official docs](https://cassandra.apache.org/doc/stable/cassandra/operating/compaction/twcs.html#changing-timewindowcompactionstrategy-options) (I rephrased since we don't split unit and size):

> Ideally, operators should select a compaction window size that produces approximately less than 50 windows. For example, if writing with a 90 day TTL, a 3 day window would be a reasonable choice.

**Comment by akstron** [comment]
You mean this right?

>Ideally, operators should select a compaction window size that produces approximately less than <del>50</del> 30 windows. For example, if writing with a 90 day TTL, a 3 day window would be a reasonable choice.

I can raise a PR with this update and close this issue.

**Comment by yurishkuro** [comment]
I meant 50

**Comment by akstron** [comment]
Why 50? I mean, the recommendation is 20-30. Or is it just that the difference is not much so that's okay?
