### ISSUE TITLE
query dependency from es return empty. Does 'IndexDateLayout' missed when init es.dependencystore ?

### ISSUE THREAD

**Issue by galric** [jaegertracing/jaeger#3523]
**Describe the bug**
system architecture and deep dependency graph return empty result while data exists in ES. 
does the function 'createDependencyReader' in 'https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/es/factory.go' forget to init IndexDateLayout ?

current:

```
	reader := esDepStore.NewDependencyStore(esDepStore.DependencyStoreParams{
		Client:              client,
		Logger:              logger,
		IndexPrefix:         cfg.GetIndexPrefix(),
		MaxDocCount:         cfg.GetMaxDocCount(),
		UseReadWriteAliases: cfg.GetUseReadWriteAliases(),
	})

```

may should be:

```
	reader := esDepStore.NewDependencyStore(esDepStore.DependencyStoreParams{
		Client:              client,
		Logger:              logger,
		IndexPrefix:         cfg.GetIndexPrefix(),
		MaxDocCount:         cfg.GetMaxDocCount(),
		UseReadWriteAliases: cfg.GetUseReadWriteAliases(),
		IndexDateLayout:     cfg.GetIndexDateLayoutDependencies(),
	})

```

add this

```

IndexDateLayout:     cfg.GetIndexDateLayoutDependencies(),

```

to make sure 
```
func indexWithDate(indexNamePrefix, indexDateLayout string, date time.Time) string {
	return indexNamePrefix + date.UTC().Format(indexDateLayout)
}
```
from https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/es/dependencystore/storage.go 
not alway return a empty string 

which effect DependencyStore.GetDependencies can only search 'jaeger-dependencies-' not 'jaeger-dependencies-2022-02-08'

**Comment by galric** [comment]
i test the diff in my local environment, and it seems works

**Comment by mindw** [comment]
@galric got hit by this also - with the same conclusion.

**Comment by jkowall** [comment]
Seems to be fixed per https://github.com/jaegertracing/jaeger/pull/3524
