### ISSUE TITLE
Ingester doesn't consume from kafka when lz4 compression enabled

### ISSUE THREAD

**Issue by micwiel** [jaegertracing/jaeger#3537]
**Describe the bug**
Ingester doesn't consume from kafka when lz4 compression enabled

**To Reproduce**
1. Add `KAFKA_PRODUCER_COMPRESSION=lz4` to jaeger-collector or `compression.type=lz4` to server.properties in kafka
2. jaeger-ingester stops consuming
3.

**Expected behavior**
jaeger-ingester should process messages like when any other type of compression is used (none, gzip, snappy, zstd)

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.31
 - Deployment: Docker

**Additional context**
Kafka version: 3.1.0
For any other type (except lz4) it is working for me but I need this particular one because of its speed and other business requirements.

**Comment by pavolloffay** [comment]
@micwiel are there any logs that show what is going wrong?

**Comment by micwiel** [comment]
@pavolloffay I deployed 

```
- docker run -it --rm -p 2181:2181 -e ALLOW_ANONYMOUS_LOGIN=yes bitnami/zookeeper:latest
- docker run -it --rm -e ALLOW_PLAINTEXT_LISTENER=yes -e KAFKA_CFG_ZOOKEEPER_CONNECT=localhost:2181 -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT -e KAFKA_CFG_LISTENERS=EXTERNAL://:9092 -e KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9092 -e KAFKA_CFG_INTER_BROKER_LISTENER_NAME=EXTERNAL -e KAFKA_CFG_COMPRESSION_TYPE=snappy -p 9092:9092 bitnami/kafka:latest
- docker run --rm -p 9200:9200 -p 9300:9300 --network=host -e "discovery.type=single-node" elasticsearch:7.10.1
- docker run --rm -e SPAN_STORAGE_TYPE=kafka -e KAFKA_PRODUCER_BROKERS=localhost:9092 -e KAFKA_TOPIC=jaeger-spans -p14250:14250 --network=host jaegertracing/jaeger-collector:1.31
- docker run --rm -e SPAN_STORAGE_TYPE=kafka -p6831:6831/udp --network=host jaegertracing/jaeger-agent:1.31 --reporter.grpc.host-port=localhost:14250
- docker run --rm --network=host --env JAEGER_AGENT_HOST=localhost --env JAEGER_AGENT_PORT=6831 -p8080-8083:8080-8083 jaegertracing/example-hotrod:latest all
- docker run --rm --network=host -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://localhost:9200 -e KAFKA_CONSUMER_BROKERS=localhost:9092 -e KAFKA_CONSUMER_GROUP_ID=__test-jaeger-ingester jaegertracing/jaeger-ingester:1.31 --log-level debug
```

and then generated some traces with hotrod. Some logs from ingester

> 2022/03/08 08:44:06 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
{"level":"info","ts":1646729046.2480888,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1646729046.2481117,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1646729046.2482195,"caller":"flags/admin.go:104","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1646729046.2482548,"caller":"flags/admin.go:115","msg":"Starting admin HTTP server","http-addr":":14270"}
{"level":"info","ts":1646729046.2482684,"caller":"flags/admin.go:96","msg":"Admin server started","http.host-port":"[::]:14270","health-status":"unavailable"}
{"level":"info","ts":1646729046.2626197,"caller":"config/config.go:205","msg":"Elasticsearch detected","version":7}
{"level":"info","ts":1646729046.2817426,"caller":"zapgrpc/zapgrpc.go:129","msg":"Deprecation warning: 299 Elasticsearch-7.10.1-1c34507e66d7db1211f66f3513706fdf548736aa \"legacy template [jaeger-span] has index patterns [*jaeger-span-*] matching patterns from existing composable templates [ilm-history,.triggered_watches,.slm-history,synthetics,metrics,.watch-history-12,.watches,logs] with patterns (ilm-history => [ilm-history-3*],.triggered_watches => [.triggered_watches*],.slm-history => [.slm-history-3*],synthetics => [synthetics-*-*],metrics => [metrics-*-*],.watch-history-12 => [.watcher-history-12*],.watches => [.watches*],logs => [logs-*-*]); this template [jaeger-span] may be ignored in favor of a composable template at index creation time\""}
{"level":"info","ts":1646729046.3016512,"caller":"zapgrpc/zapgrpc.go:129","msg":"Deprecation warning: 299 Elasticsearch-7.10.1-1c34507e66d7db1211f66f3513706fdf548736aa \"legacy template [jaeger-service] has index patterns [*jaeger-service-*] matching patterns from existing composable templates [ilm-history,.triggered_watches,.slm-history,synthetics,metrics,.watch-history-12,.watches,logs] with patterns (ilm-history => [ilm-history-3*],.triggered_watches => [.triggered_watches*],.slm-history => [.slm-history-3*],synthetics => [synthetics-*-*],metrics => [metrics-*-*],.watch-history-12 => [.watcher-history-12*],.watches => [.watches*],logs => [logs-*-*]); this template [jaeger-service] may be ignored in favor of a composable template at index creation time\""}
{"level":"debug","ts":1646729046.3091908,"caller":"consumer/deadlock_detector.go:147","msg":"Global deadlock detector disabled"}
{"level":"info","ts":1646729046.3092127,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1646729046.3092225,"caller":"consumer/consumer.go:79","msg":"Starting main loop"}
{"level":"info","ts":1646729046.4250627,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":0}
{"level":"info","ts":1646729046.4250739,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":0}
{"level":"debug","ts":1646729046.4253533,"caller":"consumer/deadlock_detector.go:98","msg":"Partition deadlock detector disabled"}
{"level":"debug","ts":1646729049.283816,"caller":"consumer/consumer.go:138","msg":"Got msg","msg":{"Headers":null,"Timestamp":"0001-01-01T00:00:00Z","BlockTimestamp":"0001-01-01T00:00:00Z","Key":"NzBhZmFjNTkzMTcxZjRiNQ==","Value":"ChAAAAAAAAAAAHCvrFkxcfS1Eghwr6xZMXH0tRoQSFRUUCBHRVQgL2NvbmZpZygBMgwI2K6ckQYQ4MmDlAM6BBCougRCFQoMc2FtcGxlci50eXBlGgVjb25zdEITCg1zYW1wbGVyLnBhcmFtEAEgAUITCglzcGFuLmtpbmQaBnNlcnZlckISCgtodHRwLm1ldGhvZBoDR0VUQiwKCGh0dHAudXJsGiAvY29uZmlnP25vbnNlPTAuOTc5ODI1NzEwMTE3NDg5OEIVCgljb21wb25lbnQaCG5ldC9odHRwQhcKEGh0dHAuc3RhdHVzX2NvZGUQAijIAUIdChRpbnRlcm5hbC5zcGFuLmZvcm1hdBoFcHJvdG9ScQoIZnJvbnRlbmQSGwoOamFlZ2VyLnZlcnNpb24aCUdvLTIuMzAuMBIRCghob3N0bmFtZRoFdHdvdXASFAoCaXAaDjE5Mi4xNjguODguMjQ1Eh8KC2NsaWVudC11dWlkGhA1MDliYzg2YzFiNTk2ZTli","Topic":"jaeger-spans","Partition":0,"Offset":1339}}
{"level":"info","ts":1646729049.2844117,"caller":"consumer/processor_factory.go:65","msg":"Creating new processors","partition":0}
{"level":"debug","ts":1646729049.2847803,"caller":"processor/parallel_processor.go:50","msg":"Spawning goroutines to process messages","num_routines":1000}
{"level":"debug","ts":1646729049.2923176,"caller":"consumer/consumer.go:138","msg":"Got msg","msg":{"Headers":null,"Timestamp":"0001-01-01T00:00:00Z","BlockTimestamp":"0001-01-01T00:00:00Z","Key":"MDg5ODQ4MjgwMWViYzEwMQ==","Value":"ChAAAAAAAAAAAAiYSCgB68EBEggKXGpJaq00HxoTSFRUUCBHRVQ6IC9jdXN0b21lciIcChAAAAAAAAAAAAiYSCgB68EBEggImEgoAevBASgBMgwI2K6ckQYQsPjJlQM6BhCg9c6RAUIdChRpbnRlcm5hbC5zcGFuLmZvcm1hdBoFcHJvdG9ScQoIZnJvbnRlbmQSGwoOamFlZ2VyLnZlcnNpb24aCUdvLTIuMzAuMBIRCghob3N0bmFtZRoFdHdvdXASFAoCaXAaDjE5Mi4xNjguODguMjQ1Eh8KC2NsaWVudC11dWlkGhA1MDliYzg2YzFiNTk2ZTli","Topic":"jaeger-spans","Partition":0,"Offset":1340}}

Then changed `-e KAFKA_CFG_COMPRESSION_TYPE=snappy` to `-e KAFKA_CFG_COMPRESSION_TYPE=lz4` in kafka, restarted all containers, generated more traces in hotrod. All logs from ingester
>2022/03/08 08:45:09 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
{"level":"info","ts":1646729109.8175604,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1646729109.8176231,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1646729109.8178535,"caller":"flags/admin.go:104","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1646729109.8179219,"caller":"flags/admin.go:115","msg":"Starting admin HTTP server","http-addr":":14270"}
{"level":"info","ts":1646729109.8179555,"caller":"flags/admin.go:96","msg":"Admin server started","http.host-port":"[::]:14270","health-status":"unavailable"}
{"level":"info","ts":1646729109.8407543,"caller":"config/config.go:205","msg":"Elasticsearch detected","version":7}
{"level":"info","ts":1646729109.861239,"caller":"zapgrpc/zapgrpc.go:129","msg":"Deprecation warning: 299 Elasticsearch-7.10.1-1c34507e66d7db1211f66f3513706fdf548736aa \"legacy template [jaeger-span] has index patterns [*jaeger-span-*] matching patterns from existing composable templates [ilm-history,.triggered_watches,.slm-history,synthetics,metrics,.watch-history-12,.watches,logs] with patterns (ilm-history => [ilm-history-3*],.triggered_watches => [.triggered_watches*],.slm-history => [.slm-history-3*],synthetics => [synthetics-*-*],metrics => [metrics-*-*],.watch-history-12 => [.watcher-history-12*],.watches => [.watches*],logs => [logs-*-*]); this template [jaeger-span] may be ignored in favor of a composable template at index creation time\""}
{"level":"info","ts":1646729109.8817034,"caller":"zapgrpc/zapgrpc.go:129","msg":"Deprecation warning: 299 Elasticsearch-7.10.1-1c34507e66d7db1211f66f3513706fdf548736aa \"legacy template [jaeger-service] has index patterns [*jaeger-service-*] matching patterns from existing composable templates [ilm-history,.triggered_watches,.slm-history,synthetics,metrics,.watch-history-12,.watches,logs] with patterns (ilm-history => [ilm-history-3*],.triggered_watches => [.triggered_watches*],.slm-history => [.slm-history-3*],synthetics => [synthetics-*-*],metrics => [metrics-*-*],.watch-history-12 => [.watcher-history-12*],.watches => [.watches*],logs => [logs-*-*]); this template [jaeger-service] may be ignored in favor of a composable template at index creation time\""}
{"level":"debug","ts":1646729109.887256,"caller":"consumer/deadlock_detector.go:147","msg":"Global deadlock detector disabled"}
{"level":"info","ts":1646729109.8872933,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1646729109.887308,"caller":"consumer/consumer.go:79","msg":"Starting main loop"}
{"level":"info","ts":1646729109.9996207,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":0}
{"level":"info","ts":1646729109.9996367,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":0}
{"level":"debug","ts":1646729109.9998155,"caller":"consumer/deadlock_detector.go:98","msg":"Partition deadlock detector disabled"}

That's it, it just hangs, no more new ingester logs have appeared. I see the data has been correctly sent to kafka by collector. I hope this would help you understand the issue.

**Comment by cyf33** [comment]
Had the same problem!!
@micwiel Ingester can consume data from kafka when using snappy? I didn't try snappy but only lz4 and it couldn't work.

OS: Linux CentoOS7
Jaeger version: 1.33
Deployment: Docker
Kafka version: 2.7

**Comment by cyf33** [comment]
> > Had the same problem!! @micwiel Ingester can consume data from kafka when using snappy? I didn't try snappy but only lz4 and it couldn't work.
> 
> @cyf33 Yes, any other compression type except lz4 is working fine for me.

thx for the reply!

**Comment by jkowall** [comment]
Should be fixed in Jaeger v2 when we have moved to otel, feel free to re-open if not.
