### ISSUE TITLE
Proposal to join Cloud Native Computing Foundation

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#354]
Jaeger team has made a proposal to donate Jaeger to [Cloud Native Computing Foundation](http://cncf.io) whose member projects include Kubernetes, Prometheus, OpenTracing, etc.

  * [presentation slides](https://docs.google.com/presentation/d/1lDNdFxr58q-Fz4-yGXiei1iFxTDYq9LTQcJZ0x5BOec/edit?ts=5968dcd3#slide=id.g24b4bc2494_1_0)
  * formal proposal: https://github.com/cncf/toc/pull/42

Pinging people from our recent (and still open) [survey](https://github.com/uber/jaeger/issues/207): if you are currently using Jaeger and support its transition to CNCF, please comment on the [CNCF TOC proposal issue](https://github.com/cncf/toc/pull/42).

The comment can be just one sentence, e.g. _We are using Jaeger at {organization name} and we support Jaeger becoming a CNCF member project {because ...}._

@jkandasa @sunfaces @jbdalido @princeop @pavolloffay @mabn @jpkrohling @nlamirault @JodeZer @prestonprice57 @jrbury @objectiser @sloev @hwinkel @Madhu1512 @yuekui2 @valichek @dianvaltodorov @ZhouZiHe @LoungeFlyZ @jeluard @diegofernandes @d-ulyanov @jyothepro @yqf3139 @tomersimis @ruinanchen @szdavid92 @anuptalwalkar @hekike @sul4bh @Strandedpirate @julianste @awhiteside @nklmish @sweatybridge @kevinearls @felixbarny @hzariv @nlamirault @longXboy @drzero42 @xdralex @philipgian @bharat-p @pvlugter @Dieterbe @frankgreco

**Comment by felixbarny** [comment]
We are using Jaeger at stagemonitor and we support Jaeger becoming a CNCF
member project

Yuri Shkuro <notifications@github.com> schrieb am Fr., 25. Aug. 2017 18:16:

**Comment by yurishkuro** [comment]
@felixbarny do you mind adding the comment to the actual TOC proposal issue? https://github.com/cncf/toc/pull/42

**Comment by felixbarny** [comment]
Lol, sorry. Yes, I'll do.

Yuri Shkuro <notifications@github.com> schrieb am Fr., 25. Aug. 2017 18:41:

**Comment by frankgreco** [comment]
@yurishkuro great work!! added my commends to the CNF proposal.
