### ISSUE TITLE
Query not available

### ISSUE THREAD

**Issue by dino-ma** [jaegertracing/jaeger#3541]
At present, we report nearly 20 billion data every day, but at present, queries are almost unavailable. Each query takes 200 seconds or even longer. Our storage backend is es. Is there a solution for this situation?

**Comment by yurishkuro** [comment]
I suggest you look up some tuning guides for ES.

**Comment by dino-ma** [comment]
> I suggest you look up some tuning guides for ES.

Is there any other recommended back-end storage? For example, time series database or list database?

**Comment by dino-ma** [comment]
> The two main supported options are ES and Cassandra, there are other backends folks have added, but they aren't fully supported. You can also look into sampling to reduce your data set. If not, you can easily scale es much larger than 20b spans per day. As Yuri stated, you'll need tuning expertise for es which is a difficult problem to solve. This is actually why my company was founded. :)

After some consideration, we plan to migrate to CK to see if our problem can be solved. If so, we will provide a pr

**Comment by jkowall** [comment]
> > The two main supported options are ES and Cassandra, there are other backends folks have added, but they aren't fully supported. You can also look into sampling to reduce your data set. If not, you can easily scale es much larger than 20b spans per day. As Yuri stated, you'll need tuning expertise for es which is a difficult problem to solve. This is actually why my company was founded. :)
> 
> After some consideration, we plan to migrate to CK to see if our problem can be solved. If so, we will provide a pr

What is CK? ClickHouse?

**Comment by dino-ma** [comment]
> 

Yet ClickHouse.
At present, we also consider writing an ES proxy based on Jaeger ingester query to store massive data. At present, our daily trace data has exceeded 50tb

**Comment by jkowall** [comment]
I would look at sampling data in that case. ClickHouse will have scaling issues since it's a vertical scaling database, and handling that capacity will probably be a challenge with decent performance. 

Another way to solve your issue is sharding in OpenSearch, but this would be a lot of work and most likely require some changes in the way Jaeger manages indices. We have built this at logz.io for our internal systems to handle the scale, but we do not use index management which is OSS today, we have our ILM system. We are moving to adopt a hybrid of OpenSearch ISM and our own with a shard balancer that we have written that will likely end up being upstream contribution for OpenSearch.

**Comment by dino-ma** [comment]
> > 
> 
> Yet ClickHouse. At present, we also consider writing an ES proxy based on Jaeger ingester query to store massive data. At present, our daily trace data has exceeded 50tb

Hello, thank you for your reply. When will opensearch meet the standards for putting into production? At present, I intend to add an ES layer based on Jaeger's existing architecture Proxy is based on consistent hash to aggregate and fragment to solve my current problem. But I still hope to adjust to opensearch or other storage in the future, because the cost of ES is too high.

**Comment by jkowall** [comment]
We run OpenSearch in heavy production, as do loads of other people. Happy to offer advice around scaling it. There is a lot of work going on in the project to reduce the cost to operate, specifically supporting object storage and separating read from write nodes depending on your throughput requirements.
