### ISSUE TITLE
Favicon returns 500

### ISSUE THREAD

**Issue by forestsword** [jaegertracing/jaeger#3563]
**Describe the bug**

Looks like after the change https://github.com/jaegertracing/jaeger/pull/3399 the favicon can no longer be served. It's now an embedded gzipped file. All the versions since 1.28 return a 500, _seeker can't seek_ error.

It can be fixed by simply removing `favoriteIcon` from `StaticRootFiles` https://github.com/jaegertracing/jaeger/blob/e36f9fec8eb4a3b9a808aa76d248094fd7f657be/cmd/query/app/static_handler.go#L41

**To Reproduce**
1. Run the all-in-one after 1.28 (also affects query)
2. Open the UI in a browser

**Expected behavior**
Return the favicon with a 200 result.

**Screenshots**

![2022-03-04_13-35](https://user-images.githubusercontent.com/31450008/156764671-2994c4db-370e-4b86-9ae1-754e9984c911.png)

**Version (please complete the following information):**

All versions after 1.28

**Comment by yurishkuro** [comment]
cc @Ashmita152

**Comment by yurishkuro** [comment]
curiously enough, if I run all-in-one from source, favicon is returned normally, but when I run the docker command it returns 500.
