### ISSUE TITLE
Fix buffer size counting bug

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger#357]
This bug was fixed in [node client](https://github.com/uber/jaeger-client-node/pull/151) both the golang and java clients exhibit the same bug. The python client does its own random thing but we should make sure it's bug free.

- [ ] golang
- [ ] java
- [ ] python

**Comment by yurishkuro** [comment]
I don't think all clients have the same bug. It manifested in Node because the buffer size counter was used in the flush method. But we should double check.

**Comment by jkowall** [comment]
Clients are deprecated now, so this will not be fixed.
