### ISSUE TITLE
Collector container cannot find certificate nor key files

### ISSUE THREAD

**Issue by mgarnaudFTOS** [jaegertracing/jaeger#3588]
**Description**

When starting a Jaeger collector docker container using a Cassandra backend with TLS encryption, the connection fails because it cannot find the certificate file.
I've doubled and tripled check the presence and validity of the certificate file.

**Setup and Version**
 - Ubuntu VM 20.04, running Docker 20.10.13 running the latest collector image (jaegertracing/jaeger-collector)
 - The VM is set up in Azure in the same virtual network as is the Cassandra cluster.
 - The VM can ping every node of the cluster and the CQLSH tool can connect to the cluster.

**Expected behavior**
The collector is able to read certificate and key files to make a properly encrypted connection to the Cassandra cluster.

**Startup Command**
docker run --network="host" 
-e SPAN_STORAGE_TYPE=cassandra 
-e CASSANDRA_SERVERS="172.21.0.5,172.21.0.6,172.21.0.7" 
-e CASSANDRA_USERNAME=******** 
-e CASSANDRA_PASSWORD=******** 
-e CASSANDRA_TLS=true 
-e CASSANDRA_TLS_CA=/etc/ssl/certs/ca-certificates.crt 
-e CASSANDRA_TLS_SERVER_NAME="*.managedcassandra.cosmos.azure.com" 
-e CASSANDRA_TLS_CERT=/etc/ssl/certs/crt.pem
-e CASSANDRA_TLS_KEY=/etc/ssl/certs/key.pem
jaegertracing/jaeger-collector:latest

**Error Message**
"./main.go:80","msg":"Failed to init storage factory","error":"failed to load server TLS cert and key: open /etc/ssl/certs/cert.pem: no such file or directory","stacktrace":"main.main.func1\n\t./main.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.4.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\t./main.go:147\nruntime.main\n\truntime/proc.go:255"}

**What troubleshooting steps did you try?**
I was intrigued by the fact that the certificate or the key file cannot be found but there is no problem with certificate authority file so I tried using that same file as certificate and key file, in that I reach a different error since obviously the files don't have the expected content but I don't get the file not found error anymore.

**Comment by Ashmita152** [comment]
Hi @mgarnaudFTOS 

You probably missing mounting the ssl certificate and key directory from host to container. So even if those files are present on your host they won't be visible inside container. You will need to add  `-v /etc/ssl/certs:/etc/ssl/certs` flag which will mount the content of hosts's /etc/ssl/certs directory inside the container's /etc/ssl/certs.

**Comment by mgarnaudFTOS** [comment]
Hi @Ashmita152 

Thanks a lot for your answer, you were right, after adding the folder mapping the files are found. I am however faced with the next issue: "Failed to init storage factory","error":"failed to load server TLS cert and key: tls: failed to parse private key"
Is there a specific format that I should use ? Currently I'm using pem files.
