### ISSUE TITLE
remote agent when tracing service running in container on amazon ECS?

### ISSUE THREAD

**Issue by trtg** [jaegertracing/jaeger#359]
What is the recommended deployment approach for integrating the side-car agent process when you want to trace a service running in a container in ECS? It seems like all span emission code assumes that the agent is running locally, I see some references in the jaeger client code like LOCAL_AGENT_DEFAULT_ENABLED, but no example of using an agent that is not local. 

Should we rebuild our existing microservice containers (i.e. change their dockerfiles to pull in the agent binary and run it in the same container)? Is there a way to reach an agent that is not at 127.0.0.1? Or should we use host/container port mappings to have the service we want to trace reach the jaeger agent (which is in its own container) by jumping through the host EC2 instance?

**Comment by yurishkuro** [comment]
I assume you'd want to run the agent similar to datadog agent https://docs.datadoghq.com/integrations/ecs/

**Comment by yurishkuro** [comment]
Looks like amazon doesn't support an equivalent of kubernetes daemons. Another alternative is to configure Jaeger clients to use http post (Go and Java only right now) directly to collectors.

**Comment by trtg** [comment]
For anyone that ran into a similar issue, I wound up just rebuilding our ECS containers to start the jaeger-agent in the background and then our main process of interest and this has worked out fine.

**Comment by trtg** [comment]
@snigdhasambitak Basically write a script that starts jaeger-agent in the background before running the process you want to monitor and then call the script in your Dockerfile's ENTRYPOINT or CMD directive. So in a bash script called run_agent_and_process.sh:
./jaeger-agent &
./my_process

If you want all of that to behave nicely with signals you can trap SIGTERM and SIGINT in your script with a function that kills the PID of jaeger-agent and kills the PID of your code's process.

**Comment by jpkrohling** [comment]
@trtg would you be interested in writing a blog post about it? Bonus points if you can include the proper traps ;)

**Comment by trtg** [comment]
@jpkrohling sure, I can take a stab at it, will see if I have time this weekend. Been meaning to write up some stuff relating to aggregate queries about spans in Cassandra too, so might try to do that as well.

**Comment by ghfahimi** [comment]
@trtg have you end up writing a blog post on this topic? I'm also interested in this issue.

**Comment by ghfahimi** [comment]
@trtg Thanks for your response 👍

**Comment by zdicesare** [comment]
AWS also now supports daemon mode for ECS services, so you can deploy the agent as a daemon and ECS services can share their local agent

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html#service_scheduler

**Comment by jpkrohling** [comment]
Based on the last comments, I think this can be closed but feel free to reopen if this is still an issue.
