### ISSUE TITLE
gRPC health check - AWS ECS

### ISSUE THREAD

**Issue by HaroonSaid** [jaegertracing/jaeger#3593]
## Requirement - what kind of business use case are you trying to solve?

AWS ECS installation for jaeger collector 

## Problem - what in Jaeger blocks you from solving the requirement?

The AWS ECS gRPC requires a health check path on port 14250, there is no gRPC health check path. 
as a workaround, we can specify `/` and status code `0-99` 

As a consequence, the collector starts complaining - message logs 

```
{"level":"info","ts":1647699502.6893282,"caller":"grpclog/component.go:71","msg":"[transport]transport: loopyWriter.run returning. connection error: desc = \"transport is closing\"","system":"grpc","grpc_log":true}
--
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add a simple gRPC health check

**Comment by christmoore** [comment]
@HaroonSaid did this latest release solve your issue?

I'm hitting the same error - Jaeger collector in AWS ECS, ALB hitting 14250 and showing `healthy` for the collector.

Yet:
```
{"level":"info","ts":1647699502.6893282,"caller":"grpclog/component.go:71","msg":"[transport]transport: loopyWriter.run returning. connection error: desc = \"transport is closing\"","system":"grpc","grpc_log":true}
--
```

still appearing

**Comment by HaroonSaid** [comment]
@christmoore - yeah still seeing the same logs  - I guess my analysis was incorrect.

**Comment by christmoore** [comment]
Looks to originate from grpc dependency https://github.com/grpc/grpc-go#the-rpc-failed-with-error-code--unavailable-desc--transport-is-closing
