### ISSUE TITLE
Use prometheus as metrics backend in jaeger agent

### ISSUE THREAD

**Issue by wanghong** [jaegertracing/jaeger#360]
I am runing agent separately, I try to use prometheus as metrics backend. Like this:
**go run cmd/agent/main.go --metrics-backend prometheus**
But i got an error
**panic:  duplicate metrics collector registration attempted.**

Is there any extra configuration for prometheus? Or prometheus is not supported for now?

**Comment by yurishkuro** [comment]
yes, it's a known problem. Prometheus API expects pre-declaration of the labels, which is not how metrics API in jaeger-lib was designed. I believe it can be solved by caching Prom' metrics on first creation inside the factory and then only re-applying the tag values.

**Comment by sagikazarmark** [comment]
So is there a quick workaround that can be applied? Or just disable prometheus metrics from jaeger for now?

**Comment by yurishkuro** [comment]
There's no quick workaround. I was looking at the APIs today and it will require serious refactoring to be able to satisfy Prometheus's preregistration requirement. 

Btw those metrics are not on by default.

**Comment by jpkrohling** [comment]
Is this about metrics related to the agent, or about exposing metrics based on trace data?

**Comment by yurishkuro** [comment]
I understood it as using Prometheus for monitoring Jaeger components

**Comment by jpkrohling** [comment]
That's what I understood as well, just wanted to confirm
