### ISSUE TITLE
Spans are lost in benchmark test

### ISSUE THREAD

**Issue by buxingzhe** [jaegertracing/jaeger#361]
I do a benchmark test against our services(via Apache ab), and found many spans are lost. All my service hosts(AWS EC2 instances) are deployed in the same LAN. If I test manually, the all tracing spans are shown in UI. But when I use ab tool to test even with only one client(ab -c 1 -n 5 -t 60 -p post_data.xml -T "text/xml" <endpoint>), most of the tracing are half-baked, looks many spans are lost. In addition, I just deployed a jaeger agent running on a separate host, and all my traced services send spans to this same agent. I used the "const" sampler type and all spans should be sampled.
I took some actions but not take effect, here are the actions that I did(applied on all hosts):
1. Change the default reporter queue size from 100 to 100000
2. As network interface MTU is just 9001, so I changed the max packet size from 65000 to 8960.
3. I increased the system network core parameters to big values, includes receive buffer size, writer buffer size

Currently, I'm more confident that the client side should not drop spans, and I'm doubt the jaeger agent side may drop spans if the span are too much. Appreciate any help or suggestion from you guys.

**Comment by buxingzhe** [comment]
The issue has went away when I add the command options --processor.jaeger-compact.server-queue-size for agent and --collector.queue-size 100000 for collector separately.

**Comment by yurishkuro** [comment]
@buxingzhe do you have suggestions how we could have prevented you having to waste time on this investigation?  For example, you could've easily detected the agent dropping spans due to queue length based on the metrics.

**Comment by vprithvi** [comment]
I think having a document about operating Jaeger, and key metrics to monitor could be a good first step.

**Comment by buxingzhe** [comment]
@yurishkuro @vprithvi I think both metrics logging and document should be helpful. Actually I fixed the issue by reading the source code, and it indeed waste much time on it.

**Comment by yurishkuro** [comment]
let's keep it open as documentation request

**Comment by yurishkuro** [comment]
Issue for metrics documentation #611
