### ISSUE TITLE
Can  support two different project in two different machine share one root span?

### ISSUE THREAD

**Issue by jiamo** [jaegertracing/jaeger#362]
Here is the situation.  The request come, A project handle it and return, and A send a async  task to B project . I want trace the all the spans in A and B at the root span from A. So I can find how much the total performance to handle the request.

**Comment by objectiser** [comment]
From your description, it seems like you should be able to achieve this by creating the root (server) span in A, and then a client span in A for the communication with B (using a FOLLOWS_FROM reference type to the root span context), and then propagate the trace context to B, where a server span would be created.

**Comment by jiamo** [comment]
"or the communication with B " not understand deeply.

A just send a task to B. How it can  communication with B in code level?
You mean.  a client span  in A and  `FOLLOWS_FROM reference type` in B have some same information when they were added to its own content?  Because A can't just pass the span to B.

**Comment by objectiser** [comment]
Can you explain more about how the task is sent from A to B, that may help. Is it a REST call?

**Comment by jiamo** [comment]
Like aws sqs (send a pickle). B unpikle the object.

**Comment by objectiser** [comment]
Ok it might be worth you having a look at this example: https://github.com/hawkular/hawkular-apm/blob/master/examples/vertx-opentracing/order-manager/src/main/java/org/hawkular/apm/examples/vertx/opentracing/ordermanager/PlaceOrderHandler.java

The `handle` method shows the service receiving a place order request and creating a root span. It results in calls to check the customers account and stock level - but eventually the order is confirmed returning a response to the original call - but then asynchronously it sends an order confirmation via an event bus in the final `orderConfirmed` method - which uses a `FOLLOWS_FROM` reference type to reference back to the parent (root) span context.

**Comment by objectiser** [comment]
And this is one of the services that consumes the 'order confirmed' message from the event bus - so equivalent to your B: https://github.com/hawkular/hawkular-apm/blob/master/examples/vertx-opentracing/inventory-manager/src/main/java/org/hawkular/apm/examples/vertx/opentracing/inventorymanager/InventoryManagerVerticle.java#L110 - it extracts the trace context from the event bus message and then uses it to create the server span.

This is how the spans in service B would be associated with the spans in service A, based on the trace context transferred in header properties with the message published on the event bus (or SQS in your case).

**Comment by jiamo** [comment]
Thanks. I will take a look at it.

**Comment by yurishkuro** [comment]
Please re-open or join the chat https://gitter.im/jaegertracing/Lobby for questions.
