### ISSUE TITLE
Accept OpenTelemetry trace data via OTLP

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#3625]
This is the most important feature that came up in Jaeger v2 discussions, but it does not actually require v2, can be done standalone.

* [x] Add OTLP receiver to collector #3701
* [x] Update documentation https://github.com/jaegertracing/documentation/pull/578
* [ ] ~Add OTLP receiver to agent~ - let's wait for user demand
* [x] Support configuration of the receiver (ports) #3710

**Comment by joe-elliott** [comment]
Where do we see this going? otlp grpc endpoints on the agent make the most sense to me.

**Comment by yurishkuro** [comment]
I would mount it both in the agent and in the collector. Some deployments (e.g. serverless) do not support agents.

**Comment by ybasket** [comment]
Where would the user demand for OLTP on the agent be collected? I'd love to see this feature implemented.
