### ISSUE TITLE
License file does not specify copyright holder

### ISSUE THREAD

**Issue by lhorie** [jaegertracing/jaeger#3648]
**Describe the bug**
LICENSE file uses Apache 2.0 boilerplate and [does not specify copyright holder](https://github.com/jaegertracing/jaeger/blob/main/LICENSE#L189)

**To Reproduce**
1. Look at the [license](https://github.com/jaegertracing/jaeger/blob/main/LICENSE#L189) file  

**Expected behavior**
License file should specify copyright year and holder

**Comment by yurishkuro** [comment]
this is a standard Apache license file that is not meant to be changed.
