### ISSUE TITLE
Clean daily spans storage on demand from Jaeger UI

### ISSUE THREAD

**Issue by pasolid** [jaegertracing/jaeger#3722]
Would be nice if there was an option in Jaeger UI to request storage cleanup. 
We are using Elasticsearch as a spans storage, and we have deployed the `jaeger-es-index-cleaner` to remove old indexes but sometimes we do need a on demand cleaning. 

The proposal is to have basic functionality of selecting dates to clean from-to and execute it from UI main screen.

**Comment by yurishkuro** [comment]
Sorry, but doing manual maintenance for something that is already automated doesn't strike me like a good idea. If you need this functionality, you can add a link to Jaeger UI config and implement it yourself as a web service that invokes the index-cleaner.

**Comment by pasolid** [comment]
I don't think that having automated processes should prevent from having manual on-demand executions. Being able to execute processes manually should introduce a higher level of overall control. Having both automated and manual executions do not compete but complete each other.

The way I see both "approaches" (not only in the Jaeger system) is:
* Automated = launch-and-forget periodic tasks
* Manual = I still want to have a control w/o messing up with scheduled tasks  
The automated cleaning process can run daily with a retention policy of X last days to be preserved. Manual execution on the other hand can be used to remove ANY data, even the latest spans.

**Comment by yurishkuro** [comment]
We already have the tools/scripts that you can run manually. I just don't think it belongs in the UI. And if it was in the UI, it would likely require some access controls, you wouldn't want a casual user of your installation to just wipe out the data, it would only make sense for some admin role.

**Comment by ravishankarkumar** [comment]
Where can I get those tools/scripts that I can run manually to clean wipe the jaeger data?
