### ISSUE TITLE
Elasticsearch 8 Action/metadata line [1] contains an unknown parameter [_type]

### ISSUE THREAD

**Issue by Antiarchitect** [jaegertracing/jaeger#3725]
**Describe the bug**

**To Reproduce**
Setup Jaeger backed by Elasticsearch 8

**Expected behavior**
Jaeger Collector works normally

**Version (please complete the following information):**
 - OS: [e.g. Linux]
 - Jaeger version: 1.30.0
 - Deployment: Kubernetes. Helm chart version: 0.56.5

**What troubleshooting steps did you try?**
`es.version: "8"`

Jaeger Collector logs:

```
{"level":"info","ts":1654091043.7802398,"caller":"zapgrpc/zapgrpc.go:129","msg":"elastic: bulk processor \"\" failed but may retry: elastic: Error 400 (Bad Request): Action/metadata line [1] contains an unknown parameter [_type] [type=illegal_argument_exception]"}
```

**Comment by yurishkuro** [comment]
try setting es.version=7, Jaeger does not support v8

**Comment by Antiarchitect** [comment]
Does not help either :( Is there any roadmap on this?

**Comment by Antiarchitect** [comment]
I see. Thank you so much for the info :)
