### ISSUE TITLE
Baggage Whitelisting

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#373]
Distributed context propagation is a valuable feature in microservice-based architectures. It is also a potentially dangerous feature, because any key-value pair added to the context must be carried as part of business request payloads to every single microservice that participates in processing of a top-level request.

Imagine a simple workflow where a request to service X fans out 10 requests to downstream service Y. If service X stores 1Mb of data in the baggage, each request to service Y will automatically contain that extra payload, and we would have to transmit 10Mb of data on top of whatever business payloads are exchanged between X and Y. As we can see, baggage is a feature that can be easily abused, especially if developers choose a lazy path of passing data via baggage instead of developing proper APIs and service contracts. Baggage is not the place to pass request parameters.

Another reason to control access to baggage is its authenticity. Assume we build a mechanism where baggage is used to pass some security tokens or the tenancy of the request. It could be disastrous if some other service in the call graph decides to replace those baggage items with other values, even if it does it by accident due to a clash in the baggage keys.

This whitelisting feature is meant to address these issues and provide mechanism for controlling:
* Which keys are allowed in the baggage by your infrastructure,
* The maximum size of the values for those keys,
* Which services are allowed to set/override which keys.

Work items:
  * [x] Log baggage to span #179
  * [ ] Implement baggage restrictions in the clients
  * [ ] Add baggage http endpoint to agent
  * [ ] Configurable baggage restrictions in the collectors
  * [ ] Documentation

**Comment by pavolloffay** [comment]
@black-adder is there any progress on this issue?

**Comment by black-adder** [comment]
Thanks for the reminder, I'll update the ticket with progress.

**Comment by jpkrohling** [comment]
Is this still being done?

**Comment by yurishkuro** [comment]
We have the code internally, need to migrate to oss

**Comment by yurishkuro** [comment]
Not on the roadmap anymore, especially with switching to OTEL SDKs
