### ISSUE TITLE
make lint fails with many 'is in the blacklist'

### ISSUE THREAD

**Issue by esnible** [jaegertracing/jaeger#3741]
`make lint` fails with

```
cmd/flags/service.go:31:2: `github.com/jaegertracing/jaeger/pkg/metrics` is in the blacklist (depguard)
	pMetrics "github.com/jaegertracing/jaeger/pkg/metrics"
	^
```

... followed by many similar errors.

This has been happening on my Mac since https://github.com/jaegertracing/jaeger/pull/3736

(I don't see anything in that PR that would cause the problem.)

To reproduce, `make lint`.
It goes away if I do `git checkout 060ddb75da54b490f7b9926ca63a044e0e32745f` and then `make lint`

**Comment by yurishkuro** [comment]
did you try to refresh the linters with `make install-tools`?

**Comment by pavolloffay** [comment]
> I am uncertain if I did the make install-tools properly because doing that step generates 21 warnings similar to


One way to find out is to remove the linter and see if it will get installed.

**Comment by esnible** [comment]
Closing because I can no longer reproduce.  I am not sure if this is because of something I did, such as changing Go version, or something that changed in Jaeger.
