### ISSUE TITLE
Describe release process

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#375]
Currently, the repository is missing a readme file describing release process.

**Comment by yurishkuro** [comment]
The mechanics of the release are simple and easy to describe:
  1. Create a PR "Preparing release X.Y.Z" with an update to CHANGELOG.md, e.g. #351
  1. After the PR is merged, create a Release on GitHub with a tag `vX.Y.Z` (must have `v` prefix) and the description copied from the changelog, e.g. [v0.7.0](https://github.com/uber/jaeger/releases/tag/v0.7.0)
  1. The tag will trigger a build of the docker images
  1. Once the images are available on DockerHub, announce the release on the mailing list, gitter, and twitter

However, we don't have a formal process of deciding on the releases.

**Comment by pavolloffay** [comment]
A readme file with this would be good. Do we also plan to use other distribution channels? Like upload binaries to github releases? It might be useful for `all-in-one`. Users would just curl the binary and run it.
