### ISSUE TITLE
Kafka Message Size Error

### ISSUE THREAD

**Issue by HaroonSaid** [jaegertracing/jaeger#3752]
**Describe the bug**
 Jaeger Collector is complaining about Kafka Message Size 

**To Reproduce**
Not sure 

**Expected behavior**
no errors 

**Screenshots**
```

{"level":"error","ts":1654885190.5972621,"caller":"kafka/writer.go:61","msg":"kafka server: Message was too large, server rejected it to avoid allocation error.","stacktrace":"github.com/jaegertracing/jaeger/plugin/storage/kafka.NewSpanWriter.func2\n\tgithub.com/jaegertracing/jaeger/plugin/storage/kafka/writer.go:61"}
--
```

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.35
 - Deployment: AWS ECS

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**
Is this error related to a single message (span) written to kafka?

**Comment by xieyuschen** [comment]
Is it possible to provide a detailed code snippet or mock it to repeat this bug error?
@HaroonSaid 
Thanks.

**Comment by HaroonSaid** [comment]
I can describe the process that we have

* spans are generated by the app and sent to a otel sidecar collector sends the data to Jaeger collector 

* Jaeger collector writes to Kafka. 

We see the above error. 

It's unclear what code you are referring to as we don't write directly to Kafka.

**Comment by yurishkuro** [comment]
I don't believe Jaeger has any controls over message size. By default it sends each span as a message, or you can enable batching, which is limited by the number of spans, not their sizes.
