### ISSUE TITLE
gprc refused

### ISSUE THREAD

**Issue by destinygujun** [jaegertracing/jaeger#3756]
{"level":"info","ts":1655297307.2381737,"caller":"app/static_handler.go:182","msg":"UI config path not provided, config file will not be watched"}
{"level":"warn","ts":1655297307.2382605,"caller":"channelz/funcs.go:342","msg":"[core][Channel #2 SubChannel #3] grpc: addrConn.createTransport failed to connect to {\n  \"Addr\": \":16685\",\n  \"ServerName\": \"localhost:16685\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}. Err: connection error: desc = \"transport: Error while dialing dial tcp :16685: connect: connection refused\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1655297307.2382925,"caller":"app/server.go:209","msg":"Query server started","http_addr":"[::]:16686","grpc_addr":"[::]:16685"}
{"level":"info","ts":1655297307.2383075,"caller":"channelz/funcs.go:340","msg":"[core][Channel #2 SubChannel #3] Subchannel Connectivity change to TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1655297307.2383156,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1655297307.238326,"caller":"app/server.go:273","msg":"Starting HTTP server","port":16686,"addr":":16686"}
{"level":"info","ts":1655297307.2383618,"caller":"grpclog/component.go:71","msg":"[core]pickfirstBalancer: UpdateSubConnState: 0xc0003fb9e0, {TRANSIENT_FAILURE connection error: desc = \"transport: Error while dialing dial tcp :16685: connect: connection refused\"}","system":"grpc","grpc_log":true}
{"level":"info","ts":1655297307.2383828,"caller":"channelz/funcs.go:340","msg":"[core][Channel #2] Channel Connectivity change to TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
{"level":"info","ts":1655297307.2383325,"caller":"app/server.go:292","msg":"Starting GRPC server","port":16685,"addr":":16685"}
{"level":"info","ts":1655297307.238409,"caller":"channelz/funcs.go:340","msg":"[core][Server #1 ListenSocket #4] ListenSocket created","system":"grpc","grpc_log":true}
{"level":"info","ts":1655297308.2387505,"caller":"channelz/funcs.go:340","msg":"[core][Channel #2 SubChannel #3] Subchannel Connectivity change to IDLE","system":"grpc","grpc_log":true}
{"level":"info","ts":1655297308.2388508,"caller":"grpclog/component.go:71","msg":"[core]pickfirstBalancer: UpdateSubConnState: 0xc0003fb9e0, {IDLE connection error: desc = \"transport: Error while dialing dial tcp :16685: connect: connection refused\"}","system":"grpc","grpc_log":true}

**Comment by npathapa** [comment]
Any update on this issue? I'm facing the same.

**Comment by dailydismay** [comment]
+1, using 1.29.0 version of jaeger query

**Comment by dailydismay** [comment]
What version are u using?
