### ISSUE TITLE
Jaeger UI doesn't present all spans with "Operation = All" 

### ISSUE THREAD

**Issue by vitalykarasik** [jaegertracing/jaeger#3757]
**Describe the bug**
Jaeger UI doesn't present all spans with "Operation = All" 

**To Reproduce**
1.  Launch Jaeger stack using docker compose
2. Send a few spans
3.  Run "Find traces" for a particular service, with "Operation = All" 

**Expected behavior**
See *all* spans for this service

**Screenshots**
Attaching two screenshots: with "Operations = All" I'm getting 3 spans "GET /Test", but with "Operation = GET /Test" I'm getting 5

**Version (please complete the following information):**
 - OS: Ubuntu 22
 - Jaeger version: [e.g. 1.8]
 - Deployment: Docker Compose

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.
![Screen Shot 2022-06-15 at 16 39 14](https://user-images.githubusercontent.com/7628795/173841876-865aceb3-5263-41bc-aa24-c7ff430bd8e5.png)
![Screen Shot 2022-06-15 at 16 38 45](https://user-images.githubusercontent.com/7628795/173841906-8fb76695-c300-4495-943e-96ecb3015d79.png)

**Additional context**

**Comment by ClementRepo** [comment]
@vitalykarasik  Do you still remember what type of storage was used? (memory, Elasticsearch, Cassandra, etc)

**Comment by vitalykarasik** [comment]
> @vitalykarasik Do you still remember what type of storage was used? (memory, Elasticsearch, Cassandra, etc)

@ClementRepo  - it was some persistent storage.

**Comment by jkowall** [comment]
- Sort them both by most spans and see what it shows. You can re-open this, but the data is inconclusive, as Yuri mentioned.
