### ISSUE TITLE
How to handle AWS lambda and SQS with Jaeger?

### ISSUE THREAD

**Issue by Danny521** [jaegertracing/jaeger#3788]
If we have a big system which has many micro services deploying in kubernetes and some lambdas deploying in AWS. So is there any possible that we can use Jaeger to tracing our whole system?
Like tracing path: serviceA->serviceB->lambda->SNS->SQS->Lambda->DynamoDB.

Our needs is we want to track each payment request in our business flow. and we only care the failed request, like we want to know which step it failed in.

**Comment by pavolloffay** [comment]
As Jonah mentioned the ticket is not related to Jaeger therefore I am closing it. 

@Danny521 feel free to reopen is there is any action item from the Jaeger team.
