### ISSUE TITLE
SPM demo does not show the Monitor tab in the UI

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#3792]
**Describe the bug**
The SPM demo described in https://github.com/jaegertracing/jaeger/blob/main/docker-compose/monitor/README.md should be showing the Monitor tab in the UI (it is enabled in the UI config), but it does not.

cc @albertteoh

**Comment by albertteoh** [comment]
I tried it out just now, making sure that I delete the existing `jaegertracing/all-in-one` image in case a bug was introduced:

```
docker rmi -f jaegertracing/all-in-one
```

but I'm still able to see the Monitor tab.

<img width="599" alt="Screen Shot 2022-07-05 at 7 26 28 am" src="https://user-images.githubusercontent.com/26584478/177217908-9a3f52a9-d881-4db0-87d5-07f65085a766.png">
 
Is there any other step I can try to reproduce the issue?

**Comment by yurishkuro** [comment]
hm, yes, after deleting the image it seems to work. Not sure if my "latest" was very old, I usually run versioned images.  Perhaps we can improve the instructions in case people run into this issue.

BTW, another issue, but I think it's for the UI only - https://github.com/jaegertracing/jaeger-ui/issues/969
