### ISSUE TITLE
[Feature]: Metric is too little

### ISSUE THREAD

**Issue by THMAIL** [jaegertracing/jaeger#3857]

**Comment by yurishkuro** [comment]
what specifically are you missing / looking for?

**Comment by THMAIL** [comment]
> 
Thank you for your reply.
I want get some metrics such as the latency of send in Jaeger-agent , the latency of Jaeger-collecor , the count of spans that the agent received/rejected/dropped and the count of spans that the client created、send and not send.
But these metrics can't find in Jaeger. Is there any way to get these metrics?

**Comment by yurishkuro** [comment]
I don't know if we have latency, because it is not relevant. Agent sends no replies so there's no latency for it to report, and collector is not a latency sensitive service, it's about throughput. Other metrics like received/dropped are available from the /metrics endpoint on the admin port.

**Comment by yurishkuro** [comment]
please reopen if you have specific asks.
