### ISSUE TITLE
slow UI / hangs browser

### ISSUE THREAD

**Issue by Dieterbe** [jaegertracing/jaeger#386]
jaeger-ui frequently makes my browser just hang, even when only showing a search result of 20 traces
sometimes i can't even change the search criteria. the form doesn't respond to clicks or keypresses, the browser hangs, and after a minute or so, it says "this page is unresponsive. kill it or wait"

anyone else experiencing this?

**Comment by jpkrohling** [comment]
Is this happening only when you have tons of traces on the server?

**Comment by Dieterbe** [comment]
how do i tell? is there a cassandra query i should execute?

**Comment by black-adder** [comment]
There are some UI optimizations that we're working on, once those land these hanging issues should be reduced

@tiffon are those optimizations landed? Do we just need to bump jaeger-ui?

**Comment by tiffon** [comment]
@black-adder Yes, search optimizations [landed in early August](https://github.com/uber/jaeger-ui/pull/46).

**Comment by tiffon** [comment]
The updates that addressed this have been propagated to the docker images. 

@Dieterbe Can you confirm this is resolved?

Thanks for reporting this issue.

**Comment by Dieterbe** [comment]
Have not encountered this problem in quite a while now. Thanks Joe !
