### ISSUE TITLE
Add additional grpc.DialOptions in agent reporter connection builder

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#3864]
I'd like to pass in additional `grpc.dialoptions` as a means to add custom middleware to connections.

Today, one needs to re-implement `grpc.CollectorProxy` to do this because it only accepts ConnBuilder (which is a struct).

I'd like to add a new field `AdditionalDialOptions` to `ConnBuilder` which can take in dial options which would be applied during connection creation.

https://github.com/jaegertracing/jaeger/blob/919fb73bf68046e6a177140b861f636ba0c6579c/cmd/agent/app/reporter/grpc/collector_proxy.go#L39 

https://github.com/jaegertracing/jaeger/blob/919fb73bf68046e6a177140b861f636ba0c6579c/cmd/agent/app/reporter/grpc/builder.go#L40-L50

**Comment by yurishkuro** [comment]
+1
