### ISSUE TITLE
[Bug]: Reproducible UI builds

### ISSUE THREAD

**Issue by TripleDogDare** [jaegertracing/jaeger#3877]
### What happened?

UI builds are not reproducible.

There's at least two issues that I've discovered so far.
1. gzipped files are inserting file timestamps. This can be resolved in the Makefile fairly easily.
2. `asset-manifest.json` does not maintain a consistent sort order. I'll probably need to add something to `./scripts` to resolve this.

### Steps to reproduce

1. `make rebuild-ui`
2. `find ./cmd/query/app/ui/actual/ -type f -exec sha256sum {} \; | tee ui.gz.sha256sum`
3. `find ./cmd/query/app/ui/actual -type f -name '*.gz' -delete`
4. `make-rebuild-ui`
5. `sha256sum -c ui.gz.sha256sum`

### Expected behavior

sha256sum check should return OK

### Additional context

Other discussion at #3876

**Comment by yurishkuro** [comment]
I think this is solved, if not please list additional items required.
