### ISSUE TITLE
after use gevent patch all, jaeger cant get span

### ISSUE THREAD

**Issue by chenbodeng719** [jaegertracing/jaeger#3896]
@floatliang Thank you.
@yurishkuro Patching standard library with `gevent` makes multi-threaded code single-threaded. And it seems that `_consume_queue` fall into lock here https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/reporter.py#L161
I think it's better to report span always via `add_callback` https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/reporter.py#L132 
```
def report_span(self, span):
        self.io_loop.add_callback(self._report_span_from_ioloop, span)
```
I made this fix locally and it helps to avoid lock. I got spans in jaeger.

_Originally posted by @condorcet in https://github.com/jaegertracing/jaeger-client-python/issues/256#issuecomment-527991054_

I did the above things, but still no work

**Comment by yurishkuro** [comment]
Jaeger clients are no longer maintained, please use OpenTelemetry.
