### ISSUE TITLE
Consider moving away from CLA

### ISSUE THREAD

**Issue by caniszczyk** [jaegertracing/jaeger#392]
Since Jaeger is moving to the CNCF, CLAs are optional and you should consider moving away from one if that's what your community wishes.

cc: @yurishkuro

**Comment by yurishkuro** [comment]
I agree, once we migrate the repo to jaegertracing org it won't have a CLA

**Comment by caniszczyk** [comment]
@yurishkuro once the repo move happens, I'll enable DCO checks and all that jazz and disable the CLA checks

**Comment by yurishkuro** [comment]
https://github.com/uber/jaeger/commit/09fe054d098c5fa558b9bdf5dd10888703c16a25

**Comment by yurishkuro** [comment]
Issue to track the move #409

**Comment by yurishkuro** [comment]
Done
