### ISSUE TITLE
[Feature]: Support accepting OTLP via Kafka

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#3949]
### Requirement

As a user of OpenTelemetry Collector, I would like to send OTLP-encoded data to Jaeger.

### Problem

Jaeger ingester today only understands 3 formats, `json` (Jaeger Protobuf as JSON), `protobuf` (Jaeger Protobuf), and `zipkin-thrift`.

### Proposal

Add two more recognized encodings, `otlp-json` and `otlp-proto`.

It should be fairly simple to implement since we already import OTLP->Jaeger decoders when receiving OTLP via RPC.

**Comment by NonsoAmadi10** [comment]
Hello yurishkuro, Please can I be assigned to this. I want to try my hands on this issue

**Comment by NonsoAmadi10** [comment]
Hello Yurishkuro, can I be assigned to this please? I want this to be my first open source contribution

**Comment by NonsoAmadi10** [comment]
Also what guide can I follow as to how I can make my Pull Request?

**Comment by yurishkuro** [comment]
> Also what guide can I follow as to how I can make my Pull Request?

Are you asking in general how to do it on GitHub [[1]], or specifically in Jaeger project [[2]]?

> I would be requiring a marshal and an unmashaller for both encodings, Is this alright?

I think you only need to unmarshall https://github.com/jaegertracing/jaeger/blob/3d67ac86f53866332568b0f542265b00d86407fc/cmd/ingester/app/builder/builder.go#L35

But when introducing a new encoding you probably don't want it to be available as output encoding of the collector, only the input encoding in the ingester. We probably don't support such asymmetry cleanly at the moment. The simplest solution is to fail collector at startup if otlp is selected at output encoding. But if you can implement bidirectional marshalling, thenwe could go with full symmetric support (OTEL contrib does have translation of OTLP to and from Jaeger proto).

[1]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
[2]: https://github.com/jaegertracing/jaeger/blob/main/CONTRIBUTING.md

**Comment by NonsoAmadi10** [comment]
Wow, alright. I would keep this in mind while implementing. Thank you Yuri!! I'd be raising my first PR soon for you to look and give feedback

**Comment by yurishkuro** [comment]
@Vishal-Chdhry give it a try

**Comment by SaarthakMaini** [comment]
Hello,

Has this issue been resolved ?

If not , may I work on this issue?

Thank You!

**Comment by yurishkuro** [comment]
@SaarthakMaini there is a PR in progress, but the author did not come back to it since Dec.
If you want to pick it up, see https://github.com/jaegertracing/jaeger/pull/4049#discussion_r1055437763

**Comment by metapox** [comment]
Hello, Can I give this a try?

**Comment by yurishkuro** [comment]
afaik there are no specific blockers other than cleaning up the PR

**Comment by yurishkuro** [comment]
#4333 introduces batching API, but only within the Kafka consumer. I think it's a sufficient first step, and the overall Storage API batching could be done in the future if necessary/

**Comment by yurishkuro** [comment]
I am going to close this, it will be solved by jaeger-v2 using official OTEL Kafka receiver.
