### ISSUE TITLE
Collector metrics are not tagged

### ISSUE THREAD

**Issue by mabn** [jaegertracing/jaeger#395]
I've added influx reporter and I'll attempt to make some PR out of it, but there are no tags so it's not possible to e.g. use group by or to filter by service. The reason for this is the use of `metrics.Factory.Namespace` which just adds another section to the metric name. 

Can this be replaced with tags? Especially `countByServiceName` could report service name as a tag, and `hostMetrics` could have hostname as a tag.

**Comment by yurishkuro** [comment]
Yes, we should do that. Collector is the oldest component implemented back when we didn't use tag-based metrics system internally, so its instrumentation never got upgraded to tags, even though the metrics API was upgraded to support them.

Incidentally, it will break our internal dashboard :-( ... But still worth it.

**Comment by yurishkuro** [comment]
PS did you implement influx reporter directly or with go-kit https://github.com/go-kit/kit/tree/master/metrics/influx ?

**Comment by mabn** [comment]
I used go-kit support from jaeger-lib: https://github.com/uber/jaeger-lib/pull/23

**Comment by yurishkuro** [comment]
I think this is addressed by #776 and available in 1.5 release.
