### ISSUE TITLE
[Security]: Repo config best practice

### ISSUE THREAD

**Issue by jkowall** [jaegertracing/jaeger#3951]
### Requirement

This is to update our security score with best practices

I reviewed the yaml files for the github actions and we should be okay to make this settings change found here (I do not have permissions to do this):

<img width="239" alt="image" src="https://user-images.githubusercontent.com/1859948/194577961-c2533072-953c-4543-b63e-49f0ba41513d.png">

<img width="599" alt="image" src="https://user-images.githubusercontent.com/1859948/194578016-5f39a45a-0d4c-48d7-84cf-e3768d7efacc.png">

Should be set to read vs read-write. I would test the release after this, it depends on how the token is being passed into ci-release Github action

### Problem

Security fix

**Comment by yurishkuro** [comment]
changed, thanks
