### ISSUE TITLE
Clock skew between the host machines

### ISSUE THREAD

**Issue by Montana** [jaegertracing/jaeger#3954]
Hey all,

I'm working with something that has two main components for time-saving, we'll call them component A, and component B. 

Both components are configured to `export trace` information to my `jaegertracing/all-in-one:1.37` deployment.

The headers from component A are propagating correctly to component B, and I can see the traces being nested, but they are out of order.

I print the epoch time for both services are:

```javascript
JavaScript new Date().getTime()
```
Thank you so much!

**Comment by yurishkuro** [comment]
It would help if you could export the traces from the UI and attach here.
