### ISSUE TITLE
[Security]: Sign Releases

### ISSUE THREAD

**Issue by jkowall** [jaegertracing/jaeger#3960]
### Requirement

Please create a GPG key and store the private key in a secret. This will be used to modify the build shell script to create signed releases. 

http://ekaia.org/blog/2009/05/10/creating-new-gpgkey/ > To create the key

Please provide the name of the github secret for the private key.

### Problem

Need to create and store GPG key to allow for verification of the builds being from the Jaeger project

### Proposal

Modify the script here to add the signing process in https://github.com/jaegertracing/jaeger/blob/2e8c6b24492df7232b1f2814cfaa8cdf004c3ec4/scripts/package-deploy.sh#L36

per: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by yurishkuro** [comment]
I suggest someone first creates a PR that demonstrates this process working (using a personal private key set in the fork).

For instance, the article suggests using `gpg --armor --detach-sign`, which (a) picks the key from the local key ring, and (b) asks for a passphrase to decode it from the ring. It's not going to work in a shell script like that exactly.

Open question: we already have a key pair known to maintainers (used to encrypt/decrypt other project secrets), should we use that one or create a new dedicated key for release signing?

**Comment by yurishkuro** [comment]
cc @jaegertracing/jaeger-maintainers

**Comment by yurishkuro** [comment]
This looks like an example of dealing with gpg keys in a script: https://github.com/operator-framework/operator-sdk/pull/4034/files#diff-cf3a54e7ea95d0803bdc9605ebf170aa569cfef0fc83d1f1a78cde09215ce133
