### ISSUE TITLE
Tag all-in-one image

### ISSUE THREAD

**Issue by sagikazarmark** [jaegertracing/jaeger#399]
Currently the all-in-one docker image can only be used with the `latest` tag. I think it would make sense to tag releases as well so that one can use the closes version to the production environment when playing with Jaeger in a test environment.

For example I still deploy the agent together with my application and configure it to use the collector from the all-in-one image in a dev environment.

**Comment by yurishkuro** [comment]
iirc #376 is supposed to fix that, once we make the next release

cc @pavolloffay

**Comment by sagikazarmark** [comment]
Awesome, thanks!

No releases in the last 10 days, so probably it will magically be solved the next time you tag a release. (That being said, the last few tags could still be useful for the all-in-one image users)

**Comment by yurishkuro** [comment]
Released as 0.8.0

https://hub.docker.com/r/jaegertracing/all-in-one/tags/
