### ISSUE TITLE
Hi from Testcontainers for Go

### ISSUE THREAD

**Issue by mdelapenya** [jaegertracing/jaeger#4053]
Hi :wave: from Testcontainers OSS community!

The #405 issue came to our attention as it mentioned `testcontainers` as not existing in Go. It was Sep 2017, which was totally true at that time. But nowadays we have a Go flavor of the library, which you may want to explore: https://github.com/testcontainers/testcontainers-go.

We'd be more than happy to collaborate with you if needed 😃

_Originally posted by @mdelapenya in https://github.com/jaegertracing/jaeger/issues/405#issuecomment-1316831367_

**Comment by mdelapenya** [comment]
> Thanks for heads up. The issue #405 has already been resolved by using an additional docker-compose file for Jaeger components.

Yes, I saw that it was closed a year ago 😄 My interest is about collaborating in the case you were interested in exploring Testcontainers for Go, as it could integrate very smoothly in your tests.

Are you open to start a discussion on the topic?

**Comment by yurishkuro** [comment]
Enhancing or renovating our existing integration tests is a large time investment, we're not planning anything like that in the near future. I'd be interested to read some blog post that illustrates the value of testcontainers.

**Comment by mdelapenya** [comment]
Sure thing, in the meantime I collect good-reads, let me share this blog post, that was very recently published: https://www.atomicjar.com/2022/11/testcontainers-testing-with-real-dependencies/. The case study described in the blog post relates to a Java project, but you'll see the point from the perspective of a Go one.

Will come back here with more use cases
