### ISSUE TITLE
Encrypted Tag Values

### ISSUE THREAD

**Issue by frankgreco** [jaegertracing/jaeger#407]
> this is a feature request

#### current problem
There are a subset of organizations that require a very high level of security around their data. Spans are no exception. In these organizations (e.g. an insurance company), span data must be encrypted at rest. Note that it is not enough to encrypt to volume that backs the data. Now spans are lightweight and we don't want to encrypt spans that don't need to be.

For example, image we had a tag with a key of `http.response_body`. Also imagine that the value for this tag contained confidential information that would need to be encrypted. Note that only the value of the tag has to be encrypted. Jaeger provides no way to encrypt confidential tag values and then decrypt them.

#### proposed solution
It would be nice to have some way to specify which tag keys require an encrypted value. This would be a function of the Jaeger agent. When the agent receives a new span, it would encrypt the specified values before sending them to the specific storage component. Then, when the data is queried, it is decrypted before it is sent to the UI. 

#### final thoughts
This represents just one example of modification users of Jaeger may want to do with spans. It might be a good idea to implement a plugin architecture for request lifecycle hooks similar to how the [Kanali](https://github.com/northwesternmutual/kanali/blob/master/PLUGIN_GUIDE.md) project does it.

**Comment by yurishkuro** [comment]
I like the idea of plugins, and we certainly have more use cases for them. I don't know how widespread is the practice of using Go plugins, I've heard varying opinions.

As for encryption, it's sounds like a too-specific requirement for the core code, certainly makes more sense as a custom plugin. I would prefer to close this ticket and open another one about supporting plugins.

**Comment by yurishkuro** [comment]
Opened an issue  #422 for plugin support.
