### ISSUE TITLE
[Bug]: Frequent info log regarding GRPC error in Jaeger collector

### ISSUE THREAD

**Issue by sidharthabiswal** [jaegertracing/jaeger#4090]
### What happened?

The following info log pops up in every 5 seconds in Jaeger collector even without using Jaeger Agent

{"level":"info","ts":1670223513.6299033,"caller":"channelz/funcs.go:340","msg":"[core][Server #1] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x17\\\\x01\\\\x00\\\\x01\\\\x13\\\\x03\\\\x03\\\\x1bܦ\\\\x01CDC\\\\xef\\\\xae\\\\xfe5\\\\xa7h\\\"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1670223514.7639444,"caller":"channelz/funcs.go:340","msg":"[core][Server #1] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x17\\\\x01\\\\x00\\\\x01\\\\x13\\\\x03\\\\x03\\\\xd8ojXi:-\\\\x9e\\\\x96D\\\\x1a\\\\xe9D\\\"\"","system":"grpc","grpc_log":true}

### Steps to reproduce

Install Jaeger Collector
Check the logs of the main container

### Expected behavior

The frequent logs should not be printed.

### Jaeger backend version

1.38.1

**Comment by yurishkuro** [comment]
You should be able to control log verbosity with `--log-level`.

The log itself seems to be caused by some misbehaving client that hits the gRPC port with malformed requests.

I don't see how this is a bug.
