### ISSUE TITLE
[Bug]: The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'

### ISSUE THREAD

**Issue by mupjha** [jaegertracing/jaeger#4126]
### What happened?

The Anti-MIME-Sniffing header X-Content-Type-Options was not set to '**nosniff**'. This allows older versions of Internet Explorer and Chrome to perform MIME-sniffing on the response body, potentially causing the response body to be interpreted and displayed as a content type other than the declared content type. Current (early 2014) and legacy versions of Firefox will use the declared content type (if one is set), rather than performing MIME-sniffing.

### Steps to reproduce

Send a GET request to the Jaeger Collector/Query/Agent.
The response specifies Content-Type, Date & Content-Length only.

### Expected behavior

Ensure that the application/web server sets the Content-Type header appropriately, and that it sets the X-Content-Type-Options header to 'nosniff' for all web pages.

**Comment by Sucharitha95** [comment]
Hi,
This issue is not yet fixed in the latest version of Jaeger, Can someone please provide some update on this.

**Comment by yurishkuro** [comment]
why is this a problem? how exactly does it cause issues for Jaeger users?

**Comment by jkowall** [comment]
No reply for a year, closing out.
