### ISSUE TITLE
[Bug]: "jaeger_collector_spans_serviceNames" metrics names should be written in 'snake_case' not 'camelCase'

### ISSUE THREAD

**Issue by manisha5464** [jaegertracing/jaeger#4128]
### What happened?

As per the Prometheus best practices, "metric names should be written in 'snake_case' not 'camelCase'
There is a jaeger collector metric 'jaeger_collector_spans_serviceNames' which is following the camelCase in metric naming convention

So an improvement is expected from the Jaeger side to follow the snake_case naming convention for above metric

### Steps to reproduce

Collect the collector metrics 
Run the 'Promtool' which is a Prometheus command line tool that helps to lint service metrics and validate metric names, labels , meta data, and types based on Prometheus instrumentation best practices.

Below warning is displayed for the " jaeger_collector_spans_serviceNames" metric 

Metric names should be written in snake_case and not camelCase 

### Expected behavior

Metric name should follow snake_case naming pattern

So expected metric name is something like this
"jaeger_collector_spans_service_names" instead of "jaeger_collector_spans_serviceNames"

### Jaeger backend version

1.38.1

**Comment by yurishkuro** [comment]
This will be a breaking change to existing dashboards, with minimal benefit.
