### ISSUE TITLE
Data Pipeline and Path-Based Dependency Diagrams

### ISSUE THREAD

**Issue by NeoCN** [jaegertracing/jaeger#414]
Is there any time schedule for the features `Data Pipeline` and `Path-Based Dependency Diagrams`?

**Comment by yurishkuro** [comment]
Approximately Q4'17 and Q1'18, respectively.

**Comment by pavolloffay** [comment]
slightly off-topic but now we have a spak job which processes spans and creates dependency links: https://github.com/jaegertracing/spark-dependencies

**Comment by NeoCN** [comment]
Any update on this?

**Comment by NeoCN** [comment]
Is there any update on this issue ?

**Comment by pavolloffay** [comment]
I am closing this as the path-based dependency diagram has been removed from the roadmap https://github.com/jaegertracing/documentation/pull/337/files#diff-589f45af23c715bf85555e66e549daa0L41.

@yurishkuro can provide more details.

Regarding the data pipeline Jaeger already supports Kafka which can be used as a data source for analytics pipeline. There is also a new project https://github.com/jaegertracing/jaeger-analytics-java which provides data analytics components for Jaeger.
