### ISSUE TITLE
[Feature]: Support OTLP Authentication

### ISSUE THREAD

**Issue by rmarasigan** [jaegertracing/jaeger#4158]
### Requirement

As a Jaeger user, I think adding the functionality of **"auth"** under the **Jaeger Collector OTLP** would be nice to have.

So when the OpenTelemetry Collector tries to communicate with the Jaeger Collector OTLP endpoint it will require it to export the trace data with authentication. It can be optional tho.

Here are some sample **auth** that is nice to have:
* [basicauthextension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension)
* [oidcauthextension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oidcauthextension)

### Problem

When the OpenTelemetry Collector is exporting the traces to the Jaeger Collector, we wanted somehow the OTLP Endpoint to have an authentication so there will be limited access to the said endpoint and in a more secure way. But right now, it just directly exports our data to the Jaeger Endpoint without any authentication which might cause some security issues.

**Comment by psk001** [comment]
Hi @yurishkuro , is this issue still open, if yes may I proceed with further?

**Comment by yurishkuro** [comment]
Go ahead. My preference would be to not implement anything but check if OTEL Collector's receiver already supports auth. If it does not, I would not implement it in Jaeger either.

**Comment by psk001** [comment]
Cool , I'll move as suggested

**Comment by psk001** [comment]
As mentioned [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7167) , opentelemetry receiver supports http authentication using username and password. Also the discussion [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7165) and [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18065) have explanations.

**Comment by psk001** [comment]
What is the way forward for this @yurishkuro ?

**Comment by varshith257** [comment]
@yurishkuro OTEL Collector's receiver Implemented HTTP Basic server auth. I think we are ready to go. Can I work on this?

**Comment by yurishkuro** [comment]
Jaeger v2 uses OTLP receivers from OTEL collector, so we support the same features. We are not going to add new ones to jaeger v1.
