### ISSUE TITLE
Speed-up CI by using published UI artifacts

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4163]
### Requirement

As a developer, I want Jaeger CI to run faster when submitting PRs.

### Problem

The query-service and all-in-one binaries & docker images require rebuilding all UI assets, which takes quite a while, and these workflows run on every CI.

### Proposal

Since the jaeger-ui submodule is almost always pinned to a published UI release, we can build the UI artifacts once upon UI release (implemented in https://github.com/jaegertracing/jaeger-ui/commit/15017d5570a508e1ef9368618e2cd8f0abacd16a, available since https://github.com/jaegertracing/jaeger-ui/releases/tag/v1.27.4) and just download them as part of the backend CI. 

**Implementation**

Currently the `rebuild-ui` Makefile target performs a full UI build: https://github.com/jaegertracing/jaeger/blob/65ad4fccf8e451184878cce79bb615edc4c94f17/Makefile#L216-L217

Instead, we can try to do this first:
* `cd jaeger-ui`
* determine of the pinned commit has a published release tag, e.g. `v1.27.4`
* check if the corresponding UI release has the `assets.tar.gz` file uploaded (e.g. https://github.com/jaegertracing/jaeger-ui/releases/download/v1.27.4/assets.tar.gz)
* if yes, download the file and unzip it into `jaeger-ui/packages/jaeger-ui/build/`

If we can't find the assets archive in the release, or the pinned commit is not a release tag, then execute the current logic.

**Comment by shubbham1215** [comment]
@yurishkuro I can try working on this issue. Could you please assign it to me?

**Comment by yurishkuro** [comment]
Sounds good, assigned

**Comment by yurishkuro** [comment]
tbh, looking at the most recent runs the worst CI job is building docker images - https://github.com/jaegertracing/jaeger/issues/4172

**Comment by shubbham1215** [comment]
Started working on this, will be making a PR this week.

**Comment by yurishkuro** [comment]
This is not fully resolved. I noticed that even though the UI assets archive contains each file only once:
```
$ tar xvf assets.tar
x packages/jaeger-ui/build/
x packages/jaeger-ui/build/static/
x packages/jaeger-ui/build/static/index-legacy-7089c23a.js
x packages/jaeger-ui/build/static/jaeger-logo-ab11f618.svg
x packages/jaeger-ui/build/static/index-b9997246.js
x packages/jaeger-ui/build/static/index-3c2d679b.css
x packages/jaeger-ui/build/static/polyfills-legacy-9486af1f.js
x packages/jaeger-ui/build/static/monitor-9000dba4.png
x packages/jaeger-ui/build/index.html
```
but after cleaning `cmd/query/app/ui/actual/static` and running `build-ui` there are two sets of files:
```
$ l cmd/query/app/ui/actual/static
total 13576
-rw-r--r--  1 ysh  staff    58K Mar 15 11:36 index-3c2d679b.css.gz
-rw-r--r--  1 ysh  staff    55K Mar 15 11:36 index-b15a508e.css.gz
-rw-r--r--  1 ysh  staff   1.6M Mar 15 11:36 index-b9997246.js.gz
-rw-r--r--  1 ysh  staff   1.6M Mar 15 11:36 index-f51f30ea.js.gz
-rw-r--r--  1 ysh  staff   1.6M Mar 15 11:36 index-legacy-2d21d8d6.js.gz
-rw-r--r--  1 ysh  staff   1.6M Mar 15 11:36 index-legacy-7089c23a.js.gz
-rw-r--r--  1 ysh  staff    45K Mar 15 11:36 jaeger-logo-ab11f618.svg.gz
-rw-r--r--  1 ysh  staff   109K Mar 15 11:36 monitor-9000dba4.png.gz
-rw-r--r--  1 ysh  staff    13K Mar 15 11:36 polyfills-legacy-9486af1f.js.gz
-rw-r--r--  1 ysh  staff    13K Mar 15 11:36 polyfills-legacy-ea9e661d.js.gz
```

That's because they are duplicated under the UI build dir:
```
$ l jaeger-ui/packages/jaeger-ui/build/static
total 50152
-rw-r--r--  1 ysh  staff   377K Mar 15 05:36 index-3c2d679b.css
-rw-r--r--  1 ysh  staff   344K Mar  6 23:00 index-b15a508e.css
-rw-r--r--  1 ysh  staff   5.8M Mar 15 05:36 index-b9997246.js
-rw-r--r--  1 ysh  staff   5.7M Mar  6 23:00 index-f51f30ea.js
-rw-r--r--  1 ysh  staff   5.9M Mar  6 23:00 index-legacy-2d21d8d6.js
-rw-r--r--  1 ysh  staff   6.0M Mar 15 05:36 index-legacy-7089c23a.js
-rw-r--r--  1 ysh  staff   158K Mar 15 05:36 jaeger-logo-ab11f618.svg
-rw-r--r--  1 ysh  staff   109K Mar 15 05:36 monitor-9000dba4.png
-rw-r--r--  1 ysh  staff    34K Mar 15 05:36 polyfills-legacy-9486af1f.js
-rw-r--r--  1 ysh  staff    34K Mar  6 23:00 polyfills-legacy-ea9e661d.js
```

we need to clean the build dir before uncompressing the archive there

**Comment by yurishkuro** [comment]
Also, if the top commit of ui submodule has no tag, the build now fails, this needs to be fixed.

**Comment by shubbham1219** [comment]
I will rework on this issue on Saturday,18 March
