### ISSUE TITLE
Change "docket images" CI/CD task to build for fewer architectures

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4172]
### Requirement

As a developer I like CI/CD runs to take as little time as possible.

### Problem

"Build docker images" workflow takes 30min now, because it builds binaries and images for all possible architectues.

### Proposal

Consider reducing the number of architectures built for PRs, and only keep the full set for the main branch / release workflow.

Personally I would limit the PR builds to linux/amd86 architecture.

**Comment by shubbham1215** [comment]
Hi @yurishkuro, Could you give a brief about what changes would be a part of this ticket? I am looking to contribute to an issue for my academic requirement. I have already picked https://github.com/jaegertracing/jaeger/issues/4163 and will be working on it this week but the instructor has also mentioned picking something that would require a good amount of time to finish. Will this be a good issue? Or if there is some other issue you can assign me that as well.

**Comment by yurishkuro** [comment]
@shubbham1215 the change would be mostly refactoring shell scripts / Makefile to pass fewer arch params to the docker build process. Around a week of work, including ramp-up.

> good amount of time to finish

what amount of time do you want to allocate?

**Comment by shubbham1215** [comment]
Okay. I think this issue is fine as it would require me much more than a week to finish it. Could you assign me this as well? Thanks.

**Comment by Eileen-Yu** [comment]
Hi @yurishkuro Here is an initialized PR for this issue:
https://github.com/jaegertracing/jaeger/pull/4286

Since I'm pretty new here, would you help with review and let me know if anything you'd like to share?
