### ISSUE TITLE
[Feature]: spm

### ISSUE THREAD

**Issue by nsaikrishna15** [jaegertracing/jaeger#4194]
### Requirement

How to give prometheus credentials on jaeger query deployment.

### Problem

I want to read metrics from a prometheus url which has the authentication enabled. How to pass the username and password in the jaeger query. i tried setting up the env: PROMETHEUS_USERNAME and PROMETHEUS_PASSWORD but no use.

**Comment by rbaumgar** [comment]
I need to provide a bearer to get access on prometheus. Any hint?
Bearer is available at /var/run/secrets/kubernetes.io/serviceaccount/token

**Comment by albertteoh** [comment]
It's currently not supported, but I think we'd need to do something similar to [this example](https://github.com/prometheus/client_golang/blob/main/api/prometheus/v1/example_test.go#L138) when the an [HTTP RoundTripper is created for the MetricsReader](https://github.com/jaegertracing/jaeger/blob/7baadbd748294574451817197f83dc9bbd1a2e38/plugin/metrics/prometheus/metricsstore/reader.go#L248).

For bearer tokens, we could follow a similar pattern to [how our ES storage](https://github.com/jaegertracing/jaeger/blob/3c8ffd105d5b7930d35655872d577c64781a819f/pkg/es/config/config.go#L524) is configured with a bearer token.

**Comment by rbaumgar** [comment]
@albertteoh shall I create a separate feature request?

**Comment by albertteoh** [comment]
> @albertteoh shall I create a separate feature request?

Yes, I think that would be better. Thanks.

**Comment by nsaikrishna15** [comment]
So would it not possible for configuring the auth of remote prometheus server in jaeger UI/jaeger query for now ?
