### ISSUE TITLE
[Bug]: Possible memory leak?

### ISSUE THREAD

**Issue by ramonsmits** [jaegertracing/jaeger#4197]
### What happened?

I observed that my Synology NAS with 8GB results in too much memory to be allocated by Jaeger.

![image](https://user-images.githubusercontent.com/152998/215761176-a5f2c4cd-0aac-43d0-ab6d-c32a90566aa3.png)

Eventually, my NAS struggles a lot due to low memory. When I stop/start the jaeger container things return to normal.

### Steps to reproduce

1. Using the [default docker setup](https://www.jaegertracing.io/docs/1.41/getting-started/)
2. Have an application that emits traces every few minutes
3. See memory growth on my NAS over a period of 10 days

### Expected behavior

I expect that memory does not increase over time. Especially as a restart will not use much memory.

### Jaeger backend version

1.41 and 1.40

### Stogage backend

Docker default, not sure what backend that is

### Operating system

Linux / Synology

### Deployment model

Docker

### Deployment configs

```shell
https://www.jaegertracing.io/docs/1.41/getting-started/

Not using the version tag with the minor, only the major!

docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
  -e COLLECTOR_OTLP_ENABLED=true \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 4317:4317 \
  -p 4318:4318 \
  -p 14250:14250 \
  -p 14268:14268 \
  -p 14269:14269 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1
```
```

**Comment by yurishkuro** [comment]
Not a bug, it's expected behavior. All-in-one has an option to restrict the size of the memory buffer used to store traces.

**Comment by ramonsmits** [comment]
ok, my bad, I thought it used persistent storage and didn't spot "with an in memory storage component." in the getting started.

Recreated it using `-e SPAN_STORAGE_TYPE=badger`

However, its weird that by default is it storing unlimited amount of traces.

Maybe it could stand out a little better that in memory is the default and link to:

- https://www.jaegertracing.io/docs/1.41/deployment/#memory

**Comment by yurishkuro** [comment]
> Maybe it could stand out a little better that in memory is the default and link to:

Do you have a place in mind where this should happen?
