### ISSUE TITLE
[Feature]: spm bearer token required for prometheus

### ISSUE THREAD

**Issue by rbaumgar** [jaegertracing/jaeger#4219]
### Requirement

I am using a global prometheus for spm where I need to present a bearer token to get access.
In kubernetes the token is available at /var/run/secrets/kubernetes.io/serviceaccount/token
Currently no parameter is available to define the token neither as value nor as file.

### Problem

spm gets a 401 when connected to prometheus

### Proposal

create a parameter like prometheus.bearer-token

**Comment by nsaikrishna15** [comment]
****Looking forward for this..

**Comment by ChillOrb** [comment]
@yurishkuro I'd like to help with this. 

Following [this comment ](https://github.com/jaegertracing/jaeger/issues/4194#issuecomment-1420550049)

I am planning to modify [Configuration](https://github.com/jaegertracing/jaeger/blob/3c8ffd105d5b7930d35655872d577c64781a819f/pkg/prometheus/config/config.go#L24) with extra fields -
1. TokenFilePath         string
2. AllowTokenFromContext bool

and modify [this part of code
](https://github.com/jaegertracing/jaeger/blob/e751dbfede923c9e0e5d12d3df29b9e8b73e5abf/plugin/metrics/prometheus/metricsstore/reader.go#L267) with [similar implementation](https://github.com/jaegertracing/jaeger/blob/3c8ffd105d5b7930d35655872d577c64781a819f/pkg/es/config/config.go#L524)

I see that we are already creating configurable rountripper [here](https://github.com/jaegertracing/jaeger/blob/3c8ffd105d5b7930d35655872d577c64781a819f/plugin/metrics/prometheus/metricsstore/reader.go#L78) so looks like this covers all required changes.

Question: Do i need to add test cases as part of this issue ?

Please let me know what you think

**Comment by yurishkuro** [comment]
Yes, we have automatic check in the CI for test coverage.

**Comment by ChillOrb** [comment]
@yurishkuro 
I have made changes to add the required functionality as mentioned above and was working on the test cases..

- I have created test function for loadfile()[ function here ](https://github.com/ChillOrb/jaeger/blob/d96e0188e75ac5917ab3579df641a062c4228642/plugin/metrics/prometheus/metricsstore/reader_test.go#L461)

Is this approach correct where i create a dummy file with token and then defer its deletion?


- I was trying to also write test cases for 	

```
type Configuration struct {
	ServerURL             string
	ConnectTimeout        time.Duration
	TLS                   tlscfg.Options
	**TokenFilePath         string
	AllowTokenFromContext bool**
}
```

But since getHTTPRoundTripper() is dependent on loadfile function i feel stuck on how to approach this ..

Can you please let me know if going in the right direction?

**Comment by albertteoh** [comment]
> Is this approach correct where i create a dummy file with token and then defer its deletion?

That seems fine, but I would incorporate that as part of writing the test that actually validates the HTTP header contents much like in the existing `TestGetRoundTripper` (see below). That is, through just the setup of the test you'll be testing the reading of the token file anyway.

> Can you please let me know if going in the right direction?

Did you consider writing this `Configuration` test in [factory_test.go](https://github.com/jaegertracing/jaeger/blob/c733708c6f1f2a894cbd475cd7f5bf86d0afdd8b/plugin/metrics/prometheus/factory_test.go#L57)?

To test the actual effect of the new config attributes, I suggest looking into extending the existing [`TestGetRoundTripper`](https://github.com/jaegertracing/jaeger/blob/7baadbd748294574451817197f83dc9bbd1a2e38/plugin/metrics/prometheus/metricsstore/reader_test.go#L317) to include the `TokenFilePath` and `AllowTokenFromContext` as test case attributes, seeing that it already asserts on the Header contents.

**Comment by ChillOrb** [comment]
@albertteoh Thanks for the pointers,

Can you please review [PR 4239](https://github.com/jaegertracing/jaeger/pull/4239)?

Also, Currently I have not written test case similar to [factory_test.go](https://github.com/jaegertracing/jaeger/blob/c733708c6f1f2a894cbd475cd7f5bf86d0afdd8b/plugin/metrics/prometheus/factory_test.go#L57) as I am trying to understand how flags parsing works. If it's important for this issue please let me know i will close my PR.
In the meantime i am trying to understand how parsing works and hope to add test for Configuration asap

**Comment by albertteoh** [comment]
> Also, Currently I have not written test case similar to [factory_test.go](https://github.com/jaegertracing/jaeger/blob/c733708c6f1f2a894cbd475cd7f5bf86d0afdd8b/plugin/metrics/prometheus/factory_test.go#L57) as I am trying to understand how flag parsing works. If it's important for this issue please let me know i will close my PR and create a new one after adding both the tests.

Thanks for helping out with this, @ChillOrb! 😄 I've added some comments in, I think you're heading in the right direction.

IIUC, we'll still need to set: `TokenFilePath` and `AllowTokenFromContext` from input parameters. I think it's a good idea to separate this concern from its use in another PR as you propose 👍🏼 . As such, I don't think https://github.com/jaegertracing/jaeger/pull/4239 should resolve this issue quite yet until you've address the changes necessary in [factory_test.go](https://github.com/jaegertracing/jaeger/blob/c733708c6f1f2a894cbd475cd7f5bf86d0afdd8b/plugin/metrics/prometheus/factory_test.go#L57) and https://github.com/jaegertracing/jaeger/blob/52212b1a782e0793bce8e9253206e49813098c6a/plugin/metrics/prometheus/options.go#L72

Do you agree?

**Comment by ChillOrb** [comment]
@albertteoh Yes , thanks for clearing that out. I will close out #4239 and work on completing the pending tasks required for this issue's resolution.

**Comment by alok1929** [comment]
Hey, are there any issues I could work on?

**Comment by yurishkuro** [comment]
@alok1929 are you specifically asking about this issue? There are plenty of others: https://github.com/jaegertracing/jaeger/labels/help%20wanted
