### ISSUE TITLE
[Bug]: HotRod example fails documented kustomize build

### ISSUE THREAD

**Issue by bigfleet** [jaegertracing/jaeger#4230]
### What happened?

As a Jaeger newbie
I want to see how to run an example app on Kubernetes
So that I can see how traffic flows from an application to sidecar to jaeger collector with or without OpenTelemetry

### Steps to reproduce

1. Download this repos`main` branch
2. Access the hotrod example at `examples/hotrod`
3. Reference the "run on kubernetes section"
4. Run `kustomize build ./kubernetes | kubectl apply -f -`

### Expected behavior

I expected `kustomize build` to create YAML resources and for `kubectl apply` to apply them.

### Relevant log output

```shell
examples/hotrod/main > kustomize build ./kubernetes | kubectl apply -f -
Error: accumulating resources: accumulation err='accumulating resources from 'base/jaeger': evalsymlink failure on '/Users/jvanfleet/src/nano/jaeger/examples/hotrod/kubernetes/base/jaeger' : lstat /Users/jvanfleet/src/nano/jaeger/examples/hotrod/kubernetes/base/jaeger: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on '/Users/jvanfleet/src/nano/jaeger/examples/hotrod/kubernetes/base/jaeger' : lstat /Users/jvanfleet/src/nano/jaeger/examples/hotrod/kubernetes/base/jaeger: no such file or directory
error: no objects passed to apply
```

### Additional context

It does appear that the kustomization once targeted a `jaeger` directory, and now there is a `jaeger-all-in-one` -- that change to `kustomization.yaml` is not enough, though:

```
examples/hotrod/main ☣> kustomize build ./kubernetes | kubectl apply -f -
Error: accumulating resources: accumulation err='accumulating resources from 'base/jaeger-all-in-one': '/Users/jvanfleet/src/nano/jaeger/examples/hotrod/kubernetes/base/jaeger-all-in-one' must resolve to a file': recursed merging from path '/Users/jvanfleet/src/nano/jaeger/examples/hotrod/kubernetes/base/jaeger-all-in-one': may not add resource with an already registered id: Deployment.v1.apps/example-hotrod.[noNs]
```

I would help, but I am trying to learn myself!  I appreciate there's a lot of attention on docker, but hopefully there are some cycles for learning on the cluster.

### Jaeger backend version

v1.42

### SDK

Whatever hotrod is using, hopefully.

### Pipeline

I would like to ultimately monitor what the sidecar injection does without any other influence to determine if that's possible for my use case.

### Stogage backend

Memory

### Operating system

n/a

### Deployment model

Kuberntes

### Deployment configs

```shell
All contained in the repo
```

**Comment by bigfleet** [comment]
Changing the kustomization to `jaeger-all-in-one` and leaving hotrod commented out DOES work, however, so this could be a simple PR.  I can do it, if that makes sense.  (No idea about contributor agreements, etc.)

**Comment by highb** [comment]
@bigfleet I'll add this to my backlog or, if you want to open a PR to fix it, I can review.

**Comment by bigfleet** [comment]
@highb ready to review

**Comment by highb** [comment]
Thanks for reviewing it @yurishkuro ! It's been a busy week for me. 😮‍💨
