### ISSUE TITLE
[Bug]: Inconsistent `metricsstore` metric namespace between all-in-one and production query setup

### ISSUE THREAD

**Issue by zjanc** [jaegertracing/jaeger#4280]
### What happened?

Relevant metrics from `metricsstore` are being reported under the same namespace (`jaeger_query_*`) as `spanstore` when using the production setup.

`jaeger_query_requests_total{operation="get_latencies",result="ok"} 0`.

When deploying the `all-in-one` setup, these metrics are reported under `jaeger_*` e.g. 

`jaeger_requests_total{operation="get_latencies",result="ok"} 0`.

This issue was identified while experimenting with adding additional tags on query metrics.

### Steps to reproduce

1. Deploy a production Jaeger setup
2. Deploy an `all-in-one` Jaeger setup
3. Compare reported metrics

### Expected behavior

- No difference in metric names between different production setups
- Report `metricsstore` metrics under a different namespace

## `cmd/query/main.go`

`metricsFactory` is used for both `metricsQueryService` and `spanReader` initialization in `cmd/query/main.go`

https://github.com/jaegertracing/jaeger/blob/1d3bc1dc6334ce6b09546d9ddfadc5765820a5e2/cmd/query/main.go#L113

https://github.com/jaegertracing/jaeger/blob/1d3bc1dc6334ce6b09546d9ddfadc5765820a5e2/cmd/query/main.go#L119

`metricsFactory` is initialized with the namespace `jaeger_query`

https://github.com/jaegertracing/jaeger/blob/1d3bc1dc6334ce6b09546d9ddfadc5765820a5e2/cmd/query/main.go#L74-L75

---

## `cmd/all-in-one/main.go`

In `cmd/all-in-one/main.go`, `metricsFactory` is only used to initialize `metricsQueryService`.

https://github.com/jaegertracing/jaeger/blob/1d3bc1dc6334ce6b09546d9ddfadc5765820a5e2/cmd/all-in-one/main.go#L274

https://github.com/jaegertracing/jaeger/blob/1d3bc1dc6334ce6b09546d9ddfadc5765820a5e2/cmd/all-in-one/main.go#L125

`metricsFactory` is also initialized with the namespace `jaeger` instead of `jaeger_query`

https://github.com/jaegertracing/jaeger/blob/1d3bc1dc6334ce6b09546d9ddfadc5765820a5e2/cmd/all-in-one/main.go#L100-L102

**Comment by nikzayn** [comment]
Hey, @zjanc I would like to take this up. Just one thing, as you have mentioned the same namespace with metrics and metrics naming convention too. Can you tell me specifically what needs to be done?

**Comment by jkowall** [comment]
No reply from reporter, going to close this out as stale.
