### ISSUE TITLE
[Bug]: OTLP http v1/trace endpoint is not documented

### ISSUE THREAD

**Issue by kasium** [jaegertracing/jaeger#4324]
### What happened?

I wanted to use jaeger with native OTLP using opentelemetry-exporter-otlp-proto-http with a URL like "http://<url>:4318". However when I tried sending data, it failed with a 404.

I read thru the code of opentelemetry-exporter-otlp-proto-http and foudn that the endpoint needs to look like  "http://<url>:4318/v1/trace".
For that I could not find any documentation

### Steps to reproduce

n/a

### Expected behavior

There is documentation

### Relevant log output

```shell
n/a
```

### Screenshot

n/a

### Additional context

n/a

### Jaeger backend version

v1.42.0

### SDK

opentelemetry-exporter-otlp-proto-http 1.16.0

### Pipeline

n/a

### Stogage backend

all-in-one

### Operating system

Linux

### Deployment model

Docker

### Deployment configs

```shell
n/a
```

**Comment by yurishkuro** [comment]
URL must contain a host name before the port. 

Configuration of the SDK is not a Jaeger issue.
