### ISSUE TITLE
[test]: CI fails on current Go tip (upcoming 1.21)

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4327]
### What happened?

Unit tests fail on Go tip

### Steps to reproduce

`make test-ci` but on Go tip (e.g. `go1.21 test ./...`)

### Expected behavior

Tests should not fail.

### Relevant log output

https://github.com/jaegertracing/jaeger/actions/runs/4486863013/jobs/7889732133#step:7:1564

The difference seems to be in different types of Context argument
```diff
- context.todoCtx{emptyCtx:context.emptyCtx{}}
+ context.backgroundCtx{emptyCtx:context.emptyCtx{}}
```

<details>
<summary>Logs from run</summary>

```
--- FAIL: TestSpanProcessor_Process (0.00s)
panic: 

mock: Unexpected Method Call
-----------------------------

WriteSpan(context.todoCtx,*model.Span)
		0: context.todoCtx{emptyCtx:context.emptyCtx{}}
		1: &model.Span{TraceID:model.TraceID{Low:0x0, High:0x0}, SpanID:0x0, OperationName:"", References:[]model.SpanRef(nil), Flags:0x0, StartTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Duration:0, Tags:[]model.KeyValue(nil), Logs:[]model.Log(nil), Process:(*model.Process)(0xc00019c190), ProcessID:"", Warnings:[]string(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}

The closest call I have is: 

WriteSpan(context.backgroundCtx,*model.Span)
		0: context.backgroundCtx{emptyCtx:context.emptyCtx{}}
		1: &model.Span{TraceID:model.TraceID{Low:0x0, High:0x0}, SpanID:0x0, OperationName:"", References:[]model.SpanRef(nil), Flags:0x0, StartTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Duration:0, Tags:[]model.KeyValue(nil), Logs:[]model.Log(nil), Process:(*model.Process)(0xc00019c190), ProcessID:"", Warnings:[]string(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}


Diff: 0: FAIL:  (context.todoCtx=context.TODO) != (context.backgroundCtx=context.Background)
	1: PASS:  (*model.Span=trace_id:<) == (*model.Span=trace_id:<) [recovered]
	panic: 

mock: Unexpected Method Call
-----------------------------

WriteSpan(context.todoCtx,*model.Span)
		0: context.todoCtx{emptyCtx:context.emptyCtx{}}
		1: &model.Span{TraceID:model.TraceID{Low:0x0, High:0x0}, SpanID:0x0, OperationName:"", References:[]model.SpanRef(nil), Flags:0x0, StartTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Duration:0, Tags:[]model.KeyValue(nil), Logs:[]model.Log(nil), Process:(*model.Process)(0xc00019c190), ProcessID:"", Warnings:[]string(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}

The closest call I have is: 

WriteSpan(context.backgroundCtx,*model.Span)
		0: context.backgroundCtx{emptyCtx:context.emptyCtx{}}
		1: &model.Span{TraceID:model.TraceID{Low:0x0, High:0x0}, SpanID:0x0, OperationName:"", References:[]model.SpanRef(nil), Flags:0x0, StartTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Duration:0, Tags:[]model.KeyValue(nil), Logs:[]model.Log(nil), Process:(*model.Process)(0xc00019c190), ProcessID:"", Warnings:[]string(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}


Diff: 0: FAIL:  (context.todoCtx=context.TODO) != (context.backgroundCtx=context.Background)
	1: PASS:  (*model.Span=trace_id:<) == (*model.Span=trace_id:<)
```
</details>

**Comment by yurishkuro** [comment]
After #4332, the tests look good, but the linter fails

https://github.com/jaegertracing/jaeger/actions/runs/4496002967/jobs/7910236615#step:7:5421

**Comment by ChillOrb** [comment]
@yurishkuro How do i get that version ? I couldnt find go1.21 in [GO](https://github.com/golang/go)

**Comment by yurishkuro** [comment]
I was able to reproduce the error locally by installing tip (https://pkg.go.dev/golang.org/dl/gotip) and running linters with overridden GOROOT. But I didn't find the reason for failures. I think the linters / tools need to be installed with tip as well, I didn't have time to investigate.

**Comment by ChillOrb** [comment]
Now i was able to reproduce the error. 
As for the golangci-lint tool , cloned the source code and built it using gotip 

```
golangci-lint --version
golangci-lint has version (devel) built with devel go1.21-8c2900b Mon Mar 27 22:17:55 2023 +0000 from (unknown, mod sum: "") on (unknown)

```
but still see lint errors.. will try to debug more

**Comment by Bharath-Ganesh** [comment]
Can I take up this issue?

**Comment by ChillOrb** [comment]
@yurishkuro 
I forgot to update this,  but i think this can be fixed when we install linters from go tip 

Here is the output 
![Screenshot 2023-04-04 at 10 12 13 PM](https://user-images.githubusercontent.com/34675136/229986713-dec88a00-e88f-4a82-8066-d79c9a14d65c.png)

**Comment by yurishkuro** [comment]
@ChillOrb what exactly do you mean by "install linters from go tip"? The CI runs that are failing perform a `gotip` installation first as the default Go version, and then run `make install-tools` that install the linters using gotip compiler. Did you mean we have to pull the HEAD of the linters themselves?

**Comment by ChillOrb** [comment]
> @ChillOrb what exactly do you mean by "install linters from go tip"? The CI runs that are failing perform a `gotip` installation first as the default Go version, and then run `make install-tools` that install the linters using gotip compiler. Did you mean we have to pull the HEAD of the linters themselves?

@yurishkuro I looked into more..

I got no error even when i used the golangci-lint version 1.52.1 which is currently being used [here](https://github.com/jaegertracing/jaeger/blob/8204fa5898f8f1a373a5d
![Screenshot 2023-04-05 at 9 51 51 PM](https://user-images.githubusercontent.com/34675136/230274965-7cb42b53-4d73-41bb-a2d9-6edaf55284ce.png)
516286694bcec8074d5/Makefile#L397)

So , it did not error out for me using both "latest(1.52.2)" and version used currently in workflow (v.15.1)

Next, Can we try to rerun `ci-unit-tests-go-tip` once and see if we are getting the same error? If the error persists, i would then try to investigate this [step](https://github.com/ChillOrb/jaeger/blob/bb0e1152e113b7edcd63cebde5c00dceb34dd72d/.github/workflows/ci-unit-tests-go-tip.yml#L23)
