### ISSUE TITLE
[Feature]: Do we want to make policy to support N-1 Go version?

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4329]
### Requirement

OpenTelemetry Collector has a policy of being compatible with the last two versions of Go, as common in the Go community. 
Since Jaeger code is being imported in OTEL in some places, should we have a similar policy?

### Problem

Our recent Go 1.20 upgrade (#4202) broke them since we started depending on Go 1.20 features.

### Proposal

* We can upgrade our CI to use new versions of Go when they come out
* But our go.mod would stay on N-1 version to ensure compiler compatibility
* We should enforce that with a CI check

### Open questions

* If we do this now, what do we do with incompatible changes, roll them back? Or make the policy effective from the next Go version only?

**Comment by yurishkuro** [comment]
@jaegertracing/jaeger-maintainers can I get opinions?

**Comment by codeboten** [comment]
Can you confirm whether the policy will be in place following go 1.20? This means the collector dependencies on jaeger will at 1.41 until the collector bumps the version of go it supports.

**Comment by yurishkuro** [comment]
confirmed

**Comment by mx-psi** [comment]
Go 1.21 is out, we will be dropping support for Go 1.19 (see open-telemetry/opentelemetry-collector-contrib/issues/25116 for status on this) and the new Jaeger policy will allow us to keep updating Jaeger after this

**Comment by yurishkuro** [comment]
@mx-psi is there a stated policy in Collector about Go versions that we can borrow?

**Comment by yurishkuro** [comment]
Booked https://github.com/jaegertracing/jaeger/issues/4653 to track implementation of the policy

**Comment by yurishkuro** [comment]
@mx-psi @codeboten fyi #4724
