### ISSUE TITLE
Jaeger's Google Summer of Code 2023 projects

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4331]
Applications will be open from March-20 to April-4: https://summerofcode.withgoogle.com/

I've proposed two projects I can sponsor:
* https://github.com/jaegertracing/jaeger/issues/4196
* https://github.com/jaegertracing/jaeger-ui/issues/1288
* Other ideas are welcome too

All of CNCF projects: https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md#jaeger

**Comment by haanhvu** [comment]
@yurishkuro Hi, I have a question about the ClickHouse project.

You mentioned that we need something like OTel Collector ClickHouse exporter to deal with batch inserts. Is [ClickHouse Asynchronous Inserts](https://clickhouse.com/docs/en/optimize/asynchronous-inserts) also an option to consider?

**Comment by yurishkuro** [comment]
Possibly, this would be one of the things to investigate. I don't know the full details of these async inserts, but I always thought that CH being a database is in a better position to guarantee data resiliency by accepting inserts into some form of WAL and then applying them in batch internally. If that's what this feature does then great.

**Comment by haanhvu** [comment]
@yurishkuro Another question, for deployments with Kafka, if we use [ClickHouse Kafka Connect Sink](https://clickhouse.com/docs/en/integrations/kafka#clickhouse-kafka-connect-sink) then we don't need jaeger-ingester here?

**Comment by yurishkuro** [comment]
Possibly.

**Comment by haanhvu** [comment]
@yurishkuro I submitted my proposal on the GSoC website.

The window closes tomorrow so it may be late to ask for review... But if you have time for review, here's the link: https://docs.google.com/document/d/1Ks44CveC4SAGtzm8CFQzNUWYLZs4bGACPgJTnNcU0Ts/edit?usp=sharing

I shared it with your github email. Please let me know if you need it to be shared with other emails (you can find Ha Anh Vu on CNCF Slack), or you can find the submitted proposal under the name Ha Anh Vu on the GSoC website.

If you don't have time for review, it's ok. I stated in the proposal that it's not a final solution proposal and can change with our learning.

Thanks for your help during the GSoC application! Whether selected or not, I already learned a lot working on PRs with you. I'm going to finish #3924 in the upcoming days.

**Comment by yurishkuro** [comment]
@haanhvu 's proposal has been selected, closing this.
