### ISSUE TITLE
Istio supported

### ISSUE THREAD

**Issue by sunfaces** [jaegertracing/jaeger#435]
Hi all: 
   Istio is going to be the most popular service mesh, so is istio supported by jaeger now?

**Comment by yurishkuro** [comment]
istio uses zipkin format which is already supported. You can find references in one of the closed issues.

@objectiser wasn't there a blog about it?

**Comment by objectiser** [comment]
There isn't currently a blog post, although will do one once some other improvements are made within Istio.

However documentation for using Jaeger with Istio can be found here: https://istio.io/docs/tasks/telemetry/distributed-tracing.html

**Comment by objectiser** [comment]
Created #437 to add reference in docs.
