### ISSUE TITLE
Support YugabyteDB as a storage backend

### ISSUE THREAD

**Issue by diondew** [jaegertracing/jaeger#4354]
### Requirement

YugabyteDB has a large, loyal user community that has raised the desire for YugabyteDB to be an officially recognized storage backend for Jaeger. 

### Problem

Currently, YugabyteDB is not an officially supported storage backend for Jaeger.  

### Proposal

By giving official support to YugabyteDB, it will improve the quality of experience for users who want to use Jaeger as a tracing platform in conjunction with YBDB. Additionally, official support might also benefit Jaeger via current users of YBDB who are looking for supported tracing platforms.

**Comment by yurishkuro** [comment]
no interest from the community
