### ISSUE TITLE
agent receiving client batch problem

### ISSUE THREAD

**Issue by ray1888** [jaegertracing/jaeger#436]
i am just reading the code , i find it hard to find how the agent/app/thrift-gen/agent.go file by thrift gen code from jaeger-datamodel project , so it probably hand write by your teams? waiting for response

**Comment by ray1888** [comment]
the correct file path is jaeger/thrift-gen/agent/agent.go

**Comment by black-adder** [comment]
Checkout https://github.com/jaegertracing/jaeger/blob/master/Makefile#L181 it's the make command that generates the thrift files
