### ISSUE TITLE
Quickwit as a storage backend

### ISSUE THREAD

**Issue by evanxg852000** [jaegertracing/jaeger#4362]
[Quickwit](https://github.com/quickwit-oss/quickwit) is a sub-second search & analytics engine designed to work natively on cloud storage for distributed tracing, logs and other search use cases. Quickwit natively supports the [OpenTelemetry protocol](https://opentelemetry.io/docs/reference/specification/protocol/otlp/) to store traces and [Jaeger UI](https://www.jaegertracing.io/) by implementing the SpanReader interface of Jaeger's [Remote Storage API](https://www.jaegertracing.io/docs/1.43/apis/#remote-storage-api-stable). This allows users to store tracing data in Quickwit via OLTP; then query and visualize using Jaeger UI. We have a tutorial on how to use [Jaeger with Quickwit](https://quickwit.io/docs/distributed-tracing/plug-quickwit-to-jaeger)

As of Quickwit 5.0, only the SpanReader part is implemented therefore Quickwit can be used as a drop-in replacement to a span storage backend.  

Is it possible to add Quickwit to the list of additional storage backends in this [Meta issue](https://github.com/jaegertracing/jaeger/issues/638) ?

Disclaimer: I work on Quickwit

**Comment by evanxg852000** [comment]
I have updated this issue to give more details

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/jaeger/discussions/4363

**Comment by yurishkuro** [comment]
Added
