### ISSUE TITLE
[Feature]: In Collector, expose droppedSpanHandler as an option

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#4375]
### Requirement

As a Jaeger operator, I'd like to have customized handling when spans are dropped due to incoming queue being full on Jaeger Collector. 

### Problem

The `droppedItemHandler` is configured inside `newSpanProcessor`.

https://github.com/jaegertracing/jaeger/blob/fa9400712a8880f2be62805ce310e5b0ea8e3803/cmd/collector/app/span_processor.go#L90-L100

### Proposal

Use the existing `Options` struct to add a new `OnDroppedSpan`, use a type assertion internally to convert the `interface{}` to a `*model.Span`. 

```
type OnDroppedSpan func(span *model.Span)

func newSpanProcessor(...

	droppedItemHandler := func(item interface{}) {
		handlerMetrics.SpansDropped.Inc(1)
	}

	if options.onDroppedSpan != nil {
		droppedItemHandler = func(iSpan interface{}) {
			options.onDroppedSpan(iSpan.(*model.Span))
		}
	}
```

**Comment by eshwarhs** [comment]
Hi, I would like to take this up. Can you assign it to me @yurishkuro

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/jaeger/blob/main/CONTRIBUTING_GUIDELINES.md#assigning-issues
