### ISSUE TITLE
[Bug]: The es index is too large created by jaeger each index 200G+

### ISSUE THREAD

**Issue by yunduansing** [jaegertracing/jaeger#4376]
### What happened?

It will create an huge index everyday (200G+,we have 8 services)

### Steps to reproduce

once.Do(func() {
			exp, err := jaeger.New(jaeger.WithCollectorEndpoint(jaeger.WithEndpoint(url)))
			if err != nil {
				applog.Error("jaeger init fail:", err.Error())
				return
			}
			otel.SetTracerProvider(tracesdk.NewTracerProvider(
				// Always be sure to batch in production.
				tracesdk.WithBatcher(exp, tracesdk.WithBatchTimeout(time.Second)),
				// Record information about this application in an Resource.
				tracesdk.WithResource(resource.NewWithAttributes(
					semconv.SchemaURL,
					semconv.ServiceNameKey.String(name),
				)),
			))
		})

### Expected behavior

How to change it ?

**Comment by yurishkuro** [comment]
you can use ILM to control for the size of the index https://www.jaegertracing.io/docs/1.43/deployment/#elasticsearch-ilm-support
