### ISSUE TITLE
how agent receive(handle) thrift send from client

### ISSUE THREAD

**Issue by ray1888** [jaegertracing/jaeger#438]
i try to get the message that the hotrod example sent to the agent , but so far i the code i read , i can't find how the TbufferServer or ThriftProcessor to handle the message . and i find that jaeger-idl for agent , the function define in agent.thrift has not found in the TbufferServer or ThriftProcessor, but as my understanding Server end thrift need to have the same function in it to receive the data from client. In this case means TbufferServer or ThriftProcessor should suppose have this function ,but it isn't . So please somebody can tell my how agent handler message from client,  or is that for jaeger-idl agent.thrift is not for thrift from client to agent ?

**Comment by ray1888** [comment]
in my understanding , client  suppose to send span to agent by the function emitZipkinBatch() show in thrift  ,  so i try to write a python agent to receive it , code is below
```
import sys
import os
from socket import *

from thrift import Thrift
from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol
from thrift.server import TServer

sys.path.append(os.path.dirname(__file__)+"agent")
sys.path.append(os.path.dirname(__file__)+"zipkincore")
sys.path.append(os.path.dirname(__file__)+"jaeger")
from agent import Agent
from zipkincore.ttypes import Span

class Handler(object):
    def emitZipkinBatch(spans):
        print "in func"
        for item in spans:
            print item.trace_id
            print item.name

    def emitBatch(spans):
        print "in func"
        for item in spans:
            print item.trace_id
            print item.name



def tbuffserver():
    transport = TSocket.TServerSocket(port=5775, socket_family=SOCK_DGRAM)
    tfactory = TTransport.TBufferedTransportFactory()
    pfactory = TBinaryProtocol.TBinaryProtocolFactory()
    handler = Handler()
    processor = Agent.Processor(handler)
    server = TServer.TSimpleServer(processor, transport, tfactory, pfactory)
    print('Starting the server...')
    server.serve()
    print('done.')
if __name__ == "__main__":
    #creatsock() 
    tbuffserver()

``` 

but i can't receive to print anything ,so where is the problem , i am using hotrod as the testing front app

**Comment by ray1888** [comment]
i want to rewrite the agent part by python , how can i receive the span from the client, can somebody tell me to the solve the receiving problem , thx

**Comment by black-adder** [comment]
Hi, the hotrod demo doesn't emit zipkin batches by default anymore, it emits jaeger batches now. The python client defaults to writing zipkin format (which will be fixed to emit jaeger in the future). For now I recommend you checkout https://github.com/yurishkuro/opentracing-tutorial/tree/master/python and write a super simple python service with a tracer and use that to test your agent.

May I ask why you'd want to rewrite the agent in python?

**Comment by ray1888** [comment]
because my company request us to do sth like jaeger(my company tech stack is relay on python),so they want us to rewrite agent and collectors for convince to maintain the system

**Comment by yurishkuro** [comment]
That sounds like a rather peculiar reason. Are you planning to rewrite Cassandra or ES in Python too?  Jaeger backend is a binary, you just need to run it.

**Comment by ray1888** [comment]
cos we are making a monitor system , which database is based on opentsdb(which is based on hbase) , we want to reuse the database rather than to use a unfamiliar database, so that is most of the reason we determind to rewrite this two part(agent and collector)

**Comment by yurishkuro** [comment]
it seems it would be a lot less work to implement support for opentsdb in the official Jaeger backend.

Is your implementation open source?

**Comment by ray1888** [comment]
yes.so your advise is to support the opentsdb rather than rebuild the code of agent and collector?

**Comment by yurishkuro** [comment]
of course. It's a lot less work, you just need to implement SpanReader/Writer interfaces. Some other team is doing the same for DynamoDB.

**Comment by ray1888** [comment]
another question , if i change the database as opentsdb ,  but i don't know which folder in your project is connecting to database( because i just read agent and collectors part) , and is it possible to change the frontend interface of jaeger ? because the current interface is not suit for our service , we want to customized by ourself

**Comment by yurishkuro** [comment]
Storage APIs are defined in the `storage` top level package.

Currently it's possible to customize the main menu of the UI, and things like google analytics account. What other customization are you looking for?

**Comment by ray1888** [comment]
so what i need to do to change database is to change the bottom of jaeger to opentsdb and adapting the storage api you guys already provide

**Comment by yurishkuro** [comment]
you can find implementations of storage APIs for Cassandra and ElasticSearch (under plugins). Yours would be just another implementation. We also have a plan to support plugins so that you wouldn't even need to recompile the official backends in order to include a custom storage impl.

**Comment by ray1888** [comment]
okey, so can you guys give us some hint to do ? because i not really familiar with your data model . if getting your help , i think it is way more easier to do so, thx

**Comment by ray1888** [comment]
and one more question , what the relationship between jaeger/pkg/es and  jaeger/plugin/es ? is it means i also need to write the pkg part for opentsdb ?

**Comment by ray1888** [comment]
the data model that i refer to mean how to save span in backend-database , rather than jaeger-idl

**Comment by black-adder** [comment]
Any configs, interfaces you need go into the pkg directory. The implementation is in the plugin directory.

The data model for the span is: https://github.com/jaegertracing/jaeger/blob/master/model/span.go#L48 although you can convert some fields so that they better fit your database requirements as we've done here for elastic search: https://github.com/jaegertracing/jaeger/blob/master/model/json/model.go#L68

The schema for cassandra is defined here: https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/schema/v001.cql.tmpl

**Comment by ray1888** [comment]
thanks a lot ,  if meet any unsolve question , i will ask in gitter chat room of jaeger

**Comment by ray1888** [comment]
there is a question show , in jaeger/pkg/es/mocks/Client.go  in line32 rf, ok := ret.Get(0).(func(string) es.IndicesCreateService), what  is rf and ret.Get(0)? and in the jaeger/pkg/es/mocks/IndicesCreateService.go  
in line 50 rf, ok := ret.Get(0).(func(context.Context) *elastic.IndicesCreateResult); and in line 59 rf, ok := ret.Get(1).(func(context.Context) error); what is the rf in this two thing?

**Comment by yurishkuro** [comment]
questions are not issues
