### ISSUE TITLE
[Bug]: non-root spans with FollowsFrom reference incorrectly represent as trace in collector metrics

### ISSUE THREAD

**Issue by ChenX1993** [jaegertracing/jaeger#4380]
### What happened?

We noticed that non-root spans with **FollowsFrom** reference are showing as traces in collector metrics, e.g. `traces.received`, `traces.rejected` metrics.

The reason is that in collector metrics, `ParentSpanID()` is used to determine if a span is a root span, e.g. below
https://github.com/jaegertracing/jaeger/blob/3d67ac86f53866332568b0f542265b00d86407fc/cmd/collector/app/metrics.go#L233-L237

And the current implementation of `ParentSpanID()` only considers **ChildOf** relationship. So if a span has only **FollowsFrom** reference, the `ParentSpanID()` doesn't consider that and returns 0.
https://github.com/jaegertracing/jaeger/blob/506adaf2bf4f8364aa21d3f3001d1a6dcc6e2e97/model/span.go#L99-L109

Not sure any particular reason that **FollowsFrom**  is not considered in the current implementation of `ParentSpanID()`.

The proposal is to either 1) fix in collector metric to replace the `ParentSpanID()`, 2) fix in `ParentSpanID()`.
Prefer 2) because we use this method a lot to determine a span is a root span internally, but changing its behavior might break other places in jaeger OSS.

### Steps to reproduce

Create spans with **FollowsFrom** relationship, and check the collector trace metrics.

### Expected behavior

non-root spans with FollowsFrom reference should not show as trace in collector metrics.

**Comment by kubarydz** [comment]
Would chaning `ParentSpanID()` behaviour in 2) way also resolve this (rather old one) TODO?

https://github.com/jaegertracing/jaeger/blob/506adaf2bf4f8364aa21d3f3001d1a6dcc6e2e97/model/adjuster/clockskew.go#L117-L126

**Comment by ChenX1993** [comment]
I think so.
