### ISSUE TITLE
FindTraces takes too much time

### ISSUE THREAD

**Issue by wjh0914** [jaegertracing/jaeger#4402]
### What happened?

we use jaeger api FindTraces to search traces from opensearch .Searching 1000 traces took 26 seconds. is there any way to improve the performace of FindTraces ?

### Steps to reproduce

1、deploy  jaeger , uesing opensearch as backend storage. other cofiguration is default
2、searching traces from jaeger ui . 1000 traces will take more than 20 seconds

### Expected behavior

Expecting the time cost is millisecends-level.

**Comment by jkowall** [comment]
I am sorry this was not addressed for a year+ :( 

This depends on your OpenSearch setup, that doesn't sound normal, but you haven't specified any of your setup nor the number of spans returned for 1000 traces. If each of them have 10k spans then I would expect that pulling 10m spans would be slow. Please re-open the issue with more details.
