### ISSUE TITLE
glide install not working

### ISSUE THREAD

**Issue by happyyi008** [jaegertracing/jaeger#444]
I followed the steps the get started and got an error running `glide install`:
```
[WARN]	stat /home/workspace/jaeger/src: no such file or directory
[ERROR]	Could not find any of /home/workspace/jaeger/src.
[INFO]	As of Glide 0.5/Go 1.5, this is required.
[ERROR]	Without src, cannot continue.
```

**Comment by yurishkuro** [comment]
what's the version of glide you have installed?

```
$ glide -v
```

**Comment by happyyi008** [comment]
glide version v0.12.3

**Comment by yurishkuro** [comment]
is your GOPATH setup correctly?  The jaeger repository is supposed to be located at `$GOPATH/src/github.com/uber/jaeger`

**Comment by happyyi008** [comment]
Ah, I see. It's working now. Thank you.

**Comment by yurishkuro** [comment]
I clarified it in CONTRIBUTING.md (https://github.com/jaegertracing/jaeger/commit/3419f80b2bd76a41336eaecd3f43b692debf2d24)
