### ISSUE TITLE
[Bug]: Flaky Test: TestSpanProcessorWithOnDroppedSpanOption

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#4450]
### What happened?

PR (note changes are unrelated to the test failure): https://github.com/jaegertracing/jaeger/pull/4446

**Test failure link**

https://github.com/jaegertracing/jaeger/actions/runs/4919763496/jobs/8787773908?pr=4446#step:7:590

Retrying the test job resulted in all tests passing.

### Steps to reproduce

Could not reproduce.

Failing test was introduced from this PR: https://github.com/jaegertracing/jaeger/pull/4387

### Expected behavior

Tests to pass.

### Relevant log output

```shell
=== RUN   TestSpanProcessorWithOnDroppedSpanOption
    span_processor_test.go:682: 
        	Error Trace:	/home/runner/work/jaeger/jaeger/cmd/collector/app/span_processor_test.go:682
        	Error:      	Not equal: 
        	            	expected: []string{"op2", "op3"}
        	            	actual  : []string{"op3"}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,2 @@
        	            	-([]string) (len=2) {
        	            	- (string) (len=3) "op2",
        	            	+([]string) (len=1) {
        	            	  (string) (len=3) "op3"
        	Test:       	TestSpanProcessorWithOnDroppedSpanOption
--- FAIL: TestSpanProcessorWithOnDroppedSpanOption (0.00s)
FAIL
	github.com/jaegertracing/jaeger/cmd/collector/app	coverage: 98.5% of statements
```

**Comment by ChenX1993** [comment]
I think it is a concurrent problem.
I was trying to use the blocking writer to make a span drop situation, but the second test span is not 100% guaranteed to be dropped. 
https://github.com/jaegertracing/jaeger/blob/5c3c20dcd309afca924174bece0ad16671105279/cmd/collector/app/span_processor_test.go#L657-L683


Below is the code for consume portion of the `bouned_queue` used in collector processor.
If the second test span is enqueued just at the time between L83 and L84 in the go routine for processing the first span, then second span can be enqueued successfully which causes the test failure as the test expect the second span to be dropped.

https://github.com/jaegertracing/jaeger/blob/5c3c20dcd309afca924174bece0ad16671105279/pkg/queue/bounded_queue.go#L67-L97


I will think about how to write the test.
