### ISSUE TITLE
Jaeger's LFX Mentorship Jun-Aug-2023 Projects

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4453]
Jaeger project is sponsoring two projects in this round: https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/02-Jun-Aug#jaeger

* https://github.com/jaegertracing/jaeger/issues/3381 ([application link](https://mentorship.lfx.linuxfoundation.org/project/b8009398-1252-4f63-82fe-363846ccc11d))
* https://github.com/jaegertracing/jaeger-ui/issues/1288 ([application link](https://mentorship.lfx.linuxfoundation.org/project/0fc6c44b-5ddf-467f-8016-72cc35b4e3ff))

Applications for mentees are currently open, due by Tue May 23, 5:00 PM PDT. Please see https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/README.md#program-guidelines

We recommend mentees to prepare an execution proposal for the chosen project, similar to Google's Summer of Code program (see https://google.github.io/gsocguides/student/writing-a-proposal and https://community.apache.org/gsoc/). Include the proposal in the cover letter you will upload to LFX website (see application links above).

**Comment by haanhvu** [comment]
This may not relate. But the Apache's proposal template may be a good resource too: https://community.apache.org/gsoc/

I actually followed this template to write the proposal for Jaeger. Personally I find this template require more comprehensive and deeper study of the project than Google's template.

**Comment by haanhvu** [comment]
Also, I think we should note that the proposal templates are only there to guide. Applicants may not have to provide all the information of the proposal template. But they should at least show an overview of how they understand and would tackle the project.

LFX application is shorter than GSoC's. So it may not be reasonable to expect a detailed proposal like GSoC.

**Comment by arkhamHack** [comment]
Hi I am planning to contribute to this project for lfx. Where do I submit the proposal? Should I submit it as a part of the cover letter?

**Comment by yurishkuro** [comment]
@arkhamHack yes

**Comment by arkhamHack** [comment]
Hi, @yurishkuro so I've added the proposal, could I get your brief opinion before I submit for final evaluations?
Here's the drive link: 
https://docs.google.com/document/d/1JHFGxZ6OscJTqXd4e7TKiu0okfJUWJUP/edit?usp=sharing&ouid=109014663822197939718&rtpof=true&sd=true

**Comment by anikdhabal** [comment]
@yurishkuro I had prepared my proposal.

**Comment by PratikDevlekar** [comment]
Hey @yurishkuro, I would like to inform you that I have included a link to the proposal in the cover letter after answering few of questionnaire, I kindly request you to take a moment to review the proposal at your convenience. Your valuable insights and feedback regarding the proposal would be greatly appreciated.

Please feel free to reach out to me if you have any further inquiries or require any additional information :)

**Comment by yurishkuro** [comment]
The applications are closed. Congratulations to selected mentees!

* Afzal Ansari @afzal442
* GLVS Kiriti @GLVSKiriti
