### ISSUE TITLE
Jaeger's LFX Mentorship Sep-Nov-2023 Projects

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4457]
Applications are now closed. Candidates selected for mentorship program are listed below.

For details about LFX mentorship & the application process, see https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship. For deadlines, see https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/03-Sep-Nov.

Direct link to applying: https://mentorship.lfx.linuxfoundation.org/participate/mentee

## Projects

The following 3 projects have been officially proposed:
  * [Upgrade Jaeger UI to the latest version of React.js](https://github.com/jaegertracing/jaeger-ui/issues/998)
    * Mentee: @anshgoyalevil
  * [Combine three distinct graph views in Jaeger UI into one](https://github.com/jaegertracing/jaeger-ui/issues/1466)
    * Mentee: @prathamesh-mutkure
  * [Build official support in Jaeger for Elasticsearch 8](https://github.com/jaegertracing/jaeger/issues/4600)
    * Mentee: @pmuls99

## Proposal
Since we had a high number of applicants in the last round, we **strongly recommend submitting a proposal** as part of your application. It helps us select mentees who are the best match for the project. The proposal should cover the following:
  * Why are you interested in the project?
  * What kind of relevant experience or skills do you have?
  * [optional] What kind of open source experience you have? Please include your github ID and describe your notable contributions to OSS.
  * How do you propose to approach the project (roadmap, milestones, schedule)?
  * What are your time commitments?
  * Are you planning to remain involved with the project after the mentorship term?

It does not mean that the longer the proposal the better. It's about the quality and demonstrating which candidate better understands the problem and has a handle on how to solve it.

LFX website does not allow uploading additional documents, so it's recommended to include the proposal in the Cover Letter. It could also be a link to a document elsewhere (make sure it has appropriate read permissions, e.g. if Google doc).

## Getting Started
While the timelines in LFX programs are not very long, we recommend trying to get your hand dirty with small contributions to the project before applying: https://www.jaegertracing.io/get-involved/ and https://www.jaegertracing.io/mentorship-for-mentees/.

Reach out on [Slack](https://www.jaegertracing.io/get-in-touch/#via-chat) with other questions.

**Comment by yurishkuro** [comment]
Possible project (please vote if interested)
  * Upgrade Jaeger UI to the latest React (and other dependencies)

**Comment by yurishkuro** [comment]
Possible project (please vote if interested):
* Combine three distinct graph views in Jaeger UI into one (https://github.com/jaegertracing/jaeger-ui/issues/1466)

**Comment by yurishkuro** [comment]
Possible project (please vote if interested):
* Build official support for Elasticsearch 8 as Jaeger backend
  * Tracking issue #3571
  * Possible path: investigate if we could use https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter directly

**Comment by yurishkuro** [comment]
Possible project (please vote if interested to take on):
* https://github.com/jaegertracing/jaeger/issues/4591

**Comment by yurishkuro** [comment]
Possible project (please vote if interested to take on):
  * https://github.com/jaegertracing/jaeger-ui/issues/1597

**Comment by sambhavgupta0705** [comment]
Hi @yurishkuro ,hope you are doing great!!
I am Sambhav Gupta an undergraduate from India ,currently contributing to AsyncAPI specification as a mentee and also learning skills to get started with cloud native ecosystem.
I would like to contribute to this project under LFX Mentorship Fall Term 2023.

**Comment by yurishkuro** [comment]
Reach out on [Slack](https://www.jaegertracing.io/get-in-touch/#via-chat) if any questions.

**Comment by yurishkuro** [comment]
For anyone watching this issue, we narrowed down the list to three projects. The main description updated.

**Comment by AdityaRaimec22** [comment]
@yurishkuro can I still apply for https://github.com/jaegertracing/jaeger-ui/issues/998 this project

**Comment by yurishkuro** [comment]
@AdityaRaimec22 applications are open till Tue Aug-15, 5:00 PM PDT

**Comment by AdityaRaimec22** [comment]
@yurishkuro I applied for that I mean to ask can I still submit the proposal I want to confirm whether the last date to submit the proposal was 27th july or not. Thanks

**Comment by yurishkuro** [comment]
The proposal should be submitted with the application, by Aug 15
