### ISSUE TITLE
[Feature]: Support CORS headers on OTEL HTTP endpoint

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4459]
### Requirement

Allow exporting traces from browser directly to Jaeger. 

### Problem

Access from the browser usually requires addressing the CORS issue.

https://stackoverflow.com/questions/76266837/open-telemetry-cors-issue-exporting-trace-data-to-jaeger

### Proposal

Support CORS headers similar to how they are supported on Zipkin endpoint (see  #2056). If OTLP HTTP Receiver already supports these, we need to allow configuring them.

**Comment by yurishkuro** [comment]
If you don't know outright how to implement it, you can help by doing research:
  * does OTLP receiver support this? If so, how/where it can be configured.

**Comment by samyakjain10** [comment]
Hi @sid-008, was just wondering if you are still working on this issue

**Comment by sid-008** [comment]
No I am not, I don't really know how to outright implement it, you can take a shot at it

**Comment by shubmjagtap** [comment]
Hi @yurishkuro  can i work on this ? @sbdtu5498 opened PR but its been 14 days . So can i work on this ?

**Comment by shubmjagtap** [comment]
yes thanks

**Comment by sbdtu5498** [comment]
@yurishkuro didn't get time to catch up on the work again. I have closed the pr for the time being.
