### ISSUE TITLE
[Feature]: Allow sidecar agent to also ingest via otlp

### ISSUE THREAD

**Issue by DevSlashRichie** [jaegertracing/jaeger#4495]
### Requirement

As a Jaeger operator using k8s, I want to use sidecar agent to also ingest via otlp ports (4317 and 4318)

### Problem

When I am injecting sidecar and it creates the container across with my deployment, it won't expose the ports said. Right now it is exporting other ports such as thrift one but not the otlp even with the option enabled.

### Open questions

 - should this ports be only enabled when otlp is also enabled?

**Comment by yurishkuro** [comment]
We do not plan to support that. `jaeger-agent` is becoming redundant as you can use OTEL Collector in its place.
