### ISSUE TITLE
Span kind for Zipkin shared spans

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#451]
Zipkin span can contain both server and client annotations. For this span we should consider adding server and client span kind. 

This fix could help to determine dependency link between services. The current implementation has to use logs in addition to tags.

The current implementation adds only one span kind tag. The decision is based on the order of annotations https://github.com/jaegertracing/jaeger/blob/master/model/converter/thrift/zipkin/to_domain.go#L313 (client annotations should be first)

**Comment by pavolloffay** [comment]
The above about logs does not hold because core annotations are not added as logs https://github.com/jaegertracing/jaeger/blob/master/model/converter/thrift/zipkin/to_domain.go#L282

**Comment by yurishkuro** [comment]
> Zipkin span can contain both server and client annotations. 

under what circumstances?

**Comment by adriancole** [comment]
Zipkin span can contain both server and client annotations.

under what circumstances

This can happen in adhoc POST requests by users saving traces, if they are
using the spark streaming job, or otherwise exporting data and merge by
span ID (only applies to v1 format, core annotations are invalid/redundant
in v2)

**Comment by adriancole** [comment]
So when we receive a v1 span, we end up splitting it. The logic isnt fun,
but if there were server and client annotations, it would become 2 v2 spans
varying on kind but still having the same span ID.

**Comment by yurishkuro** [comment]
> So when we receive a v1 span, we end up splitting it. 

yeah, that was my expectation as well. The PR just puts two `span.kind` tags on the Jaeger span, which is quite hacky, i.e. seems like it's more likely to confuse things later on than help.

**Comment by pavolloffay** [comment]
So how we move forward this? Currently, we are loosing information.

Are we going to do the split too?

**Comment by yurishkuro** [comment]
I think that's three only way, yes.
