### ISSUE TITLE
[Bug]: 1.No service dependencies found. 2.Service & Operation：Do not show dependency hierarchy

### ISSUE THREAD

**Issue by Linwenqiang-git** [jaegertracing/jaeger#4522]
### What happened?

Question one：
Service & Operation：Do not show dependency hierarchy
Question tow：
System Architecture Show:“No service dependencies found.”
Question three：
When an exception occurs in the interface call, it cannot be seen intuitively on the UI interface

### Steps to reproduce

1.docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
  -e COLLECTOR_OTLP_ENABLED=true \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 4317:4317 \
  -p 4318:4318 \
  -p 14250:14250 \
  -p 14268:14268 \
  -p 14269:14269 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.45
  2.I want to use it in a c# program, the code is as follows：
private void ConfigJaeger(ServiceConfigurationContext context)
        {
            context.Services.AddOpenTracing();
            context.Services.AddSingleton<ITracer>(serviceProvider =>
            {
                var serviceName = serviceProvider.GetRequiredService<IWebHostEnvironment>().ApplicationName;

                var loggerFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
                var sampler = new ConstSampler(sample: true);
                var reporter = new RemoteReporter.Builder()
                        .WithLoggerFactory(loggerFactory)                        
                        .WithSender(new UdpSender("192.168.79.137", 6831, 0))
                        .Build();

                var tracer = new Tracer.Builder(serviceName)
                    .WithLoggerFactory(loggerFactory)
                    .WithSampler(sampler)
                    .WithReporter(reporter)
                    .Build();
                

                GlobalTracer.Register(tracer);

                return tracer;
            });
        }

### Expected behavior

show call dependencies

### Screenshot

![image](https://github.com/jaegertracing/jaeger/assets/26178847/584f62c4-709e-47c0-bb3e-964621c55737)
![image](https://github.com/jaegertracing/jaeger/assets/26178847/ec71b264-fb24-4c84-8aed-cfc91cdf9977)

**Comment by yurishkuro** [comment]
you only have one service, so there are no dependencies

**Comment by Linwenqiang-git** [comment]
> you only have one service, so there are no dependencies

What should I do if I want to monitor redis requests? At present, there are redis read and write related in the business logic, but it is not reflected in the link tracking

**Comment by yurishkuro** [comment]
Redis does not generate traces itself, it's only observable from the client side. We have an outstanding issue for that https://github.com/jaegertracing/jaeger/issues/3804
