### ISSUE TITLE
[OTEL] Process info is missing from the spans

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4534]
When query-service span is generated by Jaeger client, we get some Process information filled out:
<img width="536" alt="image" src="https://github.com/jaegertracing/jaeger/assets/3523016/342f63ca-9085-4780-a71f-c0e712b7b059">

However, when the spans are produced by OTEL SDK, Process is empty.

<img width="687" alt="image" src="https://github.com/jaegertracing/jaeger/assets/3523016/54d4db7a-7f74-443b-967f-b2408c7e4328">

We need to find out
  * why is the server information not being filled in - doesn't OTEL SDK capture it by default? Maybe we need to enable some  resource discovery module?
  * Some attributes produced by OTEL SDK, like `otel.library.name`, should not be in the span Tags, but in the process. Ideally this should be fixed upstream in OTEL, but we could also implement it internally as a `model/adjuster`.

**Comment by Michealajit** [comment]
Hi Sir,
I'm new here can i work on this ?

**Comment by Michealajit** [comment]
@yurishkuro  is it a good first issue ?

**Comment by afzal442** [comment]
Hey Yuri, I just came over this. how do you think we can adjust Process to have `otel.library.name` and enable some resource discovery module? Is there any other tags adjusted the same way? How do you see the changes when take this into account? Thanks

**Comment by yurishkuro** [comment]
> adjust Process to have otel.library.name

The simplest way would be to add a new adjuster (under `model/adjuster`) to Jaeger that would move certain attributes from span.tags to span.process.tags.

> enable some resource discovery module

That I don't know, it needs looking into OTEL SDK code.

**Comment by NavinShrinivas** [comment]
Hey @yurishkuro, I'm looking to making my first contribution to jaeger...This issue seems like a good one, Can I be assigned this? I see it's been a while since this issue was last picked up.

**Comment by yurishkuro** [comment]
Feel free to pick it up. We do not explicitly assign issues.

**Comment by james-ryans** [comment]
Sorry... I've encountered the same issue with the previous PR contributor. I've tackled the resource discovery and tag adjuster. Should I remove my tag adjuster and only apply the resource discovery to respect the previous PR contributor?

**Comment by NavinShrinivas** [comment]
Hey, I was having trouble even getting this off the ground...I think you should go ahead and merge your prs. I'll look into some easier issues to get started with
