### ISSUE TITLE
[Feature]: Configurable HTTP options on file-based sampling configuration

### ISSUE THREAD

**Issue by zcross** [jaegertracing/jaeger#4579]
### Requirement

As a Jaeger operator, I want to be able to control settings about the HTTP (and/or TLS) connection used when [file-based remote sampling configuration](https://www.jaegertracing.io/docs/1.47/sampling/#file-based-sampling-configuration) targets a remote http(s) file source (rather than a file system path), so that I can include additional information to aid usage-specific interactions such as authentication.

### Problem

Currently, the `static.StrategyStore` supports the specification of a URL (in addition to a local file path) for loading a remote sampling policy file. If the given strategies file identity is a URL [[code](https://github.com/jaegertracing/jaeger/blob/main/plugin/sampling/strategystore/static/strategy_store.go#L131)], the a straightforward `http.Get` call is performed against that URL to retrieve (and parse, and validate) a presumed JSON strategies policy file [[code](https://github.com/jaegertracing/jaeger/blob/main/plugin/sampling/strategystore/static/strategy_store.go#L100)].

The `static.StrategyStore` has an existing configuration surface area in its `Options` [[code](https://github.com/jaegertracing/jaeger/blob/main/plugin/sampling/strategystore/static/options.go#L31)]. However, this only defines a file identity (path or URL) and a reload interval (extremely useful!). There seems to be no way for usages of this plugin to pass in additional options to this supported HTTP interaction (e.g., in other sources such as the OTEL JRS extension [[reference](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/jaegerremotesampling)]).

### Proposal

It would probably suffice to add support for the following options to the `static.StrategyStore`'s `static.Options`:
- Header additions (e.g,. name/values as a map)
- Forced HTTPS-only mode (as an added protection against config typos accidentally specifying `http` for example)

However, I see that the project already has some [TLS](https://github.com/jaegertracing/jaeger/tree/main/pkg/config/tlscfg) related option structs, so maybe there's a more standardized path forward that just reuses those types. I raise that as being immediately relevant given http(s) support, but my primary motivation in raising this subject is really the ability to configure additional HTTP headers.

### Open questions

1. Are the project maintainers open to the goals of this (general-purpose, opt-in configurability of an already-supported http(s) interaction)? 
2. If I'm willing to contribute the proposed change, are there strong preferences for a path of least resistance?

**Comment by yurishkuro** [comment]
> There seems to be no way for usages of this plugin to pass in additional options to this supported HTTP interaction

Can you provide examples of what you're thinking of passing and why? I am not sure I follow.

> Forced HTTPS-only mode

Do you mean to have another CLI flag that requires the external URL to be https? This feels like an overkill to me - you could just manually add a script to your deployment that will grep the config for `http*` and fail if it's not https, it doesn't need to be built-in into Jaeger.

**Comment by zcross** [comment]
We discussed this in CNCF Slack and I'm leaning toward your suggestion to implement a proper remote config API endpoint rather than trying to hack something with the file-based scheme, so I'll close this. Thanks!
