### ISSUE TITLE
Ingester should use topic name from actual Kafka consumer instead of configuration

### ISSUE THREAD

**Issue by abliqo** [jaegertracing/jaeger#4592]
### Requirement

Ingester must not be bound to statically configured Kafka topic to allow consumption from multiple Kafka topics in environments where actual Kafka consumer is created in custom way and with multiple topics.

### Problem

In our environment we ran into scale limitations of a single Kafka topic (1.5 GB/second). We cannot reliably operate a single Kafka topic with higher throughput than that. We are setting up multiple Kafka topics to scale the throughput further.

Sarama library allows consuming from multiple Kafka topics, if configured so: https://github.com/jaegertracing/jaeger/blob/main/pkg/kafka/consumer/config.go#L74

However, the current implementation of Kafka consumer in the [ingester](https://github.com/jaegertracing/jaeger/blob/main/cmd/ingester/app/consumer/consumer.go) is bound to a single topic specified in the configuration:
https://github.com/jaegertracing/jaeger/blob/main/cmd/ingester/app/consumer/processor_factory.go#L68

This makes it impossible to reuse that ingester code with Kafka consumer that is constructed in custom way with multiple Kafka topics.

### Proposal

The implementation should instead use the topic name from ParitionConsumer provided by the Kafka consumer: https://pkg.go.dev/github.com/bsm/sarama-cluster#PartitionConsumer.

**Comment by abliqo** [comment]
I will make a PR

**Comment by yurishkuro** [comment]
The main unit of scaling in Kafka is partitions, not topics. Ingester can already read from multiple partitions. Please demonstrate what kind of load you're processing that this mechanism is not sufficient.
