### ISSUE TITLE
Promote @jkowall to maintainer

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4597]
I propose to make @jkowall an official maintainer of Jaeger. This case is a bit unusual since @jkowall is not an active coder, and therefore we cannot go by our regular guidelines requiring code contributions. But @jkowall makes many other regular contributions to the project:
  * Regularly presents Jaeger at maintainer tracks at KubeCon
  * Done a full release
  * [Added release signing and other housekeeping tasks](https://github.com/jaegertracing/jaeger/commits?author=jkowall)
  * Documentation improvements

**Comment by albertteoh** [comment]
+1

**Comment by pavolloffay** [comment]
+1

**Comment by yurishkuro** [comment]
Vote is unanimous - welcome @jkowall

**Comment by jkowall** [comment]
Thanks, I am excited to help with the project as always and be part of the team. I appreciate the support!
