### ISSUE TITLE
[ci] Add CI check to ensure consistent version of OTEL semconv

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4646]
# Problem

As seen in this PR #4645, we used a random collection of semconv versions.

# Proposal

* Add a script to search the code for all usages of `"go.opentelemetry.io/otel/semconv/v1.xx.x"` and fail if they are not identical, with an appropriate error message and the exact files that are behind.
* Run that script as part of `make lint`

# Stretch goal

1. A script that automatically fixes the versions (suggest running the script in the output of the lint script)
2. Another check that determines the latest version of semconv available (1.20.0 is the latest right now), and ensure that all files reference that version.

**Comment by perhapsmaple** [comment]
Hello @yurishkuro, I'm interested in working on this issue. Could you please assign it to me? Thanks!

**Comment by Mayhul-Jindal** [comment]
Hey @yurishkuro as I was trying to setup the project I encountered this issue
![image](https://github.com/jaegertracing/jaeger/assets/95216160/d1728cfd-5fbd-4790-b66b-7202042926a9)
I have already tried removing the `go.sum` and then regenerated it using `go mod tidy` but still if gave me the same error. I am new to contributing and stuff, can you suggest me what should I do next ?
