### ISSUE TITLE
[deprecation] Phase out grpc-plugin storage (sidecar via hashicorp-plugin)

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4647]
We support two forms of plugins for external storage (https://github.com/jaegertracing/jaeger/tree/main/plugin/storage/grpc)
  * a sidecar model using hashicorp/go-plugin library
  * a remote storage implementing gRPC Remote Storage API

Even though the recent Hashicorp license changes (https://github.com/cncf/foundation/issues/617) may not affect the `go-plugin` library, the dual plugin model creates unnecessary complication and requires extra code to maintain. And while I did not try it myself, I expect that the sidecar model can be reproduced relatively easily by the users themselves, e.g. by running the existing plugin binaries as a sidecar using their own orchestration mechanisms.

The proposal has been accepted. Roadmap:
  * [x] Give a 6-month grace period for existing users or sidecar plugins to switch to remote gRPC model 
    * [x] #4744
  * [x] Remove the sidecar code & examples
    * [x] #5388 
  * [ ] Clean up the code for gRPC Remote Storage
    * [x] #5442 
  * [x] Update documentation
    * [x] https://github.com/jaegertracing/documentation/pull/702

**Comment by h4shk4t** [comment]
I'd like to work on this issue

**Comment by kevinh-canva** [comment]
Hi @yurishkuro, I stumbled upon this issue when trying out the https://github.com/jaegertracing/jaeger-clickhouse/ plugin. What's the recommended way now to connect Jaeger to Clickhouse?

**Comment by yurishkuro** [comment]
The module needs to be upgraded to implement a binary that runs a regular gRPC service, not a grpc-plugin.
