### ISSUE TITLE
Upgrade Query API v3 to official OpenTelemetry format

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4648]
The quest service has [`api/v3` endpoint][package] that returns data in the [OpenTelemetry format][idl]. However, it uses pre-1.0 version of OTLP, in particular the `InstrumentationLibrarySpan` container message instead of `ScopedSpans`. It also performs manual translation from Jaeger model to OTEL, even though the translation modules are available in OTEL contrib.

Proposal:
  * [x] update jaeger-idl to the current version of OTLP
  * [x] change codegen in jaeger to use the new IDL (see Makefile)
  * [x] modify the [package][] to use OTEL translator instead of manual translation
    * a rough sketch: https://github.com/jaegertracing/jaeger/pull/4649

[package]: https://github.com/jaegertracing/jaeger/tree/main/cmd/query/app/apiv3
[idl]: https://github.com/jaegertracing/jaeger-idl/blob/main/proto/api_v3/query_service.proto#L37

**Comment by tanayvaswani** [comment]
Do we need to implement model2otel auto translator for all the five methods i.e `jaegerSpansToOTLP`, `jSpanToOTLP`, `jTagsToOTLP`, `jLogsToOTLP`, `jReferencesToOTLP` ?

**Comment by yurishkuro** [comment]
the goal of the ticket is to _remove_ implementations, by reusing OTEL's translator.

**Comment by tanayvaswani** [comment]
Sorry, I shouldn't have used the word "implement", I will try working on it, thanks. :)

**Comment by tanayvaswani** [comment]
Aren't we already using [`ResourceSpans`](https://github.com/jaegertracing/jaeger-idl/blob/5ee5dbb6d84175fdfbd18eba0e15c9d8b2ca94a1/proto/api_v3/query_service.proto#L44) which seems to be a part of current version of OTLP ? 
Ref: [here](https://github.com/open-telemetry/opentelemetry-proto/blob/81a296f9dba23e32d77f46d58c8ea4244a2157a6/opentelemetry/proto/trace/v1/trace.proto#L48C24-L48C24)
The `ResourceSpans` says that "A collection of **ScopeSpans** from a Resource". 

I don't know if I am referring something which is not accurate, I'm new to Jaeger & OpenTelemetry, I have the willingness to solve this issue.

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/jaeger/blob/6b7f073339f8a1ed3a44e5cee328c2edaac0baa7/proto-gen/otel/trace/v1/trace.pb.go#L171
