### ISSUE TITLE
jaeger-collector can not connect to cassandra

### ISSUE THREAD

**Issue by Luncher** [jaegertracing/jaeger#466]
I already set up cassandra from `https://hub.docker.com/_/cassandra/` when i deploy jaeger-collector , error message: 

```
➜  ~ docker run -it --link cassandra:cassandra --rm jaegertracing/jaeger-collector
{"level":"info","ts":1507692608.057617,"caller":"healthcheck/handler.go:46","msg":"Health Check server started","http-port":14269}
2017/10/11 03:30:08 gocql: unable to dial control conn 127.0.0.1: dial tcp 127.0.0.1:9042: getsockopt: connection refused
{"level":"fatal","ts":1507692608.0581512,"caller":"collector/main.go:86","msg":"Unable to set up builder","error":"gocql: unable to create session: control: unable to connect to initial hosts: dial tcp 127.0.0.1:9042: getsockopt: connection refused","stacktrace":"github.com/uber/jaeger/vendor/go.uber.org/zap.Stack\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/go.uber.org/zap/field.go:191\ngithub.com/uber/jaeger/vendor/go.uber.org/zap.(*Logger).check\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/go.uber.org/zap/logger.go:301\ngithub.com/uber/jaeger/vendor/go.uber.org/zap.(*Logger).Fatal\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/go.uber.org/zap/logger.go:235\nmain.main.func1\n\t/home/travis/gopath/src/github.com/uber/jaeger/cmd/collector/main.go:86\ngithub.com/uber/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/github.com/spf13/cobra/command.go:636\ngithub.com/uber/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/github.com/spf13/cobra/command.go:722\ngithub.com/uber/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/github.com/spf13/cobra/command.go:681\nmain.main\n\t/home/travis/gopath/src/github.com/uber/jaeger/cmd/collector/main.go:139"}

```

docker ps:

```
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                              NAMES
4bb836bf07d9        cassandra                    "/docker-entrypoin..."   21 minutes ago      Up 21 minutes       7000-7001/tcp, 7199/tcp, 9042/tcp, 9160/tcp                                        cassandra
a4b364bb418c        jaegertracing/jaeger-agent   "/go/bin/agent-lin..."   About an hour ago   Up About an hour    0.0.0.0:5775->5775/udp, 0.0.0.0:6831-6832->6831-6832/udp, 0.0.0.0:5778->5778/tcp   pedantic_minsky

```

**Comment by yurishkuro** [comment]
maybe you need to pass cassandra address as `cassandra:9042`, instead of having it default to localhost. You can pass params via env variables (just upper-case the respective cmd line option and use _ as separator)

**Comment by Luncher** [comment]
when i run script:
```
docker run --rm -e CASSANDRA_SERVERS=127.0.0.1,CASSANDRA_PORT=9042  jaegertracing/jaeger-collector
```

print the some error message

**Comment by yurishkuro** [comment]
what about this?

```
docker run --rm -e CASSANDRA_SERVERS=cassandra jaegertracing/jaeger-collector
```

**Comment by Luncher** [comment]
➜  ~ docker run --rm -e CASSANDRA_SERVERS=cassandra jaegertracing/jaeger-collector


{"level":"info","ts":1507697194.8771298,"caller":"healthcheck/handler.go:46","msg":"Health Check server started","http-port":14269}
{"level":"fatal","ts":1507697194.8845553,"caller":"collector/main.go:86","msg":"Unable to set up builder","error":"gocql: unable to create session: lookup cassandra on 192.168.65.1:53: no such host","stacktrace":"github.com/uber/jaeger/vendor/go.uber.org/zap.Stack\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/go.uber.org/zap/field.go:191\ngithub.com/uber/jaeger/vendor/go.uber.org/zap.(*Logger).check\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/go.uber.org/zap/logger.go:301\ngithub.com/uber/jaeger/vendor/go.uber.org/zap.(*Logger).Fatal\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/go.uber.org/zap/logger.go:235\nmain.main.func1\n\t/home/travis/gopath/src/github.com/uber/jaeger/cmd/collector/main.go:86\ngithub.com/uber/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/github.com/spf13/cobra/command.go:636\ngithub.com/uber/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/github.com/spf13/cobra/command.go:722\ngithub.com/uber/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/uber/jaeger/vendor/github.com/spf13/cobra/command.go:681\nmain.main\n\t/home/travis/gopath/src/github.com/uber/jaeger/cmd/collector/main.go:139"}

**Comment by Luncher** [comment]
Will it be Cassandra's problem?

I start the Cassandra by following this instruction

```

docker run --name cassandra -d cassandra

```

**Comment by jpkrohling** [comment]
Start Cassandra:
```
$ docker run --rm -it --name cassandra -p 9042:9042 cassandra
(wait for it to finish starting up)
```

Initialize the schema:
```
$ MODE=test KEYSPACE=jaeger_v1_local ./plugin/storage/cassandra/schema/create.sh plugin/storage/cassandra/schema/v001.cql.tmpl | docker exec -i cassandra cqlsh
```

Start the collector, specifying the Cassandra host as the IP for the machine running Docker (or add `cassandra` to your network's DNS, or to `/etc/hosts`):
```
$ docker run --rm -e CASSANDRA_SERVERS=192.168.178.20 jaegertracing/jaeger-collector
```

Or link the containers as you did originally:
```
$ docker run --rm --link cassandra:cassandra -e CASSANDRA_SERVERS=cassandra jaegertracing/jaeger-collector
```

**Comment by Luncher** [comment]
can i use  `docker run --link cassandra:cassandra --rm jaegertracing/jaeger-cassandra-schema` init schema ?

**Comment by jpkrohling** [comment]
> can i use docker run --link cassandra:cassandra --rm jaegertracing/jaeger-cassandra-schema init schema ?

Absolutely. I mentioned the other way as it's what I had on a (very old by now) blog post :-) Using the `jaeger-cassandra-schema` is indeed the preferred way now.

**Comment by yurishkuro** [comment]
we need a docker-compose for this setup

**Comment by Luncher** [comment]
I already setup collector and cassandra, when i  run script  :

```shell
 docker run \
  --rm \
  -p5775:5775/udp \
  -p6831:6831/udp \
  -p6832:6832/udp \
  -p5778:5778/tcp \
  jaegertracing/jaeger-agent \
  /go/bin/agent-linux --collector.host-port=192.168.33.99:14267

```

error message:

```shell

{"level":"info","ts":1507774394.3144946,"caller":"tchannel/bulider.go:89","msg":"Enabling service discovery","service":"jaeger-collector"}
{"level":"info","ts":1507774394.3146873,"caller":"peerlistmgr/peer_list_mgr.go:111","msg":"Registering active peer","peer":"192.168.33.99:14267"}
{"level":"info","ts":1507774394.3171961,"caller":"agent/main.go:50","msg":"Starting agent"}
{"level":"info","ts":1507774395.3171203,"caller":"peerlistmgr/peer_list_mgr.go:159","msg":"Not enough connected peers","connected":0,"required":1}
{"level":"info","ts":1507774395.3173008,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"192.168.33.99:14267"}
{"level":"error","ts":1507774395.319017,"caller":"peerlistmgr/peer_list_mgr.go:171","msg":"Unable to connect","host:port":"192.168.33.99:14267","connCheckTimeout":0.25

```

but When I do not specify `collector.host-port`  work correctly.

**Comment by Luncher** [comment]
When I need to access another machine's collector, what should I do?

**Comment by Luncher** [comment]
@yurishkuro  Docker-compose files are necessary for a newbie like me

**Comment by jpkrohling** [comment]
If you started the collector as mentioned on a comment above, you'll need to expose the necessary ports, like 14267. Refer to the Kubernetes [production template](https://github.com/jaegertracing/jaeger-kubernetes/blob/master/production/jaeger-production-template.yml#L154-L159) for a complete list of ports to be opened for each individual component, but here's the command for the collector:

```
$ docker run --rm -p14267:14267 -p142678:14268 -p9411:9411 -e CASSANDRA_SERVERS=192.168.178.20 jaegertracing/jaeger-collector
```

If you continue having issues, please stop by the [Gitter channel](https://gitter.im/jaegertracing/Lobby), as it's more suitable for this kind of question.

**Comment by Luncher** [comment]
I have deployed Jaeger and thank you for your feedback ：）

**Comment by pavolloffay** [comment]
@Luncher please reopen if it's not done.
