### ISSUE TITLE
[ci] Make building debug images optional for PR CI

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4663]
This [all-in-one build](https://github.com/jaegertracing/jaeger/actions/runs/5860356108/job/15888251669?pr=4662) took 15min. In it compiling Delve debugger, which is only used in debug images, took 6min.
```
Mon, 14 Aug 2023 20:33:53 GMT #17 [linux/arm64 build 3/3] RUN if [[ "arm64" == "s390x"  ||  "arm64" == "ppc64le" ]] ; then 	touch /go/bin/dlv;     else         go install github.com/go-delve/delve/cmd/dlv@latest;     fi
Mon, 14 Aug 2023 20:39:26 GMT #17 DONE 395.9s
```
I think we should skip it altogether when running the build for PR, let it only be built for CI runs on the main branch.

**Comment by yurishkuro** [comment]
This was partially addressed by #4496 that is supposed to skip building debug images, but the logs above clearly show that's not enough. E.g. the script `scripts/build-all-in-one-image.sh` still calls `make create-baseimg-debugimg` where Delve compilation takes place, it needs to be changed too to respect the `pr-only` flag.

**Comment by karthikmurali60** [comment]
@yurishkuro I believe [this](https://github.com/jaegertracing/jaeger/pull/4672) PR should resolve this issue.

**Comment by shubmjagtap** [comment]
can i work on this issue ?

**Comment by karthikmurali60** [comment]
@yurishkuro got it. The ```make create-baseimg-debugimg``` command is being called in two scripts -
- build-upload-docker-images.sh
- build-all-in-one-image.sh

Ideally in both of these places, we should execute the make command in only **non** PR mode right ??

**Comment by yurishkuro** [comment]
We always need the main base image, but don't need debug image in pr-only
