### ISSUE TITLE
[ci] Stop building non-Linux architectures for PRs

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4664]
To make building CI for PRs faster, we can skip building for other architectures aside from `linux/amd64`:

https://github.com/jaegertracing/jaeger/blob/54ec466527933f2bf0854ba535730dfe03dec283/scripts/build-all-in-one-image.sh#L37-L41

Note that this is already done in another script https://github.com/jaegertracing/jaeger/blob/54ec466527933f2bf0854ba535730dfe03dec283/scripts/build-upload-docker-images.sh#L11-L20

**Comment by karthikmurali60** [comment]
@yurishkuro can i work on this ? I'd love to contribute !

**Comment by yurishkuro** [comment]
give it a try

**Comment by shubmjagtap** [comment]
Hello @yurishkuro  , i have made the changes but i dont know way to test .sh files in "script" folder , thats why i have not tested this change , can you suggest me how to test it , please.

**Comment by shubmjagtap** [comment]
@karthikmurali60 can you work on issue  #4663 , please . I will help by working on this issue .

**Comment by karthikmurali60** [comment]
@shubmjagtap I believe the PR that I raised should solve issue #4663 as well. Also I requested to work on this issue first 😃

**Comment by shubmjagtap** [comment]
> @shubmjagtap I believe the PR that I raised should solve issue #4663 as well. Also I requested to work on this issue first 😃

yes you are correct but according to contribution guidelines its not necessary that 1st one to request is  considered 1st one to work , anyone can raise PR ( 1st PR matters ).

![image](https://github.com/jaegertracing/jaeger/assets/135511011/e63b92e4-abd7-43f3-935f-51387af3571c)
