### ISSUE TITLE
[Feature]: Changing Twitter's Logo with X

### ISSUE THREAD

**Issue by hirentimbadiya** [jaegertracing/jaeger#4678]
### Requirement

as of now we have older version of twitter's logo which is bird one, but now as twitter's logo has been changed to X so we need to update it to X.

### Problem

since the logo of twitter has changed to X, we also need to update.

### Proposal

I'd love to work on this issue, please assign me.

**Comment by Luxxgit2k4** [comment]
I am ready to work on this issue !!

**Comment by Luxxgit2k4** [comment]
Hi there! 👋 I noticed the issue about changing the Twitter logo and I'm really excited about contributing to this project.  I'd love to help out. Looking forward to your guidance on how I can contribute effectively!
