### ISSUE TITLE
[CI] Cancel GitHub Action workflows running for stale versions

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4695]
Our CI is quite expensive to run, and always try to complete even if a new version was pushed to the PR. @anshgoyalevil just implemented a cancellation of stale jobs for the UI repository, we should replicate that behavior in this repo.

Cf: https://github.com/jaegertracing/jaeger-ui/pull/1710

**Comment by eshwarhs** [comment]
@yurishkuro Can I pick this up?
