### ISSUE TITLE
[Feature]: Support MongoDB as a storage backend

### ISSUE THREAD

**Issue by ghost** [jaegertracing/jaeger#4712]
### Requirement

We use MongoDB in our services and It'd be really neat to have MongoDB integrated as a supported storage backend.

### Problem

Choosing other storage backends will add unnecessary complexity to applications by requiring of administrating additional databases just for the sake of storing traces.

### Proposal

Add MongoDB as a supported storage backend. MongoDB supports TTL indexes and doesn't require a schema, integration with it can be easy and seamless!

### Open questions

In the meantime, what can one do store traces in a MongoDB database?

**Comment by jkowall** [comment]
MongoDB is proprietary and not open source. If someone wants to contribute it, they are more than welcome to, but it will not be an officially supported backend. Are you suggesting to work on this @Linker-123 ?

**Comment by yurishkuro** [comment]
Our investment in Elasticsearch predates its license change.

I added this issue to the overall storage backend tracker. Just like with many other storage backends, we are happy to point people to community-supported versions if someone wish to develop them, but we have no plans to support MongoDB as an official backend for Jaeger.

**Comment by yurishkuro** [comment]
This is not something that we're going to work on, so closing it. If someone implements a plugin solution please post here and we can include in the overall list.

**Comment by raul-guerrero** [comment]
has anyone seen this? https://github.com/edtsoi430/jaeger-mongodb-1
