### ISSUE TITLE
[Bug]: The traceid slice stored in memory was not properly initialized

### ISSUE THREAD

**Issue by Zelayan** [jaegertracing/jaeger#4714]
### What happened?

The traceid slice stored in memory was not properly initialized，ids slices should only have capacity

### Steps to reproduce

look here

func newTenant(cfg config.Configuration) *Tenant {
	return &Tenant{
		ids:        make([]*model.TraceID, cfg.MaxTraces),
		traces:     map[model.TraceID]*model.Trace{},
		services:   map[string]struct{}{},
		operations: map[string]map[spanstore.Operation]struct{}{},
		deduper:    adjuster.SpanIDDeduper(),
		config:     cfg,
	}
}

### Expected behavior

ids slices should only have capacity

### Screenshot

func newTenant(cfg config.Configuration) *Tenant {
	return &Tenant{
		ids:        make([]*model.TraceID, cfg.MaxTraces),
		traces:     map[model.TraceID]*model.Trace{},
		services:   map[string]struct{}{},
		operations: map[string]map[spanstore.Operation]struct{}{},
		deduper:    adjuster.SpanIDDeduper(),
		config:     cfg,
	}
}

### Operating system

os

**Comment by Zelayan** [comment]
/

**Comment by yurishkuro** [comment]
not sure what this is about. Needs more details.
