### ISSUE TITLE
[deprecation] Remove support for expvar metrics

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4722]
Currently most Jaeger components (including HotROD) accept a CLI flag that allows selecting between `prometheus`, `expvar`, and `none` as metrics backends. Most production use cases utilize `prometheus` metrics, which is the default in Jaeger. 

# Proposal
* Deprecate the corresponding CLI flags and remove the ability to configure metrics backends at all
* Still support the endpoint name CLI flag, and if explicitly set to empty string do not mount the endpoint

# Rollout plan
1. [x] Add CLI flag deprecation notice, but do not change anything -- #4740
2. [x] After three releases, remove the CLI flag and the other backends -- #5437

# Comments
* Removing expvar will remove the last dependency on go-kit
* I am working on a new version of HotROD walkthrough that will reflect this change, as well as the OTEL upgrade

**Comment by joeyyy09** [comment]
I'd like to take this up, Thanks!
