### ISSUE TITLE
[deprecate] Remove support for OTEL spanmetrics processor

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4736]
Support for spanmetrics connector was added in v1.46.0 (#4452, June) and made to be the default in v1.49.0 (#4704, Sep).

* [x] Add deprecation warning to the current flag that allows choosing between connector/processor -- #4741
* [x] Per our 3-moonths/2-releases deprecation policy, remove support for that flag and the corresponding code. -- #5539
* [x] Update README and website to avoid referencing the old flag or the processor -- https://github.com/jaegertracing/documentation/pull/709

cc @albertteoh

**Comment by varshith257** [comment]
@yurishkuro Can I ahead to make updates in docs repo?

**Comment by yurishkuro** [comment]
Yes
