### ISSUE TITLE
[Bug]: "Monitor" tab Out of memory error

### ISSUE THREAD

**Issue by tcaty** [jaegertracing/jaeger#4752]
### What happened?

Hi! In our team we use jaeger to monitor some of our serivces. We have really highloaded service, which execute a lot of operations in small time range. 

The problem is that data on "Monitor" has very long loading time. In some cases, when there are aroung 2000 pages with metrics operations kuber kills jaeger pod with OOM message. Also it has side effect on metrics storage Prometheus, which tries to sent a lot of data for these 2000 pages, so it also killed with OOM message. 

### Steps to reproduce

1. Enable SPM
2. Wait a lot of metrics data loading

### Expected behavior

We expect that data on Monitor page will be loaded separated for every page, not for all pages in one request, like it works now.

### Screenshot

![image](https://github.com/jaegertracing/jaeger/assets/79706809/7472d18b-c06f-47a6-94d0-14d269418acf)
![image](https://github.com/jaegertracing/jaeger/assets/79706809/3c5c3b8f-3d4d-4fc8-96c9-1cb0c9037656)

### Additional context

Recently we moved Promethes from HDD to SDD, there are results on screenshots above. With HDD this request had ~ 2 min duration.

### Jaeger backend version

1.48.0

### SDK

OpenTelemetry .NET Automatic Instrumentation

### Pipeline

For metrics:

OTEL AUTO INSTRUMENTATION -> OTEL COLLECTOR -> PROMETHEUS -> JAEGER

### Stogage backend

Span storage: badger, Metrics storage: Prometheus v2.74.0

### Operating system

Linux

### Deployment model

Kubernetes

### Deployment configs

```shell
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: prod
  labels:
    app: jaeger
spec:
  replicas:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          env:
          - name: METRICS_STORAGE_TYPE
            value: prometheus
          - name: PROMETHEUS_SERVER_URL
            value: ***
          - name: PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR
            value: "true"
          - name: SPAN_STORAGE_TYPE
            value: badger
          - name: BADGER_EPHEMERAL
            value: "false"
          - name: BADGER_DIRECTORY_VALUE
            value: /badger/data
          - name: BADGER_DIRECTORY_KEY
            value: /badger/key
          image: jaegertracing/all-in-one:1.48.0
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 2Gi
          ports:
            - name: telemetry
              containerPort: 4317
            - name: web-ui
              containerPort: 16686
```

**Comment by jkowall** [comment]
@tcaty Can you please share the otel collector setup which is writing the metrics? You can do a lot to make the spanmetrics connector write fewer metrics or fewer buckets, which should reduce the amount of data the monitor tab has to read as well. 

We are planning an alternate solution in Jaeger v2 for this use case, but if you want the most control, using the spanmetrics connector is the best option.
