### ISSUE TITLE
[Bug]: JaegerQueryReqsFailing alert specifies 'operation' in message and it isn't aggregated by the alert expr

### ISSUE THREAD

**Issue by filippog** [jaegertracing/jaeger#4771]
### What happened?

Thank you for your work on jaeger! I am importing the prometheus alerts internally, as part of our CI we run 
https://github.com/cloudflare/pint on the alerts and it reported the following issue:

```
$ pint lint prometheus_alerts.yml 
level=info msg="File parsed" path=prometheus_alerts.yml rules=8
prometheus_alerts.yml:62-64: template is using "operation" label but the query removes it (alerts/template)
      "message": |
        {{ $labels.job }} {{ $labels.instance }} is seeing {{ printf "%.2f" $value }}% query errors on {{ $labels.operation }}.
    "expr": "100 * sum(rate(jaeger_query_requests_total{result=\"err\"}[1m])) by (instance, job, namespace) / sum(rate(jaeger_query_requests_total[1m])) by (instance, job, namespace)> 1"
```

Indeed the template uses `operation` though `expr` does not aggregate on it

### Steps to reproduce

1. Install https://github.com/cloudflare/pint
2. Download https://github.com/jaegertracing/jaeger/blob/main/monitoring/jaeger-mixin/prometheus_alerts.yml
3. Run `pint lint prometheus_alerts.yml`

### Expected behavior

The `expr` for JaegerQueryReqsFailing also includes `operation`

**Comment by james-ryans** [comment]
HI! I've opened a PR to fix this issue, please review it if you have some time to spare. I've also explained my approach in the PR. Thanks!
