### ISSUE TITLE
jaeger-query  404 page not found

### ISSUE THREAD

**Issue by jackychee** [jaegertracing/jaeger#478]
I executed  jaeger-query via Docker, when i  access http://localhost:16686  , i get 404 page not found message.  
![t8hcch ulok9ufdl8qo_5](https://user-images.githubusercontent.com/11421069/31704489-382f2602-b414-11e7-81ad-2a60ad7a7013.png)

![dhr _0iv u68hu66 a65m6](https://user-images.githubusercontent.com/11421069/31704514-5548ec32-b414-11e7-9fe7-9ed9856524e8.png)

**Comment by jpkrohling** [comment]
Please, provide the full command used to start the `jaeger-query` image, as well as any relevant logs (`docker logs $CONTAINER_ID`)

**Comment by jackychee** [comment]
command:
docker run  -d --rm  -p16686:16686/tcp  jaegertracing/jaeger-query  /go/bin/query-linux  --es.server-urls=http://es-server-ip:9200 --span-storage.type=elasticsearch

logs:
[root@localhost ~]# docker logs 144bba711704
{"level":"info","ts":1508310321.6124156,"caller":"healthcheck/handler.go:46","msg":"Health Check server started","http-port":16687}
{"level":"info","ts":1508310321.6196938,"caller":"healthcheck/handler.go:88","msg":"Health Check state change","http-status":204}
{"level":"info","ts":1508310321.6197314,"caller":"query/main.go:109","msg":"Starting jaeger-query HTTP server","port":16686}

**Comment by jpkrohling** [comment]
I cannot reproduce your failure. Here are the commands I ran:

```
$ docker run --rm --name elasticsearch -p9200:9200 docker.elastic.co/elasticsearch/elasticsearch:5.6.0 bin/elasticsearch -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1
$ docker run --rm --name jaeger-collector --link elasticsearch:elasticsearch -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://elasticsearch:9200 -e ES_USERNAME=elastic -e ES_PASSWORD=changeme -p14267:14267 -p14268:14268 -p9411:9411 jaegertracing/jaeger-collector
$ docker run --rm --name jaeger-query --link elasticsearch:elasticsearch -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://elasticsearch:9200 -e ES_USERNAME=elastic -e ES_PASSWORD=changeme -p16686:16686/tcp jaegertracing/jaeger-query
```

And I got this (the failure is related to another issue, #464 )
![image](https://user-images.githubusercontent.com/13387/31709672-fae60778-b3f2-11e7-946e-54048631ea6d.png)

**Comment by jpkrohling** [comment]
Oh, I see what's going on. You are missing the parameter for the static files: `--query.static-files=/go/jaeger-ui/` . Try adding that to your command, or try to pass the Elasticsearch information as environment variables (like I did on my previous comment).

**Comment by jackychee** [comment]
thanks  :) #
