### ISSUE TITLE
[Bug]: Image should be created with a non-root user

### ISSUE THREAD

**Issue by dpericaxon** [jaegertracing/jaeger#4781]
### What happened?

We ran a twistlock scan of:
```
jaegertracing/jaeger-ingester  1.48.0
jaegertracing/jaeger-collector 1.48.0
jaegertracing/jaeger-query 1.48.0
```
And it returned that the image was built with "Image should be created with a non-root user".

### Steps to reproduce

Twistlock scan of the images above will return the results.

### Expected behavior

Image is created with non-root user instead of root user.

**Comment by yurishkuro** [comment]
It was done for the agent 0a889e8e, but not other images

**Comment by james-ryans** [comment]
I'd like to work on this issue. Should I update all images to non-root or only ingester, collector, and query as specified above?  I've listed the images in `cmd` directory and there are:
- all-in-one
- jaeger-collector
- jaeger-query
- jaeger-ingester
- jaeger-remote-storage
- jaeger-es-index-cleaner
- jaeger-es-rollover
- jaeger-anonymizer

**Comment by yurishkuro** [comment]
all images - there's no reason why we need to run as root

**Comment by nikzayn** [comment]
@yurishkuro I would like to take this up. 

/assign
