### ISSUE TITLE
the missing emitBatch function in your thrift generated code

### ISSUE THREAD

**Issue by haozhaodev** [jaegertracing/jaeger#479]
Hey dude, i have been read your source code both client(python version) and agent(this project) mentioned in the documentation, but i found some problems as follow:
1. Why do your python client currently only support zipkin format batch not your jaeger batch i preffer the latter.In your code ,you just write transfer logic for zipkin batch .Then the Agent.py in the thrift_gen of your jaeger_client_python miss the function **emitBatch** or interface your define in the thrift files, did you delete it and why?
2. I found out that thrift python run time library do not support UDP thransport at the server side, so i have to change your code in your python library to enforce TCP socket, is there other solutions you can recommend?

**Comment by black-adder** [comment]
1) We've been meaning to get to that but haven't had the time yet. I opened a ticket to keep track of it: https://github.com/jaegertracing/jaeger-client-python/issues/87

2) Can you link the source of the information? I'm not sure what you mean by server side given the python-client is the client side of the equation. Also, why do you have to change the python client to use TCP?

**Comment by haozhaodev** [comment]
Thanks for your replay and the ticket you opend.
What i mean is your python client usd udp socket as the basic transport in the thrift stack and buffer it, so i have to use the same transport as the server side according to thrift programming approach.But the thrift python runtime library do not support UDP socket server, only tcp is implemented, and there is a issue 1737 on ASF which added udp support at 2012 but still opening.
Here  is your source code in jaeger_client_python/TUDPTransport.py
```
class TUDPTransport(TTransportBase, object):
    """
    TUDPTransport implements just enough of the tornado transport interface
    to work for blindly sending UDP packets.
    """
    def __init__(self, host, port, blocking=False):
        self.transport_host = host
        self.transport_port = port
        self.transport_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
```
And thrift 0.10.0 python runtime library,  transport/TSocket.py:
```
class TSocketBase(TTransportBase):
    def _resolveAddr(self):
        if self._unix_socket is not None:
            return [(socket.AF_UNIX, socket.SOCK_STREAM, None, None,
                     self._unix_socket)]
        else:
            return socket.getaddrinfo(self.host,
                                      self.port,
                                      self._socket_family,
                                      socket.SOCK_STREAM,
                                      0,
                                      socket.AI_PASSIVE | socket.AI_ADDRCONFIG)
```

**Comment by black-adder** [comment]
Ok, so sounds like you are attempting to write your own collector/agent in python? If so, it might make sense for you to fork the python client and have it use TCP as well.

**Comment by yurishkuro** [comment]
this ticket is not about any specific issue, so closing it. gitter chat might be a better medium for just questions.
