### ISSUE TITLE
[Feature]: (Re)Introduce changelog-related labels and require them for PRs

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4799]
We already tried this in the past, but there was no enforcement and it didn't take.

* [x] Add a GitHub Action that will verify that a PR has a specific categorization label before it can be merged. We already have a bunch of those labels `changelog:***` labels
  * example of bot: https://github.com/asyncapi/website/pull/2170#issuecomment-1735255198
  * example: https://twitter.com/benasher44/status/1503460237331734528
* [x] Alter the release notes script to validate that all PRs have changelog labels, fail if some don't and print their URLs so that the maintainer can fix them manually. This should ignore dependabot PRs automatically.
* [x] Alter the release notes script to automatically group changes by the labels
* [ ] Apply similar changes to jaeger-ui repo

**Comment by sanyamjain036** [comment]
I'm a beginner to github actions but I want to work on this issue. I am learning about github actions online. May you please guide how to learn and solve this issue?

**Comment by Suraj-kumar00** [comment]
Hi @yurishkuro, How are you doing?
I saw no one is working on this issue so can you please assign it to me so that i can work on this issue?

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/jaeger/blob/029e759d3087de9ef55f388c2f0a425b1274f549/CONTRIBUTING_GUIDELINES.md?plain=1#L35-L41

**Comment by Suraj-kumar00** [comment]
> https://github.com/jaegertracing/jaeger/blob/029e759d3087de9ef55f388c2f0a425b1274f549/CONTRIBUTING_GUIDELINES.md?plain=1#L35-L41

Yeah thanks, Now I'm doing this!

**Comment by kanha-gupta** [comment]
Hey @Suraj-kumar00 are you currently working on this ?

**Comment by devidasjadhav** [comment]
@yurishkuro Can you please explain " to validate that all PRs have changelog labels" means ?
https://github.com/jaegertracing/jaeger/pull/4735/commits/a44a2452219f9ed246892a633bee3f0c6fa686dc

As this was the only PR with changelog. 
So I am definitely missing something here.
Please explain.

**Comment by jkowall** [comment]
@devidasjadhav We are trying to ensure that each PR has a changelog label, which would allow us to generate release notes more easily and in an automated way. Currently, the release process generates the list, but requires some manual processing of the ones which are not tagged.

**Comment by jkowall** [comment]
A couple pointer is looking at this existing action: https://github.com/marketplace/actions/pr-labels and this repo : https://github.com/actions/labeler which is using these actions too.

The current release notes script is located here too: https://github.com/jaegertracing/jaeger/blob/main/scripts/release-notes.py

**Comment by Suraj-kumar00** [comment]
> Hey @Suraj-kumar00 are you currently working on this ?

Yes.

**Comment by yurishkuro** [comment]
I just ran the script and it shows all dependabot PRs under Uncategorized, instead of skipping them.

BTW, instead of building special logic for dependabot, we can change its config to add `changelog:skip` label (now it only sets `dependencies` label).

cc @anshgoyalevil

**Comment by anshgoyalevil** [comment]
@yurishkuro Did you used the `--skip-dependabot` flag?

We can change the dependabot labelling settings but that would defeat the purpose of --skip-dependabot flag

**Comment by yurishkuro** [comment]
Ha, I didn't know we had that flag.  Well if anything it should be `--include-dependabot`, so that it's off by default, but we never really include those in the changelog anyway.

**Comment by anshgoyalevil** [comment]
Yes, then a better workaround here would be to rename the `--skip-dependabot` to `--include-dependabot` arg, and use it accordingly, but since https://github.com/jaegertracing/jaeger/pull/4854 solves this purpose anyhow, do we need to proceed with this arg renaming thing?

**Comment by yurishkuro** [comment]
No, I am good with the current state

**Comment by yurishkuro** [comment]
We need to use these new scripts in jaeger-ui repo as well.
