### ISSUE TITLE
[Feature]: Expose OTLP Ports in all-in-one docker image

### ISSUE THREAD

**Issue by arunvelsriram** [jaegertracing/jaeger#4808]
### Requirement

In the all-in-one docker image Open Telemetry protocol ports (`4317`, `4318`) need to be exposed. https://github.com/jaegertracing/jaeger/blob/main/cmd/all-in-one/Dockerfile

### Problem

We have a testcontainer setup where we rely on the ports marked as exposed by the image. Eg. when running the image with "publish all" flag ie. `docker run -P` the OTLP ports are not published 

### Proposal

Let me know if this is okay to expose. Will raise PR post discussion.

**Comment by yurishkuro** [comment]
Yea they should be. We don't seem to include them in the collector either

**Comment by arunvelsriram** [comment]
Okay. Will add it
