### ISSUE TITLE
[Feature]: Implement CI validation of shell scripts using shellcheck

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4822]
According to its docs, the [shellcheck tool](https://github.com/koalaman/shellcheck) already comes pre-installed in Github runners, so we could add a workflow that will validate all build scripts we use.

Currently running it against our scripts produces 83 warnings, so first we'd need to review them and fix the issues (or disable some lint checks), before we can enable the linter in CI.

```shell
$ shellcheck scripts/*sh | grep '^In ' | wc -l
      83
```

**Comment by akagami-harsh** [comment]
hi @yurishkuro  i would like to take on this issue, i am a beginner here so can you please guide how do i approach this issue

**Comment by akagami-harsh** [comment]
@yurishkuro which issues should i fix and on which should i disable lint checks

**Comment by satyazzz123** [comment]
@yurishkuro can I also work on this issue ?
