### ISSUE TITLE
Current quickstart docker has broken zipkin collector

### ISSUE THREAD

**Issue by postwait** [jaegertracing/jaeger#484]
We've updated our configuration to send to the new jaeger:<zipkinport>/api/v1/traces URI and are failing to get the quickstart docker image to accept our spans.  However, if I checkout master and build and run, it works fine.  It would appear there is something wrong with the build of the quickstart image that is available online.

**Comment by yurishkuro** [comment]
are you using 0.8.0 or latest? Latest was published 3 days ago, should be similar to master.

Also, there's a comment here (https://hub.docker.com/r/jaegertracing/all-in-one/) about enabling the port via env variable

**Comment by postwait** [comment]
I followed the current instructions on quckstart (which has the envvar). I'm still debugging, I'll get to the bottom of this and update the Issue.

**Comment by postwait** [comment]
I've confirmed an issue... I get no reply from 9411 (POST payload and then receive a connection closed).

If I build from master and run from tree, it works fine.


This does not work:
```
docker run -d -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp -p5778:5778 -p16686:16686 -p14268:14268 -p9411:9411 jaegertracing/all-in-one:latest
```

This does work:
```
cmd/standalone/standalone-linux --span-storage.type=memory --collector.zipkin.http-port=9411 --query.static-files=jaeger-ui/build/
```

**Comment by pavolloffay** [comment]
@postwait could you please confirm what your `latest` image is? Please run `docker images --digests`. Could you please also post logs of the running container?

**Comment by postwait** [comment]
It was an outdated image.  Not sure how my initial pull didn't work.
