### ISSUE TITLE
[ci] Split install-tools into test/build groups

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4846]
All our GH Workflows call `make install-ci`, which is just an aliast to `make install-tools`. The latter installs ALL tools, including `mockery` (never needed in CI), `golangci-lint` (a pretty expensive package to install and only needed in unit-test workflow), and `goversioninfo` only needed when building Windows binaries. The full step takes over 1min in CI, wasting time in most cases.

Proposal:
  * Split `install-tools` into mockery / testing / build sub-targets
  * Split `install-ci` target into `install-ci-test` and `install-ci-build` and invoke appropriate sub-targets from above
  * Update workflows to call the appropriate `install-ci-***` target

**Comment by Manish-Giri** [comment]
Hi, can I give this a shot?

**Comment by yurishkuro** [comment]
go for it

**Comment by Manish-Giri** [comment]
@yurishkuro Looks like there is now a PR open for this issue, would have been good to know if the author had updated about it here, to prevent duplicated efforts.
