### ISSUE TITLE
[Feature] Make ArchiveTrace button in the UI auto-configurable

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4874]
When archive storage is configured in the query-service it can receive POST requests from the UI with a trace ID and clone that trace from primary storage into archive, useful for longer retention. However, the Archive Trace button has to be separately enabled in the UI for that, even though the query-service can check at runtime if archive storage is available.

## Proposal

When query-service embeds the UI config into UI loading page, it can also include a structure describing the capabilities of the backend. One of the flags in this structure would be whether the archive storage is available, so that users wouldn't need to configure it separately in the UI. The same struct can be used to inform the UI of other things, for example whether more flexible queries are supported by the storage, like regex on tags (supported in ES but not in Cassandra).

We should still keep the enableArchive in the main UI config, but use it as a kill switch / override for archive function. When the UI decides whether to show the button, it would be `backendSupportsArchive && config.archiveEnabled`.

Implementing this ticket requires some knowledge of both Go and Node.js

## Details, Pointers

The `query-service` injects a config into UI loading page in the static handler: https://github.com/jaegertracing/jaeger/blob/089fc3c878d7def9ce92ab7194012061a8f185de/cmd/query/app/static_handler.go#L120

**Comment by MeenuyD** [comment]
Hello @yurishkuro I would like to work on this issue can you please tell should I change the logic to this
```
capabilities := BackendCapabilities{
        SupportsArchive: true,  
        SupportsFlexibleQueries: true,  
    }
    uiConfig.BackendCapabilities = capabilities
    uiConfigJSON, err := json.Marshal(uiConfig)
    if err != nil {
        return nil, fmt.Errorf("failed to marshal UI config: %w", err)
    }
    indexBytes = configObject.regexp.ReplaceAll(indexBytes, uiConfigJSON)

    return indexBytes, nil
```  by creating some new variables?

**Comment by yurishkuro** [comment]
on a high level - yes, but many details are wrong. You need to try in live code.

**Comment by MeenuyD** [comment]
Ok you assign me I will try and correct it

**Comment by yurishkuro** [comment]
we don't assign tickets, but feel free to implement

**Comment by thecoons** [comment]
I have made the requested changes on the `jaeger` PR and pushed one on `jaeger-ui`. Currently, I'm still having some issues testing the integration, but this allows for a preview of the end-to-end implementation.

**Comment by yurishkuro** [comment]
@thecoons Thank you for your contribution!  🎉 🎉 🎉  And for sticking with it during my picky code reviews :-)

**Comment by thecoons** [comment]
@yurishkuro I expected no less from you, and it's a pleasure to contribute to Jaeger.

P.S.: Your book is a very interesting read :)
