### ISSUE TITLE
Query service: /api/config returning index.html

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger#489]
**Description**

The query-service is returning the body of `index.html` when the UI requests `/api/config`.

This is causing errors in the browser, but fortunately they are not interrupting the UI experience.

The ideal scenario is the config is dumped into the body of `index.html` when it is served. This will allow us to remove the HTTP call to `/api/config` entirely. 

Per a previous discussion, the `index.html` can contain the following, which I believe can be replaced with a JSON serialization of the config:

```
JAEGER_CONFIG = DEFAULT_CONFIG;
```

Where `DEFAULT_CONFIG` is replaced with the UI config contents.

The UI config contents are `{}` by default, and can be overridden via a envar or cmd line parameter (maybe `query.ui-config`?) that conveys a filepath with a YAML or JSON file.

**Steps to reproduce the issue:**
1. Follow the steps [here](http://jaeger.readthedocs.io/en/latest/getting_started/#sample-application)
2. Create a trace via the HotROD app
3. View a trace

**Describe the results you received:**

`/api/config` returns the `index.html` content.

**Describe the results you expected:**

Either `/api/config` returns the `index.html` content or we switch to dumping the config into the body of the HTML.

**Comment by yurishkuro** [comment]
Let's make a change in the UI project first that ensures that the generated index.html contains
```
DEFAULT_CONFIG = {};
JAEGER_CONFIG = DEFAULT_CONFIG;
```
Then we can add code to the query service to assign a different value to JAEGER_CONFIG when serving index.html

**Comment by tiffon** [comment]
Sounds good, will post back when it's merged.

**Comment by yurishkuro** [comment]
UI change: https://github.com/jaegertracing/jaeger-ui/pull/107

**Comment by yurishkuro** [comment]
All done & tested, keeping this open until we add docs on how to use it.

**Comment by pavolloffay** [comment]
https://github.com/jaegertracing/jaeger-ui could list all configurable options.

**Comment by yurishkuro** [comment]
@pavolloffay elaborate? Like a help page?

**Comment by yurishkuro** [comment]
or you mean the README?  +1 then

**Comment by pavolloffay** [comment]
just the readme for now

**Comment by yurishkuro** [comment]
I think we have one outstanding issue (https://github.com/jaegertracing/jaeger-ui/issues/123) before we can document (although the current solution already works, so we _could_ just document it as is - https://github.com/jaegertracing/jaeger-ui/issues/124).

Since there are tickets in the UI repo now, I am going to close this one.
