### ISSUE TITLE
Remove dependency on deprecated github.com/golang/protobuf

### ISSUE THREAD

**Issue by mmorel-35** [jaegertracing/jaeger#4911]
### Requirement

Use only one library to handle protobuf

### Problem

There are three dependencies to handle protobuf in jaeger:
- `github.com/gogo/protobuf` : DEPRECATED
- `github.com/golang/protobuf` superseded by `google.golang.org/protobuf`
- `google.golang.org/protobuf`

### Proposal

Migrate to `google.golang.org/protobuf`

**Comment by yurishkuro** [comment]
> github.com/golang/protobuf superseded by google.golang.org/protobuf

yes, this one we should clean up, we probably just need to regenerate types using newer version.
```
$ grep -r github.com/golang/protobuf .
./go.mod:26:	github.com/golang/protobuf v1.5.3
./proto-gen/api_v3/query_service.pb.gw.go:16:	"github.com/golang/protobuf/descriptor"
./proto-gen/api_v3/query_service.pb.gw.go:17:	"github.com/golang/protobuf/proto"
./plugin/storage/grpc/proto/storageprototest/storage_test.pb.go:24:	proto "github.com/golang/protobuf/proto"
./model/prototest/model_test.pb.go:24:	proto "github.com/golang/protobuf/proto"
```

We don't have any concrete plan to move away from gogo, as it provides a significant efficiency boost over default official go-protobuf. OTEL's data model also using it - if they find a solution we could move in sync.

**Comment by akagami-harsh** [comment]
hi @yurishkuro, i want to work on this issue. So basically we have to migrate from using the `github.com/gogo/protobuf` and `github.com/golang/protobuf` dependencies to using `google.golang.org/protobuf` for handling Protocol Buffers.

**Comment by yurishkuro** [comment]
No we're not changing gogo, only the other one

**Comment by EshaanAgg** [comment]
Hi! If this issue is unassigned and no one is working on it, I would love to take this up. I have some experience working with `protobuf` in `Go`, but am completely new to `JaegerUI`. Would appreciate any help or links to documentation about the same!

**Comment by yurishkuro** [comment]
Status update - the above 3 PRs managed to remove `github.com/golang/protobuf` from the main code paths, but it still remains on the path that uses grpc-gateway. Related discussion in #4917. To resolve that, we need:
  * https://github.com/jaegertracing/docker-protobuf/issues/30
  * finish https://github.com/jaegertracing/docker-protobuf/pull/29
  * finally regenerate the types in this repo, which should remove the old dependency

**Comment by xdobiasl** [comment]
It seems that this is not fixed, dependency to `github.com/golang/protobuf` is still there in jaeger 1.55.0 linux packages:
```
xdobiasl@ldobias-cz:jaeger-1.55.0-linux-amd64$ for i in *;do echo $i:; (go version -m $i |grep protobuf);done
example-hotrod:
        dep     github.com/gogo/protobuf        v1.3.2  h1:Ov1cvc58UF3b5XjBnZv7+opcTcQFZebYjWzi34vdm4Q=
        dep     github.com/golang/protobuf      v1.5.3  h1:KhyjKVUg7Usr/dYsdSqoFveMYd5ko72D+zANwlG1mmg=
        dep     google.golang.org/protobuf      v1.32.0 h1:pPC6BG5ex8PDFnkbrGU3EixyhKcQ2aDuBS36lqK/C7I=
jaeger-agent:
        dep     github.com/gogo/protobuf        v1.3.2  h1:Ov1cvc58UF3b5XjBnZv7+opcTcQFZebYjWzi34vdm4Q=
        dep     github.com/golang/protobuf      v1.5.3  h1:KhyjKVUg7Usr/dYsdSqoFveMYd5ko72D+zANwlG1mmg=
        dep     google.golang.org/protobuf      v1.32.0 h1:pPC6BG5ex8PDFnkbrGU3EixyhKcQ2aDuBS36lqK/C7I=
jaeger-all-in-one:
        dep     github.com/gogo/protobuf        v1.3.2  h1:Ov1cvc58UF3b5XjBnZv7+opcTcQFZebYjWzi34vdm4Q=
        dep     github.com/golang/protobuf      v1.5.3  h1:KhyjKVUg7Usr/dYsdSqoFveMYd5ko72D+zANwlG1mmg=
        dep     google.golang.org/protobuf      v1.32.0 h1:pPC6BG5ex8PDFnkbrGU3EixyhKcQ2aDuBS36lqK/C7I=
jaeger-collector:
        dep     github.com/gogo/protobuf        v1.3.2  h1:Ov1cvc58UF3b5XjBnZv7+opcTcQFZebYjWzi34vdm4Q=
        dep     github.com/golang/protobuf      v1.5.3  h1:KhyjKVUg7Usr/dYsdSqoFveMYd5ko72D+zANwlG1mmg=
        dep     google.golang.org/protobuf      v1.32.0 h1:pPC6BG5ex8PDFnkbrGU3EixyhKcQ2aDuBS36lqK/C7I=
jaeger-ingester:
        dep     github.com/gogo/protobuf        v1.3.2  h1:Ov1cvc58UF3b5XjBnZv7+opcTcQFZebYjWzi34vdm4Q=
        dep     github.com/golang/protobuf      v1.5.3  h1:KhyjKVUg7Usr/dYsdSqoFveMYd5ko72D+zANwlG1mmg=
        dep     google.golang.org/protobuf      v1.32.0 h1:pPC6BG5ex8PDFnkbrGU3EixyhKcQ2aDuBS36lqK/C7I=
jaeger-query:
        dep     github.com/gogo/protobuf        v1.3.2  h1:Ov1cvc58UF3b5XjBnZv7+opcTcQFZebYjWzi34vdm4Q=
        dep     github.com/golang/protobuf      v1.5.3  h1:KhyjKVUg7Usr/dYsdSqoFveMYd5ko72D+zANwlG1mmg=
        dep     google.golang.org/protobuf      v1.32.0 h1:pPC6BG5ex8PDFnkbrGU3EixyhKcQ2aDuBS36lqK/C7I=
```

**Comment by yurishkuro** [comment]
The objective of this ticket was to remove direct dependencies, which was achieved:
```
$ grep protobuf go.mod
	github.com/gogo/protobuf v1.3.2
	google.golang.org/protobuf v1.33.0
	github.com/golang/protobuf v1.5.3 // indirect
```
We may not be able to remove indirect dependencies, especially if we're already on the latest versions of libraries that pull that indirect dependency.

We need to understand what is pulling `github.com/golang/protobuf` - if it's gogo, then there's nothing we can do without migrating off gogo (which we cannot now, because OTEL uses it).
