### ISSUE TITLE
[Bug]: export const ANALYTICS_ROOT = prefixUrl('/analytics/'); no Rest available

### ISSUE THREAD

**Issue by durrabkhan** [jaegertracing/jaeger#4921]
### What happened?

I was looking at this in jaeger.js file 
export const ANALYTICS_ROOT = prefixUrl('/analytics/');

that rest call is getting called from this 

 fetchDeepDependencyGraph(query) {
    console.log(`url = ${ANALYTICS_ROOT}v1/dependencies`)
    return getJSON(`${ANALYTICS_ROOT}v1/dependencies`, { query });
  }

I am also trying to search for /analytics rest call in golang but I am not able to find it - Please let me know if I am missing anything

### Steps to reproduce

search for jaeger.js under jeager-ui/packages/jageer-ui/src/api/

check the line 83 and then check the line 94 which is 

fetchDeepDependencyGraph

### Expected behavior

should call /analytics/v1/dependencies

### SDK

latest

**Comment by jkowall** [comment]
Firstly, sorry for the delay on this issue. Your issue doesn't seem to describe any kind of problem, and the rest of the questions in the issue template are not answered. Please re-open with a clear description of the issue you are having, and we'll answer it.
