### ISSUE TITLE
[Bug]: System Architecture tabs display in jaeger: No service dependencies found

### ISSUE THREAD

**Issue by Benboy10** [jaegertracing/jaeger#4939]
### What happened?

Hello. Would you tell me why I don't see something in System Architecture?
I installed jaeger 1.47 all in one project in kuberntes, My microservices send opentelemetry spans in two services,  I see that

Why SystemArchitecture tab is empty?

Its showing deep depedency graph well.

Elastic search -- 8.x
Jaeger -1.47

**Comment by yurishkuro** [comment]
Did you run the required pipeline?  https://www.jaegertracing.io/docs/1.50/faq/#why-is-the-dependencies-page-empty

**Comment by Benboy10** [comment]
I am newbie to jaeger. Where can i run this pipeline. is it in Elastic search or Jaeger @yurishkuro 

i can see deep depency graph but not sysytem architecture

**Comment by yurishkuro** [comment]
You need to run Spark or Flink pipeline. It is explained in the FAQ link and the respective repos' READMEs
