### ISSUE TITLE
[Bug]: Not able to see data in Monitor tab in Jaeger

### ISSUE THREAD

**Issue by Benboy10** [jaegertracing/jaeger#4940]
I am using jaeger 1.47 all in one  and integrated the micro services, I can see data in 'search' and 'comapre' but not under Monitor tab in jaeger

is Prometheus need to install separetely, please help

**Comment by yurishkuro** [comment]
This is clearly explained in the documentation and on the Monitor page itself. Please do a bit of research before asking questions, especially raising bug tickets.
