### ISSUE TITLE
[Bug]: Jaeger prometheus metrics are missing "collector" prefix?

### ISSUE THREAD

**Issue by bduffany** [jaegertracing/jaeger#5007]
### What happened?

The jaeger docs [here](https://www.jaegertracing.io/docs/1.52/performance-tuning/) as well as sample Grafana dashboard [here](https://github.com/jaegertracing/jaeger/blob/b5f73aede2d76249cbd6d9855d46ed158c0419f9/monitoring/jaeger-mixin/dashboard-for-grafana.json#L573) reference a metric `jaeger_collector_queue_length`. However, when running the latest jaeger image `jaegertracing/all-in-one:1.52`, the "collector" prefix seems to be missing - it only exports a `jaeger_queue_length` metric. So it seems like either the docs/grafana dashboard are wrong, or there's a bug where the "collector" prefix is missing on the exported metric? Or maybe these are actually different metrics and the "jaeger_collector_*" metrics are just missing?

Here are all the `jaeger_collector_*` metrics that are referenced from the Grafana dashboard:

```
jaeger_collector_in_queue_latency_bucket
jaeger_collector_queue_length
jaeger_collector_spans_dropped_total
jaeger_collector_spans_received_total
```

Unless these are actually different metrics, it looks like the actual metric names that are exported are:

```
jaeger_in_queue_latency_bucket
jaeger_queue_length
jaeger_spans_dropped_total
jaeger_spans_received_total
```

### Steps to reproduce

Run the latest all-in-one image:

```
$ docker run --rm -it --net=host jaegertracing/all-in-one:1.52
```

Check which metrics are exported:

```
$ curl -fsSL http://localhost:14269/metrics | grep queue_length
jaeger_queue_length{host="..."}
```

Observe that the metric is called "jaeger_queue_length", not "jaeger_collector_queue_length" as referenced in both docs and sample Grafana dashboards.

### Expected behavior

The metric should either be called `jaeger_collector_queue_length` or the docs + sample Grafana dashboard should reference the actual metric value `jaeger_queue_length`, depending on which is the "correct" / intended value.

### Jaeger backend version

1.52

**Comment by yurishkuro** [comment]
Yeah, looks like a bug. When you run the collector the metric name is correct, but in all-in-one it loses the `collector` segment:

**Comment by bduffany** [comment]
Thank you for fixing this!
