### ISSUE TITLE
Enable errorlint linter

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5027]
Last time we checked, there were about 20 places in the code that did not use `fmt.Errorf("...: %w, err)` error wrapping syntax, which is checked by the `errorlint` linter. 

* [ ] fix the code in those places
* [ ] enable the linter

https://github.com/jaegertracing/jaeger/blob/baed450f5f345ef915e76293bf11f76883604f31/.golangci.yml#L53-L56

**Comment by 1-8** [comment]
please assign this to me.
