### ISSUE TITLE
why the dependencystore has no mock writer

### ISSUE THREAD

**Issue by ray1888** [jaegertracing/jaeger#506]
why the dependencystore has no writer? i saw it already define in the interface.go in the dependencystore?but why in the mock directory , the writer didn't exist? is you guys forgot to merge it ?

**Comment by yurishkuro** [comment]
I think because we don't have a REST endpoint for storing dependencies, as it's typically done by a Spark job that writes to Cassandra directly.

**Comment by yurishkuro** [comment]
Closing as it's not clear why this is an issue
