### ISSUE TITLE
[Bug]:  HotROD can't send trace data to otlp endpoint correctly

### ISSUE THREAD

**Issue by lazywhite** [jaegertracing/jaeger#5063]
### What happened?

As a user, I want hotrod can send trace data to OTEL_EXPORTER_OTLP_ENDPOINT env correctly

### Steps to reproduce

1. setup a jeager-collector with otlp http endpoint http://192.168.64.3:4318
2. run  hotrod with this command`OTEL_EXPORTER_OTLP_ENDPOINT=http://192.168.64.3:4318 go run . all

### Expected behavior

hotrod can send trace data correctly

### Relevant log output

```shell
2023/12/30 17:34:00 traces export: context deadline exceeded: retry-able request failure
2023/12/30 17:34:02 traces export: context deadline exceeded: retry-able request failure
2023/12/30 17:34:02 traces export: context deadline exceeded: retry-able request failure
2023/12/30 17:34:02 traces export: context deadline exceeded: retry-able request failure
2023/12/30 17:34:02 traces export: context deadline exceeded: retry-able request failure
2023/12/30 17:34:02 traces export: context deadline exceeded: retry-able request failure
```
```


### Screenshot

_No response_

### Additional context

_No response_

### Jaeger backend version

v1.52.0

### SDK

_No response_

### Pipeline

_No response_

### Stogage backend

_No response_

### Operating system

_No response_

### Deployment model

_No response_

### Deployment configs

_No response_

**Comment by yurishkuro** [comment]
More likely you have a networking setup issue on your side. Env var works fine:
https://github.com/jaegertracing/jaeger/blob/5082239033c21a5e20c5f4afaa5117a9431dd1be/examples/hotrod/docker-compose.yml#L26
