### ISSUE TITLE
Implement missing unit tests

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5068]
Our CI enforces that all packages with .go files must have at least one _test.go file, to ensure the package is included in the code coverage, OR that it has a `.nocover` file when testing it is very difficult (e.g. requires external DB connection).

However, we somewhat abused the `.nocover` capability and have a bunch of packages that *could* have tests with high coverage. This ticket is about incrementally fixing those, which is a good first issue since the changes can be reasonably small if scoped to one package.

To see which packages need these tests, run `make nocover`.

Regarding `./examples/`, where lots of `.nocover` files are found today, I think we can replace them with `empty_test.go` as we do in some other dirs, because examples will still be excluded from the overall coverage percentage, so there's no need to be excluding them via `.nocover` mechanism (it just creates noise).

## Update Jun 17 2024

We are actually down to a single package remaining
```
$ make nocover
Verifying that all packages have test files to count in coverage
Package excluded from coverage: ./pkg/es/config/
  reason: requires connection to Elasticsearch
```
The reason stated in that package is not very valid - it only checks for the version of the server which can be easily mocked with a simple HTTP server as we already do in other ES-related tests. The majority of methods in the package do not require connection at all and can be 100% covered by tests.

**Comment by chirag-ghosh** [comment]
I would like to work on this

**Comment by yurishkuro** [comment]
@chirag-ghosh thanks. I suggest you pick one of the packages and maybe post here that you're working on it, in case someone else also wants to pick another package. Don't combine multiple packages in one PR.

**Comment by chirag-ghosh** [comment]
Sure. Since I'm new to the project, I'll first setup it in my local and the comment the package I'm working on ASAP.

**Comment by chirag-ghosh** [comment]
I am working on the storageexporter package (https://github.com/jaegertracing/jaeger/tree/main/cmd/jaeger/internal/exporters/storageexporter)

**Comment by akagami-harsh** [comment]
working on `cmd/jeager/internal`

**Comment by Pushkarm029** [comment]
working on `./pkg/version/`

**Comment by chirag-ghosh** [comment]
Working on jaegerstorage

**Comment by tarhphilomina** [comment]
working on [Jaeger/plugin/](https://github.com/jaegertracing/jaeger/tree/main/plugin)

**Comment by VaibhavMalik4187** [comment]
I'd like to work on `internal/tracegen`

**Comment by VaibhavMalik4187** [comment]
I'm working on `cmd/jaeger/internal/extension/jaegerquery/` package.

**Comment by prakrit55** [comment]
I will cover ./cmd/anonymizer/app/query/ @yurishkuro

**Comment by Wise-Wizard** [comment]
Hi @yurishkuro, Can I work on writing the test of  cmd/jaeger/internal/extension/jaegerquery/?

**Comment by Wise-Wizard** [comment]
Hi @VaibhavMalik4187, do you plan on completing the PR regarding tests for JaegerQuery or I can go ahead and complete the remaining requirements?

**Comment by h4shk4t** [comment]
I'd like to work on `cmd/anonymizer/app/query/`

**Comment by zedGGs** [comment]
Heey @yurishkuro, I can add tests too, what do u suggest is priority at the moment ?

**Comment by yurishkuro** [comment]
This is DONE! 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 

Thanks to everyone who contributed: @akagami-harsh @Pushkarm029 @chirag-ghosh @tarhphilomina @VaibhavMalik4187 @Wise-Wizard @h4shk4t @shanukun @hellspawn679 @Nabil-Salah
