### ISSUE TITLE
Is there any reason to set maximumTagKeyOrValueSize = 256?

### ISSUE THREAD

**Issue by tovin07** [jaegertracing/jaeger#508]
I want to trace some DB calls (SQL statement for example).
I look at [OpenTracing API Specification](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table) and see that I can use `db.statement` for this.

However, when I try to use this, I see that tag value in jaeger is limited to 256 characters. As it was hard-coded [at this line.](https://github.com/jaegertracing/jaeger/blob/d3df7c8ba8d9b7a18e8c5747fb560fe622a713cc/plugin/storage/cassandra/spanstore/writer.go#L61)

I think 256 characters is too short, especially when some SQL statements are generated by SQLAlchemy.

So, is there any reason for this?

@jpkrohling recommend that I should find the way to shorten SQL statement.

But I don't think that will work globally.

Thanks!

**Comment by jpkrohling** [comment]
To clarify, my recommendation is to use a tag value that can be later used for filtering purposes, like, `db.statement=select-user-from-bla` , instead of storing the whole SQL statement, which could still be stored as a log entry. But as this is set by a framework integration, my recommendation won't work :)

**Comment by yurishkuro** [comment]
Iirc it's a seeing in the client. We should remove it.

**Comment by tovin07** [comment]
Oh, thanks.
However, it appears that 256 characters limit is in JSON response too.

**Comment by yurishkuro** [comment]
@tovin07 which client are you using?

**Comment by tovin07** [comment]
I use python jaeger client and jaeger all-in-one docker.
I saw this issue in Jaeger web UI and the raw JSON returned.

**Comment by yurishkuro** [comment]
Right, Python. Here it is: https://github.com/jaegertracing/jaeger-client-python/blob/bbb07d46c03f0e4c369dbca93fda6011b3b39fae/jaeger_client/thrift.py#L78

Do you want to put a PR to remove this trimming?

**Comment by tovin07** [comment]
Of course, yes. I will make sense.
Thanks!

**Comment by tovin07** [comment]
Below is an example of SQL statement. It is about 3500 characters.
Therefore, I think that we can remove the 256 characters check.

```sql
SELECT
    anon_1.images_created_at AS anon_1_images_created_at,
    anon_1.images_updated_at AS anon_1_images_updated_at,
    anon_1.images_deleted_at AS anon_1_images_deleted_at,
    anon_1.images_deleted AS anon_1_images_deleted,
    anon_1.images_id AS anon_1_images_id,
    anon_1.images_name AS anon_1_images_name,
    anon_1.images_disk_format AS anon_1_images_disk_format,
    anon_1.images_container_format AS anon_1_images_container_format,
    anon_1.images_size AS anon_1_images_size,
    anon_1.images_virtual_size AS anon_1_images_virtual_size,
    anon_1.images_status AS anon_1_images_status,
    anon_1.images_visibility AS anon_1_images_visibility,
    anon_1.images_checksum AS anon_1_images_checksum,
    anon_1.images_min_disk AS anon_1_images_min_disk,
    anon_1.images_min_ram AS anon_1_images_min_ram,
    anon_1.images_owner AS anon_1_images_owner,
    anon_1.images_protected AS anon_1_images_protected,
    image_properties_1.created_at AS image_properties_1_created_at,
    image_properties_1.updated_at AS image_properties_1_updated_at,
    image_properties_1.deleted_at AS image_properties_1_deleted_at,
    image_properties_1.deleted AS image_properties_1_deleted,
    image_properties_1.id AS image_properties_1_id,
    image_properties_1.image_id AS image_properties_1_image_id,
    image_properties_1.name AS image_properties_1_name,
    image_properties_1.value AS image_properties_1_value,
    image_tags_1.created_at AS image_tags_1_created_at,
    image_tags_1.updated_at AS image_tags_1_updated_at,
    image_tags_1.deleted_at AS image_tags_1_deleted_at,
    image_tags_1.deleted AS image_tags_1_deleted,
    image_tags_1.id AS image_tags_1_id,
    image_tags_1.image_id AS image_tags_1_image_id,
    image_tags_1.value AS image_tags_1_value,
    image_locations_1.created_at AS image_locations_1_created_at,
    image_locations_1.updated_at AS image_locations_1_updated_at,
    image_locations_1.deleted_at AS image_locations_1_deleted_at,
    image_locations_1.deleted AS image_locations_1_deleted,
    image_locations_1.id AS image_locations_1_id,
    image_locations_1.image_id AS image_locations_1_image_id,
    image_locations_1.value AS image_locations_1_value,
    image_locations_1.meta_data AS image_locations_1_meta_data,
    image_locations_1.status AS image_locations_1_status

FROM (
    SELECT
        images.created_at AS images_created_at,
        images.updated_at AS images_updated_at,
        images.deleted_at AS images_deleted_at,
        images.deleted AS images_deleted,
        images.id AS images_id,
        images.name AS images_name,
        images.disk_format AS images_disk_format,
        images.container_format AS images_container_format,
        images.size AS images_size,
        images.virtual_size AS images_virtual_size,
        images.status AS images_status,
        images.visibility AS images_visibility,
        images.checksum AS images_checksum,
        images.min_disk AS images_min_disk,
        images.min_ram AS images_min_ram,
        images.owner AS images_owner,
        images.protected AS images_protected

    FROM
        images

    WHERE
        images.deleted = false
        AND images.status IN (
            %(status_1)s,
            %(status_2)s,
            %(status_3)s,
            %(status_4)s,
            %(status_5)s,
            %(status_6)s,
            %(status_7)s,
            %(status_8)s
        )
        AND (images.owner = %(owner_1)s
        OR images.visibility != %(visibility_1)s)

    ORDER BY
        images.created_at DESC,
        images.id DESC

    LIMIT
        %(param_1)s
) AS anon_1
    LEFT OUTER JOIN image_properties AS image_properties_1
        ON anon_1.images_id = image_properties_1.image_id
    LEFT OUTER JOIN image_tags AS image_tags_1
        ON anon_1.images_id = image_tags_1.image_id
    LEFT OUTER JOIN image_locations AS image_locations_1
        ON anon_1.images_id = image_locations_1.image_id

ORDER BY
    anon_1.images_created_at DESC,
    anon_1.images_id DESC
```

**Comment by yurishkuro** [comment]
@tovin07 I made the max tag length configurable in Python client, and increased the default to 1024.

> https://github.com/jaegertracing/jaeger/blob/d3df7c8ba8d9b7a18e8c5747fb560fe622a713cc/plugin/storage/cassandra/spanstore/writer.go#L61

This 256 limit only affects which tags are being indexed for search, it does not actually truncate the values. The assumption is that it's unlikely someone will be searching for exact match on a very long string.

> However, it appears that 256 characters limit is in JSON response too.

I am not aware of that one, where do you see this limitation? There's this code
```
model/keyvalue.go:163:		if len(kv.VBlob) > 256 {
model/keyvalue.go:164:			return hex.EncodeToString(kv.VBlob[0:256]) + "..."
```

but that's only for binary data.

**Comment by tovin07** [comment]
Thanks @yurishkuro,

I saw your PR, and it works.
If we change, or remove this, the problem will be solved.

```python
    if len(value) > 256:
        value = value[:256]
```

>> However, it appears that 256 characters limit is in JSON response too.
> I am not aware of that one, where do you see this limitation? There's this code
Hmm, because data in database is already truncated to 256 --> output data will be the same.

Anw, thank you again for your PR.
I think that this issue can be closed for now.
