### ISSUE TITLE
Jaeger's LFX Mentorship - 2024 Term 01, March - May

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5084]
**Mentorship term: March 4 - May 31**

I want to try a different approach in this round. Rather than have small independent projects as we did previously (#4457), I would rather have 2-3 mentees working collectively on one project. This will better approximate their future industry experience and will allow us to tackle more interesting projects.

For the spring term, this will be Jaeger-v2 project. For details and motivation of the project please refer to the main ticket
  * https://github.com/jaegertracing/jaeger/issues/4843

## Sub-projects for mentorship
While I don't have strong preference which part of jaeger-v2 overall roadmap will be completed during the mentorship, the LFX process requires to create three separate projects, so my proposal is to tackle these areas:

### P1: Build out full support in jaeger-v2 for all storage backends supported by jaeger-v1
* Currently only memory storage is wired in v2, we need to add Elasticsearch, Opensearch, Cassandra, Badger
* Extend existing integration tests to cover jaeger-v2 (in the style of [#4971](https://github.com/jaegertracing/jaeger/pull/4971))

### P2: Achieve observability parity between v1 and v2 (metrics, logs, traces)
* Currently jaeger-v2 components are initialized without observability clients
* We need to instantiate appropriate logging, tracing, and metrics clients and pass them to the components
* The existing code uses internal metrics API, which needs to be bridged to OTEL metrics to minimize code changes
* References
  * OTEL https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/observability.md
  * Internal metrics: https://github.com/jaegertracing/jaeger/blob/main/pkg/metrics/factory.go#L52

### P3: Support adaptive sampling
* Jaeger-v1 collector can serve sampling configuration to SDKs, and allows either static configuration (with hot reload) or adaptive sampling that continuously re-calculates the desired sampling probabilities.
* We need to enable all these capabilities in jaeger-v2
* Docs: https://www.jaegertracing.io/docs/1.52/sampling/#remote-sampling

## Application process
* For details about LFX mentorship & the application process, see https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship. 
* **Proposal required**: since we had a high number of applicants in the previous rounds, we strongly recommend submitting a proposal as part of your application. It helps us select mentees who are the best match for the project. Please see https://www.jaegertracing.io/mentorship-for-mentees/ regarding proposal details. 
  * LFX website does not allow uploading additional documents, so include the proposal in the Cover Letter.
* For deadlines, see https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/01-Mar-May
  * Mentee applications open between Monday Jan 29 - Tues Feb 13, 5:00 PM PDT
* Direct link to applying: https://mentorship.lfx.linuxfoundation.org/participate/mentee

## Getting Started
While the timelines in LFX programs are not very long, we recommend trying to [get your hand dirty with small contributions](https://www.jaegertracing.io/mentorship-for-mentees/#bootcamp) to the project before applying.

Reach out on [Slack](https://www.jaegertracing.io/get-in-touch/#via-chat) with other questions.

**Comment by Wise-Wizard** [comment]
The prospect of working collectively on a comprehensive project like Jaeger-v2 is truly exciting, and I am keen on contributing my skills and enthusiasm to its success. The outlined sub-projects align perfectly with my interests, and I believe they present a great opportunity for learning, growth and industrial exposure.
I am looking forward to the possibility of contributing to the Jaeger-v2 project and learning from the experience 🚀.

**Comment by yurishkuro** [comment]
@Wise-Wizard glad to hear. I wish LFX was more flexible in the setup - I _had_ to define 3 projects and when applying you _have to choose_ which one to apply, even though, as I mentioned, I don't particularly care if we work on these specific projects or just pick any other tasks from the V2 roadmap.

**Comment by octonawish-akcodes** [comment]
I am interested in working on this project too.

**Comment by Wise-Wizard** [comment]
> @Wise-Wizard glad to hear. I wish LFX was more flexible in the setup - I _had_ to define 3 projects and when applying you _have to choose_ which one to apply, even though, as I mentioned, I don't particularly care if we work on these specific projects or just pick any other tasks from the V2 roadmap.

Yes understandable, I will also study in depth about the projects and apply considerably, to learn and contribute more efficiently for the V2 project's success. Meanwhile, I will look into remaining issues that are leftover!

**Comment by shivam200446** [comment]
I am writing to express my excitement and gratitude for the upcoming mentorship during the 2024 Term 01. The prospect of being guided by someone of your caliber is truly inspiring, and I look forward to the growth and learning this experience will undoubtedly bring.

As we embark on this mentorship journey, I am eager to gain insights from your expertise and delve into the hands-on projects that will shape my understanding of the field. The anticipation of collaborating with like-minded peers and the expectation of a supportive learning environment have already fueled my enthusiasm.

I am confident that your mentorship will provide not only technical knowledge but also invaluable insights into the broader aspects of the industry. I appreciate the opportunity and am ready to make the most of this learning experience.

Thank you in advance for your guidance, and I look forward to the exciting and enriching journey ahead.

**Comment by Axkea** [comment]
Has the spring term been filled yet？

**Comment by Axkea** [comment]
I think I may have missed this opportunity, term2 to participate again

**Comment by haanhvu** [comment]
@Axkea Term 1 has not been filled yet. Actually it's not even opened yet...

Application will open soon (see the issue description for details). But it doesn't hurt to start preparing your application now. That will give you a fair advantage.

**Comment by Axkea** [comment]
> @Axkea Term 1 (Mar-May) has not been filled yet. Actually it's not even opened yet...
> 
> Application will open soon (see the issue description for details). But it doesn't hurt to start preparing your application now. That will give you a fair advantage.

Thank you for your answer, I mistakenly thought that the deadline for personal proposals was 24 January 2024

**Comment by haanhvu** [comment]
> Thank you for your answer, I mistakenly thought that the deadline for personal proposals was 24 January 2024

No worries this usually causes confusion... The first deadline is actually for mentors proposing project ideas to CNCF. After that will be mentee's application round (where you submit your proposal).

**Comment by 1awesomeJ** [comment]
I think this collaborative approach is awesome.

**Comment by prakrit55** [comment]
@yurishkuro, I am interested into it, and would like to get into further research to contribute to it.

**Comment by prakrit55** [comment]
By going thoroughly, with the ideas `Creating storage backends for V2 with opensearch, elasticsearch and others` is likely captivating me more. I would like to discuss it. How do I reach out to the members?

**Comment by yurishkuro** [comment]
you can ask here or on Slack (https://www.jaegertracing.io/get-in-touch/)

**Comment by verma-kunal** [comment]
Hey, project 2 i.e. "Achieve observability parity between v1 and v2 (metrics, logs, traces)" sounds interesting to me! I'll reach out on the slack channel & learn more about what needs to be done!
Thanks

**Comment by Pushkarm029** [comment]
adding support for Cassandra
