### ISSUE TITLE
[Bug] Flaky test: plugin/storage/badger/samplingstore

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5090]
Sporadically fails, e.g. I was able to reproduce with this:
```
$ go test -count 10 ./plugin/storage/badger/samplingstore
```

```
--- FAIL: TestGetThroughput (0.08s)
    storage_test.go:58:
        	Error Trace:	/Users/ysh/dev/jaegertracing/jaeger/plugin/storage/badger/samplingstore/storage_test.go:58
        	            				/Users/ysh/dev/jaegertracing/jaeger/plugin/storage/badger/samplingstore/storage_test.go:142
        	            				/Users/ysh/dev/jaegertracing/jaeger/plugin/storage/badger/samplingstore/storage_test.go:47
        	Error:      	Not equal:
        	            	expected: []*model.Throughput{(*model.Throughput)(0x14000092270), (*model.Throughput)(0x140000922a0)}
        	            	actual  : []*model.Throughput(nil)

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,15 +1,2 @@
        	            	-([]*model.Throughput) (len=2) {
        	            	- (*model.Throughput)({
        	            	-  Service: (string) (len=6) "my-svc",
        	            	-  Operation: (string) (len=2) "op",
        	            	-  Count: (int64) 0,
        	            	-  Probabilities: (map[string]struct {}) <nil>
        	            	- }),
        	            	- (*model.Throughput)({
        	            	-  Service: (string) (len=7) "our-svc",
        	            	-  Operation: (string) (len=3) "op2",
        	            	-  Count: (int64) 0,
        	            	-  Probabilities: (map[string]struct {}) <nil>
        	            	- })
        	            	-}
        	            	+([]*model.Throughput) <nil>

        	Test:       	TestGetThroughput
```

**Comment by akagami-harsh** [comment]
i'll look into it

**Comment by akagami-harsh** [comment]
does [this](https://github.com/akagami-harsh/jaeger/commit/ebb7a23ea1b7faf93391ad1b1a29eaf8b614f1c9) fixes the issue ?

**Comment by yurishkuro** [comment]
>does [this](https://github.com/akagami-harsh/jaeger/commit/ebb7a23ea1b7faf93391ad1b1a29eaf8b614f1c9) fixes the issue ?

I highly doubt it. What's wrong with that specific code? The issue with the test is most likely that it creates some non-deterministic test conditions that occasionally fail, not that the main logic is incorrect.

**Comment by akagami-harsh** [comment]
> I highly doubt it.

yeah, i was not very confident with it either.

>What's wrong with that specific code?  

`t.After(start)` was returning `false` occasionally, So i thought removing it could solve it. now on researching more i found out it could start other potential issues

**Comment by akagami-harsh** [comment]
![image](https://github.com/jaegertracing/jaeger/assets/122517264/307713af-dead-442e-80a0-9698cc6317a5)


![image](https://github.com/jaegertracing/jaeger/assets/122517264/55284297-65ab-4c35-a33c-904112859b32)

**Comment by yurishkuro** [comment]
please do. Also provide explanation why you think this this is good, i.e. what happens if the fix is not there that causes the test to fail. And please do not use sleep - if you need to wait for background activity to happen, then use assert.Eventually with small deltas and a longer timeout, this ensures that the tests are not slowed down unnecessarily.

**Comment by akagami-harsh** [comment]
`Truncate(time.Millisecond)` adjusts the time by removing any fractional parts smaller than a millisecond, effectively rounding it down to the nearest millisecond. If the test uses `time.Now()` without truncating, it includes nanoseconds, which might not be stored or retrieved with the same precision in BadgerDB. By truncating to milliseconds, it ensure that the precision used in the test matches the precision stored in the database.  i initially tried using `Truncate(time.Millisecond)` but is didn't work.

And about that `time.Sleep` turns out it works fine without it.
