### ISSUE TITLE
[Bug]: failed to parse field [duration] of type [long] in document

### ISSUE THREAD

**Issue by lt2865** [jaegertracing/jaeger#5110]
### What happened?

Upgraded to 7.17.16 of Elasticsearch from 7.16.3 and version 1.53.0 of Jaeger from 1.31.0 and since then I have been seeing the following error spammed in the logs for the container running jaeger-collector:

`{"level":"error","ts":1705412527.9303505,"caller":"config/config.go:134","msg":"Elasticsearch part of bulk request failed","map-key":"index","response":{"_index":"jaeger-span-2024-01-16","_type":"_doc","_id":"{{ ID }}","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [duration] of type [long] in document with id '{{ ID }}'. Preview of field's value: '18446744073709549616'","caused_by":{"reason":"Numeric value (18446744073709549616) out of range of long (-9223372036854775808 - 9223372036854775807)\n at [Source: (ByteArrayInputStream); line: 1, column: 225]","type":"input_coercion_exception"}}},"stacktrace":"github.com/jaegertracing/jaeger/pkg/es/config.NewClient.func2\n\tgithub.com/jaegertracing/jaeger/pkg/es/config/config.go:134\ngithub.com/olivere/elastic.(*bulkWorker).commit\n\tgithub.com/olivere/elastic@v6.2.37+incompatible/bulk_processor.go:588\ngithub.com/olivere/elastic.(*bulkWorker).work\n\tgithub.com/olivere/elastic@v6.2.37+incompatible/bulk_processor.go:501"}`

So I was trying to find the json file mentioned [here](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/es/mappings/jaeger-span-7.json) where the Jaeger span mappings are defined to try and change the field type there to see if that would fix the issue. However, I can't seem to find this file or even sure if I have access to the file in order to change these properties.

Was wondering if anyone has come across this before and if so what is a suitable fix for this as I can't really upgrade to 8.x versions and didn't see this happen prior to upgrading it. Have tried removing the index that is generated with the date stamp but it still occurs when data is sent and the index is generated again. 

Apologies if this has already been asked somewhere before. Thanks.

### Steps to reproduce

1. Upgrade elasticsearch to 7.17.16 from 7.16.3
2. Upgrade Jaeger-collector to 1.53.0 from 1.31.0

### Expected behavior

Wouldn't expect to see these errors as I didn't have an issue with this prior to upgrading and no changes in data as far as I'm aware

### Jaeger backend version

1.53.0

### Stogage backend

Elasticsearch 7.17.16

### Operating system

Linux

### Deployment model

Docker

**Comment by lt2865** [comment]
Yes I'm confused as to why this duration has been produced as before the upgrade events like these didn't occur so wasn't sure if it was a bug with this version or something else. Looks like it might be related to [this](https://github.com/jaegertracing/jaeger/issues/2517) issue but not sure if an actual fix was put in place to fix this or where I would need to go to make the change mentioned manually. Thanks. Apologies I'm quite new to Jaeger.

**Comment by yurishkuro** [comment]
Yeah, looks like the same issue. I will close this as duplicate. The other one was never resolved, even though in the discussion the approach was identified.
