### ISSUE TITLE
ThriftSender received a span that was too large

### ISSUE THREAD

**Issue by akash-wadhwa** [jaegertracing/jaeger#5111]
### What happened?

I am using image jaegertracing/all-in-one:1.53 and it is throwing "io.jaegertracing.internal.exceptions.SenderException: ThriftSender received a span that was too large, size = 518341, max = 64811" when span size is more than 64811

### Steps to reproduce

1. Run the container as:
docker run -d --name jaeger -p 6831:6831/udp -p 6832:6832/udp -p 16686:16686 -p 14268:14268 jaegertracing/all-in-one:1.53 --processor.jaeger-binary.server-max-packet-size=5242880  --processor.zipkin-compact.server-max-packet-size=5242880  --processor.jaeger-compact.server-max-packet-size=5242880  --collector.grpc-server.max-message-size=5242880  --collector.otlp.grpc.max-message-size=5242880

2. Add jaeager dependency in spring boot application
        io.opentracing.contrib.opentracing-spring-jaeger-cloud-starter:3.3.1
3. Add opentracing.jaeger.http-sender.url = http://localhost:14268/api/traces in application.properties
4. Hit some api which will create a log bigger than 64811 bytes

### Expected behavior

Jaeger should respect the server-max-packet-size and max-message-size provided as args and should not throw an exception for span size

### Relevant log output

```shell
io.jaegertracing.internal.exceptions.SenderException: ThriftSender received a span that was too large, size = 518341, max = 64811
	at io.jaegertracing.thrift.internal.senders.ThriftSender.append(ThriftSender.java:57) ~[jaeger-thrift-1.3.2.jar:1.3.2]
	at io.jaegertracing.internal.reporters.RemoteReporter$AppendCommand.execute(RemoteReporter.java:143) ~[jaeger-core-1.3.2.jar:1.3.2]
	at io.jaegertracing.internal.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:182) ~[jaeger-core-1.3.2.jar:1.3.2]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

### Jaeger backend version

1.53

### Stogage backend

badger

### Deployment model

Docker

**Comment by yurishkuro** [comment]
This will not be address.
* Jaeger SDKs are deprecated
* Jaeger agent is deprecated
* UDP transport is deprecated
* UDP transport is intentionally limited to 65K to avoid fragmentation and complications with re-assembly

**Comment by akash-wadhwa** [comment]
@yurishkuro I am using HTTP for transport. Is the 65K limit applicable to HTTP as well? If yes, then why is it mentioned in the documentation that the limit can be modified by passing appropriate CLI flags

**Comment by yurishkuro** [comment]
> I am using HTTP for transport

that's not what your examples show.
