### ISSUE TITLE
Upgrade OpenTelemetry SDK to v1.22.0

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5116]
The dependabot upgrade is failing tests #5115. 
* Use `gh` cli to download it : `gh pr checkout 5115`
* Reproduce
* Find a fix for the issue
* Create a branch from that PR and submit a new PR

**Comment by officialasishkumar** [comment]
I would like to work on this issue

**Comment by pash415** [comment]
Me too!
