### ISSUE TITLE
[Bug]: The CHILD_OF span reference is moved to the second place incorrectly

### ISSUE THREAD

**Issue by sherwoodwang** [jaegertracing/jaeger#5122]
### What happened?

When the first span reference is typed as 'CHILD_OF' and other references are 'FOLLOWS_FROM' with the same trace id, the first 'CHILD_OF' span referenced is swapped to the second place.

### Steps to reproduce

Create a span with 2 references. The first is a 'CHILD_OF' reference. The second is a 'FOLLOWS_FROM' reference. Both of them point to spans of the same trace id with the referencing one.

### Expected behavior

The order should be unchanged.

**Comment by yurishkuro** [comment]
Could you explain what made you investigate, what user-facing problem this was causing?
