### ISSUE TITLE
[fix] Ensure Kafka broker is started before running integration tests

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5148]
Kafka integration tests started failing frequently. I suspect our `scripts/kafka-integration-test.sh` script is not waiting until Kafka is properly started. We need to find a more reliable check.

There are a bunch of scripts available in the container:
```
docker run -it --rm bitnami/kafka:3.6.0 /bin/sh
$ ls -lF /opt/bitnami/kafka/bin/
```
We can probably use one of them to more reliably check for running server, e.g. `kafka-topics.sh` or `kafka-broker-api-versions.sh`, or even read & write a test message via `kafka-console-producer.sh` and `kafka-console-consumer.sh`.

Some documentation on how to run the container is available from bitnami: https://github.com/bitnami/containers/tree/main/bitnami/kafka#how-to-use-this-image

**Comment by 7h3-3mp7y-m4n** [comment]
can I take this issue?

**Comment by yurishkuro** [comment]
Feel free

**Comment by 7h3-3mp7y-m4n** [comment]
Okay @yurishkuro  :)
