### ISSUE TITLE
[Feature]: add organization and user management

### ISSUE THREAD

**Issue by KaymeKaydex** [jaegertracing/jaeger#5159]
### Requirement

In the case of using jaeger by several teams, for information security purposes it is necessary to raise either several jaegers or use some multi-tenant approaches described on the network, I suggest adding role separation in the same way as is provided, for example, in sentry

### Problem

Nowadays it is quite difficult to have a unified tracing storage system while maintaining security requirements and separating tracing from different teams

**Comment by yurishkuro** [comment]
We have some level of multi-tenancy support, see #3881

**Comment by KaymeKaydex** [comment]
> We have some level of multi-tenancy support, see #3881

wow, this looks really cool, I'll try to look into it

**Comment by KaymeKaydex** [comment]
looks like one of the problems described in the release above
