### ISSUE TITLE
[Deprecation] Drop support for Cassandra 3.x

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5160]
3.x is declared EOL https://cassandra.apache.org/_/blog/Apache-Cassandra-3.0.x-and-3.11.x-End-of-Life-Announcement.html

According to https://cassandra.apache.org/_/download.html, support for it will end once 5.x is released, which was aimed ad Dec'23, but as of 2023-12-05 only 5-Beta was released. In any case, I expect by summer 2024 the 3.x support will end, and we should remove it from Jaeger as well.

This doesn't remove any implementation, only the CI testing can drop testing with 3.x (and we should add testing with 5.x. once it is released).

**Comment by varshith257** [comment]
It seems Cassandra 5.0 had released. Am I right @yurishkuro ?

**Comment by yurishkuro** [comment]
do you have a link?

**Comment by yurishkuro** [comment]
I don't see much change: Apache Cassandra 5.0-beta  Latest release on 2023-12-05

I.e. no official release.

**Comment by yurishkuro** [comment]
🎉
