### ISSUE TITLE
[Feature]: Print fullly resolved config

### ISSUE THREAD

**Issue by gmandrade21** [jaegertracing/jaeger#5168]
### Requirement

See all configurations in Jaeger. Example:
Today we have the Prometheus metrics jaeger_collector_queue_capacity, where we can find the value of our capacity. We need to see all of our variables and parameters like METRICS_STORAGE_TYPE, JAEGER_REPORTER_LOG_SPANS, COLLECTOR_NUM_WORKERS, etc

### Problem

We can't see if the environment variables is actually working, we change those guys and work very well in our environment, but,  if we forgot to change a single node in those parameters we don't have visibility

### Proposal

Transform all environment variables in metrics and add a CLI command to show the default value and the actual value

**Comment by yurishkuro** [comment]
We could add a new CLI subcommand to print the config. The cobra/viper libraries already provide access to a resolved Config object, it's possible they have a way to iterate through it and print a combined configuration.

One concern with printing config is that it would also print any secrets / passwords provided, but imo the user running the command would already need to have access to them in the first place, so the risk is only if they try to share that printed config.

**Comment by gmafrac** [comment]
I would like to take this issue

**Comment by gmafrac** [comment]
Hi @gmandrade21 and @yurishkuro , I'm a beginner contributor and this is my first problem. I've been introducing myself to the project over the last few days but I still have a few doubts about this issue:

- How could I turn environment variables into metrics?  

- I didn't quite understand about showing the default value and the current value, could you explain it better? 

Thanks for the attention! 🙂

**Comment by yurishkuro** [comment]
@gmafrac sorry, I don't understand your questions.

The problem here is if you run a program with `SOME_ENV_VAR=xyz my-program ...`, how do you know what effect `SOME_ENV_VAR` had, whether it was used by the program or ignored and some default value was used instead. So if we allow a `print-config` subcommand, the user can validate that the final resolved configuration is used by the program.

**Comment by gmafrac** [comment]
Thanks for the explanation! I've done a PR and I'm waiting for feedback.

**Comment by pavolloffay** [comment]
Is this done?

**Comment by varshith257** [comment]
@pavolloffay I think it's done PR got merged. we can close this issue
