### ISSUE TITLE
Upgrade to latest OpenTelemetry Collector version

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5181]
Dependabot tried (#5177) to upgrade to v0.94 and there are some breaking changes that require minor code changes in Jaeger.

Best way to pick this up:
* fork jaeger repo 
* `gh pr checkout 5177`
* `git checkout -b fix-5177`
* make changes until `make test` succeeds
* create new PR

**Comment by shashank-iitbhu** [comment]
Hey! @yurishkuro , just opened a PR #5182 for this issue. Please review.
