### ISSUE TITLE
Bring code coverage back to 95%

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5194]
Oddly enough, an upgrade to Go 1.22 (#5180) resulted in almost 2% drop in code coverage.

The delta can be seen here: https://app.codecov.io/gh/jaegertracing/jaeger/commit/5bc6b50c6d3135acbec7a23bd492c743782dda80/indirect-changes

One of the big contributors to low coverage seems to be `./plugin/storage/grpc/shared`, where some of the methods are trivially testable.

**Comment by prakrit55** [comment]
i will take this up

**Comment by varshith257** [comment]
@yurishkuro Is this issue resolved?

**Comment by yurishkuro** [comment]
yes, but we need to bump the threshold back to 95 in `.codecov.yml`

**Comment by varshith257** [comment]
In readme it's showing 95

**Comment by yurishkuro** [comment]
I am referring to this: https://github.com/jaegertracing/jaeger/blob/14cbceabe734bad92599af54d853f1f4edc094df/.codecov.yml#L26-L28

**Comment by varshith257** [comment]
Ok, will work on it and submit PR
