### ISSUE TITLE
Extract archive storage integration test from ES and generalize to all storage backends

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5203]
I just noticed, to my surprise, that archiving test is only implemented in the ES integration tests

https://github.com/jaegertracing/jaeger/blob/8ae2e05878a1ab38509e6678f6336b6947c9faba/plugin/storage/integration/elasticsearch_test.go#L295

## Objective
* Extract this test into the shared test suite
* Make sure it works with the backends that support archiving (which may be all of them at this point)

**Comment by Wise-Wizard** [comment]
Should I create a new test file under integration itself, to test archiving for all Backends? Or can I just add the tests to the pre-existing test files for each storage?

**Comment by yurishkuro** [comment]
we already have integration.go as the shared framework for all backends, it should go there

**Comment by Wise-Wizard** [comment]
Hi, I believe the Archive Trace test functionality is only remaining for Cassandra and Badger after my PR. Should I continue working on them and close this issue?

**Comment by Wise-Wizard** [comment]
@yurishkuro, may I pick up on this?
