### ISSUE TITLE
jaeger search result is unusual

### ISSUE THREAD

**Issue by molon** [jaegertracing/jaeger#522]
![snapshot](https://user-images.githubusercontent.com/3739161/32592952-8b17c008-c4eb-11e7-9095-ed347df7251f.gif)

According the gif upon.
We can see the trace time of results change often.
So the result would lose some traces sometimes.
But We want to see the nearest traces timely.
And I ensure that there is no more trace produce (beacuse this is just a test env).

I think it's strange~

**Comment by lapointexavier** [comment]
I observed that running the all-in-one ✋ Is it expected since it's meant to be more of a temporary / development solution?

**Comment by black-adder** [comment]
Looks related to: https://github.com/jaegertracing/jaeger-ui/issues/57

@molon if you increase the "Limit Results" to something like 1000 and repeat this, do you see the same thing happening?

**Comment by molon** [comment]
@black-adder Thanks  for reply.

https://github.com/jaegertracing/jaeger-ui/issues/57
> I see - the memstore implementation likely doesn't provide stable search, because it uses hash maps internally. It's doable, but doesn't seem too important.

This is the problem. :)
