### ISSUE TITLE
[jaeger-v2] Do away with storage.ArchiveFactory

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5230]
Per comment https://github.com/jaegertracing/jaeger/pull/5152/files#r1501916983

We need to get rid of `storage.ArchiveFactory` interface because it is conceptually meaningless - archive storage is just a storage that implements SpanStorage interface. It should be the same thing with Factory, just have a `storage.Factory` that in context can be interpreted as primary or archive. We unnecessarily bundle these two.

**Comment by h4shk4t** [comment]
I would like to work on this.

**Comment by Wise-Wizard** [comment]
Can I work on this issue?

**Comment by Wise-Wizard** [comment]
Can I work on this issue?

**Comment by yurishkuro** [comment]
I am gonna close this as I don't think it's necessary given how v2 storage is evolving. @james-ryans is working on defining a new storage APIs for v2 where there won't be archive storage as an explicit interface.
