### ISSUE TITLE
Is dependence data is not writed when use es/cassendra as storage?

### ISSUE THREAD

**Issue by ianwoolf** [jaegertracing/jaeger#524]
I use es as storage. I found the WriteDependencies() is only defined but not used by any handler or process. So i generate dependence data from trace as it generated as memory storage way.

Do i miss something or have some mistake?

Does the roadmap has write dependences plan? Or it can generate as memory storage way whatever the storage is?

**Comment by objectiser** [comment]
When using in-memory storage (i.e. the all-in-one image) it derives the dependencies. However when using the components separately with storage (cassandra or ES), you need to use the separate https://github.com/jaegertracing/spark-dependencies component to process the dependencies.

**Comment by pavolloffay** [comment]
@ianwoolf this is also described in docs http://jaeger.readthedocs.io/en/latest/deployment/#aggregation-jobs-for-service-dependencies
