### ISSUE TITLE
Jaeger's LFX Mentorship - Term 02 - 2024 June - August

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5240]
Timeline: https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/02-Jun-Aug
  * [x] Mentee applications due Tues May 28, 5:00 PM PDT
  * [x] Admission decisions due by Tues June 11, 5:00 PM PDT
  * [x] Selection notification by Tues June 12, 5:00 PM PDT

Three projects are proposed for the summer term -- https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/02-Jun-Aug#jaeger:
  * Jaeger-V2 Observability and Healthchecks #5633
  * Jaeger-V2 Service Performance Monitoring #5632
  * Jaeger-V2 Kafka-based architecture #4868

Parent / background issue: #4843

## Application process
* For details about LFX mentorship & the application process, see https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship. 
* **Proposal required**: since we had a high number of applicants in the previous rounds, we strongly recommend submitting a proposal as part of your application. It helps us select mentees who are the best match for the project. Please see https://www.jaegertracing.io/mentorship-for-mentees/ regarding proposal details. 
  * LFX website does not allow uploading additional documents, so include the proposal in the Cover Letter.
* For deadlines, see https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/02-Jun-Aug
  * Mentee applications due Tues May 28, 5:00 PM PDT
* Direct link to applying: https://mentorship.lfx.linuxfoundation.org/participate/mentee

## Getting Started
While the timelines in LFX programs are not very long, we recommend trying to [get your hand dirty with small contributions](https://www.jaegertracing.io/mentorship-for-mentees/#bootcamp) to the project before applying.

Reach out on [Slack](https://www.jaegertracing.io/get-in-touch/#via-chat) with other questions.

**Comment by varshith257** [comment]
@yurishkuro I think we can add **Support ClickHouse storage in Jaeger V2**  to LFX Term 02 and also any missing works in our V2 roadmap

**Comment by varshith257** [comment]
Why can't we add the proposed projects in LFX 2023 Term 03. I seen there are many projects have been proposed and selected three among them - #4457

**Comment by manulpatel** [comment]
Hello @yurishkuro! Will Jaeger be participating in the LFX Mentorship Term 2 2024 (June-Aug)? I am interested in being a mentee and contributing to the Jaeger community and eagerly waiting for the project ideas.

**Comment by yurishkuro** [comment]
@varshith257 I would like the mentorships laser-focused on Jaeger V2 work, not on side projects.

**Comment by varshith257** [comment]
Yes, but it seems most of our goals in roadmap of V2 are ongoing. I thought there are few works left in our v2 roadmap:)

**Comment by yurishkuro** [comment]
The summer projects have been proposed, see main issue description.

**Comment by Wise-Wizard** [comment]
I would like to try again for the Observability issue, as it was already there in the spring term, and I am quite familiar with it!

**Comment by nikzayn** [comment]
Hey @yurishkuro, I have participated in the same in the LFX mentorship program. I have chosen the Kafka-based architecture enhancement as my summer mentorship. Thanks!!

**Comment by yurishkuro** [comment]
added Application Process section.

**Comment by vermaaatul07** [comment]
Hi @yurishkuro , i like the Jaeger-V2 Observability and Healthchecks project and will be working on it for the LFX term 2
