### ISSUE TITLE
[jaeger-v2] Build jaeger-remote-storage for gRPC integration test

### ISSUE THREAD

**Issue by james-ryans** [jaegertracing/jaeger#5266]
### Requirement

The current jaeger-v2 gRPC integration test script at #5259 uses the published `jaegertracing/jaeger-remote-storage` image and runs the latest version at CIT gRPC (v2) CI. Instead, we want to run remote storage with the code built with THIS version of the repo, not some other version (or even latest).

### Problem

This way, we can be notified directly by the CI when the remote storage changes and fails when integrated with jaeger-v2 storage extension. The problem with the current script is that we will only receive notification of the failed CIT gRPC (v2) CI on the next issued PR after the remote storage has been published, since it uses the latest published version.

**Comment by varshith257** [comment]
@yurishkuro @james-ryans I didn't find any in grpc.yml in #5259 that v1 using registry published image. Can clarify this?

1. If needed we use the published image for v1 gRPC integration test
2. For v2, we build docker image in using which is in the current github repo.

**Comment by varshith257** [comment]
@james-ryans The solution proposed in the issue is to update the test script to build the Jaeger-remote-storage image locally from the current version of the repository.

**Comment by james-ryans** [comment]
> @james-ryans The solution proposed in the issue is to update the test script to build the Jaeger-remote-storage image locally from the current version of the repository.

There's no need to update the v1 one since it already builds the binary directly when `make grpc-storage-integration-test` is called. We just need to change the v2 test script.

**Comment by james-ryans** [comment]
This issue is not relevant anymore. The solution #5259 PR offers is replaced with the new #5322 PR that solves the requirements stated here https://github.com/jaegertracing/jaeger/issues/5254#issuecomment-2016858385.
