### ISSUE TITLE
Create GitHub Action to block PRs from ${fork}/main branch

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5271]
Making PR changes on the `main` branch of a fork is a bad practice, and breaks some of our workflows that check if the current branch is `main` before doing certain steps (like trying to push to Docker).

We should set up a new workflow that will fail if the PR is submitted from `main` branch. This workflow should be added to jearger/jarger-ui/documentation repositories (perhaps we need a reusable action - only if the check logic is reasonably complex).
  * [x] Define workflow (and reusable action if necessary) in `jaeger` repo
  * [x] Add similar workflow to `jaeger-ui` repo
  * [ ] Add similar workflow to `documentation` repo

**Comment by varshith257** [comment]
@yurishkuro Can I start working there for this:

- [ ]  Add similar workflow to jaeger-ui repo
- [ ]  Add similar workflow to documentation repo

**Comment by yurishkuro** [comment]
Yes thank

**Comment by yurishkuro** [comment]
Thanks!
