### ISSUE TITLE
Jaeger Service Name Missing in Jaeger-Services-XXXXXX index

### ISSUE THREAD

**Issue by Ahsan-Aziz-Ishan** [jaegertracing/jaeger#5284]
### What happened?

Even If missing service name is not created in jaeger-service-write index.

### Steps to reproduce

1. Enable use alias
2. Remove service index
3. Spans will be stored but can not be seen from Jaeger UI

### Expected behavior

Create Service Name again if missing

### Jaeger backend version

v1.17.0

**Comment by yurishkuro** [comment]
not enough information
