### ISSUE TITLE
#coop-mode for jaeger

### ISSUE THREAD

**Issue by hh** [jaegertracing/jaeger#5285]
Met with @jkowall at Paris Kubecon.
Going to try to setup a gist for creating a jaeger onboarding.

Tracking issue.

**Comment by varshith257** [comment]
@hh The issue isn't clear and can't get what you are intending.Please fill detailed issue

**Comment by jkowall** [comment]
@varshith257 I am handling this one in person tomorrow with him at Kubecon, he just wanted a tracking issue. I have updated/assigned it. Thank you.

**Comment by manishramanandi** [comment]
hey can i contribute?

**Comment by yurishkuro** [comment]
@jkowall what is this about? There is no context.
