### ISSUE TITLE
How to trace a go-lang app running in a docker image with the jaeger all-in-one docker image

### ISSUE THREAD

**Issue by ps-stevesheldon** [jaegertracing/jaeger#529]
Hey Guys,

I was hoping somebody might help me figure out how this should work...

- I am starting the jaeger all in one docker image to test as follows:

```
docker run -d -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp \
  -p5778:5778 -p16686:16686 -p14268:14268 -p9411:9411 jaegertracing/all-in-one:latest
```

- I have an application I have written in GO which uses https://github.com/jaegertracing/jaeger-client-go

This is all working great, nicely done. However if my application is packaged into a docker image, it stops working since the agent can no longer be reached. How do you go about handling this correctly? I wondered if configuring a bridge network in docker might work but from what I can tell the jaeger go client doesn't seem to allow for a host to be set.

Thanks for any help,
Steve

**Comment by black-adder** [comment]
[This](https://github.com/jaegertracing/jaeger-client-go/blob/b7bacc465f385658dd3586f58810226776d2a4bf/config/config.go#L88) allows you to configure the host port for the agent. (although localAgentHostPort might be a misnomer if you have the agent not running locally)

**Comment by ps-stevesheldon** [comment]
Appreciated, is that just the port or can you put the address:port?

**Comment by black-adder** [comment]
address:port will work

**Comment by pavolloffay** [comment]
Hi @ps-stevesheldon you have two options:

* send data to agent via UDP. Preferably the agent should be running inside the container as a sidecar. You can also use our docker-copose and just configure the host and port in the tracer e.g. `jaeger-agent:6831`
* send data to jaeger-collector via HTTP https://github.com/jaegertracing/jaeger-client-go/blob/master/transport/http.go.

**Comment by sawansharma005** [comment]
Hi,

Is this issue solved, I am also facing the same thing. 
- could anyone help as I tried the above but not able to succeed.

**Comment by yurishkuro** [comment]
Please try https://www.jaegertracing.io/docs/latest/troubleshooting/
