### ISSUE TITLE
[Bug]: The results filtered through the tag in the `findtrace` page did not match expectations

### ISSUE THREAD

**Issue by JaredTan95** [jaegertracing/jaeger#5290]
### What happened?

No data is found when filtering traces through the following tag：

`http.url=http://sss.xxx.com/v1/user/spaces/1310e65f-16c6-4502-a9ef-15e0ff38e8b2/zone_roles?service_name=ss.sss.xxx.com`, 

Is it because the value contains the special symbol `=` at the end? Because passing the following query is normal：

`http.url=http://sss.xxx.com/v2/healthchaeck`

### Steps to reproduce

Filter traces data through the following tags：

`http.url=http://sss.xxx.com/v1/user/spaces/1310e65f-16c6-4502-a9ef-15e0ff38e8b2/zone_roles?service_name=ss.sss.xxx.com`,

### Expected behavior

Filter out the data correctly

### Screenshot

<img width="1386" alt="image" src="https://github.com/jaegertracing/jaeger/assets/12468337/475e6e4b-8cf4-4adb-958e-36a5309dc7ee">

<img width="1143" alt="image" src="https://github.com/jaegertracing/jaeger/assets/12468337/ebdba8dd-853c-42fb-a1ec-ac1cd7efa15e">

### Jaeger backend version

1.49.0

**Comment by yurishkuro** [comment]
did you try the advice in the tooltip?

<img width="1047" alt="image" src="https://github.com/jaegertracing/jaeger/assets/3523016/6f4e65c3-bb5d-4c22-bb2c-fe0e5f2346ad">

(the tooltip has a typo, I put a fix https://github.com/jaegertracing/jaeger-ui/pull/2224)

**Comment by JaredTan95** [comment]
Thank you for your reply. 
I used `'` to wrap `=` like `'='`  for query according to what you said. Unfortunately,  still failed to filter out the data:

`http.url=http://sss.xxx.com/v1/user/spaces/1310e65f-16c6-4502-a9ef-15e0ff38e8b2/zone_roles?service_name'='ss.sss.xxx.com`

**Comment by jkowall** [comment]
@JaredTan95 What is the backend you are using?

**Comment by JaredTan95** [comment]
> @JaredTan95 What is the backend you are using?

- jaeger 1.49.0
- jaeger ui 1.33.o

**Comment by yurishkuro** [comment]
quotes around the value: `http.url="http://sss.xxx.com/v1/user/spaces/1310e65f-16c6-4502-a9ef-15e0ff38e8b2/zone_roles?service_name=ss.sss.xxx.com"`

**Comment by JaredTan95** [comment]
> quotes around the value: `http.url="http://sss.xxx.com/v1/user/spaces/1310e65f-16c6-4502-a9ef-15e0ff38e8b2/zone_roles?service_name=ss.sss.xxx.com"`

Thank you for your reply, but according to your reply, it is still not effective

**Comment by yurishkuro** [comment]
Works for me in the HotROD demo (with memstore)

<img width="1478" alt="image" src="https://github.com/jaegertracing/jaeger/assets/3523016/b70f981f-46f3-4deb-8c12-5875231bdcf1">

**Comment by my-git9** [comment]
There is also a problem in my environment:

<img width="986" alt="image" src="https://github.com/jaegertracing/jaeger/assets/76980726/b5f9d451-0d00-445b-a1f5-4f742206844c">

<img width="1073" alt="image" src="https://github.com/jaegertracing/jaeger/assets/76980726/e6e3ad2b-177b-4e15-81b5-a55d3d7d57c3">

<img width="1416" alt="image" src="https://github.com/jaegertracing/jaeger/assets/76980726/12cf8d9c-c9ef-4fdf-bc91-0e044391867f">


The version information is:

<img width="213" alt="image" src="https://github.com/jaegertracing/jaeger/assets/76980726/b329b8f1-f4a0-424c-9c38-48f15a8e6154">

**Comment by yurishkuro** [comment]
Which storage backend?

**Comment by scx1st** [comment]
> Which storage backend?

ES

**Comment by yurishkuro** [comment]
I figured it out. The ES tag queries are considered regex queries. So it's not the `=` sign that trips the search, it's the `?`.

Here is example where the search fails:
<img width="1915" alt="image" src="https://github.com/jaegertracing/jaeger/assets/3523016/e4c4eadb-aafb-4080-a38d-1f134546541a">

And here's example where it succeeds, after adding an escape character `\\` in front of `?`

<img width="1912" alt="image" src="https://github.com/jaegertracing/jaeger/assets/3523016/64a3dfdb-f794-45bc-8e8f-38c58e33cd2e">

This is actually documented in the help popup:

<img width="1046" alt="image" src="https://github.com/jaegertracing/jaeger/assets/3523016/08ad709e-4bf4-4c45-a594-2ec696b74113">

**Comment by JaredTan95** [comment]
Thanks a lot, It works~
