### ISSUE TITLE
Fix breaking changes in upgrading OTEL Collector

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5302]
PR #5301. Looks like breaking changes in the collector.

One of the errors: `Error: ../../../go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver@v0.96.0/trace_receiver.go:61:25: undefined: component.ErrNilNextConsumer`

**Comment by Mona3087** [comment]
I am interested to pick this up

**Comment by lekaf974** [comment]
There was a braking change in this PR https://github.com/open-telemetry/opentelemetry-collector/issues/9322 which looks to be fix by this one https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31793

should be fix by upgrading `opentelemetry-collector-contrib` to v0.97.0
