### ISSUE TITLE
[Refactor]: Remove the use of channels to signal healthcheck status

### ISSUE THREAD

**Issue by WillSewell** [jaegertracing/jaeger#5307]
### Requirement

As a contributor who has been attempting to fix goroutine leaks in tests it would be easier to manage gorotoutine cleanup on server close if healthcheck reporting between the server and service did not rely on channels.

### Problem

As discussed in https://github.com/jaegertracing/jaeger/pull/5299/files#diff-b4a37944a109260d3630b973cdae2dc012d6bc67134efa50397976f713630e08, a significant source of complexity and risk of deadlocks comes from the use of a channel to signal server healthcheck status back to the server.

### Proposal

Instead of using a channel, `pkg/healthcheck` is already thread safe, and we currently don't have any need for components to "subscribe" to healthcheck status, so instead of writing to a channel and having a consumer update the `pkg/healthcheck`, I think we could just update the state from the server directly.

### Open questions

I'm not sure whether we should completely decouple the server from the healthcheck package, by passing in a callback to update healthcheck status. The alternative would be to just pass a `*healthcheck.Healthcheck` directly to the server.

Pros of callback: gives the caller more control - e.g. they could use a channel if they wanted to
Cons: inconsistent with how the `*healthcheck.Healthcheck` is passed directly to the collector component (example), I also think it's a bit more complex due to indirection.

Currently I'm leaning towards passing a `*healthcheck.Healthcheck` because there's currently no need for anything more flexible - e.g. the ability to subscribe to changes - and I think if this ever was required it's something that could be built into the healthcheck package.

**Comment by WillSewell** [comment]
I took the "pass directly" approach here: https://github.com/jaegertracing/jaeger/pull/5308. Interested to get your thoughts @yurishkuro as it's a bit different to the callback approach you mentioned.

**Comment by yurishkuro** [comment]
passing directly is ok. The alternative would be to just pass the function `hc.Set` so that other components would only be exposed to the function signature, not to the whole HC class. That's exactly what OTEL status reporting mechanism does.
