### ISSUE TITLE
Update GOVERNANCE with public voting

### ISSUE THREAD

**Issue by caniszczyk** [jaegertracing/jaeger#531]
Great to see initial governance defined!

One quick modification suggestion... I'd recommend that:

> A new maintainer must be proposed by an existing maintainer by sending an email to jaeger-maintainers@lists.cncf.io

This be changed to be done on the public list or via GitHub issue:
https://groups.google.com/forum/#!forum/jaeger-tracing

It's important that voting/nomination be done in a public way. This is better than say how it's done in the ASF and other foundations.

**Comment by yurishkuro** [comment]
let's take a vote on that!  @jaegertracing/jaeger-maintainers

**Comment by black-adder** [comment]
public sgtm

**Comment by pavolloffay** [comment]
+1 on public

**Comment by yurishkuro** [comment]
+1, which makes it over 2/3.
