### ISSUE TITLE
Update README with bi-weekly call information

### ISSUE THREAD

**Issue by caniszczyk** [jaegertracing/jaeger#532]
https://groups.google.com/forum/#!topic/jaeger-tracing/9BbiHUI0H_Q

This should be in a readme section somewhere on how to get involved :)

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/jaeger#project-status-bi-weekly-meeting
https://github.com/jaegertracing/jaeger#questions-discussions-bug-reports

**Comment by yurishkuro** [comment]
@caniszczyk closing, unless you think it needs something else.
