### ISSUE TITLE
es.SamplingStore.CreateTemplates is never called

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5333]
In case of Span Storage the templates are created when SpanWriter is instantiated. Sampling templates could be created when SamplingStore is being created. Right now the method exists but is never called, except from the integration test.

**Comment by Adarsh-jaiss** [comment]
- Hey @yurishkuro , I want to work on this issue, can you please elaborate the issue or provide me any reference to read and fix this issue :)

**Comment by h4shk4t** [comment]
Hi @yurishkuro I would like to work on this issue
