### ISSUE TITLE
[jaeger-v2]: Remove SkipBinaryAttrs flag from storage integration

### ISSUE THREAD

**Issue by james-ryans** [jaegertracing/jaeger#5341]
### Requirement

As a contributor, I want to remove the `SkipBinaryAttrs` flag from storage integration test that was temporarily added to bypass the issue sourced from upstream dependency. Marked with this comment https://github.com/jaegertracing/jaeger/pull/5322#discussion_r1556346781.

### Problem

The `SkipBinaryAttrs` flag was added to bypass upstream issue because OTEL `pkg/translator/jaeger` has a bug that converts Jaeger proto BINARY type tags into OTLP STRING type but remains in STRING type when converted back into Jaeger proto.

### Proposal

Remove `SkipBinaryAttrs` flag from storage integration test once the issue at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32208 has been resolved.

**Comment by prakrit55** [comment]
hey @james-ryans. @yurishkuro I would like to work on it

**Comment by james-ryans** [comment]
Hi @prakrit55, actually we have an ongoing PR for this at #5436.
