### ISSUE TITLE
[Feature]: Data Retention Policies / Cleaner for Jaeger with Cassandra Configured

### ISSUE THREAD

**Issue by talitz** [jaegertracing/jaeger#5354]
### Requirement

I'd like to have data retention policies / cleaner for cassandra as well (there is a cleaner for elastic search available to run as a cron job in the chart).

### Problem

I'd like to control and keep data in Jaeger for not more then X days back. Everything before that should be deleted / I don't want to manage or see this data.

### Proposal

Create a similar 'jaeger-solutions-es-index-cleaner' just for cassandra, cron job that runs every X times and perform cleaning based on the X parameter to keep the history.

**Comment by yurishkuro** [comment]
Cassandra does not require cleaner jobs, it has always supported TTL which you can customize in our schema creation scripts (and alter manually afterwards).
