### ISSUE TITLE
[Bug]: Jaeger not respecting JAEGER_DISABLED=true

### ISSUE THREAD

**Issue by tomsiwik** [jaegertracing/jaeger#5385]
### What happened?

I'm trying to run jaeger without it's own traces in docker (using environment variable as stated in the [documentation](https://www.jaegertracing.io/docs/1.56/monitoring/#traces)). However, when I open the UI and refresh the page the traces are still logged. I've tried pruning/killing all docker images and volumes to no effect.

### Steps to reproduce

1. Run the `docker-compose up -d` with example `docker-compose.yml`
- alternative: Run `docker run -e JAEGER_DISABLED=true -p 16686:16686 jaegertracing/all-in-one:1.56`
2. Navigate to `http://localhost:16686/`
3. Refresh page and look at traces

### Expected behavior

Traces of `jaeger-all-in-one` should not be visible

### Screenshot

<img width="1671" alt="image" src="https://github.com/jaegertracing/jaeger/assets/1047412/a7908b8c-7fde-473d-9837-77aa2a911327">

### Jaeger backend version

latest

### Operating system

M1 Mac

### Deployment model

docker,docker-compose

### Deployment configs

`docker-compose.yml`
```shell
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - JAEGER_DISABLED=true
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - '16686:16686' # UI @ http://localhost:16686
      - '14250:14250' # TRACES via protobuf
```

**Comment by varshith257** [comment]
@yurishkuro I have also tried with it and traces are appearing as mentioned above in issue. I think we need a fix for this

**Comment by yurishkuro** [comment]
what is JAEGER_DISABLED? Where is it documented?

**Comment by varshith257** [comment]
I think he introduced a variable in such a way that he can stop Jaeger 😅. I just tested with his docker file. He may assuming with that JAEGER_DISABLED=true get Jaeger stop from working

**Comment by varshith257** [comment]
@tomsiwik Can we get the link of documentation where you referred it?

**Comment by tomsiwik** [comment]
https://www.jaegertracing.io/docs/1.25/monitoring/#traces

**Comment by varshith257** [comment]
But it mentioned to keep that variable while docker run. You have explicitly introduced in Dockerfile instead at docker run cd. Once give it try and let us know

**Comment by varshith257** [comment]
Got it! Samething resulting getting confused about this variable. There mentioned the traces are of its own components of query service.

Maybe @yurishkuro will know the clear context of this `JAEGER_DISABLED=true` variable.

**Comment by tomsiwik** [comment]
True. Regardless of the naming `jaeger-query` or `jaeger-all-in-one` setting the variable to `true` or `false` does never show `jaeger-query` but always `jaeger-all-in-one`. Ideally, I don't want to see any traces but the services I'm collecting them from.

**Comment by skocan** [comment]
Hey, I'm having the same issue. Downgrading to jaegertracing 1.47 solved this issue (there is no `jaeger-all-in-one` but `jaeger-query` instead, so I think that's the reason why `JAEGER_DISABLED=true` works), but I would really appreciate some tips how to disable `jaeger-all-in-one` service.

**Comment by yurishkuro** [comment]
Since we switched to OTEL SDKs this setting is no longer applicable. We need to change the docs (retroactively). There should be a setting for OTEL SDK (like `never` sampler) which will have similar effect.

**Comment by yurishkuro** [comment]
another thing we could do is remap that var, but the prod binaries don't seem to call this function, only hotrod does

https://github.com/jaegertracing/jaeger/blob/afc4b2f1e880e15e33ac451034f2d918258b485b/internal/jaegerclientenv2otel/envvars.go#L47

**Comment by yurishkuro** [comment]
I updated the docs

**Comment by yurishkuro** [comment]
Thanks for reporting!
