### ISSUE TITLE
How to use jaeger's UI to read data from the elasticsearch written by zipkin.

### ISSUE THREAD

**Issue by ZAntony** [jaegertracing/jaeger#539]
I want to use jaeger's UI, but I'm already using a zipkin, and most of the data is on es. Is there a good solution? I see that the UI is not a lot of documentation, and there are no es configuration options

**Comment by ZAntony** [comment]
elasticsearch Indices cannot be modified

**Comment by black-adder** [comment]
Jaeger UI can only display jaeger format traces (if that's ok with you). To get this to work, we'd have to build the jaeger query service to read from zipkin es and then convert it into jaeger before displaying it in the UI. We don't have plans for supporting this feature.

**Comment by yurishkuro** [comment]
Depending on your setup you may be able to replace zipkin collectors with jaeger collectors and start writing data to ES in Jaeger format. Or you could bifurcate the incoming stream of spans into both zipkin and Jaeger installations until the data in zipkin ES expires. But if you want to keep zipkin collectors only, then as Won said you need an adapter for Jaeger UI API.

**Comment by ZAntony** [comment]
@yurishkuro @black-adder Thank you, I understand
