### ISSUE TITLE
[Feature]: spark-dependencies job should support OpenSearch in addition to ES and Cassandra

### ISSUE THREAD

**Issue by ronnybremer** [jaegertracing/jaeger#5390]
### Requirement

A Jaeger deployment allows for automatic span interdependency analysis to build a system architecture tree. I would like to see the job responsible for generating this architecture to support our OpenSearch backend storage.

### Problem

According to the documentation, spark-dependencies is only supporting ES and Cassandra, not OpenSearch.

### Proposal

To implement or document the correct parameters for the job to run against an OpenSearch backend.

**Comment by tronda** [comment]
@ronnybremer There is already [an issue](https://github.com/jaegertracing/spark-dependencies/issues/110) related to this subject in the [spark-dependencies project](https://github.com/jaegertracing/spark-dependencies).
