### ISSUE TITLE
HTTP compression for static assets

### ISSUE THREAD

**Issue by ledor473** [jaegertracing/jaeger#542]
It seems that the files served by the `/static` route are not compressed.

The jaeger-ui files seems to be properly minified but they are still quite heavy:
`/static/css/main.*.css` --> ~600KB
`/static/js/main.*.js` --> ~1.8MB

**Comment by yurishkuro** [comment]
That's a great suggestion. Off top of my head I don't remember if Go's file server supports it.

**Comment by ledor473** [comment]
It seems that mux/handlers provides one and it's already part of the dependancies:
https://github.com/gorilla/handlers

We could probably wrap the whole mux.NewRouter() with the CompressHandler just like it's done by the RecoveryHandler.

I can send a pull request with that

**Comment by yurishkuro** [comment]
pull request will be most welcome
