### ISSUE TITLE
[Bug]: Zipkin json binaryAnnotation value : cannot unmarshall

### ISSUE THREAD

**Issue by tarunkalra7** [jaegertracing/jaeger#5434]
### What happened?

While posting the zipkin json to the collector, it runs into error with this output of failing to deserialize with this : `cannot unmarshal bool into Go struct field binaryAnnotation.binaryAnnotations.value of type string`

### Steps to reproduce

```
[
{
    "traceId": "7d3277b087a7c05a",
    "name": "example",
    "id": "3c1813d224db60fe",
    "parentId": "a50ac2ce7f3bf056",
    "timestamp": 1508924339988597,
    "duration": 1781,
    "annotations": [],
    "binaryAnnotations": [
      {
        "key": "service",
        "value":  true
      }
    ]
  }
]
```
The following json fails to deserialize with this error : `cannot unmarshal bool into Go struct field binaryAnnotation.binaryAnnotations.value of type string`

With the latest version of jaeger, we are running into this error. It was working with Jaeger v1.51.0

### Expected behavior

The deserialization should be done without error. 

### Relevant log output

```shell
json: cannot unmarshal bool into Go struct field binaryAnnotation.binaryAnnotations.value of type string
```

### Jaeger backend version

v1.56.0

### Operating system

Linux

### Deployment model

docker

**Comment by yurishkuro** [comment]
Which port are you sending this to? Which http headers are sent?

**Comment by tarunkalra7** [comment]
@yurishkuro I am using 9411 port, and I have used this command to check the same with the output. Please find the same
`bash-4.4$ curl -X POST -H "Content-Type: application/json" -d '[{"traceId":"7d3277b087a7c05a","name":"example","id":"3c1813d224db60fe","parentId":"a50ac2ce7f3bf056","timestamp":1508924339988597,"duration":1781,"annotations":[],"binaryAnnotations":[{"key":"service","value":true}]}]' http://localhost:9411/api/v1/spans`

This was the response that I got : 
`zipkinv1: json: cannot unmarshal bool into Go struct field binaryAnnotation.binaryAnnotations.value of type string`

**Comment by yurishkuro** [comment]
You are using the old Zipkin JSON format, in v2 I don't think they have "binary annotations" anymore.

In [v1.53](https://github.com/jaegertracing/jaeger/blob/main/CHANGELOG.md#1530-2024-01-08) we removed Jaeger's internal implementation of Zipkin endpoint and started using one from OTEL (#5045). The tests there showed that both v1 and v2 formats were still accepted, but perhaps we don't have full coverage (for bool attr).

In any case, this is not something we can fix in Jaeger anymore, it if's a bug in the OTEL receiver it needs to be fixed there.
