### ISSUE TITLE
Flaky coverage

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger#546]
We might possibly have a flaky test that's causing coverage to drop

https://coveralls.io/builds/14255546/source?filename=pkg%2Fhealthcheck%2Fhandler.go

**Comment by black-adder** [comment]
Did a little digging:

Coverage passes:
=== RUN   TestServeHandler
2017-11-29T14:32:58.435Z	ERROR	_obj_test/handler.go:83	failed to serve	{"error": "accept tcp [::]:43979: use of closed network connection"}
github.com/jaegertracing/jaeger/pkg/healthcheck.ServeWithListener.func1
	github.com/jaegertracing/jaeger/pkg/healthcheck/_test/_obj_test/handler.go:83
--- PASS: TestServeHandler (0.00s)
PASS
coverage: 100.0% of statements

Coverage fails:
=== RUN   TestServeHandler
--- PASS: TestServeHandler (0.00s)
PASS
coverage: 92.6% of statements
2017-11-29T10:32:30.052Z	ERROR	_obj_test/handler.go:83	failed to serve	{"error": "accept tcp [::]:46818: use of closed network connection"}

Looks like the function under test starts a go routine that might only be run after the coverage is run. I'll add a fix that waits until the routine starts.

**Comment by jpkrohling** [comment]
I believe this is now outdated: https://codecov.io/gh/jaegertracing/jaeger/branch/master/history/pkg/healthcheck/handler.go?before=65a499a247e0e7d0f977f1898100e469975746ac
