### ISSUE TITLE
Allow dependabot to upgrade database versions used in integration tests

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5485]
In the storage integration tests we run backends using Docker images. The versions for those images are hardcoded in various places:
  * sometimes in the GH workflow https://github.com/jaegertracing/jaeger/blob/584b6ffa96726367177a66d653a9b39773c47bef/.github/workflows/ci-elasticsearch.yml#L28
  * sometimes in the shell script https://github.com/jaegertracing/jaeger/blob/584b6ffa96726367177a66d653a9b39773c47bef/scripts/kafka-integration-test.sh#L21
  * maybe somewhere else

None of these places are supported by the `dependabot`, so we're not getting regular upgrades and not testing via the latest versions of the storage backends.

One solution could be to use docker-compose files to bring the databases up instead of running a docker command directly. E.g. we could have `docker-compose-elasticsearch-v7.yaml` and `docker-compose-elasticsearch-v8.yaml` and simplify the matrix in the workflow to only specify the major version and then pick the right file at runtime. Then wen can configure dependabot to look at those docker-compose files where it should be able to upgrade the versions as needed.

We could try it with opensearch and see if dependabot will upgrade the versions. We also need to be careful to prevent dependabot from upgrading the major version, e.g. integration test against v1.x of opensearch should continue running against v1.x (whichever the latest release is for that major), not bump it to v2.x which is the absolute latest across majors.

## Tracker

* [x] Elasticsearch/opensearch #5490
* [x] Kafka
* [x] Cassandra

**Comment by hellspawn679** [comment]
@yurishkuro can you assign me this issue I would also like to work on Kafka and Cassandra ci
