### ISSUE TITLE
Replace "internal" metrics.Factory usage with direct calls to `expvar`

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5495]
Some of Jaeger components utilize `expvar` to report their configuration options for introspection. However, instead of using `expvar` directly they are going about it in a round-about way:
  * they create a combined metrics factory via `fork.New` which takes the primary factory and an expvar-backed metrics. Example: https://github.com/jaegertracing/jaeger/blob/a7a7308c2da52a90ebf75313ce322f82cd43b59d/cmd/agent/main.go#L64
  * the secondary factory is only used by Fork when the namespace starts with `"internal"`. Example: https://github.com/jaegertracing/jaeger/blob/a7a7308c2da52a90ebf75313ce322f82cd43b59d/cmd/agent/app/builder.go#L135 

We can simplify all of this by letting those few places that create internal namespace to use `expvar` directly:
   * `./cmd/agent/app/builder.go:132`
   * `./plugin/storage/memory/factory.go:127`
   * `./plugin/storage/factory.go:342`

For example, this code https://github.com/jaegertracing/jaeger/blob/a7a7308c2da52a90ebf75313ce322f82cd43b59d/plugin/storage/memory/factory.go#L126-L130

can be replaced with
```
func (f *Factory) publishOpts() {
	v := expvar.NewInt("jaeger_storage_memory_max_traces")
	v.Set(int64(f.options.Configuration.MaxTraces))
}
```

## Steps 
* [ ] track down the use of `fork.New` factory and remove them
* [ ] identify which internal components use `"internal"` namespace to report settings and replace with `expvar` directly
* [ ] remove `internal/metrics/fork/*`
* [ ] remove `internal/metrics/expvar/*`
* [ ] fix tests

**Comment by prakrit55** [comment]
hii @yurishkuro, after removing the  `internal/metrics/fork`, what could be the necessary way to return the `factory` ??!

**Comment by yurishkuro** [comment]
return from where?

**Comment by prakrit55** [comment]
> return from where?

in the https://github.com/jaegertracing/jaeger/blob/a7a7308c2da52a90ebf75313ce322f82cd43b59d/cmd/agent/main.go#L64
to be used afterwards

**Comment by yurishkuro** [comment]
we just use the base factory directly
