### ISSUE TITLE
[Feature]: Add Elasticsearch helper binaries to GitHub Releases

### ISSUE THREAD

**Issue by iinuwa** [jaegertracing/jaeger#5499]
### Requirement

We automate installation of Jaeger with Ansible using the Linux AMD64 binaries. We use the es-index-cleaner and es-rollover binaries, but we have to build them ourselves since they're not included in the repo. Is it possible to include those binaries the release packages?

### Problem

The Jaeger helper tools for Elasticsearch are only provided as container images, not as binaries to download.

### Proposal

A couple ways of accomplishing this are:
- Include the built Elasticsearch tools in the tarfiles (would increase size of each tarfile)
- Add a separate set of tarfiles for the helper tools (would increase the number of tarfiles, signatures, SBOMs in the release list etc.)

**Comment by yurishkuro** [comment]
I think a separate tools tar would be better. The changes need to happen in scripts/package-deploy.sh (we already build all the binaries in that workflow, but only core runtime components are included in the tar).

Curious - why can't you run Docker images? Ansible is capable of running containers.

**Comment by iinuwa** [comment]
Saw that this request is completed, thank you @FlamingSaint and @yurishkuro!

> Curious - why can't you run Docker images? Ansible is capable of running containers.

Yeah, Ansible can do that, but when it comes to containers, for us it's another layer of unnecessary complexity. We want to run these services as unprivileged services, which systemd makes easy. Running an unprivileged container as a service requires setting up user and network namespaces and imports a whole extra OS (albeit fairly small). We already have to configure trust systemd, so there's no reason to also trust and configure Alpine and the Docker daemon/Podman. Ultimately, it introduces enough complexity and security concerns into our environment to make it not worth the trouble.

I recognize that other environments heavily rely on containers, so tacking on one more container service makes perfect sense in those environments. That just doesn't happen to be the case for us. (We do have an on-prem Docker cluster running, and I have maintained it for years, but we haven't derived enough benefit to continue to run containers in our environment and plan to shut it down.)

Thanks again for supporting this deployment strategy, and for the rest of the work you do on Jaeger! This will be big help for our development process!
