### ISSUE TITLE
Is it compatible with Event Sourcing and CQRS microservice patterns -> mixture of HTTP and message broker (amqp/kafka) communications?

### ISSUE THREAD

**Issue by archenroot** [jaegertracing/jaeger#552]
Imagine I have a command send from client via http api, this command message is tranlated into event which is internally via adapter submited either via amqp/kafka/http to event store. Once the event is stored in event store database (mysql/postgres), other service tail database transaction log and publish events to be consumed by other services. This is simple flow of service/client to service communication via event store.

Can Jaeger be used to trace such flow?

**Comment by yurishkuro** [comment]
as long as the event store can store metadata with each item, the trace context can be included in the metadata and thus the flow can be traced.

**Comment by archenroot** [comment]
Nice bro, each event is having the event header which consists of any kind of metadata you can imagine and it is not a problem to extend it.

I will give this beautiful piece of art a try. This is must, I would like to see this integrated one day in for example Spring Boot Admin, or other bigger tool as plugin, but that is another question. 

Thanks a lot for this project!!!
