### ISSUE TITLE
depenabot is not upgrading docker-compose files

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5552]
This comment: https://github.com/jaegertracing/jaeger/pull/5520/files#r1633476406

**Comment by FlamingSaint** [comment]
I could give this a try

**Comment by FlamingSaint** [comment]
Just a small doubt. I don't think there is a configuration option in dependabot to do this: 
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
Please correct me if I am wrong

**Comment by yurishkuro** [comment]
if that's the case (seems like it) then we'd need to refactor your change to use standard file names and use directories for disambiguation, e.g. `cassandra/v3/docker-compose.yaml`

**Comment by yurishkuro** [comment]
E.g. this is what we did for base images:
```
./docker/base/Dockerfile
./docker/debug/Dockerfile
```

**Comment by yurishkuro** [comment]
@hellspawn679 it's still not working
```
The property '#/updates/4/' contains additional properties ["update-types"] outside of the schema when none are allowed
The property '#/updates/5/' contains additional properties ["update-types"] outside of the schema when none are allowed
The property '#/updates/6/' contains additional properties ["update-types"] outside of the schema when none are allowed
The property '#/updates/7/' contains additional properties ["update-types"] outside of the schema when none are allowed
```
In the [sample file](https://github.com/dependabot/dependabot-core/blob/1aac2b839744c809d52043fa51f447d71fe9ca48/.github/dependabot.yml#L117) I only see `update-types` used in some nested configs. I am trying another way #5560

**Comment by yurishkuro** [comment]
@FlamingSaint turns out docker-compose files are not supported by dependabot. The issue there has a workaround of using Dockerfiles in combination with docker-compose. Pretty annoying, but at this point probably worth it.

https://github.com/dependabot/dependabot-core/issues/390#issuecomment-1062170379

Longer term, we should probably switch to Mend's Renovate bot (used by OTEL project), but should confirm if it supports docker-compose. Perhaps we can enable it just for docker-compose initially, to cover the gap of dependabot.

**Comment by FlamingSaint** [comment]
Oh I didn't check for that. My bad. Also looks like Renovate bot supports docker-compose. I could work on migrating from dependabot to renovate bot. Let me know if I could go ahead.

**Comment by FlamingSaint** [comment]
Also now that the new bot can detect docker-compose files we can remove the unnecessary extra directories that are created.

**Comment by yurishkuro** [comment]
@FlamingSaint can you stamp this? https://github.com/jaegertracing/jaeger/pull/5566

**Comment by yurishkuro** [comment]
@FlamingSaint fyi - I enabled Renovate bot, it seems to be correctly discovering all dependencies (#5572). But we need to do some preparations first (for one, it does not add the label we use for dependencies)

**Comment by yurishkuro** [comment]
This is now working with Renovate bot, closing.
