### ISSUE TITLE
Create config for Mockery

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5569]
When running `make generate-mocks`, mockery tool complains that it will require a config file in the next major version. We should migrate now to a config file instead of giving instructions via CLI flags.

`11 Jun 24 19:56 UTC WRN DEPRECATION: use of the packages config will be the only way to generate mocks in v3. Please migrate your config to use the packages feature. dry-run=false migration=https://vektra.github.io/mockery/v2.42/migrating_to_packages/ url=https://vektra.github.io/mockery/v2.42/features/#packages-configuration version=v2.42.3
`

* [x] Switch to config instead of direct CLI calls #5623
* [ ] Add other mocks packages to config (see below)

We seem to have a lot of other packages for which we probably just generated mocks manually once. We need to include them into  config too:
```
$ find . -name mocks
./crossdock/services/mocks
./cmd/ingester/app/processor/mocks
./cmd/ingester/app/consumer/mocks
./cmd/collector/app/sanitizer/cache/mocks
./proto-gen/storage_v1/mocks
./plugin/sampling/leaderelection/mocks
./plugin/storage/grpc/mocks
./storage/mocks
./storage/metricsstore/mocks
./storage/dependencystore/mocks
./storage/spanstore/mocks
./storage/samplingstore/mocks
./pkg/kafka/mocks
./pkg/cassandra/mocks
./pkg/es/mocks
./pkg/es/client/mocks
./pkg/distributedlock/mocks
```

**Comment by jesslourenco** [comment]
Hi @yurishkuro, I'd like to work on this :) will be opening a PR soon.

**Comment by EraKin575** [comment]
Can I also work on this parallely?
