### ISSUE TITLE
Improve testing on Go-tip

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5601]
We have a CI workflow that runs only on the main branch commits that in addition to regular unit tests runs them on `gotip` version of Go. Recently it [started failing](https://github.com/jaegertracing/jaeger/actions/runs/9487070667/job/26142820572) because it cannot download Go tip by commit hash, perhaps due to some upstream failure to build the distro. 

The gotip installation is done by this action .github/actions/setup-go-tip/action.yml:

Proposal:
  * split this action into two steps:
    * first step to try to download the gotip distro and export a success/failure status (via `echo "{name}={value}" >> "$GITHUB_OUTPUT"`)
    * second step to run only if previous step was successful and attempt to install the distro
  * add a third step to run only if step 1 failed and use a slower way to install (build) gotip: https://pkg.go.dev/golang.org/dl/gotip

In order to test the changes, I'd recommend implementing them first in a test project, similar to https://github.com/yurishkuro/test-project-3/tree/master/.github.

**Comment by varshith257** [comment]
Taking this up!
