### ISSUE TITLE
Prevent Renovatebot from upgrading major versions

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5607]
One immediate need: in this PR #5604 the bot is bumping Cassandra image versions 3 and 4 to 5, but we actually need them to stay where they are because they are part of the backwards compatibility testing in the CI. There has to be a way to instruct Renovatebot (via config) that we only want minor/patch version upgrades, either for specific docker compose files, or for specific image names.

Similar issue in #5605 and #5606

**Comment by DustyMMiller** [comment]
I created a PR to fix this based on their docs. This is my first PR to a CNCF project so please let me know if I made any mistakes or need to do more with it.
Thanks
