### ISSUE TITLE
Export failed for  github.com/uber/jaeger-client-go

### ISSUE THREAD

**Issue by ikenchina** [jaegertracing/jaeger#561]
why did it report this error?

[INFO]	--> Exporting github.com/stretchr/testify
[INFO]	--> Exporting github.com/VividCortex/gohistogram
[INFO]	--> Exporting github.com/uber/jaeger-client-go
[INFO]	--> Exporting github.com/uber-go/atomic
[INFO]	--> Exporting github.com/uber/tchannel-go
[INFO]	--> Exporting github.com/kr/text
[ERROR]	Export failed for github.com/uber/jaeger-client-go: Error while exporting submodule sources
[INFO]	--> Exporting go.uber.org/atomic
[INFO]	--> Exporting golang.org/x/sys
[INFO]	--> Exporting golang.org/x/net
[INFO]	--> Exporting golang.org/x/text
[INFO]	--> Exporting gopkg.in/mgo.v2
[INFO]	--> Exporting gopkg.in/inf.v0
[INFO]	--> Exporting gopkg.in/olivere/elastic.v5
[INFO]	--> Exporting gopkg.in/yaml.v2
[INFO]	--> Exporting go.uber.org/multierr
[INFO]	--> Exporting go.uber.org/zap
[ERROR]	Unable to export dependencies to vendor directory: Error while exporting submodule sources

**Comment by yurishkuro** [comment]
this is some kind of glide issue (e.g. https://github.com/Masterminds/glide/issues/746). Try cleaning glide cache or upgrading glide.

**Comment by yurishkuro** [comment]
closing as it's not directly Jaeger related
