### ISSUE TITLE
Integration tests do not pass for Opensearch 2.14

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5624]
e2e tests failed in the upgrade PR https://github.com/jaegertracing/jaeger/pull/5606.

https://github.com/jaegertracing/jaeger/actions/runs/9503609365/job/26194416863?pr=5606

The logs show that the image was downloaded and "started", but then the CI script is not able to ping the server, and  for some reason the final step of printing container logs produces nothing.

Best way to fix is to run that specific workflow manually to reproduce and debug, e.g.
```
bash scripts/es-integration-test.sh opensearch 2.x 1v1
```

**Comment by hellspawn679** [comment]
i don't think there is any issue with integration test

**Comment by hellspawn679** [comment]
when i build the docker compose with version 2.14.0 it gave me logs 
`No custom admin password found. Please provide a password via the environment variable OPENSEARCH_INITIAL_ADMIN_PASSWORD.`
I will create pr adding the var in few minutes
