### ISSUE TITLE
Use db password in Cassandra integration tests

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5643]
per this comment: https://github.com/jaegertracing/jaeger/pull/5628/files#r1643314507

https://github.com/jaegertracing/jaeger/blob/main/scripts/cassandra-integration-test.sh

**Comment by ayushrakesh** [comment]
@yurishkuro, I want to work in this issue. Please assign to me.

**Comment by ayushrakesh** [comment]
Oh, @yurishkuro , I forgot that you don't assign issues. I have just made a PR, please review it.

**Comment by Ali-Alnosairi** [comment]
Hello @yurishkuro ,

I followed the instructions for [contribution](https://github.com/jaegertracing/jaeger/blob/main/CONTRIBUTING.md) then when I run `./scripts/cassandra-integration-test.sh 3.11 1.0 v1 `   just as test, but it shows error.
This is line of it `./scripts/cassandra-integration-test.sh: line 43: docker: command not found` as it shows  that no docker found. 

I just do the same guidelines for contributing.
Please If you had an idea what to do or how to run such command to test a case 

Thank you in advance.

**Comment by yurishkuro** [comment]
You need to have docker & docker compose installed

**Comment by akstron** [comment]
Hi @Ali-Alnosairi let me know if you are still working on this issue? I would like to pick this up if possible.

**Comment by Ali-Alnosairi** [comment]
Hi @akstron, Yes, I still working on it.
