### ISSUE TITLE
Implement OTLP export in microsim

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5685]
We are using github.com/yurishkuro/microsim for generating load in the integration tests. It is currently using OTEL SDK with Jaeger exporter, which are already deprecated in OTEL. We need to change `microsim` to use OTLP exporter by default.

cc @FlamingSaint

**Comment by FlamingSaint** [comment]
Okay, I will start working on this right away.

**Comment by yurishkuro** [comment]
Release as v0.4.0
