### ISSUE TITLE
Enhance e2e test for HotROD

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5735]
The existing CI test for HotROD `scripts/hotrod-integration-test.sh` only checks that the HotROD web UI is being served after running `docker compose`. Since OTEL Collector release v0.105 there was a change where OTLP receivers started using `localhost` as the default host to listen to (see #5734). This breaks visibility of Jaeger endpoints from HotROD app, but our CI tests did not fail, because `scripts/hotrod-integration-test.sh` doesn't actually check if the trace is successfully submitted to Jaeger.

We can do better. While we cannot simulate a click on the UI button in the test (technically, we can with a headless browser), we can still execute a request against HotROD's `frontend` service endpoint, which will trigger a trace generation into Jaeger. The endpoint should also return the trace ID in the response headers. Using that trace ID the test can poll Jaeger query for that trace, checking that the expected number of spans is present (retry until that number is returned or until a global timeout is reached, e.g. 5min).

**Comment by hellspawn679** [comment]
when i run hotrod container it shows this 
`traces export: Post "http://localhost:4318/v1/traces": dial tcp 127.0.0.1:4318: connect: connection refused`
and i ran jaeger container using this command 
```
docker run -d --name jaeger \
  -p 16686:16686 \
  -p 4317:4317 \
  -p 4318:4318 \
  -e LOG_LEVEL=debug \
  -e COLLECTOR_OTLP_GRPC_HOST_PORT=0.0.0.0:4317 \
  -e COLLECTOR_OTLP_HTTP_HOST_PORT=0.0.0.0:4318 \
  jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
```

**Comment by hellspawn679** [comment]
I think it is trying to hit `http://localhost:4318` inside the hotrod container

**Comment by yurishkuro** [comment]
probably same issue as here #5734
