### ISSUE TITLE
Skip building HotROD for all platforms for pull requests

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5743]
To speed up CI for pull requests we avoid expensive multi-platform image building. For example, the all-on-one CI workflow `.github/workflows/ci-all-in-one-build.yml` uses `BUILD_FLAGS=-l -D -p linux/amd64`:
  * `-l` for local build only (no pushing to public registry)
  * '-D' to skip building debug image
  * '-p' to only build for the GH runner's platform

We should reproduce the same functionality for `.github/workflows/ci-hotrod.yml` and `scripts/hotrod-integration-test.sh`

**Comment by Manoramsharma** [comment]
Hi @yurishkuro, as per my understanding do we have to achieve the similar `BUILD_FLAGS` configuration while building the image for HotROD if running on a Pull request. And defining those flags action to the corresponding script file?

I can come up with a PR if you can guide me more about the issue and if I am thinking in a right direction?

**Comment by yurishkuro** [comment]
yes, we can replicate similar setup and CLI flags from the other scripts
