### ISSUE TITLE
No service dependencies found.

### ISSUE THREAD

**Issue by ikenchina** [jaegertracing/jaeger#575]
I ran the components on my laptop

```
jaeger/cmd/collector$ go run main.go --cassandra.keyspace=jaeger_v1_test

agent:
jaeger/cmd/agent$ go run main.go --collector.host-port=localhost:14267

query:
jaeger/cmd/query$  ./query --cassandra.keyspace=jaeger_v1_test --query.static-files=../../jaeger-ui/public --log-level=debug

query-ui:
git clone https://github.com/jaegertracing/jaeger-ui.git
cd jaeger-ui
npm install
npm run build
```

and then, ran Hot R.O.D.
i could find trace in "http://localhost:3000/search" , it did work fine and displayed dependencies.
but, when i entered "http://localhost:3000/dependencies" it displayed "No service dependencies found."

cassandra(3.11.1) displayed no dependencies but has opererations and traces

```
cqlsh> select * from jaeger_v1_test.dependencies;

 ts | dependencies | ts_index
----+--------------+----------

(0 rows)
cqlsh> select * from jaeger_v1_test.operation_names limit 2;

 service_name | operation_name
--------------+-------------------
 jaeger-query | /api/dependencies
 jaeger-query |     /api/services


```

**Comment by ikenchina** [comment]
when i ran jaeger in docker, it works fine.

**Comment by ikenchina** [comment]
no errors in the components and cassandra

**Comment by yurishkuro** [comment]
http://jaeger.readthedocs.io/en/latest/deployment/#aggregation-jobs-for-service-dependencies
