### ISSUE TITLE
iOS client library

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#576]
E.g. https://github.com/OutThereLabs/jaeger-client-objc by @pat2man

**Comment by swizzlr** [comment]
If anyone is actively working on this, let me know. Looking to build a Swift tracer in the near term.

**Comment by simonpierreroy1** [comment]
You can take a look here https://github.com/wayfair/jaeger-swift :)

**Comment by simonpierreroy1** [comment]
@yurishkuro We have worked on it and release a first version of the project. You can take a look and give us feedback. :)  https://github.com/wayfair/jaeger-swift

**Comment by ryanrhee** [comment]
opentracing-swift is ready for use, no further changes are planned.

**Comment by yurishkuro** [comment]
@ryanrhee are there plans to move it under opentracing org?  cc @austinlparker

**Comment by austinlparker** [comment]
Lemme check.

**Comment by tedsuo** [comment]
Let's do it!

**Comment by ryanrhee** [comment]
@jmacd mentioned that we'd like to move this under the opentracing org, but I'm not sure what the current status of that is.

**Comment by jpkrohling** [comment]
What's the status of this one?

**Comment by austinlparker** [comment]
We still want to move it, but I don't have permissions to move things into opentracing.

**Comment by yurishkuro** [comment]
@austinlparker make me admin of that repo and I can move it

**Comment by austinlparker** [comment]
done

**Comment by yurishkuro** [comment]
Which one? I don't see Settings for https://github.com/lightstep/opentracing-swift

**Comment by austinlparker** [comment]
Try refreshing? It shows you as admin on the settings page.

**Comment by yurishkuro** [comment]
I needed to accept the invite. Move is done.

**Comment by austinlparker** [comment]
👍

**Comment by jmacd** [comment]
Cool! Thanks Yuri.

**Comment by simonpierreroy1** [comment]
@yurishkuro We just released Jaeger-iOS for Swift-5 https://github.com/wayfair/jaeger-swift. We have been using it for 3 months in codebase at Wayfair to help improve the performance of our mobile app. (We will soon publish a blog post about it) Let me know if you have any questions.

**Comment by ryanrhee** [comment]
@simonpierreroy1 did you write your own opentracing-swift interface? i don't see you using https://github.com/opentracing/opentracing-swift or https://github.com/opentracing/opentracing-objc .

**Comment by yurishkuro** [comment]
@simonpierreroy1  Great README in your repo!  A few questions:
  * Does it implement the API from https://github.com/opentracing/opentracing-swift ?
  * It mentions you submit spans in JSON - which JSON schema are you using?
  * Will you be interested in moving that repo to jaegertracing/jaeger-client-swift?
  * Would you be able to license it with Apache v2 license?

**Comment by simonpierreroy1** [comment]
@ryanrhee @yurishkuro

- API:  We used our own interface, there was no official one in swift when we started working on that project in October. We created an API that could support Jaeger (and Zepkin in the future) or any type of new implementation of spans. We use “more abstract ideas and types” to represent open-tracing concepts than the ones enforced by the Thrift definition and we map it when serializing to disk or sending spans over a network.

Side note: The public and private interface are 100% documented https://wayfair.github.io/jaeger-swift. If you would like to see the public and private documentation, clone the repo and run `jazzy --min-acl private`.

- JSON schema: I can send you the JSON schema, but it is a one-to-one correspondence to https://github.com/jaegertracing/jaeger-idl/blob/master/thrift/jaeger.thrift.

- Moving the repo and Apache v2 license: Our legal team has requested that our repository stay under the `wayfair` namespace. If that is ok with you we would still love to be the official version. I can also ask them for the Apache v2 license.

**Comment by simonpierreroy1** [comment]
Take a look here for more info on our work with Jaeger: https://tech.wayfair.com/2019/05/open-tracing-for-ios-a-performance-tool-for-everyone .

**Comment by yurishkuro** [comment]
@simonpierreroy1 great article!

**Comment by reinpold** [comment]
> Take a look here for more info on our work with Jaeger: https://tech.wayfair.com/2019/05/open-tracing-for-ios-a-performance-tool-for-everyone .

@simonpierreroy1 Thank you for sharing this, it's very useful. Do I understand correctly that your client does not provide the functionality to [inject a SpanContext into a carrier](https://github.com/opentracing/specification/blob/master/specification.md#inject-a-spancontext-into-a-carrier) using [Jaeger's propagation format](https://www.jaegertracing.io/docs/1.14/client-libraries/#propagation-format)? I am just wondering how you are propagating the SpanContext to downstream backend services currently?

**Comment by yurishkuro** [comment]
Jaeger client libraries are officially deprecated
