### ISSUE TITLE
[Bug]: jaegertracing/all-in-one:1.59 image replaced the GRPC and HTTP ipaddress from 0.0.0.0:4317 and 0.0.0.0:4318 to localhost:4317 and 4318, this blocks external access to the container.

### ISSUE THREAD

**Issue by FantasticGithubUser** [jaegertracing/jaeger#5769]
### What happened?

jaegertracing/all-in-one:1.59 image replaced the GRPC and HTTP ipaddress from 0.0.0.0:4317 and 0.0.0.0:4318 to localhost:4317 and 4318, this blocks external access to the container.

### Steps to reproduce

run this cmd in docker: docker run --name dev_jaeger -p 16686:16686 -p 4317:4317 -p 4318:418 -d jaegertracing/all-in-one:1.59
You will get 
![image](https://github.com/user-attachments/assets/55b3bc02-e053-42e7-ba2f-0efe5f3a976d)

But in version 1.58

![image](https://github.com/user-attachments/assets/86d3f9b5-2828-4959-b330-e4be53f019bf)

### Expected behavior

The Default IP to listen on for GRPC and HTTP should be 0.0.0.0

**Comment by yurishkuro** [comment]
Please see https://github.com/jaegertracing/jaeger/issues/5737

Closing as duplicate
