### ISSUE TITLE
Jaeger's LFX Mentorship - Term 03 - 2024 Sep - Nov

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5772]
Timeline: https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/03-Sep-Nov
  * [ ] Mentee applications due August 13th, 5:00 PM PDT
  * [ ] Admission decisions due by August 27th, 5:00 PM PDT
  * [ ] Selection notification by September 3rd, 5:00 PM PDT

These projects are proposed for the Fall term:
  * https://github.com/jaegertracing/helm-charts/issues/610
  * https://github.com/jaegertracing/jaeger-operator/issues/2717

Parent / background issue: jaegertracing/jaeger#4843

## Application process
* For details about LFX mentorship & the application process, see https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship. 
* Direct link to applying: https://mentorship.lfx.linuxfoundation.org/participate/mentee
* ❗**Proposal 📜 required**❗You must [submit a proposal](https://www.jaegertracing.io/mentorship-for-mentees/) as part of your application. It helps us select mentees who are the best match for the project. It also allows us to understand your approach to solving the problems we presented. 
  * Note: LFX website does not allow uploading additional documents, so include the proposal in the Cover Letter.

## Getting Started
While the timelines in LFX programs are not very long, we recommend contributing to the project through [bootcamp tasks](https://www.jaegertracing.io/mentorship-for-mentees/#bootcamp) before applying.

Reach out on [Slack](https://www.jaegertracing.io/get-in-touch/#via-chat) with other questions.

**Comment by hp77-creator** [comment]
@yurishkuro will the mentorship open any time soon?
