### ISSUE TITLE
[v2] Clean up gRPC logging

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5784]
The logs are all tagged with `zapgrpc/zapgrpc.go:176`. This indicates that the Skip() parameter is incorrect when gRPC logger is 
instantiated. It's not clear if this is done inside OTEL Collector code or in Jaeger.

For example:

```
$ go run ./cmd/jaeger --config cmd/jaeger/ingester-remote-storage.yaml

...
2024-07-28T16:17:24.271-0400	info	zapgrpc/zapgrpc.go:176	[core] original dial target is: "localhost:4317"	{"grpc_log": true}
2024-07-28T16:17:24.271-0400	info	zapgrpc/zapgrpc.go:176	[core] [Channel #1]Channel created	{"grpc_log": true}
2024-07-28T16:17:24.271-0400	info	zapgrpc/zapgrpc.go:176	[core] [Channel #1]parsed dial target is: resolver.Target{URL:url.URL{Scheme:"dns
```

Here are examples where we call Skip inside Jaeger code:
```
pkg/es/config/config.go
418:		zap.AddCallerSkip(2), // to ensure the right caller:lineno are logged

cmd/internal/flags/service.go
95:			zap.AddCallerSkip(5), // ensure the actual caller:lineNo is shown

examples/hotrod/cmd/root.go
61:		zap.AddCallerSkip(1),
```

**Comment by vvs-personalstash** [comment]
Hi, it seems these logs are being generated from the OTEL collector code i.e. from
otelcol>internal>grpclog>logger.go
It seems the given logs are generated by this zapgrpc logger instance in the logger tests
![Screenshot 2024-07-31 at 2 12 57 AM](https://github.com/user-attachments/assets/a2530095-1762-435e-b715-385b006fde2d)
I had all the 11 unwanted logs of zapgrpc generating from here .

**Comment by yurishkuro** [comment]
That code is missing `AddCallerSkip(n)` for some `n`.
