### ISSUE TITLE
Create database schema in Cassandra automatically

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5797]
Historically, Jaeger's integration with different databases was not consistent in how the database initialization happens. For example, when using Cassandra the user first needs to run a "create schema" script [1]. But running with Elasticsearch does not require a script, it's done automatically in the code on collector startup.

We want to add similar initialization to Cassandra implementation. This will be especially helpful in Jaeger v2 when it's deployed by K8s Operator from OTEL Collector, which does not have the built-in ability to run pre-initialization steps.

[1] `/plugin/storage/cassandra/schema/create.sh`

**Comment by kairveeehh** [comment]
hiii @yurishkuro I would like to take up this issue under LFX  , could you assign it to me and let me know any further resources if there?

**Comment by hellspawn679** [comment]
so basically we need to remove the schema folder dependency   and initialize with similar to es

**Comment by Spraveen8-chary** [comment]
- Add schema initialization to Jaeger's Cassandra setup.
- Update the collector startup to handle schema creation.
- Test the changes in different deployment scenarios

**Comment by akstron** [comment]
Hi @yurishkuro , I am working on it and wanted some suggestions. For this task we have to create keyspace, types and tables after cassandra session initialization. Do you recommend extracting the queries from *.tmpl files (which is how it is done currently by running `create.sh` script) or should we write the queries in the code itself?

**Comment by yurishkuro** [comment]
It's fine to read from template files, we just need to embed them into the binary.

**Comment by Manask322** [comment]
@yurishkuro  - can you confirm is this issue being worked upon ? would like to take it up.

**Comment by akstron** [comment]
Hi @Manask322 , you can go ahead with taking this up. I am caught up in some other work and can't work on my PR.

**Comment by yurishkuro** [comment]
@akstron I just noticed that in the DefaultConfiguration() function you wrote 
```
CompactionWindow:  time.Minute,
```
This would be a terrible default, most likely disabling the compaction process altogether as the raw SSTables might be spanning more than one minute of data. We need to change it to something sensible, e.g. 2hr.
