### ISSUE TITLE
Write a script to replace long Apache license headers with a short SPDX reference.

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5807]
Historically we used multi-line Apache v2 header in the files, e.g. https://github.com/jaegertracing/jaeger/blob/b76dc65f0a3fcbedb912f2ce30616daf8a73bbb2/ports/ports.go#L3

Recently we started using just an SPDX reference: https://github.com/jaegertracing/jaeger/blob/b76dc65f0a3fcbedb912f2ce30616daf8a73bbb2/cmd/jaeger/main.go#L2

* Write a script to find the files with the long header and replace it with the SPDX line.
* Store the script under ./scripts/
* Do NOT include update to the source files in the PR itself, only the script (a maintainer will then run it on the repo).

**Comment by thecaffeinedev** [comment]
Hi @yurishkuro I have created a PR for this. Could you please check it and let me know?
