### ISSUE TITLE
[Bug]: kafka crash cause colletcor crash

### ISSUE THREAD

**Issue by songzeyao0324** [jaegertracing/jaeger#5812]
### What happened?

The amount of data in jaeger-collector is very large. The collector writes a queue and discards the data when the upper limit is reached. Kafka is responsible for consuming the data of jaeger-collector. Today, Kafka is offline, causing the collector to be offline. What happened?

### Steps to reproduce

kafka crash 

### Expected behavior

Provide bug solution suggestions，When Kafka restarts or goes offline, the collector will not go offline

### Jaeger backend version

Release 1.22.0

**Comment by yurishkuro** [comment]
what do you expect collector to do if kafka is down?

**Comment by songzeyao0324** [comment]
> what do you expect collector to do if kafka is down?

I hope that if Kafka goes down, the collector process will still be there. After Kafka is restarted, it will be back to normal.

**Comment by yurishkuro** [comment]
We're not making improvements to this part of the code. In jaeger v2 we use OTEL's implementation for Kafka, which may have the property you seek.

**Comment by songzeyao0324** [comment]
> We're not making improvements to this part of the code. In jaeger v2 we use OTEL's implementation for Kafka, which may have the property you seek.

Ok, thanks
