### ISSUE TITLE
Add copyright/license headers to all scripts

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5827]
In our `make lint` and `make fmt` targets we ensure that all Go source files have a copyright & license comments like this:
```sh
$ head -2 cmd/jaeger/main.go
// Copyright (c) 2023 The Jaeger Authors.
// SPDX-License-Identifier: Apache-2.0
```

Objective:
  * modify `./scripts/updateLicense.py` to also work for shell scripts under `./scripts/`
  * make sure not to override the shebang line
  * also make sure this script works for the Makefiles, which have the pattern of `Makefiles*` or `*.mk`
  * invoke the script as needed from `lint` and `fmt` targets

Verification:
  * running `make lint` should flag all the scripts and Makefiles that are missing the license headers
  * running `make lint` should update them as needed

DO NOT commit the changes to the file headers, only raise a PR containing changes to the script & make targets.

**Comment by Zen-cronic** [comment]
i believe the `ALL_SRC` variable in [Makefile](https://github.com/jaegertracing/jaeger/blob/dc49b1faaeee15c2498c562309bab4fc0525bd56/Makefile#L32) needs to be updated too? So that the `.sh` for auto reformatted.
Something like:
```
ALL_SRC = $(shell find . \( -name '*.go' -o -name '*.sh' \) 
                   -not -name '_*' \
                   -not -name '.*' \
                    ... // the rest
```

Also, are the `.py` scripts included?

**Comment by yurishkuro** [comment]
Yes py scripts are included
