### ISSUE TITLE
[Bug]: unknown service opentelemetry.proto.collector.trace.v1.TraceService

### ISSUE THREAD

**Issue by tcharlezin** [jaegertracing/jaeger#5843]
### What happened?

Integration jaeger from helm installation with Otel Collector, is causing this error when calling the jaeger-collector on port 14250

### Steps to reproduce

1. helm repo add jaegertracing https://jaegertracing.github.io/helm-charts

2. kubectl create ns observability

3. helm install my-release jaegertracing/jaeger-operator -n observability

4. Already existent ElasticSearch
helm install jaeger jaegertracing/jaeger \
  --set provisionDataStore.cassandra=false \
  --set storage.type=elasticsearch \
  --set storage.elasticsearch.host="elasticsearch-loadbalancer.default.svc.cluster.local" \
  --set storage.elasticsearch.port=80 \
  --set storage.elasticsearch.usePassword=false

5. Run the operator:
kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml

6. Apply the yaml:
```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch: {}

    extensions:
      health_check: {}

    exporters:
      debug:
        verbosity: detailed

      otlp:
        endpoint: "jaeger-collector.default.svc.cluster.local:14250"
        tls:
          insecure: true

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug, otlp]
```

### Expected behavior

Should communicate with jaeger and create the traces.
The debug exporter is showing the correct values.

### Relevant log output

```shell
2024-08-13T21:37:27.330Z error exporterhelper/queue_sender.go:92 Exporting failed. Dropping data. {"kind": "exporter", "data_type": "traces", "name": "otlp", "error": "not retryable error: Permanent error: rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.trace.v1.TraceService", "dropped_items": 7}
go.opentelemetry.io/collector/exporter/exporterhelper.newQueueSender.func1
 go.opentelemetry.io/collector/exporter@v0.106.1/exporterhelper/queue_sender.go:92
go.opentelemetry.io/collector/exporter/internal/queue.(*boundedMemoryQueue[...]).Consume
 go.opentelemetry.io/collector/exporter@v0.106.1/internal/queue/bounded_memory_queue.go:52
go.opentelemetry.io/collector/exporter/internal/queue.(*Consumers[...]).Start.func1
 go.opentelemetry.io/collector/exporter@v0.106.1/internal/queue/consumers.go:43
```

### Jaeger backend version

v 1.53.0

### Stogage backend

ElasticSearch

### Operating system

Linux

### Deployment model

Kubernetes

**Comment by yurishkuro** [comment]
Port 14250 accepts Jaeger's legacy data format. You are sending opentelementry data, is has a different port.
