### ISSUE TITLE
Go version upgrade script should not ignore patch version

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5845]
This came up as part of #5837, specifically in the `docker/debug/Dockerfile` https://github.com/jaegertracing/jaeger/pull/5837/files#diff-ab8e812479730d5975aa87291a563e1dc0e0cf03c790d5d126c54f4248b3820bR4

When `scripts/check-go-version.sh` is run it only preforms substitution of major.minor versions, which resulted in `golang:1.22.6-alpine` becoming `golang:1.23.6-alpine` - a non-existent version at this time. In the other places it replaces versions like `1.22.x`, where substitution works fine, but when the patch version is explicitly specified the script should probably just fail and let us update the files manually.

**Comment by wasup-yash** [comment]
Do we have to be assigned to get the issue or just create a PR if it can be resolved?
