### ISSUE TITLE
localEndpoint is not parsed for extraction of service name

### ISSUE THREAD

**Issue by bandrei** [jaegertracing/jaeger#585]
The Jaeger UI seems to display `unknown-service-name` when the service name is being set in the `localEndpoint` variable of the tracing component.

This is based on the latest publicly available docker image.

For example

```
{"traceId":"fa305db27dbc6df6","id":"fa305db27dbc6df6","kind":"SERVER","name":"post","timestamp":1512505929381059,"duration":964935,"localEndpoint":{"serviceName":"myservice","ipv4":"127.0.0.1","port":22000},"tags":{"http.path":"/api/v2/resources/111496227"}}
```

![image](https://user-images.githubusercontent.com/1153251/33629717-e4a74df4-d9b9-11e7-9902-4ca543859488.png)

**Comment by bandrei** [comment]
actually, this might not even be a bug, I'm not sure whether localEndpoint is mentioned in the opentracing API at all. Closing it for now.

**Comment by yurishkuro** [comment]
I think it might be a bug. Are you using Python client by chance?

**Comment by bandrei** [comment]
Nope, I was actually using Brave from openzipkin (that's why I wasn't sure that was an actual bug). However, the interesting part is that it started working at some point and it started reporting it correctly :/ which I did not expect to happen.

**Comment by golonzovsky** [comment]
Have similar issue after updating to `jaeger 1.0` and `spring-cloud-sleuth:1.3.0.RELEASE` (uses zipkin 2). Between zipkin 1 and 2 this field git renamed from `lc` to `localEndpoint`

![screenshot from 2017-12-14 18-55-50](https://user-images.githubusercontent.com/2477950/34006996-8f0ec266-e100-11e7-932f-cd811151a2e2.png)

```
{
  "traceId": "ef1bd9a3beda07b2",
  "id": "ef1bd9a3beda07b2",
  "name": "loadbrowsecategories",
  "timestamp": 1513273531819000,
  "duration": 1084374,
  "localEndpoint": {
    "serviceName": "user-history",
    "ipv4": "10.181.1.72",
    "port": 8080
  }
}
```

```
{
  "traceId": "e94ab76ce82c0a20",
  "id": "e94ab76ce82c0a20",
  "name": "loadbrowsecategories",
  "timestamp": 1513273747662000,
  "duration": 893797,
  "binaryAnnotations": [
    {
      "key": "lc",
      "value": "unknown",
      "endpoint": {
        "serviceName": "user-history",
        "ipv4": "10.181.1.72",
        "port": 8080
      }
    }
  ]
}
```

May be related to https://github.com/jaegertracing/jaeger/issues/450

**Comment by yurishkuro** [comment]
@pavolloffay want to take a look? In #518 it seems all unit tests for `localEndpoint` test only the IP address, not the service name.

**Comment by adriancole** [comment]
FWIW "lc" stands for "local component" which is a way to qualify different
things within the same process. "localEndpoint" is the way to qualify the
process.

**Comment by pavolloffay** [comment]
I will look at it, IIRC service name is derived only from core annotations (client and server..)
