### ISSUE TITLE
[v2] Use health check extension in e2e test instead of /metrics

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5859]
In the current e2e tests we are using the metrics endpoint to check that the v2 binary is up and ready for tests:
```
   e2e_integration.go:98: Checking if Jaeger-v2 is available on http://localhost:8888/metrics
```

Since we already introduced a health check extension (#5831), we should be using that instead of /metrics.

Changes required:
  * [x] configure health check extension in other config files (#5831 only did it in all-in-one)
  * [ ] change e2e test to ping the /status endpoint of the health check extension instead of /metrics. Wait for statusOk in the JSON, not just HTTP 200.

**Comment by yurishkuro** [comment]
Current state: in #5861 all configs were added, but grpc-storage test failed because additional traces from WriteSpan endpoint are being generated (a big no-no). I am going to merge #5861 with a temporary override in grpc_test to continue using the original query service port for health check, but we need to identify the problem and remove the override for healthcheck endpoint. Surprisingly just switching to query port fixes the issue, while querying 13133 results in extra spans. My hypothesis is that the healthcheck endpoint is registered with tracing enabled, so when we hit if from the test it generates a trace from within the collector, and writing that trace generates the other traces for WriteSpan endpoint that we're seeing. We need to make sure that we do not let OTEL framework instantiate a tracer that indiscriminately traces everything. cc @Wise-Wizard

**Comment by yurishkuro** [comment]
Reproducer in https://github.com/jaegertracing/jaeger/pull/5861#issuecomment-2306270761

**Comment by yurishkuro** [comment]
It looks like most of the work here is done, but there is still one location that queries a different endpoint
```
$ rg HealthCheckEndpoint cmd/jaeger
cmd/jaeger/internal/integration/grpc_test.go
36:			HealthCheckEndpoint: fmt.Sprintf("http://localhost:%d/", ports.QueryHTTP),
```

**Comment by mahadzaryab1** [comment]
@yurishkuro how should we go about not generating the extra traces from the healthcheckextension?

**Comment by yurishkuro** [comment]
are we generating them now?

**Comment by mahadzaryab1** [comment]
@yurishkuro yeah I ran your reproducer code from the original PR and it looks to have the same failure

**Comment by yurishkuro** [comment]
Reproducer and fix https://github.com/jaegertracing/jaeger/pull/6113

**Comment by yurishkuro** [comment]
We don't generate extra trace from health extension, it's coming from grpc storage (issue #5971).
