### ISSUE TITLE
Cannot find operations in jaeger-ui, if there is '/' char in serviceName

### ISSUE THREAD

**Issue by niuhf0452** [jaegertracing/jaeger#586]
![image](https://user-images.githubusercontent.com/4718841/33645360-57b22334-da85-11e7-9c19-1b69ee845cf6.png)

**Comment by yurishkuro** [comment]
good catch.

cc @tiffon

**Comment by yurishkuro** [comment]
Re-booked as a UI issue https://github.com/jaegertracing/jaeger-ui/issues/138

**Comment by tiffon** [comment]
@yurishkuro after merging jaegertracing/jaeger-ui#140, I think this surfaced an issue in jaeger-query.

When running the hotrod demo with the service names to have `jaeger/` prepended now results in the following GET HTTP call to the query service for service `jaeger/customer`:

http://localhost:16686/api/services/jaeger%2Fcustomer/operations

The query service responds with the index.html.

**Comment by yurishkuro** [comment]
arrrg... Should we just switch to the `?service=` API?

**Comment by yurishkuro** [comment]
@tiffon we may have to switch the UI to `/api/operations?service=`, because I just ran a test (#736) and it doesn't look like Gorilla router we're using is able to deal with `/` in the middle of the parameter, even if it's url-encoded.

**Comment by tiffon** [comment]
@yurishkuro I think Gorilla might have a facility for handling this (if I followed correctly):

API: http://www.gorillatoolkit.org/pkg/mux#Router.UseEncodedPath

Related ticket: https://github.com/gorilla/mux/issues/77

Changes that are referenced:

- https://github.com/gorilla/mux/commit/0a192a193177452756c362c20087ddafcf6829c4
- https://github.com/gorilla/mux/commit/c9183aaddd2672bdebcc2d2192ed9c788b4af1e8

**Comment by yurishkuro** [comment]
true, I was able to fix the test, but I still think that we should do what we planned long time ago - only support `/api/operations?service=` API and remove all this duplicated / special-cased code from query service.
