### ISSUE TITLE
No trace in Jager UI

### ISSUE THREAD

**Issue by msn2708** [jaegertracing/jaeger#588]
Hello,

This seems like a config issue but was wondering if someone has seen this before.

I have setup the all-in-one backend on Docker Toolbox for Windows, 
IP: 192.168.99.100 

Frontend and other services running inside an Ubuntu running on a VMWare, 
IP: 192.168.159.129 

The Jaeger UI (http://192.168.99.100:16686/search) is reachable from the Ubuntu machine running on VMWware but none of the traces are being captured. 

Here is the error: 2017-12-05T19:16:07.113-0800	ERROR	log/logger.go:42	write udp  127.0.0.1:40481->127.0.0.1:6831: write: connection refused	 {"service": "route"} github.com/jaegertracing/jaeger/examples/hotrod/pkg/log.logger.Error /home/msn2708/GoCode/src/github.com/jaegertracing/jaeger/examples/hotrod/pkg/log/logger.go:42 github.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing.jaegerLoggerAdapter.Error /home/msn2708/GoCode/src/github.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing/init.go:58 github.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing.(*jaegerLoggerAdapter).Error :1 github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).flush /home/msn2708/GoCode/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:258 github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).processQueue /home/msn2708/GoCode/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/reporter.go:246
--

Any thoughts on what could be missing or how this situation can be corrected?

**Comment by yurishkuro** [comment]
> write udp 127.0.0.1:40481->127.0.0.1:6831

because you are not running the agent in the same namespace as the applications, you need to configure the clients to talk to 192.168.99.100:6831 instead of localhost:6831

**Comment by msn2708** [comment]
Thanks for the pointer Yuri. I modified this file /home/msn2708/GoCode/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/transport_udp.go and it is working now.

Wondering if this can/should be made into a configurable option?

**Comment by yurishkuro** [comment]
It is configurable: https://github.com/jaegertracing/jaeger-client-go/blob/master/config/config.go#L88

**Comment by msn2708** [comment]
Thank you for the clarification. I will close this out now.

**Comment by Juhibhadviya19** [comment]
Hello,
I have this simple python code, which gives below output:
_Initializing Jaeger Tracer with UDP reporter
Using sampler ConstSampler(True)
opentracing.tracer initialized to <jaeger_client.tracer.Tracer object at 0x7f83e7b579d0>[app_name=hello-world]
Hello, Juhi!

How can I see this trace on my UI, currently I can't see any services on Jaeger UI running on Kubernetes cloud.

Thanks a lot in advance. 
Reporting span a783c6a367bb999a:a783c6a367bb999a:0:1 hello-world.say-hello_

[hello.docx](https://github.com/jaegertracing/jaeger/files/2265742/hello.docx)
