### ISSUE TITLE
[es] Span write fails if index already exists due to race condition

### ISSUE THREAD

**Issue by jackychee** [jaegertracing/jaeger#589]
ES version is 5.1.1
{
    "level": "error", 
    "ts": 1513045072.7463179, 
    "caller": "app/span_processor.go:103", 
    "msg": "Failed to save span", 
    "error": "Failed to create index: elastic: Error 400 (Bad Request): index [jaeger-service-2017-12-12/CV-EQal-Q1KQ3vEyxG1W7g] already exists [type=index_already_exists_exception]", 
    "errorVerbose": "elastic: Error 400 (Bad Request): index [jaeger-service-2017-12-12/CV-EQal-Q1KQ3vEyxG1W7g] already exists [type=index_already_exists_exception]
Failed to create index
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).logError
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:191
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).createIndex
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:148
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:120
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:102
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:89
github.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126
github.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:57
github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65
runtime.goexit
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:2337", 
    "stacktrace": "github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:103
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:89
github.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126
github.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:57
github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65"
}

**Comment by yurishkuro** [comment]
There is a race condition in the span writer, and the [comment in the code](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/spanstore/writer.go#L142) calls it out:
```
// if there are multiple collectors writing to the same elasticsearch host, if the collectors pass
// the exists check above and try to create the same index all at once, this might fail and
// drop a couple spans (~1 per collector). Creating indices ahead of time alleviates this issue.
```

@black-adder did we envision any mechanisms for "creating indices ahead of time"?

Another, possibly a lot simpler alternative, would be to check if the error was specifically "index already exists".

**Comment by yurishkuro** [comment]
ES driver exposes the [Error struct](https://github.com/olivere/elastic/blob/release-branch.v6/errors.go#L62), which has `Error.Details.Type` string that could be checked against `"index_already_exists_exception"` (assuming that string value is stable).
