### ISSUE TITLE
Query can't read ES service data

### ISSUE THREAD

**Issue by jackychee** [jaegertracing/jaeger#590]
Query only return jaeger-query when i request  /api/services， But when i search jaeger-service-xxxx-xx-xx index in ES there other service exists,  i have even searched the traces  of other service from /search , what's wrong with it?

ES version 5.1.1
jaeger-query version 1.0.0

**Comment by yurishkuro** [comment]
@jackychee were you able to solve this?

**Comment by jackychee** [comment]
I try to reappear and then solve this problem,  and i will feedback to you in time.

**Comment by pavolloffay** [comment]
@jackychee did you manage to solve it? It's maybe related to #591

**Comment by pavolloffay** [comment]
@jackychee I will close this, I think it was fixed in https://github.com/jaegertracing/jaeger/pull/646. Feel free to reopen if the issue is still present.
