### ISSUE TITLE
timezones of ES writer and reader are inconsistent now

### ISSUE THREAD

**Issue by molon** [jaegertracing/jaeger#591]
writer.go
```
func indexNames(span *model.Span) (string, string) {
	spanDate := span.StartTime.Format("2006-01-02")
	return spanIndexPrefix + spanDate, serviceIndexPrefix + spanDate
}
```

reader.go
```
func indexWithDate(prefix string, date time.Time) string {
	return prefix + date.UTC().Format("2006-01-02")
}
```

I think users of jaeger(like me) should choose the timezone themself.
Follow the system timezone is the right style.
So the `indexNames` is ok, but the  `indexWithDate` shouldn't use UTC directly.

**Comment by yurishkuro** [comment]
yes, reader/writer must be at minimum consistent. I don't have strong opinion about whether it should be system tz or UTC. Making it configurable is an option.

Are you interesting in submitting a pul request?
