### ISSUE TITLE
Simplify bundling of UI assets

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5913]
Currently we use a build tag `ui` to force embedding of real UI assets into Jaeger binaries.  The tag is used in `cmd/query/app/ui/(placeholder|actual).go` files which both define identically named embedded file system. e.g. https://github.com/jaegertracing/jaeger/blob/8ad6ed02ae47b90340f1a7b3f9d8fa40bc27f52f/cmd/query/app/ui/actual.go#L17-L21

This creates unnecessary friction when running code locally with `go run`, one has to remember to add `-tags ui` in order to embed real UI. Without this tag we embed a fake `index.html` that renders an explanation on how to build UI assets.

## Proposal

Remove dependency on `ui` build tag. Combine `actual/placeholder.go` into a single file `assets.go` where we define differently named private variables and add a utility function (to be called from `cmd/query/app/static_handler.go`) to check of `actual`
embedded file system contains `index.html`, otherwise fallback onto `placeholder` file system (and log a warning that UI assets are not found).

The only downside of this approach is that we embed both actual and placeholder files, but since placeholder is just a single small html file, it's an easy price to pay for developer convenience.

**Comment by mahadzaryab1** [comment]
picking this up

**Comment by mahadzaryab1** [comment]
@yurishkuro PR ready for review at https://github.com/jaegertracing/jaeger/pull/5917
