### ISSUE TITLE
SPM is broken by OTEL's new version

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5982]
The PR #5968 is trying to upgrade to v0.109 and the SPM e2e test is consistently failing. It could be related to these breaking changes :

spanmetricsconnector: 
* Improve consistency between metrics generated by spanmetricsconnector. Added traces.span.metrics as default namespace ([#33227](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33227), [#32818](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32818))
* Default namespace for the generated metrics is traces.span.metrics now. | The deprecated metrics are: calls, duration and events. | The feature flag connector.spanmetrics.legacyLatencyMetricNames was added to revert the behavior.

Tasks:
  * [ ] understand what changes in OTEL and how it affects SPM in Jaeger
  * [ ] make corresponding code changes to compensate
  * [ ] provide backwards compatibility following Jaeger's policy https://github.com/jaegertracing/jaeger?tab=readme-ov-file#version-compatibility-guarantees

**Comment by FlamingSaint** [comment]
@yurishkuro I can take this up.

**Comment by yurishkuro** [comment]
@FlamingSaint sounds good

**Comment by shinigami-777** [comment]
hi @yurishkuro
There seems to be 2 solutions to this issue
1. To modify the SPM e2e test to check for metrics under the new namespace.
2. Use the Legacy metric names via the feature flag ```connector.spanmetrics.legacyLatencyMetricNames ```.
The latter seems easy to implement but the first one seems like a more future-proof solution.

**Comment by mahadzaryab1** [comment]
@yurishkuro i've tried out an approach to fix this - would you be able to review https://github.com/jaegertracing/jaeger/pull/6007?
