### ISSUE TITLE
[query] Switch to use OTEL's http/grpc servers

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#6026]
In #6023 we changed http/grpc servers in the query service to be configured via OTEL config structs, but we still have a custom implementation for creating the servers. We should fully switch to OTEL's implementations. This will be another breaking change because in OTEL the servers cannot share the same port, which is today supported in the query service via cmux.

**Comment by Garvit-77** [comment]
Hello @yurishkuro
I would like to give it a try

**Comment by yurishkuro** [comment]
@Garvit-77 go ahead

**Comment by mahadzaryab1** [comment]
@yurishkuro what should be passed in for `component.Host` in the `ToSever` method?

**Comment by yurishkuro** [comment]
When running in v2 mode we have the real host available in the extension. For v1 it's ok to pass noop, but we need to make sure that we would still get the metrics from these endpoints as we get today.

**Comment by Garvit-77** [comment]
`type Server struct {
	querySvc     *querysvc.QueryService
	queryOptions *QueryOptions

	conn          net.Listener
	grpcConn      net.Listener
	httpConn      net.Listener
	grpcServer    *grpc.Server
	httpServer    *httpServer
	separatePorts bool
	bgFinished    sync.WaitGroup
	telemetery.Setting
}`
As we're trying to completely switch to OTEL can't we change or remove the Server Struct ?
