### ISSUE TITLE
[jaeger-v2]: Fix Kafka E2E Test To Use Default Environment Variables

### ISSUE THREAD

**Issue by mahadzaryab1** [jaegertracing/jaeger#6027]
### Problem

- Part of #5229
- https://github.com/jaegertracing/jaeger/issues/5229#issuecomment-2374296714 summarizes the problem that we want to solve nicely

**Comment by mahadzaryab1** [comment]
@yurishkuro Would you be able to help me understand why we needed `createConfigWithEncoding`? Why could we not just create configuration files that had the desired values that we needed?

**Comment by yurishkuro** [comment]
Because we want to test the one official config we provide, not create copies of it that may become out of date.

**Comment by mahadzaryab1** [comment]
@yurishkuro got it! and does setting the environment variable take precedent over the config in the YAML file?

**Comment by yurishkuro** [comment]
It does not. If config has a fixed value the env variable is not going to affect it. Previously you could reference env variable from the config, but then you always have to provide the variable, otherwise the config is invalid. Now you could have both - a default value and a way to override it via env variable.

**Comment by mahadzaryab1** [comment]
> It does not. If config has a fixed value the env variable is not going to affect it. Previously you could reference env variable from the config, but then you always have to provide the variable, otherwise the config is invalid. Now you could have both - a default value and a way to override it via env variable.

@yurishkuro Thanks for the explanation! PR is ready for review at https://github.com/jaegertracing/jaeger/pull/6028.
