### ISSUE TITLE
[Feature]: Implement bearer token auth interceptor 

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger#6035]
> we should move upgradeContextWithBearerToken from plugin/storage/grpc/shared/grpc_client.go to be implemented as interceptor in pkg/bearertoken

Should be similar to the pkg/tenancy implementation.

Details: https://github.com/jaegertracing/jaeger/pull/6030#issuecomment-2387077052

**Comment by yurishkuro** [comment]
1) We should use client interceptors in `plugin/storage/grpc/shared/grpc_client.go`, currently it extracts token manually, even though it seems like the factory does attach interceptors
```
plugin/storage/grpc/factory.go
136:	opts = append(opts, grpc.WithUnaryInterceptor(bearertoken.NewUnaryClientInterceptor()))
137:	opts = append(opts, grpc.WithStreamInterceptor(bearertoken.NewStreamClientInterceptor()))
```

2) Another suspicious place:
```
plugin/metrics/prometheus/metricsstore/reader.go
25:	"github.com/jaegertracing/jaeger/pkg/bearertoken"
345:	return bearertoken.RoundTripper{
```

3) Interceptor are installed in `createGRPCServerLegacy` but not in `createGRPCServerOTEL` in `cmd/query/app/server.go`

**Comment by yurishkuro** [comment]
@chahatsagarmain I re-opened as there are other places that could use interceptors
