### ISSUE TITLE
[jaeger-v2] Consolidate v1 and v2 Configs For GRPC Storage

### ISSUE THREAD

**Issue by mahadzaryab1** [jaegertracing/jaeger#6041]
### Requirement

- Part of https://github.com/jaegertracing/jaeger/issues/5229
- See https://github.com/jaegertracing/jaeger/pull/6030/files#r1783513599 for more details

**Comment by yurishkuro** [comment]
Do we have / need a migration guide for grpc backend?

**Comment by mahadzaryab1** [comment]
@yurishkuro Created a migration guide [here](https://docs.google.com/document/d/1JhbgfC6XZQLuV7PmssgqnELnJSfX4uw1TZelIIu6ucc/edit)
