### ISSUE TITLE
Invalid use of noopHost in prod code

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#6049]
plugin/storage/grpc/factory.go:101
```
return f.config.ToClientConnWithOptions(context.Background(), componenttest.NewNopHost(), telset, clientOpts...)
```

  * when running in `v2` we should be able to pass a real Host initialized by OTEL Collector
  * when running in `v1` mode it's ok to keep using `componenttest.NewNopHost()` (it means we already made a breaking change where metrics are not reported from this client, if they ever were)

**Comment by TusharMohapatra07** [comment]
I would like to dive into the codebase and find a solution for this issue.

**Comment by chahatsagarmain** [comment]
Hi @yurishkuro , so do we need the same functionality of componenttest.NewNopHost() but utilizing Host interface in component  ?
