### ISSUE TITLE
big amount of dropped spans

### ISSUE THREAD

**Issue by mkabischev** [jaegertracing/jaeger#605]
Hi, we're testing jaeger at the moment and faced the problem with the huge amount of dropped spans.
First we started with zipkin and decided to switch to jaeger without any code modifications we use Zipkin v1 HTTP API and Elasticsearch as a storage.
Service produces ~250k spans per minute and in jaeger's we can see that it receives ~ the same number of spans (zipkin:spans_recd) but drops(spans_dropped) ~100k spans per minute. So a lot of traces are not full and there are a lot of warning like `invalid parent span IDs=1fe12a3f1e085cfc; skipping clock skew adjustment`.

We tried to increase queueSize from 2000(default value) to 300000k and also increased workersNum, but it didn't help at all.

According to metrics the queue is always full (queue_length=300k) and save_latency time looks ok (0.5q=50ms,0.9q=200ms,0.99q=1s).

Could you suggest what other metrics or configuration can help us, because that's only single service and 250k spans per minute is a small number from my point.

**Comment by yurishkuro** [comment]
In our experience spans can be dropped for two reasons: either the collectors are under-provisioned (not enough CPU quota or # of instances), or the storage is a bottleneck. It's worth looking at perf metrics of collectors and storage to see where your bottleneck is.

**Comment by mkabischev** [comment]
@yurishkuro thanks for the response. I found similar issue #439 and will try to add `index.translog.durability=async` to index settings.

**Comment by yurishkuro** [comment]
Feel free to ask questions on chat https://gitter.im/jaegertracing/Lobby
