### ISSUE TITLE
[jaeger-v2] Refactor ElasticSearch/OpenSearch Storage Configurations To Align With OTEL

### ISSUE THREAD

**Issue by mahadzaryab1** [jaegertracing/jaeger#6059]
### Requirement

In this issue, we want to align the configuration for elastic search and open search storage with OTEL (part of https://github.com/jaegertracing/jaeger/issues/5229)

### Problem

 - [x] All config fields are tagged with mapstructure such that they can be addressable from YAML via "good" names
 - [x] Configs implement Validate()
 - [x] Configs via YAML support the same defaults as in jaeger-v1
 - [x] Configs reuse standard elements of OTEL configs whenever possible, e.g. TLS, clientcfg, etc.
 - [x] Configuration looks "logical" and properly grouped, not flattened with long weird names
 - [x] We create a migration guide document with a table that lists v1 CLI flags and the corresponding v2 config fields

**Comment by mahadzaryab1** [comment]
@yurishkuro is a migration guide needed here?

**Comment by yurishkuro** [comment]
yes, certainly

**Comment by mahadzaryab1** [comment]
@yurishkuro this is the current configuration we have
```go
type Configuration struct {
	Servers                  []string               `mapstructure:"server_urls" valid:"required,url"`
	RemoteReadClusters       []string               `mapstructure:"remote_read_clusters"`
	Username                 string                 `mapstructure:"username"`
	Password                 string                 `mapstructure:"password" json:"-"`
	TokenFilePath            string                 `mapstructure:"token_file"`
	PasswordFilePath         string                 `mapstructure:"password_file"`
	AllowTokenFromContext    bool                   `mapstructure:"-"`
	Sniffer                  bool                   `mapstructure:"sniffer"` // https://github.com/olivere/elastic/wiki/Sniffing
	SnifferTLSEnabled        bool                   `mapstructure:"sniffer_tls_enabled"`
	MaxDocCount              int                    `mapstructure:"-"` // Defines maximum number of results to fetch from storage per query
	MaxSpanAge               time.Duration          `mapstructure:"-"` // configures the maximum lookback on span reads
	Timeout                  time.Duration          `mapstructure:"-"`
	BulkSize                 int                    `mapstructure:"-"`
	BulkWorkers              int                    `mapstructure:"-"`
	BulkActions              int                    `mapstructure:"-"`
	BulkFlushInterval        time.Duration          `mapstructure:"-"`
	Indices                  Indices                `mapstructure:"indices"`
	ServiceCacheTTL          time.Duration          `mapstructure:"service_cache_ttl"`
	AdaptiveSamplingLookback time.Duration          `mapstructure:"-"`
	Tags                     TagsAsFields           `mapstructure:"tags_as_fields"`
	Enabled                  bool                   `mapstructure:"-"`
	TLS                      configtls.ClientConfig `mapstructure:"tls"`
	UseReadWriteAliases      bool                   `mapstructure:"use_aliases"`
	CreateIndexTemplates     bool                   `mapstructure:"create_mappings"`
	UseILM                   bool                   `mapstructure:"use_ilm"`
	Version                  uint                   `mapstructure:"version"`
	LogLevel                 string                 `mapstructure:"log_level"`
	SendGetBodyAs            string                 `mapstructure:"send_get_body_as"`
}
```
Here are some groupings I see.

### Sniffer
- Enabled
- TLS Enabled 

### Bulk Processing 
- Size 
- Num Workers
- Num Actions
- Flush Interval

### Auth
Can be grouped under basic if we want to support more authentication types in the future
- Username 
- Password
- PasswordFilePath

Do you agree with the groupings above? Do you see any other groupings?

**Comment by yurishkuro** [comment]
I wonder if we can get rid of these if we switch to data streams

UseReadWriteAliases      
CreateIndexTemplates     
UseILM

**Comment by yurishkuro** [comment]
SendGetBodyAs - what are possible values? Should it be an enum?

**Comment by mahadzaryab1** [comment]
> SendGetBodyAs - what are possible values? Should it be an enum?

it looks to be all the http method types
```go
// SetSendGetBodyAs specifies the HTTP method to use when sending a GET request
// with a body. It is GET by default.
func SetSendGetBodyAs(httpMethod string) ClientOptionFunc {
	return func(c *Client) error {
		c.sendGetBodyAs = httpMethod
		return nil
	}
}
```

**Comment by mahadzaryab1** [comment]
> I wonder if we can get rid of these if we switch to data streams
> 
> UseReadWriteAliases CreateIndexTemplates UseILM

what are data streams in this context?

**Comment by tronda** [comment]
@mahadzaryab1 Amazon described the data stream feature in this video:
https://www.youtube.com/watch?v=Mm3GFTt8wMA

I think this comes from ElasticSearch originally so the concept is probably the same.

**Comment by mahadzaryab1** [comment]
@yurishkuro final PR is ready for review at https://github.com/jaegertracing/jaeger/pull/6090
