### ISSUE TITLE
[Bug]: Jaeger UI Lacks service.name in Process section.

### ISSUE THREAD

**Issue by feldentm-SAP** [jaegertracing/jaeger#6070]
### What happened?

The Jaeger UI seems to remove the service.name resource attribute as some sort of data deduplication as it is shown.
This is confusing for OTLP spans as the content does not reflect what has been sent.

### Steps to reproduce

Seems to happen unconditionally.
It is not clear to me if jaeger all in one self spans already show this behaviour as the data claims that he format is "otlp" but the spans seem not to contain any service attributes.

### Expected behavior

What is "serviceName" in JSON should be exposed as service.name, at least if it has been ingested like that.

### Relevant log output

(see screenshots)

### Screenshot

![Image](https://github.com/user-attachments/assets/c9b36340-1f81-409d-88fd-3849e3e4d951)
![Image](https://github.com/user-attachments/assets/c56c6dcb-67f1-4013-b61e-eb0806ef0160)
![Image](https://github.com/user-attachments/assets/12c0f81a-46c4-4410-a35a-796dae301ddf)

### Jaeger backend version

docker jaegertracing/all-in-one:latest (1.60)

### SDK

otel collector from docker otel/opentelemetry-collector-contrib:latest

### Pipeline

Java SE / Java Otel SDK -> Otel Collector -> Jaeger

### Stogage backend

none

### Operating system

linux vm

### Deployment model

docker

### Deployment configs

unmodified; should not matter here

**Comment by yurishkuro** [comment]
In the second span service name is clearly displayed: Jave OTEL test. The JSON follows jaeger schema, not otlp.
