### ISSUE TITLE
How to support composable command line arguments

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#608]
Right now query/collector binaries support `--span-storage.type` CLI switch. However, regardless of what value is provided there, all other CLI switches for both Cassandra and ES configurations are always available if one runs `-h`. This makes modularity more difficult to support.

NB: the same issue will arise if we try to support plugins (#422).

### Ideal state

Cassandra CLI switches are only displayed when `--span-storage.type=cassandra` is specified.

### Problem

CLI switches must all be pre-declared before their values are parsed / accessible to main. So if we wait for `--span-storage.type` to be parsed it's too late to add storage switches.

### Proposed solution

Remove `--span-storage.type` switch and only support it via env variable. The main logic will change as follows:

  * read storage type (or plugins directory path) from env variable
  * instantiate respective factories
  * register the main CLI switches and ask all plugin factories to register their switches as well
  * ones cobra.Command is being executed, the switch values are readable by both main and the plugin factories

cc @black-adder @pavolloffay @objectiser @jpkrohling

**Comment by frankgreco** [comment]
For plugins, if `plugin.Open` was evoked before `rootCmd.AddCommand(myCmd)`, then all of the plugins `init` functions would be evoked before the command was added. If, in a plugins `init` function, they had `cmd.Flags()....`, then it should be possible to dynamically construct a commands flags.

**Comment by yurishkuro** [comment]
we're not using globals for flags, so this is not an issue, the individual plugin factory can have a method to register flags with viper/command.
