### ISSUE TITLE
[crossdock] Replace sampling calls to agent with calls to collector

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#6083]
Part of #4739 and #6081

In the crossdock integration tests the test driver tries to connect to the "agent" and test its sampling endpoint response. We need to
  * [x] redirect it to query the sampling endpoint in the collector instead
  * [ ] remove "agent" related code

cc @mahadzaryab1

**Comment by sriganeshres** [comment]
@yurishkuro i want to work on this issue as it is my first contribution to this repository can you guide me.

**Comment by yurishkuro** [comment]
@mahadzaryab1 volunteered to guide

**Comment by Garvit-77** [comment]
Hey @yurishkuro 
I was looking into this issue but faced some hurdles majorly :
what are Endpoints for OTEL Collector ?

**Comment by yurishkuro** [comment]
https://www.jaegertracing.io/docs/1.62/apis/#remote-sampling-configuration-stable

**Comment by inosmeet** [comment]
Do we only need to change the sampling URL endpoint, or should we also refactor the naming? Or am I thinking about this the wrong way?
@yurishkuro @mahadzaryab1

**Comment by yurishkuro** [comment]
@inosmeet I updated description. Not sure what you mean by "refactor the naming"
