### ISSUE TITLE
Add integration test for hotrod on k8s

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#6086]
There is a sample setup for HotROD + all-in-one combo in `./examples/hotrod/kubernetes`. We already have integration tests that validate this combo (`.github/workflows/ci-docker-hotrod.yml`), it would be good to extend those tests to cover the k8s deployment as well, so that we can guarantee that the provided configs are valid.

**Comment by PratikFandade** [comment]
Hi @yurishkuro, I'd like to contribute to the repository and noticed this issue. Since it will be my first time working on this repo, could you provide some guidance for me to get started?

**Comment by src1026** [comment]
Hi @yurishkuro ! I'd love to look at this issue if possible. Thank you!
