### ISSUE TITLE
Package static assets inside the query-service binary

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#609]
Currently we copy static assets directory to the docker image separately and point the query service to it using cli switch.

Some people swear by https://github.com/jteeuwen/go-bindata or its extension https://github.com/elazarl/go-bindata-assetfs.

This will be especially useful if we support non-Docker packaging (#426).

**Comment by pavolloffay** [comment]
Here is a nice list of alternatives https://github.com/shurcooL/vfsgen#alternatives

I plan to use one for hotrod to fix https://github.com/jaegertracing/jaeger/pull/694#issuecomment-366755805

**Comment by eundoosong** [comment]
This feature looks interesting and I found hotrod already merged with go-bindata-assetfs (https://github.com/jaegertracing/jaeger/pull/702)
I'll have a look for contribution. (would be good start of contribution as a begginer in jaeger backend :) )
