### ISSUE TITLE
[jaeger-v2] Add Meter Provider To Telemetry Settings

### ISSUE THREAD

**Issue by mahadzaryab1** [jaegertracing/jaeger#6127]
### Requirement

We're currently using no-op meter providers in the code instead of propagating the provider from OTEL. To change this, we need to do the following: 
- [ ] Add OTEL's meter provider to https://github.com/jaegertracing/jaeger/blob/main/pkg/telemetery/settings.go#L16-L22 
- [ ] Propagate this setting to places where `noopmetric.NewMeterProvider()` is used

**Comment by akstron** [comment]
Hi @mahadzaryab1 we should be adding `LeveledMeterProvider` instead of `MeterProvider`, as I see `MeterProvider` is deprecated.

**Comment by mahadzaryab1** [comment]
@akstron yes that’s correct!

**Comment by yurishkuro** [comment]
Still see two more places in non-test code
```
$ rg noopmetric.NewMeterProvider
cmd/collector/app/handler/otlp_receiver.go
77:				return noopmetric.NewMeterProvider()
79:			MeterProvider: noopmetric.NewMeterProvider(),

cmd/collector/app/handler/zipkin_receiver.go
71:				return noopmetric.NewMeterProvider()
73:			MeterProvider: noopmetric.NewMeterProvider(),
```

**Comment by mahadzaryab1** [comment]
@yurishkuro Those are in the context of v1 - can we do anything there?

**Comment by yurishkuro** [comment]
Fair enough, we can close this.
