### ISSUE TITLE
[Feature]: ENV or CLI arg to listen on OTLP on all interfaces

### ISSUE THREAD

**Issue by codefromthecrypt** [jaegertracing/jaeger#6207]
### Requirement

Right now, if you start jaeger v2, it listens for OTLP on localhost. This means docker hostnames don't connect. I would like an option to use an ENV value or CLI arg to listen on all interfaces.

### Problem

Without this, I need to write a config file for something easy to do in other go daemons like otel-tui or ollama. I would like a simpler experience, and most importantly one that doesn't risk making other config errors.

### Proposal

any env or CLI arg would be great

**Comment by codefromthecrypt** [comment]
I found this out trying https://github.com/open-telemetry/opentelemetry.io/pull/5575 as I was using docker to run the openai instrumentation example. Then, eventually I noticed some listen ports default to localhost, and noticed flags are not supported https://docs.google.com/document/d/18B1yTMewRft2N0nW9K-ecVRTt5VaNgnrPTW1eL236t4/edit?tab=t.0

**Comment by yurishkuro** [comment]
updated docs - this behavior can be changed using `--set` overrides.

**Comment by codefromthecrypt** [comment]
excellent. thanks!
