### ISSUE TITLE
Ensure all servers listen on 0.0.0.0

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#6209]
The upstream issue with 0.0.0.0 vs. local host strikes again (#6207).

* [ ] ensure that all servers are listening on 0.0.0.0 (or `:port`, which is equivalent)
* [ ] ensure that all servers log this endpoint at startup (we may be only logging ports in some places)
* [ ] why didn't our CI for hotrod/all-in-one catch this?

Related https://github.com/open-telemetry/opentelemetry-collector/issues/11713

**Comment by yurishkuro** [comment]
1. I was referring to HotROD integration tests that includes hotrod app sending data via OTLP to all-in-one
  2. I am aware of those two ports, my question was about all other ports that jaeger opens
  3. your curl command is not authoritative as some of the endpoints do not accept GET requests so getting 404 does not mean misconfiguration. If anything it confirms the opposite - the server has to be reachable to respond with 404.
  4. same point as in 2 above

**Comment by pradeeptac** [comment]
1. I was referring to HotROD integration tests that includes hotrod app sending data via OTLP to all-in-one ---> Thanks for clarifying! will check the HotROD Integration test and update the conversation.
3. the server has to be reachable to respond with 404. ---> Yaa actually, my point was the same. 404 means reachable. and the curl gave 404 with the --set receivers.otlp.protocols.http.endpoint=0.0.0.0:4318 --set receivers.otlp.protocols.grpc.endpoint=0.0.0.0:4317 over-rides . Without setting above over-rides, it was giving "Recv failure: Connection reset by peer jaeger". 
2 and 4. question was about all other ports that jaeger opens ---> Understood. would check for the rest of the ports that Jaeger opens and if the hostPorts are logged. 

appreciate your inputs! Thanks!

**Comment by pradeeptac** [comment]
Did a quick check on [1] , for the jaeger v2 docker CI, we do set the below [over-rides in docker-compose-v2.yml](https://github.com/jaegertracing/jaeger/blob/main/examples/hotrod/docker-compose-v2.yml#L7) . This should allow the hotrod example to send metrics to otlp collector [https://github.com/jaegertracing/jaeger/blob/main/examples/hotrod/docker-compose-v2.yml#L29](over http://jaeger:4318). 
`
- --set=receivers.otlp.protocols.grpc.endpoint="0.0.0.0:4317"
- --set=receivers.otlp.protocols.http.endpoint="0.0.0.0:4318"
`

**Comment by yurishkuro** [comment]
Right, but we added them _after_ the OTEL upgrade was done and presumable out build was still green. I am verifying that now: #6226

**Comment by pradeeptac** [comment]
Thanks for taking it forward @yurishkuro ! Was trying to follow various issues around this. 
1. #6231 ---> We are introducing an environment variable JAEGER_LISTEN_HOST which gets used from all-in-one/v2 config. This defaults to localhost when not defined. In case of running from docker, it overrides to 0.0.0.0 
2. [Suppress warning about 0.0.0.0](https://github.com/open-telemetry/opentelemetry-collector/issues/11713) ---> As a result of running at port 0.0.0.0 from inside docker, we get an warning as below currently which needs to be suppressed appropriately.
```
Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks.
```
3. ensure that all servers log this endpoint at startup (we may be only logging ports in some places) ---> Initial Point 3 of this Issue still needs to be answered. Will check and update the conversation.
