### ISSUE TITLE
[Bug]: cassandra container never becomes healthy

### ISSUE THREAD

**Issue by akstron** [jaegertracing/jaeger#6215]
### What happened?

Post addition of password-based authentication, the Cassandra container spawned by the docker-compose never becomes healthy. This is because the username and password is not provided to the health check cmd.

![Image](https://github.com/user-attachments/assets/adc28254-549f-420d-9013-af280c7d04f0)

Upon checking health check stat using: `docker inspect --format "{{json .State.Health }}" "v4-cassandra-1" | jq`

![Image](https://github.com/user-attachments/assets/773c6e6f-2ec7-48bb-b0b9-1b756f9fb67a)

### Steps to reproduce

1. `docker compose -f "docker-compose/cassandra/v4/docker-compose.yaml" up -d`

### Expected behavior

1. Getting a `healthy` status at some point and no authentication error logs.

### Relevant log output

```shell
 "Status": "unhealthy",
  "FailingStreak": 9,
  "Log": [
    {
      "Start": "2024-11-16T13:37:50.300599482Z",
      "End": "2024-11-16T13:37:50.659393355Z",
      "ExitCode": 1,
      "Output": "Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': AuthenticationFailed('Remote end requires authentication')})\n"
    },
    {
      "Start": "2024-11-16T13:38:20.658710087Z",
      "End": "2024-11-16T13:38:21.009395221Z",
      "ExitCode": 1,
      "Output": "Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': AuthenticationFailed('Remote end requires authentication')})\n"
    },
```

### Jaeger backend version

Both v1 and v2

### Stogage backend

Cassandra v4

**Comment by yurishkuro** [comment]
What about these CI runs on main?

https://github.com/jaegertracing/jaeger/actions/runs/11843397266

**Comment by akstron** [comment]
> What about these CI runs on main?
> 
> https://github.com/jaegertracing/jaeger/actions/runs/11843397266

This is because the health check is done here: https://github.com/jaegertracing/jaeger/blob/eb6c5c907d349667d9921b9722f39bdd8b97dcf1/plugin/storage/cassandra/schema/docker.sh#L28C1-L44C5

which is being used here: https://github.com/jaegertracing/jaeger/blob/eb6c5c907d349667d9921b9722f39bdd8b97dcf1/scripts/cassandra-integration-test.sh#L77C2-L79C1

So, when I tried to bypass `apply_schema` for https://github.com/jaegertracing/jaeger/pull/5922 I ran into this issue that cassandra was not up.
