### ISSUE TITLE
Promote mahadzaryab1 to Maintainer

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#6264]
Mahad Zaryab (@mahadzaryab1) has continued his unstoppable streak of amazing pull requests (39!) and is now formally meets all the [requirements for becoming a maintainer](https://github.com/jaegertracing/jaeger/blob/main/GOVERNANCE.md#becoming-a-maintainer).

Examples of non-trivial PRs:
  * #5878
  * Normalizing/standardizing v2 configurations
    * #5937 
    * #5998
    * #5949 
    * #6042
    * #6060
    * #6080
  * Migrating to OTEL helpers for servers & tls
    * #6079
    * #6055
    * #6121 
  * Ongoing work on Storage V2 API
    * #6216 
    * #6221

I propose to promote him to full Jaeger Maintainer role.

**Comment by jkowall** [comment]
+1! Great stuff

**Comment by pavolloffay** [comment]
+1

**Comment by albertteoh** [comment]
+1 keep it up, @mahadzaryab1!

**Comment by yurishkuro** [comment]
Nomination seconded. Starting 5 days countdown.

**Comment by yurishkuro** [comment]
Nomination is accepted. 

Congratulation @mahadzaryab1 🎉 🎉 🎉 

It's awesome to have you on board!

**Comment by mahadzaryab1** [comment]
Thank you so much everyone! Super excited to be onboard and to continue pushing this great project forward.
