### ISSUE TITLE
Glide issue is fixed now, we don't need the warning in Makefile any more.

### ISSUE THREAD

**Issue by kxxoling** [jaegertracing/jaeger#629]
While playing with the examples/hotrod demo, I received a warning of using glide 0.12.3 instead of glide 0.13 because of this issue: https://github.com/Masterminds/glide/issues/745 . Now this is fixed, and works well on my machine:

```
$ glide --version
glide version v0.13.1
```

**Comment by yurishkuro** [comment]
would you like to put a PR?

**Comment by kxxoling** [comment]
Here it is: https://github.com/jaegertracing/jaeger/pull/630
