### ISSUE TITLE
[Bug]: kafka: cannot connect to TLS managed kafka

### ISSUE THREAD

**Issue by edefaria** [jaegertracing/jaeger#6334]
### What happened?

Using v1.64.0.

The PR #6270, change the way to load TLS on kafka.

My TLS kafka configuration on 1.64:
`"TLS":{"CAFile":"","CAPem":"[REDACTED]","IncludeSystemCACertsPool":false,"CertFile":"","CertPem":"[REDACTED]","KeyFile":"","KeyPem":"[REDACTED]","MinVersion":"","MaxVersion":"","CipherSuites":null,"ReloadInterval":0,"Insecure":false,"InsecureSkipVerify":false,"ServerName":""}`

My TLS kafka option before 1.64:
`"TLS":{"Enabled":true,"CAPath":"","CertPath":"","KeyPath":"","ServerName":"","ClientCAPath":"","CipherSuites":null,"MinVersion":"","MaxVersion":"","SkipHostVerify":false,"ReloadInterval":0}`

The new configuration has `IncludeSystemCACertsPool:false` by default, it should be possible to set IncludeSystemCACertsPool to true, or issue related to the new code loading TLS kafka.

### Steps to reproduce

1. Run jaeger-collector/jaeger-ingester with kafka + TLS producer/consumer enabled without ca/cert loaded.
2. Crash to connect to remote kafka with signed certificate.
3. See Relevant log output

### Expected behavior

It should work as before.

### Relevant log output

```shell
{"level":"fatal","ts":1733844390.6674302,"caller":"collector/main.go:73","msg":"Failed to init storage factory","error":"kafka: client has run out of available brokers to talk to: 21 errors occurred:\n\t* unexpected EOF\n\t* unexpected EOF\n\t* EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n","stacktrace":"main.main.func1\n\tgithub.com/jaegertracing/jaeger/cmd/collector/main.go:73\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\tgithub.com/jaegertracing/jaeger/cmd/collector/main.go:150\nruntime.main\n\truntime/proc.go:272"}

{"level":"fatal","ts":1733842843.1473405,"caller":"ingester/main.go:71","msg":"Unable to create consumer","error":"kafka: client has run out of available brokers to talk to: 21 errors occurred:\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n","stacktrace":"main.main.func1\n\tgithub.com/jaegertracing/jaeger/cmd/ingester/main.go:71\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\tgithub.com/jaegertracing/jaeger/cmd/ingester/main.go:107\nruntime.main\n\truntime/proc.go:272"}
```

### Jaeger backend version

v1.64.0

### Deployment configs

```shell

```

**Comment by yurishkuro** [comment]
@mahadzaryab1 we missed something in the upgrade, perhaps we need to set that flag manually if OTEL struct doesn't expose it.

**Comment by yurishkuro** [comment]
@edefaria thanks for reporting. Restoring previous behavior in #6335
