### ISSUE TITLE
ElasticSearch 6.x support

### ISSUE THREAD

**Issue by secat** [jaegertracing/jaeger#637]
Do you have plan to support the ElasticSearch backend version 6.x?

The [github.com/olivere/elastic](https://github.com/olivere/elastic/releases/tag/v6.1.1) package version v6.1.1 has been released.

**Comment by yurishkuro** [comment]
@secat is there something in Jaeger that's not working with ES 6.x?  We made one change long time ago to support 6.x - https://github.com/jaegertracing/jaeger/pull/301.

**Comment by secat** [comment]
@yurishkuro I didn't try it yet with ElasticSearch >= 6.x.

I have only scanned the `glide.yaml` file and saw that the currently used [ElasticSearch client](https://github.com/jaegertracing/jaeger/blob/master/glide.yaml#L41) version was [v5.0.39](https://github.com/jaegertracing/jaeger/blob/master/glide.yaml#L42).

Since it was not the ElasticSearch client version `v6.1.1` that was released today, I concluded that the ElasticSearch backend version 6.x was not supported.

**Comment by yurishkuro** [comment]
I'll update the docs.

**Comment by japgolly** [comment]
In light of https://github.com/jaegertracing/documentation/pull/3/files, this should be reopened.

**Comment by pavolloffay** [comment]
@yurishkuro I have noticed that you are added ES6 support to the docs https://github.com/jaegertracing/jaeger/commit/2d64ba27ccb683e41679b9090eaaa2dfd5e120c7. 

The ES client we are pulling is compatible with ES 5.x https://github.com/olivere/elastic#releases. 
There are issues when running jaeger with ES6 e.g. https://github.com/jaegertracing/jaeger/issues/665. 

I think it's better to remove the official support from the docs.

**Comment by yurishkuro** [comment]
I am not clear how #665 is specific to ES 6.x

**Comment by pavolloffay** [comment]
I will close this, there are not know problems with ES 6.x in jaeger.
