### ISSUE TITLE
[Feature]:  How to handle the display of unreported parent spans in OpenTelemetry tracing

### ISSUE THREAD

**Issue by JellyTony** [jaegertracing/jaeger#6402]
### Requirement

wu

### Problem

OpenTelemetry currently requires the parent spans to be reported in order for child spans to be correctly associated. However, in some systems, the parent span may not be reported. This leads to incomplete traces in the system. The goal is to allow child spans to be correctly displayed even when their parent spans are missing or not reported.

**Comment by yurishkuro** [comment]
I don't understand what the problem is. Jaeger always displays the trace, whether it's complete or not. So what is it that you're looking for as enhancement?

**Comment by JellyTony** [comment]
> I don't understand what the problem is. Jaeger always displays the trace, whether it's complete or not. So what is it that you're looking for as enhancement?

Some systems might not report span information, resulting in missing spans. However, they will generate spans and pass them to upstream services. This could lead to incomplete tracing spans and missing parent spans. Can we ensure that even if a parent span is missing, the hierarchy in the trace diagram can still be displayed correctly?

**Comment by yurishkuro** [comment]
Jaeger displays the data that it receives, it cannot invent what it cannot see. You need to take measures to ensure that your services are properly emitting tracing data.
