### ISSUE TITLE
Remove OTEL/contrib dependency on plugin/storage/es/spanstore/dbmodel

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#6410]
Part of #6408 (please read that first)

`logzioexporter` depends on `plugin/storage/es/spanstore/dbmodel`.

This is a completely silly dependency that is easy to remove. I only see it in `OTEL/contrib/exporter/logzioexporter/logziospan.go`

* [ ] copy whichever code is needed by logziospan.go to OTEL/contrib
* [ ] move `plugin/storage/es/spanstore/dbmodel` to `plugin/storage/es/spanstore/internal/dbmodel`

**Comment by ary82** [comment]
Hi @yurishkuro, I'm new to the repository. I'm interested in trying this out

**Comment by zzzk1** [comment]
`logziospan.go` relies on two factors.

- /jaeger/model
- /jaeger/plugin/storage/es/spanstore/dbmodel

we should first copy them to `logziospan.go` and wait for the changes to be accepted. After that, we can move the `dbmodel.go` to its new location. @yurishkuro Did I understand it correctly?

**Comment by yurishkuro** [comment]
no we do not want to cope /model, only the packages specified in the description.
