### ISSUE TITLE
Enable usage of adjusters in api_v2 and api_v3 handlers

### ISSUE THREAD

**Issue by mahadzaryab1** [jaegertracing/jaeger#6417]
During the process of building out the v2 query service, we noticed that the adjusters were not being used in the api_v2 and api_v3 handlers. In this issue, we want to enable the usage of the adjusters by default in the v1 query service and expose a flag to turn it off. This will then make the migration to the v2 query service easier. 

### Tasks
- [x] Update protobuf requests for api_v2 and api_v3 to accept a `raw_traces` flag: https://github.com/jaegertracing/jaeger-idl/pull/114
- [x] Update handlers to use adjusters: https://github.com/jaegertracing/jaeger/pull/6423

**Comment by yurishkuro** [comment]
let's try to manage linkage between issues. I just add this is as a child of #6337.
