### ISSUE TITLE
Consider renaming SPAN_STORAGE env var to SPAN_STORAGE_TYPE

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#642]
I noticed this discussion about Jaeger Helm chart: https://github.com/kubernetes/charts/pull/3109#discussion_r160825591

The original `--span-storage.type` cli switch that was deprecated in #625 in favor of SPAN_STORAGE env var was actually previously mapped to SPAN_STORAGE_TYPE env var.

We could achieve better backwards compatibility by renaming
  * SPAN_STORAGE => SPAN_STORAGE_TYPE
  * DEPENDENCY_STORAGE => DEPENDENCY_STORAGE_TYPE (for consistency).

Worth it?  It does take more characters to type.

cc @black-adder @objectiser @pavolloffay

**Comment by black-adder** [comment]
makes sense, given the refactor was technically a breaking change, anything to make the transition easier is worth it.

**Comment by pavolloffay** [comment]
+1 on this

**Comment by objectiser** [comment]
+1
