### ISSUE TITLE
Incorrect trace count returned when in UI when not using filters with Cassandra storage

### ISSUE THREAD

**Issue by Nekuromento** [jaegertracing/jaeger#652]
Jaeger query server returns inconsistent results when searching latest traces when configured to use Cassandra as storage.
This issue only manifests when no filters are specified except for query limit.
This issue only manifests when all components are deployed to remote machines (doesn't reproduce with all-in-one container).
This issue does not manifest when using ElasticCache as storage.

Expected:
Search query returns N traces. Where N equals to limit assuming storage has at least N results.

Actual:
Search query returns ~ N/2 traces (When limit is 20, UI returns 10-11 traces)

Tested with Jaeger release v0.9 and v1.1

**Comment by black-adder** [comment]
refer to https://github.com/jaegertracing/jaeger/issues/166

I'll document this issue somewhere
