### ISSUE TITLE
Documentation for Sampling Strategy

### ISSUE THREAD

**Issue by saada** [jaegertracing/jaeger#667]
I spent hours trying to figure out why my traces were rarely showing up on the UI and was baffled that the default was to use RemoteSampling in the Java client. What's more confusing is that the Jaeger agent doesn't have any docs on configuring sampling strategy. 

Can we add docs for configuring strategy on Jaeger agent and explain each strategy?

**Comment by vprithvi** [comment]
I agree that sampling documentation can be improved. 
We have some at https://github.com/jaegertracing/jaeger-client-java#testing

Sampling is performed when traces are created, and are hence controlled by the client. Do you remember where you were looking for documentation?
