### ISSUE TITLE
Can unfinished span caused by some-db-deadlock be recognized by jaeger?

### ISSUE THREAD

**Issue by ext2xhb** [jaegertracing/jaeger#677]
We are planning to use jaeger to inspect the database-sql-execute in lots of services. some-time, the sql-execution will dead-locked unpredictable.
this dead-lock will leave some span un-finished. It seems these un-finished span will not be reported by jaeger.....

**Comment by yurishkuro** [comment]
unfinished spans are not currently reported by Jaeger clients. 

Related issue https://github.com/jaegertracing/jaeger-client-java/issues/231

**Comment by snpai** [comment]
@yurishkuro would you be open to a pull request for this?

**Comment by yurishkuro** [comment]
closing in favor of #729
