### ISSUE TITLE
query-service - Search all services

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger#683]
From jaegertracing/jaeger-ui#180:

>The webui does not presently permit a search to be run until a service is selected.
>
>This is awkward; the UI must often be reloaded to see new services. More importantly it makes it impossible to search for a tag or span name across all services. This becomes especially important if you're sharding your services to deal with #38.

cc @ringerc

**Comment by tiffon** [comment]
Closing as this is a dupe.

**Comment by ringerc** [comment]
Sorry. I didn't find the old one.​
