### ISSUE TITLE
cannot query for minduration and tags simultaneously

### ISSUE THREAD

**Issue by rbtcollins** [jaegertracing/jaeger#690]
This is presumably known already, but its going to be quite a sharp limit for us as we're using tags to separate out different clusters, and that effectively means we cannot use minduration queries at all :(.

```

Status | 400
-- | --
Status text | Bad Request
URL | /api/traces
Query | end=1518034550576000&limit=2000&lookback=2d&maxDuration&minDuration=20s&operation=XXX&service=YYY&start=1517861750576000&tags=%7B%22http.status_code%22%3A%22503%22%7D
Response body | {   "data": null,   "total": 0,   "limit": 0,   "offset": 0,   "errors": [     {       "code": 400,       "msg": "Cannot query for tags when 'minDuration' is specified"     }   ] }
```

**Comment by liukai2012** [comment]
@rbtcollins Do you know why the limit exists?

**Comment by yurishkuro** [comment]
this is essentially the same reason as #166

**Comment by liukai2012** [comment]
@yurishkuro if i use es as a backend storage, can I remove the limit

**Comment by yurishkuro** [comment]
to my knowledge queries in ES should always work

**Comment by liukai2012** [comment]
Ok, Thanks

**Comment by yurishkuro** [comment]
Closing in favor of #166
