### ISSUE TITLE
scratch docker image does not cooperate with, appears to be, Marathon

### ISSUE THREAD

**Issue by radekg** [jaegertracing/jaeger#695]
When deploying the agent, query or collector image on dcos, it appears that Marathon tries to call /bin/sh inside of the container. This fails because the scratch image does not supply /bin/sh. Removing / changing `FROM scratch` to `FROM alpine:latest` resolves this problem. Current, when deploying on DCOS, the following error is returned:

```
I0212 15:30:18.052094 25140 executor.cpp:160] Starting task jaeger_ui.a0cc3e84-1009-11e8-bbd0-e25334567aec
container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory".
```

**Comment by jpkrohling** [comment]
While the solution looks simple, I fear it's not the right one... Would you have more information about *why* Marathon is trying to call `/bin/sh`? Are you able to get this down to the docker command it uses to start the container?

**Comment by radekg** [comment]
I'm short on details but I believe it automatically wraps whatever command is given to with `/bin/sh -c '...'`. No idea why it would do so: https://jira.mesosphere.com/browse/MARATHON_UI-160

**Comment by radekg** [comment]
It basically assumes existence of `/bin/sh`, which, I agree, is not very nice. So please accept it as is.

**Comment by radekg** [comment]
Here's more details and a solution:

I was trying to add additional parameters to agent, collector and query services. While doing so, I was using the `"cmd": "/go/bin/<service>-jaeger --additional-arguments..."`. However, as documented here: https://mesosphere.github.io/marathon/docs/native-docker.html#command-vs-args, when using `cmd`, Marathon will automatically wrap the command in `/bin/bash -c '...'`.

In order to prevent that, one should use `"args": ["/go/bin/<service>-linux", "--arguments...", "..."]`. This method works.

**Comment by yurishkuro** [comment]
@radekg is this something that needs to change in Jaeger Dockerfiles, or it was in your own file?

**Comment by radekg** [comment]
It appears to be happening with Marathon only. As described above, using args instead of a cmd solves the problem. So no need to change anything in existing Dockerfiles.

The dowside is, Marathon does not expand env vars in args. Leaving this here in case anybody hits that in the future.

**Comment by ja8zyjits** [comment]
@radekg did you find any solution for this?
Iam using 
`CMD ["/main"]`

It works perfectly in local system, but in dcos it exits with code 0, no error as such.

**Comment by ja8zyjits** [comment]
Got the solution, I was trying to use `fmt.Scanln` for deploying a long running go app in marathon. But it somehow exits in Marathon. Follow these solutions in such case, https://stackoverflow.com/questions/9543835/how-best-do-i-keep-a-long-running-go-program-running
