### ISSUE TITLE
Problem with "/metrics" link on production environment

### ISSUE THREAD

**Issue by manpreetsingh6** [jaegertracing/jaeger#697]
Jaeger is deployed using the production template at https://github.com/jaegertracing/jaeger-kubernetes

If I open jAEGER UI with metrics "http://JAEGERUIDNS/metric" link it shows logs in zip format and file started downloading which Prometheus could not read. Any help with Prometheus integration for Jaeger metrics would be appreciated.

This works well with Jaeger all in one image.

**Comment by yurishkuro** [comment]
Have you tried simple curl? Zip wouldn't be generated if the client didn't specify it can support it

**Comment by manpreetsingh6** [comment]
@yurishkuro Thanks for your response. 

But the problem is when I am using All-IN-ONE image and using integrating "JAEGERUI/metric"  with Prometheus I can see Jaeger metrics in Prometheus. As I explained if I am using production template and integrating "JAEGERUI/metric" with the same Prometheus I can't find the metrics.

If you could explain if I need to make any changes at Prometheus level, would really be helpful.

**Comment by yurishkuro** [comment]
I was able to reproduce, will take a look.

Which metrics are you specifically interested in from the Query/UI service?

**Comment by yurishkuro** [comment]
Now that I added this fix #724, I am thinking that it may not be such a good thing. According to this issue https://github.com/prometheus/prometheus/issues/2788, it's normal and expected that the `/metrics` endpoint returns text+gzip.

**Comment by Monnoroch** [comment]
And yet this is indeed a problem. Also, being able to open the metrics URL in a browser is a major convenience sometimes. If only for exploring what metrics the binary exports. Thanks for the fix!

**Comment by yurishkuro** [comment]
> Also, being able to open the metrics URL in a browser is a major convenience sometimes. 

 I agree, but I'm not sure what we can do here, since for production usage gzipping the scraping endpoint is certainly recommended for Prometheus. Maybe there's a Chrome plugin that unzips the text output.

**Comment by jpkrohling** [comment]
The problem is that the contents from the `/metrics` endpoint is being doubly encoded. 

    curl -v -H 'Accept-Encoding: gzip, deflate' http://192.168.39.51:32382/metrics | zcat | zcat

For reference this is the command that is similar to what the browser does:

    curl -v -H 'Accept-Encoding: gzip, deflate' http://192.168.39.51:32382/metrics | zcat

This is how it looks like for a regular website:

    curl -v -H 'Accept-Encoding: gzip, deflate' https://twitter.com/ | zcat

**Comment by jpkrohling** [comment]
By the way: 

> This works well with Jaeger all in one image.

This is because the `standalone` assembly does not apply a compression handler.

**Comment by yurishkuro** [comment]
good catch @jpkrohling
