### ISSUE TITLE
Keep count of outstanding open spans

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger#698]
We have numerous cases where users ask us why they can't see spans being persisted. One big cause is the user closes the tracer before the spans are persisted or they forget to finish the span.

If we keep a simple counter of number of started spans (and decrement per finish), then on tracer.close(), we can emit a log saying that: "N spans were started but not finished()".

Should be relatively easy to implement and will assist in debugging issues (unless no logger is configured...)

**Comment by yurishkuro** [comment]
if we do that, it's not that far from actually preemptively flushing the spans that are potentially left unfinished. If we add a flag "in-progress" to the span, and change the merge function on the backend to recognize it, we could be able to support partial spans.

**Comment by de-robat** [comment]
for reference, supporting "partial spans" is an ongoing discussion at the jaeger-client over here [https://github.com/jaegertracing/jaeger-client-java/issues/231#issuecomment-367031420](https://github.com/jaegertracing/jaeger-client-java/issues/231#issuecomment-367031420)

**Comment by knabben** [comment]
should this be implemented in the lib side? does not seems the server receive an UDP package on close() in these cases.

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients.
