### ISSUE TITLE
Cassandra's dbmodel's Span.SpanHash depends on data that isn't in dbmodel

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#704]
The computation of `Span.SpanHash` defined in `/cassandra/spanstore/dbmodel/model.go` depends on a field (`Warnings`) which isn't in dbmodel's Span.

https://github.com/jaegertracing/jaeger/blob/a631623e52a376b98cf102c423ecd9b6fc81fdf4/plugin/storage/cassandra/spanstore/dbmodel/model.go#L41

We compute the SpanHash by using the common model as seen here:

https://github.com/jaegertracing/jaeger/blob/412baf60db217d6f41d7fdca04358069362b29ca/plugin/storage/cassandra/spanstore/dbmodel/converter.go#L40-L45

**Comment by vprithvi** [comment]
Related #705

**Comment by nikzayn** [comment]
@vprithvi I would like to work on this. From the above-mentioned gist, what I got is that should I need to add **Warnings** in models.go file and what type should I consider for the same error or some custom error warning error type. 

Do brief me on the same!!
