### ISSUE TITLE
Span.Warnings not stored in Cassandra

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#705]
The `model Span.Warnings` field isn't stored in Cassandra. 

https://github.com/jaegertracing/jaeger/blob/fcbd21078ab7ed03682964c187452778242d3423/model/span.go#L59

Cassandra schema for reference:
https://github.com/jaegertracing/jaeger/blob/ec6378a7a5094ff3019c506163108da29f3f2f99/plugin/storage/cassandra/schema/v001.cql.tmpl#L54-L68

The warnings field contains details on any conversion failures from thrift to the internal model object. I feel that this is important information that should be persisted along with the rest of the Span.

**Comment by vprithvi** [comment]
@ys Any opinions against doing this?

**Comment by yurishkuro** [comment]
+1

**Comment by lazyf0z** [comment]
I'm taking this issue up, if no one else is taking this. :pray:
