### ISSUE TITLE
ES: Query with duration limits return results out of range

### ISSUE THREAD

**Issue by golonzovsky** [jaegertracing/jaeger#709]
I'm using both `minDuration` and `maxDuration` and still getting results which are way over this limits and makes plot not so usable. 

```
minDuration: 100ms
maxDuration: 2s
```

![screenshot from 2018-02-22 17-29-13](https://user-images.githubusercontent.com/2477950/36550602-f4c1c05a-17f5-11e8-992d-f82d7fda5123.png)

The issue is that resulting ES query searches for spans within that timeframe, and outlier traces does have smaller **child span which fit requested range**.

```
{
  "aggregations": {
    "traceIDs": {
      "aggregations": {
        "startTime": {
          "max": {
            "field": "startTime"
          }
        }
      },
      "terms": {
        "field": "traceID",
        "order": [
          {
            "startTime": "desc"
          }
        ],
        "size": 1001
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "duration": {
              "from": 100000,
              "include_lower": true,
              "include_upper": true,
              "to": 2000000
            }
          }
        },
        {
          "range": {
            "startTime": {
              "from": 1519307700000000,
              "include_lower": true,
              "include_upper": true,
              "to": 1519308000000000
            }
          }
        },
        {
          "match": {
            "process.serviceName": {
              "query": "storage"
            }
          }
        }
      ]
    }
  },
  "size": 0
}
```

Possible solution is to look **only on parent spans** when querying: 
```
{
  "match": {
    "parentSpanID": {
      "query": "0"
    }
  }
}
```

This will filter out traces which are in progress or missing parents (propagated from non-reporting system), but make results to fit query..

**Comment by jpkrohling** [comment]
@kevinearls could you test this one, once you have some time?

**Comment by pavolloffay** [comment]
@yurishkuro does the cassandra storage have the same behavior? It would show a trace outside of the interval if the one one of the spans matches the interval.

In that case we should better document what min/max duration means.

**Comment by yurishkuro** [comment]
This is the expected behavior, although I agree it's counter-intuitive. The search query applies to individual spans, but the results are displayed for full traces. I think the scatter plot displays full trace duration, not the durations of service/operation searched for.

**Comment by yurishkuro** [comment]
cc @tiffon to think about better user experience

**Comment by pavolloffay** [comment]
I will create an issue in UI repo and close this one: https://github.com/jaegertracing/jaeger-ui/issues/397
