### ISSUE TITLE
many github projects already updated, and this demo can't compile pass

### ISSUE THREAD

**Issue by 1046102779** [jaegertracing/jaeger#714]
chendonghai@cloud06-freego-work-00:~/godev/src/github.com/jaegertracing/jaeger/examples/hotrod$ go run main.go all        [44/488]
# github.com/uber/jaeger-lib/metrics/prometheus
../../../../uber/jaeger-lib/metrics/prometheus/factory.go:143:12: cannot use hv.WithLabelValues(f.tagsAsLabelValues(labelNames, ta
gs)...) (type prometheus.Observer) as type prometheus.Histogram in field value:
        prometheus.Observer does not implement prometheus.Histogram (missing Collect method)
# github.com/uber/jaeger-client-go/thrift-gen/jaeger
../../../../uber/jaeger-client-go/thrift-gen/jaeger/agent.go:101:34: cannot use agentProcessorEmitBatch literal (type *agentProces
sorEmitBatch) as type thrift.TProcessorFunction in assignment:
        *agentProcessorEmitBatch does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../../../uber/jaeger-client-go/thrift-gen/jaeger/agent.go:111:27: not enough arguments in call to processor.Process
        have (int32, thrift.TProtocol, thrift.TProtocol)
        want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
# github.com/uber/jaeger-client-go/thrift-gen/sampling
../../../../uber/jaeger-client-go/thrift-gen/sampling/samplingmanager.go:101:15: cannot assign 1 values to 2 variables
../../../../uber/jaeger-client-go/thrift-gen/sampling/samplingmanager.go:147:44: cannot use samplingManagerProcessorGetSamplingStr
ategy literal (type *samplingManagerProcessorGetSamplingStrategy) as type thrift.TProcessorFunction in assignment:
        *samplingManagerProcessorGetSamplingStrategy does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../../../uber/jaeger-client-go/thrift-gen/sampling/samplingmanager.go:157:27: not enough arguments in call to processor.Process
        have (int32, thrift.TProtocol, thrift.TProtocol)
        want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
# github.com/uber/jaeger-client-go/thrift-gen/zipkincore
../../../../uber/jaeger-client-go/thrift-gen/zipkincore/zipkincollector.go:101:15: cannot assign 1 values to 2 variables
../../../../uber/jaeger-client-go/thrift-gen/zipkincore/zipkincollector.go:147:42: cannot use zipkinCollectorProcessorSubmitZipkin
Batch literal (type *zipkinCollectorProcessorSubmitZipkinBatch) as type thrift.TProcessorFunction in assignment:
        *zipkinCollectorProcessorSubmitZipkinBatch does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../../../uber/jaeger-client-go/thrift-gen/zipkincore/zipkincollector.go:157:27: not enough arguments in call to processor.Proce
ss
        have (int32, thrift.TProtocol, thrift.TProtocol)
        want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
# github.com/uber/jaeger-client-go/thrift-gen/baggage
../../../../uber/jaeger-client-go/thrift-gen/baggage/baggagerestrictionmanager.go:109:15: cannot assign 1 values to 2 variables
../../../../uber/jaeger-client-go/thrift-gen/baggage/baggagerestrictionmanager.go:155:47: cannot use baggageRestrictionManagerProc
essorGetBaggageRestrictions literal (type *baggageRestrictionManagerProcessorGetBaggageRestrictions) as type thrift.TProcessorFunc
tion in assignment:
        *baggageRestrictionManagerProcessorGetBaggageRestrictions does not implement thrift.TProcessorFunction (wrong type for Pro
cess method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../../../uber/jaeger-client-go/thrift-gen/baggage/baggagerestrictionmanager.go:165:27: not enough arguments in call to processo
r.Process
        have (int32, thrift.TProtocol, thrift.TProtocol)
        want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
# github.com/uber/tchannel-go/thrift/gen-go/meta
../../../../uber/tchannel-go/thrift/gen-go/meta/meta.go:97:15: cannot assign 1 values to 2 variables
../../../../uber/tchannel-go/thrift/gen-go/meta/meta.go:170:15: cannot assign 1 values to 2 variables
../../../../uber/tchannel-go/thrift/gen-go/meta/meta.go:243:15: cannot assign 1 values to 2 variables
../../../../uber/tchannel-go/thrift/gen-go/meta/meta.go:289:31: cannot use metaProcessorHealth literal (type *metaProcessorHealth)
 as type thrift.TProcessorFunction in assignment:
        *metaProcessorHealth does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../../../uber/tchannel-go/thrift/gen-go/meta/meta.go:290:34: cannot use metaProcessorThriftIDL literal (type *metaProcessorThri
ftIDL) as type thrift.TProcessorFunction in assignment:
        *metaProcessorThriftIDL does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../../../uber/tchannel-go/thrift/gen-go/meta/meta.go:290:34: cannot use metaProcessorThriftIDL literal (type *metaProcessorThri
ftIDL) as type thrift.TProcessorFunction in assignment:
        *metaProcessorThriftIDL does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../../../uber/tchannel-go/thrift/gen-go/meta/meta.go:291:36: cannot use metaProcessorVersionInfo literal (type *metaProcessorVe
rsionInfo) as type thrift.TProcessorFunction in assignment:
        *metaProcessorVersionInfo does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../../../uber/tchannel-go/thrift/gen-go/meta/meta.go:301:27: not enough arguments in call to processor.Process
        have (int32, thrift.TProtocol, thrift.TProtocol)
        want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)

**Comment by 1046102779** [comment]
so i hope that jaeger uses  vendor mechanism to solve the problem

**Comment by black-adder** [comment]
We use glide to manage dependencies, what commands did you run install dependencies and run the demo?

**Comment by 1046102779** [comment]
tomorrow let me verify it again.

**Comment by yurishkuro** [comment]
I don't think this is a real issue, but please reopen if needed
