### ISSUE TITLE
Cannot disable cassandra TLS host verification 

### ISSUE THREAD

**Issue by javiervazquezh** [jaegertracing/jaeger#737]
Hello,

I see an issue trying to disable Cassandra's TLS host verification via command line flag (--cassandra.tls.verify-host).

The problem lyes on the the flag default value. If I invoke "collector" or "query" with the flag, tls host verification is not disabled. 
 
[plugin/storage/cassandra/options.go - Line 82](https://github.com/jaegertracing/jaeger/blob/6fce4f9f60822edc1d581d9b9c3eacd2ba9f5b15/plugin/storage/cassandra/options.go#L82)

It works as expected if I changed the flag default value to "false" but that could break existing semantics.

**Comment by yurishkuro** [comment]
have you tried `--cassandra-archive.tls.verify-host=false`?

**Comment by javiervazquezh** [comment]
@yurishkuro just tried your suggestion and it works. I was under the impression that i already had tried that and the command line wasn’t allowing me to pass the value in that format.

Thanks!
