### ISSUE TITLE
Jaeger Agent metrics not returned

### ISSUE THREAD

**Issue by ledor473** [jaegertracing/jaeger#738]
As per the [documentation](http://jaeger.readthedocs.io/en/latest/monitoring/) the Jaeger Agent should expose some metrics properly formatted for  Prometheus on `:5778/metrics` 

The Agent is started using:
```
docker run \
  --rm \
  -p5775:5775/udp \
  -p6831:6831/udp \
  -p6832:6832/udp \
  -p5778:5778/tcp \
  jaegertracing/jaeger-agent:1.2 \
  /go/bin/agent-linux --collector.host-port=my-collector:some-port
```

And I tried to retrieve the metrics using:
```
 curl -v localhost:5778/metrics
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5778 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:5778
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 14 Mar 2018 15:35:50 GMT
< Content-Length: 42
< 
'service' parameter must be provided once
```

**Comment by trtg** [comment]
why is this closed? I recently built from source and the agent still does not export any metrics/responds with: 'service' parameter must be provided once. I'm trying to debug a situation where spans are mysteriously disappearing for certain services, so it would be really helpful to know at what point they are getting dropped
