### ISSUE TITLE
Hot Rod Example not Showing Traces

### ISSUE THREAD

**Issue by florianeichin** [jaegertracing/jaeger#762]
I am running both dockerized commands

```
docker run -d --name jaeger -p6831:6831/udp -p16686:16686 jaegertracing/all-in-one:latest

docker run --rm -it --link jaeger -p8080-8083:8080-8083 jaegertracing/example-hotrod:latest --jaeger-agent.host-port=jaeger:6831
```

the hot rod works and I can click around. In jaeger, there appear 7 services, but when clicking on find traces there is the message: "No trace results. Try another query."

**Comment by yurishkuro** [comment]
can you post a screenshot of the search panel?

if you're seeing service names in the dropdown it means the data is certainly getting to the backend. Is it possible the traces happened earlier than the default 1hr lookup interval?

**Comment by florianeichin** [comment]
![image](https://user-images.githubusercontent.com/30117747/38274215-65420558-378e-11e8-8f6b-53224567fdcb.png)

Here is an image. There are services in the dropdown. 
What do you mean with the 1hr lookup interval?

**Comment by yurishkuro** [comment]
> What do you mean with the 1hr lookup interval?

You have it set to 2 days - it controls the time interval of the search query, from [now-2d, now]. If you just created the traces they should be searchable.

Have you tried searching by other service name, e.g. `frontend`?

I'm just trying to narrow down the possibilities, don't know why the search is not returning. 

You may also want to check browser console, in case there are any Javascript errors.

**Comment by florianeichin** [comment]
just i tried all 7 services. 
the console doesn't show any issues.

I tried it in another machine, that fixed the problem. But I don't know what caused the issue.

**Comment by marioscrock** [comment]
I have a similar issue running jaeger (with the docker-compose file) and hotrod (in local). 

Making more than 3 calls to hotrod, the UI only returns 3 traces for service _frontend_ (Inspecting json returned to the web page it only contains 3 traces). For other services all traces are correctly reported.

_Jaeger UI URL_
`http://localhost:16686/search?end=1523364012843000&limit=20&lookback=1h&maxDuration&minDuration&service=frontend&start=1523360412843000` 

Removing the limit=20 parameter it returns all traces correctly (`http://localhost:16686/search?end=1523364012843000&lookback=1h&maxDuration&minDuration&service=frontend&start=1523360412843000`). 

It doesn't happen using the all-in-one image. Is there any difference?
