### ISSUE TITLE
Agent for Windows

### ISSUE THREAD

**Issue by grounded042** [jaegertracing/jaeger#765]
With the new [jaeger-client-csharp](https://github.com/jaegertracing/jaeger-client-csharp) there will be those wanting to run the Jaeger Agent on Windows where their services are hosted. I've tested building the agent with `GOOS=windows` and it works on Windows. 

Would we be able to publish the binary produced for Windows? I think having a Windows binary available for download would greatly help the adoption of the C# client and those on Windows. I can submit a PR with the Makefile targets to build the agent for Windows.

**Comment by yurishkuro** [comment]
Would be nice. There have been requests for binary distros for Linux too, in addition to docker images. The main thing we're missing is the deploy stage in Travis, so a PR to add that would be most welcome.

**Comment by yurishkuro** [comment]
@grounded042 thanks for the pull request. The binaries are now part of the release, check out https://github.com/jaegertracing/jaeger/releases/tag/v1.4.1
