### ISSUE TITLE
Jaeger fragile in the face of cassandra failures

### ISSUE THREAD

**Issue by rbtcollins** [jaegertracing/jaeger#767]
We've been observing Jaeger components - specifically the collectors and query - fail to recover after Cassandra has any sort of outage. While Cassandra reliability is clearly not a topic for here ;), Jaeger's resilience to issues is.

What we see happen is this a stuck process which is only logging one thing even hours after the issue is fixed... ```gocql: no hosts available in the pool```

What we'd like to see happen is a recovery after a few minutes without manual intervention. This is related to, but distinct from, #562

**Comment by burmanm** [comment]
That sounds like a bug in the gocql though, not Jaeger directly.

**Comment by yurishkuro** [comment]
we have a fixit week coming up, & want to try upgrading the driver

**Comment by rbtcollins** [comment]
@burmanm whether it is a bug in gocql or not doesn't really matter:
 - if it is a gocql bug; until it is both fixed *and* the updated version is in use, Jaeger will still be suffering the issue, and so a tracking bug is relevant
 - if it isn't (or if gocql say they won't fix because of some reason), then a local workaround needs to be done to solve the issue.

Either way, a bug in this repo is relevant while the defect is present :).

**Comment by jpkrohling** [comment]
@rbtcollins are you still experiencing this? The driver has been updated as part of #829.

**Comment by rbtcollins** [comment]
I'll see about that, got a few things up in the air just now. Anything stopping doing a release?

**Comment by jpkrohling** [comment]
I'm closing this one, but feel free to reopen if you are still experiencing this after 1.5.0

**Comment by nyanshak** [comment]
I'd like to re-open this as I'm seeing the same problem after 1.5.0.

Related gocql issue: https://github.com/gocql/gocql/issues/915

I see there is a setting in gocql `ReconnectInterval`:

```
	// If not zero, gocql attempt to reconnect known DOWN nodes in every ReconnectInterval.
	ReconnectInterval time.Duration
```

I'm not super familiar with C* yet so haven't worked out a great way to test this. I believe I've mostly seen it when resizing the cluster.

Assuming that setting works as advertised... I believe the suggestion would be to add a flag to jaeger for cassandra reconnect interval, and set the default to some reasonable value.

**Comment by jpkrohling** [comment]
> I believe the suggestion would be to add a flag to jaeger for cassandra reconnect interval, and set the default to some reasonable value.

Would you like to contribute a patch?

**Comment by nyanshak** [comment]
@jpkrohling Sure :100: Opened #934
