### ISSUE TITLE
WIll jaeger care about removing old spans?

### ISSUE THREAD

**Issue by devoxel** [jaegertracing/jaeger#774]
My question is: will removing old spans upset any operations of jaeger?

For context: I've been setting up jaeger in production and want to add a curator job for removing old elasticsearch indexes -- I'm just wondering how jaeger will react.

Specifically for elasticsearch: should corresponding span and service entries be removed? Say `jaeger-span-2018-03-17`, should I also remove `jaeger-service-2018-03-17`?

PS. I'm not sure if this is the best place to ask this. Let me know if it's not :sweat_smile:

**Comment by black-adder** [comment]
This is fine and expected. We even have an existing script that uses curator to purge older data: https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/esCleaner.py

**Comment by yurishkuro** [comment]
@black-adder could you please add a paragraph to the docs about this?

**Comment by tanuck** [comment]
@yurishkuro is the esCleaner docker image built and pushed to the Docker hub? I can't seem to find it under the jaegertracing organization.

**Comment by black-adder** [comment]
@tanuck https://hub.docker.com/r/jaegertracing/jaeger-es-index-cleaner/

**Comment by tanuck** [comment]
@black-adder thanks! Don't know how I missed that.
