### ISSUE TITLE
make storage-integration-test fails due to issues in CompareTrace() but error is forgotten

### ISSUE THREAD

**Issue by burmanm** [jaegertracing/jaeger#777]
While writing the K/V/Badger storage backend, I enabled the storage-integration-test for that one also. That led me to silly errors, where byte-by-byte equal spans are not actually equal.

It does:

```go
if !assert.EqualValues(t, expected, actual) {
```

Where ``expected`` & ``actual`` are of type ``*model.Trace``. This leads to stretch/testify's doing a call to reflect.DeepEqual() and that fails. I copied over the code from reflect to check where this fails and what I get is:

```go
	case reflect.Struct:
		for i, n := 0, v1.NumField(); i < n; i++ {
			if !deepValueEqual(v1.Field(i), v2.Field(i), visited, depth+1) {
```

This returns false, with the following output:

```go
fmt.Printf("deepValueEqual v1.Field() != v2.Field() inside, %v != %v Struct\n", v1.Field(i), v2.Field(i))
```

Printing out ``deepValueEqual v1.Field() != v2.Field() inside, 0 != 0 Struct``. For more reason, if we do:

```go
fmt.Printf("first %v == second %v: %v\n", v1.Field(i), v2.Field(i), v1.Field(i) == v2.Field(i))
```

We get: ``first 0 == second 0: false``. The reflect.DeepEqual unfortunately hits an unexported field at this point making things difficult, but it does:

```go
	if v.kind() == Interface {
		if v.NumMethod() == 0 {
			return *(*interface{})(v.ptr)
		}
```

For both v1.Field(i) and v2.Field(i) and then compares the result. Thus, we end up with uint64(0) is not equal to uint64(0) and the Trace-comparison fails. This obviously works with the memory backend as it compares the same backing pointers, but these fail if we do json.Unmarshal / Marshal combination in between.

All I could say is that .. this type of assert is not going to work. Or can someone figure out the reason (I'm not this familiar with the golang runtime)? Doing ``fmt.Printf("Found mistake %v != %v\n", *expected, *actual)`` gives two byte-slices, but they are equal so I don't really see any mistake in the real code.

Why this hasn't been caught is simple also, the code in integration_test.go calls:

```go
	if !assert.EqualValues(t, expected, actual) {
		for _, err := range pretty.Diff(expected, actual) {
			t.Log(err)
		}
		out, err := json.Marshal(actual)
		assert.NoError(t, err)
		t.Logf("Actual trace: %s", string(out))
	}
```

Thus is catches the assert-failure, but it does not actually pass that failure to the testing.T so the test is considered a success. Also, ``pretty.Diff`` should return the difference in the first parameter, I'm not sure why that is ignored and not logged.. not that testutils.NewLogger() does do any logging at all when using the ``make storage-integration-test`` thus all errors go unnoticed. Maybe this should have been another ticket.

**Comment by yurishkuro** [comment]
Closed by #781
