### ISSUE TITLE
Could we provide pre-made Grafana dashboards for Jaeger backend components?

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#789]
Just an idea at this point, I haven't worked closely with pre-made Grafana dashboards, but is sounds very useful if people can get a monitoring picture out of the box (if using Prometheus).

**Comment by benley** [comment]
I've been developing some of these where I work.  We're planning on sharing the results in the near future, along with a handful of recording and metric relabeling rules for Prometheus.

**Comment by vprithvi** [comment]
I just came across https://grafana.com/dashboards which seems to be a way for people to distribute dashboards

**Comment by benley** [comment]
Here's what I have for jaeger-collector so far.  It probably needs to be updated for jaeger 1.5; I am still using v1.3.  It also lacks data on cassandra/ES backend storage because I'm not sure what to do for those yet.

https://grafana.com/dashboards/6394

coming soon: jaeger-query dashboard, and jaeger 1.5 updates

**Comment by benley** [comment]
We will hopefully also be sharing the jsonnet framework used to generate these dashboards soon.

**Comment by kongkong56** [comment]
how to show jeager tracing info in grafana dashboard?

**Comment by black-adder** [comment]
There's also this: https://github.com/tcolgate/jaeger-simplejson

**Comment by Dieterbe** [comment]
> how to show jeager tracing info in grafana dashboard?

grafana folks have this on the roadmap, tracing viewer and all kinds of integrations between tracing, logs and metrics. but it's going to take them a while to prototype and implement that stuff

**Comment by luong-komorebi** [comment]
My effort 😓 https://grafana.com/dashboards/10001

**Comment by jpkrohling** [comment]
I have it on my queue to get @Gouthamve's [mixin](https://github.com/grafana/jsonnet-libs/tree/master/jaeger-mixin) as base and provide it as an official starting point for people to monitor their Jaeger backend components.

**Comment by justinwalz** [comment]
This is now part of `jaeger-mixin`, can be found here https://github.com/jaegertracing/jaeger/blob/master/monitoring/jaeger-mixin/dashboard-for-grafana.json
