### ISSUE TITLE
Remove SASI index on dependency column family

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#790]
While most SASI indexes were removed as part of #80, the one in the dependencies column family still exists, leading to problems when using older versions of cassandra that don't support SASI indexes, or using [alternate storage like ScyllaDB ](https://github.com/jaegertracing/jaeger/pull/201#discussion_r121197772).

We can update the `dependency` schema to not have SASI indexes, and provide a migration script from the old schema to the new schema. 

We should also ensure that https://github.com/jaegertracing/spark-dependencies works with the new schema.

**Comment by vprithvi** [comment]
> I suggest adding a "source" column to the schema, potentially to represent data coming from different sources

I like this idea, but I don't think it should be part of the migration,  I created https://github.com/jaegertracing/jaeger/issues/791 to capture this.

**Comment by yurishkuro** [comment]
I am not suggesting we implement all of the relevant business logic, but if we are already making a breaking schema change, why not include an extra field?

**Comment by vprithvi** [comment]
>but if we are already making a breaking schema change, why not include an extra field?

Because it's unrelated to this change, and is unusable without the business logic. Why shouldn't the change be done along with the business logic?

**Comment by vprithvi** [comment]
I'm thinking that changing the data model to include a date bucket while making the time stamp as a clustering key would enable us to maintain the current query patterns while removing the SASI index.

The schema looks something like this:
https://github.com/jaegertracing/jaeger/blob/d52969b253ec0d8c3d750071c7ccdc5525de3e3a/plugin/storage/cassandra/schema/v001.cql.tmpl#L191-L196

While the write path is largely unaffected, reads become a bit more involved, as we need to compute buckets that we want to retrieve dependencies from. 

We also need to update the spark dependencies job.

The migration path seems to be the following:

1. Stop dependencies job
2. Use the Cassandra [`COPY`](https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlshCopy.html) command to export to a CSV file (which works for tables with less than 2 million rows)
3. Delete existing dependencies column family
4. Create dependencies column family with new schema
5. Massage the CSV file into the new format and load into new schema
6. Run new version of dependencies job which writes to new schema

@yurishkuro @black-adder @jpkrohling @pavolloffay wdyt?
