### ISSUE TITLE
Setup Jaeger for N services

### ISSUE THREAD

**Issue by Disturbing** [jaegertracing/jaeger#795]
Is it possible to setup Jaeger to only show a specific whitelist of services?

I tried googling it around and couldn't find it.

The idea is to:

Setup Jaeger A for service A,B,C and D only
Setup Jaeger B for service Z,Y,W only

It would be best to be able to do this with kubernetes labels as well :).

Thanks in advance!

**Comment by yurishkuro** [comment]
This is a question about environments isolation, I don't think it requires any specific support from Jaeger.

**Comment by Disturbing** [comment]
Maybe I dont understand how jaeger works? Is it possible to setup two
jaeger instances in two different namespaces and it confines itself to
those services on Kubernetes? Maybe I should be asking this question
somewhere else?

**Comment by yurishkuro** [comment]
Jaeger does not do any automatic discovery of services. When you configure Jaeger clients in your applications you tell them where to send captured traces. If you are running jaeger-agent as a sidecar or telling clients to submit directly to jaeger-collector, then you're in full control of which Jaeger backend the data is going to end up.

It's fine to ask questions here, btw. The other options are mailing list and chat https://gitter.im/jaegertracing/Lobby.

**Comment by jpkrohling** [comment]
Complementing what @yurishkuro said, this can (and should, IMO) be done at the infra layer. In Kubernetes, it would mean isolating your services into ["namespaces"](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/). In OpenShift, it would be in ["projects"](https://docs.openshift.org/latest/dev_guide/projects.html). 

Note that you cannot use `DaemonSet` on such a setup, as they run at the node level without caring about which namespaces the running pods belong to: you should either use the agent as sidecar or make the client talk directly to the collector.

**Comment by Disturbing** [comment]
Okay -- Thanks for all the quick replies guys --

Right now I'm using istio and jaeger's all-in-one template.  Jaeger is
deployed in logging and my services in default and jaeger is a sidecar to
them all if I'm not mistaken.

I'm looking potentially deploy jaeger to dev and qa namespaces as a sidecar
and when I view Jaeger is either qa or dev, you would only see the services
within that namespace.

--

Better yet, If I can append some sort of header where Jaeger only listens
and records to services with that header, that would be an amazing win for
my requirements.

Essentially, I'm trying to deploy jaeger as a service where it's only
listening to the pool of services that the client cares about, not the
entire ecosystem which could be other client's applications.
