### ISSUE TITLE
Simplify test coverage scripts

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#797]
We moved to Go 1.10 in #792, in which `go test` coverpkg has been enhanced to accept multiple packages.

>The go test -coverpkg flag now interprets its argument as a comma-separated list of patterns to match against the dependencies of each test, not as a list of packages to load anew. For example, go test -coverpkg=all is now a meaningful way to run a test with coverage enabled for the test package and all its dependencies. Also, the go test -coverprofile option is now supported when running multiple tests.

This means that we can simplify the logic in [cover.sh](https://github.com/jaegertracing/jaeger/blob/master/scripts/cover.sh) and potentially make the build faster.

**Comment by yurishkuro** [comment]
I did a test run, `go test ./...` ran for 58 second, `make test` ran for 67 seconds. Not a significant difference. To use the combined test run we would need to refactor how code coverage is generated, i.e. remove the packages with `.nocover` from the coverage output (or get rid of `.nocover` completely since we have relaxed 100% coverage rules and can probably tolerate some uncovered packages).

**Comment by yurishkuro** [comment]
Another alternative by @bogdandrutu (https://github.com/open-telemetry/opentelemetry-collector/issues/671#issuecomment-605212324) is to use https://github.com/ory/go-acc, which also allows cross-package coverage to be included.

**Comment by PankhudiB** [comment]
shall I use go-acc and add make task ? or is someone else working on this ?

**Comment by PankhudiB** [comment]
This is the output of go-acc command i just ran on the repo: 

ok  	github.com/jaegertracing/jaeger	0.011s	coverage: [no statements] [no tests to run]
?   	github.com/jaegertracing/jaeger/cmd/agent	[no test files]
ok  	github.com/jaegertracing/jaeger/cmd/agent/app	4.457s	coverage: 4.1
ok  	github.com/jaegertracing/jaeger/cmd/agent/app/configmanager	0.048s	coverage: 1.5
ok  	github.com/jaegertracing/jaeger/cmd/agent/app/configmanager/grpc	0.108s	coverage: 2.7
ok  	github.com/jaegertracing/jaeger/cmd/agent/app/customtransport	0.040s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/cmd/agent/app/httpserver	0.053s	coverage: 1.3
ok  	github.com/jaegertracing/jaeger/cmd/agent/app/processors	3.874s	coverage: 14.9
ok  	github.com/jaegertracing/jaeger/cmd/agent/app/reporter	0.157s	coverage: 2.8
ok  	github.com/jaegertracing/jaeger/cmd/agent/app/reporter/grpc	1.504s	coverage: 11.4
ok  	github.com/jaegertracing/jaeger/cmd/agent/app/servers	0.122s	coverage: 3.9
ok  	github.com/jaegertracing/jaeger/cmd/agent/app/servers/thriftudp	0.053s	coverage: 98.0
ok  	github.com/jaegertracing/jaeger/cmd/agent/app/testutils	0.134s	coverage: 1.4
?   	github.com/jaegertracing/jaeger/cmd/all-in-one	[no test files]
ok  	github.com/jaegertracing/jaeger/cmd/all-in-one/setupcontext	0.039s	coverage: 100.0
?   	github.com/jaegertracing/jaeger/cmd/anonymizer	[no test files]
?   	github.com/jaegertracing/jaeger/cmd/anonymizer/app/anonymizer	[no test files]
?   	github.com/jaegertracing/jaeger/cmd/anonymizer/app/writer	[no test files]
?   	github.com/jaegertracing/jaeger/cmd/collector	[no test files]
ok  	github.com/jaegertracing/jaeger/cmd/collector/app	0.233s	coverage: 6.8
ok  	github.com/jaegertracing/jaeger/cmd/collector/app/handler	0.188s	coverage: 11.6
ok  	github.com/jaegertracing/jaeger/cmd/collector/app/processor	0.066s	coverage: 1.0
ok  	github.com/jaegertracing/jaeger/cmd/collector/app/sampling	0.118s	coverage: 1.4
ok  	github.com/jaegertracing/jaeger/cmd/collector/app/sampling/model	0.021s	coverage: [no statements] [no tests to run]
ok  	github.com/jaegertracing/jaeger/cmd/collector/app/sampling/strategystore	0.049s	coverage: 0.0
ok  	github.com/jaegertracing/jaeger/cmd/collector/app/sanitizer	0.063s	coverage: 2.8
ok  	github.com/jaegertracing/jaeger/cmd/collector/app/sanitizer/cache	0.072s	coverage: 93.9
?   	github.com/jaegertracing/jaeger/cmd/collector/app/sanitizer/cache/mocks	[no test files]
ok  	github.com/jaegertracing/jaeger/cmd/collector/app/sanitizer/zipkin	0.051s	coverage: 6.3
ok  	github.com/jaegertracing/jaeger/cmd/collector/app/server	0.195s	coverage: 2.4
ok  	github.com/jaegertracing/jaeger/cmd/collector/app/zipkin	0.499s	coverage: 7.7
ok  	github.com/jaegertracing/jaeger/cmd/docs	0.064s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/cmd/env	0.095s	coverage: 0.8
ok  	github.com/jaegertracing/jaeger/cmd/flags	0.039s	coverage: 37.7
?   	github.com/jaegertracing/jaeger/cmd/ingester	[no test files]
ok  	github.com/jaegertracing/jaeger/cmd/ingester/app	0.091s	coverage: 2.8
?   	github.com/jaegertracing/jaeger/cmd/ingester/app/builder	[no test files]
ok  	github.com/jaegertracing/jaeger/cmd/ingester/app/consumer	1.797s	coverage: 7.1
?   	github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/mocks	[no test files]
ok  	github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/offset	0.242s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/cmd/ingester/app/processor	0.186s	coverage: 2.1
ok  	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/decorator	3.102s	coverage: 1.6
?   	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/mocks	[no test files]
?   	github.com/jaegertracing/jaeger/cmd/query	[no test files]
ok  	github.com/jaegertracing/jaeger/cmd/query/app	4.054s	coverage: 33.9
ok  	github.com/jaegertracing/jaeger/cmd/query/app/querysvc	0.073s	coverage: 5.4
ok  	github.com/jaegertracing/jaeger/cmd/query/app/ui	0.039s	coverage: 2.8
?   	github.com/jaegertracing/jaeger/cmd/query/app/ui/actual	[no test files]
?   	github.com/jaegertracing/jaeger/cmd/query/app/ui/placeholder	[no test files]
?   	github.com/jaegertracing/jaeger/cmd/tracegen	[no test files]
?   	github.com/jaegertracing/jaeger/crossdock	[no test files]
ok  	github.com/jaegertracing/jaeger/crossdock/services	0.201s	coverage: 23.8
?   	github.com/jaegertracing/jaeger/crossdock/services/mocks	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod/cmd	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod/pkg/delay	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod/pkg/httperr	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod/pkg/log	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod/pkg/pool	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod/services/config	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod/services/customer	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod/services/driver	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod/services/frontend	[no test files]
?   	github.com/jaegertracing/jaeger/examples/hotrod/services/route	[no test files]
?   	github.com/jaegertracing/jaeger/examples/memstore-plugin	[no test files]
?   	github.com/jaegertracing/jaeger/internal/tracegen	[no test files]
ok  	github.com/jaegertracing/jaeger/model	0.064s	coverage: 19.3
ok  	github.com/jaegertracing/jaeger/model/adjuster	0.053s	coverage: 10.7
?   	github.com/jaegertracing/jaeger/model/converter	[no test files]
ok  	github.com/jaegertracing/jaeger/model/converter/json	0.078s	coverage: 9.9
?   	github.com/jaegertracing/jaeger/model/converter/thrift	[no test files]
ok  	github.com/jaegertracing/jaeger/model/converter/thrift/jaeger	0.147s	coverage: 4.7
ok  	github.com/jaegertracing/jaeger/model/converter/thrift/zipkin	0.060s	coverage: 13.6
ok  	github.com/jaegertracing/jaeger/model/json	0.018s	coverage: [no statements] [no tests to run]
?   	github.com/jaegertracing/jaeger/model/prototest	[no test files]
?   	github.com/jaegertracing/jaeger/pkg	[no test files]
ok  	github.com/jaegertracing/jaeger/pkg/cache	0.061s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/pkg/cassandra	0.018s	coverage: [no statements] [no tests to run]
?   	github.com/jaegertracing/jaeger/pkg/cassandra/config	[no test files]
?   	github.com/jaegertracing/jaeger/pkg/cassandra/gocql	[no test files]
?   	github.com/jaegertracing/jaeger/pkg/cassandra/gocql/testutils	[no test files]
ok  	github.com/jaegertracing/jaeger/pkg/cassandra/metrics	0.045s	coverage: 2.3
?   	github.com/jaegertracing/jaeger/pkg/cassandra/mocks	[no test files]
ok  	github.com/jaegertracing/jaeger/pkg/clientcfg/clientcfghttp	0.080s	coverage: 6.4
?   	github.com/jaegertracing/jaeger/pkg/clientcfg/clientcfghttp/thrift-0.9.2	[no test files]
ok  	github.com/jaegertracing/jaeger/pkg/config	0.045s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/pkg/config/tlscfg	1.323s	coverage: 99.3
ok  	github.com/jaegertracing/jaeger/pkg/discovery	0.040s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/pkg/discovery/grpcresolver	0.080s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/pkg/distributedlock	0.018s	coverage: [no statements] [no tests to run]
?   	github.com/jaegertracing/jaeger/pkg/distributedlock/mocks	[no test files]
ok  	github.com/jaegertracing/jaeger/pkg/es	0.045s	coverage: [no statements] [no tests to run]
?   	github.com/jaegertracing/jaeger/pkg/es/config	[no test files]
?   	github.com/jaegertracing/jaeger/pkg/es/mocks	[no test files]
?   	github.com/jaegertracing/jaeger/pkg/es/wrapper	[no test files]
ok  	github.com/jaegertracing/jaeger/pkg/healthcheck	0.060s	coverage: 72.6
?   	github.com/jaegertracing/jaeger/pkg/kafka/auth	[no test files]
?   	github.com/jaegertracing/jaeger/pkg/kafka/consumer	[no test files]
?   	github.com/jaegertracing/jaeger/pkg/kafka/mocks	[no test files]
?   	github.com/jaegertracing/jaeger/pkg/kafka/producer	[no test files]
ok  	github.com/jaegertracing/jaeger/pkg/memory/config	0.012s	coverage: [no statements] [no tests to run]
ok  	github.com/jaegertracing/jaeger/pkg/metrics	0.031s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/pkg/multicloser	0.028s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/pkg/multierror	0.028s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/pkg/netutils	0.025s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/pkg/normalizer	0.032s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/pkg/queue	0.058s	coverage: 93.0
ok  	github.com/jaegertracing/jaeger/pkg/recoveryhandler	0.041s	coverage: 50.0
ok  	github.com/jaegertracing/jaeger/pkg/testutils	0.024s	coverage: 100.0
?   	github.com/jaegertracing/jaeger/pkg/version	[no test files]
ok  	github.com/jaegertracing/jaeger/plugin	0.033s	coverage: [no statements] [no tests to run]
ok  	github.com/jaegertracing/jaeger/plugin/pkg/distributedlock/cassandra	0.042s	coverage: 44.0
ok  	github.com/jaegertracing/jaeger/plugin/sampling/calculationstrategy	0.022s	coverage: 100.0
ok  	github.com/jaegertracing/jaeger/plugin/sampling/leaderelection	0.048s	coverage: 67.6
?   	github.com/jaegertracing/jaeger/plugin/sampling/leaderelection/mocks	[no test files]
ok  	github.com/jaegertracing/jaeger/plugin/sampling/strategystore	0.049s	coverage: 4.0
ok  	github.com/jaegertracing/jaeger/plugin/sampling/strategystore/adaptive	0.086s	coverage: 31.2
ok  	github.com/jaegertracing/jaeger/plugin/sampling/strategystore/static	0.984s	coverage: 18.5
ok  	github.com/jaegertracing/jaeger/plugin/storage	0.098s	coverage: 3.0
ok  	github.com/jaegertracing/jaeger/plugin/storage/badger	5.351s	coverage: 5.7
ok  	github.com/jaegertracing/jaeger/plugin/storage/badger/dependencystore	1.973s	coverage: 24.2
ok  	github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore	14.166s	coverage: 38.5
ok  	github.com/jaegertracing/jaeger/plugin/storage/cassandra	0.083s	coverage: 8.3
ok  	github.com/jaegertracing/jaeger/plugin/storage/cassandra/dependencystore	0.048s	coverage: 5.6
ok  	github.com/jaegertracing/jaeger/plugin/storage/cassandra/samplingstore	0.047s	coverage: 6.8
?   	github.com/jaegertracing/jaeger/plugin/storage/cassandra/savetracetest	[no test files]
ok  	github.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore	0.131s	coverage: 18.5
ok  	github.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore/dbmodel	0.044s	coverage: 12.5
ok  	github.com/jaegertracing/jaeger/plugin/storage/es	0.164s	coverage: 8.8
ok  	github.com/jaegertracing/jaeger/plugin/storage/es/dependencystore	0.069s	coverage: 5.0
ok  	github.com/jaegertracing/jaeger/plugin/storage/es/dependencystore/dbmodel	0.041s	coverage: 1.5
?   	github.com/jaegertracing/jaeger/plugin/storage/es/mappings	[no test files]
ok  	github.com/jaegertracing/jaeger/plugin/storage/es/spanstore	0.897s	coverage: 19.8
ok  	github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel	0.066s	coverage: 11.1
ok  	github.com/jaegertracing/jaeger/plugin/storage/grpc	0.064s	coverage: 2.3
?   	github.com/jaegertracing/jaeger/plugin/storage/grpc/config	[no test files]
?   	github.com/jaegertracing/jaeger/plugin/storage/grpc/mocks	[no test files]
ok  	github.com/jaegertracing/jaeger/plugin/storage/grpc/proto/storage_v1	0.085s	coverage: 17.8
?   	github.com/jaegertracing/jaeger/plugin/storage/grpc/proto/storageprototest	[no test files]
ok  	github.com/jaegertracing/jaeger/plugin/storage/grpc/shared	0.101s	coverage: 8.2
ok  	github.com/jaegertracing/jaeger/plugin/storage/integration	0.397s	coverage: 3.9
ok  	github.com/jaegertracing/jaeger/plugin/storage/kafka	0.119s	coverage: 31.3
ok  	github.com/jaegertracing/jaeger/plugin/storage/memory	0.068s	coverage: 7.5
ok  	github.com/jaegertracing/jaeger/ports	0.038s	coverage: 100.0
?   	github.com/jaegertracing/jaeger/proto-gen/api_v2	[no test files]
?   	github.com/jaegertracing/jaeger/proto-gen/storage_v1	[no test files]
?   	github.com/jaegertracing/jaeger/proto-gen/storage_v1/mocks	[no test files]
?   	github.com/jaegertracing/jaeger/proto-gen/zipkin	[no test files]
ok  	github.com/jaegertracing/jaeger/storage	0.043s	coverage: 1.0
ok  	github.com/jaegertracing/jaeger/storage/dependencystore	0.082s	coverage: 1.0
?   	github.com/jaegertracing/jaeger/storage/dependencystore/mocks	[no test files]
?   	github.com/jaegertracing/jaeger/storage/mocks	[no test files]
ok  	github.com/jaegertracing/jaeger/storage/samplingstore	0.019s	coverage: [no statements] [no tests to run]
?   	github.com/jaegertracing/jaeger/storage/samplingstore/mocks	[no test files]
ok  	github.com/jaegertracing/jaeger/storage/spanstore	0.061s	coverage: 3.2
ok  	github.com/jaegertracing/jaeger/storage/spanstore/metrics	0.065s	coverage: 4.5
?   	github.com/jaegertracing/jaeger/storage/spanstore/mocks	[no test files]
?   	github.com/jaegertracing/jaeger/swagger-gen/models	[no test files]
?   	github.com/jaegertracing/jaeger/swagger-gen/restapi	[no test files]
?   	github.com/jaegertracing/jaeger/swagger-gen/restapi/operations	[no test files]
?   	github.com/jaegertracing/jaeger/thrift-gen/agent	[no test files]
?   	github.com/jaegertracing/jaeger/thrift-gen/baggage	[no test files]
?   	github.com/jaegertracing/jaeger/thrift-gen/jaeger	[no test files]
?   	github.com/jaegertracing/jaeger/thrift-gen/sampling	[no test files]
?   	github.com/jaegertracing/jaeger/thrift-gen/zipkincore	[no test files]

**Comment by yurishkuro** [comment]
I don't think go-acc is going to be particularly useful, since it doesn't allow any more customizability than plain `go test`.

We want to exclude all auto-generated packages (see ALL_SRC in Makefile), and packages with `.nocover` files. However, those packages probably won't have any _test files and `go test` will not generate coverage for them, which is what we want. So this may be as simple as just switching to `go test ./...` and removing `cover.sh`.

**Comment by PankhudiB** [comment]
> I don't think go-acc is going to be particularly useful, since it doesn't allow any more customizability than plain `go test`.
> 
> We want to exclude all auto-generated packages (see ALL_SRC in Makefile), and packages with `.nocover` files. However, those packages probably won't have any _test files and `go test` will not generate coverage for them, which is what we want. So this may be as simple as just switching to `go test ./...` and removing `cover.sh`.

But then if we just use go test -cover ./... we would still need script to take the output and check if it meets threshold.

**Comment by yurishkuro** [comment]
Threshold is checked when the results are submitted to codecov.io

**Comment by PankhudiB** [comment]
> Threshold is checked when the results are submitted to codecov.io

Okay. Help me understand one more thing. Regarding the auto-generated packages that you referred earlier. Do we know what is the list of those  auto-generated packages beforehand ?

In which case we can simply do something like  : 
EXCLUDE_PACKAGES=$(cat .file_that_has_list_of_packages_to_be_exchluded | tr '\n' '|')
go test -covermode=set -coverprofile cover.out `go list ./... | grep -Ev ${EXCLUDE_PACKAGES}`

**Comment by yurishkuro** [comment]
I don't think generated packages are going to be a problem for code coverage, because they do not include any _test files, which makes `go test` not report any coverage for them (i.e. NULL instead of 0), and thus they do not affect the total score. If you look at the current setup, we are not excluding them
```
./scripts/cover.sh $(shell go list ./...)
```

(but we do exclude them from linters)

**Comment by PankhudiB** [comment]
wanted to do a sanity before pushing. but i am getting error while running make cover. are there any prerequisites i need in my local

**Comment by yurishkuro** [comment]
CONTRIBUTING.md should describe the required setup tests. Please post the error.

**Comment by PankhudiB** [comment]
> CONTRIBUTING.md should describe the required setup steps. Please post the error.

=== RUN   TestPanicFunc
2020-10-12T22:51:09.032+0530	PANIC	consumer/deadlock_detector.go:71	No messages processed in the last check interval	{"partition": 1, "stack": "goroutine 54 [running]:\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1(0x1)\n\t/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:73 +0x292\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.TestPanicFunc.func1()\n\t/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/deadlock_detector_test.go:71 +0x45\ngithub.com/stretchr/testify/assert.didPanic.func1(0xc000141d58, 0xc000141d26, 0xc000141d48, 0xc000480440)\n\t/Users/pankhubh/go/pkg/mod/github.com/stretchr/testify@v1.5.1/assert/assertions.go:960 +0x8c\ngithub.com/stretchr/testify/assert.didPanic(0xc000480440, 0x4cb9780, 0xc00049a480, 0x75874e8, 0xc00049a480, 0xc000488301)\n\t/Users/pankhubh/go/pkg/mod/github.com/stretchr/testify@v1.5.1/assert/assertions.go:962 +0x6d\ngithub.com/stretchr/testify/assert.Panics(0x4cb9780, 0xc00049a480, 0xc000480440, 0x0, 0x0, 0x0, 0xc0004a0060)\n\t/Users/pankhubh/go/pkg/mod/github.com/stretchr/testify@v1.5.1/assert/assertions.go:976 +0x7c\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.TestPanicFunc(0xc00049a480)\n\t/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/deadlock_detector_test.go:70 +0x1f4\ntesting.tRunner(0xc00049a480, 0x4bc60c0)\n\t/usr/local/opt/go/libexec/src/testing/testing.go:991 +0x1ec\ncreated by testing.(*T).Run\n\t/usr/local/opt/go/libexec/src/testing/testing.go:1042 +0x661\n\ngoroutine 1 [chan receive]:\ntesting.(*T).Run(0xc0001ce120, 0x4b9c8df, 0xd, 0x4bc60c0, 0x1)\n\t/usr/local/opt/go/libexec/src/testing/testing.go:1043 +0x699\ntesting.runTests.func1(0xc0001ce120)\n\t/usr/local/opt/go/libexec/src/testing/testing.go:1284 +0xa7\ntesting.tRunner(0xc0001ce120, 0xc0001afd50)\n\t/usr/local/opt/go/libexec/src/testing/testing.go:991 +0x1ec\ntesting.runTests(0xc000135020, 0x51f6d00, 0x15, 0x15, 0x0)\n\t/usr/local/opt/go/libexec/src/testing/testing.go:1282 +0x528\ntesting.(*M).Run(0xc00019a100, 0x0)\n\t/usr/local/opt/go/libexec/src/testing/testing.go:1199 +0x300\nmain.main()\n\t_testmain.go:84 +0x224\n\ngoroutine 26 [chan receive]:\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1(0xc0001f20f0)\n\t/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/consumer.go:79 +0x26b\ncreated by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start\n\t/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/consumer.go:77 +0x64\n\ngoroutine 9 [chan receive]:\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1(0xc00032a000)\n\t/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/consumer.go:79 +0x26b\ncreated by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start\n\t/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/consumer.go:77 +0x64\n\ngoroutine 70 [chan receive]:\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1(0xc0000d4000)\n\t/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/consumer.go:79 +0x26b\ncreated by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start\n\t/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/consumer.go:77 +0x64\n"}
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1
	/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.TestPanicFunc.func1
	/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/deadlock_detector_test.go:71
github.com/stretchr/testify/assert.didPanic.func1
	/Users/pankhubh/go/pkg/mod/github.com/stretchr/testify@v1.5.1/assert/assertions.go:960
github.com/stretchr/testify/assert.didPanic
	/Users/pankhubh/go/pkg/mod/github.com/stretchr/testify@v1.5.1/assert/assertions.go:962
github.com/stretchr/testify/assert.Panics
	/Users/pankhubh/go/pkg/mod/github.com/stretchr/testify@v1.5.1/assert/assertions.go:976
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.TestPanicFunc
	/Users/pankhubh/oss/jaeger/cmd/ingester/app/consumer/deadlock_detector_test.go:70
testing.tRunner
	/usr/local/opt/go/libexec/src/testing/testing.go:991

**Comment by yurishkuro** [comment]
yeah, this test is know to be unstable, there's an open ticket for it #1314. If you rerun the tests it usually passes.

**Comment by PankhudiB** [comment]
> yeah, this test is know to be unstable, there's an open ticket for it #1314. If you rerun the tests it usually passes.

Okay. I have raised a PR : https://github.com/jaegertracing/jaeger/pull/2560
can you please have a look at it
