### ISSUE TITLE
Process IP problem/inconsistency

### ISSUE THREAD

**Issue by ledor473** [jaegertracing/jaeger#821]
## Requirement - what kind of business use case are you trying to solve?
View the process IP address in a human-readable format

## Current setup
- ES Datastore
- NodeJS client 3.9.2dev0
- Java client 0.24.0

## Problem - what in Jaeger blocks you from solving the requirement?
As of now, the IP from NodeJS is displayed in Query as `-1408172028`

Here's the value in ES directly:
```
            "process": {
            "serviceName": "something-service",
            "tags": [
              {
                "key": "jaeger.version",
                "type": "string",
                "value": "Node-3.9.2dev0"
              },
              {
                "key": "jaeger.hostname",
                "type": "string",
                "value": "7fdc5f65b378"
              },
              {
                "key": "ip",
                "type": "float64",
                "value": "-1408172028"
              }
            ]
```

### Option 1:
NodeJS could report the IP as a String like the Java client. 
The value in ES would be:
```

              {
                "key": "ip",
                "type": "string",
                "value": "10.0.0.1"
              }
```

### Option 2:
Modify the Java client to report the IP in the same format as NodeJS and convert the value to a human-readable format in Query

**Comment by ledor473** [comment]
Here's a few links to save you some time:

### NodeJS code
https://github.com/jaegertracing/jaeger-client-node/blob/7df66acbcbf669ee9b0a4308531712af04ec9fc1/src/tracer.js#L64
+
https://github.com/jaegertracing/jaeger-client-node/blob/7df66acbcbf669ee9b0a4308531712af04ec9fc1/src/util.js#L97-L111

### Java code
https://github.com/jaegertracing/jaeger-client-java/blob/2fa8f3ed17e88114f6cd7114747ed298933dabd8/jaeger-core/src/main/java/io/jaegertracing/Tracer.java#L110-L128

**Comment by yurishkuro** [comment]
I just realized what the issue is - JS reports the tag type as float64, and the tag adjuster was only looking for int64 

https://github.com/jaegertracing/jaeger/blob/5eb292298bd4b0a24d36e6290968374f78ed22cc/model/adjuster/ip_tag.go#L33-L43

**Comment by yurishkuro** [comment]
so fixing this would be a better approach, it will convert the tag value on ingestion, rather than changing the clients.

**Comment by chandresh-pancholi** [comment]
Hi, As a beginner, I would like to work on this issue. 
@yurishkuro, It would be really great if you can help me out.

**Comment by jpkrohling** [comment]
@chandresh-pancholi it's really wonderful that you'd like to help us! For this issue, there's a PR open already: #865. As of now, we do have another 62 issues for you to help with:

https://github.com/search?q=org%3Ajaegertracing+is%3Aissue+is%3Aopen+label%3A%22help+wanted%22&type=Issues
