### ISSUE TITLE
jaeger ui not show logs

### ISSUE THREAD

**Issue by jiuchongxiao** [jaegertracing/jaeger#825]
hello,i want know why my jaeger not show logs,do i need some config?
![image](https://user-images.githubusercontent.com/13093730/40099567-2b55b5d2-5913-11e8-98fc-538ae188b068.png)

i use jaeger for istio、spring boot!

**Comment by jiuchongxiao** [comment]
@yurishkuro can you help me?

**Comment by objectiser** [comment]
@jiuchongxiao The istio proxy does not generate logs as part of its spans.
