### ISSUE TITLE
Doc: Architecture diagram control flow

### ISSUE THREAD

**Issue by ledor473** [jaegertracing/jaeger#834]
A question during my last presentation made me think that the `Control Flow` arrows in the architecture diagram should point in the other direction.

The diagram: https://www.jaegertracing.io/img/architecture.png

The current direction implies that Jaeger Collector is able to invoke every Agent and that every Agent is able to invoke all Jaeger Client which is probably not true in all (most?) setup.

**Comment by yurishkuro** [comment]
the arrows show the direction of data flow. We could rename the edges "control data flow"
