### ISSUE TITLE
Fix FollowsFrom spans ignoring baggage/debug header from dummy parent context

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger#843]
## Requirement - what kind of business use case are you trying to solve?
https://github.com/jaegertracing/jaeger-client-go/pull/313 for context. Looks like `StartSpan()` logic with a FollowsFrom reference to a dummy parent (i.e., a parent used for carrying baggage items or debug ID extracted from HTTP headers) are not setting the correct baggage items or debug ID, respectively. These headers were in effect only if the span was started with a ChildOf reference to the dummy header.

- [x] Go
- [ ] Java
- [ ] Node
- [ ] Python
- [ ] CPP

## Problem - what in Jaeger blocks you from solving the requirement?

This isn't a ubreak now bug since there's a workaround (use ChildOf). Might be a good starter ticket.

## Any open questions to address

I need to confirm that this is indeed a problem in every repo.

**Comment by yurishkuro** [comment]
no longer supporting Jaeger clients
