### ISSUE TITLE
Error running jaeger-query

### ISSUE THREAD

**Issue by estatkovsky** [jaegertracing/jaeger#844]
When I run jaeger-query using command:
`docker run -it --rm -p 16686:16686 -e SPAN_STORAGE_TYPE='elasticsearch' jaegertracing/jaeger-query /go/bin/query-linux --es.server-urls 'http://localhost:9200'`

I always got following error:
`open jaeger-ui-build/build/index.html: no such file`

Should I provide additional flags?

**Comment by jpkrohling** [comment]
Yes, the current image places the static assets at `/go/jaeger-ui/`, so, you need to pass something like `--query.static-files=/go/jaeger-ui/`:

```
$ docker run -it --rm -p 16686:16686 -e SPAN_STORAGE_TYPE='elasticsearch' jaegertracing/jaeger-query /go/bin/query-linux  --query.static-files=/go/jaeger-ui/ --es.server-urls 'http://localhost:9200'
```

**Comment by estatkovsky** [comment]
Thank you. This solved my problem.
