### ISSUE TITLE
Implement circular list with indexing for the memory storage

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#846]
## Requirement - what kind of business use case are you trying to solve?

* As a follow up from #845, a better implementation for the in-memory storage would be to have it as a circular list (a la container/ring). As traces need to be looked up by ID, the list has to be indexed.

## Problem - what in Jaeger blocks you from solving the requirement?

* The current in-memory "max-traces" feature is not very efficient, making `appends` and `deletes` on demand

**Comment by yurishkuro** [comment]
I think with https://github.com/jaegertracing/jaeger/pull/845/commits/a3fc1b8bbe0dc9370c0fc38f0a585efeaed8d40f this issue can be closed
