### ISSUE TITLE
FOLLOWS_FROM reference adds redundant CHILD_OF reference in v1.5.0

### ISSUE THREAD

**Issue by jpwilliams** [jaegertracing/jaeger#859]
## Requirement - what kind of business use case are you trying to solve?

Displaying relationships between services communicating using a message bus.

## Problem - what in Jaeger blocks you from solving the requirement?

When creating a span with a single `FOLLOWS_FROM` reference, the UI's JSON export reveals that two references are actually created: a `FOLLOWS_FROM` reference as expected, but also a `CHILD_OF` reference, both with identical `traceID` and `spanID` fields.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Discussion with @black-adder has revealed that the issue occurs in `v1.5.0`, but not in `v1.4.1`. @black-adder sees that the issue has likely been created in #831.

## Any open questions to address

No questions.

## Additional info

Here is a gist containing some example code to run to reproduce the problem, as well as the JSON exported in the problem version (`v1.5.0`). In `v1.4.1`, the `references` array correctly contains _only_ the `FOLLOWS_FROM` reference.

https://gist.github.com/jpwilliams/1901cefdaff283ca3afcf5eb45375dbf

**Comment by yurishkuro** [comment]
ack
