### ISSUE TITLE
Why sign each and every commit?

### ISSUE THREAD

**Issue by isaachier** [jaegertracing/jaeger#866]
## Requirement - what kind of business use case are you trying to solve?

General issue in contributing.

## Problem - what in Jaeger blocks you from solving the requirement?

It is difficult to sign each and every commit. One bad commit ruins the whole history. The only way to fix it is to squash or to do some esoteric git magic.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Only require signing the patch resulting from the pull request.

## Any open questions to address

If there is a good legal reason, we should add it to the docs.

**Comment by yurishkuro** [comment]
Patch is created by maintainers, not by the author. Whether the maintainer squashes commits (our default) or not, in both cases we are dealing with at least one code change that is not signed, and therefore not attested to its origin by the author.

**Comment by jpkrohling** [comment]
I personally sign all my commits as a "good practice", to signal that I'm indeed the one who did the commit. 

For my contributions on Jaeger repositories, the commit signature is stripped out most of the time as the commits are usually squashed.

> It is difficult to sign each and every commit.

It can be done automatically by having something like this on `~/.gitconfig`:

```
[user]
	name = Juraci Paixão Kröhling
	email = juraci@kroehling.de
	signingkey = 44385A002C3DCBC3
[commit]
	gpgsign = true
[gpg]
	program = gpg2
```

> One bad commit ruins the whole history

Not quite sure I understand what you mean here. Do you have a concrete example of what went wrong?

**Comment by isaachier** [comment]
Yes: https://github.com/jaegertracing/jaeger-client-go/pull/274. In the client repo, began working off of a branch that was not fully signed by a coworker. Was not able to fix without squashing.

**Comment by isaachier** [comment]
I want the config setting without GPG.

**Comment by isaachier** [comment]
Actually, envoy has a solution using a pre-commit hook: https://github.com/envoyproxy/envoy/pull/2283.

**Comment by jpkrohling** [comment]
I guess you are talking about "signing-off" the commit, not "signing" the commit :-)
