### ISSUE TITLE
Log debug message when span reported

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#867]
When the 'debug' log level is enabled, there is no additional log information related to spans being reported.

If an issue occurs where it is unclear whether spans have actually be reported to the server, or we need to investigate the contents of what was reported, it would be useful to switch on debug logging and see this level of detail.

## Requirement - what kind of business use case are you trying to solve?

Make it easier to identify whether spans are being correctly reported to the server.

## Problem - what in Jaeger blocks you from solving the requirement?

No debug log messages are being recorded.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Improve the debug logging in the server to help diagnose issues with handling reported spans.

**Comment by Falco20019** [comment]
What language(s) client have you used?

**Comment by jpkrohling** [comment]
This is for the collector side. 

Exporting `JAEGER_REPORTER_LOG_SPANS` would work for most clients, but I'm sure @objectiser knows that already.

**Comment by objectiser** [comment]
Yes, this issue was primarily about what the collector receives - however we should may be look at the clients as well - as `JAEGER_REPORTER_LOG_SPANS` only provides information about what the application has reported, not what the remote reporter has sent and whether it received a success response from the collector. For example the java client only records a send failure as a metric (span dropped count) - so no indication of why it failed.
