### ISSUE TITLE
Component to ingest spans from Kafka, writing to Cassandra/Elasticsearch

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#870]
## Requirement - what kind of business use case are you trying to solve?

Ability to see traces on the UI when using the Kafka storage plugin.

## Problem - what in Jaeger blocks you from solving the requirement?

There's currently no component ingesting the spans from Kafka and writing it to Cassandra/Elasticsearch, so that the Query component cannot display the reported traces.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

My initial proposal is to have a separate component that registers itself as a Kafka consumer and writes data to Elasticsearch/Cassandra using the current storage plugin for them.
Like other components, this can be executed separately on its own binary and/or included as part of the standalone.

**Comment by black-adder** [comment]
we will be open sourcing these components within the following weeks

**Comment by vprithvi** [comment]
ref #929

**Comment by yurishkuro** [comment]
ingester was released in 1.7 (although didn't make it as docker container, that will happen in 1.8)
