### ISSUE TITLE
Document why ES db model JSON is different from protobuf JSON

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#888]
As decided on 2018-06-15 call: https://docs.google.com/document/d/1ZuBAwTJvQN7xkWVvEFXj5WU9_JmS5TPiNbxCJSvPqX0/edit#heading=h.xdsshpxv2gpd

**Comment by yurishkuro** [comment]
Yes the plan is to run grpc-gateway that will expose json API based on proto. The existing json model at that point would not be needed for the UI, so if you want to move it inside ES (plus converters, which is really why it was shared with UI in the first place), then it's fine.

**Comment by pavolloffay** [comment]
I will create a copy of it to esl package. Once the UI is fixed to use the new model we can remove the duplicate in model package.

**Comment by pavolloffay** [comment]
I think we can close this.

We have decided to define a separate model for ES for:
* better encapsulation for ES storage - e.g. due to backward compatibility
* internal model might change without ES schema
