### ISSUE TITLE
Search returns results in different order every time

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#892]
## Requirement - what kind of business use case are you trying to solve?
- Reliably get the search results based in a query
- Relates to https://github.com/jaegertracing/jaeger-ui/issues/57
- Possibly relates to https://github.com/jaegertracing/jaeger-kubernetes/issues/95

## Problem - what in Jaeger blocks you from solving the requirement?
- The results ordering seem odd: items that are present when doing the search a first time are not present on the first page of results on a subsequent page load.

**Comment by knrt10** [comment]
@jpkrohling  I would like to work on this issue. I am new to go, would you please guide me to which files should I look into. It would be really helpful 😅.

**Comment by yurishkuro** [comment]
I am not clear what this issue is about, it needs more details. It sounds closely related to #166, which is unlikely a "good first issue".

**Comment by yurishkuro** [comment]
@knrt10 I would recommend picking another ticket among those labeled [good first issue](https://github.com/jaegertracing/jaeger/labels/good%20first%20issue).

**Comment by knrt10** [comment]
Ok thanks let me try.

**Comment by jpkrohling** [comment]
@yurishkuro this issue is only about adding a sort clause to the query used by the UI endpoint to list the traces. The in-memory might not be affected, but it would be good to make sure both the Cassandra and ES plugins have such clause in place.

**Comment by yurishkuro** [comment]
the fundamental issue with Cassandra search may cause different order as well. The UI already has a Sort control, so if that's not helping then the issue is with the backend storage returning non-stable results, and I think it's mostly the problem in #166.

**Comment by adinunzio84** [comment]
We've seen this with the all-in-one version of Jaeger (agents deployed as a DaemonSet) when the number of total traces is larger than the number of desired traces to return.

**Comment by mingshun** [comment]
I've seen this with ES as the backend storage on Jaeger 1.40.0. Is there any update for this issue?

**Comment by yurishkuro** [comment]
We do not make stable results order a requirement for backend storages, not I think we should given that this is observability data, not systems of record, and the trade-offs are made in favor of recency and availability, not consistency.
