### ISSUE TITLE
Independent configurations for writing and reading

### ISSUE THREAD

**Issue by davit-y** [jaegertracing/jaeger#893]
## Requirement - what kind of business use case are you trying to solve?

Ability to have different configurations for writing and reading spans. For example, writing only to Kafka, and reading from Cassandra.

In addition it would be useful to have different configurations per storage type.
For example, writing to one Kafka topic, and consuming from another.

## Problem - what in Jaeger blocks you from solving the requirement?

Apart from archive support, Jaeger only supports one configuration per storage type and the first listed storage type is used for reading, while all storage types are used for writing.

**Comment by jpkrohling** [comment]
What's the relationship between this and the PR #880? Is the PR resolving this issue here?

**Comment by yurishkuro** [comment]
it doesn't yet.

**Comment by davit-y** [comment]
#880 had commits at some point that partially solve this issue, but the creation of the ingester will create further complications so we decided to only do the basic set of requirements for the Kafka writer for now.

**Comment by pavolloffay** [comment]
Closing this ticket, the support for this will be introduced with Jaeger based on OpenTelemetry.
