### ISSUE TITLE
Files based storage backend for Jaeger tracing

### ISSUE THREAD

**Issue by SwarnimRaj** [jaegertracing/jaeger#894]
Requirement - We have a project use case where we need to store Jaeger traces but not have extra dependencies installed like Cassandra or Elasticsearch in the system. Hence we need a simple files based storage backend so that data persists unlike in memory based current implementation.

Problem - The current archive API requires a storage backend like Cassandra and as we cannot install extra software, we need to create a new files based storage backend. Also, the memory based implementation threatens to make the system run out of memory if Jaeger tracing keeps running continuously for days.

Proposal - I could implement the functionality by providing for an additional storage type "files" that writes and reads spans from json files which store the spans against a TraceID, in form of a map[string][]*model.Span. The json files would rotate after they cross a size threshold and older files would be removed so as to not exceed storage footprint. It can be used by all who would prefer a storage backend but without having extra softwares to maintain.

**Comment by yurishkuro** [comment]
There is already similar work with Badger KV #760

**Comment by jpkrohling** [comment]
@SwarnimRaj: as @yurishkuro mentioned, your idea is really valid and there's already some work going on via #760. You are more than welcome to help review/test that PR. 

I'm closing this issue, but if you think there's still value in having this even after #760, feel free to reopen, including some use cases that can't be covered by the other options.
