### ISSUE TITLE
Error when create span with Zipkin compatible endpoint

### ISSUE THREAD

**Issue by longit644** [jaegertracing/jaeger#895]
I use endpoint ` http://localhost:9411/api/v2/spans` for creating spans with request body:

```json
[
    {
        "traceId": "9aa46f78b4afbd37e6845ba62313d51d",
        "localEndpoint": null,
        "id": "ec270a5446cd8a68",
        "name": "request",
        "kind": "SERVER",
        "remoteEndpoint": {
            "ipv4": "127.0.0.1",
            "port": 47580
        },
        "duration": 2000,
        "timestamp": 1.530259357671e+15
    }
]
```

I got an error: `Unable to process request body: json: cannot unmarshal number 1.530259357671e+15 into Go struct field Span.timestamp of type int64`

Jaeger version: `jaegertracing/all-in-one:1.4.0` on Docker.

Steps to reproduce:
```bash
curl -ivX POST -H "Content-Type: application/json" localhost:9411/api/v2/spans -d @spans.json

```
[spans.txt](https://github.com/jaegertracing/jaeger/files/3411529/spans.txt)

**Comment by yurishkuro** [comment]
I doubt we'll be able to solve this, since this error is coming from standard Go JSON decoding. I think Go expects the number to be an integer value, not a floating point, e.g. if I replace it with equivalent integer, the parsing works: https://play.golang.org/p/N7PYsxkPx0y

What library are you using that generates this JSON?

**Comment by bnlong4417** [comment]
I got this error when I try to integrate Kong Zipkin Plugin(https://github.com/Kong/kong-plugin-zipkin) to Jaeger backend.

Kong Zipkin Plugin plugin uses `cjson` to generate JSON. 

I think we can use `json.Number` instead of `int64`.

**Comment by yurishkuro** [comment]
Yeah, seems feasible. Would you like to try to create a pull request?

**Comment by pavolloffay** [comment]
I have submitted #1671 with a potential fix. However it does change auto generated file from zipkin open API definition.

The instrumentations should report timestamp as `int64` and not `float` as the zipkin schema defines https://github.com/openzipkin/zipkin-api/blob/master/zipkin2-api.yaml#L421.

I would close this and re-evaluate if there are more instrumentations reporting timestamps as floats.

**Comment by pavolloffay** [comment]
I am closing this, if there are more instrumentations sending timestamp in float format, we can reevaluate.
