### ISSUE TITLE
Jaeger client for Lua

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#898]
@ldeveloperl1985 https://github.com/jaegertracing/jaeger/issues/366#issuecomment-401012559 :

> is there any Lua client or any other way to use jaeger in Lua language?

@isaachier :

> that largely depends on whether or not OpenTracing decides to support Lua. Also, the issue of many different dialects makes the situation much more difficult. Which version of Lua do you use? Is it original Lua or LuaJIT?

@ldeveloperl1985 :

> I've used kong 0.11v. which uses Lua 5.1 and LuaJIT 2.1.0

@isaachier :

> Kong is probably the primary use case. I am not familiar with that version, but does it support 64 bit integers? My problem is maintaining compatibility across several versions of Lua.

@ldeveloperl1985 :

> You can easily maintain compatibility across several versions of LUA. Lua is a dynamically typed language. There are no type definitions in the language; each value carries its own type.

@isaachier :

> That is much easier said than done. I know for a fact that 64 bit integers are only supported in >= 5.3. Also, I believe the C API has inconsistencies across minor versions and LuaJIT.

**Comment by yurishkuro** [comment]
Cf: https://github.com/Kong/Kong-plugin-zipkin.

**Comment by isaachier** [comment]
I think @rbtcollins @ror6ax might be interested in this conversation too.

**Comment by rbtcollins** [comment]
Thanks @isaachier - we are. We're currently using the nginx c++ module and poking around inside it from lua, which is not the most straightforward thing to do.

**Comment by bobrik** [comment]
There's this: https://github.com/opentracing/lua-bridge-tracer

**Comment by yurishkuro** [comment]
Per #3362, we're sunsetting Jaeger clients.
