### ISSUE TITLE
cannot use v (type *"github.com/spf13/viper".Viper) as type *"github.com/jaegertracing/jaeger/vendor/github.com/spf13/viper".Viper

### ISSUE THREAD

**Issue by JaryZhen** [jaegertracing/jaeger#907]
go version
go version go1.10.3 darwin/amd64

` go run ./cmd/agent/main.go
 command-line-arguments
cmd/agent/main.go:40:34: cannot use v (type *"github.com/spf13/viper".Viper) as type *"github.com/jaegertracing/jaeger/vendor/github.com/spf13/viper".Viper in argument to flags.TryLoadConfigFile
cmd/agent/main.go:45:50: cannot use v (type *"github.com/spf13/viper".Viper) as type *"github.com/jaegertracing/jaeger/vendor/github.com/spf13/viper".Viper in argument to new(flags.SharedFlags).InitFromViper
cmd/agent/main.go:46:59: cannot use "go.uber.org/zap".NewProductionConfig() (type "go.uber.org/zap".Config) as type "github.com/jaegertracing/jaeger/vendor/go.uber.org/zap".Config in argument to sFlags.NewLogger
cmd/agent/main.go:52:25: cannot use v (type *"github.com/spf13/viper".Viper) as type *"github.com/jaegertracing/jaeger/vendor/github.com/spf13/viper".Viper in argument to builder.InitFromViper
cmd/agent/main.go:70:36: cannot use version.Command() (type *"github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra".Command) as type *"github.com/spf13/cobra".Command in argument to command.AddCommand
cmd/agent/main.go:72:17: cannot use v (type *"github.com/spf13/viper".Viper) as type *"github.com/jaegertracing/jaeger/vendor/github.com/spf13/viper".Viper in argument to config.AddFlags
cmd/agent/main.go:72:17: cannot use command (type *"github.com/spf13/cobra".Command) as type *"github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra".Command in argument to config.AddFlags `

**Comment by yurishkuro** [comment]
This is an issue with your GOPATH / env setup. Please see CONTRIBUTING.md for setting up the project for build from source.
