### ISSUE TITLE
Unable to launch jaeger agent

### ISSUE THREAD

**Issue by ishankaronline** [jaegertracing/jaeger#910]
Hi there,

I am trying to start collector, UI and agent separately so that I can use Cassandra as storage. I was able to start the collector successfully, but I am unable to launch the agent - it says "Not enough connected peers". Any help would be greatly appreciated. 

`sudo docker run --rm -p6831:6831/udp -p5575:5575/udp -p5778:5778 -p6832:6832/udp jaegertracing/jaeger-agent /go/bin/agent-linux --collector.host-port=jaeger-collector:14267`

```
{"level":"info","ts":1530779517.829974,"caller":"tchannel/builder.go:89","msg":"Enabling service discovery","service":"jaeger-collector"}
{"level":"info","ts":1530779517.830177,"caller":"peerlistmgr/peer_list_mgr.go:111","msg":"Registering active peer","peer":"jaeger-collector:14267"}
{"level":"info","ts":1530779517.833645,"caller":"agent/main.go:62","msg":"Starting agent"}
{"level":"info","ts":1530779518.8340466,"caller":"peerlistmgr/peer_list_mgr.go:157","msg":"Not enough connected peers","connected":0,"required":1}
{"level":"info","ts":1530779518.8341284,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"jaeger-collector:14267"}
{"level":"error","ts":1530779519.0847886,"caller":"peerlistmgr/peer_list_mgr.go:171","msg":"Unable to connect","host:port":"jaeger-collector:14267","connCheckTimeout":0.25,"error":"tchannel error ErrCodeTimeout: timeout","stacktrace":"github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).ensureConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:171\ngithub.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).maintainConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:101"}
```

Thank you in advance!

**Comment by jpkrohling** [comment]
Is your Agent able to resolve the host `jaeger-collector` ? You can try that by running a command like this:

```
$ docker run -it busybox ping jaeger-collector
```

For better troubleshooting, join our Gitter channel: https://gitter.im/jaegertracing/Lobby

**Comment by ishankaronline** [comment]
Yeah... it says: ping: bad address 'jaeger-collector'

This is how I run my collector:
**sudo docker run -it --rm -p14267:14267 -p14268:14268  jaegertracing/jaeger-collector /go/bin/collector-linux --cassandra.keyspace=jaeger_v1_test --cassandra.servers=172.17.0.2 --cassandra.username=cassandra --cassandra.password=cassandra**

_{"level":"info","ts":1530755599.2690523,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":14269,"status":"unavailable"}
{"level":"info","ts":1530755599.8199978,"caller":"cassandra/factory.go:92","msg":"Cassandra archive storage configuration is empty, skipping"}
{"level":"info","ts":1530755599.8424366,"caller":"static/strategy_store.go:77","msg":"No sampling strategies provided, using defaults"}
{"level":"info","ts":1530755599.844296,"caller":"collector/main.go:141","msg":"Registering metrics handler with HTTP server","route":"/metrics"}
{"level":"info","ts":1530755599.844659,"caller":"collector/main.go:149","msg":"Starting Jaeger Collector HTTP server","http-port":14268}
{"level":"info","ts":1530755599.845158,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}_

Thanks!

**Comment by jpkrohling** [comment]
> Yeah... it says: ping: bad address 'jaeger-collector'

Then your problem is with your Docker networking, not Jaeger. Please, refer to the Docker documentation on how to link containers. For instance, if you start your collector with `--name=jaeger-collector`, you should start the Agent with a command like this:

```
docker run \
  --rm \
  -p6831:6831/udp \
  -p5575:5575/udp \
  -p5778:5778 \
  -p6832:6832/udp \
  --link jaeger-collector:jaeger-collector
  jaegertracing/jaeger-agent \
  /go/bin/agent-linux --collector.host-port=jaeger-collector:14267
```
https://docs.docker.com/network/links/

I'm closing this issue, as it's not related to Jaeger. If you think a documentation page on our side can be improved, please open an issue under the repository https://github.com/jaegertracing/documentation .

**Comment by yurishkuro** [comment]
> if you start your collector with `--name=jaeger-collector`

that's exactly what seems to be missing in @ishankaronline 's command line

**Comment by jpkrohling** [comment]
That's one thing that is missing. The other part is the `--link`.

**Comment by ishankaronline** [comment]
Thanks @yurishkuro @jpkrohling!
