### ISSUE TITLE
Dependency Graph don't show when storage is elasticsearch

### ISSUE THREAD

**Issue by candyleer** [jaegertracing/jaeger#913]
## Problem - what in Jaeger blocks you from solving the requirement?

when the strorage is elasticseach ,the dependency graph didn't show as expected,but the default storage cassandra

**Comment by yurishkuro** [comment]
Did you run the aggregation job?

https://www.jaegertracing.io/docs/deployment/#AggregationJobsforServiceDependencies

**Comment by jpkrohling** [comment]
Yes, that's the one.

**Comment by candyleer** [comment]
thanks for your answer

**Comment by jpkrohling** [comment]
I'm closing this issue, but if you still have problems in obtaining the service graph to be displayed or if you have problems with the Spark job, feel free to reopen this issue.

**Comment by laniakea1990** [comment]
@jpkrohling I run the spark job, and have below log:
INFO ElasticsearchDependciesJob: Running Dependencies job for 2018-12-05T00:00Z, reading from jaeger-span-2018-12-05 index, result storing to jaeger-dependencies-2018-12-05/dependencies
WARN NativeCodeLoader: Unable to load native-hadoop library for your platform...using builtin-java classes where applicable
It does not generate the dependencies index, the ES has index "jaeger-span-2018-12-05"

**Comment by koushik9951** [comment]
HI,

Can someone let me know, how we can run the dependencies jar as a distributed way? as my index is having a high volume of data, I tried with a single instance of the jar, but its taking days of time to process.
like mentioning the shards or running multiple instances of the jar with a single index name .. will this approach works?

**Comment by candyleer** [comment]
@koushik9951  I dont use this feature in production for the same reason, data is huge😄

**Comment by pavolloffay** [comment]
To run it in a distributed way it requires spark cluster. Then you provide a connection to your spark master when running the job https://github.com/jaegertracing/spark-dependencies#configuration

**Comment by yurishkuro** [comment]
fyi https://github.com/jaegertracing/jaeger-analytics/issues/5
