### ISSUE TITLE
Make Go client support JAEGER_ENDPOINT env var and use it in hotrod

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#920]
Per https://github.com/jaegertracing/jaeger/pull/915#discussion_r200855019

I think a cleaner approach is to change Go client to respect JAEGER_ENDPOINT env var, similar to Java client, which would allow configuring either UDP or HTTP reporter from env vars only, without adding extra flags to the HotROD binary.

- [x] Go client to respect JAEGER_ENDPOINT
- [ ] Update HotROD to remove extra flags

**Comment by danehans** [comment]
@yurishkuro I would like to work on this issue.

**Comment by yurishkuro** [comment]
@danehans go for it! Thanks!

**Comment by eundoosong** [comment]
Hello, is there any plan to release the next version of go-client including https://github.com/jaegertracing/jaeger-client-go/pull/323 ?

Because I've been working on `Update HotROD to remove extra flags` and almost done.
But the latest version(v2.14.0) of go client doesn't have JAEGER_ENDPOINT.

**Comment by black-adder** [comment]
@eundoosong 2.15 is out
