### ISSUE TITLE
Proposal: rename jaeger-standalone to jaeger-all-in-one

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#932]
The docker image is labeled `all-in-one` but we call the executable `jaeger-standalone` and that's how it is included in the binary distributions. I propose we change the executable to be called all-in-one as well.

We can probably even rename the source directory to `cmd/all-in-one`, since the package name there is `main` anyway.

**Comment by black-adder** [comment]
let's keep releasing `jaeger-standalone` until we release 2.0? I'm pretty sure there are people who are directly using `all-in-one`.

**Comment by yurishkuro** [comment]
everyone should be using versioned releases, so if we rename it in 1.7 it's not going to break anyone unless people explicitly upgrade.

**Comment by yurishkuro** [comment]
> everyone should be using versioned releases

Specifically, we're talking about renaming the binary, which you can ONLY download from a concrete version (unlike Docker images where we, mistakenly, published tag "1")

**Comment by jpkrohling** [comment]
Funny, I thought about opening an issue some time ago about this, but in the other direction: instead of "all-in-one", standardizing on "standalone".

**Comment by yurishkuro** [comment]
I think picking one name is more important than which name, but I think all-in-one is a bit more accurate and, more importantly, backwards compatible - there are many blog posts that refer to it already.

**Comment by jpkrohling** [comment]
For the record, I have nothing against `all-in-one`. I just find it easier to type "standalone" instead :-)

**Comment by Dieterbe** [comment]
:thumbsup:
