### ISSUE TITLE
Are validations on the Cassandra configuration object necessary?

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#935]
The validation tags on the Cassandra configuration file seem to have limited utility because there seems to be no validator specified (e.g. https://github.com/go-validator/validator)

If we do specify a validator, it renders some of the default configuration values useless, because it forces users to specify Connections Per Host, Keyspace, etc. 

I propose removing these validation tags because they are currently unused. 

https://github.com/jaegertracing/jaeger/blob/67352afacb33716d75e42a3f437605ce20ef0f75/pkg/cassandra/config/config.go#L29-L40

**Comment by yurishkuro** [comment]
I suspect they are used in our internal builds using our internal x-config

**Comment by vprithvi** [comment]
>I suspect they are used in our internal builds using our internal x-config

This is accurate, I'll discuss this usage with you privately

**Comment by yurishkuro** [comment]
will work better in v2
