### ISSUE TITLE
Support "service" tag

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#936]
Rebooking from https://github.com/jaegertracing/jaeger-client-java/issues/490.

## Requirement - what kind of business use case are you trying to solve?

OpenTracing specification added service tags: https://github.com/opentracing/specification/commit/f7ca62c911b47cdc2a0b07298f75fe3ad9b0b6eb

## Problem - what in Jaeger blocks you from solving the requirement?

There's no special handing for the `service` tag in Jaeger right now.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add an adjuster (https://github.com/jaegertracing/jaeger/tree/master/model/adjuster) that will read the `service` tag from the span and update the `span.process.serviceName` field.

## Any open questions to address

As I mentioned (https://github.com/opentracing/specification/issues/77#issuecomment-380544025) previously, Jaeger tracers use multiple attributes in the Process object to identify the service. The `service` tag only overrides the service name, but attributes like `process.tags["ip"]` will be set to the IP of the process creating the span (e.g. a service mesh). This might be confusing when looking at the traces in the UI, or worse it could affect some other logic like the clock skew adjustment.

**Comment by jpkrohling** [comment]
cc @mustafaakin it's yours, if you want to work on it :)

**Comment by mustafaakin** [comment]
I am working on it @jpkrohling thanks!

**Comment by quaff** [comment]
Any updates?

**Comment by pavolloffay** [comment]
The referenced PR mostly changes OT API. The processing on the server side would be probably similar/the same as what we have previously discussed here. The open question is what tag will we use as the proposed API allows to use basically an arbitrary tag.

**Comment by yurishkuro** [comment]
The service tag has been pulled out of OT Spec.
