### ISSUE TITLE
HotRod doesn't work properly for me.

### ISSUE THREAD

**Issue by AnsQihong** [jaegertracing/jaeger#939]
I use the plain Jaeger executable without docker on Windows 7 at this moment. I started the Jaeger standalone(all in one) then the hotrod with parameter all. In Jaeger UI, I could see frontend service of hotrod and show it's tracing information.   On the web page of frontend, I could see four buttons representing four customers. But if I clicked it, I only saw something like `Dispatching a car...[req: 7484-1]`. On console running hotrod, there was Error log printed out:
```
...INFO log/spanlogger.go:34  HTTP request received "service": "frontend", "method": "GET", "url": "dispatch?customer=567&nonse=0.308099110858462275}
... INFO log/spanlogger.go:34  Getting customer  {"service": "frontend",  "component": "customer_client", "customer_id": "567"}
... ERROR log/spanlogger.go:39  request failed {"service": "frontend", "error": "403 Forbidden"}
```

On Jaeger UI/dependencies tab, I was supposed to see a service dependency diagram. But I only saw the text "No service dependencies found."

**Comment by yurishkuro** [comment]
`"403 Forbidden"` is quite strange - any more details?  Is your firewall blocking ports?

**Comment by AnsQihong** [comment]
The plain executable release doesn't include  any configuration file for the hotrod. Is this a problem? I found the default port(8081) of customer server was actually used by the Mcafee virus scanner. This might be the reason of "403 Forbidden".  There might be a pitfall in hotrod. When a port was bind by other program previously, it didn't report an error. I tried to start the customer with -p 8085, then I started the frontend. There seemed not way to let frontend know customer was listening on 8085. I was not sure whether hotrod already implemented any service discovery, so the frontend could detect the new port used by the customer. However, I still saw the same error.

**Comment by AnsQihong** [comment]
Thanks for the response. I had to switch to another machine whose 8081 was not used by any program, then hotrod and jaeger backend worked properly. Since support running hotrod as multiple processes has been created. I'll close this one.
