### ISSUE TITLE
Support running HotROD as multiple processes

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#948]
## Requirement - what kind of business use case are you trying to solve?

As was raised in https://github.com/jaegertracing/jaeger/issues/939#issuecomment-406476388, when one of the ports used by HotROD is already taken on the host, there's no real way to run HotROD from executables (only from Docker image).

## Problem - what in Jaeger blocks you from solving the requirement?

While the HotROD allows running each of the microservices separately, it does not provide the ability to configure their ports so that each component can find the other components.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add command line flags for port number for each of the microservices in HotROD.

**Comment by cboornaz17** [comment]
I'd like to give this one a shot this week. If you could give a little more clarity on exactly how the flags should work that would be great.
