### ISSUE TITLE
Kafka configuration example

### ISSUE THREAD

**Issue by yrsh** [jaegertracing/jaeger#955]
As I see, according https://github.com/jaegertracing/jaeger/pull/880 now it is possible to use kafka as storage, but how?

## Requirement - what kind of business use case are you trying to solve?
Use kafka as primary storage.

## Problem - what in Jaeger blocks you from solving the requirement?
There is no docs about it. Only for elastic and cassandra as storage backend here:
https://www.jaegertracing.io/docs/deployment/

**Comment by vprithvi** [comment]
It is possible to use Kafka as a write only storage. We expect storage
forwarding to Cassandra/ES and read functionality to be available in the
coming weeks. Documentation for Kafka use is being tracked at
https://github.com/jaegertracing/documentation/issues/90

**Comment by jjcollinge** [comment]
@vprithvi - I had a quick scan of the code. Am I right in thinking you can't currently pass more complex [sarama](https://github.com/Shopify/sarama) configuration through yet such as SASL authentication etc? I'm looking to use this integration with [Azure's Event Hubs Kafka API](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview) and require to override some of the default configurations. Is this something in flight or would you welcome a PR if I can find time to add it?

**Comment by jjcollinge** [comment]
I do still intend to finish this (I have the code ready) - I'm just waiting on a bug fix in the service so I can properly test.

**Comment by pavolloffay** [comment]
Docs can be found at https://www.jaegertracing.io/docs/1.18/deployment/#kafka
