### ISSUE TITLE
Make clock skew adjustment transparent

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#961]
## Requirement - what kind of business use case are you trying to solve?

It is currently not obvious in Jaeger UI is the span timestamps were adjusted for clock skew. @tedsuo wrote:

> The issue was that displaying “manipulated” data, however well intentioned, led users to mistrust what they were seeing in some cases. “Is this 'real data' or is this ‘corrected data’?" was becoming a common question when looking at odd display patterns, or patterns that did not match other data sources. Given that we usually could not “correct” most scenarios properly but could only place the spans into a sort of “best guess” situation, we decided it would be better to avoid confusion and always show raw data, with visual annotations to point out where we felt the raw data was suspicious. So the main issue is trust, and retaining the ability to triage raw data. Another approach would be to give users a toggle to turn off the corrections so they can quickly see the raw data.
> 
> As an example, there were situations where clock correction was actually covering up issues, or subtly moving spans in a way which “looked right” but developers knew were impossible. For example, in one case there was a batch processing workload where the clock correction subtly moved things to make it look like the map/reduce phases were slightly overlapping in impossible ways. Other cases were where incorrect instrumentation lead to “incoceivable” child spans, but the source was not clock skew - that child span really was offset in a crazy way!

## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger clock skew adjustment is not recorded anywhere in the adjusted spans. UI does not make it obvious that the timestamps were adjusted.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

* [x] Clock skew adjuster should record the delta in the adjusted span
* [x] Jaeger UI should display a warning in the span details (and/or some other visual cue) that the span was adjusted
* [ ] Jaeger UI should provide a toggle to view the unadjusted trace (the `/api/trace` endpoint already allows retrieving unadjusted trace)

## Any open questions to address

How to do a visual cue that the span is adjusted.

**Comment by felippe-mendonca** [comment]
I had the same problem as exposed [here](https://github.com/jaegertracing/jaeger-client-java/issues/192). It took some time do figure out if the problem was mine or not. Because of that I think that could be interesting to have a mix between the second and third proposal: when displaying adjusted trace, warn the user about that.

**Comment by cameronbraid** [comment]
Is there any way to make the UI run without the clock skew adjuster ? 

It is leading to incorrect representations of spans, shifting spans by hundreds of milliseconds in some cases.

<img width="820" alt="screen shot 2019-01-14 at 7 04 40 pm" src="https://user-images.githubusercontent.com/672405/51101598-647db400-182f-11e9-929f-b8a8b48d2710.png">

should be as follows

<img width="630" alt="screen shot 2019-01-14 at 7 06 56 pm" src="https://user-images.githubusercontent.com/672405/51101659-9ee75100-182f-11e9-9cac-36c8cd8bb02d.png">

**Comment by cameronbraid** [comment]
It turns out that the root cause of this was the root span (in blue in first image) finishing too soon.  So the Clock Skew adjuster assumed that this was a clock skew issue masking the real problem.

**Comment by cameronbraid** [comment]
Actually , even with that fixed I get the same problem when the root span is on one server and the child spans on another server, I get the following

<img width="1673" alt="screen shot 2019-01-14 at 7 50 40 pm 1" src="https://user-images.githubusercontent.com/672405/51103141-cb05d080-1835-11e9-8f65-ceb251c6f0eb.png">

The `response-transformer` span starts after the `proxy-request` span finishes and yet it always displays like this

**Comment by cameronbraid** [comment]
With the clock skew adjuster disabled it looks like this, which is exactly what I expect

<img width="1675" alt="screen shot 2019-01-14 at 8 00 49 pm" src="https://user-images.githubusercontent.com/672405/51103538-38663100-1837-11e9-8824-5cdbfc5feea6.png">

I don't want the UI to shift the spans in time to balance the 'latency' before and after it to be the same, that is just incorrect.

**Comment by yurishkuro** [comment]
I agree. We already have an API call that returns "raw" trace, without adjustments. We just need a UI enhancement to use that API call to display the trace view.

**Comment by flixr** [comment]
I'm also running into this problem...
Is there any way to turn off the adjustment globally?

**Comment by dhulchuk** [comment]
> I'm also running into this problem...
> Is there any way to turn off the adjustment globally?

We use next workaround for this problem:
You can set ip param in all traces to constant, so clock adjustment will be ignored for all new traces.

**Comment by dhulchuk** [comment]
<img width="1102" alt="Screen Shot 2019-11-07 at 16 46 07" src="https://user-images.githubusercontent.com/46413718/68399060-72b20d80-017e-11ea-8a49-8117950b8f7b.png">

**Comment by bobrik** [comment]
I opened #2052 to add a warning similar to what you can see in the comment above.

**Comment by bobrik** [comment]
@yurishkuro, I think you can tick two first boxes in the issue description after #2052.

**Comment by yurishkuro** [comment]
I believe this issue is resolved by #2052 and #2119.

**Comment by flixr** [comment]
Just asking as it was part of the proposed solution: There are no plans anymore to add a toggle to view the unadjusted trace in the UI?

**Comment by yurishkuro** [comment]
There is still an open ticket https://github.com/jaegertracing/jaeger-ui/issues/197 for that.
