### ISSUE TITLE
Zipkin HTTP Endpoint Does Not Correctly Parse Content-Type Header

### ISSUE THREAD

**Issue by netshade** [jaegertracing/jaeger#963]
## Requirement - what kind of business use case are you trying to solve?

Post Zipkin traces from an Android client (okhttp).

## Problem - what in Jaeger blocks you from solving the requirement?

The Zipkin HTTP handler [incorrectly uses the full text of the `Content-Type` header](https://github.com/jaegertracing/jaeger/blob/53955e348810c9d119bda87fc99951dd73603319/cmd/collector/app/zipkin/http_handler.go#L84-L90) as a means of ascertaining whether the request uses `application/json`. A valid `Content-Type` header may be a [`media-type`](https://tools.ietf.org/html/rfc7231#section-3.1.1.1), a la `application/json; charset=utf8` which would fail the direct comparison in the linked code.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Adjust `Content-Type` detection in the various endpoints to correctly parse a `media-type` following the [specification](https://tools.ietf.org/html/rfc7231#section-3.1.1.1).

**Comment by yurishkuro** [comment]
we can use https://golang.org/pkg/mime/#ParseMediaType
