### ISSUE TITLE
Is 'jaeger_cassandra_errors' count cumulated ?

### ISSUE THREAD

**Issue by xihw** [jaegertracing/jaeger#965]
I get jaeger_cassandra_errors{table="traces"} 51000 from /metrics endpoint, is the 51000 cumulated number ? Could you explain a bit how this number is generated ?
Wondering does it make more sense to emit a rate value ?

**Comment by jpkrohling** [comment]
@xihw I'm closing this, as I believe this has been answered properly. If you still have questions about this, feel free to reopen.
