### ISSUE TITLE
Version incompatibility during upgrade to 1.6

### ISSUE THREAD

**Issue by ledor473** [jaegertracing/jaeger#966]
## Requirement - what kind of business use case are you trying to solve?
Upgrade safely each component from one version to the other.

## Problem - what in Jaeger blocks you from solving the requirement?
Usually upgrading Jaeger is pretty smooth but I had an issue with the latest version (1.6). 
We were running version 1.4.1 on Query and Collector. Collector is sending the data to an Elasticsearch (5.x).

For this upgrade, I started by upgrading the Collectors to 1.6. Once they were started, I went in Query to validate if the traces were still flowing correctly. Query was returning the following error when trying to find new traces:
```
HTTP Error: Converting JSONSpan to domain Span failed: strconv.ParseUint: parsing "": invalid syntax
```

I assume the issue is caused by this PR: https://github.com/jaegertracing/jaeger/pull/831

Upgrading the Query component to 1.6 **fixed** that issue and no traces were lost as expected.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
- Maybe there could be a "Breaking Change" section in the Release Note?
- Should we define an upgrade order for each release (I'd rather we avoid that honestly)?
- Should we have an automated test for that kind of upgrade 
  - In this case, I was upgrading from 1.4 to 1.6. That being said I could have done 1.4 to 1.5 and 1.5 to 1.6 and probably hit the same problem

## Any open questions to address
We run different Jaeger Agent versions (afaik they all are >= 1.2), if there's a breaking change between the Agents and the Collectors we would likely loss traces. 
From your knowledge, is there any breaking change that are planned or happened in the past?

**Comment by yurishkuro** [comment]
Partial duplicate of https://github.com/jaegertracing/documentation/issues/117

**Comment by ledor473** [comment]
@yurishkuro I totally missed that issue because it's in the documentation project.

The error message in this issue might be useful to someone doing the upgrade but I have no objection if we merge this issue with the one you've mentioned.

**Comment by ledor473** [comment]
Sounds good! I've renamed the issue so it's more about that specific problem.

The rest can be done in jaegertracing/documentation#117
