### ISSUE TITLE
How to store data in ES with all-in-one docker image?

### ISSUE THREAD

**Issue by Yisaer** [jaegertracing/jaeger#971]
Hi，i'm using `docker.io/jaegertracing/all-in-one:1.5` docker image and I know set `SPAN_STORAGE_TYPE` as `elasticsearch` in `env` but i didn't find how to set `ES_HOSTS`.

Can you tell me how to set `ES Store` with `docker.io/jaegertracing/all-in-one:1.5`  image?

**Comment by yurishkuro** [comment]
`--es.server-urls` or `ES_SERVER_URLS`

**Comment by yurishkuro** [comment]
`SPAN_STORAGE_TYPE=elasticsearch go run ./cmd/standalone/main.go help`

**Comment by pavolloffay** [comment]
@Yisaer you can join https://gitter.im/jaegertracing/Lobby to ask questions.
