### ISSUE TITLE
Spanstore does not support store warnings

### ISSUE THREAD

**Issue by yancl** [jaegertracing/jaeger#976]
## Requirement - what kind of business use case are you trying to solve?

The jaeger-ui can't fetch warnings from span to promote user something unnormal happens

## Problem - what in Jaeger blocks you from solving the requirement?

the spanstore data model doesn't have `warnings` in its schema, so it ignore the warnings 
[dbmodel.Span](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/spanstore/dbmodel/model.go#L39) doesn't match [model.Span](https://github.com/jaegertracing/jaeger/blob/master/model/model.pb.go#L253)

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I am not sure whether my understanding is right about the `warnings`'s purpose. so i think we should either remove the warnings field from model.Span or add a field to dbmodel.Span to support warning.

**Comment by black-adder** [comment]
Hi there,

jaeger will store spans as is without altering them in anyway. Warnings only come into play during reads. Whenever a trace is fetched for reading, we sanitize and massage the trace and add warnings; this means we don't need to persist the warnings.

The reason why warnings are only added during reads is that during ingestion, we store spans as they arrive. We don't have the complete trace until read time, at which time we can apply our sanitizers to the entire trace, not just spans.

**Comment by yancl** [comment]
Thanks @black-adder , got it, very clear. 

BTW, is there any way to tell the jaeger ui to render some span more clearly(the red color, for example) to catch attention when some warning(rpc call timeout, for example) or error happens? after all, there may be hundreds of spans in one trace show.

**Comment by yurishkuro** [comment]
@yancl Jaeger shows red exclamation point next to the span that contains the error=true tag. If the span is not visible because the parent is collapsed, the exclamation sigh bubbles up to the closest visible parent.

![image](https://user-images.githubusercontent.com/3523016/44070137-2d73fa94-9f50-11e8-82bd-baaadb50fb47.png)

If you would like a different visualization, please open a ticket in the jaeger-ui repo and make suggestions to start a discussion.

**Comment by yancl** [comment]
It looks great to me with the current visualization, thanks.
