### ISSUE TITLE
Add authentication to collector HTTP endpoint

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger#981]
## Requirement - what kind of business use case are you trying to solve?

Unless I'm missing something, it seems like the clients can already add username/passport when reporting spans via http. However, we never open sourced the actual HTTP handler authentication. @vprithvi I remember you added the auth handler internally, did we just forget to move it over?

**Comment by jpkrohling** [comment]
You are not missing anything. We added this for people who are using auth proxies in front of the collector. See https://medium.com/jaegertracing/protecting-jaeger-ui-with-an-oauth-sidecar-proxy-34205cca4bb1

**Comment by black-adder** [comment]
ahhh, somehow missed that. Thanks!
