### ISSUE TITLE
Upgrade TChannel

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#983]
We're on very old version 1.1.0, the latest is 1.11.0

As a minor point, glide is complaining
```
[WARN]	Conflict: github.com/stretchr/testify rev is currently ^v1.2.1, but github.com/uber/tchannel-go wants master
```
(the latest tchannel is not on master of testify, but on ^1.1)

**Comment by pavolloffay** [comment]
Can this be closed? `tchannel` is going to be removed in https://github.com/jaegertracing/jaeger/issues/2105

**Comment by pavolloffay** [comment]
Closing this as tchannel will be removed
