### ISSUE TITLE
Performance tests - storage backends

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#990]
As a continuation of #989, we also want to exercise a common set of options against different storage backends: 

* Cassandra
* Elasticsearch
* Kafka
* in-memory
* Any other "supported" backend that might be available at the time of the test

In order to get comparable results, everything should remain the same except the backend configuration. A tricky part is factoring out the network latency from the results, but there are some techniques for that.

Once we have good results about "same everything, different backend", we might also want to compare the same backend with different configuration options, so that we get to know what's the best set of options for a given storage. For instance, Kafka might perform better with more workers and smaller queue size, whereas ES might need a bigger queue size.

**Comment by yurishkuro** [comment]
old issue
