### ISSUE TITLE
Prepare for graduation at CNCF

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#994]
We are coming up to the anniversary of Jaeger joining CNCF ([9/13/2017](https://lists.cncf.io/g/cncf-toc/topic/8008347#1209)) at incubation stage, and it seems we're ready for graduation.

From https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc:

## Have committers from at least two organizations.

✅ We have 2 regular committers from Red Hat and 4 from Uber.

## Have achieved and maintained a Core Infrastructure Initiative Best Practices Badge.

✅ We have some gaps, but overall get a passing grade: https://bestpractices.coreinfrastructure.org/en/projects/1273

## Adopt the CNCF Code of Conduct.

✅ https://github.com/jaegertracing/jaeger/blob/master/CODE_OF_CONDUCT.md

## Explicitly define a project governance and committer process. 

> This preferably is laid out in a GOVERNANCE.md file and references an OWNERS.md file showing the current and emeritus committers.

we have
  * ✅ governance: https://github.com/jaegertracing/jaeger/blob/master/GOVERNANCE.md and
  * ✅ and owners: https://github.com/jaegertracing/jaeger/blob/master/CODEOWNERS

## Have a public list of project adopters for at least the primary repo

✅ https://github.com/jaegertracing/jaeger/blob/master/ADOPTERS.md

@caniszczyk :
  * do we need a presentation to the TOC or just an offline voting & a pull request (like [fluentd graduation](https://github.com/cncf/toc/pull/69))?
  * any outstanding legal issues? We still haven't transferred the jaegertracing.io domain name to CNCF.

**Comment by jpkrohling** [comment]
> Have achieved and maintained a Core Infrastructure Initiative Best Practices Badge

About this one, the only item missing IIRC is to document the external interfaces ( #456 ). I think we don't have any public external interfaces, so, it might be OK to set this as "non applicable". It all depends on how do we see the Query endpoints: I've seen comments in a few issues saying that this is internal and might change, but I've also us pointing users to some non-official documentation (or directly to the code).

**Comment by yurishkuro** [comment]
I think we do want public API for query service, as it provides better extensibility that external users have asked for, as you mentioned. But according to the tool/badge it's ok not to have this item satisfied and still have a passing grade. I think ultimately it will be up to CNCF TOC.

A fix for FOSSA would also be nice (#854).

**Comment by jpkrohling** [comment]
> I think we do want public API for query service

I'll add "not applicable" for now, as I understand that we don't have a supported external interface, but we want one for the future.

**Comment by jpkrohling** [comment]
Actually, I'll add "met", as most of the interaction we have with application developers is via the OpenTracing API, which is well documented. We also have JavaDocs with explanation on how to extend the client with the available SPIs (Sender/MetricsFactory).

**Comment by jstoja** [comment]
Did you guys have any feedback on this?

**Comment by jpkrohling** [comment]
Yes! It's being tracked here: https://github.com/cncf/toc/pull/171

**Comment by yurishkuro** [comment]
The TOC has voted in favor of Jaeger graduation! 🎉 🎉 🎉 🎈🎈🎈 

https://www.cncf.io/announcement/2019/10/31/cloud-native-computing-foundation-announces-jaeger-graduation/
