### ISSUE TITLE
[Conceptual question] jarger-agent behavior on out of memory

### ISSUE THREAD

**Issue by maniaabdi** [jaegertracing/jaeger#997]
Hello every one 

I was wondering How jaeger-agent behaves if it runs out of memory. Assumes I only have 100MB of memory and jaeger-agent consumes all of it. How does it behave on upcoming traces? Is it dropping old-traces who has not been sent to collector and make room for new ones? Is it blocking new traces? What is the policy in such situation.

Bests
Mania

**Comment by isaachier** [comment]
I am not 100% but I believe OOM in a Go program results in a panic. AFAIK, we (perhaps intentionally) do not recover from this panic. Nor would we have a clear idea of how to handle such a panic given that Go's runtime handles memory usage. In Go, I believe this is the standard practice. Please correct me if I am mistaken.
